### ISSUE TITLE
AOA3进入传送门报错：Colliding entity with block

### ISSUE THREAD

**Issue by strange-qwq** [IzzelAliz/Arclight#101]
控制台输出：
`
[20:45:39] [Server thread/FATAL] [minecraft/ThreadTaskExecutor]: Error executing task on Server
net.minecraft.crash.ReportedException: Colliding entity with block
        at net.minecraft.entity.Entity.func_213315_a(EntityMixin.java:565) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:entity.EntityMixin,pl:mixin:A,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.network.play.ServerPlayNetHandler.func_147347_a(ServerPlayNetHandlerMixin.java:1880) ~[?:?] {re:mixin,re:classloading,pl:mixin:APP:mixins.arclight.core.json:network.play.ServerPlayNetHandlerMixin,pl:mixin:A}
        at net.minecraft.network.play.client.CPlayerPacket.func_148833_a(SourceFile:122) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
        at net.minecraft.network.play.client.CPlayerPacket$PositionRotationPacket.func_148833_a(SourceFile:18) ~[?:?] {re:classloading}
        at net.minecraft.network.PacketThreadUtil.mda6fc18$lambda$checkThreadAndEnqueue$0$0(PacketThreadUtilMixin.java:536) ~[?:?] {re:mixin,re:classloading,pl:mixin:APP:mixins.arclight.core.json:network.PacketThreadUtilMixin,pl:mixin:A}
        at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18) ~[?:?] {re:classloading}
        at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144) [?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
        at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) [?:?] {re:mixin,re:classloading}
        at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServerMixin.java:731) [?:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServerMixin.java:141) [?:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118) [?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
        at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServerMixin.java:714) [?:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServerMixin.java:708) [?:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213161_c(SourceFile:127) [?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
        at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServerMixin.java:694) [?:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.run(MinecraftServerMixin.java:1978) [?:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,pl:mixin:A,pl:runtimedistcleaner:A}
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_275] {}
Caused by: java.lang.NullPointerException
        at net.minecraft.entity.player.ServerPlayerEntity.changeDimension(ServerPlayerEntityMixin.java:1740) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:entity.player.ServerPlayerEntityMixin,pl:mixin:A,re:mixin,pl:accesstransformer:B}
        at net.tslat.aoa3.block.functional.portal.PortalBlock.func_196262_a(PortalBlock.java:196) ~[?:3.4.2-1.15.2] {re:classloading,pl:runtimedistcleaner:A}
        at net.minecraft.block.BlockState.func_196950_a(BlockStateMixin.java:257) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:mixins.arclight.core.json:block.BlockStateMixin,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.entity.Entity.func_145775_I(EntityMixin.java:815) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:entity.EntityMixin,pl:mixin:A,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.entity.Entity.func_213315_a(EntityMixin.java:560) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:entity.EntityMixin,pl:mixin:A,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        ... 16 more
[20:45:39] [Server thread/WARN] [minecraft/MinecraftServer]: Can't keep up! Is the server overloaded? Running 2797ms or 55 ticks behind
[20:45:39] [Server thread/WARN] [minecraft/ServerWorld]: Force-added player with duplicate UUID 8f81b865-a67e-36a3-b161-f08e77c7c304
[20:45:39] [Server thread/WARN] [minecraft/NetworkSystem]: Failed to handle packet for /192.168.2.2:51815
net.minecraft.crash.ReportedException: Colliding entity with block
        at net.minecraft.entity.player.ServerPlayerEntity.func_71127_g(ServerPlayerEntityMixin.java:424) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:entity.player.ServerPlayerEntityMixin,pl:mixin:A,re:mixin,pl:accesstransformer:B}
        at net.minecraft.network.play.ServerPlayNetHandler.func_73660_a(ServerPlayNetHandlerMixin.java:183) ~[?:?] {re:mixin,re:classloading,pl:mixin:APP:mixins.arclight.core.json:network.play.ServerPlayNetHandlerMixin,pl:mixin:A}
        at net.minecraft.network.NetworkManager.func_74428_b(NetworkManagerMixin.java:228) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:network.NetworkManagerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:135) [?:?] {re:classloading,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServerMixin.java:866) [?:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServerMixin.java:330) [?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.dedicated.DedicatedServerMixin,pl:mixin:A}
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServerMixin.java:784) [?:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.run(MinecraftServerMixin.java:1974) [?:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,pl:mixin:A,pl:runtimedistcleaner:A}
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_275] {}
Caused by: java.lang.NullPointerException
        at net.minecraft.entity.player.ServerPlayerEntity.changeDimension(ServerPlayerEntityMixin.java:1740) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:entity.player.ServerPlayerEntityMixin,pl:mixin:A,re:mixin,pl:accesstransformer:B}
        at net.tslat.aoa3.block.functional.portal.PortalBlock.func_196262_a(PortalBlock.java:199) ~[?:3.4.2-1.15.2] {re:classloading,pl:runtimedistcleaner:A}
        at net.minecraft.block.BlockState.func_196950_a(BlockStateMixin.java:257) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:mixins.arclight.core.json:block.BlockStateMixin,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.entity.Entity.func_145775_I(EntityMixin.java:815) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:entity.EntityMixin,pl:mixin:A,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.entity.Entity.func_213315_a(EntityMixin.java:560) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:entity.EntityMixin,pl:mixin:A,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.entity.LivingEntity.func_213352_e(LivingEntityMixin.java:1889) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:entity.LivingEntityMixin,pl:mixin:A,pl:arclight_implementer:async,pl:arclight_implementer:A,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.entity.player.PlayerEntity.func_213352_e(PlayerEntityMixin.java:1531) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:entity.player.PlayerEntityMixin,pl:mixin:A,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.entity.LivingEntity.func_70636_d(LivingEntityMixin.java:2289) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:entity.LivingEntityMixin,pl:mixin:A,pl:arclight_implementer:async,pl:arclight_implementer:A,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.entity.player.PlayerEntity.func_70636_d(PlayerEntityMixin.java:507) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:entity.player.PlayerEntityMixin,pl:mixin:A,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntityMixin.java:2104) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:entity.LivingEntityMixin,pl:mixin:A,pl:arclight_implementer:async,pl:arclight_implementer:A,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.entity.player.PlayerEntity.func_70071_h_(PlayerEntityMixin.java:233) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:entity.player.PlayerEntityMixin,pl:mixin:A,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.entity.player.ServerPlayerEntity.func_71127_g(ServerPlayerEntityMixin.java:361) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:entity.player.ServerPlayerEntityMixin,pl:mixin:A,re:mixin,pl:accesstransformer:B}
        ... 8 more
[20:45:39] [Server thread/WARN] [minecraft/NetworkSystem]: Failed to handle packet for /192.168.2.2:51815
net.minecraft.crash.ReportedException: Colliding entity with block
        at net.minecraft.entity.player.ServerPlayerEntity.func_71127_g(ServerPlayerEntityMixin.java:424) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:entity.player.ServerPlayerEntityMixin,pl:mixin:A,re:mixin,pl:accesstransformer:B}
        at net.minecraft.network.play.ServerPlayNetHandler.func_73660_a(ServerPlayNetHandlerMixin.java:183) ~[?:?] {re:mixin,re:classloading,pl:mixin:APP:mixins.arclight.core.json:network.play.ServerPlayNetHandlerMixin,pl:mixin:A}
        at net.minecraft.network.NetworkManager.func_74428_b(NetworkManagerMixin.java:228) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:network.NetworkManagerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:135) [?:?] {re:classloading,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServerMixin.java:866) [?:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServerMixin.java:330) [?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.dedicated.DedicatedServerMixin,pl:mixin:A}
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServerMixin.java:784) [?:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.run(MinecraftServerMixin.java:1974) [?:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,pl:mixin:A,pl:runtimedistcleaner:A}
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_275] {}
Caused by: java.lang.NullPointerException
        at net.minecraft.entity.player.ServerPlayerEntity.changeDimension(ServerPlayerEntityMixin.java:1740) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:entity.player.ServerPlayerEntityMixin,pl:mixin:A,re:mixin,pl:accesstransformer:B}
        at net.tslat.aoa3.block.functional.portal.PortalBlock.func_196262_a(PortalBlock.java:192) ~[?:3.4.2-1.15.2] {re:classloading,pl:runtimedistcleaner:A}
        at net.minecraft.block.BlockState.func_196950_a(BlockStateMixin.java:257) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:mixins.arclight.core.json:block.BlockStateMixin,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.entity.Entity.func_145775_I(EntityMixin.java:815) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:entity.EntityMixin,pl:mixin:A,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.entity.Entity.func_213315_a(EntityMixin.java:560) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:entity.EntityMixin,pl:mixin:A,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.entity.LivingEntity.func_213352_e(LivingEntityMixin.java:1889) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:entity.LivingEntityMixin,pl:mixin:A,pl:arclight_implementer:async,pl:arclight_implementer:A,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.entity.player.PlayerEntity.func_213352_e(PlayerEntityMixin.java:1531) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:entity.player.PlayerEntityMixin,pl:mixin:A,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.entity.LivingEntity.func_70636_d(LivingEntityMixin.java:2289) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:entity.LivingEntityMixin,pl:mixin:A,pl:arclight_implementer:async,pl:arclight_implementer:A,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.entity.player.PlayerEntity.func_70636_d(PlayerEntityMixin.java:507) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:entity.player.PlayerEntityMixin,pl:mixin:A,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntityMixin.java:2104) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:entity.LivingEntityMixin,pl:mixin:A,pl:arclight_implementer:async,pl:arclight_implementer:A,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.entity.player.PlayerEntity.func_70071_h_(PlayerEntityMixin.java:233) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:entity.player.PlayerEntityMixin,pl:mixin:A,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.entity.player.ServerPlayerEntity.func_71127_g(ServerPlayerEntityMixin.java:361) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:entity.player.ServerPlayerEntityMixin,pl:mixin:A,re:mixin,pl:accesstransformer:B}
        ... 8 more
[20:45:39] [Server thread/WARN] [minecraft/NetworkSystem]: Failed to handle packet for /192.168.2.2:51815
net.minecraft.crash.ReportedException: Colliding entity with block
        at net.minecraft.entity.player.ServerPlayerEntity.func_71127_g(ServerPlayerEntityMixin.java:424) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:entity.player.ServerPlayerEntityMixin,pl:mixin:A,re:mixin,pl:accesstransformer:B}
        at net.minecraft.network.play.ServerPlayNetHandler.func_73660_a(ServerPlayNetHandlerMixin.java:183) ~[?:?] {re:mixin,re:classloading,pl:mixin:APP:mixins.arclight.core.json:network.play.ServerPlayNetHandlerMixin,pl:mixin:A}
        at net.minecraft.network.NetworkManager.func_74428_b(NetworkManagerMixin.java:228) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:network.NetworkManagerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:135) [?:?] {re:classloading,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServerMixin.java:866) [?:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServerMixin.java:330) [?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.dedicated.DedicatedServerMixin,pl:mixin:A}
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServerMixin.java:784) [?:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.run(MinecraftServerMixin.java:1974) [?:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,pl:mixin:A,pl:runtimedistcleaner:A}
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_275] {}
Caused by: java.lang.NullPointerException
        at net.minecraft.entity.player.ServerPlayerEntity.changeDimension(ServerPlayerEntityMixin.java:1740) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:entity.player.ServerPlayerEntityMixin,pl:mixin:A,re:mixin,pl:accesstransformer:B}
        at net.tslat.aoa3.block.functional.portal.PortalBlock.func_196262_a(PortalBlock.java:189) ~[?:3.4.2-1.15.2] {re:classloading,pl:runtimedistcleaner:A}
        at net.minecraft.block.BlockState.func_196950_a(BlockStateMixin.java:257) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:mixins.arclight.core.json:block.BlockStateMixin,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.entity.Entity.func_145775_I(EntityMixin.java:815) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:entity.EntityMixin,pl:mixin:A,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.entity.Entity.func_213315_a(EntityMixin.java:560) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:entity.EntityMixin,pl:mixin:A,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.entity.LivingEntity.func_213352_e(LivingEntityMixin.java:1889) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:entity.LivingEntityMixin,pl:mixin:A,pl:arclight_implementer:async,pl:arclight_implementer:A,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.entity.player.PlayerEntity.func_213352_e(PlayerEntityMixin.java:1531) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:entity.player.PlayerEntityMixin,pl:mixin:A,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.entity.LivingEntity.func_70636_d(LivingEntityMixin.java:2289) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:entity.LivingEntityMixin,pl:mixin:A,pl:arclight_implementer:async,pl:arclight_implementer:A,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.entity.player.PlayerEntity.func_70636_d(PlayerEntityMixin.java:507) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:entity.player.PlayerEntityMixin,pl:mixin:A,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntityMixin.java:2104) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:entity.LivingEntityMixin,pl:mixin:A,pl:arclight_implementer:async,pl:arclight_implementer:A,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.entity.player.PlayerEntity.func_70071_h_(PlayerEntityMixin.java:233) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:entity.player.PlayerEntityMixin,pl:mixin:A,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.entity.player.ServerPlayerEntity.func_71127_g(ServerPlayerEntityMixin.java:361) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:entity.player.ServerPlayerEntityMixin,pl:mixin:A,re:mixin,pl:accesstransformer:B}
        ... 8 more

`

**Comment by IzzelAliz** [comment]
请填写模板
