### ISSUE TITLE
[1.20.1] MythicMobs插件不兼容，启动报错

### ISSUE THREAD

**Issue by luoxiawuchen** [IzzelAliz/Arclight#1014]
### 请确认您已完成以下几件事

- [X] 正在使用最新的 Arclight
- [X] 已为所有插件及模组安装依赖
- [X] 已为所有插件及模组更新至最新版
- [X] 不可在 Spigot 复现
- [X] 不可在 Forge 复现

### Arclight 版本

arclight-1.20.1-1.0.0-SNAPSHOT-5a54db3

### Java 版本 | 操作系统

window10 64x JDK17

### 相关 Mod/插件 的名称及版本

```raw
插件：MythicMobs 
下载链接：https://mythiccraft.io/index.php?pages/official-mythicmobs-download/&version=5.3.0
模组：未添加
```

### 错误描述

MM怪物插件载入时报错【完整报错已上传至链接】，提示：[Minecraft]: Error occurred while enabling MythicMobs v5.3.2-SNAPSHOT-52fe5620 (Is it up to date?)
java.lang.NoClassDefFoundError: org/bukkit/craftbukkit/v1_20_R1/util/CraftLegacy

世界载入完毕后，无限报错，提示：
[00:24:36 ERROR] [MythicMobs]: [EVENTS] Exception thrown whilst handling event: org.bukkit.event.world.EntitiesLoadEvent
[00:24:36 ERROR] [STDERR]: java.lang.NullPointerException: Cannot invoke "io.lumine.mythic.core.mobs.MobExecutor.getVanillaType(io.lumine.mythic.api.mobs.entities.MythicEntityType)" because the return value of "io.lumine.mythic.bukkit.MythicBukkit.getMobManager()" is null
[00:24:36 ERROR] [STDERR]:      at io.lumine.mythic.bukkit.listeners.MobListeners.lambda$load$6(MobListeners.java:285)
[00:24:36 ERROR] [STDERR]:      at io.lumine.mythic.bukkit.utils.Delegates$ConsumerToBiConsumerSecond.accept(Delegates.java:144)
[00:24:36 ERROR] [STDERR]:      at io.lumine.mythic.bukkit.utils.events.functional.single.EventListener.execute(EventListener.java:131)
[00:24:36 ERROR] [STDERR]:      at TRANSFORMER/arclight@1.20.1-1.0.0-SNAPSHOT-5a54db3/org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[00:24:36 ERROR] [STDERR]:      at TRANSFORMER/arclight@1.20.1-1.0.0-SNAPSHOT-5a54db3/org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589)
[00:24:36 ERROR] [STDERR]:      at TRANSFORMER/arclight@1.20.1-1.0.0-SNAPSHOT-5a54db3/org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576)
[00:24:36 ERROR] [STDERR]:      at TRANSFORMER/arclight@1.20.1-1.0.0-SNAPSHOT-5a54db3/org.bukkit.craftbukkit.v.event.CraftEventFactory.callEntitiesLoadEvent(CraftEventFactoryMixin.java:1767)
[00:24:36 ERROR] [STDERR]:      at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.level.entity.PersistentEntitySectionManager.handler$bfa000$arclight$fireLoad(PersistentEntitySectionManagerMixin.java:581)
[00:24:36 ERROR] [STDERR]:      at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.level.entity.PersistentEntitySectionManager.m_157582_(PersistentEntitySectionManagerMixin.java:263)
[00:24:36 ERROR] [STDERR]:      at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.level.entity.PersistentEntitySectionManager.m_157506_(PersistentEntitySectionManagerMixin.java:269)
[00:24:36 ERROR] [STDERR]:      at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.level.ServerLevel.m_8793_(ServerLevelMixin.java:355)
[00:24:36 ERROR] [STDERR]:      at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_5703_(MinecraftServerMixin.java:895)
[00:24:36 ERROR] [STDERR]:      at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServerMixin.java:273)
[00:24:36 ERROR] [STDERR]:      at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_5705_(MinecraftServerMixin.java:816)
[00:24:36 ERROR] [STDERR]:      at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_130011_(MinecraftServerMixin.java:2072)
[00:24:36 ERROR] [STDERR]:      at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_206580_(MinecraftServerMixin.java:251)
[00:24:36 ERROR] [STDERR]:      at java.base/java.lang.Thread.run(Thread.java:833)

### 复现步骤

1、安装插件，启动服务器
2、报错，无法使用

### 报错信息

https://paste.ubuntu.com/p/WhBWTr2TxT/

**Comment by IzzelAliz** [comment]
上游 SrgUtils 的问题
