### ISSUE TITLE
The MMOCore plugin is not supported in 1.18.2

### ISSUE THREAD

**Issue by Ru-Nan-i** [IzzelAliz/Arclight#1019]
### I have confirmed that ...

- [X] Arclight is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Forge

### Arclight version

arclight-forge-1.18.2-1.0.8

### OS & Java versions

java version "17.0.6"

### Plugins and Mods

```raw
MMOCore 1.11.3
MythicLib 1.5.2
```

### Description

After putting MMOCore and MythicLib in the plugins folder on the server, they do not respond to related commands and do not work. It's not responding, but you can see the You can see that the MMOCore plugin has been applied. It looks like you need "Include javax inject for mmocore".

### Step to reproduce

1. Put MMOCore and MythicLib into the plugins folder.
2. Check server logs

### Logs

[00:28:29 ERROR] [Minecraft]: Error occurred while enabling MMOCore v1.11.3 (Is it up to date?)
java.lang.NoClassDefFoundError: javax/inject/Provider
        at net.Indyuce.mmocore.party.PartyModuleType.<clinit>(PartyModuleType.java:11) ~[?:?]
        at net.Indyuce.mmocore.MMOCore.onEnable(MMOCore.java:208) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPluginMixin.java:264) ~[arclight-1.18.2-1.0.8-e80a33d2.jar%2369!/:arclight-1.18.2-1.0.8-e80a33d2]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoaderMixin.java:342) ~[arclight-1.18.2-1.0.8-e80a33d2.jar%2369!/:arclight-1.18.2-1.0.8-e80a33d2]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[arclight-1.18.2-1.0.8-e80a33d2.jar%2369!/:arclight-1.18.2-1.0.8-e80a33d2]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServerMixin.java:518) ~[arclight-1.18.2-1.0.8-e80a33d2.jar%2369!/:arclight-1.18.2-1.0.8-e80a33d2]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServerMixin.java:432) ~[arclight-1.18.2-1.0.8-e80a33d2.jar%2369!/:arclight-1.18.2-1.0.8-e80a33d2]
        at net.minecraft.server.MinecraftServer.handler$zbj000$arclight$enablePlugins(MinecraftServerMixin.java:2217) ~[server-1.18.2-20220404.173914-srg.jar%2374!/:?]
        at net.minecraft.server.MinecraftServer.m_129815_(MinecraftServerMixin.java:403) ~[server-1.18.2-20220404.173914-srg.jar%2374!/:?]
        at net.minecraft.server.MinecraftServer.m_130006_(MinecraftServerMixin.java:316) ~[server-1.18.2-20220404.173914-srg.jar%2374!/:?]
        at net.minecraft.server.dedicated.DedicatedServer.m_7038_(DedicatedServerMixin.java:173) ~[server-1.18.2-20220404.173914-srg.jar%2374!/:?]
        at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServerMixin.java:2099) ~[server-1.18.2-20220404.173914-srg.jar%2374!/:?]
        at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServerMixin.java:261) ~[server-1.18.2-20220404.173914-srg.jar%2374!/:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.ClassNotFoundException: javax.inject.Provider
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoaderMixin.java:147) ~[arclight-1.18.2-1.0.8-e80a33d2.jar%2369!/:arclight-1.18.2-1.0.8-e80a33d2]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoaderMixin.java:99) ~[arclight-1.18.2-1.0.8-e80a33d2.jar%2369!/:arclight-1.18.2-1.0.8-e80a33d2]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        ... 14 more

**Comment by chasiopen** [comment]
I met same problem.
