### ISSUE TITLE
在Linux上运行旧版本的GlobalMarketPlus出现验证错误

### ISSUE THREAD

**Issue by McAZero** [IzzelAliz/Arclight#1020]
### 请确认您已完成以下几件事

- [X] 正在使用最新的 Arclight
- [X] 已为所有插件及模组安装依赖
- [X] 已为所有插件及模组更新至最新版
- [X] 不可在 Spigot 复现
- [X] 不可在 Forge 复现

### Arclight 版本

arclight-forge-1.18.2-1.0.9-SNAPSHOT.jar

### Java 版本 | 操作系统

openjdk version "17.0.5" 2022-10-18 LTS | Ubuntu20.04

### 相关 Mod/插件 的名称及版本

```raw
GlobalMarketPlus v1.1.6.3
```

### 错误描述

![image](https://github.com/IzzelAliz/Arclight/assets/52328924/f61138f1-b6a0-4fbf-9fee-33dcaef9716c)
每次插件更新后 如果不能及时更新插件就会出现验证错误报错 导致有时候崩溃重启无法及时更新插件时无法加载插件 
purpur1.18.2和隔壁猫端不会出现 好像只会在Linux中报错 Windows11测试不会（左猫，右螺）

### 报错信息

[20:48:03 INFO] [GlobalMarketPlus]: Disabling GlobalMarketPlus v1.1.6.3
[20:48:03 ERROR] [Minecraft]: Error occurred (in the plugin loader) while disabling GlobalMarketPlus v1.1.6.3 (Is it up to date?)
java.lang.IllegalStateException: PluginDisableEvent cannot be triggered asynchronously from another thread.
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:572) ~[arclight-1.18.2-1.0.9-SNAPSHOT-87c9caa.jar%2369!/:arclight-1.18.2-1.0.9-SNAPSHOT-87c9caa]
        at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoaderMixin.java:361) ~[arclight-1.18.2-1.0.9-SNAPSHOT-87c9caa.jar%2369!/:arclight-1.18.2-1.0.9-SNAPSHOT-87c9caa]
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:501) ~[arclight-1.18.2-1.0.9-SNAPSHOT-87c9caa.jar%2369!/:arclight-1.18.2-1.0.9-SNAPSHOT-87c9caa]
        at studio.trc.bukkit.globalmarketplus.n.j.e(Unknown Source) ~[?:?]
        at studio.trc.bukkit.globalmarketplus.m.i.a(Unknown Source) ~[?:?]
        at studio.trc.bukkit.globalmarketplus.m.i.b(Unknown Source) ~[?:?]
        at studio.trc.bukkit.globalmarketplus.m.i.d(Unknown Source) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
[20:48:03 INFO] [Console]: GlobalMarketPlus >>> 未授权的插件，请重新下载本插件或联系插件作者。(或是尝试将插件更新到最新版本)

**Comment by IzzelAliz** [comment]
“未授权的插件，请重新下载本插件或联系插件作者。(或是尝试将插件更新到最新版本)”

你要不要试一试这句话提到的几个方法

**Comment by McAZero** [comment]
> “作者未授权的插件，请重新下载本插件或联系插件。（或者尝试将插件更新到最新版本）”
> 
> 你不要尝试一试这提到的几个方法

找过了，作者说不是插件的问题。。用其他端启动也不会这样

**Comment by IzzelAliz** [comment]
这个报错，没有任何可能不是插件的问题
