### ISSUE TITLE
1.20.1在使用PixelPlayerWorld创建世界时出错

### ISSUE THREAD

**Issue by BasinM** [IzzelAliz/Arclight#1039]
### I have confirmed that ...

- [X] Arclight is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Forge

### Arclight version

arclight-forge-1.20.1-1.0.0-SNAPSHOT

### OS & Java versions

Windows server 2022,jdk17

### Plugins and Mods

```raw
PixelPlayerWorld
```

### Description

22:25:19 WARN] [PixelPlayerWorld]: Task #552 for PixelPlayerWorld v3.1.0-beta generated an exception
java.lang.IllegalAccessError: class org.bukkit.craftbukkit.v1_20_R1.CraftServer tried to access method 'void net.minecraft.server.dedicated.DedicatedServerProperties$WorldDimensionData.<init>(com.google.gson.JsonObject, java.lang.String)' (org.bukkit.craftbukkit.v1_20_R1.CraftServer is in module arclight@1.20.1-1.0.0-SNAPSHOT-1eb0af5 of loader 'TRANSFORMER' @1b24ea2a; net.minecraft.server.dedicated.DedicatedServerProperties$WorldDimensionData is in module minecraft@1.20.1 of loader 'TRANSFORMER' @1b24ea2a)
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.createWorld(CraftServerMixin.java:1119) ~[arclight-1.20.1-1.0.0-SNAPSHOT-1eb0af5.jar%23193!/:arclight-1.20.1-1.0.0-SNAPSHOT-1eb0af5]
        at org.bukkit.Bukkit.createWorld(Bukkit.java:703) ~[arclight-1.20.1-1.0.0-SNAPSHOT-1eb0af5.jar%23193!/:arclight-1.20.1-1.0.0-SNAPSHOT-1eb0af5]
        at com.xbaimiao.template.world.World$createLocalNormalWorld$1$1$1.invoke(World.kt:133) ~[?:?]
        at com.xbaimiao.template.world.World$createLocalNormalWorld$1$1$1.invoke(World.kt:127) ~[?:?]
        at com.xbaimiao.template.shadow.easylib.module.utils.BukkitKt$submit$runnable$2$2.run(Bukkit.kt:45) ~[?:?]
        at com.xbaimiao.template.shadow.easylib.task.EasyLibBukkitTask$bukkitRunnable$1.run(EasyLibBukkitTask.kt:16) ~[?:?]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:82) ~[arclight-1.20.1-1.0.0-SNAPSHOT-1eb0af5.jar%23193!/:arclight-1.20.1-1.0.0-SNAPSHOT-1eb0af5]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftSchedulerMixin.java:415) ~[arclight-1.20.1-1.0.0-SNAPSHOT-1eb0af5.jar%23193!/:arclight-1.20.1-1.0.0-SNAPSHOT-1eb0af5]
        at net.minecraft.server.MinecraftServer.handler$zei000$arclight$runScheduler(MinecraftServerMixin.java:2309) ~[server-1.20.1-20230612.114412-srg.jar%23225!/:?]
        at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServerMixin.java) ~[server-1.20.1-20230612.114412-srg.jar%23225!/:?]
        at net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServerMixin.java:273) ~[server-1.20.1-20230612.114412-srg.jar%23225!/:?]
        at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServerMixin.java:814) ~[server-1.20.1-20230612.114412-srg.jar%23225!/:?]
        at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServerMixin.java:2070) ~[server-1.20.1-20230612.114412-srg.jar%23225!/:?]
        at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServerMixin.java:251) ~[server-1.20.1-20230612.114412-srg.jar%23225!/:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

### Step to reproduce

ppw: https://www.mcbbs.net/thread-1449338-1-1.html

创建世界

**Comment by IzzelAliz** [comment]
Please test if it is fixed.
