### ISSUE TITLE
After server start some plugins don't work

### ISSUE THREAD

**Issue by OneWorldStudio** [IzzelAliz/Arclight#1055]
### I have confirmed that ...

- [x] Arclight is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [x] unable to reproduce in Forge

### Arclight version

arclight-1.20.1-1.0.0-053d747

### OS & Java versions

java version 17.0.7 by Eclipse Adoptium; OS Linux arch amd64 version 5.15.0-75-generic

### Plugins and Mods

```raw
[17:54:32 INFO] [Console]: Plugins (105): CustomizablePlayerModels, NBTAPI, LuckPerms, CommandDefender, ItemSwapperPlugin, NocsyItems, LoneLibs, ProtocolLib, MVdWPlaceholderAPI, CinematicStudio, PlaceholderAPI, PlayTime, MTBackpack, Polymart, VenturaCalendar, RewardSystem, RedeemableCodes, DisableJoinMessage, PhysicsControl, FJetpack2Reloaded, LicenseManager, RoyaleEconomy, Vault, HolographicDisplays, PlasmoVoice, CMILib, Contracts, TAB, RPGMarketPlace, CalendarEvents, BeaconPlus3, WorldEdit, Essentials, RewardsLite, HeadDatabase, Arceon, WorldGuard, DeluxeBazaar, EssentialsSpawn, DecentHolograms, HeadBlocks, Citizens, RegionPlaceholders, AuctionMaster, CitizensGUI, DarkAuctionsX, EliteMobs, SuperiorSkyblock2, Multiverse-Core, AdvancedChests, Shopkeepers, Confiscate, MythicMobs, TheAssistant, MythicAchievements, TheCollections, AriKeys, SkinsRestorer, MTAutopickup, MythicCrucible, ajLeaderboards, Codex, LeaderMobs, ItemJoin, ModelEngine, MythicLib, MMOItems, CommandPanels, TradeSystem, RPGInventory, CustomFishing, SCore, ExecutableEvents, ExecutableItems, CustomPiglinsTrades, PlayerProfile, CustomCrops, Resources, MythicDungeons, AdvancedEnchantments, ItemsAdder, MagicCosmetics, FancyWaystones, AquaticCrates, DeluxeMenus, Machines, ExecutableBlocks, MagicGestures, eco, EcoItems, EcoArmor, Boosters, EcoBosses, EcoEnchants, EcoSkills, Actions, EcoBits, Jobs, Talismans, EcoPets, BetonQuest, Reforges, PlugManX (PlugMan), libreforge, DungeonParties

[17:54:55 INFO]: Mod List: 
• mods_folder SmartBrainLib-forge-1.20-1.11.jar : smartbrainlib (1.11) - 1
• mods_folder puffish_skills-0.5.0-1.20-forge.jar : puffish_skills (0.5.0) - 1
• mods_folder open-parties-and-claims-forge-1.20.1-0.19.1.jar : openpartiesandclaims (0.19.1) - 1
• mods_folder geckolib-forge-1.20.1-4.2.1.jar : geckolib (4.2.1) - 1
• mods_folder player-animation-lib-forge-1.0.2-rc1+1.20.jar : playeranimator (1.0.2-rc1+1.20) - 1
• mods_folder obscure_api-15.jar : obscure_api (15) - 1
• mods_folder sophisticatedcore-1.20.1-0.5.82.383.jar : sophisticatedcore (1.20.1-0.5.82.383) - 1
• mods_folder ElytraPhysicsForge-1.3-1.20.1.jar : elytra_physics (1.3) - 1
• mods_folder citadel-2.4.2-1.20.1.jar : citadel (2.4.2) - 1
• mods_folder alexsmobs-1.22.5-1.20.1.jar : alexsmobs (1.22.5) - 1
• JarInJar mixinextras-forge-0.2.0-beta.9.jar : mixinextras (0.2.0-beta.9) - 1
• mods_folder spawnermod-1.20.1-1.9.3+Forge.jar : spawnermod (1.9.3) - 1
• mods_folder CraterLib-forge-1.20-1.0.1.jar : craterlib (1.0.1) - 1
• mods_folder sophisticatedbackpacks-1.20.1-3.18.56.890.jar : sophisticatedbackpacks (1.20.1-3.18.56.890) - 1
• mods_folder moremobheads-0.2.1-1.20.1.jar : moremobheads (0.2.1-1.20.1) - 1
• mods_folder azurelib-neoforge-1.20.1-1.0.19.jar : azurelib (1.0.19) - 1
• mods_folder genshinstrument-1.20.1-3.1.1 (1).jar : genshinstrument (3.1.1) - 1
• mods_folder cloth-config-11.1.106-forge.jar : cloth_config (11.1.106) - 1
• minecraft forge-1.20.1-47.1.1-universal.jar : forge (47.1.1) - 1
• mods_folder rotl-4.5-1.20.1-forge.jar : uncraftable (4.5) - 1
• mods_folder supplementaries-1.20-2.5.21.jar : supplementaries (1.20-2.5.21) - 1
• mods_folder konkrete_forge_1.6.1-2_MC_1.20.jar : konkrete (1.6.1) - 1
• mods_folder athena-forge-1.20.1-3.0.0 (1).jar : athena (3.0.0) - 1
• mods_folder friendsandfoes-forge-mc1.20.1-1.9.3.jar : friendsandfoes (1.9.3) - 1
• mods_folder chipped-forge-1.20.1-3.0.1.jar : chipped (3.0.1) - 1
• minecraft server-1.20.1-20230612.114412-srg.jar : minecraft (1.20.1) - 1
• mods_folder handcrafted-forge-1.20-2.3.2.jar : handcrafted (2.3.2) - 1
• mods_folder moonlight-1.20-2.7.2-forge (1).jar : moonlight (1.20-2.7.2) - 1
• mods_folder bettercombat-forge-1.7.2+1.20.1.jar : bettercombat (1.7.2+1.20.1) - 1
• mods_folder netherdungeons-1.1.0-alpha1 (1).jar : netherdungeons (1.1.0-alpha1) - 1
• mods_folder 2mal3s-recipes-v1.8.1b.jar : mr_2mal3s_recipes (1-v1.8.1b) - 1
• mods_folder endrem_forge-5.2.3-R-1.20.X.jar : endrem (5.2.3-R-1.20.1) - 1
• mods_folder resourcefulconfig-forge-1.20-2.0.0.jar : resourcefulconfig (2.0.0) - 1
• mods_folder L_Enders_Cataclysm-1.26-1.20.1.jar : cataclysm (1.0) - 1
• mods_folder curios-forge-5.2.0-beta.3+1.20.1.jar : curios (5.2.0-beta.3+1.20.1) - 1
• mods_folder reliquary-1.20.1-2.0.36.1199.jar : reliquary (1.20.1-2.0.36.1199) - 1
• mods_folder Patchouli-1.20.1-81-FORGE.jar : patchouli (1.20.1-81-FORGE) - 1
• mods_folder lootbags-2.0.0-forge.jar : lootbags (2.0.0) - 1
• mods_folder almostunified-forge-1.20.1-0.5.0.jar : almostunified (1.20.1-0.5.0) - 1
• mods_folder Jewelry-1.5.0.jar : jewelcraft (1.5.0) - 1
• mods_folder armourersworkshop-forge-1.20.1-2.0.2.jar : armourers_workshop (2.0.2) - 1
• mods_folder resourcefullib-forge-1.20.1-2.1.6.jar : resourcefullib (2.1.6) - 1
• mods_folder creeperoverhaul-3.0.1-forge.jar : creeperoverhaul (3.0.1) - 1
• mods_folder architectury-9.1.12-forge.jar : architectury (9.1.12) - 1
• mods_folder doapi-1.2.5-forge.jar : doapi (1.2.5) - 2
• mods_folder letsdo-vinery-forge-1.4.1.jar : vinery (1.4.1) - 1
• mods_folder simplyswords-forge-1.50.1-1.20.1.jar : simplyswords (1.50.1-1.20.1) - 1
• mods_folder lootr-1.20-0.7.30.73.jar : lootr (0.7.29.68) - 1
• arclight arclight-1.20.1-1.0.0-053d747.jar : arclight (1.20.1-1.0.0-053d747) - 1
• mods_folder PuzzlesLib-v8.0.13-1.20.1-Forge.jar : puzzleslib (8.0.13) - 1
• mods_folder EnchantingInfuser-v8.0.1-1.20.1-Forge.jar : enchantinginfuser (8.0.1) - 1
• mods_folder aquamirae-6.API15.jar : aquamirae (6.API15) - 1
```

### Description

[17:45:56 WARN] [HyronicSkyblockCore]: Plugin HyronicSkyblockCore v1.6.0-SNAPSHOT generated an exception while executing task 3512
java.lang.NoSuchMethodError: 'org.bukkit.event.player.PlayerResourcePackStatusEvent$Status org.bukkit.entity.Player.getResourcePackStatus()'
        at dev.hyronic.hyronicskyblockcore.tasks.ActionbarTask.lambda$start$0(ActionbarTask.java:33) ~[?:?]
        at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?]
        at java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1092) ~[?:?]
        at dev.hyronic.hyronicskyblockcore.tasks.ActionbarTask.lambda$start$1(ActionbarTask.java:31) ~[?:?]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:82) ~[arclight-1.20.1-1.0.0-053d747.jar%23211!/:arclight-1.20.1-1.0.0-053d747]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[arclight-1.20.1-1.0.0-053d747.jar%23211!/:arclight-1.20.1-1.0.0-053d747]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
        
[29Jul2023 17:43:38.991] [Server thread/ERROR] [STDERR/]: java.lang.ClassCastException: class me.qKing12.RoyaleEconomy.API.Currency cannot be cast to class me.qKing12.RoyaleEconomy.MultiCurrency.Currency (me.qKing12.RoyaleEconomy.API.Currency and me.qKing12.RoyaleEconomy.MultiCurrency.Currency are in unnamed module of loader org.bukkit.plugin.java.PluginClassLoader @14a5751a)
[29Jul2023 17:43:38.991] [Server thread/ERROR] [STDERR/]: 	at com.willfp.eco.internal.spigot.EcoSpigotPlugin.loadIntegrationLoaders$lambda-45(EcoSpigotPlugin.kt:370)
[29Jul2023 17:43:38.991] [Server thread/ERROR] [STDERR/]: 	at com.willfp.eco.core.integrations.IntegrationLoader.load(IntegrationLoader.java:60)
[29Jul2023 17:43:38.991] [Server thread/ERROR] [STDERR/]: 	at com.willfp.eco.core.EcoPlugin.lambda$onEnable$1(EcoPlugin.java:403)
[29Jul2023 17:43:38.991] [Server thread/ERROR] [STDERR/]: 	at java.base/java.util.Arrays$ArrayList.forEach(Arrays.java:4204)
[29Jul2023 17:43:38.991] [Server thread/ERROR] [STDERR/]: 	at com.willfp.eco.core.EcoPlugin.onEnable(EcoPlugin.java:400)
[29Jul2023 17:43:38.991] [Server thread/ERROR] [STDERR/]: 	at TRANSFORMER/arclight@1.20.1-1.0.0-053d747/org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPluginMixin.java:266)
[29Jul2023 17:43:38.991] [Server thread/ERROR] [STDERR/]: 	at TRANSFORMER/arclight@1.20.1-1.0.0-053d747/org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoaderMixin.java:342)
[29Jul2023 17:43:38.991] [Server thread/ERROR] [STDERR/]: 	at TRANSFORMER/arclight@1.20.1-1.0.0-053d747/org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480)
[29Jul2023 17:43:38.991] [Server thread/ERROR] [STDERR/]: 	at TRANSFORMER/arclight@1.20.1-1.0.0-053d747/org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServerMixin.java:544)
[29Jul2023 17:43:38.991] [Server thread/ERROR] [STDERR/]: 	at TRANSFORMER/arclight@1.20.1-1.0.0-053d747/org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServerMixin.java:458)
[29Jul2023 17:43:38.991] [Server thread/ERROR] [STDERR/]: 	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.dedicated.DedicatedServer.handler$zld000$arclight$loadPlugins(DedicatedServerMixin.java:628)
[29Jul2023 17:43:38.991] [Server thread/ERROR] [STDERR/]: 	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.dedicated.DedicatedServer.m_7038_(DedicatedServerMixin.java:156)
[29Jul2023 17:43:38.991] [Server thread/ERROR] [STDERR/]: 	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_130011_(MinecraftServerMixin.java:2028)
[29Jul2023 17:43:38.991] [Server thread/ERROR] [STDERR/]: 	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_206580_(MinecraftServerMixin.java:251)
[29Jul2023 17:43:38.991] [Server thread/ERROR] [STDERR/]: 	at java.base/java.lang.Thread.run(Thread.java:833)

[29Jul2023 17:43:50.089] [Server thread/INFO] [TAB/]: Enabling TAB v4.0.3
[29Jul2023 17:43:50.096] [Server thread/INFO] [Console/]: [TAB] Server version: 1.20.1 (v1_20_R1)
[29Jul2023 17:43:50.145] [Server thread/INFO] [Console/]: [TAB] A compatibility issue with your server was found. Unless you are running some really weird server software, this is a bug.
[29Jul2023 17:43:50.145] [Server thread/INFO] [TAB/]: Disabling TAB v4.0.3

### Step to reproduce

1. Started the server without the plugin error
2. When entering the game everything is like this, as written in the error above

### Logs

[latest.log](https://github.com/IzzelAliz/Arclight/files/12207743/latest.log)

### Server pack link (Optional)

https://www.dropbox.com/scl/fi/0j4bt02ji1ax39k1x3b3g/Desktop.rar?rlkey=lhhx1781yq4t8qr5apin92t6e&dl=0

**Comment by OneWorldStudio** [comment]
??????

**Comment by IzzelAliz** [comment]
For HyronicSkyblockCore, It is possibly this plugin is developed under Paper and is calling a paper only method. Ask the author if they can fix.

For RoyaleEconomy, it is likely a plugin issue, ask the authors too.
