### ISSUE TITLE
在 Arclight 1.19.2 使用 ProtocolLib 进行发 SYSTEM_CHAT 包时出现报错

### ISSUE THREAD

**Issue by ed-3** [IzzelAliz/Arclight#1083]
### 请确认您已完成以下几件事

- [X] 正在使用最新的 Arclight
- [X] 已为所有插件及模组安装依赖
- [X] 已为所有插件及模组更新至最新版
- [X] 不可在 Spigot 复现
- [X] 不可在 Forge 复现

### Arclight 版本

arclight-1.19.2-1.0.2-4a870b30

### Java 版本 | 操作系统

windows 11, jdk-17.0.4

### 相关 Mod/插件 的名称及版本

```raw
模组: 无
插件: AdvancedAnnouncement(我自己的创作的插件)
PlaceholderAPI, ProtocolLib
```

### 错误描述

问题插件: AdvancedAnnouncement
在通过插件向玩家发送 SYSTEM_CHAT 数据包时发生了这个报错
已使用 spigot/paper 1.19.2 进行测试，均未出现此问题

报错内容:
```text
[10:17:14 WARN] [AdvancedAnnouncement]: Plugin AdvancedAnnouncement v1.2.6-release generated an exception while executing task 159
com.comphenix.protocol.reflect.FieldAccessException: Field index 0 is out of bounds for length 0
        at com.comphenix.protocol.reflect.FieldAccessException.fromFormat(FieldAccessException.java:49) ~[?:?]
        at com.comphenix.protocol.reflect.StructureModifier.write(StructureModifier.java:316) ~[?:?]
        at top.ed333.mcplugin.advancedann.bukkit.utils.ProtocolUtils.sendChat(ProtocolUtils.java:45) ~[?:?]
        at top.ed333.mcplugin.advancedann.bukkit.utils.ProtocolUtils.sendChat(ProtocolUtils.java:37) ~[?:?]
        at top.ed333.mcplugin.advancedann.bukkit.announcement.ChatType.lambda$send$0(ChatType.java:40) ~[?:?]
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:82) ~[arclight-1.19.2-1.0.2-4a870b30.jar%23159!/:arclight-1.19.2-1.0.2-4a870b30]
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) [arclight-1.19.2-1.0.2-4a870b30.jar%23159!/:arclight-1.19.2-1.0.2-4a870b30]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
```

相关代码:
![](https://attachment.mcbbs.net/data/myattachment/forum/202308/29/100428yxf0r94dr9xd5q6q.png)

其中对 SERVER_VERSION 的定义为:

```java
private static final short SERVER_VERSION = Short.parseShort(Bukkit.getServer().getBukkitVersion().split("\\.")[1].split("-")[0]);
```

### 复现步骤

1. 安装 [AdvancedAnnouncemet](https://github.com/ed-3/AdvancedAnnouncement/releases/tag/1.2.6-release), PlaceholderAPI, ProtocolLib
2. 启动服务器后加入游戏，执行 /aa display chat_announce_type_example

### 报错信息

[latest.log](https://github.com/IzzelAliz/Arclight/files/12459628/latest.log)
[debug.log](https://github.com/IzzelAliz/Arclight/files/12459630/debug.log)

**Comment by ed-3** [comment]
于是乎我直接抛弃了使用 ProtocolLib 发包的方式改用 `player.spigot().sendmessage()` (

但还是希望作者解决一下这个问题(

**Comment by IzzelAliz** [comment]
spigot 对 system chat 包的修改是直接改字段类型，这个没法修
