### ISSUE TITLE
附魔台无法破坏且放置不消耗

### ISSUE THREAD

**Issue by Coloryr** [IzzelAliz/Arclight#111]
### 我正在运行

* **Arclight** [版本] 
arclight-forge-1.16-1.0.10
* **你确认这是最新版吗** [是]

* **你确认所有Mod都安装了依赖** [是]

* **你确认所有插件都已更新至对应版本** [是]

* **Java** [版本] 
java version "1.8.0_251"
Java(TM) SE Runtime Environment (build 1.8.0_251-b08)
Java HotSpot(TM) 64-Bit Server VM (build 25.251-b08, mixed mode)
* **操作系统** [名称+版本]
Windows Server 2019 标准版
* **插件列表** 
Plugins (27): LuckPerms, RedstoneProximitySensor, PlugMan, DeadSouls, ProtocolLib, LibsDisguises, SkinsRestorer, ShokoNameHide, NBTAPI, Vault, InvisibleItemFrames, WorldEdit, ExplosionRegeneration, Criticals, Multiverse-Core, AuthMe, AuthHide, FastLogin, PlaceholderAPI, CMI, DeluxeChat, Cartographer2, MythicMobs, Minecraft_QQ, CMIEInjector, MMOLib, MMOItems
* **Mod 列表** 
14:07:06] [Server thread/INFO] [minecraft/DedicatedServer]: Mod List: 
? minecraft forge-1.16.4-35.1.4-server.jar : minecraft (1.16.4) - 1
? mods_folder mcw-bridges-1.0.4-mc1.16.4.jar : mcwbridges (1.0.4) - 1
? mods_folder FarmersDelight-1.16.3-0.2.4b.jar : farmersdelight (1.16.3-0.2.4b) - 1
? mods_folder QuarkOddities-1.16.3.jar : quarkoddities (1.16.3) - 1
? mods_folder swingthroughgrass-1.16.4-1.5.3.jar : swingthroughgrass (1.16.4-1.5.3) - 1
? mods_folder torchslabmod-1.16.3_v1.6.18.jar : torchslabmod (1.6.18) - 1
? mods_folder mcw-trapdors-1.0.0-mc1.16.4.jar : mcwtrpdoors (1.0.0) - 1
? mods_folder FallingTree-Forge-1.16.4-2.8.1.jar : falling_tree (2.8.1) - 1
? mods_folder ceilingtorch-1.16.2-v1.8.jar : ceilingtorch (v1.8) - 1
? mods_folder fishingreal-1.16.3-1.0.0.jar : fishingreal (1.0.0) - 1
? mods_folder fairylights-4.0.4-1.16.4.jar : fairylights (4.0.4) - 1
? mods_folder DoggyTalents-1.16.4-2.0.1.1.jar : doggytalents (2.0.1.1) - 1
? mods_folder mcw-windows-1.0.2-mc1.16.4.jar : mcwwindows (1.0.2) - 1
? mods_folder Patchouli-1.16.4-48.jar : patchouli (1.16.4-48) - 1
? mods_folder create-mc1.16.3_v0.3b.jar : create (mc1.16.3_v0.3b) - 1
? mods_folder glassential-forge-1.16.4-1.1.5.jar : glassential (1.1.5) - 1
? mods_folder CookingForBlockheads_1.16.3-9.2.2.jar : cookingforblockheads (9.2.2) - 1
? mods_folder AutoRegLib-1.6-47.jar : autoreglib (1.6-47) - 1
? mods_folder decorative_blocks-1.16.4-1.7.0.jar : decorative_blocks (1.7.0) - 1
? mods_folder CrockPot-1.16.3-1.2.1-release.jar : crockpot (1.2.1-release) - 1
? mods_folder mcws-roofs-2.0.0-mc1.16.4.jar : mcwroofs (2.0.0) - 1
? mods_folder mcw-doors-1.0.1fix-mc1.16.4.jar : mcwdoors (1.0.1) - 1
? mods_folder mapperbase-1.16.4-2.3.0.0.jar : mapperbase (1.16.4-2.3.0.0) - 1
? mods_folder roadstuff-1.16.4-4.2.0.jar : roadstuff (1.16.4-4.2.0) - 1
? mods_folder solcarrot-1.16.3-1.9.8.jar : solcarrot (1.16.3-1.9.8) - 1
? mods_folder walljump-forge-1.16.4-1.3.6.jar : walljump (1.16.4-1.3.6) - 1
? mods_folder SnowRealMagic-1.16.3-2.2.2.jar : snowrealmagic (2.2.2) - 1
? mods_folder Kiwi-1.16.3-3.4.1.jar : kiwi (3.4.1) - 1
? arclight arclight-forge-1.16-1.0.10.jar : arclight (1.16.4-1.0.10-d46a39d) - 1
? mods_folder byg-1.1.5.jar : byg (1.1.5) - 1
? maven_libs forge-1.16.4-35.1.4-universal.jar : forge (35.1.4) - 1
? mods_folder Quark-r2.4-283.jar : quark (r2.4-283) - 1
? mods_folder Aquaculture-1.16.4-2.1.8.jar : aquaculture (1.16.4-2.1.8) - 1
? mods_folder absentbydesign-1.16.4-1.3.0.jar : absentbydesign (1.16.4-1.3.0) - 1
? mods_folder chiselsandbits-0.2.8-RELEASE.jar : chiselsandbits (NONE) - 1

### 错误描述

安装quark的情况下 附魔台无法破坏 且放置时不消耗
叙述这个为什么是一个错误，是哪一方面的，以及其他可能需要的信息

### 重现步骤

1. 安装 xxx
2. 进入服务器后 xxxx
3. ....

**可在 Forge 复现** [是]

**可在 Spigot 复现** [否]

### 报错信息

[错误日志]
<details><pre>
[01һ��2021 13:52:46.443] [Server thread/ERROR] [net.minecraftforge.eventbus.EventBus/EVENTBUS]: Exception caught during firing event: Cannot cast vazkii.quark.addons.oddities.tile.MatrixEnchantingTableTileEntity to net.minecraft.tileentity.EnchantingTableTileEntity
	Index: 1
	Listeners:
		0: NORMAL
		1: ASM: io.izzel.arclight.common.mod.server.event.BlockBreakEventDispatcher@7ec38bd onBreakBlock(Lnet/minecraftforge/event/world/BlockEvent$BreakEvent;)V
		2: ASM: class fr.raksrinana.fallingtree.ForgeEventSubscriber onBlockBreakEvent(Lnet/minecraftforge/event/world/BlockEvent$BreakEvent;)V
		3: ASM: class com.simibubi.create.content.curiosities.tools.DeforesterItem onBlockDestroyed(Lnet/minecraftforge/event/world/BlockEvent$BreakEvent;)V
		4: ASM: vazkii.quark.content.tweaks.module.HoeHarvestingModule@3115aa0e onBlockBroken(Lnet/minecraftforge/event/world/BlockEvent$BreakEvent;)V
		5: LOWEST
		6: ASM: class com.simibubi.create.content.curiosities.symmetry.SymmetryHandler onBlockDestroyed(Lnet/minecraftforge/event/world/BlockEvent$BreakEvent;)V
java.lang.ClassCastException: Cannot cast vazkii.quark.addons.oddities.tile.MatrixEnchantingTableTileEntity to net.minecraft.tileentity.EnchantingTableTileEntity
	at java.lang.Class.cast(Unknown Source)
	at org.bukkit.craftbukkit.v1_16_R3.block.CraftBlockEntityState.<init>(CraftBlockEntityState.java:26)
	at org.bukkit.craftbukkit.v1_16_R3.block.CraftEnchantingTable.<init>(CraftEnchantingTable.java:12)
	at org.bukkit.craftbukkit.v1_16_R3.block.CraftBlock.getState(CraftBlockMixin.java:431)
	at io.izzel.arclight.common.mod.util.ArclightCaptures.captureBlockBreakPlayer(ArclightCaptures.java:43)
	at io.izzel.arclight.common.mod.server.event.BlockBreakEventDispatcher.onBreakBlock(BlockBreakEventDispatcher.java:26)
	at net.minecraftforge.eventbus.ASMEventHandler_29_BlockBreakEventDispatcher_onBreakBlock_BreakEvent.invoke(.dynamic)
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:297)
	at net.minecraftforge.common.ForgeHooks.onBlockBreakEvent(ForgeHooksMixin.java:565)
	at net.minecraft.server.management.PlayerInteractionManager.func_180237_b(PlayerInteractionManagerMixin.java:230)
	at net.minecraft.server.management.PlayerInteractionManager.func_229860_a_(PlayerInteractionManagerMixin.java:220)
	at net.minecraft.server.management.PlayerInteractionManager.func_225416_a(PlayerInteractionManagerMixin.java:613)
	at net.minecraft.network.play.ServerPlayNetHandler.func_147345_a(ServerPlayNetHandlerMixin.java:2169)
	at net.minecraft.network.play.client.CPlayerDiggingPacket.func_148833_a(SourceFile:40)
	at net.minecraft.network.play.client.CPlayerDiggingPacket.func_148833_a(SourceFile:10)
	at net.minecraft.network.PacketThreadUtil.mdc32f24$lambda$checkThreadAndEnqueue$0$0(PacketThreadUtilMixin.java:536)
	at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18)
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144)
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23)
	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServerMixin.java:733)
	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServerMixin.java:159)
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118)
	at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServerMixin.java:716)
	at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServerMixin.java:710)
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213161_c(SourceFile:127)
	at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServerMixin.java:696)
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServerMixin.java:1898)
	at net.minecraft.server.MinecraftServer.lambda$startServer$0(MinecraftServerMixin.java:232)
	at java.lang.Thread.run(Unknown Source)
</pre></details>

完整log
https://paste.ubuntu.com/p/y8vXB46tqC/

**Comment by IzzelAliz** [comment]
请测试，在 `arclight.conf` 像这样设置

```hocon
compatibility {
    entity-property-overrides {}
    material-property-overrides {
        "minecraft:enchanting_table" {
            blockStateClass="auto"
        }
    }
}
```
