### ISSUE TITLE
[1.20.2] Multiverse-core not teleporting

### ISSUE THREAD

**Issue by StudioTeamTV** [IzzelAliz/Arclight#1154]
### I have confirmed that ...

- [X] Arclight is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [ ] unable to reproduce in Spigot
- [ ] unable to reproduce in Forge

### Arclight version

arclight-1.20.2-1.0.1-5e1b3b3

### OS & Java versions

java version 17.0.1 by Oracle Corporation; OS Linux arch amd64 version 6.2.0-37-generic

### Plugins and Mods

```raw
mods:
• minecraft server-1.20.2-20230921.100330-srg.jar : minecraft (1.20.2) - 1
• mods_folder voicechat-forge-1.20.2-2.4.29.jar : voicechat (1.20.2-2.4.29) - 1
• minecraft forge-1.20.2-48.1.0-universal.jar : forge (48.1.0) - 1
• arclight arclight-1.20.2-1.0.1-5e1b3b3.jar : arclight (1.20.2-1.0.1-5e1b3b3) - 1
plugins:
VoidGen, PlaceholderAPI, PerWorldPlugins, CMILib, SetSpawn, CustomUknownCommand, CoordinatesHud, HeadDrops, DynColor, SelectEverywhere, ViaVersion, FakaHedaMinequery, LuckPerms, Scoreboard-revision, SkinsRestorer, TAB, GSit, Vault, WorldEdit, Essentials, GCore, Admin-GUI, Elevator, Multiverse-Core, BetterSleeping4, Residence, ColorMe, Multiverse-Inventories, EssentialsChat, BetterRTP, CustomCommands, AuthMe
```

### Description

I just type /mv tp world (for example) and in the console appears a message:
and the version of multivese is working on normal CraftBukkit

[12:09:32 ERROR] [STDERR]: java.lang.ClassCastException: class net.minecraft.server.dedicated.DedicatedPlayerList cannot be cast to class net.minecraft.server.level.ServerPlayer (net.minecraft.server.dedicated.DedicatedPlayerList and net.minecraft.server.level.ServerPlayer are in module minecraft@1.20.2 of loader 'TRANSFORMER' @19fd43da)
[12:09:32 ERROR] [STDERR]: at TRANSFORMER/minecraft@1.20.2/net.minecraft.server.players.PlayerList.respawn(PlayerListMixin.java:1176)
[12:09:32 ERROR] [STDERR]: at TRANSFORMER/arclight@1.20.2-1.0.1-5e1b3b3/org.bukkit.craftbukkit.v1_20_R2.entity.CraftPlayer.teleport(CraftPlayerMixin.java:964)
[12:09:32 ERROR] [STDERR]: at TRANSFORMER/arclight@1.20.2-1.0.1-5e1b3b3/org.bukkit.craftbukkit.v1_20_R2.entity.CraftEntity.teleport(CraftEntityMixin.java:532)
[12:09:32 ERROR] [STDERR]: at com.onarandombox.MultiverseCore.utils.SimpleSafeTTeleporter.safelyTeleport(SimpleSafeTTeleporter.java:216)
[12:09:32 ERROR] [STDERR]: at com.onarandombox.MultiverseCore.utils.SimpleSafeTTeleporter.teleport(SimpleSafeTTeleporter.java:336)
[12:09:32 ERROR] [STDERR]: at com.onarandombox.MultiverseCore.commands.TeleportCommand.runCommand(TeleportCommand.java:152)
[12:09:32 ERROR] [STDERR]: at com.onarandombox.commandhandler.CommandHandler.checkAndRunCommand(CommandHandler.java:296)
[12:09:32 ERROR] [STDERR]: at com.onarandombox.commandhandler.CommandHandler.processFoundCommands(CommandHandler.java:143)
[12:09:32 ERROR] [STDERR]: at com.onarandombox.commandhandler.CommandHandler.locateAndRunCommand(CommandHandler.java:93)
[12:09:32 ERROR] [STDERR]: at com.onarandombox.MultiverseCore.MultiverseCore.onCommand(MultiverseCore.java:839)
[12:09:32 ERROR] [STDERR]: at TRANSFORMER/arclight@1.20.2-1.0.1-5e1b3b3/org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[12:09:32 ERROR] [STDERR]: at net.tonimatasdev.perworldplugins.api.PerWorldCommand$1.execute(PerWorldCommand.java:50)
[12:09:32 ERROR] [STDERR]: at TRANSFORMER/arclight@1.20.2-1.0.1-5e1b3b3/org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149)
[12:09:32 ERROR] [STDERR]: at TRANSFORMER/arclight@1.20.2-1.0.1-5e1b3b3/org.bukkit.craftbukkit.v1_20_R2.CraftServer.dispatchCommand(CraftServerMixin.java:879)
[12:09:32 ERROR] [STDERR]: at TRANSFORMER/arclight@1.20.2-1.0.1-5e1b3b3/org.bukkit.craftbukkit.v1_20_R2.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:50)
[12:09:32 ERROR] [STDERR]: at MC-BOOTSTRAP/brigadier@1.1.8/com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:264)
[12:09:32 ERROR] [STDERR]: at TRANSFORMER/minecraft@1.20.2/net.minecraft.commands.Commands.m_242674_(CommandsMixin.java:263)
[12:09:32 ERROR] [STDERR]: at TRANSFORMER/minecraft@1.20.2/net.minecraft.server.network.ServerGamePacketListenerImpl.m_246958_(ServerPlayNetHandlerMixin.java:2712)
[12:09:32 ERROR] [STDERR]: at TRANSFORMER/minecraft@1.20.2/net.minecraft.server.network.ServerGamePacketListenerImpl.m_244885_(ServerPlayNetHandlerMixin.java:1169)
[12:09:32 ERROR] [STDERR]: at TRANSFORMER/minecraft@1.20.2/net.minecraft.util.thread.BlockableEventLoop.m_18693_(BlockableEventLoop.java:67)
[12:09:32 ERROR] [STDERR]: at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
[12:09:32 ERROR] [STDERR]: at TRANSFORMER/minecraft@1.20.2/net.minecraft.server.TickTask.run(TickTask.java:18)
[12:09:32 ERROR] [STDERR]: at TRANSFORMER/minecraft@1.20.2/net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:156)
[12:09:32 ERROR] [STDERR]: at TRANSFORMER/minecraft@1.20.2/net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23)
[12:09:32 ERROR] [STDERR]: at TRANSFORMER/minecraft@1.20.2/net.minecraft.server.MinecraftServer.m_6367_(MinecraftServerMixin.java:765)
[12:09:32 ERROR] [STDERR]: at TRANSFORMER/minecraft@1.20.2/net.minecraft.server.MinecraftServer.m_6367_(MinecraftServerMixin.java:160)
[12:09:32 ERROR] [STDERR]: at TRANSFORMER/minecraft@1.20.2/net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:130)
[12:09:32 ERROR] [STDERR]: at TRANSFORMER/minecraft@1.20.2/net.minecraft.server.MinecraftServer.m_129961_(MinecraftServerMixin.java:748)
[12:09:32 ERROR] [STDERR]: at TRANSFORMER/minecraft@1.20.2/net.minecraft.server.MinecraftServer.m_7245_(MinecraftServerMixin.java:742)
[12:09:32 ERROR] [STDERR]: at TRANSFORMER/minecraft@1.20.2/net.minecraft.util.thread.BlockableEventLoop.m_18701_(BlockableEventLoop.java:139)
[12:09:32 ERROR] [STDERR]: at TRANSFORMER/minecraft@1.20.2/net.minecraft.server.MinecraftServer.m_130012_(MinecraftServerMixin.java:728)
[12:09:32 ERROR] [STDERR]: at TRANSFORMER/minecraft@1.20.2/net.minecraft.server.MinecraftServer.m_130011_(MinecraftServerMixin.java:2081)
[12:09:32 ERROR] [STDERR]: at TRANSFORMER/minecraft@1.20.2/net.minecraft.server.MinecraftServer.m_206580_(MinecraftServerMixin.java:249)
[12:09:32 ERROR] [STDERR]: at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by Mikalixar** [comment]
We (we being the community I'm an Admin of) are having the same issue.
