### ISSUE TITLE
Bug: Failed to load function watching:check java.util.concurrent.CompletionException: java.lang.IllegalArgumentException

### ISSUE THREAD

**Issue by Lamagape1** [IzzelAliz/Arclight#1161]
### I have confirmed that ...

- [X] Arclight is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Forge

### Arclight version

arclight-forge-1.19.2-1.0.3

### OS & Java versions

java version 18.0.2.1 by Oracle Corporation; OS Windows 11 arch amd64 version 10.0

### Plugins and Mods

```raw
PLUGINS: WorldEdit, spark, OpeNLogin, ProtocolLib, WorldGuard, NeoPerformance

MODS: mods_folder adaptive_performance_tweaks_core_1.19.2-10.2.0.jar : adaptive_performance_tweaks_core (10.2.0) - 1
• mods_folder infernal-expansion-1.19.2-2.5.3.jar : infernalexp (2.5.1) - 1
• mods_folder beautify-1.4.3.jar : beautify (1.4.3) - 1
• mods_folder player-animation-lib-forge-1.0.2.jar : playeranimator (1.0.2) - 1
• mods_folder aether-1.19.2-1.0.0-beta.2-forge.jar : aether (1.19.2-1.0.0-beta.2-forge) - 1
• mods_folder mcw-windows-2.2.0-mc1.19.2forge.jar : mcwwindows (2.2.0) - 1
• mods_folder dynamiclights-1.19.2.2.jar : dynamiclights (1.19.2.2) - 1
• mods_folder villagernames-1.19.2-7.1.jar : villagernames (7.1) - 1
• mods_folder citadel-2.1.4-1.19.jar : citadel (2.1.4) - 1
• mods_folder alexsmobs-1.21.1.jar : alexsmobs (1.21.1) - 1
• mods_folder YungsApi-1.19.2-Forge-3.8.10.jar : yungsapi (1.19.2-Forge-3.8.10) - 1
• JarInJar mixinextras-forge-0.2.0-rc.5.jar : mixinextras (0.2.0-rc.5) - 1
• mods_folder simpleplanes-1.19.2-5.2.2.jar : simpleplanes (1.19.2-5.2.2) - 1
• mods_folder sculkhorde-1.19.2-0.8.0.jar : sculkhorde (1.19.2-0.8.0) - 1
• mods_folder bygonenether-1.3.2-1.19.2.jar : bygonenether (1.3.2) - 1
• mods_folder balm-forge-1.19.2-4.6.0.jar : balm (4.6.0) - 1
• mods_folder cloth-config-8.3.103-forge.jar : cloth_config (8.3.103) - 1
• mods_folder ctov-3.2.6c.jar : ctov (3.2.6c) - 1
• mods_folder twilightforest-1.19.2-4.2.1518-universal.jar : twilightforest (4.2.1518) - 1
• mods_folder structure_gel-1.19.2-2.7.3.jar : structure_gel (2.7.3) - 1
• mods_folder FarmersDelight-1.19.2-1.2.3.jar : farmersdelight (1.19.2-1.2.3) - 1
• mods_folder handcrafted-forge-1.19.2-2.0.6.jar : handcrafted (2.0.6) - 1
• mods_folder endrem_forge-5.2.1-R-1.19.X.jar : endrem (5.2.1-R-1.19.2) - 1
• mods_folder StructureCompass-1.19.2-1.4.6.jar : structurecompass (1.4.6) - 1
• mods_folder nekoration-1.19.2-1.8.1.jar : nekoration (1.8.1) - 1
• mods_folder YungsBridges-1.19.2-Forge-3.1.0.jar : yungsbridges (1.19.2-Forge-3.1.0) - 1
• mods_folder born_in_chaos_[Forge]1.19.2_1.9.jar : born_in_chaos_v1 (1.0.0) - 1
• mods_folder wthit-forge-5.19.3.jar : wthit (5.19.3) - 2
• mods_folder MOAdecor+COOKERY+1.19.2.jar : moa_decor_cookery (1.19.2) - 1
• JarInJar curios-forge-1.19.2-5.1.4.1.jar : curios (1.19.2-5.1.4.1) - 1
• mods_folder collective-1.19.2-7.21.jar : collective (7.21) - 1
• mods_folder tombstone-8.2.12-1.19.2.jar : tombstone (8.2.12) - 1
• mods_folder Desolation+1.1.8+1.19.2.jar : desolation (1.1.8) - 1
• mods_folder resourcefullib-forge-1.19.2-1.1.24.jar : resourcefullib (1.1.24) - 1
• JarInJar cumulus_menus-1.19.2-1.0.0-beta.1-forge.jar : cumulus_menus (1.19.2-1.0.0-beta.1-forge) - 1
• mods_folder mutantmore-1.19.2-early-access-1.0.7.jar : mutantmore (1.0) - 1
• mods_folder architectury-6.5.85-forge.jar : architectury (6.5.85) - 1
• mods_folder doapi-1.1.0b.jar : doapi (1.1.0b) - 2
• mods_folder letsdo-candlelight-forge-1.1.9.jar : candlelight (1.1.9) - 1
• mods_folder nitrogen_internals-1.19.2-0.2.2-forge.jar : nitrogen_internals (1.19.2-0.2.2-forge) - 1
• mods_folder ScalingHealth-1.19.2-7.0.0+6.jar : scalinghealth (7.0.0+6) - 1
• mods_folder geckolib-forge-1.19-3.1.40.jar : geckolib3 (3.1.40) - 1
• mods_folder cave_dweller-1.19.2-1.6.5.jar : cave_dweller (1.6.5) - 1
• mods_folder EnchantingInfuser-v4.2.2-1.19.2-Forge.jar : enchantinginfuser (4.2.2) - 1
• mods_folder adaptive_performance_tweaks_spawn_1.19.2-10.2.0.jar : adaptive_performance_tweaks_spawn (10.2.0) - 1
• mods_folder Fastload-Reforged-mc1.19.2-3.4.0.jar : fastload (3.4.0) - 1
• mods_folder MutantMonsters-v4.0.6-1.19.2-Forge.jar : mutantmonsters (4.0.6) - 1
• mods_folder MOAdecor+GARDEN+1.19.1.jar : moa_decor_garden_ (1.19.1) - 1
• mods_folder edf-remastered-4.3.jar : mr_edf_remastered (4.3) - 1
• mods_folder treeharvester-1.19.2-8.4.jar : treeharvester (8.4) - 1
• mods_folder [1.19.2]-Medieval-Siege-Machines-v1.10.jar : siegemachines (1.0) - 1
• mods_folder The_Graveyard_2.5.3_(FORGE)_for_1.19.2..jar : graveyard (2.5.3) - 1
• mods_folder waystones-forge-1.19.2-11.4.2.jar : waystones (11.4.2) - 1
• mods_folder Structory-1.19-v1.3.jar : structory (1.0.1) - 1
• mods_folder integrated_api_forge-1.2.7+1.19.2.jar : integrated_api (1.2.7+1.19.2) - 1
• mods_folder comforts-forge-6.0.6+1.19.2.jar : comforts (6.0.6+1.19.2) - 1
• mods_folder TravelersBackpack-1.19.2-8.2.37.jar : travelersbackpack (8.2.37) - 1
• mods_folder NaturesCompass-1.19.2-1.10.0-forge.jar : naturescompass (1.19.2-1.10.0-forge) - 1
• mods_folder artifacts-1.19.2-5.0.4.jar : artifacts (1.19.2-5.0.4) - 1
• mods_folder configured-2.1.1-1.19.2.jar : configured (2.1.1) - 1
• mods_folder badpackets-forge-0.2.3.jar : badpackets (0.2.3) - 1
• mods_folder HopoBetterUnderwaterRuins-[1.19-1.19.3]-1.1.1.jar : hopour (1.1.1) - 1
• mods_folder Ice_and_Fire-1.19.2-2.1.11.jar : iceandfire (1.19.2-2.1.11) - 1
• mods_folder azurelib-forge-1.19.2-1.0.38.jar : azurelib (1.0.38) - 1
• minecraft forge-1.19.2-43.3.2-universal.jar : forge (43.3.2) - 1
• mods_folder Waddles-1.19-0.9.1.jar : waddles (1.19-0.9.1) - 1
• mods_folder THEUNDEADREVAMPED_0.9e_1.19.2.jar : undead_revamp2 (1.0.0) - 1
• mods_folder alcocraftplus-1.19.2-forge-1.0.1.jar : alcocraftplus (1.0.1) - 1
• mods_folder ironchest-1.19.2-14.2.7.jar : ironchest (1.19.2-14.2.7) - 1
• mods_folder DungeonsArise-1.19.2-2.1.56-beta.jar : dungeons_arise (2.1.56-1.19.2) - 1
• minecraft server-1.19.2-20220805.130853-srg.jar : minecraft (1.19.2) - 1
• mods_folder TerraBlender-forge-1.19.2-2.0.1.166.jar : terrablender (2.0.1.166) - 1
• mods_folder moonlight-1.19.2-2.3.5-forge.jar : moonlight (1.19.2-2.3.5) - 1
• mods_folder bettercombat-forge-1.7.1+1.19.jar : bettercombat (1.7.1+1.19) - 1
• mods_folder ToolBelt-1.19.2-1.19.7.jar : toolbelt (1.19.7) - 1
• JarInJar commonality-1.19.2-4.2.1.jar : commonality (4.2.1) - 1
• mods_folder silent-lib-1.19.2-7.0.3.jar : silentlib (7.0.3) - 1
• mods_folder From-The-Fog-1.19-v1.9.1-Forge-Fabric.jar : watching (1.9.1) - 1
• JarInJar spectrelib-forge-0.12.6+1.19.2.jar : spectrelib (0.12.6+1.19.2) - 1
• JarInJar kffmod-3.12.0.jar : kotlinforforge (3.12.0) - 1
• JarInJar flywheel-forge-1.19.2-0.6.10-20.jar : flywheel (0.6.10-20) - 1
• mods_folder create-1.19.2-0.5.1.f.jar : create (0.5.1.f) - 1
• mods_folder lava_monster-1.19.1-1.0.11.jar : lava_monster (1.0.11) - 1
• mods_folder AutoRegLib-1.8.2-55.jar : autoreglib (1.8.2-55) - 1
• mods_folder Quark-3.4-418.jar : quark (3.4-418) - 1
• mods_folder supplementaries-1.19.2-2.4.13.jar : supplementaries (1.19.2-2.4.13) - 1
• mods_folder [1.19.2]+SecurityCraft+v1.9.6.1.jar : securitycraft (1.9.6.1) - 1
• mods_folder Nullscape_1.19.3_v1.2.2.jar : nullscape (1.2.2) - 1
• JarInJar apexcore-1.19.2-7.3.1.jar : apexcore (7.3.1) - 1
• mods_folder fantasyfurniture-1.19.2-6.6.1.jar : fantasyfurniture (6.6.1) - 1
• arclight arclight-1.19.2-1.0.3-cfdf69de.jar : arclight (1.19.2-1.0.3-cfdf69de) - 1
• mods_folder PuzzlesLib-v4.4.3-1.19.2-Forge.jar : puzzleslib (4.4.3) - 1
• mods_folder immersive_melodies-0.1.0+1.19.2-forge.jar : immersive_melodies (0.1.0+1.19.2) - 1
• JarInJar expandability-forge-7.0.0.jar : expandability (7.0.0) - 1
```

### Description

The owner of the mod told me that this seems to be a bug with arclight. I was looking for a way to resolve this and i found that i have to change permission-level-type, but it is already in "level 2" so i dont know what to do.

[13:27:55 ERROR]: Failed to load function watching:check
java.util.concurrent.CompletionException: java.lang.IllegalArgumentException: Whilst parsing command on line 1: Unknown or incomplete command, see below for error at position 0: <--[HERE]
        at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315) ~[?:?]
        at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320) ~[?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1770) ~[?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760) ~[?:?]
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?]
        at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?]
        at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?]
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?]
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?]
Caused by: java.lang.IllegalArgumentException: Whilst parsing command on line 1: Unknown or incomplete command, see below for error at position 0: <--[HERE]
        at net.minecraft.commands.CommandFunction.m_77984_(CommandFunction.java:63) ~[server-1.19.2-20220805.130853-srg.jar%23329!/:?]
        at net.minecraft.server.ServerFunctionLibrary.m_214320_(ServerFunctionLibrary.java:85) ~[server-1.19.2-20220805.130853-srg.jar%23329!/:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
        ... 6 more
[13:27:55 ERROR]: Parsing error loading custom advancement sculkhorde:craft_infestation_purifier: Invalid criterion trigger: minecraft:recipe_crafted
[13:27:55 ERROR]: Parsing error loading custom advancement sculkhorde:craft_pure_souls: Invalid criterion trigger: minecraft:recipe_crafted
[13:27:55 ERROR]: Parsing error loading custom advancement mutantmore:nether/upgrade_rodling: Expected requirements[0] to be a JsonArray, was "rod...et"
[13:27:55 ERROR]: Parsing error loading custom advancement sculkhorde:craft_purification_flask: Expected item to be an item, was unknown string 'sculkhorde:purity_splash_potion'
[13:27:55 ERROR]: Parsing error loading custom advancement sculkhorde:craft_infestation_ward_block: Invalid criterion trigger: minecraft:recipe_crafted
[13:27:55 ERROR]: Parsing error loading custom advancement sculkhorde:craft_essence_of_purity: Invalid criterion trigger: minecraft:recipe_crafted

### Logs

[latest.log](https://github.com/IzzelAliz/Arclight/files/13707335/latest.log)

**Comment by Krimatoria** [comment]
Hmm, I have a similar problem, but I do not know which mod is causing it...

**Comment by BronsonCarder** [comment]
I have very few mods in common with this modlist. This narrows it down significantly... in fact, the only thing it can be is From the Fog.

**Comment by BronsonCarder** [comment]
Soooo.... yeah, for anyone curious about this:
From the Fog has a file called check.mcfunction, in it's "watching" folder. 

This is the entire content of that file:
"check lol"

**Comment by qyl27** [comment]
Could you publish the content of `check.mcfunction` ?

**Comment by qyl27** [comment]
> Soooo.... yeah, for anyone curious about this: From the Fog has a file called check.mcfunction, in it's "watching" folder.
> 
> This is the entire content of that file: "check lol"

Which mod provides `check` command?  
It seems that Minecraft doesn't understand this command.

**Comment by BronsonCarder** [comment]
...I already said. 
The mod is From the Fog. 
Minecraft doesn't understand the command because there is no command in the file. 

Literally, the entire content, every character in the file check.mcfunction is:
"check lol"

There's no command, no function. But removing the file breaks the mod. I don't know what purpose it serves, but for one reason or another, it has to be in there, and this error will keep popping up. But it doesn't actually affect anything. 

To check this for yourself, simply use winRAR (or similar) to unzip the From_The_Fog.jar file. There is a folder called "watching." The "check.mcfunction" file is in that folder. That's why the error says watching:check.

**Comment by qyl27** [comment]
> ...I already said. The mod is From the Fog. Minecraft doesn't understand the command because there is no command in the file.
> 
> Literally, the entire content, every character in the file check.mcfunction is: "check lol"
> 
> There's no command, no function. But removing the file breaks the mod. I don't know what purpose it serves, but for one reason or another, it has to be in there, and this error will keep popping up. But it doesn't actually affect anything.
> 
> To check this for yourself, simply use winRAR (or similar) to unzip the From_The_Fog.jar file. There is a folder called "watching." The "check.mcfunction" file is in that folder. That's why the error says watching:check.

Minecraft will treat each line which in the `mcfunction` file inside datapacks as a command, if no mod provides the `check` command, it will undoubtedly fail.  
You'd better ask the mod author to check their code.

**Comment by qyl27** [comment]
![image](https://github.com/user-attachments/assets/a2c1def5-8126-496f-87fc-db476b136bc9)  
I have added the datapack 1.9.1 into vanilla 1.19.2, and now you see, that it will fail in vanilla.

**Comment by BronsonCarder** [comment]
I don't think this is a bug. I think this was a workaround to add a feature that the author either didn't know how to, or could not, implement otherwise. 
From the Fog appears to work as intended. It just also puts this error into the logs. 
I believe that this can safely be ignored.

**Comment by qyl27** [comment]
Yes, that it is.
