### ISSUE TITLE
Apotheosis Deadly Module incompatiblity

### ISSUE THREAD

**Issue by HerrBeef** [IzzelAliz/Arclight#117]
### I am running

* **Arclight** [VERSION] 1.0.11 SNAPSHOT

* **This is the latest development version** Y

* **Java** 8 Update 271

* **Operating System** CentOS 7 & Windows 10 Pro

* **Plugins** None

* **Mods** Apotheosis, Placebo

### Description

It crashes when the deadly module is enabled, after flying around a bit.
It's fixed when i disable Deadly Module. So it has to be something about these changes.

### Step to reproduce

1. Install Apotheosis (enable all modules)
2. Fly around in the world
3. Crash

**Reproducible in Forge** N

**Reproducible in Spigot** N

### Logs

[ERROR LOG]

<details><pre>
java.lang.IllegalStateException: EntityPotionEffectEvent cannot be triggered asynchronously from another thread.
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:572) ~[arclight:arclight-1.16.4-1.0.11-SNAPSHOT-feb567a] {re:mixin,re:classloading}
	at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callEntityPotionEffectChangeEvent(CraftEventFactoryMixin.java:1500) ~[arclight:arclight-1.16.4-1.0.11-SNAPSHOT-feb567a] {re:mixin,re:classloading,pl:mixin:APP:mixins.arclight.bukkit.json:CraftEventFactoryMixin,pl:mixin:A,pl:arclight_implementer:switch,pl:arclight_implementer:A}
	at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callEntityPotionEffectChangeEvent(CraftEventFactoryMixin.java:1488) ~[arclight:arclight-1.16.4-1.0.11-SNAPSHOT-feb567a] {re:mixin,re:classloading,pl:mixin:APP:mixins.arclight.bukkit.json:CraftEventFactoryMixin,pl:mixin:A,pl:arclight_implementer:switch,pl:arclight_implementer:A}
	at net.minecraft.entity.LivingEntity.func_195064_c(LivingEntityMixin.java:3596) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:apotheosis:apothshieldblock,xf:fml:apotheosis:apothpotiondmg,pl:mixin:APP:mixins.arclight.core.json:entity.LivingEntityMixin,pl:mixin:APP:caelus.mixins.json:LivingEntityMixin,pl:mixin:APP:charm.mixins.json:LivingEntityMixin,pl:mixin:A,pl:arclight_implementer:A,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at shadows.apotheosis.deadly.gen.BossItem.initBoss(BossItem.java:107) ~[apotheosis:4.4.1] {re:classloading}
	at shadows.apotheosis.deadly.gen.BossItem.spawnBoss(BossItem.java:96) ~[apotheosis:4.4.1] {re:classloading}
	at shadows.apotheosis.deadly.gen.BossItem.place(BossItem.java:81) ~[apotheosis:4.4.1] {re:classloading}
	at shadows.apotheosis.deadly.gen.BossGenerator.generate(BossGenerator.java:37) ~[apotheosis:4.4.1] {re:classloading}
	at shadows.apotheosis.deadly.gen.DeadlyFeature.func_241855_a(DeadlyFeature.java:51) ~[apotheosis:4.4.1] {re:classloading}
	at shadows.apotheosis.deadly.gen.DeadlyFeature.func_241855_a(DeadlyFeature.java:29) ~[apotheosis:4.4.1] {re:classloading}
	at net.minecraft.world.gen.feature.ConfiguredFeature.func_242765_a(SourceFile:55) ~[?:?] {re:mixin,re:classloading}
	at net.minecraft.world.biome.Biome.func_242427_a(Biome.java:254) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:ftbchunks.mixins.json:BiomeMixin,pl:mixin:APP:blame.mixins.json:BiomeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.world.gen.ChunkGenerator.func_230351_a_(SourceFile:220) ~[?:?] {re:mixin,re:classloading}
	at net.minecraft.world.chunk.ChunkStatus.lambda$static$9(ChunkStatus.java:77) ~[?:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.world.chunk.ChunkStatus.func_223198_a(ChunkStatus.java:198) ~[?:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.world.server.ChunkManager.lambda$null$18(ChunkManagerMixin.java:524) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:world.server.ChunkManagerMixin,pl:mixin:APP:ftbchunks.mixins.json:ChunkManagerMixin,pl:mixin:A,pl:arclight_implementer:async,pl:arclight_implementer:A,pl:runtimedistcleaner:A}
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[?:?] {re:classloading}
	at net.minecraft.world.server.ChunkManager.lambda$chunkGenerate$20(ChunkManagerMixin.java:522) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:world.server.ChunkManagerMixin,pl:mixin:APP:ftbchunks.mixins.json:ChunkManagerMixin,pl:mixin:A,pl:arclight_implementer:async,pl:arclight_implementer:A,pl:runtimedistcleaner:A}
	at java.util.concurrent.CompletableFuture.uniCompose(CompletableFuture.java:966) ~[?:1.8.0_275] {}
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:940) ~[?:1.8.0_275] {}
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:456) ~[?:1.8.0_275] {}
	at net.minecraft.world.chunk.ChunkTaskPriorityQueueSorter.func_219083_b(SourceFile:58) ~[?:?] {re:classloading}
	at net.minecraft.util.concurrent.DelegatedTaskExecutor.func_213148_e(SourceFile:94) ~[?:?] {re:classloading}
	at net.minecraft.util.concurrent.DelegatedTaskExecutor.func_213145_a(SourceFile:137) ~[?:?] {re:classloading}
	at net.minecraft.util.concurrent.DelegatedTaskExecutor.run(SourceFile:105) ~[?:?] {re:classloading}
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402) ~[?:1.8.0_275] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_275] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[?:1.8.0_275] {}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692) ~[?:1.8.0_275] {re:computing_frames}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175) ~[?:1.8.0_275] {}
</pre></details>

**Comment by IzzelAliz** [comment]
You can enable async catcher in `arclight.conf` 

```
async-catcher {
    defaultOperation=block
}
```

**Comment by HerrBeef** [comment]
This seems to work, but why is that necessary?

**Comment by IzzelAliz** [comment]
Worlds are generated multithreaded in 1.15 but Bukkit plugins cannot handle that, so async catcher put these actions to main thread.

**Comment by HerrBeef** [comment]
Ah okay, seems logical now. What does block? And what does dispatch? 
When i turn it to block i get a warning with "Async effect add".

**Comment by IzzelAliz** [comment]
Dispatch is throwing the adding effect action to main thread, block is dispatch and wait for its result. You don't need to worry about the warning.

**Comment by HerrBeef** [comment]
Okay, Thanks!
