### ISSUE TITLE
Errors with MMOitems

### ISSUE THREAD

**Issue by JohnKillswitch** [IzzelAliz/Arclight#1170]
### I have confirmed that ...

- [X] Arclight is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Forge

### Arclight version

arclight-1.20.1-1.0.3-SNAPSHOT-610953f

### OS & Java versions

OS: Debian 10 openjdk version "21.0.1" 2023-10-17 LTS OpenJDK Runtime Environment Temurin-21.0.1+12 (build 21.0.1+12-LTS) OpenJDK 64-Bit Server VM Temurin-21.0.1+12 (build 21.0.1+12-LTS, mixed mode, sharing)

### Plugins and Mods

```raw
[14:34:07 INFO]: Mod List:
• minecraft server-1.20.1-20230612.114412-srg.jar : minecraft (1.20.1) - 1
• JarInJar mixinextras-forge-0.2.0-beta.8.jar : mixinextras (0.2.0-beta.8) - 1
• JarInJar additionalentityattributes-forge-1.4.0.5+1.20.1.jar : additionalentityattributes (1.4.0.5+1.20.1) - 1
• mods_folder OpticManager_FORGE_v1.3.0_mc1.20.jar : opticmanager (1.3.0) - 1
• mods_folder player-animation-lib-forge-1.0.2-rc1+1.20.jar : playeranimator (1.0.2-rc1+1.20) - 1
• mods_folder CreativeCore_FORGE_v2.11.16_mc1.20.1.jar : creativecore (2.11.16) - 1
• arclight arclight-1.20.1-1.0.3-SNAPSHOT-610953f.jar : arclight (1.20.1-1.0.3-SNAPSHOT-610953f) - 1
• mods_folder ItemPhysic_FORGE_v1.7.0_mc1.20.1.jar : itemphysic (1.7.0) - 1
• mods_folder extendedslabs-1.20.1-3.0.1.jar : extendedslabs (3.0.1) - 1
• mods_folder Pehkui-3.7.11+1.20.1-forge (1).jar : pehkui (3.7.11+1.20.1-forge) - 1
• mods_folder bendy-lib-forge-4.0.0.jar : bendylib (4.0.0) - 1
• JarInJar calio-forge-1.20.1-1.11.0.1.jar : calio (1.20.1-1.11.0.1) - 1
• mods_folder caelus-forge-3.1.0+1.20 (1).jar : caelus (3.1.0+1.20) - 1
• minecraft forge-1.20.1-47.2.16-universal.jar : forge (47.2.16) - 1
• JarInJar apoli-forge-1.20.1-2.9.0.2.jar : apoli (1.20.1-2.9.0.2) - 1
• mods_folder origins-forge-1.20.1-1.10.0.2-all.jar : origins (1.20.1-1.10.0.2) - 1
• mods_folder vanishmod-1.1.14.jar : vmod (1.1.14) - 1
• mods_folder emotecraft-for-MC1.20.1-2.2.7-b.build.50-forge.jar : emotecraft (2.2.7-b.build.50) - 1
• mods_folder nyfsspiders-forge-1.20.1-2.1.1.jar : nyfsspiders (2.1.1) - 1



[14:34:20 INFO] [Console]: Plugins (31): LuckPerms, InventoryRollbackPlus, Chunky, PlaceholderAPI, kotlin-stdlib, LoneLibs, ProtocolLib, AbobaTest, LibsDisguises, QuasarUtils, TAB, AzLink, Vault, Chatty, voicechat, WorldEdit, WorldGuard, Citizens, DiscordSRV, MythicMobs, ModelEngine, CoreProtect, MythicLib, MCPets, Lands, MMOItems, ExtraContexts, FarmLimiter, ItemsAdder, DeluxeMenus, ScreenEffects
```

### Description

errors with staves in plugin. the staves fire a beam of particles that fly forward. An error appears if you left-click in the air with a staff. If you click on an entity or block, then everything is fine

### Step to reproduce

install MMOITEMs
make a staff
try to left click air

### Logs

[28Dec2023 14:31:01.926] [Server thread/ERROR] [MythicMobs/]: [31m[EVENTS] Exception thrown whilst handling event: org.bukkit.event.player.PlayerBucketEmptyEvent[37m
[28Dec2023 14:31:01.926] [Server thread/ERROR] [STDERR/]: java.lang.NoSuchMethodError: 'org.bukkit.entity.Entity org.bukkit.entity.Player.getTargetEntity(int, boolean)'
[28Dec2023 14:31:01.926] [Server thread/ERROR] [STDERR/]: 	at io.lumine.mythic.bukkit.adapters.BukkitSkillTriggers.onBucketFill(BukkitSkillTriggers.java:154)
[28Dec2023 14:31:01.926] [Server thread/ERROR] [STDERR/]: 	at io.lumine.mythic.bukkit.utils.Delegates$ConsumerToBiConsumerSecond.accept(Delegates.java:144)
[28Dec2023 14:31:01.926] [Server thread/ERROR] [STDERR/]: 	at io.lumine.mythic.bukkit.utils.events.functional.single.EventListener.execute(EventListener.java:131)
[28Dec2023 14:31:01.926] [Server thread/ERROR] [STDERR/]: 	at TRANSFORMER/arclight@1.20.1-1.0.3-SNAPSHOT-610953f/org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[28Dec2023 14:31:01.926] [Server thread/ERROR] [STDERR/]: 	at TRANSFORMER/arclight@1.20.1-1.0.3-SNAPSHOT-610953f/org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589)
[28Dec2023 14:31:01.926] [Server thread/ERROR] [STDERR/]: 	at TRANSFORMER/arclight@1.20.1-1.0.3-SNAPSHOT-610953f/org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576)
[28Dec2023 14:31:01.926] [Server thread/ERROR] [STDERR/]: 	at TRANSFORMER/arclight@1.20.1-1.0.3-SNAPSHOT-610953f/org.bukkit.craftbukkit.v1_20_R1.event.CraftEventFactory.getPlayerBucketEvent(CraftEventFactoryMixin.java:512)
[28Dec2023 14:31:01.926] [Server thread/ERROR] [STDERR/]: 	at TRANSFORMER/arclight@1.20.1-1.0.3-SNAPSHOT-610953f/org.bukkit.craftbukkit.v1_20_R1.event.CraftEventFactory.callPlayerBucketEmptyEvent(CraftEventFactoryMixin.java:484)
[28Dec2023 14:31:01.926] [Server thread/ERROR] [STDERR/]: 	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.item.BucketItem.handler$bgc000$arclight$bucketEmpty(BucketItemMixin.java:599)
[28Dec2023 14:31:01.926] [Server thread/ERROR] [STDERR/]: 	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.item.BucketItem.emptyContents(BucketItemMixin.java:133)
[28Dec2023 14:31:01.926] [Server thread/ERROR] [STDERR/]: 	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.item.BucketItem.m_7203_(BucketItemMixin.java:89)
[28Dec2023 14:31:01.926] [Server thread/ERROR] [STDERR/]: 	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.item.ItemStack.m_41682_(ItemStackMixin.java:275)
[28Dec2023 14:31:01.926] [Server thread/ERROR] [STDERR/]: 	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.level.ServerPlayerGameMode.m_6261_(ServerPlayerGameModeMixin.java:286)
[28Dec2023 14:31:01.926] [Server thread/ERROR] [STDERR/]: 	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.network.ServerGamePacketListenerImpl.m_5760_(ServerPlayNetHandlerMixin.java:2699)
[28Dec2023 14:31:01.926] [Server thread/ERROR] [STDERR/]: 	at TRANSFORMER/minecraft@1.20.1/net.minecraft.network.protocol.game.ServerboundUseItemPacket.m_5797_(CPlayerTryUseItemPacketMixin.java:29)
[28Dec2023 14:31:01.926] [Server thread/ERROR] [STDERR/]: 	at TRANSFORMER/minecraft@1.20.1/net.minecraft.network.protocol.game.ServerboundUseItemPacket.m_5797_(CPlayerTryUseItemPacketMixin.java:7)
[28Dec2023 14:31:01.926] [Server thread/ERROR] [STDERR/]: 	at TRANSFORMER/minecraft@1.20.1/net.minecraft.network.protocol.PacketUtils.mdc7298d$lambda$ensureRunningOnSameThread$0$0(PacketThreadUtilMixin.java:537)
[28Dec2023 14:31:01.926] [Server thread/ERROR] [STDERR/]: 	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.TickTask.run(TickTask.java:18)
[28Dec2023 14:31:01.926] [Server thread/ERROR] [STDERR/]: 	at TRANSFORMER/minecraft@1.20.1/net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:156)
[28Dec2023 14:31:01.926] [Server thread/ERROR] [STDERR/]: 	at TRANSFORMER/minecraft@1.20.1/net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23)
[28Dec2023 14:31:01.926] [Server thread/ERROR] [STDERR/]: 	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_6367_(MinecraftServerMixin.java:770)
[28Dec2023 14:31:01.926] [Server thread/ERROR] [STDERR/]: 	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_6367_(MinecraftServerMixin.java:161)
[28Dec2023 14:31:01.926] [Server thread/ERROR] [STDERR/]: 	at TRANSFORMER/minecraft@1.20.1/net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:130)
[28Dec2023 14:31:01.926] [Server thread/ERROR] [STDERR/]: 	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_129961_(MinecraftServerMixin.java:753)
[28Dec2023 14:31:01.926] [Server thread/ERROR] [STDERR/]: 	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_7245_(MinecraftServerMixin.java:747)
[28Dec2023 14:31:01.926] [Server thread/ERROR] [STDERR/]: 	at TRANSFORMER/minecraft@1.20.1/net.minecraft.util.thread.BlockableEventLoop.m_18701_(BlockableEventLoop.java:139)
[28Dec2023 14:31:01.926] [Server thread/ERROR] [STDERR/]: 	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_130012_(MinecraftServerMixin.java:733)
[28Dec2023 14:31:01.926] [Server thread/ERROR] [STDERR/]: 	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_130011_(MinecraftServerMixin.java:2074)
[28Dec2023 14:31:01.926] [Server thread/ERROR] [STDERR/]: 	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_206580_(MinecraftServerMixin.java:251)
[28Dec2023 14:31:01.926] [Server thread/ERROR] [STDERR/]: 	at java.base/java.lang.Thread.run(Thread.java:1583)

**Comment by JohnKillswitch** [comment]
and also weird thing: 
staves not working if you'll head to west
