### ISSUE TITLE
ModelEngine 4 攻击模型崩服

### ISSUE THREAD

**Issue by appleLPG** [IzzelAliz/Arclight#1175]
### 请确认您已完成以下几件事

- [X] 正在使用最新的 Arclight
- [X] 已为所有插件及模组安装依赖
- [X] 已为所有插件及模组更新至最新版
- [X] 不可在 Spigot 复现
- [X] 不可在 Forge 复现

### Arclight 版本

arclight-1.20.1-1.0.3-SNAPSHOT-7c67acb

### Java 版本 | 操作系统

17.0.9

### 相关 Mod/插件 的名称及版本

```raw
ModelEngine vR4.0.4
```

### 错误描述

召唤的模型可以移动，右键模型后玩家被踢出，左键或受伤会崩服

### 报错信息

右键
[12:57:35 INFO]: apple_LPG lost connection: Internal Exception: java.lang.NoClassDefFoundError: com/destroystokyo/paper/event/player/PlayerUseUnknownEntityEvent
左键
[12:51:40 WARN] [ModelEngine]: Plugin ModelEngine vR4.0.4 generated an exception while executing task 3
java.lang.NoSuchMethodError: 'boolean net.minecraft.world.level.block.state.BlockState.isOpaque()'
        at com.ticxo.modelengine.v1_20_R1.entity.OcclusionClipContext.m_45694_(OcclusionClipContext.java:19) ~[?:?]
        at net.minecraft.world.level.BlockGetter.m_151358_(BlockGetterMixin.java:63) ~[server-1.20.1-20230612.114412-srg.jar%23165!/:?]
        at net.minecraft.world.level.BlockGetter.m_151361_(BlockGetterMixin.java:119) ~[server-1.20.1-20230612.114412-srg.jar%23165!/:?]
        at net.minecraft.world.level.BlockGetter.m_45547_(BlockGetterMixin.java:58) ~[server-1.20.1-20230612.114412-srg.jar%23165!/:?]
        at com.ticxo.modelengine.v1_20_R1.entity.EntityHandlerImpl.isVisible(EntityHandlerImpl.java:553) ~[?:?]
        at com.ticxo.modelengine.v1_20_R1.entity.EntityHandlerImpl.shouldCull(EntityHandlerImpl.java:545) ~[?:?]
        at com.ticxo.modelengine.api.entity.data.BukkitEntityData.updateCulledPlayer(BukkitEntityData.java:152) ~[?:?]
        at com.ticxo.modelengine.api.entity.data.BukkitEntityData.asyncUpdate(BukkitEntityData.java:69) ~[?:?]
        at com.ticxo.modelengine.api.entity.EntityDataTracker.asyncFetchEntityData(EntityDataTracker.java:32) ~[?:?]
        at com.ticxo.modelengine.api.utils.ticker.DualTicker.lambda$queueRepeatingAsyncTask$5(DualTicker.java:57) ~[?:?]
        at com.ticxo.modelengine.api.utils.ticker.Task.tick(Task.java:25) ~[?:?]
        at java.util.ArrayList.removeIf(ArrayList.java:1672) ~[?:?]
        at java.util.ArrayList.removeIf(ArrayList.java:1660) ~[?:?]
        at com.ticxo.modelengine.api.utils.ticker.PseudoThread.tick(PseudoThread.java:63) ~[?:?]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:82) ~[arclight-1.20.1-1.0.3-SNAPSHOT-7c67acb.jar%23163!/:arclight-1.20.1-1.0.3-SNAPSHOT-7c67acb]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[arclight-1.20.1-1.0.3-SNAPSHOT-7c67acb.jar%23163!/:arclight-1.20.1-1.0.3-SNAPSHOT-7c67acb]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:842) ~[?:?]
[12:51:41 INFO]: apple_LPG lost connection: Internal Exception: java.lang.NoClassDefFoundError: com/destroystokyo/paper/event/player/PlayerUseUnknownEntityEvent
[12:51:41 INFO]: apple_LPG left the game

**Comment by IzzelAliz** [comment]
ModelEngine 调了一个 paper 添加的方法，应该可以在 Spigot 上复现，建议报给 ME 作者

**Comment by rafucuk** [comment]
Meg 4 maintainers seems like to don't want to fix the issue. This have been reported before and they "resolve" the bug with saying use the new paper version. So we left to you @IzzelAliz we will need some paper patches or only (isOpaque) while it is only thing to reported.

**Comment by rafucuk** [comment]
just fixed with r4.05 sorry

**Comment by rafucuk** [comment]
PlayerUseUnknownEntityEvent is still a problem tho

**Comment by 303404Hi** [comment]
I wrote a patch for this.

It has been tested on Arclight 1.20.1-1.0.6

[ModelEngineSpigotFix.zip](https://github.com/user-attachments/files/25182878/ModelEngineSpigotFix.zip)
