### ISSUE TITLE
arclight-forge-1.19.4安装模组BiomesOPlenty (超多群系)报错无法运行

### ISSUE THREAD

**Issue by lmr126** [IzzelAliz/Arclight#1187]
### 请确认您已完成以下几件事

- [X] 正在使用最新的 Arclight
- [X] 已为所有插件及模组安装依赖
- [X] 已为所有插件及模组更新至最新版
- [X] 不可在 Spigot 复现
- [X] 不可在 Forge 复现

### Arclight 版本

arclight-forge-1.19.4-1.0.6

### Java 版本 | 操作系统

Ubuntu 22.04.2 LTS x86_64

### 相关 Mod/插件 的名称及版本

```raw
模组：BiomesOPlenty-1.19.4-17.3.0.542.jar
此模组前置：TerraBlender-forge-1.19.4-2.3.0.22.jar
```

### **运行日志内容：**
[11:19:43 INFO] [Arclight]: 正在向 Bukkit 注册 ...
[11:19:43 ERROR] [Arclight]: 处理 Forge 注册时出错 
java.lang.ExceptionInInitializerError: null
        at jdk.internal.misc.Unsafe.ensureClassInitialized0(Native Method) ~[?:?]
        at jdk.internal.misc.Unsafe.ensureClassInitialized(Unsafe.java:1155) ~[?:?]
        at sun.misc.Unsafe.ensureClassInitialized(Unsafe.java:743) ~[?:?]
        at io.izzel.arclight.api.Unsafe.ensureClassInitialized(Unsafe.java:249) ~[arclight-forge-1.19.4-1.0.6.jar%2382!/:arclight-1.19.4-1.0.6-0437196]
        at io.izzel.arclight.api.Unsafe.getStatic(Unsafe.java:50) ~[arclight-forge-1.19.4-1.0.6.jar%2382!/:arclight-1.19.4-1.0.6-0437196]
        at io.izzel.arclight.common.mod.server.BukkitRegistry.<clinit>(BukkitRegistry.java:83) ~[arclight-1.19.4-1.0.6-0437196.jar%23167!/:arclight-1.19.4-1.0.6-0437196]
        at io.izzel.arclight.common.mod.server.ArclightServer.createOrLoad(ArclightServer.java:76) ~[arclight-1.19.4-1.0.6-0437196.jar%23167!/:arclight-1.19.4-1.0.6-0437196]
        at net.minecraft.server.players.PlayerList.handler$zch000$arclight$loadServer(PlayerListMixin.java:1050) ~[server-1.19.4-20230314.122934-srg.jar%23175!/:?]
        at net.minecraft.server.players.PlayerList.<init>(PlayerListMixin.java:143) ~[server-1.19.4-20230314.122934-srg.jar%23175!/:?]
        at net.minecraft.server.dedicated.DedicatedPlayerList.<init>(DedicatedPlayerList.java:17) ~[server-1.19.4-20230314.122934-srg.jar%23175!/:?]
        at net.minecraft.server.dedicated.DedicatedServer.m_7038_(DedicatedServerMixin.java:158) ~[server-1.19.4-20230314.122934-srg.jar%23175!/:?]
        at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServerMixin.java:2037) ~[server-1.19.4-20230314.122934-srg.jar%23175!/:?]
        at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServerMixin.java:252) ~[server-1.19.4-20230314.122934-srg.jar%23175!/:?]
        at java.lang.Thread.run(Thread.java:842) ~[?:?]
Caused by: java.lang.IllegalArgumentException: value already present: null
        at com.google.common.collect.HashBiMap.put(HashBiMap.java:310) ~[guava-31.1-jre.jar%23106!/:?]
        at com.google.common.collect.HashBiMap.put(HashBiMap.java:290) ~[guava-31.1-jre.jar%23106!/:?]
        at org.bukkit.craftbukkit.v1_19_R3.util.CraftMagicNumbers.<clinit>(CraftMagicNumbersMixin.java:122) ~[arclight-1.19.4-1.0.6-0437196.jar%23167!/:arclight-1.19.4-1.0.6-0437196]
        ... 14 more
[11:19:43 ERROR]: Encountered an unexpected exception
java.lang.ExceptionInInitializerError: null
        at jdk.internal.misc.Unsafe.ensureClassInitialized0(Native Method) ~[?:?]
        at jdk.internal.misc.Unsafe.ensureClassInitialized(Unsafe.java:1155) ~[?:?]
        at sun.misc.Unsafe.ensureClassInitialized(Unsafe.java:743) ~[?:?]
        at io.izzel.arclight.api.Unsafe.ensureClassInitialized(Unsafe.java:249) ~[arclight-forge-1.19.4-1.0.6.jar%2382!/:arclight-1.19.4-1.0.6-0437196]
        at io.izzel.arclight.api.Unsafe.getStatic(Unsafe.java:50) ~[arclight-forge-1.19.4-1.0.6.jar%2382!/:arclight-1.19.4-1.0.6-0437196]
        at io.izzel.arclight.common.mod.server.BukkitRegistry.<clinit>(BukkitRegistry.java:83) ~[arclight-1.19.4-1.0.6-0437196.jar%23167!/:arclight-1.19.4-1.0.6-0437196]
        at io.izzel.arclight.common.mod.server.ArclightServer.createOrLoad(ArclightServer.java:76) ~[arclight-1.19.4-1.0.6-0437196.jar%23167!/:arclight-1.19.4-1.0.6-0437196]
        at net.minecraft.server.players.PlayerList.handler$zch000$arclight$loadServer(PlayerListMixin.java:1050) ~[server-1.19.4-20230314.122934-srg.jar%23175!/:?]
        at net.minecraft.server.players.PlayerList.<init>(PlayerListMixin.java:143) ~[server-1.19.4-20230314.122934-srg.jar%23175!/:?]
        at net.minecraft.server.dedicated.DedicatedPlayerList.<init>(DedicatedPlayerList.java:17) ~[server-1.19.4-20230314.122934-srg.jar%23175!/:?]
        at net.minecraft.server.dedicated.DedicatedServer.m_7038_(DedicatedServerMixin.java:158) ~[server-1.19.4-20230314.122934-srg.jar%23175!/:?]
        at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServerMixin.java:2037) ~[server-1.19.4-20230314.122934-srg.jar%23175!/:?]
        at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServerMixin.java:252) ~[server-1.19.4-20230314.122934-srg.jar%23175!/:?]
        at java.lang.Thread.run(Thread.java:842) ~[?:?]
Caused by: java.lang.IllegalArgumentException: value already present: null
        at com.google.common.collect.HashBiMap.put(HashBiMap.java:310) ~[guava-31.1-jre.jar%23106!/:?]
        at com.google.common.collect.HashBiMap.put(HashBiMap.java:290) ~[guava-31.1-jre.jar%23106!/:?]
        at org.bukkit.craftbukkit.v1_19_R3.util.CraftMagicNumbers.<clinit>(CraftMagicNumbersMixin.java:122) ~[arclight-1.19.4-1.0.6-0437196.jar%23167!/:arclight-1.19.4-1.0.6-0437196]
        ... 14 more
[11:19:44 FATAL]: Preparing crash report with UUID 4bc5f36d-6850-43d8-98cd-669e8da3e6eb
[11:19:44 ERROR]: This crash report has been saved to: /media/cuckoo/bendancaimi/ARCceshi/./crash-reports/crash-2024-01-12_11.19.44-server.txt

**### crash-reports内容：**
---- Minecraft Crash Report ----
// Why is it breaking :(

Time: 2024-01-12 10:14:44
Description: Exception in server tick loop

java.lang.IllegalStateException: Failed to initialize server
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServerMixin.java:2038) ~[server-1.19.4-20230314.122934-srg.jar%23163!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServerMixin.java:252) ~[server-1.19.4-20230314.122934-srg.jar%23163!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:A}
	at java.lang.Thread.run(Thread.java:842) ~[?:?] {re:mixin}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.19.4
	Minecraft Version ID: 1.19.4
	Operating System: Linux (amd64) version 5.19.0-46-generic
	Java Version: 17.0.9, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
	Memory: 626063192 bytes (597 MiB) / 1447034880 bytes (1380 MiB) up to 8388608000 bytes (8000 MiB)
	CPUs: 8
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i3-10100F CPU @ 3.60GHz
	Identifier: Intel64 Family 6 Model 165 Stepping 3
	Microarchitecture: unknown
	Frequency (GHz): 3.60
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 8
	Graphics card #0 name: TU106 [GeForce RTX 2060 SUPER]
	Graphics card #0 vendor: NVIDIA Corporation (0x10de)
	Graphics card #0 VRAM (MB): 288.00
	Graphics card #0 deviceId: 0x1f06
	Graphics card #0 versionInfo: unknown
	Memory slot #0 capacity (MB): 16384.00
	Memory slot #0 clockSpeed (GHz): -0.00
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 16384.00
	Memory slot #1 clockSpeed (GHz): -0.00
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 18047.21
	Virtual memory used (MB): 19121.06
	Swap memory total (MB): 2048.00
	Swap memory used (MB): 11.25
	JVM Flags: 0 total; 
	Server Running: true
	Data Packs: vanilla, mod:forge, mod:arclight (incompatible)
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Stable
	Is Modded: Definitely; Server brand changed to 'forge arclight/Executions'
	Type: Dedicated Server (map_server.txt)
	ModLauncher: 10.0.8+10.0.8+main.0ef7e830
	ModLauncher launch target: forgeserver
	ModLauncher naming: srg
	ModLauncher services: 
		mixin-0.8.5.jar mixin PLUGINSERVICE 
		arclight-forge-1.19.4-1.0.6.jar arclight_implementer PLUGINSERVICE 
		eventbus-6.0.3.jar eventbus PLUGINSERVICE 
		fmlloader-1.19.4-45.2.6.jar slf4jfixer PLUGINSERVICE 
		fmlloader-1.19.4-45.2.6.jar object_holder_definalize PLUGINSERVICE 
		fmlloader-1.19.4-45.2.6.jar runtime_enum_extender PLUGINSERVICE 
		fmlloader-1.19.4-45.2.6.jar capability_token_subclass PLUGINSERVICE 
		accesstransformers-8.0.4.jar accesstransformer PLUGINSERVICE 
		fmlloader-1.19.4-45.2.6.jar runtimedistcleaner PLUGINSERVICE 
		modlauncher-10.0.8.jar mixin TRANSFORMATIONSERVICE 
		modlauncher-10.0.8.jar fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		lowcodefml@null
		javafml@null
	Mod List: 
		server-1.19.4-20230314.122934-srg.jar             |Minecraft                     |minecraft                     |1.19.4              |DONE      |Manifest: NOSIGNATURE
		forge-1.19.4-45.2.6-universal.jar                 |Forge                         |forge                         |45.2.6              |DONE      |Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
		arclight-1.19.4-1.0.6-0437196.jar                 |Arclight Mod                  |arclight                      |1.19.4-1.0.6-0437196|DONE      |Manifest: NOSIGNATURE
	Crash Report UUID: 19321def-9681-44c0-8919-fe4637145bef
	FML: 45.2
	Forge: net.minecraftforge:45.2.6

### 复现步骤

1.运行arclight-forge-1.19.4-1.0.6自动补全文件后
2.安装 BiomesOPlenty和TerraBlender，运行后报错抛异常

### 报错信息

[latest.log](https://github.com/IzzelAliz/Arclight/files/13911173/latest.log)
[crash-2024-01-12_10.14.44-server.txt](https://github.com/IzzelAliz/Arclight/files/13911181/crash-2024-01-12_10.14.44-server.txt)

**Comment by lmr126** [comment]
java：jdk-17.0.9

**Comment by IzzelAliz** [comment]
1.19.4 不再支持
