### ISSUE TITLE
[1.19.4] Error HappyHUD

### ISSUE THREAD

**Issue by Skytoone** [IzzelAliz/Arclight#1188]
### I have confirmed that ...

- [X] Arclight is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Forge

### Arclight version

forge arclight/Executions 1.19.4

### OS & Java versions

Java 17

### Plugins and Mods

```raw
Mods :
minecraft server-1.19.4-20230314.122934-srg.jar : minecraft (1.19.4) - 1
• mods_folder Guidebook-1.19.4-3.8.0.jar : gbook (3.8.0) - 1
• mods_folder ironfurnaces-1.19.4-3.8.0.jar : ironfurnaces (3.8.0) - 1
• mods_folder player-animation-lib-forge-1.0.2+1.19.4.jar : playeranimator (1.0.2+1.19.4) - 1
• mods_folder jei-1.19.4-forge-13.1.0.16.jar : jei (13.1.0.16) - 1
• mods_folder inventorio-1.19.4-forge-1.9.1.jar : inventorio (1.9.1) - 1
• mods_folder RoughlyEnoughItems-11.0.683-forge.jar : roughlyenoughitems (11.0.683) - 1
• JarInJar kffmod-4.2.0.jar : kotlinforforge (4.2.0) - 1
• mods_folder journeymap-1.19.4-5.9.7-forge.jar : journeymap (5.9.7) - 1
• mods_folder citadel-2.3.4-1.19.4.jar : citadel (2.3.4) - 1
• mods_folder alexsmobs-1.22.3.jar : alexsmobs (1.22.3) - 1
• mods_folder StorageDrawers-1.19.4-11.3.1.jar : storagedrawers (11.3.1) - 1
• mods_folder YungsApi-1.19.4-Forge-3.10.1.jar : yungsapi (1.19.4-Forge-3.10.1) - 1
• mods_folder invhud.forge.1.19.4-3.4.9.jar : inventoryhud (3.4.9) - 1
• mods_folder architectury-8.2.89-forge.jar : architectury (8.2.89) - 1
• mods_folder mcw-furniture-3.2.1-mc1.19.4forge.jar : mcwfurnitures (3.2.1) - 1
• arclight arclight-1.19.4-1.0.6-0437196.jar : arclight (1.19.4-1.0.6-0437196) - 1
• mods_folder ruby-2.5.jar : ruby (2.5) - 1
• mods_folder PuzzlesLib-v6.0.11-1.19.4-Forge.jar : puzzleslib (6.0.11) - 1
• mods_folder YungsBetterNetherFortresses-1.19.4-Forge-1.2.0.jar : betterfortresses (1.19.4-Forge-1.2.0) - 1
• mods_folder cloth-config-10.1.117-forge.jar : cloth_config (10.1.117) - 1
• mods_folder voicechat-forge-1.19.4-2.4.32.jar : voicechat (1.19.4-2.4.32) - 1
• mods_folder soundphysics-forge-1.19.4-1.1.1.jar : sound_physics_remastered (1.19.4-1.1.1) - 1
• minecraft forge-1.19.4-45.2.6-universal.jar : forge (45.2.6) - 1
• mods_folder Aquaculture-1.19.4-2.4.17.jar : aquaculture (1.19.4-2.4.17) - 1
• mods_folder Emotecraft-Mod-Forge-1.19.4.jar : emotecraft (2.2.7-b.build.48) - 1

Plugins :
CustomDeathMessages, GFly, PlaceholderAPI, Vault, UltraPermissions, ChatManager, ProtocolLib, Multiverse-Core, Spartan, WorldEdit, DecentHolograms, TAB, IllegalStack, WorldBorder, LiteBans, WorldGuard, Oraxen, DeluxeMenus, WarpSystem
```

### Description

When I start the server it displays this error in the HappyHUD console, so I went to see the developer of this plugin but he told me to direct me to you to fix this problem.

```
[22:52:55 WARN] [HappyHud]: Task #306 for HappyHUD v1.0.11-RELEASE generated an exception
java.lang.IllegalStateException: Unable to construct new instance using private net.minecraft.network.protocol.game.ClientboundBossEventPacket$UpdateNameOperation(net.minecraft.network.FriendlyByteBuf)
at com.comphenix.protocol.reflect.accessors.DefaultConstrutorAccessor.invoke(DefaultConstrutorAccessor.java:21) ~[?:?]
at com.comphenix.protocol.wrappers.AutoWrapper.unwrap(AutoWrapper.java:126) ~[?:?]
at com.comphenix.protocol.wrappers.AutoWrapper.getGeneric(AutoWrapper.java:187) ~[?:?]
at com.ehhthan.happyhud.comp.protocollib.wrapper.WrapperPlayServerBoss$1.getGeneric(WrapperPlayServerBoss.java:51) ~[?:?]
at com.ehhthan.happyhud.comp.protocollib.wrapper.WrapperPlayServerBoss$1.getGeneric(WrapperPlayServerBoss.java:39) ~[?:?]
at com.comphenix.protocol.reflect.StructureModifier.writeInternal(StructureModifier.java:357) ~[?:?]
at com.comphenix.protocol.reflect.StructureModifier.write(StructureModifier.java:321) ~[?:?]
at com.ehhthan.happyhud.comp.protocollib.wrapper.WrapperPlayServerBoss.setOperation(WrapperPlayServerBoss.java:138) ~[?:?]
at com.ehhthan.happyhud.api.bossbar.BossBarHandler.setHud(BossBarHandler.java:99) ~[?:?]
at com.ehhthan.happyhud.api.HudHolder.lambda$send$2(HudHolder.java:190) ~[?:?]
at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftTask.run(CraftTask.java:82) ~[arclight-1.19.4-1.0.6-0437196.jar%23173!/:arclight-1.19.4-1.0.6-0437196]
at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftSchedulerMixin.java:415) ~[arclight-1.19.4-1.0.6-0437196.jar%23173!/:arclight-1.19.4-1.0.6-0437196]
at net.minecraft.server.MinecraftServer.handler$zbc000$arclight$runScheduler(MinecraftServerMixin.java:2322) ~[server-1.19.4-20230314.122934-srg.jar%23187!/:?]
at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServerMixin.java) ~[server-1.19.4-20230314.122934-srg.jar%23187!/:?]
at net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServerMixin.java:284) ~[server-1.19.4-20230314.122934-srg.jar%23187!/:?]
at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServerMixin.java:817) ~[server-1.19.4-20230314.122934-srg.jar%23187!/:?]
at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServerMixin.java:2079) ~[server-1.19.4-20230314.122934-srg.jar%23187!/:?]
at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServerMixin.java:252) ~[server-1.19.4-20230314.122934-srg.jar%23187!/:?]
at java.lang.Thread.run(Thread.java:840) ~[?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "net.minecraft.network.FriendlyByteBuf.m_130238_()" because "p_178725_" is null
at net.minecraft.network.protocol.game.ClientboundBossEventPacket$UpdateNameOperation.<init>(ClientboundBossEventPacket.java:230) ~[server-1.19.4-20230314.122934-srg.jar%23187!/:?]
at com.comphenix.protocol.reflect.accessors.DefaultConstrutorAccessor.invoke(DefaultConstrutorAccessor.java:19) ~[?:?]
... 18 more
```

### Step to reproduce

1. Install the HappyHUD plugin
2. Start server
3. Join the server
4. Display error in console

### Logs

https://pastebin.com/BNv4rFL9

**Comment by IzzelAliz** [comment]
1.19.4 is no longer supported. I'll still fix this in latest versions.
