### ISSUE TITLE
Trials 1.0.3 PlayerAttemptPickupItemEvent Error

### ISSUE THREAD

**Issue by rafucuk** [IzzelAliz/Arclight#1196]
### I have confirmed that ...

- [X] Arclight is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Forge

### Arclight version

arclight-forge-1.20.1-1.0.3

### OS & Java versions

openjdk version "17.0.9" 2023-10-17 OS:Ubuntu

### Plugins and Mods

```raw
MythicMobs
ModelEngine
MythicLib
LevelledMobs
```

### Description

MythicMobs did not loaded correcly and its depends giving out errors because of that

### Logs

```
[20Jan2024 21:45:00.601] [Server thread/ERROR] [Minecraft/]: Error occurred while enabling MythicMobs v5.6.0-SNAPSHOT-64003811 (Is it up to date?)
java.lang.NoClassDefFoundError: org/bukkit/event/player/PlayerAttemptPickupItemEvent
	at io.lumine.mythic.core.drops.DropExecutor.<init>(DropExecutor.java:73) ~[?:?] {}
	at io.lumine.mythic.bukkit.MythicBukkit.enable(MythicBukkit.java:171) ~[?:?] {}
	at io.lumine.mythic.bukkit.utils.plugin.LuminePlugin.onEnable(LuminePlugin.java:86) ~[?:?] {}
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPluginMixin.java:266) ~[arclight-1.20.1-1.0.3-ec79af9.jar%23230!/:arclight-1.20.1-1.0.3-ec79af9] {re:mixin,re:mixin,re:classloading,pl:mixin:APP:mixins.arclight.bukkit.json:JavaPluginMixin,pl:mixin:A,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin}
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoaderMixin.java:342) ~[arclight-1.20.1-1.0.3-ec79af9.jar%23230!/:arclight-1.20.1-1.0.3-ec79af9] {re:mixin,re:classloading,pl:mixin:APP:mixins.arclight.bukkit.json:JavaPluginLoaderMixin,pl:mixin:A,re:mixin}
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[arclight-1.20.1-1.0.3-ec79af9.jar%23230!/:arclight-1.20.1-1.0.3-ec79af9] {re:mixin,re:classloading,re:mixin}
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServerMixin.java:546) ~[arclight-1.20.1-1.0.3-ec79af9.jar%23230!/:arclight-1.20.1-1.0.3-ec79af9] {re:mixin,re:classloading,pl:mixin:APP:mixins.arclight.bukkit.json:CraftServerMixin,pl:mixin:A,re:mixin,re:mixin,re:mixin,re:mixin}
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServerMixin.java:460) ~[arclight-1.20.1-1.0.3-ec79af9.jar%23230!/:arclight-1.20.1-1.0.3-ec79af9] {re:mixin,re:classloading,pl:mixin:APP:mixins.arclight.bukkit.json:CraftServerMixin,pl:mixin:A,re:mixin,re:mixin,re:mixin,re:mixin}
	at net.minecraft.server.MinecraftServer.handler$bcj000$arclight$enablePlugins(MinecraftServerMixin.java:2137) ~[server-1.20.1-20230612.114412-srg.jar%23299!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:APP:fastload.mixins.json:server.MinecraftServerMixin,pl:mixin:APP:citadel.mixins.json:MinecraftServerMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.MinecraftServerMixin,pl:mixin:APP:crafttweaker.mixins.json:common.access.server.AccessMinecraftServer,pl:mixin:A,re:mixin,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_129815_(MinecraftServerMixin.java:385) ~[server-1.20.1-20230612.114412-srg.jar%23299!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:APP:fastload.mixins.json:server.MinecraftServerMixin,pl:mixin:APP:citadel.mixins.json:MinecraftServerMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.MinecraftServerMixin,pl:mixin:APP:crafttweaker.mixins.json:common.access.server.AccessMinecraftServer,pl:mixin:A,re:mixin,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_130006_(MinecraftServerMixin.java:308) ~[server-1.20.1-20230612.114412-srg.jar%23299!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:APP:fastload.mixins.json:server.MinecraftServerMixin,pl:mixin:APP:citadel.mixins.json:MinecraftServerMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.MinecraftServerMixin,pl:mixin:APP:crafttweaker.mixins.json:common.access.server.AccessMinecraftServer,pl:mixin:A,re:mixin,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.server.dedicated.DedicatedServer.m_7038_(DedicatedServerMixin.java:164) ~[server-1.20.1-20230612.114412-srg.jar%23299!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.dedicated.DedicatedServerMixin,pl:mixin:A,re:mixin,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServerMixin.java:2028) ~[server-1.20.1-20230612.114412-srg.jar%23299!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:APP:fastload.mixins.json:server.MinecraftServerMixin,pl:mixin:APP:citadel.mixins.json:MinecraftServerMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.MinecraftServerMixin,pl:mixin:APP:crafttweaker.mixins.json:common.access.server.AccessMinecraftServer,pl:mixin:A,re:mixin,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServerMixin.java:251) ~[server-1.20.1-20230612.114412-srg.jar%23299!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:APP:fastload.mixins.json:server.MinecraftServerMixin,pl:mixin:APP:citadel.mixins.json:MinecraftServerMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.MinecraftServerMixin,pl:mixin:APP:crafttweaker.mixins.json:common.access.server.AccessMinecraftServer,pl:mixin:A,re:mixin,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at java.lang.Thread.run(Thread.java:840) ~[?:?] {re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin}
Caused by: java.lang.ClassNotFoundException: org.bukkit.event.player.PlayerAttemptPickupItemEvent
	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoaderMixin.java:147) ~[arclight-1.20.1-1.0.3-ec79af9.jar%23230!/:arclight-1.20.1-1.0.3-ec79af9] {re:mixin,re:classloading,pl:mixin:APP:mixins.arclight.bukkit.json:PluginClassLoaderMixin,pl:mixin:A,re:mixin}
	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoaderMixin.java:99) ~[arclight-1.20.1-1.0.3-ec79af9.jar%23230!/:arclight-1.20.1-1.0.3-ec79af9] {re:mixin,re:classloading,pl:mixin:APP:mixins.arclight.bukkit.json:PluginClassLoaderMixin,pl:mixin:A,re:mixin}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?] {re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin}
	... 15 more
```

**Comment by rafucuk** [comment]
Do not use dev builds fixed.
