### ISSUE TITLE
FarmControl doesn't initiallize

### ISSUE THREAD

**Issue by Dum4G** [IzzelAliz/Arclight#120]
### I am running

* **Arclight** 1.16.4-1.0.11-SNAPSHOT-feb567a 

* **This is the latest development version** [N]

<details>
  <summary>Click to expand</summary>

* **Java** 8 275 

* **Operating System** Debian 10

* **Plugins**  LuckPerms, SkinsRestorer, UberEnchant, Chunky, VillagerOptimiser, spark, Vault, ConsoleSpamFix, ProtocolLib, FastAsyncWorldEdit (WorldEdit), Essentials, EssentialsChat, TAB, IllegalStack, EssentialsSpawn, WorldGuard, BanItem, AuthMe, CoreProtect, LWC

* **Mods** • minecraft forge-1.16.4-35.1.28-server.jar : minecraft (1.16.4) - 1
• mods_folder mcw-bridges-1.0.4-mc1.16.4.jar : mcwbridges (1.0.4) - 1
• mods_folder decorative_blocks-1.16.4-1.6.0.jar : decorative_blocks (1.6.0) - 1
• mods_folder eternalwinter-1.3.jar : eternalwinter (1.3) - 1
• mods_folder buildersaddition-1.16.4-20201130b.jar : buildersaddition (1.16.4-20201130b) - 1
• mods_folder BiomesOPlenty-1.16.4-13.0.0.421-universal.jar : biomesoplenty (1.16.4-13.0.0.418) - 1
• mods_folder FastFurnace-1.16.3-4.3.0.jar : fastfurnace (4.3.0) - 1
• mods_folder CoronaMask-1.16.4-v1.jar : corona_mask (1.0.0) - 1
• mods_folder valhelsia_structures-16.0.5.jar : valhelsia_structures (16.0.5) - 1
• mods_folder mcws-roofs-2.0.0-mc1.16.4.jar : mcwroofs (2.0.0) - 1
• mods_folder dungeons-plus-1.16.4-1.1.0.jar : dungeons_plus (1.1.0) - 1
• mods_folder AI-Improvements-1.16.2-0.3.0.jar : aiimprovements (0.3.0) - 1
• mods_folder additional_lights-1.16.4-2.1.3.jar : additional_lights (2.1.3) - 1
• arclight arclight-forge-1.16-1.0.11-SNAPSHOT.jar : arclight (1.16.4-1.0.11-SNAPSHOT-feb567a) - 1
• mods_folder trashcans-1.0.3-mc1.16.4.jar : trashcans (1.0.3) - 1
• mods_folder FallingTree-Forge-1.16.4-2.7.0.jar : falling_tree (2.7.0) - 1
• maven_libs forge-1.16.4-35.1.28-universal.jar : forge (35.1.28) - 1
• mods_folder pamhc2foodcore-1.16.3-1.0.0.jar : pamhc2foodcore (version) - 1
• mods_folder structure-gel-api-1.16.4-1.7.2.jar : structure_gel (1.7.2) - 1
• mods_folder FastWorkbench-1.16.3-4.4.1.jar : fastbench (4.4.1) - 1
• mods_folder CookingForBlockheads_1.16.3-9.2.2.jar : cookingforblockheads (9.2.2) - 1
• mods_folder christmasfestivity-1.3.5-1.16.4.jar : christmasfestivity (1.3.5-1.16.4) - 1
• mods_folder Placebo-1.16.3-4.3.3.jar : placebo (4.3.3) - 1</details>

### Description

FarmControl plugin fails to initiallize, command suggestions are broken

**Reproducible in Forge** [N]

**Reproducible in Spigot** [N]

### Logs

```
[08 эт2021 02:22:20.164] [Server thread/ERROR] [Minecraft/]: Error occurred while enabling FarmControl v1.1.0 (Is it up to date?)
java.lang.ExceptionInInitializerError: null
	at com.froobworld.farmcontrol.HookManager.<init>(HookManager.java:20) ~[?:?]
	at com.froobworld.farmcontrol.FarmControl.onEnable(FarmControl.java:29) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPluginMixin.java:263) ~[arclight:arclight-1.16.4-1.0.11-SNAPSHOT-feb567a]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoaderMixin.java:351) ~[arclight:arclight-1.16.4-1.0.11-SNAPSHOT-feb567a]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[arclight:arclight-1.16.4-1.0.11-SNAPSHOT-feb567a]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServerMixin.java:494) ~[arclight:arclight-1.16.4-1.0.11-SNAPSHOT-feb567a]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServerMixin.java:2246) ~[arclight:arclight-1.16.4-1.0.11-SNAPSHOT-feb567a]
	at net.minecraft.server.MinecraftServer.handler$zpp000$arclight$enablePlugins(MinecraftServerMixin.java:1972) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240787_a_(MinecraftServerMixin.java:382) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240800_l__(MinecraftServerMixin.java:308) ~[?:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServerMixin.java:168) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServerMixin.java:1856) ~[?:?]
	at net.minecraft.server.MinecraftServer.lambda$startServer$0(MinecraftServerMixin.java:232) ~[?:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]
Caused by: com.froobworld.farmcontrol.lib.joor.ReflectException: java.lang.ClassNotFoundException: net.minecraft.server.dedicated.MinecraftServer
	at com.froobworld.farmcontrol.lib.joor.Reflect.forName(Reflect.java:959) ~[?:?]
	at com.froobworld.farmcontrol.lib.joor.Reflect.onClass(Reflect.java:170) ~[?:?]
	at com.froobworld.farmcontrol.hook.tick.SpigotTickHook.<clinit>(SpigotTickHook.java:15) ~[?:?]
	... 14 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.server.dedicated.MinecraftServer
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoaderMixin.java:561) ~[arclight:arclight-1.16.4-1.0.11-SNAPSHOT-feb567a]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoaderMixin.java:96) ~[arclight:arclight-1.16.4-1.0.11-SNAPSHOT-feb567a]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_252]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_252]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_252]
	at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_252]
	at io.izzel.arclight.common.mod.util.remapper.generated.ArclightReflectionHandler_0.redirectForName(ArclightReflectionHandler.java:43) ~[arclight:arclight-1.16.4-1.0.11-SNAPSHOT-feb567a]
	at io.izzel.arclight.common.mod.util.remapper.generated.ArclightReflectionHandler_0.redirectForName(ArclightReflectionHandler.java:27) ~[arclight:arclight-1.16.4-1.0.11-SNAPSHOT-feb567a]
	at com.froobworld.farmcontrol.lib.joor.Reflect.forName(Reflect.java:956) ~[?:?]
	at com.froobworld.farmcontrol.lib.joor.Reflect.onClass(Reflect.java:170) ~[?:?]
	at com.froobworld.farmcontrol.hook.tick.SpigotTickHook.<clinit>(SpigotTickHook.java:15) ~[?:?]
	... 14 more
```
[debug.log](https://github.com/IzzelAliz/Arclight/files/5784419/debug.log)

**Comment by IzzelAliz** [comment]
Please test with latest build and see if it is fixed
