### ISSUE TITLE
[Minor] NetworkManager: handleDisconnection() called twice

### ISSUE THREAD

**Issue by Dum4G** [IzzelAliz/Arclight#122]
### I am running

* **Arclight** 1.16.4-1.0.11-SNAPSHOT-03401a4 

* **This is the latest development version** [Y]

<details>
  <summary>Click to expand</summary>

* **Java** 8 275 

* **Operating System** Debian 10

* **Plugins**  LuckPerms, SkinsRestorer, UberEnchant, Chunky, VillagerOptimiser, spark, Vault, ConsoleSpamFix, ProtocolLib, FastAsyncWorldEdit (WorldEdit), Essentials, EssentialsChat, TAB, IllegalStack, EssentialsSpawn, WorldGuard, BanItem, AuthMe, CoreProtect, LWC, FarmControl

* **Mods** • minecraft forge-1.16.4-35.1.28-server.jar : minecraft (1.16.4) - 1
• mods_folder mcw-bridges-1.0.4-mc1.16.4.jar : mcwbridges (1.0.4) - 1
• mods_folder decorative_blocks-1.16.4-1.6.0.jar : decorative_blocks (1.6.0) - 1
• mods_folder eternalwinter-1.3.jar : eternalwinter (1.3) - 1
• mods_folder buildersaddition-1.16.4-20201130b.jar : buildersaddition (1.16.4-20201130b) - 1
• mods_folder BiomesOPlenty-1.16.4-13.0.0.421-universal.jar : biomesoplenty (1.16.4-13.0.0.418) - 1
• mods_folder FastFurnace-1.16.3-4.3.0.jar : fastfurnace (4.3.0) - 1
• mods_folder CoronaMask-1.16.4-v1.jar : corona_mask (1.0.0) - 1
• mods_folder valhelsia_structures-16.0.5.jar : valhelsia_structures (16.0.5) - 1
• mods_folder mcws-roofs-2.0.0-mc1.16.4.jar : mcwroofs (2.0.0) - 1
• mods_folder dungeons-plus-1.16.4-1.1.0.jar : dungeons_plus (1.1.0) - 1
• mods_folder AI-Improvements-1.16.2-0.3.0.jar : aiimprovements (0.3.0) - 1
• mods_folder additional_lights-1.16.4-2.1.3.jar : additional_lights (2.1.3) - 1
• arclight arclight-forge-1.16-1.0.11-SNAPSHOT.jar : arclight (1.16.4-1.0.11-SNAPSHOT-feb567a) - 1
• mods_folder trashcans-1.0.3-mc1.16.4.jar : trashcans (1.0.3) - 1
• mods_folder FallingTree-Forge-1.16.4-2.7.0.jar : falling_tree (2.7.0) - 1
• maven_libs forge-1.16.4-35.1.28-universal.jar : forge (35.1.28) - 1
• mods_folder pamhc2foodcore-1.16.3-1.0.0.jar : pamhc2foodcore (version) - 1
• mods_folder structure-gel-api-1.16.4-1.7.2.jar : structure_gel (1.7.2) - 1
• mods_folder FastWorkbench-1.16.3-4.4.1.jar : fastbench (4.4.1) - 1
• mods_folder CookingForBlockheads_1.16.3-9.2.2.jar : cookingforblockheads (9.2.2) - 1
• mods_folder christmasfestivity-1.3.5-1.16.4.jar : christmasfestivity (1.3.5-1.16.4) - 1
• mods_folder Placebo-1.16.3-4.3.3.jar : placebo (4.3.3) - 1</details>

### Description

I'm not even sure if it's Arclight problem but Essentials team hates hybrid forks. Whenever someone quits the server it shows this warning. I suppose it started to occur in recet buids with newer Forge versions, tested against build 2.19-17 that I used before and the most recent EssentialX build

**Reproducible in Forge** [N]

**Reproducible in Spigot** [Supposedly not]

### Logs

```
[19:34:12] [Server thread/WARN] [Essentials/]: Task #30 for Essentials v2.19.0-dev+17-dda4d58 generated an exception
java.util.ConcurrentModificationException: null
        at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:911) ~[?:1.8.0_275] {}
        at java.util.ArrayList$Itr.next(ArrayList.java:861) ~[?:1.8.0_275] {}
        at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:47) ~[arclight-forge-1.16-1.0.11-SNAPSHOT.jar:arclight-1.16.4-1.0.11-SNAPSHOT-03401a4] {}
        at java.util.Collections$UnmodifiableCollection$1.next(Collections.java:1044) ~[?:1.8.0_275] {}
        at com.earth2me.essentials.EssentialsTimer.run(EssentialsTimer.java:47) ~[?:?] {re:classloading,re:classloading,re:classloading}
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:81) ~[arclight:arclight-1.16.4-1.0.11-SNAPSHOT-03401a4] {re:classloading}
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:400) ~[arclight:arclight-1.16.4-1.0.11-SNAPSHOT-03401a4] {re:mixin,re:classloading}
        at net.minecraft.server.MinecraftServer.handler$zpp000$arclight$runScheduler(MinecraftServerMixin.java:2132) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServerMixin.java) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServerMixin.java:291) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.dedicated.DedicatedServerMixin,pl:mixin:A,re:mixin,pl:accesstransformer:B}
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServerMixin.java:786) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServerMixin.java:1894) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.lambda$startServer$0(MinecraftServerMixin.java:232) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_275] {}
[19:34:12] [Server thread/WARN] [minecraft/NetworkManager]: handleDisconnection() called twice
```

**Comment by IzzelAliz** [comment]
This seems like a Essentials error. Maybe ask them for help.
