### ISSUE TITLE
Internal Server Error - Please help me

### ISSUE THREAD

**Issue by OrangeLol** [IzzelAliz/Arclight#1236]
### I have confirmed that ...

- [X] Arclight is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Forge

### Arclight version

arclight-1.19.2-1.0.4-4dbbff1 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT)

### OS & Java versions

JAVA JRE 17

### Plugins and Mods

```raw
• mods_folder botarium-forge-1.19.2-1.9.1.jar : botarium (1.9.1) - 1
• mods_folder Nightmare - Epic Siege Mod 1.19.2 v0.6.jar : nightmareinminecraft (1.0) - 1
• mods_folder appliedenergistics2-forge-12.9.9.jar : ae2 (12.9.9) - 1
• mods_folder FunMod 5.5.jar : funmod (5.5) - 1
• mods_folder InsaneLib-1.7.5-mc1.19.2.jar : insanelib (1.7.5) - 1
• mods_folder Heart_Container_Mod_1.0.1_1.19.2.jar : heart_container_mod (1.0.1) - 1
• mods_folder waystones-forge-1.19.2-11.4.2.jar : waystones (11.4.2) - 1
• mods_folder itemupgrader-core-1.0.4.jar : itemupgrader (1.0.4) - 1
• mods_folder Placebo-1.19.2-7.3.5.jar : placebo (7.3.5) - 1
• mods_folder citadel-2.1.4-1.19.jar : citadel (2.1.4) - 1
• mods_folder YungsApi-1.19.2-Forge-3.8.10.jar : yungsapi (1.19.2-Forge-3.8.10) - 1
• mods_folder DungeonCrawl-1.19-2.3.12.jar : dungeoncrawl (2.3.12) - 1
• mods_folder u_team_core-1.19.2-4.4.3.260.jar : uteamcore (4.4.3.260) - 1
• mods_folder Apotheosis-1.19.2-6.4.1.jar : apotheosis (6.4.1) - 1
• mods_folder ProgressiveBosses-3.7.5-mc1.19.2.jar : progressivebosses (3.7.5) - 1
• mods_folder balm-forge-1.19.2-4.6.0.jar : balm (4.6.0) - 1
• mods_folder blueprint-1.19.2-6.2.0.jar : blueprint (6.2.0) - 1
• mods_folder savage_and_ravage-1.19.2-5.0.5.jar : savage_and_ravage (5.0.5) - 1
• mods_folder biggerstacks-1.19.2-3.8.1-all.jar : biggerstacks (1.19.2-3.8.1) - 1
• mods_folder cloth-config-8.3.115-forge.jar : cloth_config (8.3.115) - 1
• minecraft forge-1.19.2-43.3.7-universal.jar : forge (43.3.7) - 1
• mods_folder itemupgrader-1.1.0.jar : itemupgrader_content (1.1.0) - 1
• mods_folder TheOneWhoWatches-V1.3.0-1.19.2.jar : the_one_who_watches (1.3.0) - 1
• mods_folder structure_gel-1.19.2-2.7.3.jar : structure_gel (2.7.3) - 1
• minecraft server-1.19.2-20220805.130853-srg.jar : minecraft (1.19.2) - 1
• mods_folder cofh_core-1.19.2-10.3.1.48.jar : cofh_core (10.3.1) - 1
• JarInJar thermal_core-1.19.2-10.3.0.9.jar : thermal (10.3.0) - 1
• mods_folder tenshilib-1.19.2-1.6.15-forge.jar : tenshilib (1.19.2-1.6.15) - 1
• mods_folder voicechat-forge-1.19.2-2.5.5.jar : voicechat (1.19.2-2.5.5) - 1
• mods_folder TerraBlender-forge-1.19.2-2.0.1.136.jar : terrablender (2.0.1.136) - 1
• mods_folder BiomesOPlenty-1.19.2-17.1.1.162.jar : biomesoplenty (17.1.1.162) - 1
• mods_folder endrem_forge-5.2.1-R-1.19.X.jar : endrem (5.2.1-R-1.19.2) - 1
• mods_folder UnusualEnd1.19.2_V1.4.3.jar : unusualend (1.4.3) - 1
• mods_folder resourcefulconfig-forge-1.19.2-1.0.20.jar : resourcefulconfig (1.0.20) - 1
• mods_folder easy_villagers-1.19.2-1.0.17.jar : easy_villagers (1.19.2-1.0.17) - 1
• mods_folder L_Enders_Cataclysm-1.90 tongue fixed-1.19.2.jar : cataclysm (1.0) - 1
• mods_folder curios-forge-1.19.2-5.1.6.1.jar : curios (1.19.2-5.1.6.1) - 1
• JarInJar flywheel-forge-1.19.2-0.6.10-20.jar : flywheel (0.6.10-20) - 1
• mods_folder create-1.19.2-0.5.1.f.jar : create (0.5.1.f) - 1
• mods_folder Patchouli-1.19.2-77.jar : patchouli (1.19.2-77) - 1
• mods_folder shadowizardlib-1.19.2-1.0.8.jar : shadowizardlib (1.19.2-1.0.8) - 1
• mods_folder TFTH 0.2.jar : the_flesh_that_hates (1.0.0) - 1
• mods_folder thermal_foundation-1.19.2-10.3.1.57.jar : thermal_foundation (10.3.1) - 1
• mods_folder thermal_expansion-1.19.2-10.3.1.25.jar : thermal_expansion (10.3.1) - 1
• mods_folder resourcefullib-forge-1.19.2-1.1.24.jar : resourcefullib (1.1.24) - 1
• mods_folder spore_1.19.2_2.0.2b.jar : spore (2.0.2) - 1
• mods_folder lootr-1.19-0.4.25.67.jar : lootr (0.4.25.67) - 1
• arclight arclight-1.19.2-1.0.4-4dbbff1.jar : arclight (1.19.2-1.0.4-4dbbff1) - 1
• mods_folder YungsBetterEndIsland-1.19.2-Forge-1.0.jar : betterendisland (1.19.2-Forge-1.0) - 1
• mods_folder Aquaculture-1.19.2-2.4.8.jar : aquaculture (1.19.2-2.4.8) - 1
• mods_folder geckolib-forge-1.19-3.1.40.jar : geckolib3 (3.1.40) - 1
• mods_folder dreadsteel-1.19.2-1.1.6.jar : dreadsteel (1.19.2-1.1.6) - 1
• mods_folder ad_astra-forge-1.19.2-1.12.7.jar : ad_astra (1.12.7) - 1
```

### Description

I join the server , it says internal server error.
I have other client side mods such as rubidium , rubidium extra , pluto , saturn , and other...
I tried singlePlayer and it works perfectly fine

### Step to reproduce

1.Make an server
2.Download the mods : https://www.mediafire.com/file/wf6iynx1787wxls/mods.rar/file
3.Install the mods to the server , with arclight
4.Put mods to mods folder in .minecraft
5.Run Forge 1.19.2
6.Join the srver

### Logs

customer@apollopanel~ Server marked as running...

[11:22:36 WARN]: Failed to handle packet for /101.128.125.85:4930
net.minecraft.ReportedException: Ticking player
        at net.minecraft.server.level.ServerPlayer.m_9240_(ServerPlayerMixin.java:510) ~[server-1.19.2-20220805.130853-srg.jar%23257!/:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.m_9933_(ServerPlayNetHandlerMixin.java:264) ~[server-1.19.2-20220805.130853-srg.jar%23257!/:?]
        at net.minecraft.network.Connection.m_129483_(ConnectionMixin.java:248) ~[server-1.19.2-20220805.130853-srg.jar%23257!/:?]
        at net.minecraft.server.network.ServerConnectionListener.m_9721_(ServerConnectionListener.java:143) ~[server-1.19.2-20220805.130853-srg.jar%23257!/:?]
        at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServerMixin.java:880) ~[server-1.19.2-20220805.130853-srg.jar%23257!/:?]
        at net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServerMixin.java:292) ~[server-1.19.2-20220805.130853-srg.jar%23257!/:?]
        at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServerMixin.java:806) ~[server-1.19.2-20220805.130853-srg.jar%23257!/:?]
        at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServerMixin.java:2127) ~[server-1.19.2-20220805.130853-srg.jar%23257!/:?]
        at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServerMixin.java:244) ~[server-1.19.2-20220805.130853-srg.jar%23257!/:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.RuntimeException: Attempted to load class net/minecraft/client/player/LocalPlayer for invalid dist DEDICATED_SERVER
        at net.minecraftforge.fml.loading.RuntimeDistCleaner.processClassWithFlags(RuntimeDistCleaner.java:57) ~[fmlloader-1.19.2-43.3.7.jar%23100!/:1.0]
        at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:88) ~[modlauncher-10.0.8.jar%2387!/:?]
        at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-10.0.8.jar%2387!/:?]
        at cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:50) ~[modlauncher-10.0.8.jar%2387!/:?]
        at cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:113) ~[securejarhandler-2.1.4.jar:?]
        at cpw.mods.cl.ModuleClassLoader.lambda$findClass$15(ModuleClassLoader.java:219) ~[securejarhandler-2.1.4.jar:?]
        at cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:229) ~[securejarhandler-2.1.4.jar:?]
        at cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:219) ~[securejarhandler-2.1.4.jar:?]
        at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:135) ~[securejarhandler-2.1.4.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        at com.baranhan123.funmod.util.handlers.MobSpawnHandler.searchMobsAndApply(MobSpawnHandler.java:256) ~[FunMod%205.5.jar%23226!/:5.5]
        at com.baranhan123.funmod.util.handlers.__MobSpawnHandler_searchMobsAndApply_PlayerTickEvent.invoke(.dynamic) ~[FunMod%205.5.jar%23226!/:5.5]
        at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73) ~[eventbus-6.0.3.jar%2384!/:?]
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.3.jar%2384!/:?]
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.3.jar%2384!/:?]
        at net.minecraftforge.event.ForgeEventFactory.onPlayerPreTick(ForgeEventFactoryMixin.java:814) ~[forge-1.19.2-43.3.7-universal.jar%23262!/:?]
        at net.minecraft.world.entity.player.Player.m_8119_(PlayerMixin.java:216) ~[server-1.19.2-20220805.130853-srg.jar%23257!/:?]
        at net.minecraft.server.level.ServerPlayer.m_9240_(ServerPlayerMixin.java:447) ~[server-1.19.2-20220805.130853-srg.jar%23257!/:?]
        ... 9 more
[11:22:36 INFO]: R13i lost connection: Internal server error
[11:22:36 INFO] [voicechat]: [voicechat] Disconnecting client R13i
[11:22:36 INFO]: R13i left the game

**Comment by SNWCreations** [comment]
A mod tried to use client-specific class. Caused by funmod. Please remove it or contact its author.

**Comment by IzzelAliz** [comment]
This is not likely caused by Arclight. Ask authors of funmod if they can fix it.
