### ISSUE TITLE
1.20.4 Forge Fixed Installer Doesn't Work

### ISSUE THREAD

**Issue by AzureDoom** [IzzelAliz/Arclight#1247]
### I have confirmed that ...

- [X] Arclight is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Forge

### Arclight version

 arclight-forge-1.20.4-1.0.3-SNAPSHOT.jar 

### OS & Java versions

Ubuntu, Java 17

### Plugins and Mods

```raw
None, empty install
```

### Description

Download Forge release: https://github.com/IzzelAliz/Arclight/releases/tag/Whisper%2F1.0.3-SNAPSHOT
Start server jar
Crash due to forge iinstaller not downloading

### Step to reproduce

Download Forge release: https://github.com/IzzelAliz/Arclight/releases/tag/Whisper%2F1.0.3-SNAPSHOT
Start server jar
Crash due to forge iinstaller not downloading

### Logs

[01.03 21:16:54] [Server] Downloaded libraries/net/minecraft/server/1.20.4/server-1.20.4-bundled.jar
[01.03 21:16:54] [Server] java.lang.RuntimeExceptionFailed net.minecraftforge:forge:1.20.4-49.0.22:installer 
[01.03 21:16:54] [Server]   (1) java.lang.RuntimeExceptionHash not match, expect bd6b7ea945bfb954a33a8f13fe1e522a6c55c1a7 found cab4a14d4eadbd475d752eee9852c6ea948d47e4 in https://arclight.hypertention.cn/net/minecraftforge/forge/1.20.4-49.0.22/forge-1.20.4-49.0.22-installer.jar
[01.03 21:16:54] [Server]   (2) java.lang.RuntimeExceptionHash not match, expect bd6b7ea945bfb954a33a8f13fe1e522a6c55c1a7 found cab4a14d4eadbd475d752eee9852c6ea948d47e4 in https://repo.spongepowered.org/maven/net/minecraftforge/forge/1.20.4-49.0.22/forge-1.20.4-49.0.22-installer.jar
[01.03 21:16:54] [Server] java.lang.RuntimeExceptionFailed net.minecraftforge:forge:1.20.4-49.0.22:installer 
[01.03 21:16:54] [Server]   (1) java.lang.RuntimeExceptionHash not match, expect bd6b7ea945bfb954a33a8f13fe1e522a6c55c1a7 found cab4a14d4eadbd475d752eee9852c6ea948d47e4 in https://arclight.hypertention.cn/net/minecraftforge/forge/1.20.4-49.0.22/forge-1.20.4-49.0.22-installer.jar
[01.03 21:16:54] [Server]   (2) java.lang.RuntimeExceptionHash not match, expect bd6b7ea945bfb954a33a8f13fe1e522a6c55c1a7 found cab4a14d4eadbd475d752eee9852c6ea948d47e4 in https://repo.spongepowered.org/maven/net/minecraftforge/forge/1.20.4-49.0.22/forge-1.20.4-49.0.22-installer.jar
[01.03 21:16:54] [Server] 	at io.izzel.arclight.installer.MavenDownloader.get(MavenDownloader.java:55)
[01.03 21:16:54] [Server] 	at io.izzel.arclight.installer.MavenDownloader.get(MavenDownloader.java:10)
[01.03 21:16:54] [Server] 	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
[01.03 21:16:54] [Server] 	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
[01.03 21:16:54] [Server] 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
[01.03 21:16:54] [Server] 	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
[01.03 21:16:54] [Server] 	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
[01.03 21:16:54] [Server] 	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
[01.03 21:16:54] [Server] 	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
[01.03 21:16:54] [Server] Fail to launch Arclight.

### Server pack link (Optional)

none

**Comment by IzzelAliz** [comment]
fixed.
