### ISSUE TITLE
和机械动力兼容性不佳

### ISSUE THREAD

**Issue by Huaxidesu** [IzzelAliz/Arclight#125]
[crash-2021-01-10_22.30.27-server.txt](https://github.com/IzzelAliz/Arclight/files/5792853/crash-2021-01-10_22.30.27-server.txt)

这是今天的机械臂用砂纸擦石英蹦的，服务器无限重启，换了forge端正常
前几天还有用建筑大炮蹦的，开了原版forge端进服打掉服务器才不会无限重启，
现在已经换了原版forge端了
arclight-forge-1.15-1.0.15
Create 1.15 （机械动力）

**Comment by Akegarasu** [comment]
蓝图炮最新版依然会崩 靠近该区块后无限重启

**Comment by IzzelAliz** [comment]
> 
> 
> 蓝图炮最新版依然会崩 靠近该区块后无限重启

请提供报错

**Comment by Akegarasu** [comment]
* **Arclight** arclight-forge-1.16-1.0.11.jar

* **Mod 列表** 
? minecraft forge-1.16.4-35.1.29-server.jar : minecraft (1.16.4) - 1
? mods_folder [移除教学提示]IKnowWhatImDoing-3.1.0-forge.jar : iknowwhatimdoing (3.1.0) - 1
? mods_folder [鼠标手势]MouseTweaks-2.13-mc1.16.2.jar : mousetweaks (2.13) - 1
? mods_folder [高亮显示前置]Bookshelf-1.16.4-9.0.2.jar : bookshelf (9.0.2) - 1
? mods_folder [堆叠扩展]upsizer-mc1.16.4-6.1.1.jar : upsizer (6.1.1) - 1
? mods_folder [枪械]ava-1.5.9.jar : ava (1.5.9) - 1
? mods_folder [HWYLA]Hwyla-forge-1.10.11-B78_1.16.2.jar : waila (1.10.11-B78_1.16.2) - 1
? mods_folder [亮度显示前置]cloth-config-forge-4.1.0.jar : cloth-config (4.0) - 1
? arclight arclight-forge-1.16-1.0.11.jar : arclight (1.16.4-1.0.11-daf16fd) - 1
? mods_folder [倒置漏斗]Uppers-0.3.2.jar : uppers (0.3.2) - 1
? maven_libs forge-1.16.4-35.1.29-universal.jar : forge (35.1.29) - 1
? mods_folder [苹果皮]AppleSkin-mc1.16.2-forge-1.0.14.jar : appleskin (1.0.14) - 1
? mods_folder [高亮显示]WAWLA-1.16.3-6.0.1.jar : wawla (6.0.1) - 1
? mods_folder [箱子整理]Inventory-Tweaks-Renewed-Mod-1.16.4.jar : invtweaks (1.16.4-1.0.1) - 1
? mods_folder [机械动力]create-mc1.16.3_v0.3e.jar : create (mc1.16.3_v0.3e) - 1
? mods_folder [更多箱子]ironchest-1.16.4-11.2.10.jar : ironchest (1.16.4-11.2.10) - 1
? mods_folder [亮度显示]light-overlay-5.5.4.jar : lightoverlay-forge (NONE) - 1

* **插件列表**
MiniMOTD, ClearEntity, SignCommand, ElevatorSigns, GroupManager, PlaceholderAPI, PlugMan, AutoBroadcastLite, SignWarper, ProtocolLib, CratesLottery, InventoryRollback, SignEdit, LiteSignIn, AdvancedCleaner, VoxelSniper, PFWorlds, LoginBoxSss, TrashBin, Vault, Lores, JavaScriptLibrary, Essentials, ResourceWorld, Admin-GUI, AtMe, QuickShop, QSGUI, FastAsyncWorldEdit (WorldEdit), PlayerTitle, EssentialsProtect, EssentialsAntiBuild, CoreProtect

[错误日志]

<details><pre>
[0m[16:01:32] [Server thread/INFO] [Waila/]: Syncing config to akibanzu (705e3f9f-600e-3de2-a082-4b4b4d97dbac)
[m[33m[16:01:32] [Server thread/WARN] [minecraft/MinecraftServer]: Can't keep up! Is the server overloaded? Running 2751ms or 55 ticks behind
[m[0m[16:01:33] [Server thread/INFO] [Minecraft/]: -------- World Settings For [world] --------
[m[0m[16:01:33] [Server thread/INFO] [Minecraft/]: View Distance: 8
[m[0m[16:01:33] [Server thread/INFO] [Minecraft/]: Nerfing mobs spawned from spawners: false
[m[0m[16:01:33] [Server thread/INFO] [Minecraft/]: Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64
[m[0m[16:01:33] [Server thread/INFO] [Minecraft/]: Cactus Growth Modifier: 100%
[m[0m[16:01:33] [Server thread/INFO] [Minecraft/]: Cane Growth Modifier: 100%
[m[0m[16:01:33] [Server thread/INFO] [Minecraft/]: Melon Growth Modifier: 100%
[m[0m[16:01:33] [Server thread/INFO] [Minecraft/]: Mushroom Growth Modifier: 100%
[m[0m[16:01:33] [Server thread/INFO] [Minecraft/]: Pumpkin Growth Modifier: 100%
[m[0m[16:01:33] [Server thread/INFO] [Minecraft/]: Sapling Growth Modifier: 100%
[m[0m[16:01:33] [Server thread/INFO] [Minecraft/]: Beetroot Growth Modifier: 100%
[m[0m[16:01:33] [Server thread/INFO] [Minecraft/]: Carrot Growth Modifier: 100%
[m[0m[16:01:33] [Server thread/INFO] [Minecraft/]: Potato Growth Modifier: 100%
[m[0m[16:01:33] [Server thread/INFO] [Minecraft/]: Wheat Growth Modifier: 100%
[m[0m[16:01:33] [Server thread/INFO] [Minecraft/]: NetherWart Growth Modifier: 100%
[m[0m[16:01:33] [Server thread/INFO] [Minecraft/]: Vine Growth Modifier: 100%
[m[0m[16:01:33] [Server thread/INFO] [Minecraft/]: Cocoa Growth Modifier: 100%
[m[0m[16:01:33] [Server thread/INFO] [Minecraft/]: Bamboo Growth Modifier: 100%
[m[0m[16:01:33] [Server thread/INFO] [Minecraft/]: SweetBerry Growth Modifier: 100%
[m[0m[16:01:33] [Server thread/INFO] [Minecraft/]: Kelp Growth Modifier: 100%
[m[0m[16:01:33] [Server thread/INFO] [Minecraft/]: Entity Activation Range: An 32 / Mo 32 / Ra 48 / Mi 16 / Tiv true
[m[0m[16:01:33] [Server thread/INFO] [Minecraft/]: Hopper Transfer: 8 Hopper Check: 1 Hopper Amount: 1
[m[0m[16:01:33] [Server thread/INFO] [Minecraft/]: Max TNT Explosions: 100
[m[0m[16:01:33] [Server thread/INFO] [Minecraft/]: Tile Max Tick Time: 50ms Entity max Tick Time: 50ms
[m[0m[16:01:33] [Server thread/INFO] [Minecraft/]: Custom Map Seeds:  Village: 10387312 Desert: 14357617 Igloo: 14357618 Jungle: 14357619 Swamp: 14357620 Monument: 10387313 Ocean: 14357621 Shipwreck: 165745295 End City: 10387313 Slime: 987234911 Bastion: 30084232 Fortress: 30084232 Mansion: 10387319 Fossil: 14357921 Portal: 34222645
[m[0m[16:01:33] [Server thread/INFO] [Minecraft/]: Item Merge Radius: 2.5
[m[0m[16:01:33] [Server thread/INFO] [Minecraft/]: Experience Merge Radius: 3.0
[m[0m[16:01:33] [Server thread/INFO] [Minecraft/]: Arrow Despawn Rate: 1200 Trident Respawn Rate:1200
[m[0m[16:01:33] [Server thread/INFO] [Minecraft/]: Item Despawn Rate: 6000
[m[0m[16:01:33] [Server thread/INFO] [Minecraft/]: Mob Spawn Range: 6
[m[0m[16:01:33] [Server thread/INFO] [Minecraft/]: Allow Zombie Pigmen to spawn from portal blocks: true
[m[0m[16:01:33] [Server thread/INFO] [Minecraft/]: Zombie Aggressive Towards Villager: true
[m[1;31m[16:01:33] [Server thread/FATAL] [n.m.c.ForgeMod/]: Preparing crash report with UUID 5a08eff4-2b49-4b04-bf24-371776a87931
[m[1;31m[16:01:33] [Server thread/ERROR] [minecraft/MinecraftServer]: Encountered an unexpected exception
>net.minecraft.crash.ReportedException: Ticking block entity
at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServerMixin.java:854) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServerMixin.java:291) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.dedicated.DedicatedServerMixin,pl:mixin:A}
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServerMixin.java:786) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServerMixin.java:1895) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
at net.minecraft.server.MinecraftServer.lambda$startServer$0(MinecraftServerMixin.java:232) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
at java.lang.Thread.run(Unknown Source) [?:1.8.0_271] {}
>Caused by: java.lang.AbstractMethodError: Method com/simibubi/create/content/schematics/SchematicWorld.bridge$getAddEntityReason()Lorg/bukkit/event/entity/CreatureSpawnEvent$SpawnReason; is abstract
at com.simibubi.create.content.schematics.SchematicWorld.bridge$getAddEntityReason(SchematicWorld.java) ~[create:mc1.16.3_v0.3e] {re:classloading}
at net.minecraft.world.IServerWorld.func_242417_l(IServerWorldMixin.java:533) ~[?:?] {re:mixin,re:computing_frames,re:classloading,pl:mixin:APP:mixins.arclight.core.json:world.IServerWorldMixin,pl:mixin:A}
at net.minecraft.world.gen.feature.template.Template.lambda$addEntitiesToWorld$5(Template.java:427) ~[?:?] {re:classloading}
at java.util.Optional.ifPresent(Unknown Source) ~[?:1.8.0_271] {}
at net.minecraft.world.gen.feature.template.Template.addEntitiesToWorld(Template.java:419) ~[?:?] {re:classloading}
at net.minecraft.world.gen.feature.template.Template.func_237146_a_(Template.java:337) ~[?:?] {re:classloading}
at net.minecraft.world.gen.feature.template.Template.func_237152_b_(Template.java:203) ~[?:?] {re:classloading}
at net.minecraft.world.gen.feature.template.Template.func_237144_a_(Template.java:199) ~[?:?] {re:classloading}
at com.simibubi.create.content.schematics.block.SchematicannonTileEntity.initializePrinter(SchematicannonTileEntity.java:555) ~[create:mc1.16.3_v0.3e] {re:classloading,pl:runtimedistcleaner:A}
at com.simibubi.create.content.schematics.block.SchematicannonTileEntity.tickPrinter(SchematicannonTileEntity.java:349) ~[create:mc1.16.3_v0.3e] {re:classloading,pl:runtimedistcleaner:A}
at com.simibubi.create.content.schematics.block.SchematicannonTileEntity.func_73660_a(SchematicannonTileEntity.java:309) ~[create:mc1.16.3_v0.3e] {re:classloading,pl:runtimedistcleaner:A}
at net.minecraft.world.World.func_217391_K(WorldMixin.java:491) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:world.WorldMixin,pl:mixin:A,pl:runtimedistcleaner:A}
at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorldMixin.java:371) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:world.server.ServerWorldMixin,pl:mixin:A,pl:arclight_implementer:async,pl:arclight_implementer:A,pl:runtimedistcleaner:A}
at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServerMixin.java:850) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
... 5 more
[m[1;31m[16:01:33] [Server thread/ERROR] [minecraft/MinecraftServer]:  Cause of unexpected exception was
>java.lang.AbstractMethodError: Method com/simibubi/create/content/schematics/SchematicWorld.bridge$getAddEntityReason()Lorg/bukkit/event/entity/CreatureSpawnEvent$SpawnReason; is abstract
at com.simibubi.create.content.schematics.SchematicWorld.bridge$getAddEntityReason(SchematicWorld.java) ~[create:mc1.16.3_v0.3e] {re:classloading}
at net.minecraft.world.IServerWorld.func_242417_l(IServerWorldMixin.java:533) ~[?:?] {re:mixin,re:computing_frames,re:classloading,pl:mixin:APP:mixins.arclight.core.json:world.IServerWorldMixin,pl:mixin:A}
at net.minecraft.world.gen.feature.template.Template.lambda$addEntitiesToWorld$5(Template.java:427) ~[?:?] {re:classloading}
at java.util.Optional.ifPresent(Unknown Source) ~[?:1.8.0_271] {}
at net.minecraft.world.gen.feature.template.Template.addEntitiesToWorld(Template.java:419) ~[?:?] {re:classloading}
at net.minecraft.world.gen.feature.template.Template.func_237146_a_(Template.java:337) ~[?:?] {re:classloading}
at net.minecraft.world.gen.feature.template.Template.func_237152_b_(Template.java:203) ~[?:?] {re:classloading}
at net.minecraft.world.gen.feature.template.Template.func_237144_a_(Template.java:199) ~[?:?] {re:classloading}
at com.simibubi.create.content.schematics.block.SchematicannonTileEntity.initializePrinter(SchematicannonTileEntity.java:555) ~[create:mc1.16.3_v0.3e] {re:classloading,pl:runtimedistcleaner:A}
at com.simibubi.create.content.schematics.block.SchematicannonTileEntity.tickPrinter(SchematicannonTileEntity.java:349) ~[create:mc1.16.3_v0.3e] {re:classloading,pl:runtimedistcleaner:A}
at com.simibubi.create.content.schematics.block.SchematicannonTileEntity.func_73660_a(SchematicannonTileEntity.java:309) ~[create:mc1.16.3_v0.3e] {re:classloading,pl:runtimedistcleaner:A}
at net.minecraft.world.World.func_217391_K(WorldMixin.java:491) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:world.WorldMixin,pl:mixin:A,pl:runtimedistcleaner:A}
at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorldMixin.java:371) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:world.server.ServerWorldMixin,pl:mixin:A,pl:arclight_implementer:async,pl:arclight_implementer:A,pl:runtimedistcleaner:A}
at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServerMixin.java:850) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServerMixin.java:291) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.dedicated.DedicatedServerMixin,pl:mixin:A}
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServerMixin.java:786) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServerMixin.java:1895) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
at net.minecraft.server.MinecraftServer.lambda$startServer$0(MinecraftServerMixin.java:232) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
at java.lang.Thread.run(Unknown Source) [?:1.8.0_271] {}
</pre></details>

**Comment by IzzelAliz** [comment]
请测试是否修复

**Comment by Akegarasu** [comment]
arclight-1.16.5-1.0.12-SNAPSHOT-b0b2d38
测试仍然会炸
[日志](https://paste.ubuntu.com/p/9fKMgdsqVy/)

**Comment by IzzelAliz** [comment]
草，我脑抽，请再次测试

**Comment by Akegarasu** [comment]
ok了
