### ISSUE TITLE
java.net.ConnectException: null

### ISSUE THREAD

**Issue by h4che404** [IzzelAliz/Arclight#1263]
### I have confirmed that ...

- [X] Arclight is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Forge

### Arclight version

arclight - 1.19.2  1.0.5

### OS & Java versions

SO archlinux - java version 19

### Plugins and Mods

```raw
Plugins (4): LuckPerms, Essentials, ChatManager, sleep-most
Mods: https://drive.google.com/file/d/1x4tIc4-62L5680nJjkW4kUg2L7CTw2W2/view?usp=drive_link
```

### Description

I start my server and everything works fine. It appears to me that the world loads and is online but when I try to enter the server it stays connected and never enters and I was reading in the console that there is an error with httpConect

### Step to reproduce

1-Download the modpack
2-Enter the game
3-Try connecting

### Logs

https://paste.ubuntu.com/p/BwWM4b42v9/

### Server pack link (Optional)

https://drive.google.com/file/d/1x4tIc4-62L5680nJjkW4kUg2L7CTw2W2/view?usp=drive_link

**Comment by qyl27** [comment]
The root of the problem is here.  
Have you installed all the correct versions of dependencies with mod ZombieAwareness?  

```
[12Mar2024 13:28:02.531] [Thread-0/ERROR] [net.minecraftforge.fml.javafmlmod.FMLModContainer/]: Exception caught during firing event: 'void com.corosus.modconfig.ConfigMod.onReload(net.minecraftforge.fml.event.config.ModConfigEvent$Reloading)'
	Index: 1
	Listeners:
		0: NORMAL
		1: net.minecraftforge.eventbus.EventBus$$Lambda$4464/0x0000000801c325d8@526e221c
java.lang.NoSuchMethodError: 'void com.corosus.modconfig.ConfigMod.onReload(net.minecraftforge.fml.event.config.ModConfigEvent$Reloading)'
	at TRANSFORMER/zombieawareness@1.19.2-1.12.3/com.corosus.zombieawareness.ZombieAwareness.onReload(ZombieAwareness.java:69)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:260)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:252)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:315)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:296)
	at LAYER PLUGIN/javafmllanguage@1.19.2-43.3.8/net.minecraftforge.fml.javafmlmod.FMLModContainer.lambda$new$0(FMLModContainer.java:44)
	at LAYER PLUGIN/fmlcore@1.19.2-43.3.8/net.minecraftforge.fml.ModContainer.lambda$dispatchConfigEvent$8(ModContainer.java:167)
	at java.base/java.util.Optional.ifPresent(Optional.java:178)
	at LAYER PLUGIN/fmlcore@1.19.2-43.3.8/net.minecraftforge.fml.ModContainer.dispatchConfigEvent(ModContainer.java:167)
	at LAYER PLUGIN/fmlcore@1.19.2-43.3.8/net.minecraftforge.fml.config.ModConfig.fireEvent(ModConfig.java:77)
	at LAYER PLUGIN/fmlcore@1.19.2-43.3.8/net.minecraftforge.fml.config.ConfigFileTypeHandler$ConfigWatcher.run(ConfigFileTypeHandler.java:147)
	at MC-BOOTSTRAP/com.electronwill.nightconfig.core@3.6.4/com.electronwill.nightconfig.core.file.FileWatcher$WatcherThread.run(FileWatcher.java:181)
```

**Comment by h4che404** [comment]
I would think so, I didn't know I had that problem. Anyway, looking at the discord server I found that one of the mods that I had installed on the server is incompatible with arclight and it is called pluto. What it does is not let you connect to the server so I deleted it and solved the connection problem. But seeing as you found more problems, I would like to know if you could flag them for me and see if we can solve it

**Comment by qyl27** [comment]
Well, for a specific mod, maybe a new issue thread would be better. It allows us to manage the issues more conveniently.
