### ISSUE TITLE
Arclight forge installer nonfunctional for 1.19.2

### ISSUE THREAD

**Issue by marcellonovak** [IzzelAliz/Arclight#1270]
### I have confirmed that ...

- [X] Arclight is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Forge

### Arclight version

arclight-forge-1.19.2-1.0.4.jar

### OS & Java versions

OS: Debian 12, Java: openjdk version "17.0.9" 2023-10-17

### Plugins and Mods

```raw
None as of now
```

### Description

Running the installer, I got the following error:
```
user@mc-server ~/arcserver [SIGINT]> java -jar arclight-forge-1.19.2-1.0.4.jar
Downloading missing libraries ...
Downloading mc version manifest...
Downloaded forge-1.19.2-43.3.7-installer.jar
Minecraft version: 1.19.2, server: f69c284232d7c7580bd89a5a4931c3581eae1378, mappings: ed5e6e8334ad67f5af0150beed0f3d156d74bd57
Processing forge installer...
Downloaded libraries/net/minecraft/server/1.19.2/server-1.19.2.jar
Forge installation is starting, please wait...
JVM info: Debian - 17.0.9 - 17.0.9+9-Debian-1deb12u1
java.net.preferIPv4Stack=true
Current Time: 14/03/2024 22:00:40
Host: files.minecraftforge.net [51.79.83.165]
Host: maven.minecraftforge.net [51.79.83.165]
Host: libraries.minecraft.net [13.107.246.70, 13.107.213.70]
Host: launchermeta.mojang.com [13.107.246.70, 13.107.213.70]
Host: piston-meta.mojang.com [13.107.213.70, 13.107.246.70]
java.net.UnknownHostException: authserver.mojang.com: Name or service not known
        at java.base/java.net.Inet4AddressImpl.lookupAllHostAddr(Native Method)
        at java.base/java.net.InetAddress$PlatformNameService.lookupAllHostAddr(InetAddress.java:934)
        at java.base/java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1543)
        at java.base/java.net.InetAddress$NameServiceAddresses.get(InetAddress.java:852)
        at java.base/java.net.InetAddress.getAllByName0(InetAddress.java:1533)
        at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1385)
        at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1306)
        at net.minecraftforge.installer.DownloadUtils.getIps(DownloadUtils.java:290)
        at net.minecraftforge.installer.SimpleInstaller.main(SimpleInstaller.java:120)
Exception in thread "main"
java.lang.NullPointerException: Cannot invoke "java.util.List.stream()" because the return value of "net.minecraftforge.installer.DownloadUtils.getIps(String)" is null
        at net.minecraftforge.installer.SimpleInstaller.main(SimpleInstaller.java:120)
java.lang.Exception: Forge installation failed
        at io.izzel.arclight.forgeinstaller.ForgeInstaller.applicationInstall(ForgeInstaller.java:96)
        at io.izzel.arclight.boot.application.Main_Forge.forgeInstall(Main_Forge.java:41)
        at io.izzel.arclight.boot.application.Main_Forge.main(Main_Forge.java:19)
        at io.izzel.arclight.server.Launcher.main(Launcher.java:18)
Fail to launch Arclight.
```

This was not fixable by changing DNS servers, instead, I had to replace the automatically created forge installer with one downloaded from the website, install forge, and THEN run the arclight server.

### Step to reproduce

Download Arclight on a Debian 12 machine
Try to run it and fail

### Logs

N/A

**Comment by IzzelAliz** [comment]
Use 1.0.5
