### ISSUE TITLE
World teleporting error

### ISSUE THREAD

**Issue by Dum4G** [IzzelAliz/Arclight#130]
### I am running

* **Arclight** [Update Mixin commit, 1.16.4] 

* **This is the latest development version** [N]

<details>
  <summary>Click to expand</summary>

* **Java** 8 275 

* **Operating System** Debian 10

* **Plugins**  LuckPerms, SkinsRestorer, UberEnchant, Chunky, VillagerOptimiser, spark, Vault, ConsoleSpamFix, ProtocolLib, FastAsyncWorldEdit (WorldEdit), Essentials, EssentialsChat, TAB, IllegalStack, EssentialsSpawn, WorldGuard, BanItem, AuthMe, CoreProtect, LWC, FarmControl

* **Mods** • minecraft forge-1.16.4-35.1.28-server.jar : minecraft (1.16.4) - 1
• mods_folder mcw-bridges-1.0.4-mc1.16.4.jar : mcwbridges (1.0.4) - 1
• mods_folder decorative_blocks-1.16.4-1.6.0.jar : decorative_blocks (1.6.0) - 1
• mods_folder eternalwinter-1.3.jar : eternalwinter (1.3) - 1
• mods_folder buildersaddition-1.16.4-20201130b.jar : buildersaddition (1.16.4-20201130b) - 1
• mods_folder BiomesOPlenty-1.16.4-13.0.0.421-universal.jar : biomesoplenty (1.16.4-13.0.0.418) - 1
• mods_folder FastFurnace-1.16.3-4.3.0.jar : fastfurnace (4.3.0) - 1
• mods_folder CoronaMask-1.16.4-v1.jar : corona_mask (1.0.0) - 1
• mods_folder valhelsia_structures-16.0.5.jar : valhelsia_structures (16.0.5) - 1
• mods_folder mcws-roofs-2.0.0-mc1.16.4.jar : mcwroofs (2.0.0) - 1
• mods_folder dungeons-plus-1.16.4-1.1.0.jar : dungeons_plus (1.1.0) - 1
• mods_folder AI-Improvements-1.16.2-0.3.0.jar : aiimprovements (0.3.0) - 1
• mods_folder additional_lights-1.16.4-2.1.3.jar : additional_lights (2.1.3) - 1
• arclight arclight-forge-1.16-1.0.11-SNAPSHOT.jar : arclight (1.16.4-1.0.11-SNAPSHOT-feb567a) - 1
• mods_folder trashcans-1.0.3-mc1.16.4.jar : trashcans (1.0.3) - 1
• mods_folder FallingTree-Forge-1.16.4-2.7.0.jar : falling_tree (2.7.0) - 1
• maven_libs forge-1.16.4-35.1.28-universal.jar : forge (35.1.28) - 1
• mods_folder pamhc2foodcore-1.16.3-1.0.0.jar : pamhc2foodcore (version) - 1
• mods_folder structure-gel-api-1.16.4-1.7.2.jar : structure_gel (1.7.2) - 1
• mods_folder FastWorkbench-1.16.3-4.4.1.jar : fastbench (4.4.1) - 1
• mods_folder CookingForBlockheads_1.16.3-9.2.2.jar : cookingforblockheads (9.2.2) - 1
• mods_folder christmasfestivity-1.3.5-1.16.4.jar : christmasfestivity (1.3.5-1.16.4) - 1
• mods_folder Placebo-1.16.3-4.3.3.jar : placebo (4.3.3) - 1</details>

### Description

Happens very rarely, doesn't have any visible impact. As player told me he was in ender world and moved to his home by using a portal. Either he used an ender pearl to activate the portal or has thrown it somewhat badly.

**Reproducible in Forge** [N]

**Reproducible in Spigot** [N]

### Logs

```
        at net.minecraft.world.server.ChunkManager.func_219183_a(ChunkManagerMixin.java:879) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:world.server.ChunkManagerMixin,pl:mixin:A,pl:arclight_implementer:async,pl:arclight_implementer:A,pl:runtimedistcleaner:A}
        at net.minecraft.world.server.ServerChunkProvider.func_217221_a(ServerChunkProviderMixin.java:467) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:world.server.ServerChunkProviderMixin,pl:mixin:A,re:mixin,pl:accesstransformer:B}
        at net.minecraft.network.play.ServerPlayNetHandler.handler$zph000$arclight$updateLoc(ServerPlayNetHandlerMixin.java:1874) ~[?:?] {re:mixin,re:classloading,pl:mixin:APP:mixins.arclight.core.json:network.play.ServerPlayNetHandlerMixin,pl:mixin:A,re:mixin}
        at net.minecraft.network.play.ServerPlayNetHandler.func_184339_a(ServerPlayNetHandlerMixin.java:429) ~[?:?] {re:mixin,re:classloading,pl:mixin:APP:mixins.arclight.core.json:network.play.ServerPlayNetHandlerMixin,pl:mixin:A,re:mixin}
        at net.minecraft.network.play.client.CConfirmTeleportPacket.func_148833_a(SourceFile:30) ~[?:?] {re:classloading,re:mixin}
        at net.minecraft.network.play.client.CConfirmTeleportPacket.func_148833_a(SourceFile:8) ~[?:?] {re:classloading,re:mixin}
        at net.minecraft.network.PacketThreadUtil.md649223$lambda$checkThreadAndEnqueue$0$0(PacketThreadUtilMixin.java:536) ~[?:?] {re:mixin,re:classloading,pl:mixin:APP:mixins.arclight.core.json:network.PacketThreadUtilMixin,pl:mixin:A}
        at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18) ~[?:?] {re:classloading}
        at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144) ~[?:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
        at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) ~[?:?] {re:mixin,re:computing_frames,re:classloading,re:mixin}
        at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServerMixin.java:733) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServerMixin.java:159) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118) ~[?:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
        at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServerMixin.java:716) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServerMixin.java:710) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213161_c(SourceFile:127) ~[?:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
        at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServerMixin.java:696) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServerMixin.java:1899) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.lambda$startServer$0(MinecraftServerMixin.java:232) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_275] {}
```

-->

**Comment by IzzelAliz** [comment]
Please provide full log

**Comment by Dum4G** [comment]
[2021-01-16-1.log](https://github.com/IzzelAliz/Arclight/files/5825897/2021-01-16-1.log)
[debug.log](https://github.com/IzzelAliz/Arclight/files/5825898/debug.log)

**Comment by IzzelAliz** [comment]
This seems like a spigot bug and reproducible on spigot with following instruction:

1. Entering end
2. Throwing ender pearl into end portal

My fix solved what raised from above but it may not cover all possibilities. Please test this fix.

**Comment by IzzelAliz** [comment]
We have fixed this spigot bug https://hub.spigotmc.org/jira/browse/SPIGOT-6327
