### ISSUE TITLE
AnvilMenu issues

### ISSUE THREAD

**Issue by LIUKRAST** [IzzelAliz/Arclight#1311]
Hello! I'm working on a server side forge mod which implements an AnvilMenu, but arclight throws an error not being able to get the worldpos of the AnvilEntity. I want it to be like that, cause the menu has to work for a text input. Is there a way i can disable the anvil worldPosition check?

My class extends
```java
class AnvilMenu
```

Exception is:
```
[14:44:47 ERROR]: Failed to handle packet net.minecraft.network.protocol.game.ServerboundContainerClickPacket@60ca652a, suppressing error
java.lang.NullPointerException: Cannot invoke "io.izzel.arclight.common.bridge.core.world.WorldBridge.bridge$getWorld()" because the return value of "io.izzel.arclight.common.bridge.core.util.IWorldPosCallableBridge.bridge$getWorld()" is null
        at io.izzel.arclight.common.bridge.core.util.IWorldPosCallableBridge.bridge$getLocation(IWorldPosCallableBridge.java:21) ~[arclight-1.20.1-1.0.4-fd335c1.jar%23233!/:arclight-1.20.1-1.0.4-fd335c1]
        at net.minecraft.world.inventory.AnvilMenu.getBukkitView(RepairContainerMixin.java:739) ~[server-1.20.1-20230612.114412-srg.jar%23305!/:?]
        at net.minecraft.world.inventory.AnvilMenu.m_6640_(RepairContainerMixin.java:726) ~[server-1.20.1-20230612.114412-srg.jar%23305!/:?]
        at net.minecraft.world.inventory.ItemCombinerMenu.m_6199_(ItemCombinerMixin.java:106) ~[server-1.20.1-20230612.114412-srg.jar%23305!/:?]
        at net.minecraft.world.inventory.ItemCombinerMenu$3.m_6596_(ItemCombinerMenu.java:96) ~[server-1.20.1-20230612.114412-srg.jar%23305!/:?]
        at net.minecraft.world.SimpleContainer.m_6836_(SimpleContainerMixin.java:144) ~[server-1.20.1-20230612.114412-srg.jar%23305!/:?]
        at net.minecraft.world.inventory.Slot.m_5852_(SlotMixin.java:63) ~[server-1.20.1-20230612.114412-srg.jar%23305!/:?]
        at net.minecraft.world.inventory.AbstractContainerMenu.m_182406_(AbstractContainerMenuMixin.java:576) ~[server-1.20.1-20230612.114412-srg.jar%23305!/:?]
        at net.frozenblock.liukrast.claimsplus.entry.menu.AddPlayerMenu.setup(AddPlayerMenu.java:39) ~[claims_plus-1.0.0.jar%23245!/:1.0.0]
        at net.frozenblock.liukrast.claimsplus.entry.menu.AddPlayerMenu.<init>(AddPlayerMenu.java:33) ~[claims_plus-1.0.0.jar%23245!/:1.0.0]
        at net.frozenblock.liukrast.claimsplus.entry.menu.PermissionMenu.lambda$clicked$3(PermissionMenu.java:121) ~[claims_plus-1.0.0.jar%23245!/:1.0.0]
        at net.minecraft.world.SimpleMenuProvider.m_7208_(SimpleMenuProvider.java:25) ~[server-1.20.1-20230612.114412-srg.jar%23305!/:?]
        at net.minecraft.server.level.ServerPlayer.m_5893_(ServerPlayerMixin.java:963) ~[server-1.20.1-20230612.114412-srg.jar%23305!/:?]
        at net.frozenblock.liukrast.claimsplus.entry.menu.PermissionMenu.m_150399_(PermissionMenu.java:121) ~[claims_plus-1.0.0.jar%23245!/:1.0.0]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.m_5914_(ServerPlayNetHandlerMixin.java:3406) ~[server-1.20.1-20230612.114412-srg.jar%23305!/:?]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.m_5797_(ServerboundContainerClickPacket.java:56) ~[server-1.20.1-20230612.114412-srg.jar%23305!/:?]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.m_5797_(ServerboundContainerClickPacket.java:12) ~[server-1.20.1-20230612.114412-srg.jar%23305!/:?]
        at net.minecraft.network.protocol.PacketUtils.mddf0115$lambda$ensureRunningOnSameThread$0$0(PacketThreadUtilMixin.java:537) ~[server-1.20.1-20230612.114412-srg.jar%23305!/:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[server-1.20.1-20230612.114412-srg.jar%23305!/:?]
        at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:156) ~[server-1.20.1-20230612.114412-srg.jar%23305!/:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[server-1.20.1-20230612.114412-srg.jar%23305!/:?]
        at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServerMixin.java:770) ~[server-1.20.1-20230612.114412-srg.jar%23305!/:?]
        at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServerMixin.java:161) ~[server-1.20.1-20230612.114412-srg.jar%23305!/:?]
        at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:130) ~[server-1.20.1-20230612.114412-srg.jar%23305!/:?]
        at net.minecraft.server.MinecraftServer.m_129961_(MinecraftServerMixin.java:753) ~[server-1.20.1-20230612.114412-srg.jar%23305!/:?]
        at net.minecraft.server.MinecraftServer.m_7245_(MinecraftServerMixin.java:747) ~[server-1.20.1-20230612.114412-srg.jar%23305!/:?]
        at net.minecraft.util.thread.BlockableEventLoop.m_18701_(BlockableEventLoop.java:139) ~[server-1.20.1-20230612.114412-srg.jar%23305!/:?]
        at net.minecraft.server.MinecraftServer.m_130012_(MinecraftServerMixin.java:733) ~[server-1.20.1-20230612.114412-srg.jar%23305!/:?]
        at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServerMixin.java:2074) ~[server-1.20.1-20230612.114412-srg.jar%23305!/:?]
        at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServerMixin.java:251) ~[server-1.20.1-20230612.114412-srg.jar%23305!/:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
        ```

**Comment by lifeoutofbalance** [comment]
This same error is happening on the latest horn build with the EasyAnvils mod, I see this is tagged with 1.20 but would any future 1.19.x builds contain this fix?

```
[18May2024 00:11:33.803] [Server thread/ERROR] [net.minecraft.network.protocol.PacketUtils/]: Failed to handle packet net.minecraft.network.protocol.game.ServerboundContainerClickPacket@7e46179e, suppressing error
java.lang.NullPointerException: Cannot invoke "io.izzel.arclight.common.bridge.core.world.WorldBridge.bridge$getWorld()" because the return value of "io.izzel.arclight.common.bridge.core.util.IWorldPosCallableBridge.bridge$getWorld()" is null
at io.izzel.arclight.common.bridge.core.util.IWorldPosCallableBridge.bridge$getLocation(IWorldPosCallableBridge.java:21) ~[arclight-1.19.2-1.0.5-696a298.jar%23420!/:arclight-1.19.2-1.0.5-696a298] {re:mixin,re:classloading}
at net.minecraft.world.inventory.AnvilMenu.getBukkitView(RepairContainerMixin.java:739) ~[server-1.19.2-20220805.130853-srg.jar%23681!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:world.inventory.RepairContainerMixin,pl:mixin:APP:easyanvils.common.mixins.json:accessor.AnvilMenuAccessor,pl:mixin:APP:goblintraders.mixins.json:RepairContainerMixin,pl:mixin:APP:quark.mixins.json:AnvilMenuMixin,pl:mixin:A}
at net.minecraft.world.inventory.AnvilMenu.m_6640_(RepairContainerMixin.java:563) ~[server-1.19.2-20220805.130853-srg.jar%23681!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:world.inventory.RepairContainerMixin,pl:mixin:APP:easyanvils.common.mixins.json:accessor.AnvilMenuAccessor,pl:mixin:APP:goblintraders.mixins.json:RepairContainerMixin,pl:mixin:APP:quark.mixins.json:AnvilMenuMixin,pl:mixin:A}
at net.minecraft.world.inventory.ItemCombinerMenu.m_6199_(ItemCombinerMixin.java:80) ~[server-1.19.2-20220805.130853-srg.jar%23681!/:?] {re:mixin,re:classloading,pl:mixin:APP:mixins.arclight.core.json:world.inventory.ItemCombinerMixin,pl:mixin:APP:easyanvils.common.mixins.json:accessor.ItemCombinerMenuAccessor,pl:mixin:APP:railways-common.mixins.json:MixinItemCombinerMenu,pl:mixin:A}
at net.minecraft.world.inventory.ItemCombinerMenu$1.m_6596_(ItemCombinerMenu.java:26) ~[server-1.19.2-20220805.130853-srg.jar%23681!/:?] {re:classloading}
at net.minecraft.world.SimpleContainer.m_6836_(SimpleContainerMixin.java:140) ~[server-1.19.2-20220805.130853-srg.jar%23681!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:world.SimpleContainerMixin,pl:mixin:A}
at fuzs.easyanvils.world.inventory.BuiltInAnvilMenu.init(BuiltInAnvilMenu.java:16) ~[EasyAnvils-v4.0.11-1.19.2-Forge.jar%23509!/:4.0.11] {re:classloading}
at fuzs.easyanvils.world.inventory.ModAnvilMenu.m_6640_(ModAnvilMenu.java:88) ~[EasyAnvils-v4.0.11-1.19.2-Forge.jar%23509!/:4.0.11] {re:mixin,re:classloading}
at net.minecraft.world.inventory.ItemCombinerMenu.m_6199_(ItemCombinerMixin.java:80) ~[server-1.19.2-20220805.130853-srg.jar%23681!/:?] {re:mixin,re:classloading,pl:mixin:APP:mixins.arclight.core.json:world.inventory.ItemCombinerMixin,pl:mixin:APP:easyanvils.common.mixins.json:accessor.ItemCombinerMenuAccessor,pl:mixin:APP:railways-common.mixins.json:MixinItemCombinerMenu,pl:mixin:A}
at fuzs.easyanvils.world.inventory.ModAnvilMenu.m_7934_(ModAnvilMenu.java:344) ~[EasyAnvils-v4.0.11-1.19.2-Forge.jar%23509!/:4.0.11] {re:mixin,re:classloading}
at net.minecraft.world.inventory.AbstractContainerMenu.m_150407_(AbstractContainerMenuMixin.java:220) ~[server-1.19.2-20220805.130853-srg.jar%23681!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:world.inventory.AbstractContainerMenuMixin,pl:mixin:APP:mixins.hammerlib.json:AbstractContainerMenuAccessor,pl:mixin:APP:immersiveengineering.mixins.json:accessors.ContainerAccess,pl:mixin:APP:aether.mixins.json:common.accessor.AbstractContainerMenuAccessor,pl:mixin:APP:placebo.mixins.json:AbstractContainerMenuInvoker,pl:mixin:APP:railways-common.mixins.json:MixinAbstractContainerMenu,pl:mixin:A}
at net.minecraft.world.inventory.AbstractContainerMenu.m_38946_(AbstractContainerMenuMixin.java:170) ~[server-1.19.2-20220805.130853-srg.jar%23681!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:world.inventory.AbstractContainerMenuMixin,pl:mixin:APP:mixins.hammerlib.json:AbstractContainerMenuAccessor,pl:mixin:APP:immersiveengineering.mixins.json:accessors.ContainerAccess,pl:mixin:APP:aether.mixins.json:common.accessor.AbstractContainerMenuAccessor,pl:mixin:APP:placebo.mixins.json:AbstractContainerMenuInvoker,pl:mixin:APP:railways-common.mixins.json:MixinAbstractContainerMenu,pl:mixin:A}
at net.minecraft.server.network.ServerGamePacketListenerImpl.m_5914_(ServerPlayNetHandlerMixin.java:3518) ~[server-1.19.2-20220805.130853-srg.jar%23681!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_servergamepacketlistenerimpl_handleinteract,re:classloading,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_servergamepacketlistenerimpl_handleinteract,pl:mixin:A,re:mixin,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_servergamepacketlistenerimpl_handleinteract}
at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.m_5797_(ServerboundContainerClickPacket.java:56) ~[server-1.19.2-20220805.130853-srg.jar%23681!/:?] {re:mixin,re:classloading}
at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.m_5797_(ServerboundContainerClickPacket.java:12) ~[server-1.19.2-20220805.130853-srg.jar%23681!/:?] {re:mixin,re:classloading}
at net.minecraft.network.protocol.PacketUtils.md4e4098$lambda$ensureRunningOnSameThread$0$0(PacketThreadUtilMixin.java:537) ~[server-1.19.2-20220805.130853-srg.jar%23681!/:?] {re:mixin,re:classloading,pl:mixin:APP:mixins.arclight.core.json:network.protocol.PacketThreadUtilMixin,pl:mixin:A}
at net.minecraft.server.TickTask.run(TickTask.java:18) ~[server-1.19.2-20220805.130853-srg.jar%23681!/:?] {re:classloading,re:mixin}
at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:157) ~[server-1.19.2-20220805.130853-srg.jar%23681!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:modernfix-common.mixins.json:perf.fix_loop_spin_waiting.BlockableEventLoopMixin,pl:mixin:A}
at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[server-1.19.2-20220805.130853-srg.jar%23681!/:?] {re:computing_frames,re:mixin,re:classloading}
at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServerMixin.java:763) ~[server-1.19.2-20220805.130853-srg.jar%23681!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_minecraftserverclass,xf:fml:xaerominimap:xaero_minecraftserver,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,re:classloading,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_minecraftserverclass,xf:fml:xaerominimap:xaero_minecraftserver,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:create_new_age.mixins.json:MinecraftServerMixin,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:APP:citadel.mixins.json:MinecraftServerMixin,pl:mixin:APP:blockswap.mixins.json:MixinMinecraftServer,pl:mixin:A}
at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServerMixin.java:157) ~[server-1.19.2-20220805.130853-srg.jar%23681!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_minecraftserverclass,xf:fml:xaerominimap:xaero_minecraftserver,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,re:classloading,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_minecraftserverclass,xf:fml:xaerominimap:xaero_minecraftserver,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:create_new_age.mixins.json:MinecraftServerMixin,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:APP:citadel.mixins.json:MinecraftServerMixin,pl:mixin:APP:blockswap.mixins.json:MixinMinecraftServer,pl:mixin:A}
at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:131) ~[server-1.19.2-20220805.130853-srg.jar%23681!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:modernfix-common.mixins.json:perf.fix_loop_spin_waiting.BlockableEventLoopMixin,pl:mixin:A}
at net.minecraft.server.MinecraftServer.m_129961_(MinecraftServerMixin.java:746) ~[server-1.19.2-20220805.130853-srg.jar%23681!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_minecraftserverclass,xf:fml:xaerominimap:xaero_minecraftserver,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,re:classloading,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_minecraftserverclass,xf:fml:xaerominimap:xaero_minecraftserver,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:create_new_age.mixins.json:MinecraftServerMixin,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:APP:citadel.mixins.json:MinecraftServerMixin,pl:mixin:APP:blockswap.mixins.json:MixinMinecraftServer,pl:mixin:A}
at net.minecraft.server.MinecraftServer.m_7245_(MinecraftServerMixin.java:740) ~[server-1.19.2-20220805.130853-srg.jar%23681!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_minecraftserverclass,xf:fml:xaerominimap:xaero_minecraftserver,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,re:classloading,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_minecraftserverclass,xf:fml:xaerominimap:xaero_minecraftserver,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:create_new_age.mixins.json:MinecraftServerMixin,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:APP:citadel.mixins.json:MinecraftServerMixin,pl:mixin:APP:blockswap.mixins.json:MixinMinecraftServer,pl:mixin:A}
at net.minecraft.util.thread.BlockableEventLoop.m_18699_(BlockableEventLoop.java:116) ~[server-1.19.2-20220805.130853-srg.jar%23681!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:modernfix-common.mixins.json:perf.fix_loop_spin_waiting.BlockableEventLoopMixin,pl:mixin:A}
at net.minecraft.server.MinecraftServer.m_130012_(MinecraftServerMixin.java:725) ~[server-1.19.2-20220805.130853-srg.jar%23681!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_minecraftserverclass,xf:fml:xaerominimap:xaero_minecraftserver,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,re:classloading,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_minecraftserverclass,xf:fml:xaerominimap:xaero_minecraftserver,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:create_new_age.mixins.json:MinecraftServerMixin,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:APP:citadel.mixins.json:MinecraftServerMixin,pl:mixin:APP:blockswap.mixins.json:MixinMinecraftServer,pl:mixin:A}
at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServerMixin.java:2131) ~[server-1.19.2-20220805.130853-srg.jar%23681!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_minecraftserverclass,xf:fml:xaerominimap:xaero_minecraftserver,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,re:classloading,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_minecraftserverclass,xf:fml:xaerominimap:xaero_minecraftserver,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:create_new_age.mixins.json:MinecraftServerMixin,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:APP:citadel.mixins.json:MinecraftServerMixin,pl:mixin:APP:blockswap.mixins.json:MixinMinecraftServer,pl:mixin:A}
at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServerMixin.java:244) ~[server-1.19.2-20220805.130853-srg.jar%23681!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_minecraftserverclass,xf:fml:xaerominimap:xaero_minecraftserver,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,re:classloading,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_minecraftserverclass,xf:fml:xaerominimap:xaero_minecraftserver,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:create_new_age.mixins.json:MinecraftServerMixin,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:APP:citadel.mixins.json:MinecraftServerMixin,pl:mixin:APP:blockswap.mixins.json:MixinMinecraftServer,pl:mixin:A}
at java.lang.Thread.run(Thread.java:840) [?:?] {re:mixin,re:mixin}

```
