### ISSUE TITLE
[1.20.1]区块卸载相关崩溃 java.util.ConcurrentModificationException: null 是否类似#1056

### ISSUE THREAD

**Issue by ColdTearsYY** [IzzelAliz/Arclight#1316]
### 请确认您已完成以下几件事

- [X] 正在使用最新的 Arclight
- [X] 已为所有插件及模组安装依赖
- [X] 已为所有插件及模组更新至最新版
- [X] 不可在 Spigot 复现
- [X] 不可在 Forge 复现

### Arclight 版本

arclight-1.20.1-1.0.6-SNAPSHOT-94d8220

### Java 版本 | 操作系统

系统：win10，java：graalvm-ee-java17-22.1.0

### 相关 Mod/插件 的名称及版本

```raw
在crash report里可以看
https://mclo.gs/94aIbIW
```

### 错误描述

疑似和DistanceManager 、区块卸载有关 （#1056）
初次发现是在玩家被高额伤害怪物打死时崩溃。单人不复现，需要服务器至少两人
高额伤害来自莱特兰-恶意模组的复印词条，根据玩家身上的附魔总数提高怪物伤害
莱特兰群分析如图
![1713060341427](https://github.com/IzzelAliz/Arclight/assets/65808439/28ba55b8-cabc-4cff-95c4-7aaa7edfc27c)

后来发现在移动时（比如使用传送石碑mod的传送石传送）也会崩溃

### 复现步骤

1.安装好模组，启动服务器
2.玩家使用传送石碑远距离或跨世界传送
3.服务器崩溃

### 报错信息

https://mclo.gs/94aIbIW

**Comment by KingKottlewing** [comment]
[crash-2024-04-15_19.12.31-server.txt](https://github.com/IzzelAliz/Arclight/files/14982338/crash-2024-04-15_19.12.31-server.txt)
Same in 1.18.2

**Comment by ColdTearsYY** [comment]
![QQ_1721090517368](https://github.com/user-attachments/assets/c9de857e-3c39-40de-968f-bcb5148dedc4)
希望螺螺能抽空看一下 崩的太稳定了
`
A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Suspected Mod: 
	Arclight Mod (arclight), Version: 1.20.1-1.0.6-SNAPSHOT-52ab6e5
		Mixin class: io.izzel.arclight.common.mixin.core.server.level.DistanceManagerMixin
		Target: net.minecraft.server.level.DistanceManager
		at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.level.DistanceManager.redirect$dae000$arclight$safeIter(DistanceManagerMixin.java:556)
Stacktrace:
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:1095) ~[?:?] {}
	at java.util.ArrayList$Itr.next(ArrayList.java:1049) ~[?:?] {}
	at com.google.common.collect.Iterators$1.next(Iterators.java:146) ~[guava-31.1-jre.jar%23108!/:?] {}
	at java.util.Iterator.forEachRemaining(Iterator.java:133) ~[?:?] {re:mixin,re:mixin,re:mixin}
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1939) ~[?:?] {}
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?] {}
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?] {}
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151) ~[?:?] {}
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174) ~[?:?] {}
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?] {}
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?] {}
	at net.minecraft.world.level.entity.PersistentEntitySectionManager.m_157543_(PersistentEntitySectionManagerMixin.java:175) ~[server-1.20.1-20230612.114412-srg.jar%23845!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:world.level.entity.PersistentEntitySectionManagerMixin,pl:mixin:APP:youkaishomecoming.mixins.json:PersistentEntitySectionManagerAccessor,pl:mixin:A}
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184) ~[?:?] {}
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) ~[?:?] {}
	at java.util.stream.LongPipeline$1$1.accept(LongPipeline.java:177) ~[?:?] {}
	at java.util.PrimitiveIterator$OfLong.forEachRemaining(PrimitiveIterator.java:185) ~[?:?] {re:mixin}
	at java.util.Spliterators$LongIteratorSpliterator.forEachRemaining(Spliterators.java:2144) ~[?:?] {}
	at java.util.Spliterator$OfLong.forEachRemaining(Spliterator.java:777) ~[?:?] {}
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?] {}
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?] {}
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151) ~[?:?] {}
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174) ~[?:?] {}
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?] {}
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?] {}
	at net.minecraft.world.level.entity.PersistentEntitySectionManager.m_157527_(PersistentEntitySectionManagerMixin.java:160) ~[server-1.20.1-20230612.114412-srg.jar%23845!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:world.level.entity.PersistentEntitySectionManagerMixin,pl:mixin:APP:youkaishomecoming.mixins.json:PersistentEntitySectionManagerAccessor,pl:mixin:A}
	at net.minecraft.world.level.entity.PersistentEntitySectionManager.m_287207_(PersistentEntitySectionManagerMixin.java:146) ~[server-1.20.1-20230612.114412-srg.jar%23845!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:world.level.entity.PersistentEntitySectionManagerMixin,pl:mixin:APP:youkaishomecoming.mixins.json:PersistentEntitySectionManagerAccessor,pl:mixin:A}
	at net.minecraft.server.level.ChunkMap.m_287285_(ChunkMapMixin.java:1307) ~[server-1.20.1-20230612.114412-srg.jar%23845!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.level.ChunkMapMixin,pl:mixin:APP:modernfix-common.mixins.json:bugfix.paper_chunk_patches.ChunkMapMixin,pl:mixin:APP:modernfix-forge.mixins.json:bugfix.chunk_deadlock.ChunkMapLoadMixin,pl:mixin:APP:krypton.mixins.json:shared.network.avoidwork.ThreadedAnvilChunkStorageMixin,pl:mixin:APP:krypton.mixins.json:shared.network.flushconsolidation.ThreadedAnvilChunkStorageMixin,pl:mixin:APP:emotecraft.mixins.json:ChunkMapAccessor,pl:mixin:APP:adastra-common.mixins.json:common.multipart.ChunkMapMixin,pl:mixin:APP:ftbchunks-common.mixins.json:ChunkMapMixin,pl:mixin:APP:mixins.arclight.impl.forge.optimization.json:network.ChunkMapMixin_Optimize,pl:mixin:APP:mixins.arclight.impl.forge.optimization.json:trackingrange.ChunkManagerMixin_TrackingRange,pl:mixin:APP:ars_nouveau.mixins.json:camera.ChunkMapMixin,pl:mixin:A,pl:arclight_implementer:async,pl:arclight_implementer:A}
	at net.minecraft.server.level.ChunkHolder.m_287189_(ChunkHolderMixin.java:346) ~[server-1.20.1-20230612.114412-srg.jar%23845!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:modernfix-common.mixins.json:perf.ticking_chunk_alloc.ChunkHolderMixin,pl:mixin:APP:mixins.arclight.core.json:server.level.ChunkHolderMixin,pl:mixin:APP:chunksending.mixins.json:ChunkHolderMixin,pl:mixin:A}
	at net.minecraft.server.level.ChunkHolder.m_143003_(ChunkHolderMixin.java:416) ~[server-1.20.1-20230612.114412-srg.jar%23845!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:modernfix-common.mixins.json:perf.ticking_chunk_alloc.ChunkHolderMixin,pl:mixin:APP:mixins.arclight.core.json:server.level.ChunkHolderMixin,pl:mixin:APP:chunksending.mixins.json:ChunkHolderMixin,pl:mixin:A}
	at net.minecraft.server.level.DistanceManager.m_183906_(DistanceManagerMixin.java:120) ~[server-1.20.1-20230612.114412-srg.jar%23845!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.level.DistanceManagerMixin,pl:mixin:A}
	at net.minecraft.server.level.DistanceManager.redirect$dae000$arclight$safeIter(DistanceManagerMixin.java:556) ~[server-1.20.1-20230612.114412-srg.jar%23845!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.level.DistanceManagerMixin,pl:mixin:A}
	at net.minecraft.server.level.DistanceManager.m_140805_(DistanceManagerMixin.java:119) ~[server-1.20.1-20230612.114412-srg.jar%23845!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.level.DistanceManagerMixin,pl:mixin:A}
	at net.minecraft.server.level.ServerChunkCache.m_8489_(ServerChunkCacheMixin.java:273) ~[server-1.20.1-20230612.114412-srg.jar%23845!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:cupboard.mixins.json:ChunkLoadDebug,pl:mixin:APP:mixins.arclight.core.json:server.level.ServerChunkCacheMixin,pl:mixin:APP:modernfix-forge.mixins.json:bugfix.chunk_deadlock.ServerChunkCache_CurrentLoadingMixin,pl:mixin:A}
	at net.minecraft.server.level.ServerChunkCache.m_201698_(ServerChunkCacheMixin.java:309) ~[server-1.20.1-20230612.114412-srg.jar%23845!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:cupboard.mixins.json:ChunkLoadDebug,pl:mixin:APP:mixins.arclight.core.json:server.level.ServerChunkCacheMixin,pl:mixin:APP:modernfix-forge.mixins.json:bugfix.chunk_deadlock.ServerChunkCache_CurrentLoadingMixin,pl:mixin:A}
	at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevelMixin.java:305) ~[server-1.20.1-20230612.114412-srg.jar%23845!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:cupboard.mixins.json:ServerAddEntityMixin,pl:mixin:APP:mixins.arclight.core.json:server.level.ServerLevelMixin,pl:mixin:APP:citadel.mixins.json:ServerLevelMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.cache_strongholds.ServerLevelMixin,pl:mixin:APP:modernfix-common.mixins.json:bugfix.chunk_deadlock.ServerLevelMixin,pl:mixin:APP:krypton.mixins.json:server.fastchunkentityaccess.ServerWorldMixin,pl:mixin:APP:crafttweaker.mixins.json:common.transform.world.level.MixinServerLevel,pl:mixin:APP:adastra-common.mixins.json:common.ServerLevelMixin,pl:mixin:APP:adastra-common.mixins.json:common.multipart.ServerLevelMixin,pl:mixin:APP:youkaishomecoming.mixins.json:ServerLevelAccessor,pl:mixin:APP:observable.common.json:ServerLevelMixin,pl:mixin:APP:mixins.bosses_of_mass_destruction.json:ExplosionMixin,pl:mixin:APP:blueprint.mixins.json:ServerLevelMixin,pl:mixin:APP:mixins.arclight.impl.forge.optimization.json:activationrange.ServerWorldMixin_ActivationRange,pl:mixin:A,pl:arclight_implementer:async,pl:arclight_implementer:A,re:mixin,pl:accesstransformer:B}
-- Affected level --

`

**Comment by ColdTearsYY** [comment]
新的crash report: https://mclo.gs/qMRBt9d

**Comment by KingKottlewing** [comment]
> ### 请确认您已完成以下几件事
> * [x]  正在使用最新的 Arclight
> * [x]  已为所有插件及模组安装依赖
> * [x]  已为所有插件及模组更新至最新版
> * [x]  不可在 Spigot 复现
> * [x]  不可在 Forge 复现
> 
> ### Arclight 版本
> arclight-1.20.1-1.0.6-SNAPSHOT-94d8220
> 
> ### Java 版本 | 操作系统
> 系统：win10，java：graalvm-ee-java17-22.1.0
> 
> ### 相关 Mod/插件 的名称及版本
> ```
> 在crash report里可以看
> https://mclo.gs/94aIbIW
> ```
> 
> ### 错误描述
> 疑似和DistanceManager 、区块卸载有关 （#1056） 初次发现是在玩家被高额伤害怪物打死时崩溃。单人不复现，需要服务器至少两人 高额伤害来自莱特兰-恶意模组的复印词条，根据玩家身上的附魔总数提高怪物伤害 莱特兰群分析如图 ![1713060341427](https://private-user-images.githubusercontent.com/65808439/322240836-28ba55b8-cabc-4cff-95c4-7aaa7edfc27c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIyNzM5NDgsIm5iZiI6MTcyMjI3MzY0OCwicGF0aCI6Ii82NTgwODQzOS8zMjIyNDA4MzYtMjhiYTU1YjgtY2FiYy00Y2ZmLTk1YzQtN2FhYTdlZGZjMjdjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI5VDE3MjA0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVhMjI3NDg3OTk2MzBlNzU1MTdlMjI0NGNjNzQzOWJmMmM2ZjA0NTgzZmRjNGZhMmEyOWY0MzYyY2U4ODI0MmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.j2_oD9KyCHdQJcer-egFSZGFk7kvp2Xp778Hwa1k4C0)
> 
> 后来发现在移动时（比如使用传送石碑mod的传送石传送）也会崩溃
> 
> ### 复现步骤
> 1.安装好模组，启动服务器 2.玩家使用传送石碑远距离或跨世界传送 3.服务器崩溃
> 
> ### 报错信息
> https://mclo.gs/94aIbIW
> 
> ### 复现用压缩包下载链接(可选)
> _No response_

Try adding this, it may fix your issue

https://github.com/AllTheMods/ATM-9/issues/406#issuecomment-1848366883

**Comment by ColdTearsYY** [comment]
> > ### 请确认您已完成以下几件事
> > 
> > * [x]   正在使用最新的 Arclight
> > * [x]   已为所有插件及模组安装依赖
> > * [x]   已为所有插件及模组更新至最新版
> > * [x]   不可在 Spigot 复现
> > * [x]   不可在 Forge 复现
> > 
> > ### Arclight 版本
> > arclight-1.20.1-1.0.6-SNAPSHOT-94d8220
> > ### Java 版本 | 操作系统
> > 系统：win10，java：graalvm-ee-java17-22.1.0
> > ### 相关 Mod/插件 的名称及版本
> > ```
> > 在crash report里可以看
> > https://mclo.gs/94aIbIW
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ### 错误描述
> > 疑似和DistanceManager 、区块卸载有关 （#1056） 初次发现是在玩家被高额伤害怪物打死时崩溃。单人不复现，需要服务器至少两人 高额伤害来自莱特兰-恶意模组的复印词条，根据玩家身上的附魔总数提高怪物伤害 莱特兰群分析如图 ![1713060341427](https://private-user-images.githubusercontent.com/65808439/322240836-28ba55b8-cabc-4cff-95c4-7aaa7edfc27c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIyNzM5NDgsIm5iZiI6MTcyMjI3MzY0OCwicGF0aCI6Ii82NTgwODQzOS8zMjIyNDA4MzYtMjhiYTU1YjgtY2FiYy00Y2ZmLTk1YzQtN2FhYTdlZGZjMjdjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI5VDE3MjA0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVhMjI3NDg3OTk2MzBlNzU1MTdlMjI0NGNjNzQzOWJmMmM2ZjA0NTgzZmRjNGZhMmEyOWY0MzYyY2U4ODI0MmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.j2_oD9KyCHdQJcer-egFSZGFk7kvp2Xp778Hwa1k4C0)
> > 后来发现在移动时（比如使用传送石碑mod的传送石传送）也会崩溃
> > ### 复现步骤
> > 1.安装好模组，启动服务器 2.玩家使用传送石碑远距离或跨世界传送 3.服务器崩溃
> > ### 报错信息
> > https://mclo.gs/94aIbIW
> > ### 复现用压缩包下载链接(可选)
> > _No response_
> 
> Try adding this, it may fix your issue
> 
> [AllTheMods/ATM-9#406 (comment)](https://github.com/AllTheMods/ATM-9/issues/406#issuecomment-1848366883)

It didn't solve my problem. The server is still crashing. But thank you for your kindness :)

**Comment by ColdTearsYY** [comment]
Latest crash report: https://mclo.gs/mBpZh4F
截止8月1日仍然存在。
It crashed when players move around chunks.
仍会玩家跑地图崩溃。
I really need it fix... Waiting

**Comment by KingKottlewing** [comment]
> > > ### 请确认您已完成以下几件事
> > > 
> > > * [x]    正在使用最新的 Arclight
> > > * [x]    已为所有插件及模组安装依赖
> > > * [x]    已为所有插件及模组更新至最新版
> > > * [x]    不可在 Spigot 复现
> > > * [x]    不可在 Forge 复现
> > > 
> > > ### Arclight 版本
> > > arclight-1.20.1-1.0.6-SNAPSHOT-94d8220
> > > ### Java 版本 | 操作系统
> > > 系统：win10，java：graalvm-ee-java17-22.1.0
> > > ### 相关 Mod/插件 的名称及版本
> > > ```
> > > 在crash report里可以看
> > > https://mclo.gs/94aIbIW
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > ### 错误描述
> > > 疑似和DistanceManager 、区块卸载有关 （#1056） 初次发现是在玩家被高额伤害怪物打死时崩溃。单人不复现，需要服务器至少两人 高额伤害来自莱特兰-恶意模组的复印词条，根据玩家身上的附魔总数提高怪物伤害 莱特兰群分析如图 ![1713060341427](https://private-user-images.githubusercontent.com/65808439/322240836-28ba55b8-cabc-4cff-95c4-7aaa7edfc27c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIyNzM5NDgsIm5iZiI6MTcyMjI3MzY0OCwicGF0aCI6Ii82NTgwODQzOS8zMjIyNDA4MzYtMjhiYTU1YjgtY2FiYy00Y2ZmLTk1YzQtN2FhYTdlZGZjMjdjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI5VDE3MjA0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVhMjI3NDg3OTk2MzBlNzU1MTdlMjI0NGNjNzQzOWJmMmM2ZjA0NTgzZmRjNGZhMmEyOWY0MzYyY2U4ODI0MmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.j2_oD9KyCHdQJcer-egFSZGFk7kvp2Xp778Hwa1k4C0)
> > > 后来发现在移动时（比如使用传送石碑mod的传送石传送）也会崩溃
> > > ### 复现步骤
> > > 1.安装好模组，启动服务器 2.玩家使用传送石碑远距离或跨世界传送 3.服务器崩溃
> > > ### 报错信息
> > > https://mclo.gs/94aIbIW
> > > ### 复现用压缩包下载链接(可选)
> > > _No response_
> > 
> > 
> > Try adding this, it may fix your issue
> > [AllTheMods/ATM-9#406 (comment)](https://github.com/AllTheMods/ATM-9/issues/406#issuecomment-1848366883)
> 
> It didn't solve my problem. The server is still crashing. But thank you for your kindness :)

No problem, but that's very strange, I put it on my server as a mod and it fixed it for me, no more crashes.

**Comment by Jasaxion** [comment]
截止 2025年3月该问题仍然存在， (即便是用的 nightly 的最新构建）玩家跑图稍微快一点就会导致崩溃。
