### ISSUE TITLE
[1.20.4-Fabric] WorldEdit 创世神插件不兼容，无法使用（“在不支持的版本上编辑被禁止“）/WorldEdit-Fabric疑似mixin冲突（无法编辑树叶，并报错）

### ISSUE THREAD

**Issue by luoxiawuchen** [IzzelAliz/Arclight#1322]
### 请确认您已完成以下几件事

- [X] 正在使用最新的 Arclight
- [X] 已为所有插件及模组安装依赖
- [X] 已为所有插件及模组更新至最新版
- [X] 不可在 Spigot 复现
- [X] 不可在 Forge 复现

### Arclight 版本

arclight-1.20.4-1.0.4-SNAPSHOT-e88b7bf #1191

### Java 版本 | 操作系统

win10 java17

### 相关 Mod/插件 的名称及版本

```raw
worldedit-bukkit-7.3.1-SNAPSHOT-dist.jar
链接：https://dev.bukkit.org/projects/worldedit/files/5168643
```

### 错误描述

插件载入时提示：
[12:15:21 WARN] [c.s.w.b.WorldEditPlugin]:
**********************************************
** This WorldEdit version does not fully support your version of Bukkit.
**
** When working with blocks or undoing, chests will be empty, signs
** will be blank, and so on. There will be no support for entity
** and block property-related functions.
**
** Please see https://worldedit.enginehub.org/en/latest/faq/#bukkit-adapters
**********************************************

[12:15:22 INFO] [WorldEdit]: ====================================================
[12:15:22 INFO] [WorldEdit]:  WorldEdit works better if you use Paper
[12:15:22 INFO] [WorldEdit]:  as your server software.
[12:15:22 INFO] [WorldEdit]:
[12:15:22 INFO] [WorldEdit]:  Paper offers significant performance improvements,
[12:15:22 INFO] [WorldEdit]:  bug fixes, security enhancements and optional
[12:15:22 INFO] [WorldEdit]:  features for server owners to enhance their server.
[12:15:22 INFO] [WorldEdit]:
[12:15:22 INFO] [WorldEdit]:  Paper includes Timings v2, which is significantly
[12:15:22 INFO] [WorldEdit]:  better at diagnosing lag problems over v1.
[12:15:22 INFO] [WorldEdit]:
[12:15:22 INFO] [WorldEdit]:  All of your plugins should still work, and the
[12:15:22 INFO] [WorldEdit]:  Paper community will gladly help you fix any issues.
[12:15:22 INFO] [WorldEdit]:
[12:15:22 INFO] [WorldEdit]:  Join the Paper Community @ https://papermc.io
[12:15:22 INFO] [WorldEdit]: ====================================================

进入游戏后使用提示：
![image](https://github.com/IzzelAliz/Arclight/assets/64759847/2f83b4d2-69ca-47c8-89a2-0ac751e3ed32)

一些debug信息：Unknown property snowy for block minecraft:grass_block

### 复现步骤

1、安装插件
2、提示警告
3、键入命令后，无法正常执行，抛出提示

### 报错信息

[debug.log]
https://paste.ubuntu.com/p/mmqFp5Y5V3/

[latest.log]
https://paste.ubuntu.com/p/nPctKjWPPy/

**Comment by luoxiawuchen** [comment]
**一些补充：**
经测试，可以通过同时安装fabricmod版本作为替代解决方案
但fabricmod无法编辑树叶，并抛出错误
![image](https://github.com/IzzelAliz/Arclight/assets/64759847/9b4b9125-d0f4-4c26-af48-4cdf87e4a287)

根据日志，疑似mixin冲突
[18:40:23 INFO] [FabricLoader/MixinExtras|Service]: Initializing MixinExtras via com.llamalad7.mixinextras.service.MixinExtrasServiceImpl(version=0.3.2).
[18:41:02 WARN] [FabricLoader/Mixin]: Discarding @Unique public method setBlockState in worldedit-fabric.mixins.json:MixinLevelChunkSetBlockHook from mod worldedit because it already exists in net.minecraft.class_2818

一些关键报错信息：
[18:41:55 ERROR] [c.s.w.u.e.EventBus]: Could not dispatch event: com.sk89q.worldedit.event.platform.PlatformReadyEvent@6e3c8ebc to handler EventHandler{priority=NORMAL}
java.lang.reflect.InvocationTargetException: null
        at com.sk89q.worldedit.util.eventbus.EventHandler.handleEvent(EventHandler.java:75) ~[worldedit-mod-7.3.0.jar:?]
        at com.sk89q.worldedit.util.eventbus.EventBus.dispatch(EventBus.java:193) ~[worldedit-mod-7.3.0.jar:?]
        at com.sk89q.worldedit.util.eventbus.EventBus.post(EventBus.java:181) ~[worldedit-mod-7.3.0.jar:?]
        at com.sk89q.worldedit.bukkit.WorldEditPlugin.setupWorldData(WorldEditPlugin.java:205) ~[?:?]
        at com.sk89q.worldedit.bukkit.WorldEditPlugin$WorldInitListener.onWorldInit(WorldEditPlugin.java:534) ~[?:?]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[arclight-1.20.4-1.0.4-SNAPSHOT-e88b7bf.jar:?]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[arclight-1.20.4-1.0.4-SNAPSHOT-e88b7bf.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[arclight-1.20.4-1.0.4-SNAPSHOT-e88b7bf.jar:?]
        at net.minecraft.server.MinecraftServer.handler$zbh000$arclight$worldInit(MinecraftServerMixin.java:2245) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_3786(MinecraftServerMixin.java:366) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_3735(MinecraftServerMixin.java:330) ~[server-intermediary.jar:?]
        at net.minecraft.class_3176.method_3823(DedicatedServerMixin_Vanilla.java:169) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServerMixin.java:2074) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServerMixin.java:270) ~[server-intermediary.jar:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.IllegalStateException: Currently invalid
        at com.sk89q.worldedit.util.lifecycle.Lifecycled.lambda$valueOrThrow$0(Lifecycled.java:99) ~[worldedit-mod-7.3.0.jar:?]
        at java.util.Optional.orElseThrow(Optional.java:403) ~[?:?]
        at com.sk89q.worldedit.util.lifecycle.Lifecycled.valueOrThrow(Lifecycled.java:99) ~[worldedit-mod-7.3.0.jar:?]
        at com.sk89q.worldedit.fabric.FabricWorldEdit.getRegistry(FabricWorldEdit.java:118) ~[worldedit-mod-7.3.0.jar:?]
        at com.sk89q.worldedit.fabric.FabricAdapter.adapt(FabricAdapter.java:212) ~[worldedit-mod-7.3.0.jar:?]
        at com.sk89q.worldedit.fabric.internal.FabricTransmogrifier.transmogToMinecraft(FabricTransmogrifier.java:117) ~[worldedit-mod-7.3.0.jar:?]
        at com.sk89q.worldedit.fabric.FabricAdapter.adapt(FabricAdapter.java:188) ~[worldedit-mod-7.3.0.jar:?]
        at com.sk89q.worldedit.fabric.FabricBlockRegistry.getInternalBlockStateId(FabricBlockRegistry.java:71) ~[worldedit-mod-7.3.0.jar:?]
        at com.sk89q.worldedit.extension.platform.Capability$4.ready(Capability.java:100) ~[worldedit-mod-7.3.0.jar:?]
        at com.sk89q.worldedit.extension.platform.PlatformManager.lambda$handleNewPlatformReady$0(PlatformManager.java:342) ~[worldedit-mod-7.3.0.jar:?]
        at java.util.Map.forEach(Map.java:713) ~[?:?]
        at com.sk89q.worldedit.extension.platform.PlatformManager.handleNewPlatformReady(PlatformManager.java:342) ~[worldedit-mod-7.3.0.jar:?]
        at com.sk89q.worldedit.util.eventbus.MethodHandleEventHandler.dispatch(MethodHandleEventHandler.java:51) ~[worldedit-mod-7.3.0.jar:?]
        at com.sk89q.worldedit.util.eventbus.EventHandler.handleEvent(EventHandler.java:73) ~[worldedit-mod-7.3.0.jar:?]
        ... 14 more

完整错误日志：
[debug.log]
https://paste.ubuntu.com/p/CNRy8FFxzS/

[latest.log]
https://paste.ubuntu.com/p/BtxrJBBF6T/

**Comment by Shybella** [comment]
Don't use the Bukkit version of Worldedit, use the Forge or Fabric version.

**Comment by heipiao233** [comment]
可能就是mc版本太新，WE还不支持

**Comment by luoxiawuchen** [comment]
> 可能就是mc版本太新，WE还不支持

补充：经过测试，单独安装fabric版不影响，同时安装fabric和bukkit版本时才会出现上述影响（无法编辑树叶）（但就奇怪是怎么就树叶方块的编辑优先级bukkit版会大于fabric。）

**Comment by luoxiawuchen** [comment]
已解决 arclight-wiki：https://wiki.izzel.io/s/arclight-docs/doc/troubleshooting-1Ay2vsmIrn
