### ISSUE TITLE
[1.19.2] The /restart command must be used twice to restart server

### ISSUE THREAD

**Issue by mattervisualizer** [IzzelAliz/Arclight#1327]
### I have confirmed that ...

- [X] Arclight is up to date
- [X] unable to reproduce in Spigot
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Forge

### Arclight version

arclight-1.19.2-1.0.5-696a298

### OS & Java versions

OS: Debian 12, Java: openjdk 17.0.10

### Plugins and Mods

```raw
Plugins (38): LuckPerms, InventoryRollbackPlus, BlueMap, ArmorStandAdjustor, Chunky, OpenInv, Suicide, PlaceholderAPI, UltimateAutoRestart, FJoLM, SimpleMail, BlueMapCustomSkinProvider, BlueMapPlayerControl, spark, SetSpawn, ChunkyBorder, ProtocolLib, HeroAction, FastLeafDecay, Maintenance, PL-Hide, GSit, CustomHelp, NBTAPI, Hat, Vault, InvisibleItemFrames, PlayerParticles, LPC, WelcomeMessageReloaded, AdvancedBan, DeluxeMenus, SuperVanish, ChatManager, DiscordSRV, TabList, Plan, DeathMessages

Mod List:
• mods_folder [opt] saturn.jar : saturn (0.1.2) - 1
• mods_folder [api] supermartijn642config.jar : supermartijn642configlib (1.1.8) - 1
• mods_folder [fix] netherportalfix.jar : netherportalfix (10.0.2) - 1
• mods_folder [main] connectablechains.jar : connectiblechains (2.1.4) - 1
• mods_folder [main] beautify-translated-by-mv.jar : beautify (1.4.3) - 1
• mods_folder [api] playeranimationlib.jar : playeranimator (0.4.0) - 1
• mods_folder [api] botarium.jar : botarium (1.9.2) - 1
• mods_folder [main] ae2.jar : ae2 (12.9.9) - 1
• mods_folder [main] naturalist.jar : naturalist (4.0.3) - 1
• mods_folder [fix] gpumemleakfix.jar : gpumemleakfix (1.19.2-1.6) - 1
• mods_folder [fix] clumps.jar : clumps (9.0.0+14) - 1
• mods_folder [opt] fastasyncworldsave.jar : fastasyncworldsave (1.19.2-1.2) - 1
• mods_folder [main] toggleitemframes.jar : toggleableitemframes (2.0.0-1.19.3-forge) - 1
• mods_folder [fix] shutupexperimentalsettings.jar : shutupexperimentalsettings (1.0.5) - 1
• mods_folder [api] ctm.jar : ctm (1.19.2-1.1.6+8) - 1
• mods_folder [api] configured.jar : configured (2.1.1) - 1
• JarInJar mixinextras-forge-0.2.0-beta.6.jar : mixinextras (0.2.0-beta.6) - 1
• mods_folder [fix] anti-xray.jar : antixray (1.3.0) - 1
• mods_folder [main] re-deco-translated-by-mv.jar : redeco (1.5.0) - 1
• mods_folder [opt] rhodioum.jar : lazydfu (0.1.3) - 1
• mods_folder [opt] starlight.jar : starlight (1.1.1+forge.a3aea74) - 1
• mods_folder [main-create-addon] create-steam-n-rails-translated-by-ja.jar : railways (1.5.3+forge-mc1.19.2) - 1
• mods_folder [main-create-addon] create-newage.jar : create_new_age (1.1.1) - 1
• mods_folder [api] balm.jar : balm (4.6.0) - 1
• mods_folder [opt] dynamicview.jar : dynview (2.3) - 1
• mods_folder [main] crafttweaker.jar : crafttweaker (10.1.55) - 1
• mods_folder [fix] memoryleakfix.jar : memoryleakfix (1.1.5) - 1
• mods_folder [api] melody.jar : melody (1.0.1) - 1
• mods_folder [main-ie-addon] i-pertrolium-translated-by-mv.jar : immersivepetroleum (4.2.0-28) - 1
• mods_folder [api] cloth.jar : cloth_config (8.3.115) - 1
• minecraft forge-1.19.2-43.3.8-universal.jar : forge (43.3.8) - 1
• mods_folder [api] konkrete.jar : konkrete (1.8.0) - 1
• mods_folder [client] emotecraft.jar : emotecraft (2.2.7-b.build.47) - 1
• mods_folder [main] chipped.jar : chipped (2.1.5) - 1
• minecraft server-1.19.2-20220805.130853-srg.jar : minecraft (1.19.2) - 1
• mods_folder [main] dyenamics-translated-by-mv.jar : dyenamics (2.0.0) - 1
• mods_folder [opt] smoothchunks.jar : smoothchunk (1.19.2-3.5) - 1
• mods_folder [main] ie.jar : immersiveengineering (1.19.2-9.2.3-167) - 1
• mods_folder [fix] nochatreports.jar : nochatreports (1.19.2-v1.5.1) - 1
• mods_folder [api] creativecore.jar : creativecore (2.9.3) - 1
• JarInJar spectrelib-forge-0.12.8+1.19.2.jar : spectrelib (0.12.8+1.19.2) - 1
• mods_folder [api] supermatrijn642core.jar : supermartijn642corelib (1.1.16) - 1
• mods_folder [opt] smoothboot.jar : smoothboot (0.0.4) - 1
• mods_folder [main] fairylights.jar : fairylights (6.0.0) - 1
• mods_folder [main-create-addon] create-craft-tweaker.jar : createtweaker (3.0.0.7) - 1
• mods_folder [api] resourcefulconfig.jar : resourcefulconfig (1.0.20) - 1
• mods_folder [opt] venus.jar : venus (0.0.1) - 1
• mods_folder [opt] betterfps.jar : betterfpsdist (1.19.2-4.0) - 1
• JarInJar kffmod-3.12.0.jar : kotlinforforge (3.12.0) - 1
• mods_folder [api] iceberg.jar : iceberg (1.1.4) - 1
• JarInJar flywheel-forge-1.19.2-0.6.10-20.jar : flywheel (0.6.10-20) - 1
• mods_folder [main] create.jar : create (0.5.1.f) - 1
• mods_folder [main-create-addon] create-deco-translated-by-ja.jar : createdeco (1.3.3-1.19.2) - 1
• mods_folder [main] ironchestsrestocked-translated-by-mv.jar : ironchests (3.1.3) - 1
• mods_folder [main-create-addon] create-stuff-translated-by-ja.jar : create_sa (2.0.4.) - 1
• mods_folder [main] polymorph.jar : polymorph (0.46.6+1.19.2) - 1
• mods_folder [main-polymorph-addon] polyae2.jar : polyeng (0.1.0-1.19.2) - 1
• mods_folder [opt] entityculling.jar : entityculling (1.6.1) - 1
• mods_folder [opt] betterchunkloading.jar : betterchunkloading (1.19.2-2.5) - 1
• mods_folder [fix] antighost.jar : antighost (1.19.1-forge42.0.1-1.1.3) - 1
• mods_folder [main] fancymenu.jar : fancymenu (3.1.5) - 1
• mods_folder [api] resourcefullib.jar : resourcefullib (1.1.24) - 1
• mods_folder [opt] pluto.jar : pluto (0.0.9) - 1
• mods_folder [main] mccrayfishfunituremod.jar : cfm (7.0.0-pre35) - 1
• mods_folder [api] architectury.jar : architectury (6.5.85) - 1
• mods_folder [opt] ferritecore.jar : ferritecore (5.0.3) - 1
• mods_folder [fix] aiimprovements.jar : aiimprovements (0.5.2) - 1
• mods_folder [api] cupboard.jar : cupboard (1.19.2-2.1) - 1
• arclight arclight-1.19.2-1.0.5-696a298.jar : arclight (1.19.2-1.0.5-696a298) - 1
• mods_folder [opt] async-locator.jar : asynclocator (1.3.0) - 1
• mods_folder [fix] notelemetry.jar : no_telemetry (1.8.0) - 1
• mods_folder [api] geckolib.jar : geckolib3 (3.1.40) - 1
• mods_folder [main] crittersandcompanions-translated-by-mv.jar : crittersandcompanions (1.19.2-2.1.1) - 1
• mods_folder [main] adastra.jar : ad_astra (1.12.7) - 1
```

### Description

I noticed an interesting feature of this bug, it occurs exclusively when any player logs on to the server. i.e. if you restart the server with the /restart command and there is no one logged on to the server, the server will restart correctly. Otherwise - you need to write the command twice, and the console error occurs:

- [Mon 18:24:37 ERROR STDERR]     at java.base/java.util.ArrayList$Itr.next(ArrayList.java:967)
- [Mon 18:24:37 ERROR STDERR]     at TRANSFORMER/arclight@1.19.2-1.0.5-696a298/org.spigotmc.RestartCommand.restart(RestartCommand.java:57)
- [Mon 18:24:37 ERROR STDERR]     at TRANSFORMER/arclight@1.19.2-1.0.5-696a298/org.spigotmc.RestartCommand.restart(RestartCommand.java:40)
- [Mon 18:24:37 ERROR STDERR]     at TRANSFORMER/arclight@1.19.2-1.0.5-696a298/org.spigotmc.RestartCommand$1.run(RestartCommand.java:31)
- [Mon 18:24:37 ERROR STDERR]     at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.bridge$drainQueuedTasks(MinecraftServerMixin.java:2208)
- [Mon 18:24:37 ERROR STDERR]     at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.level.ServerChunkCache$MainThreadExecutor.m_7245_(ServerChunkCache_MainThreadExecutorMixin.java:633)
- [Mon 18:24:37 ERROR STDERR]     at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.level.ServerChunkCache.m_8466_(ServerChunkCacheMixin.java:267)
- [Mon 18:24:37 ERROR STDERR]     at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.m_129961_(MinecraftServerMixin.java:751)
- [Mon 18:24:37 ERROR STDERR]     at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.m_7245_(MinecraftServerMixin.java:740)
- [Mon 18:24:37 ERROR STDERR]     at TRANSFORMER/minecraft@1.19.2/net.minecraft.util.thread.BlockableEventLoop.m_18701_(BlockableEventLoop.java:140)
- [Mon 18:24:37 ERROR STDERR]     at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.m_130012_(MinecraftServerMixin.java:726)
- [Mon 18:24:37 ERROR STDERR]     at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.m_130011_(MinecraftServerMixin.java:2131)
- [Mon 18:24:37 ERROR STDERR]     at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.m_206580_(MinecraftServerMixin.java:244)
- [Mon 18:24:37 ERROR STDERR]     at java.base/java.lang.Thread.run(Thread.java:840)

the entire log is shown below

### Step to reproduce

1. Load the server
2. Join the server
3. Restart the server with /restart command in game or in console

### Logs

[latest.log](https://github.com/IzzelAliz/Arclight/files/15067417/latest.log)

### Server pack link (Optional)

https://drive.google.com/file/d/1_rnrZ6-ed3Fw1_lmD2jBnEtEV8hmd3vD/view?usp=share_link

**Comment by mattervisualizer** [comment]
UPDATE: I did the same thing on a clean server, where no plugins or mods are installed. everything is the same - the command does not work
