### ISSUE TITLE
[1.20.1] cannot connect to server with "Invalid payload REGISTER"

### ISSUE THREAD

**Issue by medi-torimorta** [IzzelAliz/Arclight#1333]
### I have confirmed that ...

- [X] Arclight is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [x] unable to reproduce in Spigot
- [X] unable to reproduce in Forge

### Arclight version

arclight-forge-1.20.1-1.0.5-1a8925b

### OS & Java versions

OS:Ubuntu 22.04 x64, Java:openjdk version 18.0.2-ea

### Plugins and Mods

```raw
create
create enchantment industry plus
```

### Description

1. run a server with arclight trials 1.0.5 release
2. try to connect
3. get kicked with message "Invalid payload REGISTER!"
4. check the latest.log and see the error
`org.bukkit.plugin.messaging.ChannelNameTooLongException: Attempted to send a Plugin Message to a channel that was too large. The maximum length a channel may be is 64 chars (attempted 65 - 'create_enchantment_industry_plus:create_enchantment_industry_plus.`

maybe the same fix as below can be applied to 1.20.1?
https://github.com/IzzelAliz/Arclight/pull/1319

**Comment by hank9999** [comment]
> The maximum length a channel may be is 64 chars (attempted 65

It seems like a same problem

**Comment by hank9999** [comment]
The patch has been merged to Whisper(1.20.4)

**Comment by TheFairyMan** [comment]
Hope I'm not reviving this needlessly, instead of creating my own for the same problem.
Also using 1.20.1 version with "arclight-forge-1.20.1-1.0.5".

The error is the same, but with a different mod: [Dungeon's Delight (CurseForge)](https://www.curseforge.com/minecraft/mc-mods/dungeons-delight), Farmer's delight Add-on.

I have seen a fix for papermc that allows you to add this startup flag to increase the channel lenght: _-Dpaper.disableChannelLimit=true_ Located [here](https://docs.papermc.io/velocity/faq#:~:text=Invalid%20payload%20REGISTER%20%E2%80%8B&text=This%20error%20typically%20occurs%20on,flags%20and%20restarting%20the%20server.)

While this one doesn't works, I couldn't find one for bukkit or something else that did the job.

I'm not sure if Whisper mentioned above does that, but if it does, is there a possibility of it being backported to 1.20.1?

Also, for reference, this is the error:

`[20:01:05 ERROR]: Couldn't register custom payload
org.bukkit.plugin.messaging.ChannelNameTooLongException: Attempted to send a Plugin Message to a channel that was too large. The maximum length a channel may be is 64 chars (attempted 65 - 'dungeons_delight_gourmet_battles:dungeons_delight_gourmet_battles.
        at org.bukkit.plugin.messaging.StandardMessenger.validateAndCorrectChannel(StandardMessenger.java:500) ~[arclight-1.20.1-1.0.5-1a8925b.jar%23314!/:arclight-1.20.1-1.0.5-1a8925b]
        at org.bukkit.craftbukkit.v1_20_R1.entity.CraftPlayer.addChannel(CraftPlayerMixin.java:2308) ~[arclight-1.20.1-1.0.5-1a8925b.jar%23314!/:arclight-1.20.1-1.0.5-1a8925b]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.md71ef68$lambda$arclight$customPayload$7$0(ServerPlayNetHandlerMixin.java:3610) ~[server-1.20.1-20230612.114412-srg.jar%23467!/:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[server-1.20.1-20230612.114412-srg.jar%23467!/:?]
        at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:156) ~[server-1.20.1-20230612.114412-srg.jar%23467!/:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[server-1.20.1-20230612.114412-srg.jar%23467!/:?]
        at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServerMixin.java:770) ~[server-1.20.1-20230612.114412-srg.jar%23467!/:?]
        at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServerMixin.java:161) ~[server-1.20.1-20230612.114412-srg.jar%23467!/:?]
        at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:130) ~[server-1.20.1-20230612.114412-srg.jar%23467!/:?]
        at net.minecraft.server.MinecraftServer.m_129961_(MinecraftServerMixin.java:753) ~[server-1.20.1-20230612.114412-srg.jar%23467!/:?]
        at net.minecraft.server.MinecraftServer.m_7245_(MinecraftServerMixin.java:747) ~[server-1.20.1-20230612.114412-srg.jar%23467!/:?]
        at net.minecraft.util.thread.BlockableEventLoop.m_18699_(BlockableEventLoop.java:115) ~[server-1.20.1-20230612.114412-srg.jar%23467!/:?]
        at net.minecraft.server.MinecraftServer.m_130012_(MinecraftServerMixin.java:732) ~[server-1.20.1-20230612.114412-srg.jar%23467!/:?]
        at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServerMixin.java:2074) ~[server-1.20.1-20230612.114412-srg.jar%23467!/:?]
        at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServerMixin.java:251) ~[server-1.20.1-20230612.114412-srg.jar%23467!/:?]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]`

**Comment by hank9999** [comment]
[arclight-forge-1.20.1-1.0.6-SNAPSHOT.zip](https://github.com/user-attachments/files/16422672/arclight-forge-1.20.1-1.0.6-SNAPSHOT.zip)
@TheFairyMan @medi-torimorta Hi, I built a jar with patch #1437 (#1319), could you try it?

**Comment by TheFairyMan** [comment]
Yep, it worked just fine, I didn't see any errors either, thank you.
I don't know any other mods like Dungeon's Delight that caused such issues to test them, and see if it's working for more stuff.

**Comment by OktavioMex** [comment]
@hank9999 hellow Bro i have i think the same problem but i dont use Forge i use Fabric and the error is this,
Couldn't register custom payload
org.bukkit.plugin.messaging.ChannelNameTooLongException: Attempted to send a Plugin Message to a channel that was too large. The maximum length a channel may be is 64 chars (attempted 70 - 'friendsandfoes:networking/friendsandfoes/moobloom_variants_sync_packet.
        at org.bukkit.plugin.messaging.StandardMessenger.validateAndCorrectChannel(StandardMessenger.java:500) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.entity.CraftPlayer.addChannel(CraftPlayer.java:2339) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleCustomPayload(ServerGamePacketListenerImpl.java:3583) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundCustomPayloadPacket.handle(ServerboundCustomPayloadPacket.java:37) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundCustomPayloadPacket.handle(ServerboundCustomPayloadPacket.java:15) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:51) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1338) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1315) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1308) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1286) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1174) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.20.1.jar:git-Paper-196]
        at java.lang.Thread.run(Thread.java:842) ~[?:?]

i hope can you help me, i want to create a server in my PC to play with my friends, the server has mods and start well but when im try to conect send me the error invalid payload register

**Comment by hank9999** [comment]
@OktavioMex sorry to reply you late, I just saw this message.
You should check what you are using, and create a new issue to your server software.
This project is a forge software with bukkit.

**Comment by hank9999** [comment]
@medi-torimorta Should we close this issue? The patch has been applied to 1.20.1 for a long time.

**Comment by medi-torimorta** [comment]
sorry i’ve forgotten about this.
i’ll close the issue, thanks!
