### ISSUE TITLE
Arclight Downloader Keep on crashing

### ISSUE THREAD

**Issue by ARS-Ajah** [IzzelAliz/Arclight#1348]
# Arclight Downloader Keep on crashing

Arclight Trials/1.0.5
Minecraft 1.20.1
Forge 47.2.20

When i tried to download arclight with arclight-forge-1.20.1-1.0.5.jar this happen 
*Exception in thread "main" java.lang.NoSuchMethodError: 'void sun.misc.Unsafe.en
sureClassInitialized(java.lang.Class)'
    at io.izzel.arclight.api.Unsafe.ensureClassInitialized(Unsafe.java:249)
    at io.izzel.arclight.api.Unsafe.<clinit>(Unsafe.java:26)
    at io.izzel.arclight.forgeinstaller.ForgeInstaller.<clinit>(ForgeInstall
er.java:57)
    at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized0(Native Met
hod)
    at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized(Unsafe.java
:1160)
    at java.base/java.lang.invoke.DirectMethodHandle.checkInitialized(Direct
MethodHandle.java:382)
    at java.base/java.lang.invoke.DirectMethodHandle.ensureInitialized(Direc
tMethodHandle.java:370)
    at java.base/java.lang.invoke.DirectMethodHandle.internalMemberNameEnsur
eInit(DirectMethodHandle.java:335)
    at io.izzel.arclight.boot.application.Main_Forge.forgeInstall(Main_Forge
.java:41)
    at io.izzel.arclight.boot.application.Main_Forge.main(Main_Forge.java:19
)
    at io.izzel.arclight.server.Launcher.main(Launcher.java:18)*
 How do i fix it I Am using JDK-22

**Comment by IzzelAliz** [comment]
Use jdk 21.
