### ISSUE TITLE
arclight doesnt launch

### ISSUE THREAD

**Issue by Ivannivi** [IzzelAliz/Arclight#1365]
### I have confirmed that ...

- [X] Arclight is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Forge

### Arclight version

arclight-forge-1.20.4-1.0.3-13f0d63.jar

### OS & Java versions

Windows 11 pro java 17.0.8 2023-07-18 LTS

### Plugins and Mods

```raw
mods:
        - balm 9.0.9
        - betterdeserttemples 1.20.4-Forge-3.4.4
        - betterdungeons 1.20.4-Forge-4.4.4
        - betterendisland 1.20.4-Forge-2.4.3
        - betterfortresses 1.20.4-Forge-2.4.4
        - betterjungletemples 1.20.4-Forge-2.4.4
        - bettermineshafts 1.20.4-Forge-4.4.2
        - betteroceanmonuments 1.20.4-Forge-3.4.3
        - betterstrongholds 1.20.4-Forge-4.4.3
        - betterwitchhuts 1.20.4-Forge-3.4.3
        - chunky 1.3.146
        - cloth_config 13.0.121
        - collective 7.61
        - cristellib 1.2.2
        - dcintegration 3.0.5
        - doubledoors 5.8
        - fallingtree 1.20.4.3
        - forge 49.0.31
        - forgeconfigapiport 20.4.3
                \-- mixinextras 0.3.5
        - ibeeditor 2.2.8
        - inventoryessentials 10.0.4
        - inventoryprofilesnext 1.10.10
        - kotlinforforge 4.10.0
        - leavesbegone 20.4.1
        - minecraft 1.20.4
        - netherportalfix 15.0.1
        - puzzleslib 20.4.44
        - servercore 1.5.0+1.20.4
        - t_and_t 1.12.1
        - tectonic 2.3.4
        - worldedit 7.3.0+6678-55745ad
        - yungsapi 1.20.4-Forge-4.4.3
        - yungsbridges 1.20.4-Forge-4.4.2
        - yungsextras 1.20.4-Forge-4.4.2\
plugins: none
```

### Description

[13:13:24 ERROR] [mixin]: Critical injection failure: LVT in net/minecraft/server/players/PlayerList::m_11236_(Lnet/minecraft/server/level/ServerPlayer;Z)Lnet/minecraft/server/level/ServerPlayer; has incompatible changes at opcode 453 in callback servercore.common.mixins.json:optimizations.players.PlayerListMixin->@Inject::servercore$moveToSpawn(Lnet/minecraft/server/level/ServerPlayer;ZLorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;Lnet/minecraft/core/BlockPos;FZLnet/minecraft/server/level/ServerLevel;Ljava/util/Optional;Lnet/minecraft/server/level/ServerLevel;Lnet/minecraft/server/level/ServerPlayer;)V.
 Expected: [Lnet/minecraft/core/BlockPos;, F, Z, Lnet/minecraft/server/level/ServerLevel;, Ljava/util/Optional;, Lnet/minecraft/server/level/ServerLevel;, Lnet/minecraft/server/level/ServerPlayer;]
    Found: [Lorg/bukkit/Location;, Z, Lorg/bukkit/event/player/PlayerRespawnEvent$RespawnReason;, Lnet/minecraft/core/BlockPos;, F, Z, Lorg/bukkit/World;]
Available: [Lorg/bukkit/Location;, Z, Lorg/bukkit/event/player/PlayerRespawnEvent$RespawnReason;, Lnet/minecraft/core/BlockPos;, F, Z, Lorg/bukkit/World;, Z, Lnet/minecraft/server/level/ServerLevel;, Lnet/minecraft/server/level/ServerLevel;, Lnet/minecraft/server/level/ServerPlayer;]
[13:13:24 ERROR] [STDERR]: java.lang.reflect.InvocationTargetException
[13:13:24 ERROR] [STDERR]:      at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[13:13:24 ERROR] [STDERR]:      at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[13:13:24 ERROR] [STDERR]:      at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[13:13:24 ERROR] [STDERR]:      at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[13:13:24 ERROR] [STDERR]:      at SECURE-BOOTSTRAP/net.minecraftforge.fmlloader@1.20.4-49.0.31/net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:91)
[13:13:24 ERROR] [STDERR]:      at SECURE-BOOTSTRAP/net.minecraftforge.fmlloader@1.20.4-49.0.31/net.minecraftforge.fml.loading.targets.CommonLaunchHandler.lambda$makeService$0(CommonLaunchHandler.java:75)
[13:13:24 ERROR] [STDERR]:      at SECURE-BOOTSTRAP/cpw.mods.modlauncher@10.1.2/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
[13:13:24 ERROR] [STDERR]:      at SECURE-BOOTSTRAP/cpw.mods.modlauncher@10.1.2/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:74)
[13:13:24 ERROR] [STDERR]:      at SECURE-BOOTSTRAP/cpw.mods.modlauncher@10.1.2/cpw.mods.modlauncher.Launcher.run(Launcher.java:114)
[13:13:24 ERROR] [STDERR]:      at SECURE-BOOTSTRAP/cpw.mods.modlauncher@10.1.2/cpw.mods.modlauncher.Launcher.main(Launcher.java:73)
[13:13:24 ERROR] [STDERR]:      at SECURE-BOOTSTRAP/cpw.mods.modlauncher@10.1.2/cpw.mods.modlauncher.BootstrapEntry.main(BootstrapEntry.java:17)
[13:13:24 ERROR] [STDERR]:      at SECURE-BOOTSTRAP/arclight.boot@1.0/io.izzel.arclight.boot.forge.mod.ModuleBootstrap.main(ModuleBootstrap.java:46)
[13:13:24 ERROR] [STDERR]:      at arclight.launch@1.0/io.izzel.arclight.boot.forge.application.ApplicationBootstrap.moduleMain(ApplicationBootstrap.java:84)
[13:13:24 ERROR] [STDERR]:      at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[13:13:24 ERROR] [STDERR]:      at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[13:13:24 ERROR] [STDERR]:      at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[13:13:24 ERROR] [STDERR]:      at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[13:13:24 ERROR] [STDERR]:      at io.izzel.arclight.boot.forge.application.ApplicationBootstrap.start(ApplicationBootstrap.java:46)
[13:13:24 ERROR] [STDERR]:      at io.izzel.arclight.boot.forge.application.ApplicationBootstrap.main(ApplicationBootstrap.java:21)
[13:13:24 ERROR] [STDERR]:      at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[13:13:24 ERROR] [STDERR]:      at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[13:13:24 ERROR] [STDERR]:      at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[13:13:24 ERROR] [STDERR]:      at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[13:13:24 ERROR] [STDERR]:      at io.izzel.arclight.boot.forge.application.Main_Forge.main(Main_Forge.java:23)
[13:13:24 ERROR] [STDERR]:      at io.izzel.arclight.server.Launcher.main(Launcher.java:27)
[13:13:24 ERROR] [STDERR]: Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
[13:13:24 ERROR] [STDERR]:      at SECURE-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392)
[13:13:24 ERROR] [STDERR]:      at SECURE-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:250)
[13:13:24 ERROR] [STDERR]:      at SECURE-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.service.modlauncher.MixinTransformationHandler.processClass(MixinTransformationHandler.java:131)
[13:13:24 ERROR] [STDERR]:      at SECURE-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.launch.MixinLaunchPluginLegacy.processClass(MixinLaunchPluginLegacy.java:131)
[13:13:24 ERROR] [STDERR]:      at SECURE-BOOTSTRAP/cpw.mods.modlauncher@10.1.2/cpw.mods.modlauncher.serviceapi.ILaunchPluginService.processClassWithFlags(ILaunchPluginService.java:142)
[13:13:24 ERROR] [STDERR]:      at SECURE-BOOTSTRAP/cpw.mods.modlauncher@10.1.2/cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:91)
[13:13:24 ERROR] [STDERR]:      at SECURE-BOOTSTRAP/cpw.mods.modlauncher@10.1.2/cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:107)
[13:13:24 ERROR] [STDERR]:      at SECURE-BOOTSTRAP/cpw.mods.modlauncher@10.1.2/cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:44)
[13:13:24 ERROR] [STDERR]:      at cpw.mods.securejarhandler/net.minecraftforge.securemodules.SecureModuleClassLoader.readerToClass(SecureModuleClassLoader.java:473)
[13:13:24 ERROR] [STDERR]:      at cpw.mods.securejarhandler/net.minecraftforge.securemodules.SecureModuleClassLoader.findClass(SecureModuleClassLoader.java:399)
[13:13:24 ERROR] [STDERR]:      at cpw.mods.securejarhandler/net.minecraftforge.securemodules.SecureModuleClassLoader.loadClass(SecureModuleClassLoader.java:415)
[13:13:24 ERROR] [STDERR]:      at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
[13:13:24 ERROR] [STDERR]:      at TRANSFORMER/minecraft@1.20.4/net.minecraft.server.Main.lambda$main$4(Main.java:240)
[13:13:24 ERROR] [STDERR]:      at TRANSFORMER/minecraft@1.20.4/net.minecraft.server.MinecraftServer.m_129872_(MinecraftServerMixin_Forge.java:265)
[13:13:24 ERROR] [STDERR]:      at TRANSFORMER/minecraft@1.20.4/net.minecraft.server.Main.main(Main.java:232)
[13:13:24 ERROR] [STDERR]:      ... 25 more
[13:13:24 ERROR] [STDERR]: Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: LVT in net/minecraft/server/players/PlayerList::m_11236_(Lnet/minecraft/server/level/ServerPlayer;Z)Lnet/minecraft/server/level/ServerPlayer; has incompatible changes at opcode 453 in callback servercore.common.mixins.json:optimizations.players.PlayerListMixin->@Inject::servercore$moveToSpawn(Lnet/minecraft/server/level/ServerPlayer;ZLorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;Lnet/minecraft/core/BlockPos;FZLnet/minecraft/server/level/ServerLevel;Ljava/util/Optional;Lnet/minecraft/server/level/ServerLevel;Lnet/minecraft/server/level/ServerPlayer;)V.
 Expected: [Lnet/minecraft/core/BlockPos;, F, Z, Lnet/minecraft/server/level/ServerLevel;, Ljava/util/Optional;, Lnet/minecraft/server/level/ServerLevel;, Lnet/minecraft/server/level/ServerPlayer;]
    Found: [Lorg/bukkit/Location;, Z, Lorg/bukkit/event/player/PlayerRespawnEvent$RespawnReason;, Lnet/minecraft/core/BlockPos;, F, Z, Lorg/bukkit/World;]
Available: [Lorg/bukkit/Location;, Z, Lorg/bukkit/event/player/PlayerRespawnEvent$RespawnReason;, Lnet/minecraft/core/BlockPos;, F, Z, Lorg/bukkit/World;, Z, Lnet/minecraft/server/level/ServerLevel;, Lnet/minecraft/server/level/ServerLevel;, Lnet/minecraft/server/level/ServerPlayer;]
[13:13:24 ERROR] [STDERR]:      at SECURE-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.injection.callback.CallbackInjector.inject(CallbackInjector.java:497)
[13:13:24 ERROR] [STDERR]:      at SECURE-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.injection.callback.CallbackInjector.inject(CallbackInjector.java:447)
[13:13:24 ERROR] [STDERR]:      at SECURE-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.injection.code.Injector.inject(Injector.java:276)
[13:13:24 ERROR] [STDERR]:      at SECURE-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.injection.struct.InjectionInfo.inject(InjectionInfo.java:445)
[13:13:24 ERROR] [STDERR]:      at SECURE-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1355)
[13:13:24 ERROR] [STDERR]:      at SECURE-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1051)
[13:13:24 ERROR] [STDERR]:      at SECURE-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:400)
[13:13:24 ERROR] [STDERR]:      at SECURE-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325)
[13:13:24 ERROR] [STDERR]:      at SECURE-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:383)
[13:13:24 ERROR] [STDERR]:      at SECURE-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:365)
[13:13:24 ERROR] [STDERR]:      at SECURE-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
[13:13:24 ERROR] [STDERR]:      ... 39 more
[13:13:24 ERROR] [STDERR]: Fail to launch Arclight.

This should not happen

### Step to reproduce

1. install arch 1.20.4 forge 2. install mods that i put 3. launch archlight

### Logs

[latest.log](https://github.com/user-attachments/files/15604564/latest.log)

**Comment by sepsol** [comment]
Same here. The error can be seen in this minimal reproducible Docker example:
https://gist.github.com/sepsol/0daecc4e3ee85e52c6cf3ff34fc9eaea

![image](https://github.com/IzzelAliz/Arclight/assets/47871887/53bc6c91-4485-4524-aa7d-879ffb4039a6)
