### ISSUE TITLE
[1.20.1] unable to interact with creature entities with error: Failed to handle packet net.minecraft.network.protocol.game.ServerboundInteractPacket@302014d0, suppressing error

### ISSUE THREAD

**Issue by HybridizedHere** [IzzelAliz/Arclight#1381]
### I have confirmed that ...

- [X] Arclight is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Forge

### Arclight version

arclight-forge-1.20.1-1.0.5

### OS & Java versions

JDK 17 Pebblehost server

### Plugins and Mods

```raw
Mods:
architectury-9.1.13-forge
betterarcheology-1.1.5-1.20.1		
bettervillage-forge-1.20.1-3.2.0	
Chunk-Pregenerator-1.20-4.4.2	
citadel-2.5.3-1.20.1	
comforts-forge-6.3.5+1.20.1		
cupboard-1.20.1-2.3
curios-forge-5.7.0+1.20.1	
dragonmounts-1.20.1-1.2.3-beta	
dungeons-and-taverns-3.0.3 [Forge]	
easy_npc_1.20.1-4.5.1	
evenmoreinstruments-1.20+1.20.1-3.0
FarmersDelight-1.20.1-1.2.4
fennecfox-forge-1.20.1-1.0.0		
friendsandfoes-forge-mc1.20.1-2.0.9	
From-The-Fog-1.20-v1.9.2-Forge-Fabric		
genshinstrument-1.20+1.20.1-3.4		
geophilic-v2.1.0-mc1.20u1.20.2		
handcrafted-forge-1.20.1-3.0.5		
hourglass-1.20-1.2.1.1		
libraryferret-forge-1.20.1-4.0.0		
mavapi-1.1.3-mc1.20.1		
mavm-1.2.4-mc1.20		
moonlight-1.20-2.9.17-forge		
moremobvariants-forge+1.20-1.2.2		
musicalfoxes-1.0.3	
mvs-4.1.1-1.20-forge		
octolib-1.20.1-0.3		
off-hand-combat-2.0.0-forge		
Philips-Ruins1.20.1-3.2		
rare-ice-0.6.0		
resourcefullib-forge-1.20.1-2.1.23		
sit-1.20.1-1.3.5	
sophisticatedbackpacks-1.20.1-3.20.1.1012		
sophisticatedcore-1.20.1-0.6.3.553	
structureessentials-1.20.1-3.2		
supplementaries-1.20-2.7.36
tidal-towns-1.2		
voicechat-forge-1.20.1-2.4.32		
WWOO-FABRIC+FORGE+QUILT-2.0.0		
Xaeros_Minimap_23.9.7_Forge_1.20		
XaerosWorldMap_1.37.8_Forge_1.20		
YungsApi-1.20-Forge-4.0.3		
YungsBetterDungeons-1.20-Forge-4.0.3		
YungsBetterEndIsland-1.20-Forge-2.0.5		
YungsBetterJungleTemples-1.20-Forge-2.0.4	
YungsBetterMineshafts-1.20-Forge-4.0.4		
YungsBetterNetherFortresses-1.20-Forge-2.0.5		
YungsBetterOceanMonuments-1.20-Forge-3.0.4
YungsBetterStrongholds-1.20-Forge-4.0.3		
YungsBetterWitchHuts-1.20-Forge-3.0.3		
YungsBridges-1.20-Forge-4.0.3	
YungsExtras-1.20-Forge-4.0.3

Plugins:
EssentialsX-2.19.7
EssentialsXChat-2.19.7 	
ImageOnMap	
LibsDisguises-10.0.37-Free
ProjectKorra-1.11.1	
ProtocolLib	
VoxelSniper-6.1.2	
worldedit-bukkit-7.3.1
```

### Description

Attempting to interact with any creature entity produces this error in console and nothing happens to said entity, example listed is when you try to attack a horse:

16.06 17:29:33 [Server] [ERROR] Failed to handle packet net.minecraft.network.protocol.game.ServerboundInteractPacket@58f5560b, suppressing error
16.06 17:29:33 [Server] [INFO] java.lang.ClassCastException: class net.minecraft.server.network.ServerGamePacketListenerImpl$1Handler$17d8c5878872466592518e5237b27837 cannot be cast to class cinnamon.ofc.Listener (net.minecraft.server.network.ServerGamePacketListenerImpl$1Handler$17d8c5878872466592518e5237b27837 is in module minecraft@1.20.1 of loader 'TRANSFORMER' @c5e69a5; cinnamon.ofc.Listener is in module offhandcombat@2.0.0 of loader 'TRANSFORMER' @c5e69a5)
16.06 17:29:33 [Server] [INFO] at net.minecraft.server.network.ServerGamePacketListenerImpl.modify$zck000$handleInteract(ServerPlayNetHandlerMixin.java:4314) ~[server-1.20.1-20230612.114412-srg.jar%23271!/:?]
16.06 17:29:33 [Server] [INFO] at net.minecraft.server.network.ServerGamePacketListenerImpl.m_6946_(ServerPlayNetHandlerMixin.java:3152) ~[server-1.20.1-20230612.114412-srg.jar%23271!/:?]
16.06 17:29:33 [Server] [INFO] at net.minecraft.network.protocol.game.ServerboundInteractPacket.m_5797_(ServerboundInteractPacket.java:53) ~[server-1.20.1-20230612.114412-srg.jar%23271!/:?]
16.06 17:29:33 [Server] [INFO] at net.minecraft.network.protocol.game.ServerboundInteractPacket.m_5797_(ServerboundInteractPacket.java:13) ~[server-1.20.1-20230612.114412-srg.jar%23271!/:?]
16.06 17:29:33 [Server] [INFO] at net.minecraft.network.protocol.PacketUtils.mdae7374$lambda$ensureRunningOnSameThread$0$0(PacketThreadUtilMixin.java:537) ~[server-1.20.1-20230612.114412-srg.jar%23271!/:?]
16.06 17:29:33 [Server] [INFO] at net.minecraft.server.TickTask.run(TickTask.java:18) ~[server-1.20.1-20230612.114412-srg.jar%23271!/:?]
16.06 17:29:33 [Server] [INFO] at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:156) ~[server-1.20.1-20230612.114412-srg.jar%23271!/:?]
16.06 17:29:33 [Server] [INFO] at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[server-1.20.1-20230612.114412-srg.jar%23271!/:?]
16.06 17:29:33 [Server] [INFO] at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServerMixin.java:770) ~[server-1.20.1-20230612.114412-srg.jar%23271!/:?]
16.06 17:29:35 [Server] [INFO] at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServerMixin.java:161) ~[server-1.20.1-20230612.114412-srg.jar%23271!/:?]
16.06 17:29:35 [Server] [INFO] at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:130) ~[server-1.20.1-20230612.114412-srg.jar%23271!/:?]
16.06 17:29:35 [Server] [INFO] at net.minecraft.server.MinecraftServer.m_129961_(MinecraftServerMixin.java:753) ~[server-1.20.1-20230612.114412-srg.jar%23271!/:?]
16.06 17:29:35 [Server] [INFO] at net.minecraft.server.MinecraftServer.m_7245_(MinecraftServerMixin.java:747) ~[server-1.20.1-20230612.114412-srg.jar%23271!/:?]
16.06 17:29:35 [Server] [INFO] at net.minecraft.util.thread.BlockableEventLoop.m_18701_(BlockableEventLoop.java:139) ~[server-1.20.1-20230612.114412-srg.jar%23271!/:?]
16.06 17:29:35 [Server] [INFO] at net.minecraft.server.MinecraftServer.m_130012_(MinecraftServerMixin.java:733) ~[server-1.20.1-20230612.114412-srg.jar%23271!/:?]
16.06 17:29:35 [Server] [INFO] at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServerMixin.java:2074) ~[server-1.20.1-20230612.114412-srg.jar%23271!/:?]
16.06 17:29:35 [Server] [INFO] at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServerMixin.java:251) ~[server-1.20.1-20230612.114412-srg.jar%23271!/:?]
16.06 17:29:35 [Server] [INFO] at java.lang.Thread.run(Thread.java:833) ~[?:?]

### Step to reproduce

Install arclight and all listed mods/plugins on a Pebblehost server
join the server and attempt to interact with creature entities/mobs

### Server pack link (Optional)

https://www.mediafire.com/file/thckytwa4ku91vm/pebblehost-698241-f9zubu.zip/file

**Comment by wuweidmw** [comment]
我的世界1.21.1neoforge端可以对生物造成伤害但是1.21.1的arclight端无法用任何方法伤害生物

**Comment by HybridizedHere** [comment]
So just switching to NeoForge instead of Forge would be the easiest fix?

**Comment by wuweidmw** [comment]
> So just switching to NeoForge instead of Forge would be the easiest fix?所以直接切换到 NeoForge 而不是 Forge 会是最简单的解决方法吗？

This is a server primarily based on plugins, with additional terrain and horizon mods.
