### ISSUE TITLE
Server crash when calling the player#getUUID method

### ISSUE THREAD

**Issue by joagar21** [IzzelAliz/Arclight#1405]
### I have confirmed that ...

- [ ] Arclight is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Forge

### Arclight version

arclight-1.16.5

### OS & Java versions

java 11

### Plugins and Mods

```raw
pixelmon and essentials, tried removing essentials but its still crashing the server so essentials has nothing to do with it.
```

### Description

here is the full error 
java.lang.NoSuchMethodError: net.minecraft.entity.Entity.getUUID()Ljava/util/UUID;
	at github.SpawnListener.SpawnListener$PokemonSpawnListener.onPokemonSpawn(SpawnListener.java:22) ~[?:?]
	at io.izzel.arclight.common.mod.util.PluginEventHandler_145_PokemonSpawnListener_onPokemonSpawn_SpawnEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?]
	at com.pixelmonmod.pixelmon.api.spawning.SpawnAction.doSpawn(SpawnAction.java:94) ~[pixelmon:1.16.5-9.1.11]
	at com.pixelmonmod.pixelmon.api.spawning.archetypes.entities.pokemon.SpawnActionPokemon.doSpawn(SpawnActionPokemon.java:140) ~[pixelmon:1.16.5-9.1.11]
	at com.pixelmonmod.pixelmon.api.spawning.archetypes.entities.pokemon.SpawnActionPokemon.doSpawn(SpawnActionPokemon.java:42) ~[pixelmon:1.16.5-9.1.11]
	at com.pixelmonmod.pixelmon.api.spawning.archetypes.spawners.TickingSpawner.doPass(TickingSpawner.java:100) ~[pixelmon:1.16.5-9.1.11]
	at com.pixelmonmod.pixelmon.api.spawning.SpawnerCoordinator.onTick(SpawnerCoordinator.java:50) ~[pixelmon:1.16.5-9.1.11]
	at net.minecraftforge.eventbus.ASMEventHandler_148_SpawnerCoordinator_onTick_ServerTickEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.fml.hooks.BasicEventHooks.onPostServerTick(BasicEventHooks.java:106) ~[forge:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServerMixin.java:828) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServerMixin.java:1917) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServerMixin.java:232) ~[?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]

### Step to reproduce

when a pokemon spawns it crashes the server

**Comment by Elyas2024** [comment]
remove all client side mods, keep only the mods required on both, so fps mods should not be on server unless it says it can work on both or serverside

**Comment by joagar21** [comment]
im using some pixelmon API as well so it shouldnt be removed and what do you mean by fps? frames per second?
