### ISSUE TITLE
The "arclight-1.21-Fabric" server crashes when I look for the End portal in Minecraft.

### ISSUE THREAD

**Issue by LCServer3yf** [IzzelAliz/Arclight#1411]
### I have confirmed that ...

- [ ] Arclight is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Forge

### Arclight version

arclight-fabric-1.21-1.0.0-SNAPSHOT

### OS & Java versions

java version "21.0.3" 2024-04-16 LTS Java(TM) SE Runtime Environment (build 21.0.3+7-LTS-152) Java HotSpot(TM) 64-Bit Server VM (build 21.0.3+7-LTS-152, mixed mode, sharing)

### Plugins and Mods

```raw
1 Plugins SkinsRestorer - 0 Mods
```

### Description

[17:39:26 ERROR]: Encountered an unexpected exception
net.minecraft.class_148: Ticking block entity
        at net.minecraft.server.MinecraftServer.method_3813(MinecraftServerMixin.java:1025) ~[server-intermediary.jar:?]
        at net.minecraft.class_3176.method_3813(DedicatedServerMixin_Vanilla.java:299) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_3748(MinecraftServerMixin.java:912) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServerMixin.java:697) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServerMixin.java:281) ~[server-intermediary.jar:?]
        at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
Caused by: java.lang.IllegalStateException: Not implemented.
        at io.izzel.arclight.mixin.DecorationOps.callsite(DecorationOps.java:20) ~[server.jar:arclight-1.21-1.0.0-SNAPSHOT-b3349e9]
        at net.minecraft.class_1917.redirect$bjf000$arclight$spawnerSpawn(BaseSpawnerMixin.java:550) ~[server-intermediary.jar:?]
        at net.minecraft.class_1917.method_31588(BaseSpawnerMixin.java:166) ~[server-intermediary.jar:?]
        at net.minecraft.class_2636.method_31697(class_2636.java:58) ~[server-intermediary.jar:?]
        at net.minecraft.class_2818$class_5563.method_31703(LevelChunk_BoundTickingBlockEntityMixin.java:683) ~[server-intermediary.jar:?]
        at net.minecraft.class_2818$class_5564.method_31703(class_2818.java:737) ~[server-intermediary.jar:?]
        at net.minecraft.class_1937.method_18471(LevelMixin.java:488) ~[server-intermediary.jar:?]
        at net.minecraft.class_3218.method_18765(ServerLevelMixin.java:413) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_3813(MinecraftServerMixin.java:1021) ~[server-intermediary.jar:?]
        ... 5 more
        
        
[crash-2024-07-05_17.39.27-server.txt](https://github.com/user-attachments/files/16114312/crash-2024-07-05_17.39.27-server.txt)

### Step to reproduce

1. Enter the server
2. Look for the End portal

### Logs

[latest.log](https://github.com/user-attachments/files/16114353/latest.log)

**Comment by luluxiaoyu** [comment]
[18:02:07 WARN] [neruina]: Neruina caught an exception, see below for cause
java.lang.NullPointerException: Cannot invoke "net.minecraft.class_2561.getString()" because "defaultMessage" is null
        at net.minecraft.class_3222.method_6078(ServerPlayerMixin_Vanilla.java:2464) ~[server-intermediary.jar:?]
        at net.minecraft.class_1309.method_5643(LivingEntityMixin_Vanilla.java:1252) ~[server-intermediary.jar:?]
        at net.minecraft.class_1657.method_5643(PlayerMixin_Vanilla.java:2609) ~[server-intermediary.jar:?]
        at net.minecraft.class_3222.method_5643(ServerPlayerMixin_Vanilla.java:811) ~[server-intermediary.jar:?]
        at net.minecraft.class_1685.method_7454(ThrownTridentMixin.java:134) ~[server-intermediary.jar:?]
        at net.minecraft.class_1676.method_7488(ProjectileMixin.java:208) ~[server-intermediary.jar:?]
        at net.minecraft.class_1676.method_59860(ProjectileMixin.java:182) ~[server-intermediary.jar:?]
        at net.minecraft.class_1665.method_5773(AbstractArrowMixin.java:248) ~[server-intermediary.jar:?]
        at net.minecraft.class_1685.method_5773(ThrownTridentMixin.java:94) ~[server-intermediary.jar:?]
        at net.minecraft.class_3218.method_18762(ServerLevelMixin.java:770) ~[server-intermediary.jar:?]
        at net.minecraft.class_1937.mixinextras$bridge$accept$207(LevelMixin.java) ~[server-intermediary.jar:?]
        at com.bawnorton.neruina.handler.TickHandler.safelyTickEntities(TickHandler.java:92) ~[Neruina-2.1.0-fabric+1.21.j
ar:?]
        at net.minecraft.class_1937.wrapOperation$dij000$neruina$catchTickingEntities$notTheCauseOfTickLag(LevelMixin.java
:8583) ~[server-intermediary.jar:?]
        at net.minecraft.class_1937.method_18472(LevelMixin.java:498) ~[server-intermediary.jar:?]
        at net.minecraft.class_3218.method_31420(ServerLevelMixin.java:408) ~[server-intermediary.jar:?]
        at net.minecraft.class_5574.method_31791(class_5574.java:54) ~[server-intermediary.jar:?]
        at net.minecraft.class_3218.method_18765(ServerLevelMixin.java:372) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_3813(MinecraftServerMixin.java:1021) ~[server-intermediary.jar:?]
        at net.minecraft.class_3176.method_3813(DedicatedServerMixin_Vanilla.java:299) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_3748(MinecraftServerMixin.java:912) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServerMixin.java:697) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServerMixin.java:281) ~[server-intermediary.jar:?]
        at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
[18:02:12 ERROR]: Failed to handle packet net.minecraft.class_2799@4de46236, suppressing error
java.lang.NullPointerException: Cannot invoke "org.bukkit.Location.getWorld()" because "location" is null
        at net.minecraft.class_3324.handler$zfh000$arclight$postRespawn(PlayerListMixin.java:1388) ~[server-intermediary.j
ar:?]
        at net.minecraft.class_3324.method_14556(PlayerListMixin.java:530) ~[server-intermediary.jar:?]
        at net.minecraft.class_3244.method_12068(ServerPlayNetHandlerMixin.java:1672) ~[server-intermediary.jar:?]
        at net.minecraft.class_2799.method_12120(class_2799.java:32) ~[server-intermediary.jar:?]
        at net.minecraft.class_2799.method_11054(class_2799.java:8) ~[server-intermediary.jar:?]
        at net.minecraft.class_2600.md897fe7$arclight$lambda$ensureRunningOnSameThread$0$0(PacketThreadUtilMixin.java:538)
 ~[server-intermediary.jar:?]
        at net.minecraft.class_3738.run(class_3738.java:18) ~[server-intermediary.jar:?]
        at net.minecraft.class_1255.method_18859(BlockableEventLoopMixin.java:162) ~[server-intermediary.jar:?]
        at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_24306(MinecraftServerMixin.java:864) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_18859(MinecraftServerMixin.java:173) ~[server-intermediary.jar:?]
        at net.minecraft.class_1255.method_16075(BlockableEventLoopMixin.java:136) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_20415(MinecraftServerMixin.java:846) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_16075(MinecraftServerMixin.java:840) ~[server-intermediary.jar:?]
        at net.minecraft.class_1255.method_18857(BlockableEventLoopMixin.java:145) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_18857(MinecraftServerMixin.java:810) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_16208(MinecraftServerMixin.java:815) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServerMixin.java:702) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServerMixin.java:281) ~[server-intermediary.jar:?]
        at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]  seem the same？

**Comment by luluxiaoyu** [comment]
似乎是一样的问题 刷怪笼似乎有问题？
`java.lang.IllegalStateException: Not implemented.
        at io.izzel.arclight.mixin.DecorationOps.callsite(DecorationOps.java:20) ~[arclight-fabric-1.21-1.0.0-SNAPSHOT.jar
:arclight-1.21-1.0.0-SNAPSHOT-c47e085]
        at net.minecraft.class_1917.redirect$blk000$arclight$spawnerSpawn(BaseSpawnerMixin.java:550) ~[server-intermediary
.jar:?]
        at net.minecraft.class_1917.method_31588(BaseSpawnerMixin.java:166) ~[server-intermediary.jar:?]
        at net.minecraft.class_2636.method_31697(class_2636.java:58) ~[server-intermediary.jar:?]
        at net.minecraft.class_2818$class_5563.mixinextras$bridge$tick$11(LevelChunk_BoundTickingBlockEntityMixin.java) ~[
server-intermediary.jar:?]
        at com.bawnorton.neruina.handler.TickHandler.safelyTickBlockEntity(TickHandler.java:169) ~[Neruina-2.1.0-fabric+1.
21.jar:?]
        at net.minecraft.class_2818$class_5563.wrapOperation$dii000$neruina$catchTickingBlockEntity$notTheCauseOfTickLag(L
evelChunk_BoundTickingBlockEntityMixin.java:1808) ~[server-intermediary.jar:?]
        at net.minecraft.class_2818$class_5563.method_31703(LevelChunk_BoundTickingBlockEntityMixin.java:683) ~[server-int
ermediary.jar:?]
        at net.minecraft.class_2818$class_5564.method_31703(class_2818.java:737) ~[server-intermediary.jar:?]
        at net.minecraft.class_1937.method_18471(LevelMixin.java:488) ~[server-intermediary.jar:?]
        at net.minecraft.class_3218.method_18765(ServerLevelMixin.java:413) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_3813(MinecraftServerMixin.java:1021) ~[server-intermediary.jar:?]
        at net.minecraft.class_3176.method_3813(DedicatedServerMixin_Vanilla.java:299) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_3748(MinecraftServerMixin.java:912) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServerMixin.java:697) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServerMixin.java:281) ~[server-intermediary.jar:?]
        at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]`

**Comment by luluxiaoyu** [comment]
跳下虚空后：（用的是当前actions最新版本）
`[18:27:34 WARN] [neruina]: Neruina caught an exception, see below for cause
net.minecraft.class_148: Ticking player
        at net.minecraft.class_3222.method_14226(ServerPlayerMixin_Vanilla.java:652) ~[server-intermediary.jar:?]
        at net.minecraft.class_3244.mixinextras$bridge$method_14226$201(ServerPlayNetHandlerMixin.java) ~[server-intermedi
ary.jar:?]
        at com.bawnorton.neruina.handler.TickHandler.safelyTickPlayer(TickHandler.java:122) ~[Neruina-2.1.0-fabric+1.21.ja
r:?]
        at net.minecraft.class_3244.wrapOperation$dif000$neruina$catchTickingPlayer$notTheCauseOfTickLag(ServerPlayNetHand
lerMixin.java:8282) ~[server-intermediary.jar:?]
        at net.minecraft.class_3244.method_18784(ServerPlayNetHandlerMixin.java:268) ~[server-intermediary.jar:?]
        at net.minecraft.class_2535.method_10754(ConnectionMixin.java:401) ~[server-intermediary.jar:?]
        at net.minecraft.class_3242.method_14357(class_3242.java:176) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_3813(MinecraftServerMixin.java:1032) ~[server-intermediary.jar:?]
        at net.minecraft.class_3176.method_3813(DedicatedServerMixin_Vanilla.java:299) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_3748(MinecraftServerMixin.java:912) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServerMixin.java:697) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServerMixin.java:281) ~[server-intermediary.jar:?]
        at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
Caused by: java.lang.NoSuchMethodError: 'net.minecraft.class_1542 net.minecraft.class_3222.drop(net.minecraft.class_1799,
boolean, boolean, boolean)'
        at org.bukkit.craftbukkit.v1_21_R1.event.CraftEventFactory.callPlayerDeathEvent(CraftEventFactoryMixin.java:941) ~
[arclight-1.21-1.0.0-SNAPSHOT-c47e085.jar:?]
        at net.minecraft.class_3222.method_6078(ServerPlayerMixin_Vanilla.java:2477) ~[server-intermediary.jar:?]
        at net.minecraft.class_1309.method_5643(LivingEntityMixin_Vanilla.java:1252) ~[server-intermediary.jar:?]
        at net.minecraft.class_1657.method_5643(PlayerMixin_Vanilla.java:2609) ~[server-intermediary.jar:?]
        at net.minecraft.class_3222.method_5643(ServerPlayerMixin_Vanilla.java:811) ~[server-intermediary.jar:?]
        at net.minecraft.class_1309.method_5825(LivingEntityMixin_Vanilla.java:1953) ~[server-intermediary.jar:?]
        at net.minecraft.class_1297.method_31473(EntityMixin_Vanilla.java:572) ~[server-intermediary.jar:?]
        at net.minecraft.class_1297.method_5670(EntityMixin_Vanilla.java:549) ~[server-intermediary.jar:?]
        at net.minecraft.class_1309.method_5670(LivingEntityMixin_Vanilla.java:406) ~[server-intermediary.jar:?]
        at net.minecraft.class_1297.method_5773(EntityMixin_Vanilla.java:487) ~[server-intermediary.jar:?]
        at net.minecraft.class_1309.method_5773(LivingEntityMixin_Vanilla.java:2468) ~[server-intermediary.jar:?]
        at net.minecraft.class_1657.method_5773(PlayerMixin_Vanilla.java:312) ~[server-intermediary.jar:?]
        at net.minecraft.class_3222.method_14226(ServerPlayerMixin_Vanilla.java:588) ~[server-intermediary.jar:?]
        ... 12 more`

**Comment by LCServer3yf** [comment]
> 刷怪笼似乎有问题？ `java.lang.IllegalStateException: Not implemented. at io.izzel.arclight.mixin.DecorationOps.callsite(DecorationOps.java:20) ~[arclight-fabric-1.21-1.0.0-SNAPSHOT.jar :arclight-1.21-1.0.0-SNAPSHOT-c47e085] at net.minecraft.class_1917.redirect$blk000$arclight$spawnerSpawn(BaseSpawnerMixin.java:550) ~[server-intermediary .jar:?] at net.minecraft.class_1917.method_31588(BaseSpawnerMixin.java:166) ~[server-intermediary.jar:?] at net.minecraft.class_2636.method_31697(class_2636.java:58) ~[server-intermediary.jar:?] at net.minecraft.class_2818$class_5563.mixinextras$bridge$tick$11(LevelChunk_BoundTickingBlockEntityMixin.java) ~[ server-intermediary.jar:?] at com.bawnorton.neruina.handler.TickHandler.safelyTickBlockEntity(TickHandler.java:169) ~[Neruina-2.1.0-fabric+1. 21.jar:?] at net.minecraft.class_2818$class_5563.wrapOperation$dii000$neruina$catchTickingBlockEntity$notTheCauseOfTickLag(L evelChunk_BoundTickingBlockEntityMixin.java:1808) ~[server-intermediary.jar:?] at net.minecraft.class_2818$class_5563.method_31703(LevelChunk_BoundTickingBlockEntityMixin.java:683) ~[server-int ermediary.jar:?] at net.minecraft.class_2818$class_5564.method_31703(class_2818.java:737) ~[server-intermediary.jar:?] at net.minecraft.class_1937.method_18471(LevelMixin.java:488) ~[server-intermediary.jar:?] at net.minecraft.class_3218.method_18765(ServerLevelMixin.java:413) ~[server-intermediary.jar:?] at net.minecraft.server.MinecraftServer.method_3813(MinecraftServerMixin.java:1021) ~[server-intermediary.jar:?] at net.minecraft.class_3176.method_3813(DedicatedServerMixin_Vanilla.java:299) ~[server-intermediary.jar:?] at net.minecraft.server.MinecraftServer.method_3748(MinecraftServerMixin.java:912) ~[server-intermediary.jar:?] at net.minecraft.server.MinecraftServer.method_29741(MinecraftServerMixin.java:697) ~[server-intermediary.jar:?] at net.minecraft.server.MinecraftServer.method_29739(MinecraftServerMixin.java:281) ~[server-intermediary.jar:?] at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]`

I tried to locate the End portal using Ender Eyes and Spectator Mode to easily find the structure. Once there, I switched to Creative Mode, and that's when the server crashed. I thought it might be due to some mod or plugin, so I did a clean reinstallation of the server and created a new world. I searched for the End again, and the same thing happened. The only thing I can think of is a problem with the general spawner or the 'Silverfish Spawner.' Beyond this point, I don't know if the issue lies in how I have set up the server or if it is an Arclight problem.

I just did more testing using /Give to get spawners and placing them with zombies, then changing the time to night. This ultimately causes a crash. The spawners during the day and without spawning mobs do not cause a crash
