### ISSUE TITLE
Smithing table doesnt work

### ISSUE THREAD

**Issue by NioR1o** [IzzelAliz/Arclight#1413]
### I have confirmed that ...

- [ ] Arclight is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Forge

### Arclight version

arclight-fabric-1.21-1.0.0-SNAPSHOT.jar

### OS & Java versions

20

### Plugins and Mods

```raw
Without plugins and mods
```

### Description

Smithing table doesnt work correctly

https://github.com/IzzelAliz/Arclight/assets/121576844/177d7df8-bcfc-4dbc-9214-47bd1a9b7e6a

### Step to reproduce

1 Open smithing table
2 Try to apply a template

### Logs

[09:35:49 ERROR]: Failed to handle packet net.minecraft.class_2813@4bf26b71, suppressing error
net.minecraft.class_148: Container click
        at net.minecraft.class_1703.method_7593(AbstractContainerMenuMixin.java:304) ~[server-intermediary.jar:?]
        at net.minecraft.class_3244.method_12076(ServerPlayNetHandlerMixin.java:3445) ~[server-intermediary.jar:?]
        at net.minecraft.class_2813.method_12191(class_2813.java:71) ~[server-intermediary.jar:?]
        at net.minecraft.class_2813.method_11054(class_2813.java:14) ~[server-intermediary.jar:?]
        at net.minecraft.class_2600.md4fa0ae$arclight$lambda$ensureRunningOnSameThread$0$0(PacketThreadUtilMixin.java:538) ~[server-intermediary.jar:?]
        at net.minecraft.class_3738.run(class_3738.java:18) ~[server-intermediary.jar:?]
        at net.minecraft.class_1255.method_18859(BlockableEventLoopMixin.java:162) ~[server-intermediary.jar:?]
        at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_24306(MinecraftServerMixin.java:864) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_18859(MinecraftServerMixin.java:173) ~[server-intermediary.jar:?]
        at net.minecraft.class_1255.method_16075(BlockableEventLoopMixin.java:136) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_20415(MinecraftServerMixin.java:846) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_16075(MinecraftServerMixin.java:840) ~[server-intermediary.jar:?]
        at net.minecraft.class_1255.method_18857(BlockableEventLoopMixin.java:145) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_18857(MinecraftServerMixin.java:810) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_16208(MinecraftServerMixin.java:815) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServerMixin.java:702) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServerMixin.java:281) ~[server-intermediary.jar:?]
        at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
Caused by: java.lang.IllegalStateException: Not implemented.
        at io.izzel.arclight.mixin.DecorationOps.callsite(DecorationOps.java:20) ~[arclight.jar:arclight-1.21-1.0.0-SNAPSHOT-b3349e9]
        at net.minecraft.class_4862.redirect$ban000$arclight$prepareSmithing(SmithingTableContainerMixin.java:528) ~[server-intermediary.jar:?]
        at net.minecraft.class_4862.method_24928(SmithingTableContainerMixin.java:108) ~[server-intermediary.jar:?]
        at net.minecraft.class_4861.method_7609(ItemCombinerMixin.java:106) ~[server-intermediary.jar:?]
        at net.minecraft.class_4861$3.method_5431(class_4861.java:96) ~[server-intermediary.jar:?]
        at net.minecraft.class_1277.redirect$chg000$fabric-transfer-api-v1$fabric_redirectMarkDirty(SimpleContainerMixin.java:1043) ~[server-intermediary.jar:?]
        at net.minecraft.class_1277.method_5447(SimpleContainerMixin.java:142) ~[server-intermediary.jar:?]
        at net.minecraft.class_1735.method_7673(SlotMixin.java:75) ~[server-intermediary.jar:?]
        at net.minecraft.class_1735.method_48931(SlotMixin.java:66) ~[server-intermediary.jar:?]
        at net.minecraft.class_1735.method_53512(SlotMixin.java:63) ~[server-intermediary.jar:?]
        at net.minecraft.class_1703.method_7616(AbstractContainerMenuMixin.java:661) ~[server-intermediary.jar:?]
        at net.minecraft.class_4861.method_7601(ItemCombinerMixin.java:147) ~[server-intermediary.jar:?]
        at net.minecraft.class_1703.method_30010(AbstractContainerMenuMixin.java:394) ~[server-intermediary.jar:?]
        at net.minecraft.class_1703.method_7593(AbstractContainerMenuMixin.java:294) ~[server-intermediary.jar:?]
        ... 18 more
[09:35:50 ERROR]: Failed to handle packet net.minecraft.class_2813@72c8b756, suppressing error
net.minecraft.class_148: Container click
        at net.minecraft.class_1703.method_7593(AbstractContainerMenuMixin.java:304) ~[server-intermediary.jar:?]
        at net.minecraft.class_3244.method_12076(ServerPlayNetHandlerMixin.java:3445) ~[server-intermediary.jar:?]
        at net.minecraft.class_2813.method_12191(class_2813.java:71) ~[server-intermediary.jar:?]
        at net.minecraft.class_2813.method_11054(class_2813.java:14) ~[server-intermediary.jar:?]
        at net.minecraft.class_2600.md4fa0ae$arclight$lambda$ensureRunningOnSameThread$0$0(PacketThreadUtilMixin.java:538) ~[server-intermediary.jar:?]
        at net.minecraft.class_3738.run(class_3738.java:18) ~[server-intermediary.jar:?]
        at net.minecraft.class_1255.method_18859(BlockableEventLoopMixin.java:162) ~[server-intermediary.jar:?]
        at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_24306(MinecraftServerMixin.java:864) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_18859(MinecraftServerMixin.java:173) ~[server-intermediary.jar:?]
        at net.minecraft.class_1255.method_16075(BlockableEventLoopMixin.java:136) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_20415(MinecraftServerMixin.java:846) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_16075(MinecraftServerMixin.java:840) ~[server-intermediary.jar:?]
        at net.minecraft.class_1255.method_18857(BlockableEventLoopMixin.java:145) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_18857(MinecraftServerMixin.java:810) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_16208(MinecraftServerMixin.java:815) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServerMixin.java:702) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServerMixin.java:281) ~[server-intermediary.jar:?]
        at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
Caused by: java.lang.IllegalStateException: Not implemented.
        at io.izzel.arclight.mixin.DecorationOps.callsite(DecorationOps.java:20) ~[arclight.jar:arclight-1.21-1.0.0-SNAPSHOT-b3349e9]
        at net.minecraft.class_4862.redirect$ban000$arclight$prepareSmithing(SmithingTableContainerMixin.java:528) ~[server-intermediary.jar:?]
        at net.minecraft.class_4862.method_24928(SmithingTableContainerMixin.java:108) ~[server-intermediary.jar:?]
        at net.minecraft.class_4861.method_7609(ItemCombinerMixin.java:106) ~[server-intermediary.jar:?]
        at net.minecraft.class_4861$3.method_5431(class_4861.java:96) ~[server-intermediary.jar:?]
        at net.minecraft.class_1277.redirect$chg000$fabric-transfer-api-v1$fabric_redirectMarkDirty(SimpleContainerMixin.java:1043) ~[server-intermediary.jar:?]
        at net.minecraft.class_1277.method_5447(SimpleContainerMixin.java:142) ~[server-intermediary.jar:?]
        at net.minecraft.class_1735.method_7673(SlotMixin.java:75) ~[server-intermediary.jar:?]
        at net.minecraft.class_1735.method_48931(SlotMixin.java:66) ~[server-intermediary.jar:?]
        at net.minecraft.class_1735.method_53512(SlotMixin.java:63) ~[server-intermediary.jar:?]
        at net.minecraft.class_1703.method_7616(AbstractContainerMenuMixin.java:661) ~[server-intermediary.jar:?]
        at net.minecraft.class_4861.method_7601(ItemCombinerMixin.java:147) ~[server-intermediary.jar:?]
        at net.minecraft.class_1703.method_30010(AbstractContainerMenuMixin.java:394) ~[server-intermediary.jar:?]
        at net.minecraft.class_1703.method_7593(AbstractContainerMenuMixin.java:294) ~[server-intermediary.jar:?]
        ... 18 more
[09:35:50 ERROR]: Failed to handle packet net.minecraft.class_2813@33058f3a, suppressing error
net.minecraft.class_148: Container click
        at net.minecraft.class_1703.method_7593(AbstractContainerMenuMixin.java:304) ~[server-intermediary.jar:?]
        at net.minecraft.class_3244.method_12076(ServerPlayNetHandlerMixin.java:3445) ~[server-intermediary.jar:?]
        at net.minecraft.class_2813.method_12191(class_2813.java:71) ~[server-intermediary.jar:?]
        at net.minecraft.class_2813.method_11054(class_2813.java:14) ~[server-intermediary.jar:?]
        at net.minecraft.class_2600.md4fa0ae$arclight$lambda$ensureRunningOnSameThread$0$0(PacketThreadUtilMixin.java:538) ~[server-intermediary.jar:?]
        at net.minecraft.class_3738.run(class_3738.java:18) ~[server-intermediary.jar:?]
        at net.minecraft.class_1255.method_18859(BlockableEventLoopMixin.java:162) ~[server-intermediary.jar:?]
        at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_24306(MinecraftServerMixin.java:864) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_18859(MinecraftServerMixin.java:173) ~[server-intermediary.jar:?]
        at net.minecraft.class_1255.method_16075(BlockableEventLoopMixin.java:136) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_20415(MinecraftServerMixin.java:846) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_16075(MinecraftServerMixin.java:840) ~[server-intermediary.jar:?]
        at net.minecraft.class_1255.method_18857(BlockableEventLoopMixin.java:145) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_18857(MinecraftServerMixin.java:810) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_16208(MinecraftServerMixin.java:815) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServerMixin.java:702) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServerMixin.java:281) ~[server-intermediary.jar:?]
        at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
Caused by: java.lang.IllegalStateException: Not implemented.
        at io.izzel.arclight.mixin.DecorationOps.callsite(DecorationOps.java:20) ~[arclight.jar:arclight-1.21-1.0.0-SNAPSHOT-b3349e9]
        at net.minecraft.class_4862.redirect$ban000$arclight$prepareSmithing(SmithingTableContainerMixin.java:528) ~[server-intermediary.jar:?]
        at net.minecraft.class_4862.method_24928(SmithingTableContainerMixin.java:115) ~[server-intermediary.jar:?]
        at net.minecraft.class_4861.method_7609(ItemCombinerMixin.java:106) ~[server-intermediary.jar:?]
        at net.minecraft.class_4861$3.method_5431(class_4861.java:96) ~[server-intermediary.jar:?]
        at net.minecraft.class_1277.redirect$chg000$fabric-transfer-api-v1$fabric_redirectMarkDirty(SimpleContainerMixin.java:1043) ~[server-intermediary.jar:?]
        at net.minecraft.class_1277.method_5447(SimpleContainerMixin.java:142) ~[server-intermediary.jar:?]
        at net.minecraft.class_1735.method_7673(SlotMixin.java:75) ~[server-intermediary.jar:?]
        at net.minecraft.class_1735.method_48931(SlotMixin.java:66) ~[server-intermediary.jar:?]
        at net.minecraft.class_1735.method_53512(SlotMixin.java:63) ~[server-intermediary.jar:?]
        at net.minecraft.class_1703.method_7616(AbstractContainerMenuMixin.java:661) ~[server-intermediary.jar:?]
        at net.minecraft.class_4861.method_7601(ItemCombinerMixin.java:147) ~[server-intermediary.jar:?]
        at net.minecraft.class_1703.method_30010(AbstractContainerMenuMixin.java:394) ~[server-intermediary.jar:?]
        at net.minecraft.class_1703.method_7593(AbstractContainerMenuMixin.java:294) ~[server-intermediary.jar:?]

**Comment by TikaTIGER2009** [comment]
yes
I have this problem

**Comment by TikaTIGER2009** [comment]
upgrade pls

**Comment by SEBISTANSF** [comment]
i have this problem too and i don't know how to resolve it hope somone will find a solution :)

**Comment by qyl27** [comment]
Fixed, refer #1491
