### ISSUE TITLE
IT CRASHES HELPPP

### ISSUE THREAD

**Issue by DaniBTZ** [IzzelAliz/Arclight#1425]
### I have confirmed that ...

- [X] Arclight is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Forge

### Arclight version

1.16.5

### OS & Java versions

Windows 11

### Plugins and Mods

```raw
none
```

### Description

it crashes instantly 

### Logs

Using locale en_us and fallback locale zh_cn
2024-07-21 17:35:39,231 main WARN JNDI lookup class is not available because this JRE does not support JNDI. JNDI string lookups will not be available, continuing configuration. Ignoring java.lang.ClassCastException: class org.apache.logging.log4j.core.lookup.JndiLookup
[17:35:39] [main/INFO] [Arclight/]:

       ___           ___     __   /\
      /   | ________/ (_)__ / /  / /
     / /| |/ __/ __/ / / _ / _ \/__/
    / ___ / / / /_/ / / / / // / /
   /_/  |/_/  \__/_/_/\_ /_//_/ /
                     /__/     \/

    Version arclight-1.16.5-1.0.24-551ec3ff
    Build Date 2022-10-04 04:20:42

[17:35:39] [main/INFO] [c.m.m.Launcher/MODLAUNCHER]: ModLauncher running: args [--gameDir, ., --launchTarget, fmlserver, --fml.forgeVersion, 36.2.39, --fml.mcpVersion, 20210115.111550, --fml.mcVersion, 1.16.5, --fml.forgeGroup, net.minecraftforge, nogui]
[17:35:39] [main/INFO] [c.m.m.Launcher/MODLAUNCHER]: ModLauncher 8.1.3+8.1.3+main-8.1.x.c94d18ec starting: java version 21.0.1 by Oracle Corporation
[17:35:40] [main/INFO] [forge/FixSSL]: Added Lets Encrypt root certificates as additional trust
[17:35:40] [main/INFO] [mixin/]: SpongePowered MIXIN Subsystem Version=0.8.4 Source=file:/C:/Users/daniel/OneDrive/Desktop/TEST%20SERVER/libraries/org/spongepowered/mixin/0.8.4/mixin-0.8.4.jar Service=ModLauncher Env=SERVER
[17:35:42] [main/INFO] [mixin/]: Successfully loaded Mixin Connector [io.izzel.arclight.impl.ArclightConnector_Forge]
[17:35:42] [main/INFO] [Arclight/]: Arclight core mixin added.
[17:35:42] [main/INFO] [Arclight/]: Arclight optimization mixin added.
[17:35:42] [main/INFO] [c.m.m.LaunchServiceHandler/MODLAUNCHER]: Launching target 'fmlserver' with arguments [--gameDir, ., nogui]
[17:35:45] [main/WARN] [mixin/]: Error loading class: java/lang/invoke/MethodHandles$Lookup (java.lang.IllegalArgumentException: Class file major version 65 is not supported by active ASM (version 9.0 supports class version 61), reading java.lang.invoke.MethodHandles$Lookup)
[17:35:45] [main/WARN] [mixin/]: Error loading class: java/lang/invoke/MethodHandles$Lookup (java.lang.IllegalArgumentException: Class file major version 65 is not supported by active ASM (version 9.0 supports class version 61), reading java.lang.invoke.MethodHandles$Lookup)
[17:35:45] [main/WARN] [mixin/]: Error loading class: java/util/Map$Entry (java.lang.IllegalArgumentException: Class file major version 65 is not supported by active ASM (version 9.0 supports class version 61), reading java.util.Map$Entry)
[17:35:45] [main/WARN] [mixin/]: Error loading class: java/lang/invoke/MethodHandles$Lookup (java.lang.IllegalArgumentException: Class file major version 65 is not supported by active ASM (version 9.0 supports class version 61), reading java.lang.invoke.MethodHandles$Lookup)
[17:35:45] [main/WARN] [mixin/]: Error loading class: java/lang/invoke/MethodHandles$Lookup (java.lang.IllegalArgumentException: Class file major version 65 is not supported by active ASM (version 9.0 supports class version 61), reading java.lang.invoke.MethodHandles$Lookup)
[17:35:45] [main/WARN] [mixin/]: Error loading class: java/util/Map$Entry (java.lang.IllegalArgumentException: Class file major version 65 is not supported by active ASM (version 9.0 supports class version 61), reading java.util.Map$Entry)
[17:35:45] [main/WARN] [mixin/]: Error loading class: java/lang/invoke/MethodHandles$Lookup (java.lang.IllegalArgumentException: Class file major version 65 is not supported by active ASM (version 9.0 supports class version 61), reading java.lang.invoke.MethodHandles$Lookup)
[17:35:45] [main/WARN] [mixin/]: Error loading class: java/lang/invoke/MethodHandles$Lookup (java.lang.IllegalArgumentException: Class file major version 65 is not supported by active ASM (version 9.0 supports class version 61), reading java.lang.invoke.MethodHandles$Lookup)
[17:35:45] [main/WARN] [mixin/]: Error loading class: java/lang/invoke/MethodHandles$Lookup (java.lang.IllegalArgumentException: Class file major version 65 is not supported by active ASM (version 9.0 supports class version 61), reading java.lang.invoke.MethodHandles$Lookup)
[17:35:45] [main/WARN] [mixin/]: Error loading class: java/util/Map$Entry (java.lang.IllegalArgumentException: Class file major version 65 is not supported by active ASM (version 9.0 supports class version 61), reading java.util.Map$Entry)
[17:35:45] [main/WARN] [mixin/]: Error loading class: java/lang/invoke/MethodHandles$Lookup (java.lang.IllegalArgumentException: Class file major version 65 is not supported by active ASM (version 9.0 supports class version 61), reading java.lang.invoke.MethodHandles$Lookup)
[17:35:45] [main/WARN] [mixin/]: Error loading class: java/lang/invoke/MethodHandles$Lookup (java.lang.IllegalArgumentException: Class file major version 65 is not supported by active ASM (version 9.0 supports class version 61), reading java.lang.invoke.MethodHandles$Lookup)
[17:35:45] [main/WARN] [mixin/]: Error loading class: java/lang/invoke/MethodHandles$Lookup (java.lang.IllegalArgumentException: Class file major version 65 is not supported by active ASM (version 9.0 supports class version 61), reading java.lang.invoke.MethodHandles$Lookup)
[17:35:45] [main/WARN] [mixin/]: Error loading class: java/util/Map$Entry (java.lang.IllegalArgumentException: Class file major version 65 is not supported by active ASM (version 9.0 supports class version 61), reading java.util.Map$Entry)
[17:35:45] [main/WARN] [mixin/]: Error loading class: java/lang/invoke/MethodHandles$Lookup (java.lang.IllegalArgumentException: Class file major version 65 is not supported by active ASM (version 9.0 supports class version 61), reading java.lang.invoke.MethodHandles$Lookup)
[17:35:45] [main/WARN] [mixin/]: Error loading class: java/util/Map$Entry (java.lang.IllegalArgumentException: Class file major version 65 is not supported by active ASM (version 9.0 supports class version 61), reading java.util.Map$Entry)
[17:35:45] [main/WARN] [mixin/]: Error loading class: java/lang/invoke/MethodHandles$Lookup (java.lang.IllegalArgumentException: Class file major version 65 is not supported by active ASM (version 9.0 supports class version 61), reading java.lang.invoke.MethodHandles$Lookup)
[17:35:45] [main/WARN] [mixin/]: Error loading class: java/lang/invoke/MethodHandles$Lookup (java.lang.IllegalArgumentException: Class file major version 65 is not supported by active ASM (version 9.0 supports class version 61), reading java.lang.invoke.MethodHandles$Lookup)
[17:35:45] [main/WARN] [mixin/]: Error loading class: java/lang/invoke/MethodHandles$Lookup (java.lang.IllegalArgumentException: Class file major version 65 is not supported by active ASM (version 9.0 supports class version 61), reading java.lang.invoke.MethodHandles$Lookup)
[17:35:45] [main/WARN] [mixin/]: Error loading class: java/lang/invoke/MethodHandles$Lookup (java.lang.IllegalArgumentException: Class file major version 65 is not supported by active ASM (version 9.0 supports class version 61), reading java.lang.invoke.MethodHandles$Lookup)
[17:35:45] [main/WARN] [mixin/]: Error loading class: java/lang/invoke/MethodHandles$Lookup (java.lang.IllegalArgumentException: Class file major version 65 is not supported by active ASM (version 9.0 supports class version 61), reading java.lang.invoke.MethodHandles$Lookup)
[17:35:45] [main/WARN] [mixin/]: Error loading class: java/util/Map$Entry (java.lang.IllegalArgumentException: Class file major version 65 is not supported by active ASM (version 9.0 supports class version 61), reading java.util.Map$Entry)
[17:35:45] [main/WARN] [mixin/]: Error loading class: java/lang/invoke/MethodHandles$Lookup (java.lang.IllegalArgumentException: Class file major version 65 is not supported by active ASM (version 9.0 supports class version 61), reading java.lang.invoke.MethodHandles$Lookup)
[17:35:45] [main/WARN] [mixin/]: Error loading class: java/lang/invoke/MethodHandles$Lookup (java.lang.IllegalArgumentException: Class file major version 65 is not supported by active ASM (version 9.0 supports class version 61), reading java.lang.invoke.MethodHandles$Lookup)
[17:35:45] [main/WARN] [mixin/]: Error loading class: java/lang/invoke/MethodHandles$Lookup (java.lang.IllegalArgumentException: Class file major version 65 is not supported by active ASM (version 9.0 supports class version 61), reading java.lang.invoke.MethodHandles$Lookup)
[17:35:45] [main/WARN] [mixin/]: Error loading class: java/lang/invoke/MethodHandles$Lookup (java.lang.IllegalArgumentException: Class file major version 65 is not supported by active ASM (version 9.0 supports class version 61), reading java.lang.invoke.MethodHandles$Lookup)
[17:35:45] [main/WARN] [mixin/]: Error loading class: java/util/Map$Entry (java.lang.IllegalArgumentException: Class file major version 65 is not supported by active ASM (version 9.0 supports class version 61), reading java.util.Map$Entry)
[17:35:45] [main/WARN] [mixin/]: Error loading class: java/lang/invoke/MethodHandles$Lookup (java.lang.IllegalArgumentException: Class file major version 65 is not supported by active ASM (version 9.0 supports class version 61), reading java.lang.invoke.MethodHandles$Lookup)
[17:35:45] [main/WARN] [mixin/]: Error loading class: java/lang/Thread$UncaughtExceptionHandler (java.lang.IllegalArgumentException: Class file major version 65 is not supported by active ASM (version 9.0 supports class version 61), reading java.lang.Thread$UncaughtExceptionHandler)
[17:35:45] [main/WARN] [mixin/]: Error loading class: java/lang/invoke/MethodHandles$Lookup (java.lang.IllegalArgumentException: Class file major version 65 is not supported by active ASM (version 9.0 supports class version 61), reading java.lang.invoke.MethodHandles$Lookup)
[17:35:45] [main/WARN] [mixin/]: Error loading class: java/lang/invoke/MethodHandles$Lookup (java.lang.IllegalArgumentException: Class file major version 65 is not supported by active ASM (version 9.0 supports class version 61), reading java.lang.invoke.MethodHandles$Lookup)
[17:35:45] [main/WARN] [mixin/]: Error loading class: java/lang/invoke/MethodHandles$Lookup (java.lang.IllegalArgumentException: Class file major version 65 is not supported by active ASM (version 9.0 supports class version 61), reading java.lang.invoke.MethodHandles$Lookup)
[17:35:45] [main/WARN] [mixin/]: Error loading class: java/lang/invoke/MethodHandles$Lookup (java.lang.IllegalArgumentException: Class file major version 65 is not supported by active ASM (version 9.0 supports class version 61), reading java.lang.invoke.MethodHandles$Lookup)
[17:35:45] [main/WARN] [mixin/]: Error loading class: java/lang/invoke/MethodHandles$Lookup (java.lang.IllegalArgumentException: Class file major version 65 is not supported by active ASM (version 9.0 supports class version 61), reading java.lang.invoke.MethodHandles$Lookup)
[17:35:45] [main/WARN] [mixin/]: Error loading class: java/lang/invoke/MethodHandles$Lookup (java.lang.IllegalArgumentException: Class file major version 65 is not supported by active ASM (version 9.0 supports class version 61), reading java.lang.invoke.MethodHandles$Lookup)
[17:35:45] [main/WARN] [mixin/]: Error loading class: java/lang/invoke/MethodHandles$Lookup (java.lang.IllegalArgumentException: Class file major version 65 is not supported by active ASM (version 9.0 supports class version 61), reading java.lang.invoke.MethodHandles$Lookup)
[17:35:45] [main/WARN] [mixin/]: Error loading class: java/lang/invoke/MethodHandles$Lookup (java.lang.IllegalArgumentException: Class file major version 65 is not supported by active ASM (version 9.0 supports class version 61), reading java.lang.invoke.MethodHandles$Lookup)
[17:35:45] [main/WARN] [mixin/]: Error loading class: java/lang/invoke/MethodHandles$Lookup (java.lang.IllegalArgumentException: Class file major version 65 is not supported by active ASM (version 9.0 supports class version 61), reading java.lang.invoke.MethodHandles$Lookup)
[17:35:45] [main/WARN] [mixin/]: Error loading class: java/lang/invoke/MethodHandles$Lookup (java.lang.IllegalArgumentException: Class file major version 65 is not supported by active ASM (version 9.0 supports class version 61), reading java.lang.invoke.MethodHandles$Lookup)
[17:35:45] [main/WARN] [mixin/]: Error loading class: java/lang/invoke/MethodHandles$Lookup (java.lang.IllegalArgumentException: Class file major version 65 is not supported by active ASM (version 9.0 supports class version 61), reading java.lang.invoke.MethodHandles$Lookup)
[17:35:45] [main/WARN] [mixin/]: Error loading class: java/lang/invoke/MethodHandles$Lookup (java.lang.IllegalArgumentException: Class file major version 65 is not supported by active ASM (version 9.0 supports class version 61), reading java.lang.invoke.MethodHandles$Lookup)
[17:35:45] [main/WARN] [mixin/]: Error loading class: java/lang/invoke/MethodHandles$Lookup (java.lang.IllegalArgumentException: Class file major version 65 is not supported by active ASM (version 9.0 supports class version 61), reading java.lang.invoke.MethodHandles$Lookup)
[17:35:45] [main/WARN] [mixin/]: Error loading class: java/lang/invoke/MethodHandles$Lookup (java.lang.IllegalArgumentException: Class file major version 65 is not supported by active ASM (version 9.0 supports class version 61), reading java.lang.invoke.MethodHandles$Lookup)
[17:35:45] [main/WARN] [mixin/]: Error loading class: java/lang/invoke/MethodHandles$Lookup (java.lang.IllegalArgumentException: Class file major version 65 is not supported by active ASM (version 9.0 supports class version 61), reading java.lang.invoke.MethodHandles$Lookup)
[17:35:45] [main/WARN] [mixin/]: Error loading class: java/lang/invoke/MethodHandles$Lookup (java.lang.IllegalArgumentException: Class file major version 65 is not supported by active ASM (version 9.0 supports class version 61), reading java.lang.invoke.MethodHandles$Lookup)
[17:35:45] [main/WARN] [mixin/]: Error loading class: java/lang/invoke/MethodHandles$Lookup (java.lang.IllegalArgumentException: Class file major version 65 is not supported by active ASM (version 9.0 supports class version 61), reading java.lang.invoke.MethodHandles$Lookup)
[17:35:45] [main/WARN] [mixin/]: Error loading class: java/lang/invoke/MethodHandles$Lookup (java.lang.IllegalArgumentException: Class file major version 65 is not supported by active ASM (version 9.0 supports class version 61), reading java.lang.invoke.MethodHandles$Lookup)
[17:35:45] [main/WARN] [mixin/]: Error loading class: java/lang/invoke/MethodHandles$Lookup (java.lang.IllegalArgumentException: Class file major version 65 is not supported by active ASM (version 9.0 supports class version 61), reading java.lang.invoke.MethodHandles$Lookup)
[17:35:45] [main/WARN] [mixin/]: Error loading class: java/lang/invoke/MethodHandles$Lookup (java.lang.IllegalArgumentException: Class file major version 65 is not supported by active ASM (version 9.0 supports class version 61), reading java.lang.invoke.MethodHandles$Lookup)
[17:35:45] [main/WARN] [mixin/]: Error loading class: java/lang/invoke/MethodHandles$Lookup (java.lang.IllegalArgumentException: Class file major version 65 is not supported by active ASM (version 9.0 supports class version 61), reading java.lang.invoke.MethodHandles$Lookup)
[17:35:45] [main/WARN] [mixin/]: Error loading class: java/lang/invoke/MethodHandles$Lookup (java.lang.IllegalArgumentException: Class file major version 65 is not supported by active ASM (version 9.0 supports class version 61), reading java.lang.invoke.MethodHandles$Lookup)
[17:35:45] [main/WARN] [mixin/]: Error loading class: java/lang/invoke/MethodHandles$Lookup (java.lang.IllegalArgumentException: Class file major version 65 is not supported by active ASM (version 9.0 supports class version 61), reading java.lang.invoke.MethodHandles$Lookup)
[17:35:45] [main/WARN] [mixin/]: Error loading class: java/lang/invoke/MethodHandles$Lookup (java.lang.IllegalArgumentException: Class file major version 65 is not supported by active ASM (version 9.0 supports class version 61), reading java.lang.invoke.MethodHandles$Lookup)
[17:35:45] [main/WARN] [mixin/]: Error loading class: java/lang/invoke/MethodHandles$Lookup (java.lang.IllegalArgumentException: Class file major version 65 is not supported by active ASM (version 9.0 supports class version 61), reading java.lang.invoke.MethodHandles$Lookup)
[17:35:45] [main/WARN] [mixin/]: Error loading class: java/util/Map$Entry (java.lang.IllegalArgumentException: Class file major version 65 is not supported by active ASM (version 9.0 supports class version 61), reading java.util.Map$Entry)
[17:35:45] [main/WARN] [mixin/]: Error loading class: java/util/Map$Entry (java.lang.IllegalArgumentException: Class file major version 65 is not supported by active ASM (version 9.0 supports class version 61), reading java.util.Map$Entry)
[17:35:45] [main/WARN] [mixin/]: Error loading class: java/lang/invoke/MethodHandles$Lookup (java.lang.IllegalArgumentException: Class file major version 65 is not supported by active ASM (version 9.0 supports class version 61), reading java.lang.invoke.MethodHandles$Lookup)
[17:35:45] [main/WARN] [mixin/]: Error loading class: java/lang/invoke/MethodHandles$Lookup (java.lang.IllegalArgumentException: Class file major version 65 is not supported by active ASM (version 9.0 supports class version 61), reading java.lang.invoke.MethodHandles$Lookup)
[17:35:45] [main/WARN] [mixin/]: Error loading class: java/lang/invoke/MethodHandles$Lookup (java.lang.IllegalArgumentException: Class file major version 65 is not supported by active ASM (version 9.0 supports class version 61), reading java.lang.invoke.MethodHandles$Lookup)
[17:35:45] [main/WARN] [mixin/]: Error loading class: java/util/Map$Entry (java.lang.IllegalArgumentException: Class file major version 65 is not supported by active ASM (version 9.0 supports class version 61), reading java.util.Map$Entry)
[17:35:45] [main/WARN] [mixin/]: Error loading class: java/util/Map$Entry (java.lang.IllegalArgumentException: Class file major version 65 is not supported by active ASM (version 9.0 supports class version 61), reading java.util.Map$Entry)
[17:35:45] [main/WARN] [mixin/]: Error loading class: java/lang/invoke/MethodHandles$Lookup (java.lang.IllegalArgumentException: Class file major version 65 is not supported by active ASM (version 9.0 supports class version 61), reading java.lang.invoke.MethodHandles$Lookup)
[17:35:45] [main/WARN] [mixin/]: Error loading class: java/lang/AutoCloseable (java.lang.IllegalArgumentException: Class file major version 65 is not supported by active ASM (version 9.0 supports class version 61), reading java.lang.AutoCloseable)
[17:35:45] [main/WARN] [mixin/]: Error loading class: java/util/concurrent/Executor (java.lang.IllegalArgumentException: Class file major version 65 is not supported by active ASM (version 9.0 supports class version 61), reading java.util.concurrent.Executor)
[17:35:45] [main/WARN] [mixin/]: Error loading class: java/lang/AutoCloseable (java.lang.IllegalArgumentException: Class file major version 65 is not supported by active ASM (version 9.0 supports class version 61), reading java.lang.AutoCloseable)
[17:35:45] [main/WARN] [mixin/]: Error loading class: java/lang/RuntimeException (java.lang.IllegalArgumentException: Class file major version 65 is not supported by active ASM (version 9.0 supports class version 61), reading java.lang.RuntimeException)
Exception in thread "main" [17:35:45] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:698]: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
[17:35:45] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:698]:        at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392)
[17:35:45] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:698]:        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:250)
[17:35:45] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:698]:        at org.spongepowered.asm.service.modlauncher.MixinTransformationHandler.processClass(MixinTransformationHandler.java:131)
[17:35:45] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:698]:        at org.spongepowered.asm.launch.MixinLaunchPluginLegacy.processClass(MixinLaunchPluginLegacy.java:131)
[17:35:45] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:698]:        at cpw.mods.modlauncher.serviceapi.ILaunchPluginService.processClassWithFlags(ILaunchPluginService.java:154)
[17:35:45] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:698]:        at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:85)
[17:35:45] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:698]:        at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120)
[17:35:45] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:698]:        at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:265)
[17:35:45] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:698]:        at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:136)
[17:35:45] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:698]:        at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98)
[17:35:45] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:698]:        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
[17:35:45] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:698]:        at java.base/java.lang.Class.getDeclaredMethods0(Native Method)
[17:35:45] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:698]:        at java.base/java.lang.Class.privateGetDeclaredMethods(Class.java:3578)
[17:35:45] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:698]:        at java.base/java.lang.Class.getMethodsRecursive(Class.java:3719)
[17:35:45] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:698]:        at java.base/java.lang.Class.getMethod0(Class.java:3705)
[17:35:45] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:698]:        at java.base/java.lang.Class.getMethod(Class.java:2393)
[17:35:45] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:698]:        at net.minecraftforge.fml.loading.FMLServerLaunchProvider.lambda$launchService$0(FMLServerLaunchProvider.java:37)
[17:35:45] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:698]:        at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
[17:35:45] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:698]:        at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
[17:35:45] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:698]:        at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
[17:35:45] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:698]:        at cpw.mods.modlauncher.Launcher.run(Launcher.java:82)
[17:35:45] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:698]:        at cpw.mods.modlauncher.Launcher.main(Launcher.java:66)
[17:35:45] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:698]:        at net.minecraftforge.server.ServerMain$Runner.runLauncher(ServerMain.java:49)
[17:35:45] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:698]:        at net.minecraftforge.server.ServerMain$Runner.access$100(ServerMain.java:46)
[17:35:45] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:698]:        at net.minecraftforge.server.ServerMain.main(ServerMain.java:43)
[17:35:45] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:698]:        at io.izzel.arclight.common.ArclightMain.run(ArclightMain.java:50)
[17:35:45] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:698]:        at io.izzel.arclight.server.Main_Forge.main(Main_Forge.java:16)
[17:35:45] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:698]:        at io.izzel.arclight.server.Launcher.main(Launcher.java:16)
[17:35:45] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:660]: Caused by: org.spongepowered.asm.mixin.throwables.ClassMetadataNotFoundException: java.lang.RuntimeException
[17:35:45] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:660]:    at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.transformMethod(MixinPreProcessorStandard.java:754)
[17:35:45] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:660]:    at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.transform(MixinPreProcessorStandard.java:739)
[17:35:45] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:660]:    at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:310)
[17:35:45] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:660]:    at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.createContextFor(MixinPreProcessorStandard.java:280)
[17:35:45] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:660]:    at org.spongepowered.asm.mixin.transformer.MixinInfo.createContextFor(MixinInfo.java:1288)
[17:35:45] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:660]:    at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:292)
[17:35:45] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:660]:    at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:383)
[17:35:45] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:660]:    at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:365)
[17:35:45] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:660]:    at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
[17:35:45] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:660]:    ... 27 more

**Comment by Artcas2** [comment]
just download the last java jdk from https://www.oracle.com/java/technologies/downloads/#java22

**Comment by qyl27** [comment]
Outdated JDK version.
