### ISSUE TITLE
[forge 1.20.4] 遇到沼泽小屋附近服务端会崩溃

### ISSUE THREAD

**Issue by ljlVink** [IzzelAliz/Arclight#1439]
### 请确认您已完成以下几件事

- [X] 正在使用最新的 Arclight
- [X] 已为所有插件及模组安装依赖
- [X] 已为所有插件及模组更新至最新版
- [X] 不可在 Spigot 复现
- [x] 不可在 Forge 复现

### Arclight 版本

arclight-1.20.4-1.0.4-80ec5df

### Java 版本 | 操作系统

openjdk version "21.0.3" 2024-04-16 OpenJDK Runtime Environment (build 21.0.3+9-Ubuntu-1ubuntu1) OpenJDK 64-Bit Server VM (build 21.0.3+9-Ubuntu-1ubuntu1, mixed mode, sharing)

### 相关 Mod/插件 的名称及版本

```raw
• mods_folder weaponmaster_ydm-forge-1.20.4-4.2.3.jar : weaponmaster_ydm (4.2.3) - 1
• mods_folder supermartijn642configlib-1.1.8-forge-mc1.20.2.jar : supermartijn642configlib (1.1.8) - 1
• mods_folder CustomSkinLoader_ForgeActive-14.19.1.jar : customskinloader (14.19.1) - 1
• mods_folder jei-1.20.4-forge-17.3.1.3.jar : jei (17.3.1.3) - 1
• mods_folder buildersaddition2-1.20.4-2.0.3.jar : buildersaddition2 (2.0.3) - 1
• mods_folder AttributeFix-Forge-1.20.4-24.0.2.jar : attributefix (24.0.2) - 1
• mods_folder YungsBetterOceanMonuments-1.20.4-Forge-3.4.3.jar : betteroceanmonuments (1.20.4-Forge-3.4.3) - 1
• mods_folder mcw-windows-2.2.1-mc1.20.4forge.jar : mcwwindows (2.2.1) - 1
• mods_folder waystones-forge-1.20.4-16.0.5.jar : waystones (16.0.5) - 1
• mods_folder mcwfurnituresbop-1.20-1.1.jar : mcwfurnituresbop (1.20-1.1) - 1
• mods_folder mcw-paintings-1.0.5-1.20.4forge.jar : mcwpaintings (1.0.5) - 1
• mods_folder XaerosWorldMap_1.38.8_Forge_1.20.4.jar : xaeroworldmap (1.38.8) - 1
• mods_folder travelersbackpack-forge-1.20.4-9.4.3.jar : travelersbackpack (9.4.3) - 1
• mods_folder newshieldvariants-merged-1.20.4-1.2.0.jar : newshieldvariants (1.2.0) - 1
• mods_folder YungsApi-1.20.4-Forge-4.4.3.jar : yungsapi (1.20.4-Forge-4.4.3) - 1
• JarInJar mixinextras-forge-0.3.6.jar : mixinextras (0.3.6) - 1
• mods_folder MyServerIsCompatible-1.20-1.0.jar : myserveriscompatible (1.0) - 1
• mods_folder macawsbridgesbop-1.20.4-1.1.jar : macawsbridgesbop (1.20.4-1.1) - 1
• mods_folder GlitchCore-forge-1.20.4-1.0.0.59.jar : glitchcore (1.0.0.59) - 1
• mods_folder Bookshelf-Forge-1.20.4-23.1.9.jar : bookshelf (23.1.9) - 1
• mods_folder forge-medievalend-1.0.1.jar : medievalend (1.0.1) - 1
• mods_folder YungsBetterDesertTemples-1.20.4-Forge-3.4.4.jar : betterdeserttemples (1.20.4-Forge-3.4.4) - 1
• mods_folder mcw-doors-1.1.1forge-mc1.20.4.jar : mcwdoors (1.1.1) - 1
• mods_folder balm-forge-1.20.4-9.0.9.jar : balm (9.0.9) - 1
• mods_folder shulkerbox-forge-1.20.4-2.0.4.jar : shulkerbox (1.20.4-2.0.4) - 1
• mods_folder fusion-1.1.1-forge-mc1.20.2.jar : fusion (1.1.1) - 1
• mods_folder carryon-forge-1.20.4-2.1.3.13.jar : carryon (2.1.3) - 1
• mods_folder chat_heads-0.12.8-forge-1.20.3.jar : chat_heads (0.12.8) - 1
• mods_folder startinv-1.0.0-forge-1.20.4.jar : startinv (1.0.0) - 1
• mods_folder macawsroofsbop-1.20-1.0.jar : macawsroofsbop (1.20-1.0) - 1
• mods_folder cloth-config-13.0.121-forge.jar : cloth_config (13.0.121) - 1
• classpath forge-1.20.4-49.1.0-universal.jar : forge (49.1.0) - 1
• mods_folder despawningeggshatch-1.20.4-4.3.jar : despawningeggshatch (4.3) - 1
• mods_folder durabilitytooltip-1.1.5-forge-mc1.20.jar : durabilitytooltip (1.1.5) - 1
• mods_folder mcw-paths-1.0.5-1.20.4forge.jar : mcwpaths (1.0.5) - 1
• mods_folder AdvancementPlaques-1.20.4-forge-1.5.1.jar : advancementplaques (1.5.1) - 1
• mods_folder BetterPingDisplay-1.20.4-1.1.jar : betterpingdisplay (1.1) - 1
• minecraft forge-1.20.4-49.1.0-server.jar : minecraft (1.20.4) - 1
• mods_folder mcw-bridges-3.0.0-mc1.20.4forge.jar : mcwbridges (3.0.0) - 1
• mods_folder lapisreserve-1.0.8F.jar : lapisreserve (1.0.8F) - 1
• mods_folder libIPN-forge-1.20.2-4.0.2.jar : libipn (4.0.2) - 1
• mods_folder BetterCompatibilityChecker-forge-5.1.2+mc1.20.4.jar : bcc (5.1.2) - 1
• mods_folder TerraBlender-forge-1.20.4-3.3.0.12.jar : terrablender (3.3.0.12) - 1
• mods_folder BiomesOPlenty-forge-1.20.4-19.0.0.90.jar : biomesoplenty (19.0.0.90) - 1
• mods_folder NoChatReports-FORGE-1.20.4-v2.6.1.jar : nochatreports (1.20.4-v2.6.1) - 1
• mods_folder Jade-1.20.4-forge-13.2.1.jar : jade (13.2.1) - 1
• mods_folder inventorytotem-1.20.4-3.2.jar : inventorytotem (3.2) - 1
• mods_folder mcw-trapdoors-1.1.3-mc1.20.4forge.jar : mcwtrpdoors (1.1.3) - 1
• mods_folder mcw-fences-1.1.2-mc1.20.4forge.jar : mcwfences (1.1.2) - 1
• mods_folder ava-1.20.4-2.6.72.jar : ava (2.6.72) - 1
• mods_folder supermartijn642corelib-1.1.17-forge-mc1.20.4.jar : supermartijn642corelib (1.1.17) - 1
• mods_folder YungsBridges-1.20.4-Forge-4.4.2.jar : yungsbridges (1.20.4-Forge-4.4.2) - 1
• mods_folder ForgeConfigAPIPort-v20.4.3-1.20.4-Forge.jar : forgeconfigapiport (20.4.3) - 1
• mods_folder mcwfencesbop-1.20.4-1.2.jar : mcwfencesbop (1.20.4-1.2) - 1
• JarInJar kffmod-4.11.0.jar : kotlinforforge (4.11.0) - 1
• mods_folder BarteringStation-v20.4.1-1.20.4-Forge.jar : barteringstation (20.4.1) - 1
• mods_folder Iceberg-1.20.4-forge-1.1.20.jar : iceberg (1.1.20) - 1
• mods_folder Xaeros_Minimap_24.2.0_Forge_1.20.4.jar : xaerominimap (24.2.0) - 1
• mods_folder collective-1.20.4-7.64.jar : collective (7.64) - 1
• mods_folder Searchables-forge-1.20.4-1.0.6.jar : searchables (1.0.6) - 1
• mods_folder YungsExtras-1.20.4-Forge-4.4.2.jar : yungsextras (1.20.4-Forge-4.4.2) - 1
• mods_folder inventoryhud.forge.1.20.4-3.4.24.jar : inventoryhud (3.4.24) - 1
• mods_folder AmbientEnvironment-forge-1.20.4-14.0.0.4.jar : ambientenvironment (14.0.0.4) - 1
• mods_folder mcw-roofs-2.3.1-mc1.20.4forge.jar : mcwroofs (2.3.1) - 1
• mods_folder InventoryProfilesNext-forge-1.20.2-1.10.10.jar : inventoryprofilesnext (1.10.10) - 1
• mods_folder appleskin-forge-mc1.20.2-2.5.1.jar : appleskin (2.5.1+mc1.20.2) - 1
• mods_folder newslabvariants-merged-1.20.4-2.1.0.jar : newslabvariants (2.1.0) - 1
• mods_folder mcw-furniture-3.2.2-mc1.20.4forge.jar : mcwfurnitures (3.2.2) - 1
• arclight arclight-1.20.4-1.0.4-80ec5df.jar : arclight (1.0.4) - 1
• mods_folder PuzzlesLib-v20.4.52-1.20.4-Forge.jar : puzzleslib (20.4.52) - 1
• mods_folder monolib-forge-1.20.4-1.3.0.jar : monolib (1.3.0) - 1
• mods_folder BetterF3-9.0.2-Forge-1.20.4.jar : betterf3 (9.0.2) - 1
• mods_folder autochangefight-0.0.2.jar : autochangefight (0.0.2) - 1
• mods_folder YungsBetterMineshafts-1.20.4-Forge-4.4.2.jar : bettermineshafts (1.20.4-Forge-4.4.2) - 1
• mods_folder yeetusexperimentus-forge-84.0.3.jar : yeetusexperimentus (84.0.3) - 1
• mods_folder mcw-lights-1.1.0-mc1.20.4forge.jar : mcwlights (1.1.0) - 1
• mods_folder BetterAdvancements-Forge-1.20.4-0.4.2.8.jar : betteradvancements (0.4.2.8) - 1
```

### 错误描述

沼泽小屋附近区块时服务器崩溃，而且不生成沼泽地形

```java
Suspected Mod: 
	Arclight Mod (arclight), Version: 1.0.4
		Mixin class: io.izzel.arclight.common.mixin.core.world.gen.feature.structure.SwampHutPieceMixin
		Target: net.minecraft.world.level.levelgen.structure.structures.SwampHutPiece
		at TRANSFORMER/minecraft@1.20.4/net.minecraft.world.level.levelgen.structure.structures.SwampHutPiece.handler$bcj000$arclight$spawnReason1(SwampHutPieceMixin.java:524)
Stacktrace:
	at net.minecraft.world.level.levelgen.structure.structures.SwampHutPiece.handler$bcj000$arclight$spawnReason1(SwampHutPieceMixin.java:524) ~[forge-1.20.4-49.1.0-server.jar!/:?] {re:mixin,xf:fml:forge:forge_method_redirector,re:classloading,xf:fml:forge:forge_method_redirector,pl:mixin:APP:mixins.arclight.core.json:world.gen.feature.structure.SwampHutPieceMixin,pl:mixin:A}
	at net.minecraft.world.level.levelgen.structure.structures.SwampHutPiece.m_213694_(SwampHutPieceMixin.java:117) ~[forge-1.20.4-49.1.0-server.jar!/:?] {re:mixin,xf:fml:forge:forge_method_redirector,re:classloading,xf:fml:forge:forge_method_redirector,pl:mixin:APP:mixins.arclight.core.json:world.gen.feature.structure.SwampHutPieceMixin,pl:mixin:A}
	at net.minecraft.world.level.levelgen.structure.StructureStart.m_226850_(StructureStartMixin.java:571) ~[forge-1.20.4-49.1.0-server.jar!/:?] {re:mixin,re:computing_frames,re:classloading,pl:mixin:APP:mixins.arclight.core.json:world.level.levelgen.structure.StructureStartMixin,pl:mixin:A}
	at net.minecraft.world.level.chunk.ChunkGenerator.m_223080_(ChunkGeneratorMixin.java:320) ~[forge-1.20.4-49.1.0-server.jar!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:world.level.chunk.ChunkGeneratorMixin,pl:mixin:APP:betteroceanmonuments.mixins.json:DisableVanillaMonumentsMixin,pl:mixin:APP:betterdeserttemples.mixins.json:DisableVanillaPyramidsMixin,pl:mixin:APP:bettermineshafts.mixins.json:DisableVanillaMineshaftsMixin,pl:mixin:A}
	at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:422) ~[guava-32.1.2-jre.jar!/:?] {re:mixin}
	at net.minecraft.world.level.chunk.ChunkGenerator.m_213609_(ChunkGeneratorMixin.java:319) ~[forge-1.20.4-49.1.0-server.jar!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:world.level.chunk.ChunkGeneratorMixin,pl:mixin:APP:betteroceanmonuments.mixins.json:DisableVanillaMonumentsMixin,pl:mixin:APP:betterdeserttemples.mixins.json:DisableVanillaPyramidsMixin,pl:mixin:APP:bettermineshafts.mixins.json:DisableVanillaMineshaftsMixin,pl:mixin:A}
	at net.minecraft.world.level.chunk.ChunkStatus.m_279978_(ChunkStatus.java:108) ~[forge-1.20.4-49.1.0-server.jar!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.world.level.chunk.ChunkStatus$SimpleGenerationTask.m_214024_(ChunkStatus.java:309) ~[forge-1.20.4-49.1.0-server.jar!/:?] {re:classloading}
	at net.minecraft.world.level.chunk.ChunkStatus.m_280308_(ChunkStatus.java:252) ~[forge-1.20.4-49.1.0-server.jar!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.server.level.ChunkMap.lambda$scheduleChunkGeneration$27(ChunkMapMixin.java:637) ~[forge-1.20.4-49.1.0-server.jar!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.level.ChunkMapMixin,pl:mixin:APP:mixins.arclight.impl.optimization.json:network.ChunkMapMixin_Optimize,pl:mixin:APP:mixins.arclight.impl.optimization.json:trackingrange.ChunkManagerMixin_TrackingRange,pl:mixin:A,pl:arclight_implementer:async,pl:arclight_implementer:A}
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[datafixerupper-6.0.8.jar!/:?] {}
	at net.minecraft.server.level.ChunkMap.lambda$scheduleChunkGeneration$29(ChunkMapMixin.java:628) ~[forge-1.20.4-49.1.0-server.jar!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.level.ChunkMapMixin,pl:mixin:APP:mixins.arclight.impl.optimization.json:network.ChunkMapMixin_Optimize,pl:mixin:APP:mixins.arclight.impl.optimization.json:trackingrange.ChunkManagerMixin_TrackingRange,pl:mixin:A,pl:arclight_implementer:async,pl:arclight_implementer:A}
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?] {}
	at net.minecraft.server.level.ChunkTaskPriorityQueueSorter.m_143188_(ChunkTaskPriorityQueueSorter.java:62) ~[forge-1.20.4-49.1.0-server.jar!/:?] {re:classloading}
	at net.minecraft.util.thread.ProcessorMailbox.m_18759_(ProcessorMailbox.java:91) ~[forge-1.20.4-49.1.0-server.jar!/:?] {re:classloading}
	at net.minecraft.util.thread.ProcessorMailbox.m_18747_(ProcessorMailbox.java:146) ~[forge-1.20.4-49.1.0-server.jar!/:?] {re:classloading}

```

### 复现步骤

-

### 报错信息

https://pastebin.com/0Ktf2nw4

**Comment by ljlVink** [comment]
又试了一下，不加任何mod和插件也会导致在靠近沼泽女巫屋时崩溃

**Comment by qwrtbl** [comment]
I stumbled across the absolute same issue with the same "Suspected Mod" text on my 1.20.4 1.0.4-80ec5df arclight server and it worked out by simply removing a Carry On mod. Seems strange that in your case removing all the mods and plugins doen't help the problem, but I'd try running a new world with all your mods and plugins except the Carry On mod and see if the problem remains.

**Comment by ljlVink** [comment]
> I stumbled across the absolute same issue with the same "Suspected Mod" text on my 1.20.4 1.0.4-80ec5df arclight server and it worked out by simply removing a Carry On mod. Seems strange that in your case removing all the mods and plugins doen't help the problem, but I'd try running a new world with all your mods and plugins except the Carry On mod and see if the problem remains.

I think it's arclight's bug, because I used a forge server to load the same mods and maps and the swamphut loaded without crash.
