### ISSUE TITLE
ProtocolLib #490 Can't pass PlayerLoginEvent

### ISSUE THREAD

**Issue by Dum4G** [IzzelAliz/Arclight#144]
### I am running

* **Arclight** 1.16.5-1.0.12-SNAPSHOT-bcf3f33 

* **This is the latest development version** [Y]

<details>
  <summary>Click to expand</summary>

* **Java** 8 275 

* **Operating System** Debian 10

* **Plugins**  LuckPerms, SkinsRestorer, UberEnchant, Chunky, VillagerOptimiser, spark, Vault, ConsoleSpamFix, ProtocolLib, FastAsyncWorldEdit (WorldEdit), Essentials, EssentialsChat, TAB, IllegalStack, EssentialsSpawn, WorldGuard, BanItem, AuthMe, CoreProtect, LWC, FarmControl

* **Mods** 
• minecraft forge-1.16.5-36.0.1-server.jar : minecraft (1.16.5) - 1
• mods_folder mcw-bridges-1.0.5-mc1.16.5-4.jar : mcwbridges (1.0.5) - 1
• mods_folder decorative_blocks-1.16.4-1.7.2.jar : decorative_blocks (1.7.2) - 1
• mods_folder eternalwinter-1.3.jar : eternalwinter (1.3) - 1
• mods_folder buildersaddition-1.16.4-20210124a.jar : buildersaddition (1.16.4-20210124a) - 1
• mods_folder BiomesOPlenty-1.16.4-13.0.0.421-universal.jar : biomesoplenty (1.16.4-13.0.0.418) - 1
• mods_folder FastFurnace-1.16.4-4.4.0.jar : fastfurnace (4.4.0) - 1
• mods_folder CoronaMask-1.16.4-v1.jar : corona_mask (1.0.0) - 1
• mods_folder valhelsia_structures-16.0.5.jar : valhelsia_structures (16.0.5) - 1
• mods_folder mcw-roofs-2.0.1-mc1.16.5-4.jar : mcwroofs (2.0.1) - 1
• mods_folder dungeons_plus-1.16.4-1.1.2.jar : dungeons_plus (1.1.2) - 1
• mods_folder AI-Improvements-1.16.2-0.3.0.jar : aiimprovements (0.3.0) - 1
• mods_folder additional_lights-1.16.4-2.1.3.jar : additional_lights (2.1.3) - 1
• arclight arclight-forge-1.16-1.0.12-SNAPSHOT.jar : arclight (1.16.5-1.0.12-SNAPSHOT-bcf3f33) - 1
• mods_folder trashcans-1.0.6a-mc1.16.4.jar : trashcans (1.0.6a) - 1
• mods_folder FallingTree-Forge-1.16.5-2.10.0.jar : falling_tree (2.10.0) - 1
• maven_libs forge-1.16.5-36.0.1-universal.jar : forge (36.0.1) - 1
• mods_folder pamhc2foodcore-1.16.3-1.0.1.jar : pamhc2foodcore (version) - 1
• mods_folder structure_gel-1.16.4-1.7.5.jar : structure_gel (1.7.5) - 1
• mods_folder FastWorkbench-1.16.4-4.5.0.jar : fastbench (4.5.0) - 1
• mods_folder CookingForBlockheads_1.16.3-9.2.2.jar : cookingforblockheads (9.2.2) - 1
• mods_folder christmasfestivity-1.3.6-1.16.4.jar : christmasfestivity (1.3.6-1.16.4) - 1
• mods_folder Placebo-1.16.4-4.4.1.jar : placebo (4.4.1) - 1</details>

### Description

ProtocolLib #490 causes this error everytime someone joins the server. Something that didn't happen on 1.16.4

**Reproducible in Forge** [N]

**Reproducible in Spigot** [IDK]

### Logs

```
[20:11:50] [Server thread/ERROR] [Minecraft/]: Could not pass event PlayerLoginEvent to ProtocolLib v4.6.0-SNAPSHOT-b490
org.bukkit.event.EventException: null
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[arclight:arclight-1.16.5-1.0.12-SNAPSHOT-bcf3f33] {re:mixin,re:classloading}
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[arclight:arclight-1.16.5-1.0.12-SNAPSHOT-bcf3f33] {re:mixin,re:classloading}
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[arclight:arclight-1.16.5-1.0.12-SNAPSHOT-bcf3f33] {re:mixin,re:classloading}
        at net.minecraft.server.management.PlayerList.bridge$canPlayerLogin(PlayerListMixin.java:1121) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.management.PlayerListMixin,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.network.login.ServerLoginNetHandler.func_147326_c(ServerLoginNetHandlerMixin.java:604) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:network.login.ServerLoginNetHandlerMixin,pl:mixin:A}
        at net.minecraft.network.login.ServerLoginNetHandler.func_73660_a(ServerLoginNetHandlerMixin.java:65) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:network.login.ServerLoginNetHandlerMixin,pl:mixin:A}
        at net.minecraft.network.NetworkManager.func_74428_b(NetworkManagerMixin.java:222) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:network.NetworkManagerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:134) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServerMixin.java:864) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServerMixin.java:291) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.dedicated.DedicatedServerMixin,pl:mixin:A,re:mixin,pl:accesstransformer:B}
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServerMixin.java:786) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServerMixin.java:1895) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.lambda$startServer$0(MinecraftServerMixin.java:232) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_275] {}
Caused by: java.lang.NullPointerException
        at com.comphenix.protocol.injector.netty.ChannelInjector.findChannelHandler(ChannelInjector.java:929) ~[?:?] {re:classloading,re:classloading}
        at com.comphenix.protocol.injector.netty.InjectionFactory.fromPlayer(InjectionFactory.java:93) ~[?:?] {re:classloading,re:classloading}
        at com.comphenix.protocol.injector.netty.ProtocolInjector$4.updatePlayer(ProtocolInjector.java:364) ~[?:?] {re:classloading,re:classloading}
        at com.comphenix.protocol.injector.PacketFilterManager.onPlayerLogin(PacketFilterManager.java:920) ~[?:?] {re:classloading,re:classloading}
        at com.comphenix.protocol.injector.PacketFilterManager.access$200(PacketFilterManager.java:71) ~[?:?] {re:classloading,re:classloading}
        at com.comphenix.protocol.injector.PacketFilterManager$3.onPlayerLogin(PacketFilterManager.java:893) ~[?:?] {re:classloading,re:classloading}
        ... 14 more
```

[debug.log](https://github.com/IzzelAliz/Arclight/files/5895229/debug.log)
[latest.log](https://github.com/IzzelAliz/Arclight/files/5895233/latest.log)

**Comment by IzzelAliz** [comment]
Please test if it is fixed

**Comment by Dum4G** [comment]
Error is gone
