### ISSUE TITLE
Hello, support please Connecrot and Fargefired Fabric 1.21 and fix mod

### ISSUE THREAD

**Issue by OneWorldStudio** [IzzelAliz/Arclight#1447]
### I have confirmed that ...

- [X] Arclight is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [ ] unable to reproduce in Spigot
- [X] unable to reproduce in Forge

### Arclight version

arclight-neoforge-1.21-1.0.0-SNAPSHOT

### OS & Java versions

java version 21

### Plugins and Mods

```raw
Plugin: Nope
Mod: Sinytra Connector 1.21 [https://github.com/Sinytra/Connector/actions/runs/10289946872] and Forgified Fabric API 1.21 [https://modrinth.com/mod/forgified-fabric-api/version/0.101.2+2.0.9+1.21]
```

### Description

when the server starts, it immediately closes

Please also update NeoForge to 21.0.164

### Step to reproduce

1] I threw mods 2] started the server 3] crash

### Logs

not

**Comment by OneWorldStudio** [comment]
[08авг.2024 00:53:05.948] [modloading-worker-0/ERROR] [net.neoforged.fml.javafmlmod.FMLModContainer/LOADING]: Failed to create mod instance. ModID: forbidden_arcanus, class com.stal111.forbidden_arcanus.ForbiddenArcanus
java.lang.NoClassDefFoundError: net/neoforged/neoforge/event/entity/RegisterSpawnPlacementsEvent
	at java.base/java.lang.Class.getDeclaredMethods0(Native Method) ~[?:?] {re:mixin}
	at java.base/java.lang.Class.privateGetDeclaredMethods(Class.java:3578) ~[?:?] {re:mixin}
	at java.base/java.lang.Class.getDeclaredMethods(Class.java:2676) ~[?:?] {re:mixin}
	at MC-BOOTSTRAP/net.neoforged.bus/net.neoforged.bus.EventBus.register(EventBus.java:85) ~[bus-8.0.1.jar%23100!/:?] {}
	at TRANSFORMER/forbidden_arcanus@2.5.2-beta/com.stal111.forbidden_arcanus.ModEventHandler.registerModEvents(ModEventHandler.java:20) ~[forbidden_arcanus-2.5.2-beta.jar%23191!/:?] {re:classloading}
	at TRANSFORMER/valhelsia_core@1.1.3/net.valhelsia.valhelsia_core.core.neoforge.ValhelsiaForgeEventHandler.register(ValhelsiaForgeEventHandler.java:21) ~[valhelsia_core-neoforge-1.21-1.1.3.jar%23195!/:?] {re:classloading}
	at TRANSFORMER/valhelsia_core@1.1.3/net.valhelsia.valhelsia_core.core.ModDefinition.<init>(ModDefinition.java:28) ~[valhelsia_core-neoforge-1.21-1.1.3.jar%23195!/:?] {re:classloading}
	at TRANSFORMER/valhelsia_core@1.1.3/net.valhelsia.valhelsia_core.core.ModDefinition$Builder.create(ModDefinition.java:70) ~[valhelsia_core-neoforge-1.21-1.1.3.jar%23195!/:?] {re:classloading}
	at TRANSFORMER/forbidden_arcanus@2.5.2-beta/com.stal111.forbidden_arcanus.ForbiddenArcanus.<init>(ForbiddenArcanus.java:31) ~[forbidden_arcanus-2.5.2-beta.jar%23191!/:?] {re:classloading}
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62) ~[?:?] {}
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502) ~[?:?] {}
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486) ~[?:?] {}
	at MC-BOOTSTRAP/fml_loader@4.0.1/net.neoforged.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:115) ~[loader-4.0.1.jar%2393!/:4.0] {}
	at MC-BOOTSTRAP/fml_loader@4.0.1/net.neoforged.fml.ModLoader.lambda$constructMods$3(ModLoader.java:152) ~[loader-4.0.1.jar%2393!/:4.0] {}
	at MC-BOOTSTRAP/fml_loader@4.0.1/net.neoforged.fml.ModLoader.lambda$dispatchParallelTask$7(ModLoader.java:230) ~[loader-4.0.1.jar%2393!/:4.0] {}
	at java.base/java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:934) [?:?] {}
	at java.base/java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:911) [?:?] {}
	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:483) [?:?] {}
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387) [?:?] {}
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312) [?:?] {}
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843) [?:?] {}
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808) [?:?] {}
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188) [?:?] {}
Caused by: java.lang.ClassNotFoundException: net.neoforged.neoforge.event.entity.RegisterSpawnPlacementsEvent
	at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:220) ~[securejarhandler-3.0.8.jar:?] {}
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?] {}
	... 23 more
[08авг.2024 00:53:05.953] [main/FATAL] [net.neoforged.fml.ModLoader/LOADING]: Failed to wait for future Mod Construction, 1 errors found
[08авг.2024 00:53:06.029] [main/FATAL] [net.neoforged.neoforge.common.NeoForgeMod/]: Preparing crash report with UUID 2182e1c5-1e54-438f-a64d-5cfc72e52b01
[08авг.2024 00:53:06.029] [main/FATAL] [net.neoforged.neoforge.server.loading.ServerModLoader/]: Crash report saved to .\crash-reports\crash-2024-08-08_00.53.06-fml.txt
[08авг.2024 00:53:06.030] [main/FATAL] [net.neoforged.neoforge.common.NeoForgeMod/]: Preparing crash report with UUID 53d5ca24-7c0a-4297-aeaf-7c0173b02992
[08авг.2024 00:53:06.034] [main/ERROR] [net.minecraft.server.Main/FATAL]: Failed to start the minecraft server
net.neoforged.fml.ModLoadingException: Loading errors encountered:
	- Forbidden Arcanus (forbidden_arcanus) has failed to load correctly
	  java.lang.NoClassDefFoundError: net/neoforged/neoforge/event/entity/RegisterSpawnPlacementsEvent

	at MC-BOOTSTRAP/fml_loader@4.0.1/net.neoforged.fml.ModLoader.waitForFuture(ModLoader.java:280) ~[loader-4.0.1.jar%2393!/:4.0] {}
	at MC-BOOTSTRAP/fml_loader@4.0.1/net.neoforged.fml.ModLoader.dispatchParallelTask(ModLoader.java:243) ~[loader-4.0.1.jar%2393!/:4.0] {}
	at MC-BOOTSTRAP/fml_loader@4.0.1/net.neoforged.fml.ModLoader.constructMods(ModLoader.java:151) ~[loader-4.0.1.jar%2393!/:4.0] {}
	at MC-BOOTSTRAP/fml_loader@4.0.1/net.neoforged.fml.ModLoader.gatherAndInitializeMods(ModLoader.java:141) ~[loader-4.0.1.jar%2393!/:4.0] {}
	at TRANSFORMER/neoforge@21.0.4-beta/net.neoforged.neoforge.internal.CommonModLoader.begin(CommonModLoader.java:47) ~[neoforge-21.0.4-beta-universal.jar%23188!/:?] {re:classloading}
	at TRANSFORMER/neoforge@21.0.4-beta/net.neoforged.neoforge.server.loading.ServerModLoader.load(ServerModLoader.java:32) ~[neoforge-21.0.4-beta-universal.jar%23188!/:?] {re:classloading}
	at TRANSFORMER/minecraft@1.21/net.minecraft.server.Main.main(Main.java:124) ~[server-1.21-20240613.152323-srg.jar%23187!/:?] {re:classloading,pl:accesstransformer:B}
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?] {}
	at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[?:?] {}
	at MC-BOOTSTRAP/fml_loader@4.0.1/net.neoforged.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:136) ~[loader-4.0.1.jar%2393!/:4.0] {}
	at MC-BOOTSTRAP/fml_loader@4.0.1/net.neoforged.fml.loading.targets.CommonLaunchHandler.serverService(CommonLaunchHandler.java:128) ~[loader-4.0.1.jar%2393!/:4.0] {}
	at MC-BOOTSTRAP/fml_loader@4.0.1/net.neoforged.fml.loading.targets.CommonServerLaunchHandler.runService(CommonServerLaunchHandler.java:32) ~[loader-4.0.1.jar%2393!/:4.0] {}
	at MC-BOOTSTRAP/fml_loader@4.0.1/net.neoforged.fml.loading.targets.CommonLaunchHandler.lambda$launchService$4(CommonLaunchHandler.java:118) ~[loader-4.0.1.jar%2393!/:4.0] {}
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.2/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-11.0.2.jar%2395!/:?] {}
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.2/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-11.0.2.jar%2395!/:?] {}
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.2/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-11.0.2.jar%2395!/:?] {}
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.2/cpw.mods.modlauncher.Launcher.run(Launcher.java:103) [modlauncher-11.0.2.jar%2395!/:?] {}
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.2/cpw.mods.modlauncher.Launcher.main(Launcher.java:74) [modlauncher-11.0.2.jar%2395!/:?] {}
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.2/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-11.0.2.jar%2395!/:?] {}
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.2/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-11.0.2.jar%2395!/:?] {}
	at MC-BOOTSTRAP/arclight.boot/io.izzel.arclight.boot.neoforge.application.ApplicationBootstrap.accept(ApplicationBootstrap.java:47) [server.jar%2391!/:arclight-1.21-1.0.0-SNAPSHOT-c47e085] {}
	at MC-BOOTSTRAP/arclight.boot/io.izzel.arclight.boot.neoforge.application.ApplicationBootstrap.accept(ApplicationBootstrap.java:14) [server.jar%2391!/:arclight-1.21-1.0.0-SNAPSHOT-c47e085] {}
	at cpw.mods.bootstraplauncher@2.0.2/cpw.mods.bootstraplauncher.BootstrapLauncher.run(BootstrapLauncher.java:210) [bootstraplauncher-2.0.2.jar:?] {}
	at cpw.mods.bootstraplauncher@2.0.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:69) [bootstraplauncher-2.0.2.jar:?] {}
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?] {}
	at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[?:?] {}
	at io.izzel.arclight.boot.neoforge.application.Main_Neoforge.main(Main_Neoforge.java:23) [server.jar:arclight-1.21-1.0.0-SNAPSHOT-c47e085] {}
	at io.izzel.arclight.server.Launcher.main(Launcher.java:39) [server.jar:arclight-1.21-1.0.0-SNAPSHOT-c47e085] {}

**Comment by OneWorldStudio** [comment]
[08авг.2024 00:52:05.741] [main/INFO] [cpw.mods.modlauncher.Launcher/MODLAUNCHER]: ModLauncher running: args [--launchTarget, arclightserver, --fml.neoForgeVersion, 21.0.4-beta, --fml.fmlVersion, 4.0.1, --fml.mcVersion, 1.21, --fml.neoFormVersion, 20240613.152323, --nogui]
[08авг.2024 00:52:05.741] [main/INFO] [cpw.mods.modlauncher.Launcher/MODLAUNCHER]: JVM identified as Eclipse Adoptium OpenJDK 64-Bit Server VM 21.0.3+9-LTS
[08авг.2024 00:52:05.742] [main/INFO] [cpw.mods.modlauncher.Launcher/MODLAUNCHER]: ModLauncher 11.0.2+main.4612c65f starting: java version 21.0.3 by Eclipse Adoptium; OS Windows 10 arch amd64 version 10.0
[08авг.2024 00:52:05.825] [main/INFO] [net.neoforged.fml.loading.ImmediateWindowHandler/]: ImmediateWindowProvider not loading because launch target is arclightserver
[08авг.2024 00:52:05.874] [main/INFO] [mixin/]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=union:/C:/Users/TheDu/OneDrive/Рабочий%20стол/NeoWorld%20MMORPG%20Server/libraries/net/fabricmc/sponge-mixin/0.13.4+mixin.0.8.5/sponge-mixin-0.13.4+mixin.0.8.5.jar%23109!/ Service=ModLauncher Env=SERVER
[08авг.2024 00:52:06.064] [main/INFO] [net.neoforged.fml.loading.moddiscovery.locators.JarInJarDependencyLocator/]: Found 1 dependencies adding them to mods collection
[08авг.2024 00:52:06.184] [main/INFO] [net.neoforged.fml.loading.FMLServiceProvider/CORE]: Loading coremod script-engine for [neoforge]
[08авг.2024 00:52:06.719] [main/INFO] [mixin/]: Compatibility level set to JAVA_17
[08авг.2024 00:52:06.735] [main/INFO] [mixin/]: Compatibility level set to JAVA_21
[08авг.2024 00:52:06.801] [main/INFO] [mixin/]: Successfully loaded Mixin Connector [io.izzel.arclight.common.mod.ArclightConnector]
[08авг.2024 00:52:06.819] [main/INFO] [Arclight/]: Основной миксин Arclight добавлен.
[08авг.2024 00:52:06.827] [main/INFO] [Arclight/]: Оптимизирующий миксин Arclight добавлен.
[08авг.2024 00:52:06.831] [main/INFO] [cpw.mods.modlauncher.LaunchServiceHandler/MODLAUNCHER]: Launching target 'arclightserver' with arguments [--nogui]
[08авг.2024 00:52:06.836] [main/WARN] [mixin/]: Reference map 'terrablender.refmap.json' for terrablender.mixins.json could not be read. If this is a development environment you can ignore this message
[08авг.2024 00:52:06.837] [main/WARN] [mixin/]: Reference map 'terrablender.refmap.json' for terrablender_neoforge.mixins.json could not be read. If this is a development environment you can ignore this message
[08авг.2024 00:52:06.837] [main/WARN] [mixin/]: Reference map 'glitchcore.refmap.json' for glitchcore.mixins.json could not be read. If this is a development environment you can ignore this message
[08авг.2024 00:52:06.837] [main/WARN] [mixin/]: Reference map 'glitchcore.refmap.json' for glitchcore.neoforge.mixins.json could not be read. If this is a development environment you can ignore this message
[08авг.2024 00:52:06.838] [main/WARN] [mixin/]: Reference map 'regions_unexplored.refmap.json' for regions_unexplored.mixins.json could not be read. If this is a development environment you can ignore this message
[08авг.2024 00:52:06.838] [main/WARN] [mixin/]: Reference map 'regions_unexplored.refmap.json' for regions_unexplored.neoforge.mixins.json could not be read. If this is a development environment you can ignore this message
[08авг.2024 00:52:06.839] [main/WARN] [mixin/]: Reference map 'biomesoplenty.refmap.json' for biomesoplenty.mixins.json could not be read. If this is a development environment you can ignore this message
[08авг.2024 00:52:06.840] [main/WARN] [mixin/]: Reference map 'biomesoplenty.refmap.json' for biomesoplenty.neoforge.mixins.json could not be read. If this is a development environment you can ignore this message
[08авг.2024 00:52:06.840] [main/WARN] [mixin/]: Reference map 'geckolib.refmap.json' for geckolib.mixins.json could not be read. If this is a development environment you can ignore this message
[08авг.2024 00:52:06.840] [main/WARN] [mixin/]: Reference map 'forbidden_arcanus.refmap.json' for forbidden_arcanus.mixins.json could not be read. If this is a development environment you can ignore this message
[08авг.2024 00:52:08.262] [main/INFO] [MixinExtras|Service/]: Initializing MixinExtras via com.llamalad7.mixinextras.service.MixinExtrasServiceImpl(version=0.3.5).
[08авг.2024 00:52:09.843] [main/FATAL] [mixin/]: Mixin apply for mod regions_unexplored failed regions_unexplored.neoforge.mixins.json:NeoCropPlacerMixin from mod regions_unexplored -> net.minecraft.world.level.block.CropBlock: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException Invalid descriptor on regions_unexplored.neoforge.mixins.json:NeoCropPlacerMixin from mod regions_unexplored->@Inject::regions_unexplored$getGrowthSpeed(Lnet/minecraft/world/level/block/state/BlockState;Lnet/minecraft/world/level/BlockGetter;Lnet/minecraft/core/BlockPos;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;)V! Expected (Lnet/minecraft/world/level/block/Block;Lnet/minecraft/world/level/BlockGetter;Lnet/minecraft/core/BlockPos;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;)V but found (Lnet/minecraft/world/level/block/state/BlockState;Lnet/minecraft/world/level/BlockGetter;Lnet/minecraft/core/BlockPos;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;)V [INJECT Applicator Phase -> regions_unexplored.neoforge.mixins.json:NeoCropPlacerMixin from mod regions_unexplored -> Apply Injections ->  -> Inject -> regions_unexplored.neoforge.mixins.json:NeoCropPlacerMixin from mod regions_unexplored->@Inject::regions_unexplored$getGrowthSpeed(Lnet/minecraft/world/level/block/state/BlockState;Lnet/minecraft/world/level/BlockGetter;Lnet/minecraft/core/BlockPos;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;)V]
org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: Invalid descriptor on regions_unexplored.neoforge.mixins.json:NeoCropPlacerMixin from mod regions_unexplored->@Inject::regions_unexplored$getGrowthSpeed(Lnet/minecraft/world/level/block/state/BlockState;Lnet/minecraft/world/level/BlockGetter;Lnet/minecraft/core/BlockPos;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;)V! Expected (Lnet/minecraft/world/level/block/Block;Lnet/minecraft/world/level/BlockGetter;Lnet/minecraft/core/BlockPos;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;)V but found (Lnet/minecraft/world/level/block/state/BlockState;Lnet/minecraft/world/level/BlockGetter;Lnet/minecraft/core/BlockPos;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;)V [INJECT Applicator Phase -> regions_unexplored.neoforge.mixins.json:NeoCropPlacerMixin from mod regions_unexplored -> Apply Injections ->  -> Inject -> regions_unexplored.neoforge.mixins.json:NeoCropPlacerMixin from mod regions_unexplored->@Inject::regions_unexplored$getGrowthSpeed(Lnet/minecraft/world/level/block/state/BlockState;Lnet/minecraft/world/level/BlockGetter;Lnet/minecraft/core/BlockPos;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;)V]
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.injection.callback.CallbackInjector.inject(CallbackInjector.java:564) ~[sponge-mixin-0.13.4+mixin.0.8.5.jar%23109!/:0.13.4+mixin.0.8.5] {}
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.injection.callback.CallbackInjector.inject(CallbackInjector.java:494) ~[sponge-mixin-0.13.4+mixin.0.8.5.jar%23109!/:0.13.4+mixin.0.8.5] {}
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.injection.code.Injector.inject(Injector.java:277) ~[sponge-mixin-0.13.4+mixin.0.8.5.jar%23109!/:0.13.4+mixin.0.8.5] {}
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.injection.struct.InjectionInfo.inject(InjectionInfo.java:445) ~[sponge-mixin-0.13.4+mixin.0.8.5.jar%23109!/:0.13.4+mixin.0.8.5] {}
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1377) ~[sponge-mixin-0.13.4+mixin.0.8.5.jar%23109!/:0.13.4+mixin.0.8.5] {}
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1062) ~[sponge-mixin-0.13.4+mixin.0.8.5.jar%23109!/:0.13.4+mixin.0.8.5] {}
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:402) ~[sponge-mixin-0.13.4+mixin.0.8.5.jar%23109!/:0.13.4+mixin.0.8.5] {}
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:327) ~[sponge-mixin-0.13.4+mixin.0.8.5.jar%23109!/:0.13.4+mixin.0.8.5] {}
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:422) ~[sponge-mixin-0.13.4+mixin.0.8.5.jar%23109!/:0.13.4+mixin.0.8.5] {}
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[sponge-mixin-0.13.4+mixin.0.8.5.jar%23109!/:0.13.4+mixin.0.8.5] {}
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.13.4+mixin.0.8.5.jar%23109!/:0.13.4+mixin.0.8.5] {}
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:250) ~[sponge-mixin-0.13.4+mixin.0.8.5.jar%23109!/:0.13.4+mixin.0.8.5] {}
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.service.modlauncher.MixinTransformationHandler.processClass(MixinTransformationHandler.java:131) ~[sponge-mixin-0.13.4+mixin.0.8.5.jar%23109!/:0.13.4+mixin.0.8.5] {}
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.launch.MixinLaunchPluginLegacy.processClass(MixinLaunchPluginLegacy.java:131) ~[sponge-mixin-0.13.4+mixin.0.8.5.jar%23109!/:0.13.4+mixin.0.8.5] {}
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.2/cpw.mods.modlauncher.serviceapi.ILaunchPluginService.processClassWithFlags(ILaunchPluginService.java:156) ~[modlauncher-11.0.2.jar%2395!/:11.0.2+main.4612c65f] {}
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.2/cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:88) ~[modlauncher-11.0.2.jar%2395!/:?] {}
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.2/cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-11.0.2.jar%2395!/:?] {}
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.2/cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:50) ~[modlauncher-11.0.2.jar%2395!/:?] {}
	at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:190) ~[securejarhandler-3.0.8.jar:?] {}
	at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.lambda$findClass$20(ModuleClassLoader.java:298) ~[securejarhandler-3.0.8.jar:?] {}
	at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:311) ~[securejarhandler-3.0.8.jar:?] {}
	at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:298) ~[securejarhandler-3.0.8.jar:?] {}
	at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:214) ~[securejarhandler-3.0.8.jar:?] {}
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?] {}
	at TRANSFORMER/minecraft@1.21/net.minecraft.world.level.block.FireBlock.bootStrap(FireBlockMixin_NeoForge.java:342) ~[server-1.21-20240613.152323-srg.jar%23188!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:world.level.block.FireBlockMixin from mod (unknown),pl:mixin:APP:mixins.arclight.neoforge.json:core.world.level.block.FireBlockMixin_NeoForge from mod (unknown),pl:mixin:APP:forbidden_arcanus.mixins.json:AccessorFireBlock from mod forbidden_arcanus,pl:mixin:A}
	at TRANSFORMER/minecraft@1.21/net.minecraft.server.Bootstrap.bootStrap(BootstrapMixin.java:45) ~[server-1.21-20240613.152323-srg.jar%23188!/:?] {re:mixin,re:classloading,pl:mixin:APP:mixins.arclight.core.json:server.BootstrapMixin from mod (unknown),pl:mixin:A}
	at TRANSFORMER/minecraft@1.21/net.minecraft.server.Main.main(Main.java:120) ~[server-1.21-20240613.152323-srg.jar%23188!/:?] {re:classloading,pl:accesstransformer:B}
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?] {}
	at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[?:?] {}
	at MC-BOOTSTRAP/fml_loader@4.0.1/net.neoforged.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:136) ~[loader-4.0.1.jar%2393!/:4.0] {}
	at MC-BOOTSTRAP/fml_loader@4.0.1/net.neoforged.fml.loading.targets.CommonLaunchHandler.serverService(CommonLaunchHandler.java:128) ~[loader-4.0.1.jar%2393!/:4.0] {}
	at MC-BOOTSTRAP/fml_loader@4.0.1/net.neoforged.fml.loading.targets.CommonServerLaunchHandler.runService(CommonServerLaunchHandler.java:32) ~[loader-4.0.1.jar%2393!/:4.0] {}
	at MC-BOOTSTRAP/fml_loader@4.0.1/net.neoforged.fml.loading.targets.CommonLaunchHandler.lambda$launchService$4(CommonLaunchHandler.java:118) ~[loader-4.0.1.jar%2393!/:4.0] {}
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.2/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-11.0.2.jar%2395!/:?] {}
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.2/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-11.0.2.jar%2395!/:?] {}
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.2/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-11.0.2.jar%2395!/:?] {}
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.2/cpw.mods.modlauncher.Launcher.run(Launcher.java:103) [modlauncher-11.0.2.jar%2395!/:?] {}
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.2/cpw.mods.modlauncher.Launcher.main(Launcher.java:74) [modlauncher-11.0.2.jar%2395!/:?] {}
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.2/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-11.0.2.jar%2395!/:?] {}
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.2/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-11.0.2.jar%2395!/:?] {}
	at MC-BOOTSTRAP/arclight.boot/io.izzel.arclight.boot.neoforge.application.ApplicationBootstrap.accept(ApplicationBootstrap.java:47) [server.jar%2391!/:arclight-1.21-1.0.0-SNAPSHOT-c47e085] {}
	at MC-BOOTSTRAP/arclight.boot/io.izzel.arclight.boot.neoforge.application.ApplicationBootstrap.accept(ApplicationBootstrap.java:14) [server.jar%2391!/:arclight-1.21-1.0.0-SNAPSHOT-c47e085] {}
	at cpw.mods.bootstraplauncher@2.0.2/cpw.mods.bootstraplauncher.BootstrapLauncher.run(BootstrapLauncher.java:210) [bootstraplauncher-2.0.2.jar:?] {}
	at cpw.mods.bootstraplauncher@2.0.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:69) [bootstraplauncher-2.0.2.jar:?] {}
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?] {}
	at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[?:?] {}
	at io.izzel.arclight.boot.neoforge.application.Main_Neoforge.main(Main_Neoforge.java:23) [server.jar:arclight-1.21-1.0.0-SNAPSHOT-c47e085] {}
	at io.izzel.arclight.server.Launcher.main(Launcher.java:39) [server.jar:arclight-1.21-1.0.0-SNAPSHOT-c47e085] {}

**Comment by qyl27** [comment]
The priority of supporting Sinytra Connector won't be too high, we have Fabric version.

**Comment by InitAuther97** [comment]
Should be fixed now.
