### ISSUE TITLE
1.21版本与多世界插件几乎不兼容

### ISSUE THREAD

**Issue by qingchenyouforcc** [IzzelAliz/Arclight#1452]
### 请确认您已完成以下几件事

- [X] 正在使用最新的 Arclight
- [X] 已为所有插件及模组安装依赖
- [X] 已为所有插件及模组更新至最新版
- [X] 不可在 Spigot 复现
- [X] 不可在 Forge 复现

### Arclight 版本

arclight-1.21-1.0.0-SNAPSHOT-c47e085.jar

### Java 版本 | 操作系统

openjdk 21.0.1

### 相关 Mod/插件 的名称及版本

```raw
Multiverse-Core-4.3.1.jar
```

### 错误描述

进入多世界插件创建的世界后，玩家无法发送信息和输入指令，提示：聊天在客户端选项中被禁用。无法与世界交互，当使用/kill杀死玩家时，玩家无法重生，服务端开始报错:
[09:19:49 WARN] [Minecraft]: Unexpected exception while parsing console command "kill CN_qingchen"
org.bukkit.command.CommandException: Unhandled exception executing 'kill CN_qingchen' in org.bukkit.craftbukkit.v1_21_R1.command.VanillaCommandWrapper(kill)
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:157) ~[arclight-1.21-1.0.0-SNAPSHOT-c47e085.jar:?]
        at org.bukkit.craftbukkit.v1_21_R1.CraftServer.dispatchCommand(CraftServerMixin.java:913) ~[arclight-1.21-1.0.0-SNAPSHOT-c47e085.jar:?]
        at org.bukkit.craftbukkit.v1_21_R1.CraftServer.dispatchServerCommand(CraftServerMixin.java:898) ~[arclight-1.21-1.0.0-SNAPSHOT-c47e085.jar:?]
        at net.minecraft.class_3176.redirect$zem000$arclight$serverCommandEvent(DedicatedServerMixin_Vanilla.java:762) ~[server-intermediary.jar:?]
        at net.minecraft.class_3176.method_13941(DedicatedServerMixin_Vanilla.java:318) ~[server-intermediary.jar:?]
        at net.minecraft.class_3176.method_3813(DedicatedServerMixin_Vanilla.java:300) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_3748(MinecraftServerMixin.java:912) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServerMixin.java:697) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServerMixin.java:281) ~[server-intermediary.jar:?]
        at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
Caused by: java.lang.NoSuchMethodError: 'net.minecraft.class_1542 net.minecraft.class_3222.drop(net.minecraft.class_1799, boolean, boolean, boolean)'
        at org.bukkit.craftbukkit.v1_21_R1.event.CraftEventFactory.callPlayerDeathEvent(CraftEventFactoryMixin.java:941) ~[arclight-1.21-1.0.0-SNAPSHOT-c47e085.jar:?]
        at net.minecraft.class_3222.method_6078(ServerPlayerMixin_Vanilla.java:2477) ~[server-intermediary.jar:?]
        at net.minecraft.class_1309.method_5643(LivingEntityMixin_Vanilla.java:1252) ~[server-intermediary.jar:?]
        at net.minecraft.class_1657.method_5643(PlayerMixin_Vanilla.java:2609) ~[server-intermediary.jar:?]
        at net.minecraft.class_3222.method_5643(ServerPlayerMixin_Vanilla.java:811) ~[server-intermediary.jar:?]
        at net.minecraft.class_1309.method_5768(LivingEntityMixin_Vanilla.java:300) ~[server-intermediary.jar:?]
        at net.minecraft.class_3075.method_13430(class_3075.java:32) ~[server-intermediary.jar:?]
        at net.minecraft.class_3075.method_13431(class_3075.java:25) ~[server-intermediary.jar:?]
        at com.mojang.brigadier.context.ContextChain.runExecutable(ContextChain.java:73) ~[brigadier-1.2.9.jar:?]
        at net.minecraft.class_8865.method_54416(class_8865.java:29) ~[server-intermediary.jar:?]
        at net.minecraft.class_8865.execute(class_8865.java:13) ~[server-intermediary.jar:?]
        at net.minecraft.class_8856.method_54405(class_8856.java:8) ~[server-intermediary.jar:?]
        at net.minecraft.class_8847.method_54388(class_8847.java:8) ~[server-intermediary.jar:?]
        at net.minecraft.class_8854.method_54390(class_8854.java:107) ~[server-intermediary.jar:?]
        at net.minecraft.class_2170.method_54313(CommandsMixin.java:379) ~[server-intermediary.jar:?]
        at net.minecraft.class_2170.method_9249(CommandsMixin.java:309) ~[server-intermediary.jar:?]
        at net.minecraft.class_2170.method_44252(CommandsMixin.java:299) ~[server-intermediary.jar:?]
        at net.minecraft.class_2170.performPrefixedCommand(CommandsMixin.java:624) ~[server-intermediary.jar:?]
        at org.bukkit.craftbukkit.v1_21_R1.command.VanillaCommandWrapper.execute(VanillaCommandWrapper.java:43) ~[arclight-1.21-1.0.0-SNAPSHOT-c47e085.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:150) ~[arclight-1.21-1.0.0-SNAPSHOT-c47e085.jar:?]
        ... 9 more
当玩家退出服务器后无法再次进入，只有重启服务器才能解决该问题

### 复现步骤

1.安装Multiverse-Core插件
2.玩家进入服务器
3.输入/mv create 世界 世界类型 来创建世界
4.输入/mv tp 世界 进入创建的世界
复现玩家无法发送信息和输入指令，提示：聊天在客户端选项中被禁用。
5.在服务端输入/kill id 杀死玩家
复现服务器报错
6.玩家再次进入服务器，发现卡在正在连接中
复现玩家无法进入
7.重启服务器，玩家可以重新进入服务器

### 报错信息

https://netcut.cn/1i52ue6gs

**Comment by qyl27** [comment]
已经被 c47e085 修复了。

**Comment by qingchenyouforcc** [comment]
> 已经被 [c47e085](https://github.com/IzzelAliz/Arclight/commit/c47e085172036e12fea7abc51ea1274a86bbbf76) 修复了。

我反馈的就是c47e085啊

**Comment by qyl27** [comment]
> > 已经被 [c47e085](https://github.com/IzzelAliz/Arclight/commit/c47e085172036e12fea7abc51ea1274a86bbbf76) 修复了。
> 
> 我反馈的就是c47e085啊

啊，不好意思，我复制错了，是它的后一个commit 5bf8aaf 
~~（昨天回了俩issue都是 c47e085 修复的，所以不小心复制错了）~~
