### ISSUE TITLE
更新fabric loader 0.16

### ISSUE THREAD

**Issue by PTALTS-LK** [IzzelAliz/Arclight#1465]
### 请确认您已完成以下几件事

- [X] 正在使用最新的 Arclight
- [X] 已为所有插件及模组安装依赖
- [X] 已为所有插件及模组更新至最新版
- [X] 不可在 Spigot 复现
- [X] 不可在 Forge 复现

### Arclight 版本

1.21-1.0.0-SNAPSHOT

### Java 版本 | 操作系统

java version "21.0.2" 2024-01-16 LTS

### 相关 Mod/插件 的名称及版本

```raw
fabric:
 - Forge Config API Port 21.0.8
 - Puzzles Lib 21.0.22
```

### 错误描述

这些mod需要0.16版本fabric loader，而arc内置的fabric loader版本为0.15.11

### 报错信息

[12:48:13 ERROR] [FabricLoader]: Incompatible mods found!
net.fabricmc.loader.impl.FormattedException: Some of your mods are incompatible with the game or each other!
确定了一种可能的解决方法，这样做可能会解决你的问题：
         - 将 模组 'Fabric Loader' (fabricloader) 0.15.11 替换为 0.16.0 及以上版本。
更多信息：
         - 模组 'Forge Config API Port' (forgeconfigapiport) 21.0.8 需要 模组 'Fabric Loader' (fabricloader) 的 0.16.0 及以上版本，但已经安装了的版本 0.15.11 不对！
         - 模组 'Puzzles Lib' (puzzleslib) 21.0.22 需要 模组 'Fabric Loader' (fabricloader) 的 0.16.0 及以上版本，但已经安装了的版本 0.15.11 不对！
        at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51) ~[fabric-loader-0.15.11.jar:?]
        at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:195) ~[fabric-loader-0.15.11.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:146) ~[fabric-loader-0.15.11.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68) [fabric-loader-0.15.11.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.15.11.jar:?]
        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.15.11.jar:?]
        at io.izzel.arclight.boot.fabric.application.Main_Fabric.main(Main_Fabric.java:33) [arclight-fabric-1.21-1.0.0-SNAPSHOT.jar:arclight-1.21-1.0.0-SNAPSHOT-b3349e9]
        at io.izzel.arclight.server.Launcher.main(Launcher.java:39) [arclight-fabric-1.21-1.0.0-SNAPSHOT.jar:arclight-1.21-1.0.0-SNAPSHOT-b3349e9]

**Comment by qyl27** [comment]
已经在最新构建中完成。

**Comment by MooreBilibili** [comment]
我的做法就是把\libraries\net\fabricmc\fabric-loader\0.15.11里面的fabric-loader-0.15.11.jar换成最新的fabricloader,并重命名为fabric-loader-0.15.11.jar,然后就能用了
