### ISSUE TITLE
Player death error

### ISSUE THREAD

**Issue by FeikkiSteppe** [IzzelAliz/Arclight#1466]
### I have confirmed that ...

- [X] Arclight is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Forge

### Arclight version

arclight-1.21-1.0.0-SNAPSHOT-b3349e9 with Fabric Loader 0.15.11

### OS & Java versions

Os: no idea what os the server provider has, Java: Version 21

### Plugins and Mods

```raw
No plugins or mods
```

### Description

So when a player dies in any way it causes the player to have an error message and not being able to say anything in chat

### Step to reproduce

1. Join the game
2. Die

### Logs

[19:47:47 ERROR]: Failed to handle packet net.minecraft.class_2799@40c49438, suppressing error
java.lang.NullPointerException: Cannot invoke "org.bukkit.Location.getWorld()" because "location" is null
        at net.minecraft.class_3324.handler$zdc000$arclight$postRespawn(PlayerListMixin.java:1388) ~[server-intermediary.jar:?]
        at net.minecraft.class_3324.method_14556(PlayerListMixin.java:530) ~[server-intermediary.jar:?]
        at net.minecraft.class_3244.method_12068(ServerPlayNetHandlerMixin.java:1672) ~[server-intermediary.jar:?]
        at net.minecraft.class_2799.method_12120(class_2799.java:32) ~[server-intermediary.jar:?]
        at net.minecraft.class_2799.method_11054(class_2799.java:8) ~[server-intermediary.jar:?]
        at net.minecraft.class_2600.md6b7611$arclight$lambda$ensureRunningOnSameThread$0$0(PacketThreadUtilMixin.java:538) ~[server-intermediary.jar:?]
        at net.minecraft.class_3738.run(class_3738.java:18) ~[server-intermediary.jar:?]
        at net.minecraft.class_1255.method_18859(BlockableEventLoopMixin.java:162) ~[server-intermediary.jar:?]
        at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_24306(MinecraftServerMixin.java:864) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_18859(MinecraftServerMixin.java:173) ~[server-intermediary.jar:?]
        at net.minecraft.class_1255.method_16075(BlockableEventLoopMixin.java:136) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_20415(MinecraftServerMixin.java:846) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_16075(MinecraftServerMixin.java:840) ~[server-intermediary.jar:?]
        at net.minecraft.class_1255.method_18857(BlockableEventLoopMixin.java:145) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_18857(MinecraftServerMixin.java:810) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_16208(MinecraftServerMixin.java:815) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServerMixin.java:702) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServerMixin.java:281) ~[server-intermediary.jar:?]
        at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]

**Comment by REDKING-11** [comment]
ye thats a massive issue sometimes in my server too it happens some times too that you die in the loading screen that when you have join you are in death screen

**Comment by qyl27** [comment]
Outdated version.  
It was already fixed on Jul 2, 2024, by c47e085.  
The newest version of the active branch is always in GitHub Actions.
