### ISSUE TITLE
[MINOR] BlazeandCave's Advancements Pack Init errors

### ISSUE THREAD

**Issue by Dum4G** [IzzelAliz/Arclight#147]
### I am running

* **Arclight** 1.16.5-1.0.12-SNAPSHOT-1c0136c 

* **This is the latest development version** [Y]

<details>
  <summary>Click to expand</summary>

* **Java** 8 275 

* **Operating System** Debian 10

* **Plugins**  LuckPerms, SkinsRestorer, UberEnchant, Chunky, VillagerOptimiser, spark, Vault, ConsoleSpamFix, ProtocolLib, FastAsyncWorldEdit (WorldEdit), Essentials, EssentialsChat, TAB, IllegalStack, EssentialsSpawn, WorldGuard, BanItem, AuthMe, CoreProtect, LWC, FarmControl

* **Mods** 
• minecraft forge-1.16.5-36.0.1-server.jar : minecraft (1.16.5) - 1
• mods_folder mcw-bridges-1.0.5-mc1.16.5-4.jar : mcwbridges (1.0.5) - 1
• mods_folder decorative_blocks-1.16.4-1.7.2.jar : decorative_blocks (1.7.2) - 1
• mods_folder eternalwinter-1.3.jar : eternalwinter (1.3) - 1
• mods_folder buildersaddition-1.16.4-20210124a.jar : buildersaddition (1.16.4-20210124a) - 1
• mods_folder BiomesOPlenty-1.16.4-13.0.0.421-universal.jar : biomesoplenty (1.16.4-13.0.0.418) - 1
• mods_folder FastFurnace-1.16.4-4.4.0.jar : fastfurnace (4.4.0) - 1
• mods_folder CoronaMask-1.16.4-v1.jar : corona_mask (1.0.0) - 1
• mods_folder valhelsia_structures-16.0.5.jar : valhelsia_structures (16.0.5) - 1
• mods_folder mcw-roofs-2.0.1-mc1.16.5-4.jar : mcwroofs (2.0.1) - 1
• mods_folder dungeons_plus-1.16.4-1.1.2.jar : dungeons_plus (1.1.2) - 1
• mods_folder AI-Improvements-1.16.2-0.3.0.jar : aiimprovements (0.3.0) - 1
• mods_folder additional_lights-1.16.4-2.1.3.jar : additional_lights (2.1.3) - 1
• arclight arclight-forge-1.16-1.0.12-SNAPSHOT.jar : arclight (1.16.5-1.0.12-SNAPSHOT-bcf3f33) - 1
• mods_folder trashcans-1.0.6a-mc1.16.4.jar : trashcans (1.0.6a) - 1
• mods_folder FallingTree-Forge-1.16.5-2.10.0.jar : falling_tree (2.10.0) - 1
• maven_libs forge-1.16.5-36.0.1-universal.jar : forge (36.0.1) - 1
• mods_folder pamhc2foodcore-1.16.3-1.0.1.jar : pamhc2foodcore (version) - 1
• mods_folder structure_gel-1.16.4-1.7.5.jar : structure_gel (1.7.5) - 1
• mods_folder FastWorkbench-1.16.4-4.5.0.jar : fastbench (4.5.0) - 1
• mods_folder CookingForBlockheads_1.16.3-9.2.2.jar : cookingforblockheads (9.2.2) - 1
• mods_folder christmasfestivity-1.3.6-1.16.4.jar : christmasfestivity (1.3.6-1.16.4) - 1
• mods_folder Placebo-1.16.4-4.4.1.jar : placebo (4.4.1) - 1</details>

### Description

On every boot at least one of achievements from BACAP 1.11.1 kinda fails to load because of completion error. It's always some random achievement that works nonetheless. To reproduce just place datapack in a world/datapacks folder and start a server.

**Reproducible in Forge** [N]

**Reproducible in Spigot** [N]

### Logs

```
[13:14:10] [Worker-Main-6/ERROR] [minecraft/FunctionReloader]: Failed to load function bc_rewards:adventure/i_am_loot
java.util.concurrent.CompletionException: java.lang.NullPointerException
        at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273) ~[?:1.8.0_275] {}
        at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280) [?:1.8.0_275] {}
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1606) [?:1.8.0_275] {}
        at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1596) [?:1.8.0_275] {}
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) [?:1.8.0_275] {}
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) [?:1.8.0_275] {}
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692) [?:1.8.0_275] {}
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175) [?:1.8.0_275] {}
Caused by: java.lang.NullPointerException
        at org.bukkit.craftbukkit.v1_16_R3.command.VanillaCommandWrapper.getPermission(VanillaCommandWrapper.java:90) ~[arclight:arclight-1.16.5-1.0.12-SNAPSHOT-1c0136c] {re:mixin,re:classloading}
        at net.minecraft.command.CommandSource.handler$zep000$arclight$checkPermission(CommandSourceMixin.java:534) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:command.CommandSourceMixin,pl:mixin:A}
        at net.minecraft.command.CommandSource.func_197034_c(CommandSourceMixin.java) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:command.CommandSourceMixin,pl:mixin:A}
        at net.minecraft.command.impl.ExecuteCommand.func_198387_a(SourceFile:123) ~[?:?] {re:classloading}
        at com.mojang.brigadier.tree.CommandNode.handler$zen000$on(CommandNodeMixin.java:545) ~[?:?] {re:mixin,re:classloading,pl:mixin:APP:mixins.arclight.core.json:command.CommandNodeMixin,pl:mixin:A}
        at com.mojang.brigadier.tree.CommandNode.canUse(CommandNodeMixin.java) ~[?:?] {re:mixin,re:classloading,pl:mixin:APP:mixins.arclight.core.json:command.CommandNodeMixin,pl:mixin:A}
        at com.mojang.brigadier.CommandDispatcher.parseNodes(CommandDispatcher.java:357) ~[?:?] {re:classloading}
        at com.mojang.brigadier.CommandDispatcher.parse(CommandDispatcher.java:347) ~[?:?] {re:classloading}
        at net.minecraft.command.FunctionObject.func_237140_a_(SourceFile:55) ~[?:?] {re:classloading}
        at net.minecraft.resources.FunctionReloader.func_240935_a_(SourceFile:86) ~[?:?] {re:classloading}
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1604) ~[?:1.8.0_275] {}
        ... 5 more
```

[debug.log](https://github.com/IzzelAliz/Arclight/files/5899531/debug.log)
[latest.log](https://github.com/IzzelAliz/Arclight/files/5899532/latest.log)

**Comment by IzzelAliz** [comment]
Please test if it is fixed in latest build.
