### ISSUE TITLE
It doesn't open because of an error.

### ISSUE THREAD

**Issue by pil0lo** [IzzelAliz/Arclight#1483]
### I have confirmed that ...

- [X] Arclight is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Forge

### Arclight version

arclight-fabric-1.21-1.0.0-SNAPSHOT.jar

### OS & Java versions

java version "22.0.1" 2024-04-16 Java(TM) SE Runtime Environment (build 22.0.1+8-16) Java HotSpot(TM) 64-Bit Server VM (build 22.0.1+8-16, mixed mode, sharing) 

### Plugins and Mods

```raw
- animal_feeding_trough 1.1.1+1.21
	- ante 1.2
	- anvilrestoration 2.2
	- architectury 13.0.6
	- artifacts 12.0.6
	   |-- cardinal-components-base 6.1.0
	   |-- cardinal-components-entity 6.1.0
	   |-- com_electronwill_night-config_core 3.8.0
	   |-- com_electronwill_night-config_toml 3.8.0
	   \-- expandability 12.0.0
	- autofish 1.0.2
	- automaticdoors 4.7
	- azurepaxels 1.0.3
	- balm-fabric 21.0.19
	   \-- kuma_api 21.0.5-SNAPSHOT
	- better_craftables 1.6.0
	- blastingsand 1.21-11-fabric
	- charmofundying 9.0.0+1.21
	   \-- spectrelib 0.17.1+1.21
	        |-- com_electronwill_night-config_core 3.8.0
	        \-- com_electronwill_night-config_toml 3.8.0
	- chunky 1.4.14
	- cicada 0.8.3+1.21-and-above
	- cloth-config 15.0.130
	   \-- cloth-basic-math 0.6.1
	- collective 7.84
	- commonnetworking 1.0.16-1.21
	- connectiblechains 2.4.2+1.21.1
	- craftingslots 21.0.2
	- cristellib 1.2.8
	   \-- blue_endless_jankson 1.2.3
	- cryingportals 2.7
	- ctlib 0.1.13
	- customportals 3.6.0
	   |-- cardinal-components-base 6.1.0
	   \-- cardinal-components-world 6.1.0
	- darktimer 1.2.1
	- disenchanter 0.1.10+1.21
	- doors-closed 1.0.0+1.19.4
	- dragonloot 1.1.5
	- elytraslot 9.0.0+1.21
	   \-- mixinsquared 0.1.2-beta.6
	- enchantingtree 1.0.0
	- entityculling 1.6.6
	- experiencebottler 1.21+build.2
	- expore 1.21-0.1
	- fabric-api 0.102.0+1.21
	   |-- fabric-api-base 0.4.42+6573ed8cd1
	   |-- fabric-api-lookup-api-v1 1.6.68+b5597344d1
	   |-- fabric-biome-api-v1 13.0.29+5bd9f1bcd1
	   |-- fabric-block-api-v1 1.0.22+0af3f5a7d1
	   |-- fabric-block-view-api-v2 1.0.10+6573ed8cd1
	   |-- fabric-blockrenderlayer-v1 1.1.52+0af3f5a7d1
	   |-- fabric-client-tags-api-v1 1.1.15+6573ed8cd1
	   |-- fabric-command-api-v1 1.2.49+f71b366fd1
	   |-- fabric-command-api-v2 2.2.28+6ced4dd9d1
	   |-- fabric-commands-v0 0.2.66+df3654b3d1
	   |-- fabric-content-registries-v0 8.0.16+b5597344d1
	   |-- fabric-convention-tags-v1 2.0.19+7f945d5bd1
	   |-- fabric-convention-tags-v2 2.5.0+c5e2b5c6d1
	   |-- fabric-crash-report-info-v1 0.2.29+0af3f5a7d1
	   |-- fabric-data-attachment-api-v1 1.1.27+6a6dfa19d1
	   |-- fabric-data-generation-api-v1 20.2.16+16c4ae25d1
	   |-- fabric-dimensions-v1 4.0.0+6fc22b99d1
	   |-- fabric-entity-events-v1 1.6.12+6fc22b99d1
	   |-- fabric-events-interaction-v0 0.7.12+ba9dae06d1
	   |-- fabric-game-rule-api-v1 1.0.53+6ced4dd9d1
	   |-- fabric-item-api-v1 11.0.0+afdfc921d1
	   |-- fabric-item-group-api-v1 4.1.4+78017270d1
	   |-- fabric-key-binding-api-v1 1.0.47+0af3f5a7d1
	   |-- fabric-keybindings-v0 0.2.45+df3654b3d1
	   |-- fabric-lifecycle-events-v1 2.3.12+6c1df360d1
	   |-- fabric-loot-api-v2 3.0.14+3f89f5a5d1
	   |-- fabric-loot-api-v3 1.0.2+3f89f5a5d1
	   |-- fabric-message-api-v1 6.0.13+6573ed8cd1
	   |-- fabric-model-loading-api-v1 2.0.0+fe474d6bd1
	   |-- fabric-networking-api-v1 4.2.2+60c3209bd1
	   |-- fabric-object-builder-api-v1 15.2.0+a551f7a4d1
	   |-- fabric-particles-v1 4.0.2+6573ed8cd1
	   |-- fabric-recipe-api-v1 5.0.12+65089712d1
	   |-- fabric-registry-sync-v0 5.1.2+60c3209bd1
	   |-- fabric-renderer-api-v1 3.4.0+c705a49cd1
	   |-- fabric-renderer-indigo 1.7.0+c705a49cd1
	   |-- fabric-renderer-registries-v1 3.2.68+df3654b3d1
	   |-- fabric-rendering-data-attachment-v1 0.3.48+73761d2ed1
	   |-- fabric-rendering-fluids-v1 3.1.6+b5597344d1
	   |-- fabric-rendering-v0 1.1.71+df3654b3d1
	   |-- fabric-rendering-v1 5.0.5+df16efd0d1
	   |-- fabric-resource-conditions-api-v1 4.3.0+8dc279b1d1
	   |-- fabric-resource-loader-v0 1.3.0+56599129d1
	   |-- fabric-screen-api-v1 2.0.24+b5597344d1
	   |-- fabric-screen-handler-api-v1 1.3.86+b5597344d1
	   |-- fabric-sound-api-v1 1.0.23+6573ed8cd1
	   |-- fabric-transfer-api-v1 5.1.16+3dccd343d1
	   \-- fabric-transitive-access-wideners-v1 6.1.0+176f9036d1
	- fabric-language-kotlin 1.12.1+kotlin.2.0.20
	   |-- org_jetbrains_kotlin_kotlin-reflect 2.0.20
	   |-- org_jetbrains_kotlin_kotlin-stdlib 2.0.20
	   |-- org_jetbrains_kotlin_kotlin-stdlib-jdk7 2.0.20
	   |-- org_jetbrains_kotlin_kotlin-stdlib-jdk8 2.0.20
	   |-- org_jetbrains_kotlinx_atomicfu-jvm 0.25.0
	   |-- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm 1.8.1
	   |-- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8 1.8.1
	   |-- org_jetbrains_kotlinx_kotlinx-datetime-jvm 0.6.1
	   |-- org_jetbrains_kotlinx_kotlinx-io-bytestring-jvm 0.5.3
	   |-- org_jetbrains_kotlinx_kotlinx-io-core-jvm 0.5.3
	   |-- org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm 1.7.1
	   |-- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm 1.7.1
	   \-- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm 1.7.1
	- fabricloader 0.16.5
	   \-- mixinextras 0.4.1
	- fallingtrees 0.12.3
	- ferritecore 7.0.0
	- fleshz 1.5.1
	- forgeconfigapiport 21.0.8
	   |-- com_electronwill_night-config_core 3.8.0
	   \-- com_electronwill_night-config_toml 3.8.0
	- geckolib 4.5.6
	- handoveryouritems 3.4
	- iceberg 1.2.0
	- idwtialsimmoedm 0.3.0+1.21
	- infchest 21.0.2
	- java 22
	- krypton 0.2.8
	   \-- com_velocitypowered_velocity-native 3.3.0-SNAPSHOT
	- lithium 0.12.7
	- medieval_buildings 1.0.2
	- medievalend 1.0.2
	- mes 1.3.2-1.21-fabric
	- midnightlib 1.6.3
	- mine-spawners 1.0
	- minecraft 1.21
	- modernfix 5.19.1+mc1.21
	- more_babies 2.0.0
	- movingelevators 1.4.7
	- mr_classic_luckyblocks 1
	- mr_daycounter 1.21
	- mr_dragonkind_evolved 1.5
	- mr_just_anotherstructurepack 1.9.1
	- mr_show_dimensioninname 1-v.2.0.0
	- mr_thepa_structures 1.0
	- mr_true_ending 1-v1.1.2d
	- mythicupgrades 4.2.0+mc1.21
	   \-- mixinextras 0.4.1
	- netheriteextras 0.4.0+mc1.21
	- noisium 2.3.0+mc1.21-1.21.1
	- owo 0.12.12+1.21
	   |-- io_wispforest_endec 0.1.5
	   |-- io_wispforest_endec_gson 0.1.3
	   |-- io_wispforest_endec_jankson 0.1.3
	   \-- io_wispforest_endec_netty 0.1.2
	- packedup 1.0.30+b
	- pandalib 0.4.2
	- passthroughsigns 2.7.0
	- physicsmod 3.0.16
	- placeholder-api 2.4.1+1.21
	- pointblank 1.6.7
	- polymer-bundled 0.9.9+1.21
	   |-- polymer-autohost 0.9.9+1.21
	   |    \-- io_netty_netty-codec-http 4.1.82
	   |-- polymer-blocks 0.9.9+1.21
	   |-- polymer-common 0.9.9+1.21
	   |    \-- packet_tweaker 0.5.5+1.21
	   |-- polymer-core 0.9.9+1.21
	   |    |-- polymer-networking 0.9.9+1.21
	   |    |    \-- polymer-common 0.9.9+1.21
	   |    |         \-- packet_tweaker 0.5.5+1.21
	   |    \-- polymer-registry-sync-manipulator 0.9.9+1.21
	   |-- polymer-resource-pack 0.9.9+1.21
	   |    \-- polymer-common 0.9.9+1.21
	   |         \-- packet_tweaker 0.5.5+1.21
	   \-- polymer-virtual-entity 0.9.9+1.21
	        \-- polymer-common 0.9.9+1.21
	             \-- packet_tweaker 0.5.5+1.21
	- reinfchest 3.0.1+1.21
	   \-- reinfcore 4.0.1+1.21
	- repurposed_structures 7.5.4+1.21-fabric
	- resourcefullib 3.0.10
	   |-- com_teamresourceful_bytecodecs 1.1.2
	   \-- com_teamresourceful_yabn 1.0.3
	- ring_of_growth 1.6.5
	   \-- blue_endless_jankson 1.2.3
	- ring_of_repair 1.3.5
	   \-- blue_endless_jankson 1.2.3
	- ring_of_teleport 1.5.6
	   \-- blue_endless_jankson 1.2.3
	- showmeyourskin 1.11.3+1.21
	   |-- cardinal-components-base 6.1.0
	   \-- cardinal-components-entity 6.1.0
	- shulkerboxtooltip 5.0.4+1.21
	- soulbound 1.0.0+1.21
	- supermartijn642configlib 1.1.8
	- supermartijn642corelib 1.1.17
	- t_and_t 1.13.2
	- telepass 6.0.0
	- the_bumblezone 7.6.22+1.21-fabric
	   \-- athena 4.0.0
	- tiered 1.0.2
	- trajectory-preview 4.0-1.21
	- trashslot 21.0.1
	- trinkets 3.10.0
	   |-- cardinal-components-base 6.1.0
	   \-- cardinal-components-entity 6.1.0
	- trop 24.7.19
	- underground_villages 4.0.0
	- unionlib 12.0.7
	   \-- com_google_code_findbugs_jsr305 3.0.2
	- universal-graves 3.4.2+1.21
	   |-- common-protection-api 1.0.0
	   |-- fabric-permissions-api-v0 0.2-SNAPSHOT
	   |-- predicate-api 0.5.1+1.21
	   |-- server_translations_api 2.3.1+1.21-pre2
	   \-- sgui 1.6.0+1.21
	- uselessreptile 0.7.4.2-1.21
	   |-- common-protection-api 1.0.0
	   \-- primitive_multipart_entities 1.1.1
	- vanityslots 1.4.0+1.21
	- veinmining 5.0.0-beta+1.21
	   \-- spectrelib 0.17.1+1.21
	        |-- com_electronwill_night-config_core 3.8.0
	        \-- com_electronwill_night-config_toml 3.8.0
	- vinurl 1.1.3
	- xaerominimap 24.4.0
	- xtraarrows 3.4.2
	- yes_steve_model 2.2.2
	- yet_another_config_lib_v3 3.5.0+1.21-fabric
	   |-- com_twelvemonkeys_common_common-image 3.10.0
	   |-- com_twelvemonkeys_common_common-io 3.10.0
	   |-- com_twelvemonkeys_common_common-lang 3.10.0
	   |-- com_twelvemonkeys_imageio_imageio-core 3.10.0
	   |-- com_twelvemonkeys_imageio_imageio-metadata 3.10.0
	   |-- com_twelvemonkeys_imageio_imageio-webp 3.10.0
	   |-- org_quiltmc_parsers_gson 0.2.1
	   \-- org_quiltmc_parsers_json 0.2.1
```

### Description

I'm using Fabric 1.21, so I've put in all the Fabric 1.21 mods that I'm using. But I'm getting an error.

### Logs

01:27:46 | Minecraft has crashed!net.fabricmc.loader.impl.FormattedException: java.lang.ExceptionInInitializerError
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:63) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:472) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.15.11.jar:?]
	at io.izzel.arclight.boot.fabric.application.Main_Fabric.main(Main_Fabric.java:33) [arclight-fabric-1.21-1.0.0-SNAPSHOT.jar:arclight-1.21-1.0.0-SNAPSHOT-b3349e9]
	at io.izzel.arclight.server.Launcher.main(Launcher.java:39) [arclight-fabric-1.21-1.0.0-SNAPSHOT.jar:arclight-1.21-1.0.0-SNAPSHOT-b3349e9]
Caused by: java.lang.ExceptionInInitializerError
	at net.minecraft.class_2358.method_10199(FireBlockMixin_Fabric.java:336) ~[server-intermediary.jar:?]
	at net.minecraft.class_2966.method_12851(BootstrapMixin.java:52) ~[server-intermediary.jar:?]
	at net.minecraft.server.Main.main(Main.java:108) ~[server-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.11.jar:?]
	... 5 more
Caused by: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_1706 failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.15.11.jar:?]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
	at net.minecraft.class_2246.<clinit>(class_2246.java:557) ~[server-intermediary.jar:?]
	at net.minecraft.class_2358.method_10199(FireBlockMixin_Fabric.java:336) ~[server-intermediary.jar:?]
	at net.minecraft.class_2966.method_12851(BootstrapMixin.java:52) ~[server-intermediary.jar:?]
	at net.minecraft.server.Main.main(Main.java:108) ~[server-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.11.jar:?]
	... 5 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.15.11.jar:?]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
	at net.minecraft.class_2246.<clinit>(class_2246.java:557) ~[server-intermediary.jar:?]
	at net.minecraft.class_2358.method_10199(FireBlockMixin_Fabric.java:336) ~[server-intermediary.jar:?]
	at net.minecraft.class_2966.method_12851(BootstrapMixin.java:52) ~[server-intermediary.jar:?]
	at net.minecraft.server.Main.main(Main.java:108) ~[server-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.11.jar:?]
	... 5 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Constant modifier method arclight$maximumRepairCost(I)I in mixins.arclight.core.json:world.inventory.AnvilMenuMixin from mod arclight failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap arclight-common-arclight-common-refmap.json
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:468) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1384) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1062) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:402) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:327) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:422) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.15.11.jar:?]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
	at net.minecraft.class_2246.<clinit>(class_2246.java:557) ~[server-intermediary.jar:?]
	at net.minecraft.class_2358.method_10199(FireBlockMixin_Fabric.java:336) ~[server-intermediary.jar:?]
	at net.minecraft.class_2966.method_12851(BootstrapMixin.java:52) ~[server-intermediary.jar:?]
	at net.minecraft.server.Main.main(Main.java:108) ~[server-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.11.jar:?]
	... 5 more
[m

### Server pack link (Optional)

https://drive.google.com/file/d/1_HITDQBA_3h-vNuPOy3fzXs475-_aD5g/view?usp=sharing

**Comment by qyl27** [comment]
1.21-1.0.0-SNAPSHOT is the outdated version.  
Have you really confirmed that **Arclight is up to date**?
