### ISSUE TITLE
1.15.2运行时出错！

### ISSUE THREAD

**Issue by KonjacCool** [IzzelAliz/Arclight#15]
服务器运行时出现以下错误！
[21:54:44] [Server thread/ERROR] [Arclight/]: 处理 Forge 注册时出错
java.lang.IllegalArgumentException: Illegal Capacity: -1
        at java.util.ArrayList.<init>(Unknown Source) ~[?:1.8.0_251] {}
        at io.izzel.arclight.common.mod.server.BukkitRegistry.loadEntities(BukkitRegistry.java:60) ~[?:arclight-1.15.2-1.0.1-5a1500a] {re:mixin,re:classloading}
        at io.izzel.arclight.common.mod.server.BukkitRegistry.registerAll(BukkitRegistry.java:54) ~[?:arclight-1.15.2-1.0.1-5a1500a] {re:mixin,re:classloading}
        at net.minecraft.server.management.PlayerList.handler$zmm000$arclight$loadCraftBukkit(PlayerListMixin_1_15.java:992) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.management.PlayerListMixin,pl:mixin:APP:mixins.arclight.core.1_15.json:server.management.PlayerListMixin_1_15,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.server.management.PlayerList.<init>(PlayerListMixin_1_15.java:104) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.management.PlayerListMixin,pl:mixin:APP:mixins.arclight.core.1_15.json:server.management.PlayerListMixin_1_15,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.server.dedicated.DedicatedPlayerList.<init>(SourceFile:14) [?:?] {re:classloading}
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServerMixin.java:182) [?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.dedicated.DedicatedServerMixin,pl:mixin:A}
        at net.minecraft.server.MinecraftServer.run(MinecraftServerMixin.java:1910) [?:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,pl:mixin:A,pl:runtimedistcleaner:A,re:arclight_implementer,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_251] {re:arclight_implementer}

**Comment by IzzelAliz** [comment]
这个问题已经在前几次更新修复
请使用构建站的版本
