### ISSUE TITLE
Can't launcher my arclight forger server due to nightconfig can't find a value

### ISSUE THREAD

**Issue by Meekiavelique** [IzzelAliz/Arclight#1506]
### I have confirmed that ...

- [X] Arclight is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Forge

### Arclight version

arclight-1.20.1-1.0.5-1a8925b

### OS & Java versions

Java 21 ( can't know the os or the specific version of the java since it's in a hosting panel)

### Plugins and Mods

```raw
Aurora-1.5.11.jar
AuroraQuests-1.1.1.jar
AzLink.jar
CrazyCrates-1.13.jar
CustomEnderChest-v1.13.1.jar
EssentialsX-2.21.0-dev+110-f1a5caf.jar
EssentialsXChat-2.21.0-dev+110-f1a5caf.jar
gringotts-2.12.5.jar
GSit-1.10.0.jar
ItemsAdder_3.6.4.jar
LiteEco-1.4.7-SNAPSHOT.jar
LocketteX-1.8.0.jar
LoneLibs_1.0.58.jar
LuckPerms-Bukkit-5.4.134.jar
multiverse-core-4.3.13.jar
multiverse-portals-4.2.3.jar
ProtocolLib.jar
Shopkeepers-2.14.0.jar
SkArclight-1.0.0.jarSkript-2.9.1.jar
TAB v4.1.7.jar
Vault.jar
worldguard-bukkit-7.0.9-dist.jar


aether-1.20.1-1.4.2-neoforge.jar
aquamirae-6.API15.jar
archive-2024-09-01T183118+0200.tar.gz
archive-2024-09-01T183203+0200.tar.gz
balm-forge-1.20.1-7.3.7-all.jar
BiomesOPlenty-1.20.1-18.0.0.598.jar
blue_skies-1.20.1-1.3.31.jar
caelus-forge-3.2.0+1.20.1.jar
chat_heads-0.12.13-forge-1.20.jar
citadel-2.6.0-1.20.1.jar
common-networking-forge-1.0.5-1.20.1.jar
Cucumber-1.20.1-7.0.11.jar
curios-forge-5.9.1+1.20.1.jar
dungeons-and-taverns-3.0.3.f.jar
eeeabsmobs-1.20.1-0.95.jar
exlinefurniture-forge-1.20.1-2.7.3.jar
Explorify v1.6.1 f10-48.jar
FarmersDelight-1.20.1-1.2.4.jar
geckolib-forge-1.20.1-4.4.7.jar
handcrafted-forge-1.20.1-3.0.6.jar
hyperbox-1.20.1-4.0.2.0.jar
Icarus-NeoForge-2.9.2.jar
iceandfire-2.1.13-1.20.1-beta-5.jar
Incendium_1.20.x_v5.3.5.jar
InsaneLib-1.13.5-mc1.20.1.jar
Jade-1.20.1-forge-11.9.4.jar
jei-1.20.1-forge-15.12.3.54.jar
L_Enders_Cataclysm-1.99.5 -1.20.1.jar
lionfishapi-1.9.jar
lootr-forge-1.20-0.7.34.87.jar
lost_aether_content-1.20.1-1.2.3.jar
lukis-grand-capitals-1.0.jar
mcw-fences-1.1.2-mc1.20.1forge.jar
mcw-furniture-3.3.0-mc1.20.1forge.jar
mcw-trapdoors-1.1.3-mc1.20.1forge.jar
mcw-windows-2.3.0-mc1.20.1forge.jar
mcwfurnituresbop-1.20-1.2.jar
MedievalOriginsRevival-6.4.5+1.20.1-forge.jar
melody_forge_1.0.3_MC_1.20.1-1.20.4.jar
moonlight-1.20-2.12.12-forge.jar
more_villargers-2.5.6-forge-1.20.1.jar
MysticalAgriculture-1.20.1-7.0.12.jar
NightConfigFixes-v8.0.0-1.20.1-Forge (1).jar
obscure_api-15.jar
origins-forge-1.20.1-1.10.0.9-all.jar
Pehkui-3.8.2+1.20.1-forge.jar
ProgressiveBosses-3.9.4-mc1.20.1.jar
realmrpg_fallen_adventurers_1.0.3_forge_1.20.1.jar
realmrpg_imps_and_demons_0.9.0_forge_1.20.1.jar
resourcefulconfig-forge-1.20.1-2.1.2.jar
resourcefullib-forge-1.20.1-2.1.28.jar
saturn-mc1.20.1-0.1.3.jar
ShieldExpansion-1.20.1-1.1.7a.jar
shopkeepersmodcompatibility-2.0.jar
sophisticatedbackpacks-1.20.1-3.20.5.1044.jar
sophisticatedcore-1.20.1-0.6.22.611.jar
spartantoolkit-1.20.1-1.4.2.jar
spartantwilight-1.20.1-3.1.0.jar
SpartanWeaponry-1.20.1-forge-3.1.3-all.jar
stalwart-dungeons-1.20.1-1.2.8.jar
structure_gel-1.20.1-2.16.2.jar
takesapillage-1.0.3-1.20.1.jar
TerraBlender-forge-1.20.1-3.0.1.7.jar
Twigs-1.20.1-3.1.1.jar
twilightforest-1.20.1-4.3.2508-universal.jar
voicechat-forge-1.20.1-2.5.20.jar
waystones-forge-1.20-14.1.4.jar
weaponmaster-1.4.2-1.20.1.jar
worldedit-mod-7.2.15.jar
```

### Description

Getting com.electronwill.nightconfig.core.io.ParsingException: Invalid bare key: ${mod_id} when launching the server
Happenned after a restart of it

### Step to reproduce

I really don't know it did it by restarting the server

### Logs

Using locale en_us and fallback locale zh_cn
[19:32:19 INFO] [Arclight]: 
       ___           ___     __   /\
      /   | ________/ (_)__ / /  / /
     / /| |/ __/ __/ / / _ / _ \/__/
    / ___ / / / /_/ / / / / // / /
   /_/  |/_/  \__/_/_/\_ /_//_/ /
                     /__/     \/
    Version 顿顽 (Trials) / arclight-1.20.1-1.0.5-1a8925b
    Build Date 2024-02-28 14:51:40

[19:32:19 INFO] [c.m.m.Launcher/MODLAUNCHER]: ModLauncher running: args [--launchTarget, arclightserver, --fml.forgeVersion, 47.2.20, --fml.mcVersion, 1.20.1, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20230612.114412]
[19:32:19 INFO] [c.m.m.Launcher/MODLAUNCHER]: ModLauncher 10.0.9+10.0.9+main.dcd20f30 starting: java version 21.0.2 by GraalVM Community; OS Linux arch amd64 version 5.10.0-28-amd64
[19:32:20 INFO]: ImmediateWindowProvider not loading because launch target is arclightserver
[19:32:20 INFO] [mixin]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=union:/home/container/libraries/org/spongepowered/mixin/0.8.5/mixin-0.8.5.jar%2399!/ Service=ModLauncher Env=SERVER
com.electronwill.nightconfig.core.io.ParsingException: Invalid bare key: ${mod_id}
        at MC-BOOTSTRAP/com.electronwill.nightconfig.toml@3.6.4/com.electronwill.nightconfig.toml.TableParser.parseKey(TableParser.java:175)
        at MC-BOOTSTRAP/com.electronwill.nightconfig.toml@3.6.4/com.electronwill.nightconfig.toml.TableParser.parseTableName(TableParser.java:111)
        at MC-BOOTSTRAP/com.electronwill.nightconfig.toml@3.6.4/com.electronwill.nightconfig.toml.TomlParser.parse(TomlParser.java:51)
        at MC-BOOTSTRAP/com.electronwill.nightconfig.toml@3.6.4/com.electronwill.nightconfig.toml.TomlParser.parse(TomlParser.java:37)
        at MC-BOOTSTRAP/com.electronwill.nightconfig.core@3.6.4/com.electronwill.nightconfig.core.io.ConfigParser.parse(ConfigParser.java:113)
        at MC-BOOTSTRAP/com.electronwill.nightconfig.core@3.6.4/com.electronwill.nightconfig.core.io.ConfigParser.parse(ConfigParser.java:219)
        at MC-BOOTSTRAP/com.electronwill.nightconfig.core@3.6.4/com.electronwill.nightconfig.core.io.ConfigParser.parse(ConfigParser.java:202)
        at MC-BOOTSTRAP/com.electronwill.nightconfig.core@3.6.4/com.electronwill.nightconfig.core.file.WriteAsyncFileConfig.load(WriteAsyncFileConfig.java:138)
        at MC-BOOTSTRAP/fmlloader@1.20.1-47.2.20/net.minecraftforge.fml.loading.moddiscovery.ModFileParser.modsTomlParser(ModFileParser.java:44)
        at MC-BOOTSTRAP/fmlloader@1.20.1-47.2.20/net.minecraftforge.fml.loading.moddiscovery.ModFileParser.readModList(ModFileParser.java:31)
        at MC-BOOTSTRAP/fmlloader@1.20.1-47.2.20/net.minecraftforge.fml.loading.moddiscovery.ModFile.<init>(ModFile.java:79)
        at MC-BOOTSTRAP/fmlloader@1.20.1-47.2.20/net.minecraftforge.fml.loading.moddiscovery.ModFile.<init>(ModFile.java:68)
        at MC-BOOTSTRAP/fmlloader@1.20.1-47.2.20/net.minecraftforge.fml.loading.moddiscovery.AbstractModProvider.createMod(AbstractModProvider.java:52)
        at MC-BOOTSTRAP/fmlloader@1.20.1-47.2.20/net.minecraftforge.fml.loading.moddiscovery.AbstractJarFileModLocator.lambda$scanMods$0(AbstractJarFileModLocator.java:19)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
        at java.base/java.util.stream.SortedOps$RefSortingSink.end(SortedOps.java:395)
        at java.base/java.util.stream.Sink$ChainedReference.end(Sink.java:261)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:510)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575)
        at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
        at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616)
        at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:622)
        at java.base/java.util.stream.ReferencePipeline.toList(ReferencePipeline.java:627)
        at MC-BOOTSTRAP/fmlloader@1.20.1-47.2.20/net.minecraftforge.fml.loading.moddiscovery.AbstractJarFileModLocator.scanMods(AbstractJarFileModLocator.java:19)
        at MC-BOOTSTRAP/fmlloader@1.20.1-47.2.20/net.minecraftforge.fml.loading.moddiscovery.ModDiscoverer.discoverMods(ModDiscoverer.java:75)
        at MC-BOOTSTRAP/fmlloader@1.20.1-47.2.20/net.minecraftforge.fml.loading.FMLLoader.beginModScan(FMLLoader.java:164)
        at MC-BOOTSTRAP/fmlloader@1.20.1-47.2.20/net.minecraftforge.fml.loading.FMLServiceProvider.beginScanning(FMLServiceProvider.java:86)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.TransformationServiceDecorator.runScan(TransformationServiceDecorator.java:112)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.TransformationServicesHandler.lambda$runScanningTransformationServices$8(TransformationServicesHandler.java:100)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
        at java.base/java.util.HashMap$ValueSpliterator.forEachRemaining(HashMap.java:1787)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575)
        at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
        at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616)
        at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:622)
        at java.base/java.util.stream.ReferencePipeline.toList(ReferencePipeline.java:627)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.TransformationServicesHandler.runScanningTransformationServices(TransformationServicesHandler.java:102)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.TransformationServicesHandler.initializeTransformationServices(TransformationServicesHandler.java:55)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.Launcher.run(Launcher.java:88)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.Launcher.main(Launcher.java:78)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
        at MC-BOOTSTRAP/arclight.boot/io.izzel.arclight.boot.application.ApplicationBootstrap.accept(ApplicationBootstrap.java:46)
        at MC-BOOTSTRAP/arclight.boot/io.izzel.arclight.boot.application.ApplicationBootstrap.accept(ApplicationBootstrap.java:13)
        at cpw.mods.bootstraplauncher@1.1.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
        at io.izzel.arclight.boot.application.Main_Forge.main(Main_Forge.java:23)
        at io.izzel.arclight.server.Launcher.main(Launcher.java:18)
Fail to launch Arclight.

**Comment by Meekiavelique** [comment]
??
