### ISSUE TITLE
删除mod后加载出错

### ISSUE THREAD

**Issue by 3269199948** [IzzelAliz/Arclight#151]
### 我正在运行

* **Arclight** [版本] arclight-forge-1.16-1.0.12.jar

* **你确认这是最新版吗** [是/否]

* **你确认所有Mod都安装了依赖** [是]

* **你确认所有插件都已更新至对应版本** [是]

* **Java** [jdk1.8] 

* **操作系统** [Centos7.5]

此问题与其他插件或mod无关，即使只有一个mod，删掉在启动也是一样无法启动

### 错误描述
注册了 3866 个材料，其中 2335 个方块 1531 个物品
[16:25:47] [Server thread/ERROR] [Arclight/]: 处理 Forge 注册时出错
java.lang.ArrayIndexOutOfBoundsException: 67
        at org.bukkit.potion.PotionEffectType.registerPotionEffectType(PotionEffectTypeMixin.java:305) ~[arclight:arclight-1.16.5-1.0.12-SNAPSHOT-b0b2d38] {re:mixin,re:classloading,pl:mixin:APP:mixins.arclight.bukkit.json:PotionEffectTypeMixin,pl:mixin:A}
        at io.izzel.arclight.common.mod.server.BukkitRegistry.loadPotions(BukkitRegistry.java:201) ~[arclight:arclight-1.16.5-1.0.12-SNAPSHOT-b0b2d38] {re:mixin,re:classloading}
        at io.izzel.arclight.common.mod.server.BukkitRegistry.registerAll(BukkitRegistry.java:76) ~[arclight:arclight-1.16.5-1.0.12-SNAPSHOT-b0b2d38] {re:mixin,re:classloading}
        at io.izzel.arclight.common.mod.server.ArclightServer.createOrLoad(ArclightServer.java:38) ~[arclight:arclight-1.16.5-1.0.12-SNAPSHOT-b0b2d38] {re:mixin,re:classloading}
        at net.minecraft.server.management.PlayerList.handler$bao000$arclight$loadServer(PlayerListMixin.java:1023) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.management.PlayerListMixin,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.server.management.PlayerList.<init>(PlayerListMixin.java:120) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.management.PlayerListMixin,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.server.dedicated.DedicatedPlayerList.<init>(SourceFile:16) ~[?:?] {re:mixin,re:classloading}
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServerMixin.java:160) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
        at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServerMixin.java:1857) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.lambda$startServer$0(MinecraftServerMixin.java:232) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_281] {}

     ### 执行到此处卡住

注册了 2 个新的世界类型
[16:25:56] [Server thread/ERROR] [minecraft/MinecraftServer]: Encountered an unexpected exception
java.lang.NullPointerException: null
        at org.spigotmc.SpigotWorldConfig.getBoolean(SpigotWorldConfig.java:44) ~[arclight:arclight-1.16.5-1.0.12-SNAPSHOT-b0b2d38] {re:mixin,re:classloading}
        at org.spigotmc.SpigotWorldConfig.init(SpigotWorldConfig.java:23) ~[arclight:arclight-1.16.5-1.0.12-SNAPSHOT-b0b2d38] {re:mixin,re:classloading}
        at org.spigotmc.SpigotWorldConfig.<init>(SpigotWorldConfig.java:18) ~[arclight:arclight-1.16.5-1.0.12-SNAPSHOT-b0b2d38] {re:mixin,re:classloading}
        at net.minecraft.world.World.handler$bcf000$arclight$init(WorldMixin.java:1252) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:observerlib:coremodmethod,xf:fml:astralsorcery:sun_brightness_server,pl:mixin:APP:mixins.arclight.core.json:world.WorldMixin,pl:mixin:A,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.world.World.<init>(WorldMixin.java:123) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:observerlib:coremodmethod,xf:fml:astralsorcery:sun_brightness_server,pl:mixin:APP:mixins.arclight.core.json:world.WorldMixin,pl:mixin:A,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.world.server.ServerWorld.<init>(ServerWorldMixin.java:179) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:world.server.ServerWorldMixin,pl:mixin:A,pl:arclight_implementer:async,pl:arclight_implementer:A,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.func_240787_a_(MinecraftServerMixin.java:335) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.func_240800_l__(MinecraftServerMixin.java:308) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServerMixin.java:168) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
        at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServerMixin.java:1857) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.lambda$startServer$0(MinecraftServerMixin.java:232) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_281] {}
[16:25:56] [Server thread/FATAL] [n.m.c.ForgeMod/]: Preparing crash report with UUID 45fb5315-7fce-450d-945a-280d9922c127

### 重现步骤

1. 安装 xxx
2. 进入服务器后 xxxx
3. ....

**可在 Forge 复现** [是]

**可在 Spigot 复现** [否]

### 报错信息

[错误日志]
https://paste.ubuntu.com/p/wmtqzyRjmp/

**Comment by IzzelAliz** [comment]
请提供 debug.log

**Comment by 3269199948** [comment]
> 请提供 debug.log

端都被我删了，我都以为你不管了
