### ISSUE TITLE
[ 1.21.1 - Neoforge ] ProtocolLib didn‘t work

### ISSUE THREAD

**Issue by windy664** [IzzelAliz/Arclight#1513]
### I have confirmed that ...

- [X] Arclight is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Forge

### Arclight version

arclight-neoforge-1.21.1-1.0.0-SNAPSHOT

### OS & Java versions

Java21

### Plugins and Mods

```raw
ProtocolLib
```

### Description

[0210ÔÂ2024 21:09:17.207] [Server thread/ERROR] [Minecraft/]:   [ProtocolLib] INTERNAL ERROR: Cannot load ProtocolLib.
  If this problem hasn't already been reported, please open a ticket
  at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
  Stack Trace:
  java.lang.IllegalArgumentException: Unable to find a field that matches {modifiers=[required: 10000, banned: 1000], type={ type input instanceof interface java.util.Map }}
  	at com.comphenix.protocol.reflect.FuzzyReflection.getField(FuzzyReflection.java:352)
  	at com.comphenix.protocol.injector.packet.PacketRegistry.createNewRegister(PacketRegistry.java:183)
  	at com.comphenix.protocol.injector.packet.PacketRegistry.initialize(PacketRegistry.java:334)
  	at com.comphenix.protocol.injector.packet.PacketRegistry.getClientPacketTypes(PacketRegistry.java:369)
  	at com.comphenix.protocol.injector.PacketFilterManager.<init>(PacketFilterManager.java:120)
  	at com.comphenix.protocol.injector.PacketFilterBuilder.build(PacketFilterBuilder.java:121)
  	at com.comphenix.protocol.ProtocolLib.onLoad(ProtocolLib.java:183)
  	at TRANSFORMER/arclight@1.0.0-SNAPSHOT+d0dda85/org.bukkit.craftbukkit.v1_21_R1.CraftServer.loadPlugins(CraftServerMixin.java:469)
  	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.dedicated.DedicatedServer.handler$bca000$arclight$loadPlugins(DedicatedServerMixin_NeoForge.java:752)
  	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServerMixin_NeoForge.java:183)
  	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.runServer(MinecraftServerMixin_NeoForge.java:670)
  	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServerMixin_NeoForge.java:267)
  	at java.base/java.lang.Thread.run(Thread.java:1583)
  Dump:
  Parameters: 
    [NULL]
  Sender:
    com.comphenix.protocol.ProtocolLib@22222029[
      statistics=<null>
      packetTask=<null>
      tickCounter=0
      configExpectedMod=-1
      updater=com.comphenix.protocol.updater.SpigotUpdater@4d481514
      redirectHandler=<null>
      scheduler=com.comphenix.protocol.scheduler.DefaultScheduler@2fcce012
      commandProtocol=<null>
      commandPacket=<null>
      commandFilter=<null>
      packetLogging=<null>
      skipDisable=false
      isEnabled=false
      loader=org.bukkit.plugin.java.JavaPluginLoader@f315d89
      server=CraftServer{serverName=CraftBukkit,serverVersion=arclight-1.21.1-1.0.0-SNAPSHOT-d0dda85,minecraftVersion=1.21.1}
      file=plugins\[P][Ç°ÖÃ]ProtocolLib.jar
      description=org.bukkit.plugin.PluginDescriptionFile@69949552
      dataFolder=plugins\ProtocolLib
      classLoader=org.bukkit.plugin.java.PluginClassLoader@30e344a
      naggable=true
      newConfig=YamlConfiguration[path='', root='YamlConfiguration']
      configFile=plugins\ProtocolLib\config.yml
      logger=io.izzel.arclight.common.mod.util.log.ArclightPluginLogger@61987536
    ]
  Version:
    ProtocolLib v5.2.0-SNAPSHOT-679
  Java Version:
    21.0.4

**Comment by qyl27** [comment]
无法复现

**Comment by windy664** [comment]
补充：[ProtocolLib v5.2.0]

**Comment by qyl27** [comment]
> 补充：[ProtocolLib v5.2.0]

5.2.0是给1.8~1.20.4的呀，你有读过他们的说明吗（
