### ISSUE TITLE
[ 1.21.1 - Neoforge ] NBTAPI 不正常

### ISSUE THREAD

**Issue by windy664** [IzzelAliz/Arclight#1514]
### I have confirmed that ...

- [X] Arclight is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Forge

### Arclight version

arclight-neoforge-1.21.1-1.0.0-SNAPSHOT

### OS & Java versions

Java21

### Plugins and Mods

```raw
NBTAPI
```

### Description

NBTAPI无法正常enable

### Logs

||                                                  
                                 |||                  |||                                        ||                    |       |                                                   
                                  ||                                                                                                                                               
                                  |                                                                                                                                                

[0210ÔÂ2024 21:09:35.503] [Server thread/INFO] [Console/]:    ____ ______   ___   ____    ____ __  __   _  __  _____
  / __//_  __/  / _ ) / __ \  / __/ \ \/ /  / |/ / / ___/
 / _/   / /    / _  |/ /_/ / _\ \    \  /  /    / / /__  
/_/    /_/    /____/ \___\_\/___/    /_/  /_/|_/  \___/  
                                                         

[0210ÔÂ2024 21:09:35.503] [Server thread/INFO] [UnrealCore/]: Enabling UnrealCore v2.0
[0210ÔÂ2024 21:09:35.517] [Server thread/INFO] [UnrealCore/]: System: Using port 34519, waiting for client to connect.
[0210ÔÂ2024 21:09:35.544] [Server thread/INFO] [TrChat/]: Enabling TrChat v2.2.0-beta4
[0210ÔÂ2024 21:09:35.630] [Server thread/INFO] [PlaceholderAPI/]: Successfully registered internal expansion: trchat [2.2.0-beta4]
[0210ÔÂ2024 21:09:35.663] [Server thread/ERROR] [STDERR/]: SLF4J: No SLF4J providers were found.
[0210ÔÂ2024 21:09:35.663] [Server thread/ERROR] [STDERR/]: SLF4J: Defaulting to no-operation (NOP) logger implementation
[0210ÔÂ2024 21:09:35.663] [Server thread/ERROR] [STDERR/]: SLF4J: See https://www.slf4j.org/codes.html#noProviders for further details.
[0210ÔÂ2024 21:09:36.691] [Server thread/INFO] [Console/]: [TrChat] µ±Ç°ÎÞ¿ç·þÖ§³Ö.
[0210ÔÂ2024 21:09:36.729] [Server thread/INFO] [Console/]: [TrChat] ÁÄÌì | ³É¹¦ÔØÈë 12 ¸öÁÄÌì¹¦ÄÜ... [16 Ms]
[0210ÔÂ2024 21:09:36.735] [Server thread/INFO] [Console/]: [TrChat] ¹ýÂËÆ÷ | ÒÑÔØÈë±¾µØÃô¸Ð´Ê¿â×Ü¼Æ 3 ¸ö.
[0210ÔÂ2024 21:09:36.843] [Server thread/INFO] [Console/]: [TrChat] ÁÄÌì | ³É¹¦ÔØÈë 4 ¸öÁÄÌìÆµµÀ... [108 Ms]
[0210ÔÂ2024 21:09:36.843] [Server thread/INFO] [Console/]: [TrChat] ÐÅÏ¢ | ¼ÓÔØÍê±Ï. TrChat v2.2.0-beta4 ÏÖÒÑÆôÓÃ, ¾´ÇëÊ¹ÓÃ.
[0210ÔÂ2024 21:09:36.845] [Server thread/INFO] [BanPiston/]: Enabling BanPiston v1.2.1
[0210ÔÂ2024 21:09:36.845] [Server thread/INFO] [Console/]: BanPiston plugin loaded success!
[0210ÔÂ2024 21:09:36.849] [Server thread/INFO] [AntiLoop/]: Enabling AntiLoop v2.4
[0210ÔÂ2024 21:09:36.854] [Server thread/WARN] [AntiLoop/]: Ã»ÓÐÕÒµ½·½¿é:ENDERIO_ENERGY_CONDUIT
[0210ÔÂ2024 21:09:36.854] [Server thread/INFO] [AntiLoop/]:  _              _     _   _                             
[0210ÔÂ2024 21:09:36.854] [Server thread/INFO] [AntiLoop/]: / \     _ __   | |_  (_) | |       ___     ___    _ __  
[0210ÔÂ2024 21:09:36.854] [Server thread/INFO] [AntiLoop/]: / _ \   | '_ \  | __| | | | |      / _ \   / _ \  | '_ \ 
[0210ÔÂ2024 21:09:36.855] [Server thread/INFO] [AntiLoop/]: / ___ \  | | | | | |_  | | | |___  | (_) | | (_) | | |_) |
[0210ÔÂ2024 21:09:36.855] [Server thread/INFO] [AntiLoop/]: /_/   \_\ |_| |_|  \__| |_| |_____|  \___/   \___/  | .__/ 
[0210ÔÂ2024 21:09:36.855] [Server thread/INFO] [AntiLoop/]:                                                     |_|    
[0210ÔÂ2024 21:09:36.855] [Server thread/INFO] [AntiLoop/]: AntLoopÒÑ¼ÓÔØ - °æ±¾ - 1.0
[0210ÔÂ2024 21:09:36.856] [Server thread/INFO] [MiaoBoard/]: Enabling MiaoBoard v2.6.0-git-00db90be472bcc688847491a33f195cc5637bbd1
[0210ÔÂ2024 21:09:37.384] [Server thread/INFO] [NoBuildPlus/]: Enabling NoBuildPlus v1.4.3
[0210ÔÂ2024 21:09:37.401] [Server thread/INFO] [Minecraft/]: Initialization completed: {}
[0210ÔÂ2024 21:09:37.401] [Server thread/INFO] [NoBuildPlus/]: [NBP] START LOADING ...
[0210ÔÂ2024 21:09:37.403] [Server thread/INFO] [NoBuildPlus/]: [NBP] CMD LOADED.
[0210ÔÂ2024 21:09:37.439] [Server thread/INFO] [NoBuildPlus/]: [NBP] LISTENERS LOADED.
[0210ÔÂ2024 21:09:37.439] [Server thread/INFO] [NoBuildPlus/]: [NBP] HOOKED FUNCTIONS LOADED.
[0210ÔÂ2024 21:09:37.440] [Server thread/INFO] [NoBuildPlus/]: Plugin loaded! Version: 1.4.3
[0210ÔÂ2024 21:09:37.441] [Server thread/INFO] [NoBuildPlus/]: NBP API is loaded! This is a testing API at v0.1
[0210ÔÂ2024 21:09:37.441] [Server thread/INFO] [NoBuildPlus/]:     _   __      ____        _ __    ______  __          
[0210ÔÂ2024 21:09:37.441] [Server thread/INFO] [NoBuildPlus/]:    / | / /___  / __ )__  __(_) /___/ / __ \\/ /_  _______
[0210ÔÂ2024 21:09:37.441] [Server thread/INFO] [NoBuildPlus/]:   /  |/ / __ \\/ __  / / / / / / __  / /_/ / / / / / ___/
[0210ÔÂ2024 21:09:37.441] [Server thread/INFO] [NoBuildPlus/]:  / /|  / /_/ / /_/ / /_/ / / / /_/ / ____/ / /_/ (__  ) 
[0210ÔÂ2024 21:09:37.441] [Server thread/INFO] [NoBuildPlus/]: /_/ |_/\____/_____/\__,_/_/_/\__,_/_/   /_/\__,_/____/  
[0210ÔÂ2024 21:09:37.450] [Server thread/INFO] [NBTAPI/]: Enabling NBTAPI v2.13.2
[0210ÔÂ2024 21:09:37.450] [Server thread/INFO] [NBTAPI/]: Checking bindings...
[0210ÔÂ2024 21:09:37.460] [Server thread/INFO] [NBTAPI/]: All Classes were able to link!
[0210ÔÂ2024 21:09:37.512] [Server thread/INFO] [NBTAPI/]: All Methods were able to link!
[0210ÔÂ2024 21:09:37.512] [Server thread/INFO] [NBTAPI/]: Running NBT reflection test...
[0210ÔÂ2024 21:09:37.984] [Server thread/WARN] [NBTAPI/]: Error during 'LegacyItemTest' test!
de.tr7zw.nbtapi.NbtApiException: [?][2.13.2]1.12.2 item didn't load correctly! ItemStack{COBBLESTONE x 42, UNSPECIFIC_META:{meta-type=UNSPECIFIC, display-name="test", custom=H4sIAAAAAAAA/+NiYOBkYEnNS87gYmBgYGRmYM4pywGymJkZmDJTgAwlBgYAZk0CxiQAAAA=}}
	at de.tr7zw.nbtapi.plugin.tests.items.LegacyItemTest.test(LegacyItemTest.java:30) ~[?:?] {}
	at de.tr7zw.nbtapi.plugin.NBTAPI.onEnable(NBTAPI.java:193) ~[?:?] {}
	at TRANSFORMER/arclight@1.0.0-SNAPSHOT+d0dda85/org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPluginMixin.java:267) ~[arclight-1.21.1-1.0.0-SNAPSHOT-d0dda85.jar%23274!/:arclight-1.21.1-1.0.0-SNAPSHOT-d0dda85] {re:mixin,re:classloading,pl:mixin:APP:mixins.arclight.bukkit.json:JavaPluginMixin from mod (unknown),pl:mixin:A,re:mixin}
	at TRANSFORMER/arclight@1.0.0-SNAPSHOT+d0dda85/org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoaderMixin.java:342) ~[arclight-1.21.1-1.0.0-SNAPSHOT-d0dda85.jar%23274!/:arclight-1.21.1-1.0.0-SNAPSHOT-d0dda85] {re:mixin,re:classloading,pl:mixin:APP:mixins.arclight.bukkit.json:JavaPluginLoaderMixin from mod (unknown),pl:mixin:A}
	at TRANSFORMER/arclight@1.0.0-SNAPSHOT+d0dda85/org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:492) ~[arclight-1.21.1-1.0.0-SNAPSHOT-d0dda85.jar%23274!/:arclight-1.21.1-1.0.0-SNAPSHOT-d0dda85] {re:mixin,re:classloading,re:mixin,re:mixin}
	at TRANSFORMER/arclight@1.0.0-SNAPSHOT+d0dda85/org.bukkit.craftbukkit.v1_21_R1.CraftServer.enablePlugin(CraftServerMixin.java:575) ~[arclight-1.21.1-1.0.0-SNAPSHOT-d0dda85.jar%23274!/:arclight-1.21.1-1.0.0-SNAPSHOT-d0dda85] {re:mixin,re:classloading,pl:mixin:APP:mixins.arclight.neoforge.json:bukkit.CraftServerMixin_NeoForge from mod (unknown),pl:mixin:APP:mixins.arclight.bukkit.json:CraftServerMixin from mod (unknown),pl:mixin:A,re:mixin}
	at TRANSFORMER/arclight@1.0.0-SNAPSHOT+d0dda85/org.bukkit.craftbukkit.v1_21_R1.CraftServer.enablePlugins(CraftServerMixin.java:489) ~[arclight-1.21.1-1.0.0-SNAPSHOT-d0dda85.jar%23274!/:arclight-1.21.1-1.0.0-SNAPSHOT-d0dda85] {re:mixin,re:classloading,pl:mixin:APP:mixins.arclight.neoforge.json:bukkit.CraftServerMixin_NeoForge from mod (unknown),pl:mixin:APP:mixins.arclight.bukkit.json:CraftServerMixin from mod (unknown),pl:mixin:A,re:mixin}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.handler$bbd000$arclight$enablePlugins(MinecraftServerMixin_NeoForge.java:2385) ~[server-1.21.1-20240808.144430-srg.jar%23272!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A,re:mixin,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.createLevels(MinecraftServerMixin_NeoForge.java:430) ~[server-1.21.1-20240808.144430-srg.jar%23272!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A,re:mixin,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.loadLevel(MinecraftServerMixin_NeoForge.java:337) ~[server-1.21.1-20240808.144430-srg.jar%23272!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A,re:mixin,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServerMixin_NeoForge.java:193) ~[server-1.21.1-20240808.144430-srg.jar%23272!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.dedicated.DedicatedServerMixin from mod (unknown),pl:mixin:APP:mixins.arclight.neoforge.json:core.server.dedicated.DedicatedServerMixin_NeoForge from mod (unknown),pl:mixin:A,re:mixin,pl:accesstransformer:B}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.runServer(MinecraftServerMixin_NeoForge.java:670) ~[server-1.21.1-20240808.144430-srg.jar%23272!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A,re:mixin,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServerMixin_NeoForge.java:267) ~[server-1.21.1-20240808.144430-srg.jar%23272!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A,re:mixin,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at java.base/java.lang.Thread.run(Thread.java:1583) [?:?] {re:mixin,re:mixin,re:mixin}

**Comment by qyl27** [comment]
无法复现

**Comment by windy664** [comment]
[00:25:52 INFO]: Gave 1 [64M MEGA Storage Component] to Vespera
[00:25:57 INFO]: Vespera issued server command: /nbt
[00:25:57 ERROR] [STDERR]: java.lang.NullPointerException: Cannot invoke "java.lang.reflect.Method.getDeclaringClass()" because "method" is null
[00:25:57 ERROR] [STDERR]:      at TRANSFORMER/arclight@1.0.0-SNAPSHOT+78c1bfe/io.izzel.arclight.common.mod.util.remapper.ArclightRedirectAdapter.methodToString(ArclightRedirectAdapter.java:396)
[00:25:57 ERROR] [STDERR]:      at TRANSFORMER/arclight@1.0.0-SNAPSHOT+78c1bfe/io.izzel.arclight.common.mod.util.remapper.ArclightRedirectAdapter.runHandle(ArclightRedirectAdapter.java:108)
[00:25:57 ERROR] [STDERR]:      at TRANSFORMER/arclight@1.0.0-SNAPSHOT+78c1bfe/io.izzel.arclight.common.mod.util.remapper.generated.ArclightReflectionHandler_18.handleMethodInvoke(ArclightReflectionHandler.java:529)
[00:25:57 ERROR] [STDERR]:      at ml.mcos.itemnbtedit.nbt.V17AndAfter.asNMSCopy(V17AndAfter.java:55)
[00:25:57 ERROR] [STDERR]:      at ml.mcos.itemnbtedit.nbt.V17AndAfter.getItemNBT(V17AndAfter.java:64)
[00:25:57 ERROR] [STDERR]:      at ml.mcos.itemnbtedit.ItemNBTEdit.onCommand(ItemNBTEdit.java:40)
[00:25:57 ERROR] [STDERR]:      at TRANSFORMER/arclight@1.0.0-SNAPSHOT+78c1bfe/org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[00:25:57 ERROR] [STDERR]:      at TRANSFORMER/arclight@1.0.0-SNAPSHOT+78c1bfe/org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:150)
[00:25:57 ERROR] [STDERR]:      at TRANSFORMER/arclight@1.0.0-SNAPSHOT+78c1bfe/org.bukkit.craftbukkit.v1_21_R1.CraftServer.dispatchCommand(CraftServerMixin.java:922)
[00:25:57 ERROR] [STDERR]:      at TRANSFORMER/arclight@1.0.0-SNAPSHOT+78c1bfe/org.bukkit.craftbukkit.v1_21_R1.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:50)
[00:25:57 ERROR] [STDERR]:      at MC-BOOTSTRAP/brigadier@1.3.10/com.mojang.brigadier.context.ContextChain.runExecutable(ContextChain.java:73)
[00:25:57 ERROR] [STDERR]:      at TRANSFORMER/minecraft@1.21.1/net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:29)
[00:25:57 ERROR] [STDERR]:      at TRANSFORMER/minecraft@1.21.1/net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:13)
[00:25:57 ERROR] [STDERR]:      at TRANSFORMER/minecraft@1.21.1/net.minecraft.commands.execution.UnboundEntryAction.lambda$bind$0(UnboundEntryAction.java:8)
[00:25:57 ERROR] [STDERR]:      at TRANSFORMER/minecraft@1.21.1/net.minecraft.commands.execution.CommandQueueEntry.execute(CommandQueueEntry.java:8)
[00:25:57 ERROR] [STDERR]:      at TRANSFORMER/minecraft@1.21.1/net.minecraft.commands.execution.ExecutionContext.runCommandQueue(ExecutionContext.java:107)
[00:25:57 ERROR] [STDERR]:      at TRANSFORMER/minecraft@1.21.1/net.minecraft.commands.Commands.executeCommandInContext(CommandsMixin_NeoForge.java:363)
[00:25:57 ERROR] [STDERR]:      at TRANSFORMER/minecraft@1.21.1/net.minecraft.commands.Commands.performCommand(CommandsMixin_NeoForge.java:284)
[00:25:57 ERROR] [STDERR]:      at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.network.ServerGamePacketListenerImpl.performUnsignedChatCommand(ServerPlayNetHandlerMixin_NeoForge.java:1281)
[00:25:57 ERROR] [STDERR]:      at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$7(ServerPlayNetHandlerMixin_NeoForge.java:1268)
[00:25:57 ERROR] [STDERR]:      at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.TickTask.run(TickTask.java:18)
[00:25:57 ERROR] [STDERR]:      at TRANSFORMER/minecraft@1.21.1/net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoopMixin.java:148)
[00:25:57 ERROR] [STDERR]:      at TRANSFORMER/minecraft@1.21.1/net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23)
[00:25:57 ERROR] [STDERR]:      at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.doRunTask(MinecraftServerMixin_NeoForge.java:872)
[00:25:57 ERROR] [STDERR]:      at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.doRunTask(MinecraftServerMixin_NeoForge.java:170)
[00:25:57 ERROR] [STDERR]:      at TRANSFORMER/minecraft@1.21.1/net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoopMixin.java:122)
[00:25:57 ERROR] [STDERR]:      at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServerMixin_NeoForge.java:855)
[00:25:57 ERROR] [STDERR]:      at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.pollTask(MinecraftServerMixin_NeoForge.java:849)
[00:25:57 ERROR] [STDERR]:      at TRANSFORMER/minecraft@1.21.1/net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoopMixin.java:111)
[00:25:57 ERROR] [STDERR]:      at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServerMixin_NeoForge.java:825)
[00:25:57 ERROR] [STDERR]:      at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.runServer(MinecraftServerMixin_NeoForge.java:712)
[00:25:57 ERROR] [STDERR]:      at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServerMixin_NeoForge.java:267)
[00:25:57 ERROR] [STDERR]:      at java.base/java.lang.Thread.run(Thread.java:1583)

**Comment by qyl27** [comment]
`/nbt` 是什么插件？
