### ISSUE TITLE
[ 1.21.1 - Neoforge ] Cannot set ResolvableProfile in CraftMetaSkull

### ISSUE THREAD

**Issue by windy664** [IzzelAliz/Arclight#1516]
### I have confirmed that ...

- [X] Arclight is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Forge

### Arclight version

arclight-neoforge-1.21.1-1.0.0-SNAPSHOT

### OS & Java versions

Java21

### Plugins and Mods

```raw
pocketgames
```

### Description

I encountered an IllegalArgumentException while attempting to set a GameProfile to a CraftMetaSkull.profile in Arclight 1.21.1. The error seems to occur during the execution of a custom item utility method getSkullFromURL.
The error specifically points to setting the net.minecraft.world.item.component.ResolvableProfile field, which suggests that the field types are incompatible.

### Step to reproduce

1. Call ItemUtil.getSkullFromURL with a valid URL.
2. Try setting the resulting skull item in a GUI.

### Logs

[17:53:09 ERROR] [STDERR]: java.lang.IllegalArgumentException: Can not set net.minecraft.world.item.component.ResolvableProfile field org.bukkit.craftbukkit.v1_21_R1.inventory.CraftMetaSkull.profile to com.mojang.authlib.GameProfile
[17:53:09 ERROR] [STDERR]:      at java.base/jdk.internal.reflect.FieldAccessorImpl.throwSetIllegalArgumentException(FieldAccessorImpl.java:228)
[17:53:09 ERROR] [STDERR]:      at java.base/jdk.internal.reflect.FieldAccessorImpl.throwSetIllegalArgumentException(FieldAccessorImpl.java:232)
[17:53:09 ERROR] [STDERR]:      at java.base/jdk.internal.reflect.MethodHandleObjectFieldAccessorImpl.set(MethodHandleObjectFieldAccessorImpl.java:115)
[17:53:09 ERROR] [STDERR]:      at java.base/java.lang.reflect.Field.set(Field.java:836)
[17:53:09 ERROR] [STDERR]:      at com.live.bemmamin.pocketgames.utils.ItemUtil.getSkullFromURL(ItemUtil.java:219)
[17:53:09 ERROR] [STDERR]:      at com.live.bemmamin.pocketgames.utils.ItemUtil.getSkull(ItemUtil.java:191)
[17:53:09 ERROR] [STDERR]:      at com.live.bemmamin.pocketgames.utils.ItemUtil.getItemStack(ItemUtil.java:156)
[17:53:09 ERROR] [STDERR]:      at com.live.bemmamin.pocketgames.MainGUI.setPageButtons(MainGUI.java:99)
[17:53:09 ERROR] [STDERR]:      at com.live.bemmamin.pocketgames.MainGUI.menu(MainGUI.java:63)
[17:53:09 ERROR] [STDERR]:      at com.live.bemmamin.pocketgames.commands.pocketgamescmd.MenuSub.onCommand(MenuSub.java:51)
[17:53:09 ERROR] [STDERR]:      at com.live.bemmamin.pocketgames.commands.AbstractCommand.onCommand(AbstractCommand.java:50)
[17:53:09 ERROR] [STDERR]:      at TRANSFORMER/arclight@1.0.0-SNAPSHOT+d0dda85/org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[17:53:09 ERROR] [STDERR]:      at TRANSFORMER/arclight@1.0.0-SNAPSHOT+d0dda85/org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:150)
[17:53:09 ERROR] [STDERR]:      at TRANSFORMER/arclight@1.0.0-SNAPSHOT+d0dda85/org.bukkit.craftbukkit.v1_21_R1.CraftServer.dispatchCommand(CraftServerMixin.java:921)
[17:53:09 ERROR] [STDERR]:      at TRANSFORMER/arclight@1.0.0-SNAPSHOT+d0dda85/org.bukkit.Bukkit.dispatchCommand(Bukkit.java:921)
[17:53:09 ERROR] [STDERR]:      at eu.decentsoftware.holograms.api.actions.ActionType$4.lambda$execute$0(ActionType.java:85)
[17:53:09 ERROR] [STDERR]:      at TRANSFORMER/arclight@1.0.0-SNAPSHOT+d0dda85/org.bukkit.craftbukkit.v1_21_R1.scheduler.CraftTask.run(CraftTask.java:82)
[17:53:09 ERROR] [STDERR]:      at TRANSFORMER/arclight@1.0.0-SNAPSHOT+d0dda85/org.bukkit.craftbukkit.v1_21_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftSchedulerMixin.java:415)
[17:53:09 ERROR] [STDERR]:      at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.handler$bbj000$arclight$runScheduler(MinecraftServerMixin_NeoForge.java:2567)
[17:53:09 ERROR] [STDERR]:      at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.tickChildren(MinecraftServerMixin_NeoForge.java)
[17:53:09 ERROR] [STDERR]:      at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServerMixin_NeoForge.java:317)
[17:53:09 ERROR] [STDERR]:      at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.tickServer(MinecraftServerMixin_NeoForge.java:917)
[17:53:09 ERROR] [STDERR]:      at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.runServer(MinecraftServerMixin_NeoForge.java:707)
[17:53:09 ERROR] [STDERR]:      at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServerMixin_NeoForge.java:267)
[17:53:09 ERROR] [STDERR]:      at java.base/java.lang.Thread.run(Thread.java:1583)
[17:53:09 ERROR] [STDERR]: java.lang.IllegalArgumentException: Can not set net.minecraft.world.item.component.ResolvableProfile field org.bukkit.craftbukkit.v1_21_R1.inventory.CraftMetaSkull.profile to com.mojang.authlib.GameProfile
[17:53:09 ERROR] [STDERR]:      at java.base/jdk.internal.reflect.FieldAccessorImpl.throwSetIllegalArgumentException(FieldAccessorImpl.java:228)
[17:53:09 ERROR] [STDERR]:      at java.base/jdk.internal.reflect.FieldAccessorImpl.throwSetIllegalArgumentException(FieldAccessorImpl.java:232)
[17:53:09 ERROR] [STDERR]:      at java.base/jdk.internal.reflect.MethodHandleObjectFieldAccessorImpl.set(MethodHandleObjectFieldAccessorImpl.java:115)
[17:53:09 ERROR] [STDERR]:      at java.base/java.lang.reflect.Field.set(Field.java:836)
[17:53:09 ERROR] [STDERR]:      at com.live.bemmamin.pocketgames.utils.ItemUtil.getSkullFromURL(ItemUtil.java:219)
[17:53:09 ERROR] [STDERR]:      at com.live.bemmamin.pocketgames.utils.ItemUtil.getSkull(ItemUtil.java:191)
[17:53:09 ERROR] [STDERR]:      at com.live.bemmamin.pocketgames.utils.ItemUtil.getItemStack(ItemUtil.java:156)
[17:53:09 ERROR] [STDERR]:      at com.live.bemmamin.pocketgames.MainGUI.setItem(MainGUI.java:138)
[17:53:09 ERROR] [STDERR]:      at com.live.bemmamin.pocketgames.MainGUI.access$200(MainGUI.java:18)
[17:53:09 ERROR] [STDERR]:      at com.live.bemmamin.pocketgames.MainGUI$1.run(MainGUI.java:129)
[17:53:09 ERROR] [STDERR]:      at TRANSFORMER/arclight@1.0.0-SNAPSHOT+d0dda85/org.bukkit.craftbukkit.v1_21_R1.scheduler.CraftTask.run(CraftTask.java:82)
[17:53:09 ERROR] [STDERR]:      at TRANSFORMER/arclight@1.0.0-SNAPSHOT+d0dda85/org.bukkit.craftbukkit.v1_21_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftSchedulerMixin.java:415)
[17:53:09 ERROR] [STDERR]:      at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.handler$bbj000$arclight$runScheduler(MinecraftServerMixin_NeoForge.java:2567)
[17:53:09 ERROR] [STDERR]:      at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.tickChildren(MinecraftServerMixin_NeoForge.java)
[17:53:09 ERROR] [STDERR]:      at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServerMixin_NeoForge.java:317)
[17:53:09 ERROR] [STDERR]:      at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.tickServer(MinecraftServerMixin_NeoForge.java:917)
[17:53:09 ERROR] [STDERR]:      at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.runServer(MinecraftServerMixin_NeoForge.java:707)
[17:53:09 ERROR] [STDERR]:      at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServerMixin_NeoForge.java:267)
[17:53:09 ERROR] [STDERR]:      at java.base/java.lang.Thread.run(Thread.java:1583)

**Comment by windy664** [comment]
![Screenshot_2024-10-03-19-37-00-554_com tencent mobileqq-edit](https://github.com/user-attachments/assets/d05990b4-fb1b-4129-bed2-5589f8eef82c)
