### ISSUE TITLE
1.15.2Arc端的存档升级到1.16.5Arc端（最新）处理 Forge 注册时出错 

### ISSUE THREAD

**Issue by xingxingchuan** [IzzelAliz/Arclight#152]
### 我正在运行

* **Arclight** [arclight-forge-1.16-1.0.12] 

* **你确认这是最新版吗** [是]

* **你确认所有Mod都安装了依赖** [是]

* **你确认所有插件都已更新至对应版本** [是]

* **Java** [openjdk version "11.0.10" 2021-01-19 LTS] 

* **操作系统** [WindowsServer2019 Datacenter]

* **插件列表** 
CoreProtect-19.4.jar
TimeIsMoney.jar
TempFly-3.0.8.jar
Shopkeepers-2.12.0.jar
AtMe-1.2@Y88G.jar
Chairs.jar
PvPManager.jar
NoDreams-1.2.1.jar
PlaceholderAPI-2.10.9.jar
HolographicDisplays.jar
ElevatorsFree.jar
ProtocolLib.jar
TitleManager-2.3.1.jar
LockettePro-2.10.8.jar
UltimateTimber-2.2.2.jar
Yum.jar
Vault.jar
NyaaCore-mc1.16.4-8.0.18.jar
NyaaUtils-mc1.16.4-8.0.11.jar
LangUtils-mc1.16.1-2.4.3.jar
NyaaBank-mc1.16.1-8.0.1.jar
Multiverse-Core-4.2.2.jar
Residence4.9.2.4.jar
LuckPerms-Bukkit-5.2.76.jar
QuickShop-4.0.6.3.jar
AuthMe-5.6.0-SNAPSHOT.jar
EssentialsXProtect-2.18.2.0.jar
EssentialsXSpawn-2.18.2.0.jar
EssentialsXChat-2.18.2.0.jar
EssentialsXAntiBuild-2.18.2.0.jar
EssentialsX-2.18.2.0.jar
MiaoChat.jar
caipiao.jar
KiloEnchant-2.0.4.jar
ColorMOTD.jar
DeluxeTags.jar
AutumnLeaves-0.0.6.jar
* **Mod 列表** 
TrackAPI-1.16.4-forge-1.2.1.jar
UniversalModCore-1.16.4-forge-1.0.1.jar
ImmersiveRailroading-1.16.4-forge-1.8.0.1.jar
curios-forge-1.16.5-4.0.4.0.jar
Kiwi-1.16.3-3.4.1.jar
ChineseWorkshop-1.16.3-3.2.0.jar
ImmersiveEngineering-1.16.5-4.2.1-131.jar
furniture-7.0.0-pre19-1.16.3.jar
Artifacts-1.16.5-2.7.6.jar
mapperbase-1.16.4-2.3.0.0.jar
roadstuff-1.16.4-4.2.0.jar
FarmersDelight-1.16.3-0.3.2.jar
trashcans-1.0.6a-mc1.16.4.jar
pamhc2foodcore-1.16.3-1.0.2.jar
car-1.16.4-1.0.5.jar

### 错误描述
我原来是1.15.2Arclight的模组服，近期在升级1.16.5的过程中，将原来在1.15.2的插件一一手动下载安装，成功启动了1.16.5的服务端。加入了模组后，也是能够正常启动。但是当我把原来的存档拷贝到新端里就无法启动。

叙述这个为什么是一个错误，是哪一方面的，以及其他可能需要的信息

### 重现步骤

1. 保持存档为原生
2. 更换老版本（1.15.2）存档

**可在 Forge 复现** [不清楚]

**可在 Spigot 复现** [不清楚]

### 报错信息

[错误日志]
有关链接：https://paste.ubuntu.com/p/DybgqXc8bx/
- [Server thread/ERROR] [Arclight/]: 处理 Forge 注册时出错 
java.lang.IllegalArgumentException: Cannot set already-set enchantment
	at org.bukkit.enchantments.Enchantment.registerEnchantment(Enchantment.java:332) ~[arclight:arclight-1.16.5-1.0.12-30c1219]
	at io.izzel.arclight.common.mod.server.BukkitRegistry.loadEnchantments(BukkitRegistry.java:185) ~[arclight:arclight-1.16.5-1.0.12-30c1219]
	at io.izzel.arclight.common.mod.server.BukkitRegistry.registerAll(BukkitRegistry.java:77) ~[arclight:arclight-1.16.5-1.0.12-30c1219]
	at io.izzel.arclight.common.mod.server.ArclightServer.createOrLoad(ArclightServer.java:38) ~[arclight:arclight-1.16.5-1.0.12-30c1219]
	at net.minecraft.server.management.PlayerList.handler$bab000$arclight$loadServer(PlayerListMixin.java:1023) ~[?:?]
	at net.minecraft.server.management.PlayerList.<init>(PlayerListMixin.java:120) ~[?:?]
	at net.minecraft.server.dedicated.DedicatedPlayerList.<init>(SourceFile:16) ~[?:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServerMixin.java:160) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServerMixin.java:1857) ~[?:?]
	at net.minecraft.server.MinecraftServer.lambda$startServer$0(MinecraftServerMixin.java:232) ~[?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]

-  [net.minecraft.server.MinecraftServer/]: Encountered an unexpected exception
java.lang.NullPointerException: null
	at org.spigotmc.SpigotWorldConfig.getBoolean(SpigotWorldConfig.java:44) ~[arclight:arclight-1.16.5-1.0.12-30c1219]
	at org.spigotmc.SpigotWorldConfig.init(SpigotWorldConfig.java:23) ~[arclight:arclight-1.16.5-1.0.12-30c1219]
	at org.spigotmc.SpigotWorldConfig.<init>(SpigotWorldConfig.java:18) ~[arclight:arclight-1.16.5-1.0.12-30c1219]
	at net.minecraft.world.World.handler$bbi000$arclight$init(WorldMixin.java:1252) ~[?:?]
	at net.minecraft.world.World.<init>(WorldMixin.java:123) ~[?:?]
	at net.minecraft.world.server.ServerWorld.<init>(ServerWorldMixin.java:179) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240787_a_(MinecraftServerMixin.java:335) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240800_l__(MinecraftServerMixin.java:308) ~[?:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServerMixin.java:168) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServerMixin.java:1857) ~[?:?]
	at net.minecraft.server.MinecraftServer.lambda$startServer$0(MinecraftServerMixin.java:232) ~[?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]

[Server console handler/DEBUG] [org.jline/]: Error registering default handler for signal WINCH
java.lang.reflect.InvocationTargetException: null
	at jdk.internal.reflect.GeneratedConstructorAccessor61.newInstance(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:490) ~[?:?]
	at org.jline.utils.Signals.doRegister(Signals.java:93) ~[jline-3.12.1.jar:?]
	at org.jline.utils.Signals.registerDefault(Signals.java:67) [jline-3.12.1.jar:?]
	at org.jline.terminal.impl.AbstractWindowsTerminal.handle(AbstractWindowsTerminal.java:152) [jline-3.12.1.jar:?]
	at org.jline.reader.impl.LineReaderImpl.readLine(LineReaderImpl.java:656) [jline-3.12.1.jar:?]
	at org.jline.reader.impl.LineReaderImpl.readLine(LineReaderImpl.java:418) [jline-3.12.1.jar:?]
	at net.minecraftforge.server.console.TerminalHandler.handleCommands(TerminalHandler.java:60) [forge:?]
	at net.minecraft.server.dedicated.DedicatedServer$1.run(DedicatedServer.java:84) [?:?]
Caused by: java.lang.IllegalArgumentException: Unknown signal: WINCH
	at jdk.internal.misc.Signal.<init>(Signal.java:148) ~[?:?]
	at sun.misc.Signal.<init>(Signal.java:139) ~[?:?]
	... 10 more
[032月2021 18:06:43.704] [Server console handler/DEBUG] [org.jline/]: Error registering default handler for signal CONT
java.lang.reflect.InvocationTargetException: null
	at jdk.internal.reflect.GeneratedConstructorAccessor61.newInstance(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:490) ~[?:?]
	at org.jline.utils.Signals.doRegister(Signals.java:93) ~[jline-3.12.1.jar:?]
	at org.jline.utils.Signals.registerDefault(Signals.java:67) [jline-3.12.1.jar:?]
	at org.jline.terminal.impl.AbstractWindowsTerminal.handle(AbstractWindowsTerminal.java:152) [jline-3.12.1.jar:?]
	at org.jline.reader.impl.LineReaderImpl.readLine(LineReaderImpl.java:659) [jline-3.12.1.jar:?]
	at org.jline.reader.impl.LineReaderImpl.readLine(LineReaderImpl.java:418) [jline-3.12.1.jar:?]
	at net.minecraftforge.server.console.TerminalHandler.handleCommands(TerminalHandler.java:60) [forge:?]
	at net.minecraft.server.dedicated.DedicatedServer$1.run(DedicatedServer.java:84) [?:?]
Caused by: java.lang.IllegalArgumentException: Unknown signal: CONT
	at jdk.internal.misc.Signal.<init>(Signal.java:148) ~[?:?]
	at sun.misc.Signal.<init>(Signal.java:139) ~[?:?]
	... 10 more

有劳Arclight的开发团队解决

**Comment by xingxingchuan** [comment]
不小心忘记贴出crashreport的地址了
https://paste.ubuntu.com/p/kCp3BJRJFg/

**Comment by IzzelAliz** [comment]
请提供 debug.log，如果有可能的话请二分找出导致注册出错的模组。

crashreport 中的问题与 issue 无关，删除 spigot.yml 即可

**Comment by xingxingchuan** [comment]
debug.log已经给出了 地址是 https://paste.ubuntu.com/p/DybgqXc8bx/
当我把模组全部删除了也会同样出现这个错误 导致无法启动

**Comment by xingxingchuan** [comment]
这个是存档文件 https://victoriaca-my.sharepoint.com/:u:/g/personal/chaitanyayang_ncov_office_gy/EYSFy7pirzxNu2IDob7cKukBqBk_bb3aastf3EQvFXJHaw?e=fTzXSV
在客户端中是可以正常启动的

**Comment by IzzelAliz** [comment]
请测试最新版是否修复

**Comment by xingxingchuan** [comment]
已测试，问题未解决 报错仍旧

**Comment by IzzelAliz** [comment]
报错贴出来

**Comment by xingxingchuan** [comment]
log
https://paste.ubuntu.com/p/ZZQ5MyrPFF/
crash report
https://paste.ubuntu.com/p/VsSdykXjnr/

**Comment by IzzelAliz** [comment]
你根本就没更新

https://ci.appveyor.com/project/IzzelAliz/arclight-16

**Comment by xingxingchuan** [comment]
不好意思，我以为是在github release里的最新版本
经过测试，服务器能够正常启动了，能够正常游玩
感谢修复BUG
