### ISSUE TITLE
[ 1.21.1 - Neoforge ] 使用CMI插件调时间、天气错误

### ISSUE THREAD

**Issue by windy664** [IzzelAliz/Arclight#1521]
### I have confirmed that ...

- [X] Arclight is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Forge

### Arclight version

arclight-neoforge-1.21.1-1.0.0-SNAPSHOT

### OS & Java versions

Java21

### Plugins and Mods

```raw
CMI CMIlib
```

### Description

输入/day (CMI的指令) 天气和时间一直刷新 一直刷新 

### Logs

[0610月2024 22:44:02.779] [Server thread/WARN] [CMILib/]: Task #5208 for CMILib v1.5.0.5 generated an exception
java.lang.IllegalAccessError: class org.bukkit.craftbukkit.v1_21_R1.CraftWorld tried to access abstract protected method 'void net.minecraft.world.level.GameRules$Value.deserialize(java.lang.String)' (org.bukkit.craftbukkit.v1_21_R1.CraftWorld is in module arclight@1.0.0-SNAPSHOT+d0dda85 of loader 'TRANSFORMER' @f9cab00; net.minecraft.world.level.GameRules$Value is in module minecraft@1.21.1 of loader 'TRANSFORMER' @f9cab00)
	at TRANSFORMER/arclight@1.0.0-SNAPSHOT+d0dda85/org.bukkit.craftbukkit.v1_21_R1.CraftWorld.setGameRuleValue(CraftWorldMixin.java:1771) ~[arclight-1.21.1-1.0.0-SNAPSHOT-d0dda85.jar%23276!/:arclight-1.21.1-1.0.0-SNAPSHOT-d0dda85] {re:mixin,re:computing_frames,re:classloading,pl:mixin:APP:mixins.arclight.neoforge.json:bukkit.CraftWorldMixin_NeoForge from mod (unknown),pl:mixin:APP:mixins.arclight.bukkit.json:CraftWorldMixin from mod (unknown),pl:mixin:A,re:mixin,re:mixin}
	at com.Zrips.CMI.utils.TimeManager.lambda$6(TimeManager.java:342) ~[?:?] {}
	at TRANSFORMER/arclight@1.0.0-SNAPSHOT+d0dda85/org.bukkit.craftbukkit.v1_21_R1.scheduler.CraftTask.run(CraftTask.java:82) ~[arclight-1.21.1-1.0.0-SNAPSHOT-d0dda85.jar%23276!/:arclight-1.21.1-1.0.0-SNAPSHOT-d0dda85] {re:classloading}
	at TRANSFORMER/arclight@1.0.0-SNAPSHOT+d0dda85/org.bukkit.craftbukkit.v1_21_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftSchedulerMixin.java:415) ~[arclight-1.21.1-1.0.0-SNAPSHOT-d0dda85.jar%23276!/:arclight-1.21.1-1.0.0-SNAPSHOT-d0dda85] {re:mixin,re:classloading,pl:mixin:APP:mixins.arclight.bukkit.json:CraftSchedulerMixin from mod (unknown),pl:mixin:A,re:mixin}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.handler$bbj000$arclight$runScheduler(MinecraftServerMixin_NeoForge.java:2567) ~[server-1.21.1-20240808.144430-srg.jar%23274!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A,re:mixin,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.tickChildren(MinecraftServerMixin_NeoForge.java) ~[server-1.21.1-20240808.144430-srg.jar%23274!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A,re:mixin,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServerMixin_NeoForge.java:317) ~[server-1.21.1-20240808.144430-srg.jar%23274!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.dedicated.DedicatedServerMixin from mod (unknown),pl:mixin:APP:mixins.arclight.neoforge.json:core.server.dedicated.DedicatedServerMixin_NeoForge from mod (unknown),pl:mixin:A,re:mixin,pl:accesstransformer:B}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.tickServer(MinecraftServerMixin_NeoForge.java:917) ~[server-1.21.1-20240808.144430-srg.jar%23274!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A,re:mixin,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.runServer(MinecraftServerMixin_NeoForge.java:707) ~[server-1.21.1-20240808.144430-srg.jar%23274!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A,re:mixin,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServerMixin_NeoForge.java:267) ~[server-1.21.1-20240808.144430-srg.jar%23274!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A,re:mixin,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at java.base/java.lang.Thread.run(Thread.java:1583) [?:?] {re:mixin,re:mixin,re:mixin}

**Comment by qyl27** [comment]
我刚才使用CMILib 1.5.1.4和CMI 9.7.6.6没能复现
