### ISSUE TITLE
Broken dimensions in Pixelmon Mod

### ISSUE THREAD

**Issue by NatNATTO** [IzzelAliz/Arclight#1529]
### I have confirmed that ...

- [X] Arclight is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Forge

### Arclight version

Arclight-forge-1.20.2-1.0.3

### OS & Java versions

openjdk version "21.0.4" 2024-07-16 LTS

### Plugins and Mods

```raw
Mods:

Pixelmon-1.20.2-9.2.7-universal
BiomesOPlenty-1.20.2-18.2.0.53
TerraBlender-forge-1.20.2-3.0.0.171


Plugins:
BukkitPixelmonPlaceholders-1.2.2
ChatInjector-1.0.3
ChatLoader-3.2.1
Economy 2.3
EssentialsX-2.21.0-dev
EssentialsXChat-2.21.0-dev
EverNifeCore-2.0.4.1
griefdefender-bukkit-3.0.0
ItemFrameShops 7.0.0
LuckPerms-Bukkit-5.4.139
PixelmonEconomyBridge-1.1.4
PlaceholderAPI-2.11.6
ProtocolLib
Vault
Worldedit-bukkit-7.2.18-dist
```

### Description

In order to reproduce this error, all you need installed on your server is Arclight-forge-1.20.2-1.0.3 and Pixelmon-1.20.2-9.2.7
_(This error also happens with versions 1.0.2 and 1.0.1 of Arclight-forge-1.20.2)_

While in game the player crashes if they enter a pixelmon portal to another dimension. The crash tells the player they were "timed out" and the server log says they "Player disconnected after X ticks" ... If they log back in they are still on the portal and will crash again, the player has to wait for the portal to despawn or for a Mod to save them.

Conveniently, Pixelmon includes an item you can right click with to warp to the dimensions included with the mod. In this case the player does not crash however we get an ERROR in the client log shown below...

 

> [21:14:38 ERROR]: Failed to handle packet net.minecraft.network.protocol.game.ServerboundUseItemPacket@caf9981, suppressing error
> java.lang.ClassCastException: class net.minecraft.server.dedicated.DedicatedPlayerList cannot be cast to class net.minecraft.server.level.ServerPlayer (net.minecraft.server.dedicated.DedicatedPlayerList and net.minecraft.server.level.ServerPlayer are in module minecraft@1.20.2 of loader 'TRANSFORMER' @5f366587)
>         at net.minecraft.server.players.PlayerList.respawn(PlayerListMixin.java:1176) ~[server-1.20.2-20230921.100330-srg.jar%23165!/:?]
>         at org.bukkit.craftbukkit.v1_20_R2.entity.CraftPlayer.teleport(CraftPlayerMixin.java:964) ~[arclight-1.20.2-1.0.3-5abaeaf.jar%23160!/:arclight-1.20.2-1.0.3-5abaeaf]
>         at net.minecraft.server.level.ServerPlayer.handler$zjm000$arclight$handleBy(ServerPlayerMixin.java:2652) ~[server-1.20.2-20230921.100330-srg.jar%23165!/:?]
>         at net.minecraft.server.level.ServerPlayer.m_8999_(ServerPlayerMixin.java:1443) ~[server-1.20.2-20230921.100330-srg.jar%23165!/:?]
>         at com.pixelmonmod.pixelmon.api.util.helpers.DimensionHelper.lambda$teleport$0(DimensionHelper.java:53) ~[Pixelspoofy-1.20.2-9.2.7-universal.jar%23162!/:?]
>         at java.util.Optional.ifPresent(Optional.java:178) ~[?:?]
>         at com.pixelmonmod.pixelmon.api.util.helpers.DimensionHelper.teleport(DimensionHelper.java:40) ~[Pixelspoofy-1.20.2-9.2.7-universal.jar%23162!/:?]
>         at com.pixelmonmod.pixelmon.api.util.helpers.DimensionHelper.teleport(DimensionHelper.java:25) ~[Pixelspoofy-1.20.2-9.2.7-universal.jar%23162!/:?]
>         at com.pixelmonmod.pixelmon.items.TeleporterItem.doTeleport(TeleporterItem.java:56) ~[Pixelspoofy-1.20.2-9.2.7-universal.jar%23162!/:?]
>         at com.pixelmonmod.pixelmon.items.TeleporterItem.m_7203_(TeleporterItem.java:39) ~[Pixelspoofy-1.20.2-9.2.7-universal.jar%23162!/:?]
>         at net.minecraft.world.item.ItemStack.m_41682_(ItemStackMixin.java:280) ~[server-1.20.2-20230921.100330-srg.jar%23165!/:?]
>         at net.minecraft.server.level.ServerPlayerGameMode.m_6261_(ServerPlayerGameModeMixin.java:286) ~[server-1.20.2-20230921.100330-srg.jar%23165!/:?]
>         at net.minecraft.server.network.ServerGamePacketListenerImpl.m_5760_(ServerPlayNetHandlerMixin.java:2595) ~[server-1.20.2-20230921.100330-srg.jar%23165!/:?]
>         at net.minecraft.network.protocol.game.ServerboundUseItemPacket.m_5797_(CPlayerTryUseItemPacketMixin.java:29) ~[server-1.20.2-20230921.100330-srg.jar%23165!/:?]
>         at net.minecraft.network.protocol.game.ServerboundUseItemPacket.m_5797_(CPlayerTryUseItemPacketMixin.java:7) ~[server-1.20.2-20230921.100330-srg.jar%23165!/:?]
>         at net.minecraft.network.protocol.PacketUtils.md6369a1$lambda$ensureRunningOnSameThread$0$0(PacketThreadUtilMixin.java:537) ~[server-1.20.2-20230921.100330-srg.jar%23165!/:?]
>         at net.minecraft.server.TickTask.run(TickTask.java:18) ~[server-1.20.2-20230921.100330-srg.jar%23165!/:?]
>         at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:156) ~[server-1.20.2-20230921.100330-srg.jar%23165!/:?]
>         at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[server-1.20.2-20230921.100330-srg.jar%23165!/:?]
>         at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServerMixin.java:765) ~[server-1.20.2-20230921.100330-srg.jar%23165!/:?]
>         at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServerMixin.java:160) ~[server-1.20.2-20230921.100330-srg.jar%23165!/:?]
>         at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:130) ~[server-1.20.2-20230921.100330-srg.jar%23165!/:?]
>         at net.minecraft.server.MinecraftServer.m_129961_(MinecraftServerMixin.java:748) ~[server-1.20.2-20230921.100330-srg.jar%23165!/:?]
>         at net.minecraft.server.MinecraftServer.m_7245_(MinecraftServerMixin.java:742) ~[server-1.20.2-20230921.100330-srg.jar%23165!/:?]
>         at net.minecraft.util.thread.BlockableEventLoop.m_18701_(BlockableEventLoop.java:139) ~[server-1.20.2-20230921.100330-srg.jar%23165!/:?]
>         at net.minecraft.server.MinecraftServer.m_130012_(MinecraftServerMixin.java:728) ~[server-1.20.2-20230921.100330-srg.jar%23165!/:?]
>         at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServerMixin.java:2081) ~[server-1.20.2-20230921.100330-srg.jar%23165!/:?]
>         at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServerMixin.java:249) ~[server-1.20.2-20230921.100330-srg.jar%23165!/:?]
>         at java.lang.Thread.run(Thread.java:1583) ~[?:?]
        

This is game breaking as some features and content used in the other dimensions are unobtainable in other parts of gameplay and has proven to be quite a hinderance on my server for a few updates of both pixelmon and arclight and I would love to see it get some attention because Arclight is absolutely amazing! 
        

### Step to reproduce

In order to reproduce this error, all you need installed on your server is Arclight-forge-1.20.2-1.0.3 and Pixelmon-1.20.2-9.2.7

Load into the server and enter an "Ultra Space Wormhole" they spawn randomly around the world in the sky, they can also be spawned with commands /summon @e[type=pixelmon:ultra_space_wormhole]

You will crash due to a timeout. Server log will say the "PLAYER has disconnected after X ticks"

You can attempt to enter into Ultraspace using an alternative route such as the teleporter item. Open your creative inventory and get the "Ultra Space Teleporter" item, and right click. You will not get teleported to Ultraspace, you will not crash, but the server log will produce a packet error.

### Logs

[latest.log](https://github.com/user-attachments/files/17371095/latest.log)

ERROR is produced at timestamp 21:14:38.915

**Comment by lllWinchesterlll** [comment]
The problem also occurs if we use some plugin to create other worlds, when trying to teleport to another world the game only shows an error, a developer of one of the teleport plugins, said that Bukkit teleport() function is broken, I don't understand anything about it but I hope it can be solved in version 1.20.2, pixelmon game and that's the last supported version, please if you can fix it
