### ISSUE TITLE
Libreforge error (api related to EcoPlugins)

### ISSUE THREAD

**Issue by gdadamx** [IzzelAliz/Arclight#1553]
### I have confirmed that ...

- [X] Arclight is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Forge

### Arclight version

arclight-1.21.1-1.0.0-SNAPSHOT-1732a9b

### OS & Java versions

Java HotSpot (TM) 64Bit Server VM (build 21.0.4+8-LTS274, mixed mode, sharing)

### Plugins and Mods

```raw
Eco 6.74.3
Libreforge 4.72.2
Reforges 6.71.2
```

### Description

Error occurs when enabling libreforge, a library for EcoPlugins (EcoItems,etc...)

### Step to reproduce

1. Install Reforges + Eco
2. Log errors, plugin doesn't start

### Logs

[15Nov2024 15:13:00.620] [Server thread/INFO] [PlaceholderAPI/]: Successfully registered internal expansion: libreforge [4.72.2]
[15Nov2024 15:13:00.728] [Server thread/ERROR] [Minecraft/]: Error occurred while enabling libreforge v4.72.2 (Is it up to date?)
java.lang.ExceptionInInitializerError: null
	at com.willfp.libreforge.effects.Effects.<clinit>(Effects.kt:473) ~[?:?] {}
	at com.willfp.libreforge.integrations.vault.VaultIntegration.load(VaultIntegration.kt:16) ~[?:?] {}
	at com.willfp.libreforge.LibreforgeSpigotPlugin.loadIntegrationLoaders$lambda$11(LibreforgeSpigotPlugin.kt:192) ~[?:?] {}
	at com.willfp.eco.core.integrations.IntegrationLoader.load(IntegrationLoader.java:60) ~[?:?] {}
	at com.willfp.eco.core.EcoPlugin.lambda$onEnable$1(EcoPlugin.java:414) ~[?:?] {}
	at java.base/java.util.Arrays$ArrayList.forEach(Arrays.java:4305) ~[?:?] {}
	at com.willfp.eco.core.EcoPlugin.onEnable(EcoPlugin.java:411) ~[?:?] {}
	at TRANSFORMER/arclight@1.0.0-SNAPSHOT+1732a9b/org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPluginMixin.java:267) ~[arclight-1.21.1-1.0.0-SNAPSHOT-1732a9b.jar%23252!/:arclight-1.21.1-1.0.0-SNAPSHOT-1732a9b] {re:mixin,re:classloading,pl:mixin:APP:mixins.arclight.bukkit.json:JavaPluginMixin from mod (unknown),pl:mixin:A,re:mixin,re:mixin}
	at TRANSFORMER/arclight@1.0.0-SNAPSHOT+1732a9b/org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoaderMixin.java:342) ~[arclight-1.21.1-1.0.0-SNAPSHOT-1732a9b.jar%23252!/:arclight-1.21.1-1.0.0-SNAPSHOT-1732a9b] {re:mixin,re:classloading,pl:mixin:APP:mixins.arclight.bukkit.json:JavaPluginLoaderMixin from mod (unknown),pl:mixin:A}
	at TRANSFORMER/arclight@1.0.0-SNAPSHOT+1732a9b/org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:492) ~[arclight-1.21.1-1.0.0-SNAPSHOT-1732a9b.jar%23252!/:arclight-1.21.1-1.0.0-SNAPSHOT-1732a9b] {re:mixin,re:classloading,re:mixin}
	at TRANSFORMER/arclight@1.0.0-SNAPSHOT+1732a9b/org.bukkit.craftbukkit.v1_21_R1.CraftServer.enablePlugin(CraftServerMixin.java:576) ~[arclight-1.21.1-1.0.0-SNAPSHOT-1732a9b.jar%23252!/:arclight-1.21.1-1.0.0-SNAPSHOT-1732a9b] {re:mixin,re:classloading,pl:mixin:APP:mixins.arclight.neoforge.json:bukkit.CraftServerMixin_NeoForge from mod (unknown),pl:mixin:APP:mixins.arclight.bukkit.json:CraftServerMixin from mod (unknown),pl:mixin:A,re:mixin,re:mixin,re:mixin}
	at TRANSFORMER/arclight@1.0.0-SNAPSHOT+1732a9b/org.bukkit.craftbukkit.v1_21_R1.CraftServer.enablePlugins(CraftServerMixin.java:490) ~[arclight-1.21.1-1.0.0-SNAPSHOT-1732a9b.jar%23252!/:arclight-1.21.1-1.0.0-SNAPSHOT-1732a9b] {re:mixin,re:classloading,pl:mixin:APP:mixins.arclight.neoforge.json:bukkit.CraftServerMixin_NeoForge from mod (unknown),pl:mixin:APP:mixins.arclight.bukkit.json:CraftServerMixin from mod (unknown),pl:mixin:A,re:mixin,re:mixin,re:mixin}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.handler$ben000$arclight$enablePlugins(MinecraftServerMixin_NeoForge.java:2385) ~[server-1.21.1-20240808.144430-srg.jar%23250!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,xf:fml:xaerominimap:xaero_minecraftserver,pl:connector_pre_launch:A,re:classloading,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,xf:fml:xaerominimap:xaero_minecraftserver,pl:mixin:A,pl:connector_pre_launch:A,re:mixin,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,xf:fml:xaerominimap:xaero_minecraftserver,pl:connector_pre_launch:A}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.createLevels(MinecraftServerMixin_NeoForge.java:430) ~[server-1.21.1-20240808.144430-srg.jar%23250!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,xf:fml:xaerominimap:xaero_minecraftserver,pl:connector_pre_launch:A,re:classloading,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,xf:fml:xaerominimap:xaero_minecraftserver,pl:mixin:A,pl:connector_pre_launch:A,re:mixin,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,xf:fml:xaerominimap:xaero_minecraftserver,pl:connector_pre_launch:A}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.loadLevel(MinecraftServerMixin_NeoForge.java:337) ~[server-1.21.1-20240808.144430-srg.jar%23250!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,xf:fml:xaerominimap:xaero_minecraftserver,pl:connector_pre_launch:A,re:classloading,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,xf:fml:xaerominimap:xaero_minecraftserver,pl:mixin:A,pl:connector_pre_launch:A,re:mixin,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,xf:fml:xaerominimap:xaero_minecraftserver,pl:connector_pre_launch:A}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServerMixin_NeoForge.java:193) ~[server-1.21.1-20240808.144430-srg.jar%23250!/:?] {re:mixin,pl:accesstransformer:B,pl:connector_pre_launch:A,re:computing_frames,pl:accesstransformer:B,pl:connector_pre_launch:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.dedicated.DedicatedServerMixin from mod (unknown),pl:mixin:APP:mixins.arclight.neoforge.json:core.server.dedicated.DedicatedServerMixin_NeoForge from mod (unknown),pl:mixin:A,pl:connector_pre_launch:A,re:mixin,pl:accesstransformer:B,pl:connector_pre_launch:A,re:mixin,pl:accesstransformer:B,pl:connector_pre_launch:A}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.runServer(MinecraftServerMixin_NeoForge.java:670) ~[server-1.21.1-20240808.144430-srg.jar%23250!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,xf:fml:xaerominimap:xaero_minecraftserver,pl:connector_pre_launch:A,re:classloading,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,xf:fml:xaerominimap:xaero_minecraftserver,pl:mixin:A,pl:connector_pre_launch:A,re:mixin,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,xf:fml:xaerominimap:xaero_minecraftserver,pl:connector_pre_launch:A}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServerMixin_NeoForge.java:267) ~[server-1.21.1-20240808.144430-srg.jar%23250!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,xf:fml:xaerominimap:xaero_minecraftserver,pl:connector_pre_launch:A,re:classloading,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,xf:fml:xaerominimap:xaero_minecraftserver,pl:mixin:A,pl:connector_pre_launch:A,re:mixin,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,xf:fml:xaerominimap:xaero_minecraftserver,pl:connector_pre_launch:A}
	at java.base/java.lang.Thread.run(Thread.java:1583) [?:?] {re:mixin,re:mixin,re:mixin,re:mixin}
Caused by: java.lang.IllegalArgumentException: Cannot copy null stack
	at MC-BOOTSTRAP/com.google.common@32.1.2-jre/com.google.common.base.Preconditions.checkArgument(Preconditions.java:143) ~[guava-32.1.2-jre.jar%23115!/:?] {re:mixin}
	at TRANSFORMER/arclight@1.0.0-SNAPSHOT+1732a9b/org.bukkit.inventory.ItemStack.<init>(ItemStack.java:113) ~[arclight-1.21.1-1.0.0-SNAPSHOT-1732a9b.jar%23252!/:arclight-1.21.1-1.0.0-SNAPSHOT-1732a9b] {re:mixin,re:classloading,pl:arclight_implementer:inventory,pl:arclight_implementer:A,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin}
	at TRANSFORMER/arclight@1.0.0-SNAPSHOT+1732a9b/org.bukkit.inventory.CraftingRecipe.<init>(CraftingRecipe.java:23) ~[arclight-1.21.1-1.0.0-SNAPSHOT-1732a9b.jar%23252!/:arclight-1.21.1-1.0.0-SNAPSHOT-1732a9b] {re:mixin,re:computing_frames,re:classloading,re:mixin}
	at TRANSFORMER/arclight@1.0.0-SNAPSHOT+1732a9b/org.bukkit.craftbukkit.v1_21_R1.inventory.CraftComplexRecipe.<init>(CraftComplexRecipe.java:17) ~[arclight-1.21.1-1.0.0-SNAPSHOT-1732a9b.jar%23252!/:arclight-1.21.1-1.0.0-SNAPSHOT-1732a9b] {re:mixin,re:classloading}
	at TRANSFORMER/arclight@1.0.0-SNAPSHOT+1732a9b/io.izzel.arclight.common.mod.util.ArclightSpecialRecipe.<init>(ArclightSpecialRecipe.java:20) ~[arclight-1.21.1-1.0.0-SNAPSHOT-1732a9b.jar%23252!/:arclight-1.21.1-1.0.0-SNAPSHOT-1732a9b] {re:mixin,re:classloading}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.item.crafting.Recipe.bridge$toBukkitRecipe(RecipeMixin.java:518) ~[server-1.21.1-20240808.144430-srg.jar%23250!/:?] {re:mixin,pl:connector_pre_launch:A,re:classloading,pl:mixin:APP:mixins.arclight.core.json:world.item.crafting.RecipeMixin from mod (unknown),pl:mixin:A,pl:connector_pre_launch:A}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.item.crafting.RecipeHolder.toBukkitRecipe(RecipeHolderMixin.java:525) ~[server-1.21.1-20240808.144430-srg.jar%23250!/:?] {re:mixin,pl:connector_pre_launch:A,re:classloading,pl:mixin:APP:mixins.arclight.core.json:world.item.crafting.RecipeHolderMixin from mod (unknown),pl:mixin:APP:quality_food.mixins.json:RecipeHolderMixin from mod quality_food,pl:mixin:A,pl:connector_pre_launch:A}
	at TRANSFORMER/arclight@1.0.0-SNAPSHOT+1732a9b/org.bukkit.craftbukkit.v1_21_R1.inventory.RecipeIterator.next(RecipeIterator.java:24) ~[arclight-1.21.1-1.0.0-SNAPSHOT-1732a9b.jar%23252!/:arclight-1.21.1-1.0.0-SNAPSHOT-1732a9b] {re:classloading}
	at TRANSFORMER/arclight@1.0.0-SNAPSHOT+1732a9b/org.bukkit.craftbukkit.v1_21_R1.inventory.RecipeIterator.next(RecipeIterator.java:10) ~[arclight-1.21.1-1.0.0-SNAPSHOT-1732a9b.jar%23252!/:arclight-1.21.1-1.0.0-SNAPSHOT-1732a9b] {re:classloading}
	at com.willfp.libreforge.effects.impl.EffectAutosmelt.<clinit>(EffectAutosmelt.kt:40) ~[?:?] {}
	... 19 more

**Comment by qyl27** [comment]
Related to #1550, work in progress.
