### ISSUE TITLE
Crash while starting up the server

### ISSUE THREAD

**Issue by smilee1010** [IzzelAliz/Arclight#1569]
### I have confirmed that ...

- [X] Arclight is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Forge

### Arclight version

arclight-fabric-1.21-1.0.0-SNAPSHOT

### OS & Java versions

OS: Windows 11 23H2 x64 Java version: 21

### Plugins and Mods

```raw
Plugins (1): TrainCarts
Mods (6): Fabric api 0.102.0, FarmersDelight-1.21-2.1.9+refabricated, movingelevators-1.4.9-fabric-mc1.21, refurbished_furniture-fabric-1.21-1.0.6, supermartijn642configlib-1.1.8-fabric-mc1.21, supermartijn642corelib-1.1.17c-fabric-mc1.21
Framework 0.9.1
```

### Description

I have no idea why this is happening,

### Step to reproduce

1. Make a server and install Arclight
2. Install the mods and plugin
3. Start the server

### Logs

[main/INFO] [FabricLoader/GameProvider/]: Loading Minecraft 1.21 Arclight arclight-1.21-1.0.0-SNAPSHOT-b3349e9 with Fabric Loader 0.15.11
mainEx[2111월2024 14:09:28.021] [main/INFO] [FabricLoader/]: Loading 75 mods:
	- arclight 1.0.0-SNAPSHOT+b3349e9
	- fabric-api 0.102.0+1.21
	   |-- fabric-api-base 0.4.42+6573ed8cd1
	   |-- fabric-api-lookup-api-v1 1.6.68+b5597344d1
	   |-- fabric-biome-api-v1 13.0.29+5bd9f1bcd1
	   |-- fabric-block-api-v1 1.0.22+0af3f5a7d1
	   |-- fabric-block-view-api-v2 1.0.10+6573ed8cd1
	   |-- fabric-blockrenderlayer-v1 1.1.52+0af3f5a7d1
	   |-- fabric-client-tags-api-v1 1.1.15+6573ed8cd1
	   |-- fabric-command-api-v1 1.2.49+f71b366fd1
	   |-- fabric-command-api-v2 2.2.28+6ced4dd9d1
	   |-- fabric-commands-v0 0.2.66+df3654b3d1
	   |-- fabric-content-registries-v0 8.0.16+b5597344d1
	   |-- fabric-convention-tags-v1 2.0.19+7f945d5bd1
	   |-- fabric-convention-tags-v2 2.5.0+c5e2b5c6d1
	   |-- fabric-crash-report-info-v1 0.2.29+0af3f5a7d1
	   |-- fabric-data-attachment-api-v1 1.1.27+6a6dfa19d1
	   |-- fabric-data-generation-api-v1 20.2.16+16c4ae25d1
	   |-- fabric-dimensions-v1 4.0.0+6fc22b99d1
	   |-- fabric-entity-events-v1 1.6.12+6fc22b99d1
	   |-- fabric-events-interaction-v0 0.7.12+ba9dae06d1
	   |-- fabric-game-rule-api-v1 1.0.53+6ced4dd9d1
	   |-- fabric-item-api-v1 11.0.0+afdfc921d1
	   |-- fabric-item-group-api-v1 4.1.4+78017270d1
	   |-- fabric-key-binding-api-v1 1.0.47+0af3f5a7d1
	   |-- fabric-keybindings-v0 0.2.45+df3654b3d1
	   |-- fabric-lifecycle-events-v1 2.3.12+6c1df360d1
	   |-- fabric-loot-api-v2 3.0.14+3f89f5a5d1
	   |-- fabric-loot-api-v3 1.0.2+3f89f5a5d1
	   |-- fabric-message-api-v1 6.0.13+6573ed8cd1
	   |-- fabric-model-loading-api-v1 2.0.0+fe474d6bd1
	   |-- fabric-networking-api-v1 4.2.2+60c3209bd1
	   |-- fabric-object-builder-api-v1 15.2.0+a551f7a4d1
	   |-- fabric-particles-v1 4.0.2+6573ed8cd1
	   |-- fabric-recipe-api-v1 5.0.12+65089712d1
	   |-- fabric-registry-sync-v0 5.1.2+60c3209bd1
	   |-- fabric-renderer-api-v1 3.4.0+c705a49cd1
	   |-- fabric-renderer-indigo 1.7.0+c705a49cd1
	   |-- fabric-renderer-registries-v1 3.2.68+df3654b3d1
	   |-- fabric-rendering-data-attachment-v1 0.3.48+73761d2ed1
	   |-- fabric-rendering-fluids-v1 3.1.6+b5597344d1
	   |-- fabric-rendering-v0 1.1.71+df3654b3d1
	   |-- fabric-rendering-v1 5.0.5+df16efd0d1
	   |-- fabric-resource-conditions-api-v1 4.3.0+8dc279b1d1
	   |-- fabric-resource-loader-v0 1.3.0+56599129d1
	   |-- fabric-screen-api-v1 2.0.24+b5597344d1
	   |-- fabric-screen-handler-api-v1 1.3.86+b5597344d1
	   |-- fabric-sound-api-v1 1.0.23+6573ed8cd1
	   |-- fabric-transfer-api-v1 5.1.16+3dccd343d1
	   \-- fabric-transitive-access-wideners-v1 6.1.0+176f9036d1
	- fabricloader 0.15.11
	- farmersdelight 1.21-2.1.9+refabricated
	   |-- mm 2.3
	   |-- porting_lib_base 3.1.0-beta+fdrf.1+1.21
	   |    |-- com_electronwill_night-config_core 3.8.0
	   |    |-- com_electronwill_night-config_toml 3.8.0
	   |    |-- mixinextras 0.4.0-beta.2
	   |    |-- mm 2.3
	   |    |-- porting_lib_accessors 3.1.0-beta+fdrf.1+1.21
	   |    |-- porting_lib_asm 3.1.0-beta+fdrf.1+1.21
	   |    |-- porting_lib_attributes 3.1.0-beta+fdrf.1+1.21
	   |    |-- porting_lib_blocks 3.1.0-beta+fdrf.1+1.21
	   |    |-- porting_lib_common 3.1.0-beta+fdrf.1+1.21
	   |    |-- porting_lib_core 3.1.0-beta+fdrf.1+1.21
	   |    |-- porting_lib_entity 3.1.0-beta+fdrf.1+1.21
	   |    |-- porting_lib_extensions 3.1.0-beta+fdrf.1+1.21
	   |    |-- porting_lib_fluids 3.1.0-beta+fdrf.1+1.21
	   |    |-- porting_lib_gametest 3.1.0-beta+fdrf.1+1.21
	   |    |-- porting_lib_gui_utils 3.1.0-beta+fdrf.1+1.21
	   |    |-- porting_lib_mixin_extensions 3.1.0-beta+fdrf.1+1.21
	   |    |-- porting_lib_tags 3.0
	   |    \-- porting_lib_transfer 3.1.0-beta+fdrf.1+1.21
	   |-- porting_lib_config 3.1.0-beta+fdrf.1+1.21
	   |    |-- com_electronwill_night-config_core 3.8.0
	   |    |-- com_electronwill_night-config_toml 3.8.0
	   |    |-- mixinextras 0.4.0-beta.2
	   |    |-- porting_lib_core 3.1.0-beta+fdrf.1+1.21
	   |    \-- porting_lib_gametest 3.1.0-beta+fdrf.1+1.21
	   |-- porting_lib_item_abilities 3.1.0-beta+fdrf.1+1.21
	   |    |-- mixinextras 0.4.0-beta.2
	   |    |-- porting_lib_blocks 3.1.0-beta+fdrf.1+1.21
	   |    |-- porting_lib_core 3.1.0-beta+fdrf.1+1.21
	   |    |-- porting_lib_gametest 3.1.0-beta+fdrf.1+1.21
	   |    \-- porting_lib_level_events 3.1.0-beta+fdrf.1+1.21
	   |-- porting_lib_lazy_registration 3.1.0-beta+fdrf.1+1.21
	   |    |-- mixinextras 0.4.0-beta.2
	   |    |-- porting_lib_core 3.1.0-beta+fdrf.1+1.21
	   |    \-- porting_lib_gametest 3.1.0-beta+fdrf.1+1.21
	   |-- porting_lib_loot 3.1.0-beta+fdrf.1+1.21
	   |    |-- mixinextras 0.4.0-beta.2
	   |    |-- porting_lib_conditions 3.1.0-beta+fdrf.1+1.21
	   |    |-- porting_lib_core 3.1.0-beta+fdrf.1+1.21
	   |    \-- porting_lib_gametest 3.1.0-beta+fdrf.1+1.21
	   \-- porting_lib_recipe_book_categories 3.1.0-beta+fdrf.1+1.21
	        |-- mixinextras 0.4.0-beta.2
	        |-- porting_lib_core 3.1.0-beta+fdrf.1+1.21
	        \-- porting_lib_gametest 3.1.0-beta+fdrf.1+1.21
	- framework 0.9.1
	   |-- org_javassist_javassist 3.29.2-GA
	   \-- org_reflections_reflections 0.10.2
	- java 21
	- minecraft 1.21
	- movingelevators 1.4.9
	- refurbished_furniture 1.0.6
	- supermartijn642configlib 1.1.8
	- supermartijn642corelib 1.1.17+c
mainEx[2111월2024 14:09:28.160] [main/INFO] [FabricLoader/Mixin/]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/C:/Users/joonh/AppData/Roaming/.feather/player-server/servers/ec7b6c63-0640-42da-8b89-3c0833ff6b97/libraries/net/fabricmc/sponge-mixin/0.13.3+mixin.0.8.5/sponge-mixin-0.13.3+mixin.0.8.5.jar Service=Knot/Fabric Env=SERVER
mainEx[2111월2024 14:09:28.209] [main/INFO] [FabricLoader/Mixin/]: Compatibility level set to JAVA_17
mainEx[2111월2024 14:09:28.258] [main/INFO] [FabricLoader/Mixin/]: Compatibility level set to JAVA_21
mainEx[2111월2024 14:09:28.634] [main/INFO] [Arclight/]: 언어 en_us 대신 ko_kr을 사용합니다.
mainEx[2111월2024 14:09:28.640] [main/INFO] [Arclight/]: 

       ___           ___     __   /\
      /   | ________/ (_)__ / /  / /
     / /| |/ __/ __/ / / _ / _ \/__/
    / ___ / / / /_/ / / / / // / /
   /_/  |/_/  \__/_/_/\_ /_//_/ /
                     /__/     \/

    버전: 诸王 (Feudal Kings) / arclight-1.21-1.0.0-SNAPSHOT-b3349e9
    빌드 날짜: 2024-06-29 03:46:12

mainEx[2111월2024 14:09:28.739] [main/WARN] [FabricLoader/Mixin/]: Reference map 'supermartijn642configlib.mixins.refmap.json' for supermartijn642configlib.mixins.json could not be read. If this is a development environment you can ignore this message
mainEx[2111월2024 14:09:28.829] [main/WARN] [FabricLoader/Mixin/]: Error loading class: net/minecraft/class_881 (java.lang.ClassNotFoundException: net/minecraft/class_881)
mainEx[2111월2024 14:09:28.830] [main/WARN] [FabricLoader/Mixin/]: @Mixin target net.minecraft.class_881 was not found porting_lib_base.mixins.json:client.BoatRendererMixin from mod porting_lib_base
mainEx[2111월2024 14:09:28.831] [main/WARN] [FabricLoader/Mixin/]: Error loading class: net/minecraft/class_525 (java.lang.ClassNotFoundException: net/minecraft/class_525)
mainEx[2111월2024 14:09:28.831] [main/WARN] [FabricLoader/Mixin/]: @Mixin target net.minecraft.class_525 was not found porting_lib_base.mixins.json:client.CreateWorldScreenMixin from mod porting_lib_base
mainEx[2111월2024 14:09:28.878] [main/WARN] [FabricLoader/Mixin/]: Error loading class: net/minecraft/class_906 (java.lang.ClassNotFoundException: net/minecraft/class_906)
mainEx[2111월2024 14:09:28.878] [main/WARN] [FabricLoader/Mixin/]: @Mixin target net.minecraft.class_906 was not found porting_lib_item_abilities.mixins.json:FishingHookRendererMixin from mod porting_lib_item_abilities
mainEx[2111월2024 14:09:29.239] [main/WARN] [FabricLoader/Mixin/]: Error loading class: net/minecraft/class_638 (java.lang.ClassNotFoundException: net/minecraft/class_638)
mainEx[2111월2024 14:09:29.239] [main/WARN] [FabricLoader/Mixin/]: @Mixin target net.minecraft.class_638 was not found porting_lib_level_events.mixins.json:client.ClientLevelMixin from mod porting_lib_level_events
mainEx[2111월2024 14:09:29.392] [main/WARN] [FabricLoader/Mixin/]: Error loading class: net/minecraft/class_314 (java.lang.ClassNotFoundException: net/minecraft/class_314)
mainEx[2111월2024 14:09:29.392] [main/WARN] [FabricLoader/Mixin/]: @Mixin target net.minecraft.class_314 was not found mixins.mm.json:net.minecraft.class_314 from mod mm
mainEx[2111월2024 14:09:29.515] [main/INFO] [FabricLoader/MixinExtras|Service/]: Initializing MixinExtras via com.llamalad7.mixinextras.service.MixinExtrasServiceImpl(version=0.4.0-beta.2).
mainEx[2111월2024 14:09:30.955] [main/ERROR] [FabricLoader/Mixin/]: Mixin apply for mod porting_lib_entity failed porting_lib_entity.mixins.json:common.PlayerMixin from mod porting_lib_entity -> net.minecraft.class_1657: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException Unexpecteded NullPointerException whilst transforming the mixin class: [INJECT Applicator Phase -> porting_lib_entity.mixins.json:common.PlayerMixin from mod porting_lib_entity -> Apply Injections -> PreInject -> porting_lib_entity.mixins.json:common.PlayerMixin from mod porting_lib_entity->@SugarWrapper::modifyResult(Z)Z]
mainEx org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: Unexpecteded NullPointerException whilst transforming the mixin class: [INJECT Applicator Phase -> porting_lib_entity.mixins.json:common.PlayerMixin from mod porting_lib_entity -> Apply Injections -> PreInject -> porting_lib_entity.mixins.json:common.PlayerMixin from mod porting_lib_entity->@SugarWrapper::modifyResult(Z)Z]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1393) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1062) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:402) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:327) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:422) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) [sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) [sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) [sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) [fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) [fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) [fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) [fabric-loader-0.15.11.jar:?]
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source) [?:?]
	at net.minecraft.class_2966.method_12851(BootstrapMixin.java:52) [server-intermediary.jar:?]
	at net.minecraft.server.Main.main(Main.java:108) [server-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) [fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.15.11.jar:?]
	at io.izzel.arclight.boot.fabric.application.Main_Fabric.main(Main_Fabric.java:33) [server.jar:arclight-1.21-1.0.0-SNAPSHOT-b3349e9]
	at io.izzel.arclight.server.Launcher.main(Launcher.java:39) [server.jar:arclight-1.21-1.0.0-SNAPSHOT-b3349e9]
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source) ~[?:?]
	at java.base/java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
	at net.digitalingot.rustextension.ProxiedStart.main(ProxiedStart.java:27) [rust-extension-1.0.10.jar:?]
Caused by: java.lang.NullPointerException: Cannot read field "desc" because "frame[varInsn.var]" is null
	at org.spongepowered.asm.util.Locals.getLocalsAt(Locals.java:546) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.util.Locals.getLocalsAt(Locals.java:336) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.modify.LocalVariableDiscriminator$Context.initLocals(LocalVariableDiscriminator.java:154) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.modify.LocalVariableDiscriminator$Context.<init>(LocalVariableDiscriminator.java:148) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.modify.ModifyVariableInjector$Context.<init>(ModifyVariableInjector.java:71) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.modify.ModifyVariableInjector.preInject(ModifyVariableInjector.java:159) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.code.Injector.preInject(Injector.java:259) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.preInject(InjectionInfo.java:436) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at com.llamalad7.mixinextras.versions.MixinVersionImpl_v0_8_3.preInject(MixinVersionImpl_v0_8_3.java:16) ~[mixinextras-0.4.0-beta.2-5d9423fc8c562f59.jar:?]
	at com.llamalad7.mixinextras.utils.CompatibilityHelper.preInject(CompatibilityHelper.java:29) ~[mixinextras-0.4.0-beta.2-5d9423fc8c562f59.jar:?]
	at com.llamalad7.mixinextras.wrapper.InjectorWrapperImpl.preInject(InjectorWrapperImpl.java:57) ~[mixinextras-0.4.0-beta.2-5d9423fc8c562f59.jar:?]
	at com.llamalad7.mixinextras.wrapper.WrapperInjectionInfo.preInject(WrapperInjectionInfo.java:63) ~[mixinextras-0.4.0-beta.2-5d9423fc8c562f59.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1370) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	... 24 more

**Comment by LabsZero** [comment]
Have you tried using one of these builds it has an up to date forge version (0.16.9) and is for 1.21.1
https://github.com/IzzelAliz/Arclight/actions/runs/11914341028

**Comment by qyl27** [comment]
Please really confirm that **Arclight is up to date**, yours are almost 3 months outdated.
