### ISSUE TITLE
FAWE / Fast Async World Edit / Arclight Fabric / 1.21.1 - Compatibilities

### ISSUE THREAD

**Issue by VoldirFr** [IzzelAliz/Arclight#1584]
### I have confirmed that ...

- [X] Arclight is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Forge

### Arclight version

fabric feudalkings 1.0.0 fabric snap

### OS & Java versions

java 21

### Plugins and Mods

```raw
arclight feudalkings fabric 1.0.0
fawe 2.12.3 (either paper or bukkit)
```

### Description

Using latest version of both FAWE and Arclight Fabric
Might have been reported like 10K times already
Just need to know if it will be fixed at a time or should i find an alternative ?

### Logs

[15:04:11 INFO] [FastAsyncWorldEdit]: Loading FastAsyncWorldEdit v2.12.3-SNAPSHOT
[15:04:11 ERROR] [o.b.c.v.CraftServer]: Could not retrieve manifest attributes initializing FastAsyncWorldEdit v2.12.3-SNAPSHOT (Is it up to date?)
java.lang.NullPointerException: Could not retrieve manifest attributes
at java.base/java.util.Objects.requireNonNull(Objects.java:246) ~[?:?]
at com.sk89q.worldedit.bukkit.WorldEditPlugin.onLoad(WorldEditPlugin.java:140) ~[?:?]
at knot/org.bukkit.craftbukkit.v1_21_R1.CraftServer.loadPlugins(CraftServerMixin.java:470) ~[arclight-1.21.1-1.0.0-SNAPSHOT-6e887d4.jar:?]
at knot/net.minecraft.class_3176.handler$zcj000$arclight$loadPlugins(DedicatedServerMixin_Vanilla.java:744) ~[server-intermediary.jar:?]
at knot/net.minecraft.class_3176.method_3823(DedicatedServerMixin_Vanilla.java:175) ~[server-intermediary.jar:?]
at knot/net.minecraft.server.MinecraftServer.method_29741(MinecraftServerMixin.java:664) ~[server-intermediary.jar:?]
at knot/net.minecraft.server.MinecraftServer.method_29739(MinecraftServerMixin.java:281) ~[server-intermediary.jar:?]
at java.base/java.lang.Thread.run(Thread.java:1570) [?:?]
[15:04:11 INFO] [FastAsyncWorldEdit]: Enabling FastAsyncWorldEdit v2.12.3-SNAPSHOT
[15:04:11 INFO] [c.f.c.Fawe]: LZ4 Compression Binding loaded successfully
[15:04:11 INFO] [c.f.c.Fawe]: ZSTD Compression Binding loaded successfully
[15:04:12 INFO] [c.s.w.PermissionsResolverManager]: WEPIF: Updated config file
[15:04:12 INFO] [c.s.w.PermissionsResolverManager]: WEPIF: Using the Bukkit Permissions API.
[15:04:13 ERROR] [Minecraft]: Error occurred while enabling FastAsyncWorldEdit v2.12.3-SNAPSHOT (Is it up to date?)
com.sk89q.worldedit.extension.platform.NoCapablePlatformException: Not all platforms have been registered yet! Please wait until FastAsyncWorldEdit is initialized.
at com.sk89q.worldedit.extension.platform.PlatformManager.queryCapability(PlatformManager.java:181) ~[?:?]
at com.sk89q.worldedit.bukkit.WorldEditPlugin.loadAdapter(WorldEditPlugin.java:426) ~[?:?]
at com.sk89q.worldedit.bukkit.WorldEditPlugin.setupPreWorldData(WorldEditPlugin.java:293) ~[?:?]
at com.sk89q.worldedit.bukkit.WorldEditPlugin.onEnable(WorldEditPlugin.java:264) ~[?:?]
at knot/org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPluginMixin.java:267) ~[arclight-1.21.1-1.0.0-SNAPSHOT-6e887d4.jar:?]
at knot/org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoaderMixin.java:342) ~[arclight-1.21.1-1.0.0-SNAPSHOT-6e887d4.jar:?]
at knot/org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:492) ~[arclight-1.21.1-1.0.0-SNAPSHOT-6e887d4.jar:?]
at knot/org.bukkit.craftbukkit.v1_21_R1.CraftServer.enablePlugin(CraftServerMixin.java:576) ~[arclight-1.21.1-1.0.0-SNAPSHOT-6e887d4.jar:?]
at knot/org.bukkit.craftbukkit.v1_21_R1.CraftServer.enablePlugins(CraftServerMixin.java:490) ~[arclight-1.21.1-1.0.0-SNAPSHOT-6e887d4.jar:?]
at knot/net.minecraft.class_3176.handler$zcj000$arclight$loadPlugins(DedicatedServerMixin_Vanilla.java:745) ~[server-intermediary.jar:?]
at knot/net.minecraft.class_3176.method_3823(DedicatedServerMixin_Vanilla.java:175) ~[server-intermediary.jar:?]
at knot/net.minecraft.server.MinecraftServer.method_29741(MinecraftServerMixin.java:664) ~[server-intermediary.jar:?]
at knot/net.minecraft.server.MinecraftServer.method_29739(MinecraftServerMixin.java:281) ~[server-intermediary.jar:?]

**Comment by qyl27** [comment]
I'm sorry, but we won't be able to make any promises for now. It needs a lot of work.

**Comment by OneWorldStudio** [comment]
> ### I have confirmed that ...
> * [x]  Arclight is up to date[x]  all dependencies are installed[x]  all plugins and mods are up to date[x]  unable to reproduce in Spigot[x]  unable to reproduce in Forge
> 
> ### Arclight version
> fabric feudalkings 1.0.0 fabric snap
> 
> ### OS & Java versions
> java 21
> 
> ### Plugins and Mods
> ```
> arclight feudalkings fabric 1.0.0
> fawe 2.12.3 (either paper or bukkit)
> ```
> 
> ### Description
> Using latest version of both FAWE and Arclight Fabric Might have been reported like 10K times already Just need to know if it will be fixed at a time or should i find an alternative ?
> 
> ### Step to reproduce
> _No response_
> 
> ### Logs
> [15:04:11 INFO] [FastAsyncWorldEdit]: Loading FastAsyncWorldEdit v2.12.3-SNAPSHOT [15:04:11 ERROR] [o.b.c.v.CraftServer]: Could not retrieve manifest attributes initializing FastAsyncWorldEdit v2.12.3-SNAPSHOT (Is it up to date?) java.lang.NullPointerException: Could not retrieve manifest attributes at java.base/java.util.Objects.requireNonNull(Objects.java:246) ~[?:?] at com.sk89q.worldedit.bukkit.WorldEditPlugin.onLoad(WorldEditPlugin.java:140) ~[?:?] at knot/org.bukkit.craftbukkit.v1_21_R1.CraftServer.loadPlugins(CraftServerMixin.java:470) ~[arclight-1.21.1-1.0.0-SNAPSHOT-6e887d4.jar:?] at knot/net.minecraft.class_3176.handler$zcj000$arclight$loadPlugins(DedicatedServerMixin_Vanilla.java:744) ~[server-intermediary.jar:?] at knot/net.minecraft.class_3176.method_3823(DedicatedServerMixin_Vanilla.java:175) ~[server-intermediary.jar:?] at knot/net.minecraft.server.MinecraftServer.method_29741(MinecraftServerMixin.java:664) ~[server-intermediary.jar:?] at knot/net.minecraft.server.MinecraftServer.method_29739(MinecraftServerMixin.java:281) ~[server-intermediary.jar:?] at java.base/java.lang.Thread.run(Thread.java:1570) [?:?] [15:04:11 INFO] [FastAsyncWorldEdit]: Enabling FastAsyncWorldEdit v2.12.3-SNAPSHOT [15:04:11 INFO] [c.f.c.Fawe]: LZ4 Compression Binding loaded successfully [15:04:11 INFO] [c.f.c.Fawe]: ZSTD Compression Binding loaded successfully [15:04:12 INFO] [c.s.w.PermissionsResolverManager]: WEPIF: Updated config file [15:04:12 INFO] [c.s.w.PermissionsResolverManager]: WEPIF: Using the Bukkit Permissions API. [15:04:13 ERROR] [Minecraft]: Error occurred while enabling FastAsyncWorldEdit v2.12.3-SNAPSHOT (Is it up to date?) com.sk89q.worldedit.extension.platform.NoCapablePlatformException: Not all platforms have been registered yet! Please wait until FastAsyncWorldEdit is initialized. at com.sk89q.worldedit.extension.platform.PlatformManager.queryCapability(PlatformManager.java:181) ~[?:?] at com.sk89q.worldedit.bukkit.WorldEditPlugin.loadAdapter(WorldEditPlugin.java:426) ~[?:?] at com.sk89q.worldedit.bukkit.WorldEditPlugin.setupPreWorldData(WorldEditPlugin.java:293) ~[?:?] at com.sk89q.worldedit.bukkit.WorldEditPlugin.onEnable(WorldEditPlugin.java:264) ~[?:?] at knot/org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPluginMixin.java:267) ~[arclight-1.21.1-1.0.0-SNAPSHOT-6e887d4.jar:?] at knot/org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoaderMixin.java:342) ~[arclight-1.21.1-1.0.0-SNAPSHOT-6e887d4.jar:?] at knot/org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:492) ~[arclight-1.21.1-1.0.0-SNAPSHOT-6e887d4.jar:?] at knot/org.bukkit.craftbukkit.v1_21_R1.CraftServer.enablePlugin(CraftServerMixin.java:576) ~[arclight-1.21.1-1.0.0-SNAPSHOT-6e887d4.jar:?] at knot/org.bukkit.craftbukkit.v1_21_R1.CraftServer.enablePlugins(CraftServerMixin.java:490) ~[arclight-1.21.1-1.0.0-SNAPSHOT-6e887d4.jar:?] at knot/net.minecraft.class_3176.handler$zcj000$arclight$loadPlugins(DedicatedServerMixin_Vanilla.java:745) ~[server-intermediary.jar:?] at knot/net.minecraft.class_3176.method_3823(DedicatedServerMixin_Vanilla.java:175) ~[server-intermediary.jar:?] at knot/net.minecraft.server.MinecraftServer.method_29741(MinecraftServerMixin.java:664) ~[server-intermediary.jar:?] at knot/net.minecraft.server.MinecraftServer.method_29739(MinecraftServerMixin.java:281) ~[server-intermediary.jar:?]
> 
> ### Server pack link (Optional)
> _No response_

Fawe in principle does not support blocks not from MInecraft, in order to make it work, you need to make your custom plugin without code, I made WorldEdit like that.

**Comment by Kile467** [comment]
Happens to me as well. I'm afraid we can't use FAWE for now until the team solve this!
