### ISSUE TITLE
无法使用世界生成器生成一个自定义的世界 | Cannot build a custom world using World Generator

### ISSUE THREAD

**Issue by CornWorld** [IzzelAliz/Arclight#164]
我在 Arclight 中安装了 mv多世界 和 cleanroom 插件
接着使用指令
![/mv create test normal -g CleanroomGenerator:.](https://user-images.githubusercontent.com/43746030/107916139-c1b13a00-6fa0-11eb-8c36-1839cddaa2c1.png)
来创建了一个新的世界
按理来说应该会创建一个全是虚空的世界
但是变成了这样
![Image](https://user-images.githubusercontent.com/43746030/107916260-f91fe680-6fa0-11eb-8fdd-fa6a6d2fff7f.png)

然后在paper(1.16.5-467)中使用相同的插件(以及一样的配置文件)和相同的指令
却得到了一个预料之中的世界

一些信息:
![image](https://user-images.githubusercontent.com/43746030/107916630-90853980-6fa1-11eb-8f5b-fbb6c01eb5d1.png)
![image](https://user-images.githubusercontent.com/43746030/107916682-a5fa6380-6fa1-11eb-9aaf-406c50a2db78.png)
CleanroomGenerator:1.1.1

**Comment by CornWorld** [comment]
这意味着无法正常使用一些依赖生成器的玩法 , 比如空岛生存
实测使用Bentobox与IridiumSkyblock都会出现超平坦世界而不是预料的虚空世界

#### IridiumSkyblock
![image](https://user-images.githubusercontent.com/43746030/107921380-646db680-6fa9-11eb-97b0-e45a1eb1f8f8.png)
报错:
```
[08:15:06] [Server thread/WARN] [IridiumSkyblock/]: Task #56 for IridiumSkyblock v2.6.7 generated an exception
java.lang.NoSuchFieldError: world
        at com.iridium.iridiumskyblock.nms.v1_16_R3.sendWorldBorder(v1_16_R3.java:45) ~[?:?] {re:classloading,re:classloading,re:classloading}
        at com.iridium.iridiumskyblock.Island.sendBorder(Island.java:323) ~[?:?] {re:classloading,re:classloading,re:classloading}
        at com.iridium.iridiumskyblock.Island.sendBorder(Island.java:314) ~[?:?] {re:classloading,re:classloading,re:classloading}
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:81) ~[arclight:arclight-1.16.5-1.0.12-30c1219] {re:classloading}
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:400) ~[arclight:arclight-1.16.5-1.0.12-30c1219] {re:mixin,re:classloading}
        at net.minecraft.server.MinecraftServer.handler$zpn000$arclight$runScheduler(MinecraftServerMixin.java:2134) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServerMixin.java) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServerMixin.java:291) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.dedicated.DedicatedServerMixin,pl:mixin:A}
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServerMixin.java:786) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServerMixin.java:1895) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.lambda$startServer$0(MinecraftServerMixin.java:232) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_281] {}
```
#### Bentobox(BSkyblock 并使用 Cleanroom Generator)
![image](https://user-images.githubusercontent.com/43746030/107921868-23c26d00-6faa-11eb-893f-70b9c0ab7742.png)

报错:(未发现)

**Comment by CornWorld** [comment]
刚刚使用mohist以及相同的mod与插件(包括配置文件)
发现并没有出现如上问题
可排除mod造成的影响
情况如下
![image](https://user-images.githubusercontent.com/43746030/107924427-dd6f0d00-6fad-11eb-8adf-4b997335f91e.png)

**Comment by IzzelAliz** [comment]
已知问题，有一位开发者说要修这个，如果他不修我就来

**Comment by CornWorld** [comment]
Orz
