### ISSUE TITLE
1.15.2启动崩溃

### ISSUE THREAD

**Issue by username-ui** [IzzelAliz/Arclight#18]
[14ÆßÔÂ2020 19:46:44.567] [main/INFO] [Arclight/]: 

       ___           ___     __   /\
      /   | ________/ (_)__ / /  / /
     / /| |/ __/ __/ / / _ / _ \/__/
    / ___ / / / /_/ / / / / // / /
   /_/  |/_/  \__/_/_/\_ /_//_/ /
                     /__/     \/

    ÔËÐÐ°æ±¾ arclight-1.15.2-1.0.1-5a1500a
    ¹¹½¨ÈÕÆÚ 2020-07-07 14:58:20

[14ÆßÔÂ2020 19:46:44.572] [main/INFO] [Arclight/]: ÕýÔÚ¼ÓÔØ»ìÏýÊý¾Ý ...
[14ÆßÔÂ2020 19:46:45.234] [main/INFO] [cpw.mods.modlauncher.Launcher/MODLAUNCHER]: ModLauncher running: args [--gameDir, ., --launchTarget, fmlserver, --fml.forgeVersion, 31.2.30, --fml.mcpVersion, 20200515.085601, --fml.mcVersion, 1.15.2, --fml.forgeGroup, net.minecraftforge]
[14ÆßÔÂ2020 19:46:45.242] [main/INFO] [cpw.mods.modlauncher.Launcher/MODLAUNCHER]: ModLauncher 5.1.0+69+master.79f13f7 starting: java version 1.8.0_231 by Oracle Corporation
[14ÆßÔÂ2020 19:46:48.406] [main/INFO] [net.minecraftforge.fml.loading.FixSSL/CORE]: Added Lets Encrypt root certificates as additional trust
[14ÆßÔÂ2020 19:46:48.449] [main/INFO] [mixin/]: SpongePowered MIXIN Subsystem Version=0.8 Source=file:/D:/Downloads/Arclight/libraries/org/spongepowered/mixin/0.8/mixin-0.8.jar Service=ModLauncher Env=SERVER
[14ÆßÔÂ2020 19:46:48.607] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: java.lang.NoClassDefFoundError: org/apache/commons/lang3/tuple/Pair
[14ÆßÔÂ2020 19:46:48.608] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraftforge.fml.loading.FMLLoader.setupLaunchHandler(FMLLoader.java:188)
[14ÆßÔÂ2020 19:46:48.609] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraftforge.fml.loading.FMLServiceProvider.initialize(FMLServiceProvider.java:94)
[14ÆßÔÂ2020 19:46:48.609] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at cpw.mods.modlauncher.TransformationServiceDecorator.onInitialize(TransformationServiceDecorator.java:68)
[14ÆßÔÂ2020 19:46:48.610] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at cpw.mods.modlauncher.TransformationServicesHandler.lambda$initialiseTransformationServices$7(TransformationServicesHandler.java:107)
[14ÆßÔÂ2020 19:46:48.611] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.util.HashMap$Values.forEach(Unknown Source)
[14ÆßÔÂ2020 19:46:48.611] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at cpw.mods.modlauncher.TransformationServicesHandler.initialiseTransformationServices(TransformationServicesHandler.java:107)
[14ÆßÔÂ2020 19:46:48.612] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at cpw.mods.modlauncher.TransformationServicesHandler.initializeTransformationServices(TransformationServicesHandler.java:59)
[14ÆßÔÂ2020 19:46:48.612] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at cpw.mods.modlauncher.Launcher.run(Launcher.java:75)
[14ÆßÔÂ2020 19:46:48.613] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)
[14ÆßÔÂ2020 19:46:48.613] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraftforge.server.ServerMain$Runner.runLauncher(ServerMain.java:63)
[14ÆßÔÂ2020 19:46:48.614] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraftforge.server.ServerMain$Runner.access$100(ServerMain.java:60)
[14ÆßÔÂ2020 19:46:48.614] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraftforge.server.ServerMain.main(ServerMain.java:57)
[14ÆßÔÂ2020 19:46:48.615] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at io.izzel.arclight.common.ArclightMain.run(ArclightMain.java:45)
[14ÆßÔÂ2020 19:46:48.615] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at io.izzel.arclight.server.Main_1_15.main(Main_1_15.java:10)
[14ÆßÔÂ2020 19:46:48.619] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: Caused by: java.lang.ClassNotFoundException: org.apache.commons.lang3.tuple.Pair
[14ÆßÔÂ2020 19:46:48.620] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.net.URLClassLoader.findClass(Unknown Source)
[14ÆßÔÂ2020 19:46:48.620] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.ClassLoader.loadClass(Unknown Source)
[14ÆßÔÂ2020 19:46:48.621] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
[14ÆßÔÂ2020 19:46:48.622] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.ClassLoader.loadClass(Unknown Source)
[14ÆßÔÂ2020 19:46:48.624] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: 	... 14 more

**Comment by IzzelAliz** [comment]
依赖没下全
