### ISSUE TITLE
log4j glitch

### ISSUE THREAD

**Issue by Dum4G** [IzzelAliz/Arclight#180]
### I am running

* **Arclight** 1.16.5-1.0.13 

* **This is the latest development version** [N] (probably can't be reproduced with the latest version because files are accesible)

* **Java** 15.0.2+7 JRE 

* **Operating System** Debian 10

### Description

Reproducable only on Debian machine. Sometimes server won't be able to download some libraries it needs and crash this way after timing the file out. May be Java 15 thing

### Steps to reproduce

Basically start a server with library folder missing under Java 15 and Linux
Have a crash
```Запускается установка Forge, пожалуйста подождите... (Forge installation is starting)

He удалось загрузить (failed to load) org.xerial:sqlite-jdbc:3.34.0: 
Cl) Превышено ожидание java.net.SocketTimeoutException: Read timed out https://arclight.mcxk.net/org/xerial/sqlite-jdb c/3.34.0/sqlite-jdbc-3.34.0.jar
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/logging/log4j/spi/ExtendedLoggerWrapper
 at java.lang.ClassLoader.defineClassl(Native Method)
 at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
 at java.security.SecureClassLoader.defineClassCSecureClassLoader.java:142)
 at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
at java.net.URLClassLoader$l.run(URLClassLoader.java:369)
 at java.net.URLClassLoader$l.run(URLClassLoader.java:363)
 at java.security.Accesscontroller.doPrivileged(Native Method)
 at java.net.URLClassLoader.findClass(URLClassLoader.java:362) 
at java.lang.ClassLoader.loadclass(ClassLoader.java:418) 
at sun.misc.Launcher$AppClassLoader.loadclass(Launcher.java:352) at java.lang.ClassLoader.loadclass(ClassLoader.java:351)
 at io.izzel.arclight.common.ArclightMain.printLogo(ArclightMain.java:69)
 at io.izzel.arclight.common.ArclightMain.run(ArclightMain.java:43)
 at io.izzel.arclight.server.Main_l_16.main(Main_l_16.java:10)
Caused by: java.lang.ClassNotFoundException: org.apache.logging.Iog4j.spi.ExtendedLoggerWrapper
 at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
 at java.lang.ClassLoader.loadclass(ClassLoader.java:418)
 at sun.misc.Launcher$AppClassLoader.loadclass(Launcher.java:352)
 at java.lang.ClassLoader.loadclass(ClassLoader.java:351) 
... 15 more
```
![unknown (1)](https://user-images.githubusercontent.com/5430116/109176329-c1325380-7797-11eb-8188-320cf7f837b7.png)

**Comment by IzzelAliz** [comment]
Network issue, can't fix.

Remove `forge-<version>.jar` and rerun would fix this.
