### ISSUE TITLE
 Errors on citizens plugin does not reproduce commands

### ISSUE THREAD

**Issue by ostinostin** [IzzelAliz/Arclight#184]
###citizens 2.0.27-2272

* **Arclight** [VERSION] <!-    "id": "1.15.2",
    "name": "1.15.2",
    "release_target": "1.15.2",
    "world_version": 2230,
    "protocol_version": 578,
    "pack_version": 5,
    "build_time": "2020-01-17T10:02:11+00:00",
    "stable": true -->

* **This is the latest development version** [Y/N, because ___]

* **Java** [VERSION] <!-Java8 JDK8-->

* **Operating System** [WIN10]

* **Plugins** 

Good day. Although the plugin is loading, it gives errors when loading, and also does not allow using the commands. here is the log

[ERROR LOG]
[latest.log](https://github.com/IzzelAliz/Arclight/files/6050753/latest.log)

[26фев2021 18:43:12.682] [Server thread/ERROR] [Minecraft/]: Error occurred while enabling Citizens v2.0.27-SNAPSHOT (build 2272) (Is it up to date?)
java.lang.StackOverflowError: null
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_281]
	at java.net.URLClassLoader.findResource(URLClassLoader.java:569) ~[?:1.8.0_281]
	at org.bukkit.plugin.java.PluginClassLoader.getResource(PluginClassLoaderMixin.java:86) ~[?:arclight-1.15.2-1.0.18-c1ccac9]
	at java.lang.Class.getResource(Class.java:2267) ~[?:1.8.0_281]
	at io.izzel.arclight.common.mod.util.remapper.generated.ArclightReflectionHandler_0.redirectClassGetResource(ArclightReflectionHandler.java:328) ~[?:arclight-1.15.2-1.0.18-c1ccac9]
	at net.citizensnpcs.api.util.Translator$FileClassLoader.getResource(Translator.java:109) ~[?:?]
	at io.izzel.arclight.common.mod.util.remapper.generated.ArclightReflectionHandler_0.redirectClassLoaderGetResource(ArclightReflectionHandler.java:349) ~[?:arclight-1.15.2-1.0.18-c1ccac9]
	at net.citizensnpcs.api.util.Translator$FileClassLoader.getResource(Translator.java:113) ~[?:?]
	at io.izzel.arclight.common.mod.util.remapper.generated.ArclightReflectionHandler_0.redirectClassLoaderGetResource(ArclightReflectionHandler.java:349) ~[?:arclight-1.15.2-1.0.18-c1ccac9]
	at net.citizensnpcs.api.util.Translator$FileClassLoader.getResource(Translator.java:113) ~[?:?]
	at io.izzel.arclight.common.mod.util.remapper.generated.ArclightReflectionHandler_0.redirectClassLoaderGetResource(ArclightReflectionHandler.java:349) ~[?:arclight-1.15.2-1.0.18-c1ccac9]
	at net.citizensnpcs.api.util.Translator$FileClassLoader.getResource(Translator.java:113) ~[?:?]
	at io.izzel.arclight.common.mod.util.remapper.generated.ArclightReflectionHandler_0.redirectClassLoaderGetResource(ArclightReflectionHandler.java:349) ~[?:arclight-1.15.2-1.0.18-c1ccac9]
	at net.citizensnpcs.api.util.Translator$FileClassLoader.getResource(Translator.java:113) ~[?:?]
	at io.izzel.arclight.common.mod.util.remapper.generated.ArclightReflectionHandler_0.redirectClassLoaderGetResource(ArclightReflectionHandler.java:349) ~[?:arclight-1.15.2-1.0.18-c1ccac9]
	at net.citizensnpcs.api.util.Translator$FileClassLoader.getResource(Translator.java:113) ~[?:?]
	at io.izzel.arclight.common.mod.util.remapper.generated.ArclightReflectionHandler_0.redirectClassLoaderGetResource(ArclightReflectionHandler.java:349) ~[?:arclight-1.15.2-1.0.18-c1ccac9]
	at net.citizensnpcs.api.util.Translator$FileClassLoader.getResource(Translator.java:113) ~[?:?]
	at io.izzel.arclight.common.mod.util.remapper.generated.ArclightReflectionHandler_0.redirectClassLoaderGetResource(ArclightReflectionHandler.java:349) ~[?:arclight-1.15.2-1.0.18-c1ccac9]
	at net.citizensnpcs.api.

-->

**Comment by IzzelAliz** [comment]
Duplicate with #177
