### ISSUE TITLE
 Could not pass event CreatureSpawnEvent

### ISSUE THREAD

**Issue by cathats** [IzzelAliz/Arclight#190]
服务端核心：1.0.15
插件版本：ServerBooster v1.0.34
下面这个一直在刷屏，没有进行任何操作。

```bash
[05三月2021 23:43:38.362] [Server thread/ERROR] [Minecraft/]: Could not pass event CreatureSpawnEvent to ServerBooster v1.0.34
org.bukkit.event.EventException: null
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[arclight:arclight-1.16.5-1.0.15-SNAPSHOT-242055d]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[arclight:arclight-1.16.5-1.0.15-SNAPSHOT-242055d]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[arclight:arclight-1.16.5-1.0.15-SNAPSHOT-242055d]
	at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callCreatureSpawnEvent(CraftEventFactoryMixin.java:629) ~[arclight:arclight-1.16.5-1.0.15-SNAPSHOT-242055d]
	at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.doEntityAddEventCalling(CraftEventFactoryMixin.java:566) ~[arclight:arclight-1.16.5-1.0.15-SNAPSHOT-242055d]
	at net.minecraft.world.server.ServerWorld.handler$bcb000$arclight$addEntityEvent(ServerWorldMixin.java:1799) ~[?:?]
	at net.minecraft.world.server.ServerWorld.func_72838_d(ServerWorldMixin.java:813) ~[?:?]
	at net.minecraft.world.server.ServerWorld.func_217376_c(ServerWorldMixin.java:754) ~[?:?]
	at net.minecraft.world.IServerWorld.func_242417_l(IServerWorldMixin.java:538) ~[?:?]
	at net.minecraft.world.spawner.WorldEntitySpawner.func_234966_a_(WorldEntitySpawnerMixin.java:178) ~[?:?]
	at net.minecraft.world.spawner.WorldEntitySpawner.func_234967_a_(WorldEntitySpawnerMixin.java:124) ~[?:?]
	at net.minecraft.world.spawner.WorldEntitySpawner.func_234979_a_(WorldEntitySpawnerMixin.java:594) ~[?:?]
	at net.minecraft.world.server.ServerChunkProvider.lambda$tickChunks$5(ServerChunkProviderMixin.java:359) ~[?:?]
	at java.util.ArrayList.forEach(Unknown Source) ~[?:1.8.0_281]
	at net.minecraft.world.server.ServerChunkProvider.func_217220_m(ServerChunkProviderMixin.java:346) ~[?:?]
	at net.minecraft.world.server.ServerChunkProvider.func_217207_a(ServerChunkProviderMixin.java:321) ~[?:?]
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorldMixin.java:333) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServerMixin.java:851) ~[?:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServerMixin.java:291) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServerMixin.java:787) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServerMixin.java:1899) ~[?:?]
	at net.minecraft.server.MinecraftServer.lambda$startServer$0(MinecraftServerMixin.java:232) ~[?:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_281]
Caused by: java.lang.NoClassDefFoundError: Could not initialize class dev.lone.serverbooster.e
	at dev.lone.serverbooster.f.d.a(SourceFile:58) ~[?:?]
	... 23 more
```

**Comment by IzzelAliz** [comment]
请按格式提交
