### ISSUE TITLE
WildLoader 无法正常使用

### ISSUE THREAD

**Issue by ahdg6** [IzzelAliz/Arclight#193]
### 我正在运行

* **Arclight** [arclight-forge-1.16-1.0.15] 

* **你确认这是最新版吗** [是]

* **你确认所有Mod都安装了依赖** [是]

* **你确认所有插件都已更新至对应版本** [是]

* **Java** [openjdk-hotspot-11] 

* **操作系统** [Windows Server 2019]

* **插件列表** 
WildLoader,ProtocolLib,Vault,Chunky,GriefDefender,Xconomy
* **Mod 列表** 
![图片](https://user-images.githubusercontent.com/36436808/110218115-c78ca200-7ef2-11eb-980b-e1582f03a574.png)

### 错误描述

当WildLoader插件的加载器倒计时一完成，服务器就会崩溃。

### 重现步骤

1. 安装 WildLoader
2. 进入服务器后放置插件的区块加载器
3. 等待倒计时完成，加载器过期
4. 服务器崩溃

**可在 Forge 复现** [否]

**可在 Spigot 复现** [否]

### 报错信息

[<details><pre>
[---- Minecraft Crash Report ----
// Shall we play a game?

Time: 2021/3/7 上午2:57
Description: Ticking block entity

java.lang.NoSuchMethodError: 'net.minecraft.world.chunk.Chunk net.minecraft.entity.player.ServerPlayerEntity.getCurrentChunk()'
	at com.bgsoftware.wildloaders.nms.ChunkLoaderNPC_v1_16_R3.removePlayer(ChunkLoaderNPC_v1_16_R3.java:76) ~[?:?] {re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading}
	at com.bgsoftware.wildloaders.nms.ChunkLoaderNPC_v1_16_R3.func_70106_y(ChunkLoaderNPC_v1_16_R3.java:62) ~[?:?] {re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading}
	at com.bgsoftware.wildloaders.nms.ChunkLoaderNPC_v1_16_R3.die(ChunkLoaderNPC_v1_16_R3.java) ~[?:?] {re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading}
	at com.bgsoftware.wildloaders.handlers.NPCHandler.killNPC(NPCHandler.java:58) ~[?:?] {re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading}
	at com.bgsoftware.wildloaders.handlers.LoadersHandler.lambda$removeChunkLoader$0(LoadersHandler.java:91) ~[?:?] {re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading}
	at java.util.Optional.ifPresent(Unknown Source) ~[?:?] {}
	at com.bgsoftware.wildloaders.handlers.LoadersHandler.removeChunkLoader(LoadersHandler.java:91) ~[?:?] {re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading}
	at com.bgsoftware.wildloaders.loaders.WChunkLoader.remove(WChunkLoader.java:109) ~[?:?] {re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading}
	at com.bgsoftware.wildloaders.loaders.WChunkLoader.tick(WChunkLoader.java:72) ~[?:?] {re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading}
	at com.bgsoftware.wildloaders.nms.NMSAdapter_v1_16_R3$TileEntityChunkLoader.func_73660_a(NMSAdapter_v1_16_R3.java:264) ~[?:?] {re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading}
	at com.bgsoftware.wildloaders.nms.NMSAdapter_v1_16_R3$TileEntityChunkLoader.func_222814_r(NMSAdapter_v1_16_R3.java:238) ~[?:?] {re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading}
	at net.minecraft.world.World.func_217391_K(WorldMixin.java:493) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:world.WorldMixin,pl:mixin:APP:sereneseasons.mixins.json:MixinWorld,pl:mixin:APP:starlight.mixins.json:common.world.WorldMixin,pl:mixin:A,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorldMixin.java:371) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:world.server.ServerWorldMixin,pl:mixin:APP:starlight.mixins.json:common.world.ServerWorldMixin,pl:mixin:APP:mixins.arclight.impl.optimization.1_16.json:activationrange.ServerWorldMixin_ActivationRange,pl:mixin:A,pl:arclight_implementer:async,pl:arclight_implementer:A,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServerMixin.java:851) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServerMixin.java:291) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.dedicated.DedicatedServerMixin,pl:mixin:A,re:mixin,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServerMixin.java:787) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServerMixin.java:1899) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.lambda$startServer$0(MinecraftServerMixin.java:232) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at java.lang.Thread.run(Unknown Source) [?:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at com.bgsoftware.wildloaders.nms.ChunkLoaderNPC_v1_16_R3.removePlayer(ChunkLoaderNPC_v1_16_R3.java:76) ~[?:?] {re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading}
	at com.bgsoftware.wildloaders.nms.ChunkLoaderNPC_v1_16_R3.func_70106_y(ChunkLoaderNPC_v1_16_R3.java:62) ~[?:?] {re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading}
	at com.bgsoftware.wildloaders.nms.ChunkLoaderNPC_v1_16_R3.die(ChunkLoaderNPC_v1_16_R3.java) ~[?:?] {re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading}
	at com.bgsoftware.wildloaders.handlers.NPCHandler.killNPC(NPCHandler.java:58) ~[?:?] {re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading}
	at com.bgsoftware.wildloaders.handlers.LoadersHandler.lambda$removeChunkLoader$0(LoadersHandler.java:91) ~[?:?] {re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading}
	at java.util.Optional.ifPresent(Unknown Source) ~[?:?] {}
	at com.bgsoftware.wildloaders.handlers.LoadersHandler.removeChunkLoader(LoadersHandler.java:91) ~[?:?] {re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading}
	at com.bgsoftware.wildloaders.loaders.WChunkLoader.remove(WChunkLoader.java:109) ~[?:?] {re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading}
	at com.bgsoftware.wildloaders.loaders.WChunkLoader.tick(WChunkLoader.java:72) ~[?:?] {re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading}
	at com.bgsoftware.wildloaders.nms.NMSAdapter_v1_16_R3$TileEntityChunkLoader.func_73660_a(NMSAdapter_v1_16_R3.java:264) ~[?:?] {re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading}
	at com.bgsoftware.wildloaders.nms.NMSAdapter_v1_16_R3$TileEntityChunkLoader.func_222814_r(NMSAdapter_v1_16_R3.java:238) ~[?:?] {re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading}
-- Block entity being ticked --
Details:
	Name: minecraft:command_block // com.bgsoftware.wildloaders.nms.NMSAdapter_v1_16_R3.TileEntityChunkLoader
	Block: Block{minecraft:beacon}
	Block location: World: (528,64,-381), Chunk: (at 0,4,3 in 33,-24; contains blocks 528,0,-384 to 543,255,-369), Region: (1,-1; contains chunks 32,-32 to 63,-1, blocks 512,0,-512 to 1023,255,-1)
	Block: Block{minecraft:beacon}
	Block location: World: (528,64,-381), Chunk: (at 0,4,3 in 33,-24; contains blocks 528,0,-384 to 543,255,-369), Region: (1,-1; contains chunks 32,-32 to 63,-1, blocks 512,0,-512 to 1023,255,-1)
Stacktrace:
	at net.minecraft.world.World.func_217391_K(WorldMixin.java:493) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:world.WorldMixin,pl:mixin:APP:sereneseasons.mixins.json:MixinWorld,pl:mixin:APP:starlight.mixins.json:common.world.WorldMixin,pl:mixin:A,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorldMixin.java:371) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:world.server.ServerWorldMixin,pl:mixin:APP:starlight.mixins.json:common.world.ServerWorldMixin,pl:mixin:APP:mixins.arclight.impl.optimization.1_16.json:activationrange.ServerWorldMixin_ActivationRange,pl:mixin:A,pl:arclight_implementer:async,pl:arclight_implementer:A,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}

-- Affected level --
Details:
	All players: 2 total; [ServerPlayerEntity['ahdg'/93, l='ServerLevel[world]', x=530.62, y=64.00, z=-379.99](ahdg at 530.6235675384928,64.0,-379.988923393429), ChunkLoaderNPC_v1_16_R3['Loader-world'/1221, l='ServerLevel[world]', x=528.00, y=64.00, z=-381.00](Loader-world at 528.0,64.0,-381.0)]
	Chunk stats: ServerChunkCache: 4050
	Level dimension: minecraft:overworld
	Level spawn location: World: (944,69,772), Chunk: (at 0,4,4 in 59,48; contains blocks 944,0,768 to 959,255,783), Region: (1,1; contains chunks 32,32 to 63,63, blocks 512,0,512 to 1023,255,1023)
	Level time: 22154027 game time, 35380093 day time
	Level name: world
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Level weather: Rain time: 61058 (now: false), thunder time: 103326 (now: false)
	Known server brands: Mohist, forge arclight
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServerMixin.java:851) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServerMixin.java:291) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.dedicated.DedicatedServerMixin,pl:mixin:A,re:mixin,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServerMixin.java:787) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServerMixin.java:1899) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.lambda$startServer$0(MinecraftServerMixin.java:232) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at java.lang.Thread.run(Unknown Source) [?:?] {}]
</pre></details>]

<!-- 如果上面的网站打不开，可以将以下几行代码粘贴至 [错误日志]，并将日志文本复制进去

**Comment by IzzelAliz** [comment]
这个插件用的 tunity 编译的，问作者

**Comment by ahdg6** [comment]
通过作者获取了使用 Spigot 编译的版本
那边似乎并不想提供混合服务器的支持
新错误报告如下

<details><pre>Time: 2021/3/7 下午1:03
Description: Exception ticking world

java.util.ConcurrentModificationException: null
	at java.util.ArrayList$Itr.checkForComodification(Unknown Source) ~[?:?] {}
	at java.util.ArrayList$Itr.next(Unknown Source) ~[?:?] {}
	at net.minecraft.world.World.func_217391_K(WorldMixin.java:481) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:world.WorldMixin,pl:mixin:APP:sereneseasons.mixins.json:MixinWorld,pl:mixin:APP:starlight.mixins.json:common.world.WorldMixin,pl:mixin:A,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorldMixin.java:371) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:world.server.ServerWorldMixin,pl:mixin:APP:starlight.mixins.json:common.world.ServerWorldMixin,pl:mixin:APP:mixins.arclight.impl.optimization.1_16.json:activationrange.ServerWorldMixin_ActivationRange,pl:mixin:A,pl:arclight_implementer:async,pl:arclight_implementer:A,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServerMixin.java:851) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServerMixin.java:291) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.dedicated.DedicatedServerMixin,pl:mixin:A,re:mixin,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServerMixin.java:787) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServerMixin.java:1899) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.lambda$startServer$0(MinecraftServerMixin.java:232) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at java.lang.Thread.run(Unknown Source) [?:?] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at java.util.ArrayList$Itr.checkForComodification(Unknown Source) ~[?:?] {}
	at java.util.ArrayList$Itr.next(Unknown Source) ~[?:?] {}
	at net.minecraft.world.World.func_217391_K(WorldMixin.java:481) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:world.WorldMixin,pl:mixin:APP:sereneseasons.mixins.json:MixinWorld,pl:mixin:APP:starlight.mixins.json:common.world.WorldMixin,pl:mixin:A,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorldMixin.java:371) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:world.server.ServerWorldMixin,pl:mixin:APP:starlight.mixins.json:common.world.ServerWorldMixin,pl:mixin:APP:mixins.arclight.impl.optimization.1_16.json:activationrange.ServerWorldMixin_ActivationRange,pl:mixin:A,pl:arclight_implementer:async,pl:arclight_implementer:A,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
-- Affected level --
Details:
	All players: 4 total; [ServerPlayerEntity['ahdg'/65213, l='ServerLevel[world]', x=3949.98, y=69.00, z=4585.91](ahdg at 3949.976388862836,69.0,4585.907226743155), ServerPlayerEntity['Arthas_Frost'/13019, l='ServerLevel[world]', x=528.16, y=63.00, z=-374.83](Arthas_Frost at 528.1606934774313,63.0,-374.8283028038993), ServerPlayerEntity['ElanSua'/11948, l='ServerLevel[world]', x=4888.16, y=69.00, z=-3176.30](ElanSua at 4888.162317901053,69.0,-3176.30041190559), ServerPlayerEntity['San_qian'/167296, l='ServerLevel[world]', x=3876.36, y=66.00, z=4493.64](San_qian at 3876.3649290922963,66.0,4493.640284431795)]
	Chunk stats: ServerChunkCache: 8526
	Level dimension: minecraft:overworld
	Level spawn location: World: (944,69,772), Chunk: (at 0,4,4 in 59,48; contains blocks 944,0,768 to 959,255,783), Region: (1,1; contains chunks 32,32 to 63,63, blocks 512,0,512 to 1023,255,1023)
	Level time: 22867247 game time, 36114986 day time
	Level name: world
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Level weather: Rain time: 55236 (now: false), thunder time: 32193 (now: false)
	Known server brands: Mohist, forge arclight
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServerMixin.java:851) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServerMixin.java:291) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.dedicated.DedicatedServerMixin,pl:mixin:A,re:mixin,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServerMixin.java:787) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServerMixin.java:1899) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.lambda$startServer$0(MinecraftServerMixin.java:232) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at java.lang.Thread.run(Unknown Source) [?:?] {}</pre></details>

**Comment by IzzelAliz** [comment]
这也不是我的问题，他可能不知道正确的移除 TileEntity 的方法
