### ISSUE TITLE
FAWE still not working

### ISSUE THREAD

**Issue by Matthysse** [IzzelAliz/Arclight#203]
### I am running

* **Arclight** arclight-forge-1.16-1.0.16-SNAPSHOT

* **Java** 11

* **Plugins** Citizens, Essentials X, FastAsyncWorldEdit, SuperChairs, WorldGuard

* **Mods** Adorn,Alexmobs,builderadditions,camera,citadel,exoticbirds,extlights,kotlinforforge,lithium,Mantle,notenoughcreativity,obfuscate,starlight,vehicle-mod

### Description

You said FAWE usage was fixed, but it isn't, trying //wand or //set (when doing a selection with //pos) gives an error, even in an area where there isn't a single modded block.

### Step to reproduce

1. Do //wand

### Logs

https://pastebin.com/Fy10PYGB

**Comment by KunoiSayami** [comment]
Seems work for me:
* arclight-1.16.5-1.0.16-6f9c10a
* java 1.8.0_282

But still log error here:
<details>
    <summary>java.lang.ClassNotFoundException: org.sqlite.JDBC</summary>

```
[Craft Scheduler Thread - 1/ERROR] [c.b.f.d.DBHandler/]: No JDBC driver found!
java.lang.ClassNotFoundException: org.sqlite.JDBC
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[?:1.8.0_282] {}
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoaderMixin.java:622) ~[arclight:arclight-1.16.5-1.0.16-6f9c10a] {re:mixin,re:classloading,pl:mixin:APP:mixins.arclight.bukkit.json:PluginClassLoaderMixin,pl:mixin:A}
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoaderMixin.java:96) ~[arclight:arclight-1.16.5-1.0.16-6f9c10a] {re:mixin,re:classloading,pl:mixin:APP:mixins.arclight.bukkit.json:PluginClassLoaderMixin,pl:mixin:A}
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_282] {}
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_282] {}
        at java.lang.Class.forName0(Native Method) ~[?:1.8.0_282] {}
        at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_282] {}
        at io.izzel.arclight.common.mod.util.remapper.generated.ArclightReflectionHandler_0.redirectClassForName(ArclightReflectionHandler.java:127) ~[arclight:arclight-1.16.5-1.0.16-6f9c10a] {}
        at io.izzel.arclight.common.mod.util.remapper.generated.ArclightReflectionHandler_0.redirectClassForName(ArclightReflectionHandler.java:114) ~[arclight:arclight-1.16.5-1.0.16-6f9c10a] {}
        at com.boydti.fawe.database.RollbackDatabase.openConnection(RollbackDatabase.java:315) ~[?:?] {re:classloading,re:classloading,re:classloading,re:classloading,re:classloading}
        at com.boydti.fawe.database.RollbackDatabase.<init>(RollbackDatabase.java:75) ~[?:?] {re:classloading,re:classloading,re:classloading,re:classloading,re:classloading}
        at com.boydti.fawe.database.DBHandler.getDatabase(DBHandler.java:24) ~[?:?] {re:classloading,re:classloading,re:classloading,re:classloading,re:classloading}
        at com.boydti.fawe.logging.rollback.RollbackOptimizedHistory.close(RollbackOptimizedHistory.java:95) ~[?:?] {re:classloading,re:classloading,re:classloading,re:classloading,re:classloading}
        at com.boydti.fawe.object.changeset.AbstractChangeSet.lambda$closeAsync$0(AbstractChangeSet.java:70) ~[?:?] {re:classloading,re:classloading,re:classloading,re:classloading,re:classloading}
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:81) [arclight:arclight-1.16.5-1.0.16-6f9c10a] {re:classloading}
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) [arclight:arclight-1.16.5-1.0.16-6f9c10a] {re:classloading}
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_282] {}
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_282] {}
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_282] {}
```

</details>

I found an output during start sever:

```
org.xerial:sqlite-jdbc:3.34.0 failed to download:
  (1) File sha1 mismatch, expect fd29bb0124e3f79c80b2753162a6a3873c240bcf found 307a48bc3515500a1eee086125ed473c4fd4c057: https://arclight.mcxk.net/org/xerial/sqlite-jdbc/3.34.0/sqlite-jdbc-3.34.0.jar
```

Guess it cause previous error

Update:

It work properly in my mainland machine.

**Comment by ghost** [comment]
This plugin works correctly! You can close this topic.
Use last build FAWE

**Comment by liampearson96** [comment]
The plugin version gives me the same error, however the mod version works correctly.

**Comment by Matthysse** [comment]
@DeZoWaRe wtf no ? Using the latest build from ArcLight and from FAWE still gives the exact same error...

**Comment by Dum4G** [comment]
Maybe some of your mods and plugins are not compatible with the plugin version of FAWE. For example forge versions of lithium and starlight are simply not expected on Paper-like servers. Try running FAWE alone on pure Arclight and probably stick it's Forge version then

**Comment by Matthysse** [comment]
I stopped using Lithium (makes the server crash randomly), but are you using it with mods? Does it works for you with the mods you use ?

**Comment by Dum4G** [comment]
Unfortunatelly, I have discovered some proper Lithium implementation just a few days before we scrapped our 1.16 season. Our server was lightly modded and we haven't tested FAWE with new performance tweaks applied. We haven't experienced any obvious crashes either

**Comment by Matthysse** [comment]
Yeah the plugin itself is green in the list, but the //wand command, and all edit commands just don't work.

**Comment by Matthysse** [comment]
And what do you mean with "proper Lithium implementation" ?

**Comment by Dum4G** [comment]
As you may remember, there were two (actually three) guys independently porting Lithium on Forge. The first version caused a lot of mixin conflicts and the second one was more accuratly made and suggested by me in my performance guide

**Comment by Matthysse** [comment]
Oh this one : https://github.com/jamierocks/lithium-forge ?
All the devs of the ports are inactive :( sad because they were really close to something that just works.
I think I tried this one but made the server crash on normal forge.

**Comment by Matthysse** [comment]
Found the issue! Incompatibility between FAWE and the mod KotlinforForge and Adorn

**Comment by Matthysse** [comment]
it works perfectly, even with modded blocks, thanks!
