### ISSUE TITLE
Civs城镇插件后台报错刷屏

### ISSUE THREAD

**Issue by 3439798258** [IzzelAliz/Arclight#213]
### 我正在运行

* **Arclight** [arclight-1.16.5-1.0.15-7963742] 

* **你确认这是最新版吗** [否]

* **你确认所有Mod都安装了依赖** [是]

* **你确认所有插件都已更新至对应版本** [是]

* **Java** [1.8.0_141] 

* **操作系统** [Windows Server 2012 R2]

* **插件列表** 
Plugins (17): ClearEntity, Crawling, Chunky, PlaceholderAPI, GroupManager, VillagerOptimiser, BanItem, CMILib, CatSeedLogin, Vault, BloodMoon, CMI, Civs, ScoreBoard, ClearItem, TAB, XConomy
* **Mod 列表** 
[net.minecraft.server.dedicated.DedicatedServer/]: Mod List: 
? mods_folder [集成动力][前置]CyclopsCore-1.16.5-1.11.3.jar : cyclopscore (1.11.3) - 1
? mods_folder [夸克]拓展QuarkOddities-1.16.3.jar : quarkoddities (1.16.3) - 1
? mods_folder [星辉魔法][前置]astralsorcery-1.16.4-1.13.9.jar : astralsorcery (1.16.4-1.13.9) - 1
? mods_folder 【龙之息】.jar : wyrmroost (1.16.3-1.2.11) - 1
? mods_folder [集成动力][集成终端]IntegratedTerminals-1.16.5-1.1.2.jar : integratedterminals (1.1.2) - 2
? mods_folder [自动汉化与更新]i18nupdatemod-1.15-1.16-1.0.0.jar : i18nupdate (NONE) - 1
? mods_folder [物品管理器]jei-1.16.4-7.6.1.71.jar : jei (7.6.1.71) - 1
? mods_folder 【魔术师】.jar : conjurer_illager (1.0.13) - 1
? mods_folder [前置]abnormals_core-1.16.4-3.0.6.jar : abnormals_core (3.0.6) - 1
? mods_folder [机械动力][本体]Mekanism-1.16.5-10.0.21.448.jar : mekanism (10.0.21) - 1
? mods_folder [吸血鬼][前置]Guide-API-VP-1.16.4-2.2.1.jar : guideapi-vp (2.2.1) - 1
? mods_folder [机械动力]create-mc1.16.3_v0.3e.jar : create (mc1.16.3_v0.3e) - 1
? mods_folder [前置]citadel-1.6.1.jar : citadel (1.6.1) - 1
? mods_folder [AE2]应用能源2appliedenergistics2-8.2.0.jar : appliedenergistics2 (8.2.0) - 1
? mods_folder [前置]YungsApi-1.16.4-Forge-4.jar : yungsapi (1.16.4-Forge-4) - 1
? mods_folder [机械动力][发电机]MekanismGenerators-1.16.5-10.0.21.448.jar : mekanismgenerators (10.0.21) - 1
? mods_folder [JEI附属]JustEnoughResources-1.16.3-0.12.0.100.jar : jeresources (0.12.0.100) - 1
? mods_folder [吸血鬼][白天雨伞]VampiresNeedUmbrellas-1.16.4-1.1.jar : vampiresneedumbrellas (1.1) - 1
? mods_folder [沉浸工程][原油]ImmersivePetroleum-1.16.4-3.1.0-2.jar : immersivepetroleum (3.1.0-2) - 1
? maven_libs forge-1.16.5-36.0.42-universal.jar : forge (36.0.42) - 1
? mods_folder [潜力模组]supplementaries-1.16.5-0.9.25.jar : supplementaries (1.16.5-0.9.25) - 1
? mods_folder [下界合金增强]Upgraded+Netherite+1.16.4+-+1.7.1.jar : upgradednetherite (1.7.0) - 1
? mods_folder [更多箱子]ironchest-1.16.4-11.2.10.jar : ironchest (1.16.4-11.2.10) - 1
? mods_folder [前置]structure_gel-1.16.4-1.7.5.jar : structure_gel (1.7.5) - 1
? mods_folder [集成动力][集成合成学]IntegratedCrafting-1.16.4-1.0.11.jar : integratedcrafting (1.0.11) - 1
? minecraft forge-1.16.5-36.0.42-server.jar : minecraft (1.16.5) - 1
? mods_folder [海洋生物]upgrade_aquatic-1.16.5-3.0.1.jar : upgrade_aquatic (3.0.1) - 1
? mods_folder [末地]endergetic-1.16.4-3.0.0.jar : endergetic (3.0.0) - 1
? mods_folder [农夫乐事]FarmersDelight-1.16.3-0.3.2.jar : farmersdelight (1.16.3-0.3.2) - 1
? mods_folder [集成动力][前置]CommonCapabilities-1.16.5-2.5.6.jar : commoncapabilities (2.5.6) - 1
? mods_folder [魔法艺术]mana-and-artifice-1.3.0.2.jar : mana-and-artifice (1.3.0.2) - 1
? mods_folder [沉浸工程][本体]ImmersiveEngineering-1.16.5-4.2.4-134.jar : immersiveengineering (1.16.5-4.2.4-134) - 1
? mods_folder [机械动力][附加]MekanismAdditions-1.16.5-10.0.21.448.jar : mekanismadditions (10.0.21) - 1
? mods_folder [末地]EndRemastered-R352.jar : endrem (1.16.3) - 1
? mods_folder [优化][区块]ChunkAnimator-1.16.5-1.2.3.jar : chunkanimator (1.16.5-1.2.3) - 1
? mods_folder [植物魔法][本体]Botania-1.16.4-414.jar : botania (1.16.4-414) - 1
? mods_folder [JEI附属]jeiintegration_1.16.4-6.1.1.11.jar : jeiintegration (6.1.1.11) - 1
? mods_folder [前置]curios-forge-1.16.5-4.0.4.0.jar : curios (1.16.5-4.0.4.0) - 1
? mods_folder [饰品]Artifacts-1.16.5-2.7.7.jar : artifacts (1.16.5-2.7.7) - 1
? mods_folder [前置]Patchouli-1.16.4-48.jar : patchouli (1.16.4-48) - 1
? mods_folder [刌民增强]savageandravage-1.16.4-3.0.0.jar : savageandravage (3.0.0) - 1
? mods_folder [集成动力][本体]IntegratedDynamics-1.16.5-1.5.0.jar : integrateddynamics (1.5.0) - 2
? mods_folder [安全工艺][1.16.5]+SecurityCraft+v1.8.21.1.jar : securitycraft (v1.8.21.1) - 1
? mods_folder [前置]AutoRegLib-1.6-47.jar : autoreglib (1.6-47) - 1
? mods_folder [集成动力][集成管道]IntegratedTunnels-1.16.4-1.6.16.jar : integratedtunnels (1.6.16) - 2
? mods_folder [墓碑]tombstone-1.16-6.3.1.jar : tombstone (1.16-6.3.1) - 1
? mods_folder [夸克]本体Quark-r2.4-307.jar : quark (r2.4-307) - 1
? mods_folder [机械动力][工具]MekanismTools-1.16.5-10.0.21.448.jar : mekanismtools (10.0.21) - 1
? mods_folder [吸血鬼][本体]Vampirism-1.16.4-1.7.7.jar : vampirism (1.7.7) - 2
? mods_folder [吸血鬼][附属]VampirismIntegrations-1.16.4-1.5.0.jar : vampirism_integrations (1.5.0) - 1
? mods_folder [星辉魔法]observerlib-1.16.4-1.5.1.jar : observerlib (1.16.4-1.5.1) - 1
? arclight arclight-forge-1.16-1.0.15.jar : arclight (1.16.5-1.0.15-7963742) - 1
? mods_folder 【水产养殖2】.jar : aquaculture (1.16.5-2.1.15) - 1
? mods_folder [雕刻工艺]chiselsandbits-0.2.10-RELEASE.jar : chiselsandbits (NONE) - 1
? mods_folder [更多矿井]BetterMineshafts-Forge-1.16.4-2.0.1.jar : bettermineshafts (1.16.4-2.0.1) - 1
? mods_folder [前置]geckolib-forge-1.16.5-3.0.14.jar : geckolib3 (3.0.14) - 1
### 错误描述
civs插件在控制台一直刷错误信息，可能对服务器性能产生影响。
也有可能是和通用机械mod冲突。

### 重现步骤

1. 安装civs城镇插件
2. 进入服务器后，放置一些mod方块在城镇插件的所属领域内互动
3. 开始刷屏报错

**可在 Forge 复现** [是]

**可在 Spigot 复现** [是]

### 报错信息

[错误日志]
[Minecraft/]: Could not pass event InventoryClickEvent to Civs v1.7.6
org.bukkit.event.EventException: null
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[arclight:arclight-1.16.5-1.0.15-7963742]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[arclight:arclight-1.16.5-1.0.15-7963742]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[arclight:arclight-1.16.5-1.0.15-7963742]
	at net.minecraft.network.play.ServerPlayNetHandler.func_147351_a(ServerPlayNetHandlerMixin.java:2941) ~[?:?]
	at net.minecraft.network.play.client.CClickWindowPacket.func_148833_a(CClickWindowPacket.java:34) ~[?:?]
	at net.minecraft.network.play.client.CClickWindowPacket.func_148833_a(CClickWindowPacket.java:12) ~[?:?]
	at net.minecraft.network.PacketThreadUtil.md7e3977$lambda$checkThreadAndEnqueue$0$0(PacketThreadUtilMixin.java:536) ~[?:?]
	at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144) ~[?:?]
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServerMixin.java:734) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServerMixin.java:159) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServerMixin.java:717) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServerMixin.java:711) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213160_bf(SourceFile:103) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServerMixin.java:696) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServerMixin.java:1903) ~[?:?]
	at net.minecraft.server.MinecraftServer.lambda$startServer$0(MinecraftServerMixin.java:232) ~[?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.ClassCastException: class io.izzel.arclight.common.mod.server.block.ArclightTileInventory cannot be cast to class org.bukkit.block.Chest (io.izzel.arclight.common.mod.server.block.ArclightTileInventory and org.bukkit.block.Chest are in unnamed module of loader cpw.mods.modlauncher.TransformingClassLoader @e26a3df)
	at org.redcastlemedia.multitallented.civs.civilians.CivilianListener.onCivilianClickItem(CivilianListener.java:764) ~[?:?]
	... 20 more

[Server thread/ERROR] [Minecraft/]: Could not pass event InventoryClickEvent to Civs v1.7.6
org.bukkit.event.EventException: null
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[arclight:arclight-1.16.5-1.0.15-7963742]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[arclight:arclight-1.16.5-1.0.15-7963742]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[arclight:arclight-1.16.5-1.0.15-7963742]
	at net.minecraft.network.play.ServerPlayNetHandler.func_147351_a(ServerPlayNetHandlerMixin.java:2941) ~[?:?]
	at net.minecraft.network.play.client.CClickWindowPacket.func_148833_a(CClickWindowPacket.java:34) ~[?:?]
	at net.minecraft.network.play.client.CClickWindowPacket.func_148833_a(CClickWindowPacket.java:12) ~[?:?]
	at net.minecraft.network.PacketThreadUtil.mdbd90f6$lambda$checkThreadAndEnqueue$0$0(PacketThreadUtilMixin.java:536) ~[?:?]
	at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144) ~[?:?]
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServerMixin.java:734) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServerMixin.java:159) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServerMixin.java:717) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServerMixin.java:711) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213160_bf(SourceFile:103) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServerMixin.java:696) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServerMixin.java:1903) ~[?:?]
	at net.minecraft.server.MinecraftServer.lambda$startServer$0(MinecraftServerMixin.java:232) ~[?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.ClassCastException: class io.izzel.arclight.common.mod.server.block.ArclightTileInventory cannot be cast to class org.bukkit.block.Chest (io.izzel.arclight.common.mod.server.block.ArclightTileInventory and org.bukkit.block.Chest are in unnamed module of loader cpw.mods.modlauncher.TransformingClassLoader @200d1a3d)
	at org.redcastlemedia.multitallented.civs.civilians.CivilianListener.onCivilianClickItem(CivilianListener.java:764) ~[?:?]
	... 20 more

[Server thread/ERROR] [Minecraft/]: Could not pass event InventoryClickEvent to Civs v1.7.6
org.bukkit.event.EventException: null
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[arclight:arclight-1.16.5-1.0.15-7963742]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[arclight:arclight-1.16.5-1.0.15-7963742]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[arclight:arclight-1.16.5-1.0.15-7963742]
	at net.minecraft.network.play.ServerPlayNetHandler.func_147351_a(ServerPlayNetHandlerMixin.java:2941) ~[?:?]
	at net.minecraft.network.play.client.CClickWindowPacket.func_148833_a(CClickWindowPacket.java:34) ~[?:?]
	at net.minecraft.network.play.client.CClickWindowPacket.func_148833_a(CClickWindowPacket.java:12) ~[?:?]
	at net.minecraft.network.PacketThreadUtil.mdbd90f6$lambda$checkThreadAndEnqueue$0$0(PacketThreadUtilMixin.java:536) ~[?:?]
	at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144) ~[?:?]
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServerMixin.java:734) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServerMixin.java:159) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServerMixin.java:717) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServerMixin.java:711) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213160_bf(SourceFile:103) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServerMixin.java:696) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServerMixin.java:1903) ~[?:?]
	at net.minecraft.server.MinecraftServer.lambda$startServer$0(MinecraftServerMixin.java:232) ~[?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]

**Comment by IzzelAliz** [comment]
请提供是与什么方块互动造成的错误

以及这个东西我很可能无法修复，建议与插件开发者联系
