### ISSUE TITLE
Bug Modpack Craft Of Exile Disonance !

### ISSUE THREAD

**Issue by Tealwen** [IzzelAliz/Arclight#225]
### I am running

* **Arclight** arclight-1.15.2-1.0.18-c1ccac9 

* **This is the latest development version** [Y/N, because ___]

* **Java** java version "1.8.0_281"
Java(TM) SE Runtime Environment (build 1.8.0_281-b09)
Java HotSpot(TM) 64-Bit Server VM (build 25.281-b09, mixed mode) 

* **Operating System** Windows 10

* **Plugins** 

* **Mods** 
Modpack Craft Of Exile Disonnance 

### Description

Crash on startup

### Step to reproduce

1. Install modpack

**Reproducible in Forge** [Y/N]

**Reproducible in Spigot** [Y/N]

Logs : 
`[18:23:21] [main/FATAL] [mixin/]: Mixin apply failed mixins.arclight.core.json:entity.LivingEntityMixin -> net.minecraft.entity.LivingEntity: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException @At("INVOKE") on net/minecraft/entity/LivingEntity::arclight$stopGlide with priority 500 cannot inject into net/minecraft/entity/LivingEntity::func_213352_e(Lnet/minecraft/util/math/Vec3d;)V merged by com.performant.coremod.mixin.entity.LivingEntityMixin with priority 998 [PREINJECT Applicator Phase -> mixins.arclight.core.json:entity.LivingEntityMixin -> Prepare Injections ->  -> redirect$zfn000$arclight$stopGlide(Lnet/minecraft/entity/LivingEntity;IZ)V -> Prepare]
org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: @At("INVOKE") on net/minecraft/entity/LivingEntity::arclight$stopGlide with priority 500 cannot inject into net/minecraft/entity/LivingEntity::func_213352_e(Lnet/minecraft/util/math/Vec3d;)V merged by com.performant.coremod.mixin.entity.LivingEntityMixin with priority 998 [PREINJECT Applicator Phase -> mixins.arclight.core.json:entity.LivingEntityMixin -> Prepare Injections ->  -> redirect$zfn000$arclight$stopGlide(Lnet/minecraft/entity/LivingEntity;IZ)V -> Prepare]
        at org.spongepowered.asm.mixin.injection.code.Injector.findTargetNodes(Injector.java:293) ~[mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown] {}
        at org.spongepowered.asm.mixin.injection.code.Injector.find(Injector.java:240) ~[mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown] {}
        at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.prepare(InjectionInfo.java:375) ~[mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown] {}
        at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1255) ~[mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown] {}
        at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1033) ~[mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown] {}
        at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:388) ~[mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown] {}
        at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:320) ~[mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown] {}
        at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345) ~[mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown] {}
        at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:569) ~[mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown] {}
        at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351) ~[mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown] {}
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:223) ~[mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown] {}
        at org.spongepowered.asm.mixin.transformer.MixinTransformationHandler.processClass(MixinTransformationHandler.java:121) ~[mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown] {}
        at org.spongepowered.asm.launch.MixinLaunchPlugin.processClass(MixinLaunchPlugin.java:131) ~[mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown] {}
        at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:85) ~[modlauncher-5.1.2.jar:?] {}
        at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:115) ~[modlauncher-5.1.2.jar:?] {}
        at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:247) ~[modlauncher-5.1.2.jar:?] {}
        at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:134) ~[modlauncher-5.1.2.jar:?] {}
        at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:96) ~[modlauncher-5.1.2.jar:?] {}
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_281] {}
        at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_281] {}
        at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:1.8.0_281] {}
        at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:1.8.0_281] {}
        at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:135) ~[modlauncher-5.1.2.jar:?] {}
        at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:96) ~[modlauncher-5.1.2.jar:?] {}
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_281] {}
        at java.lang.Class.getDeclaredMethods0(Native Method) ~[?:1.8.0_281] {}
        at java.lang.Class.privateGetDeclaredMethods(Unknown Source) ~[?:1.8.0_281] {}
        at java.lang.Class.privateGetMethodRecursive(Unknown Source) ~[?:1.8.0_281] {}
        at java.lang.Class.getMethod0(Unknown Source) ~[?:1.8.0_281] {}
        at java.lang.Class.getMethod(Unknown Source) ~[?:1.8.0_281] {}
        at net.minecraftforge.fml.loading.FMLServerLaunchProvider.lambda$launchService$0(FMLServerLaunchProvider.java:51) ~[forge-1.15.2-31.2.48.jar:31.2] {}
        at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-5.1.2.jar:?] {}
        at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-5.1.2.jar:?] {}
        at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-5.1.2.jar:?] {}
        at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-5.1.2.jar:?] {}
        at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-5.1.2.jar:?] {}
        at net.minecraftforge.server.ServerMain$Runner.runLauncher(ServerMain.java:63) [forge-1.15.2-31.2.48.jar:?] {}
        at net.minecraftforge.server.ServerMain$Runner.access$100(ServerMain.java:60) [forge-1.15.2-31.2.48.jar:?] {}
        at net.minecraftforge.server.ServerMain.main(ServerMain.java:57) [forge-1.15.2-31.2.48.jar:?] {}
        at io.izzel.arclight.common.ArclightMain.run(ArclightMain.java:46) [arclight-forge-1.15-1.0.18.jar:arclight-1.15.2-1.0.18-c1ccac9] {}
        at io.izzel.arclight.server.Main_1_15.main(Main_1_15.java:10) [arclight-forge-1.15-1.0.18.jar:arclight-1.15.2-1.0.18-c1ccac9] {}
Exception in thread "main" [18:23:21] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
[18:23:21] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]:         at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
[18:23:21] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]:         at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:223)
[18:23:21] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]:         at org.spongepowered.asm.mixin.transformer.MixinTransformationHandler.processClass(MixinTransformationHandler.java:121)
[18:23:21] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]:         at org.spongepowered.asm.launch.MixinLaunchPlugin.processClass(MixinLaunchPlugin.java:131)
[18:23:21] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]:         at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:85)
[18:23:21] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]:         at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:115)
[18:23:21] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]:         at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:247)
[18:23:21] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]:         at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:134)
[18:23:21] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]:         at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:96)
[18:23:21] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]:         at java.lang.ClassLoader.loadClass(Unknown Source)
[18:23:21] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]:         at java.lang.ClassLoader.defineClass1(Native Method)
[18:23:21] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]:         at java.lang.ClassLoader.defineClass(Unknown Source)
[18:23:21] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]:         at java.lang.ClassLoader.defineClass(Unknown Source)
[18:23:21] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]:         at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:135)
[18:23:21] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]:         at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:96)
[18:23:21] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]:         at java.lang.ClassLoader.loadClass(Unknown Source)
[18:23:21] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]:         at java.lang.Class.getDeclaredMethods0(Native Method)
[18:23:21] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]:         at java.lang.Class.privateGetDeclaredMethods(Unknown Source)
[18:23:21] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]:         at java.lang.Class.privateGetMethodRecursive(Unknown Source)
[18:23:21] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]:         at java.lang.Class.getMethod0(Unknown Source)
[18:23:21] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]:         at java.lang.Class.getMethod(Unknown Source)
[18:23:21] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]:         at net.minecraftforge.fml.loading.FMLServerLaunchProvider.lambda$launchService$0(FMLServerLaunchProvider.java:51)
[18:23:21] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]:         at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
[18:23:21] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]:         at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
[18:23:21] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]:         at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
[18:23:21] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]:         at cpw.mods.modlauncher.Launcher.run(Launcher.java:81)
[18:23:21] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]:         at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)
[18:23:21] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]:         at net.minecraftforge.server.ServerMain$Runner.runLauncher(ServerMain.java:63)
[18:23:21] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]:         at net.minecraftforge.server.ServerMain$Runner.access$100(ServerMain.java:60)
[18:23:21] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]:         at net.minecraftforge.server.ServerMain.main(ServerMain.java:57)
[18:23:21] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]:         at io.izzel.arclight.common.ArclightMain.run(ArclightMain.java:46)
[18:23:21] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]:         at io.izzel.arclight.server.Main_1_15.main(Main_1_15.java:10)
[18:23:21] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [mixins.arclight.core.json:entity.LivingEntityMixin] from phase [DEFAULT] in config [mixins.arclight.core.json] FAILED during APPLY
[18:23:21] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]:         at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:642)
[18:23:21] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]:         at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:594)
[18:23:21] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]:         at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:356)
[18:23:21] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]:         ... 31 more
[18:23:21] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: Caused by: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: @At("INVOKE") on net/minecraft/entity/LivingEntity::arclight$stopGlide with priority 500 cannot inject into net/minecraft/entity/LivingEntity::func_213352_e(Lnet/minecraft/util/math/Vec3d;)V merged by com.performant.coremod.mixin.entity.LivingEntityMixin with priority 998 [PREINJECT Applicator Phase -> mixins.arclight.core.json:entity.LivingEntityMixin -> Prepare Injections ->  -> redirect$zfn000$arclight$stopGlide(Lnet/minecraft/entity/LivingEntity;IZ)V -> Prepare]
[18:23:21] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]:     at org.spongepowered.asm.mixin.injection.code.Injector.findTargetNodes(Injector.java:293)
[18:23:21] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]:     at org.spongepowered.asm.mixin.injection.code.Injector.find(Injector.java:240)
[18:23:21] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]:     at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.prepare(InjectionInfo.java:375)
[18:23:21] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]:     at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1255)
[18:23:21] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]:     at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1033)
[18:23:21] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]:     at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:388)
[18:23:21] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]:     at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:320)
[18:23:21] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]:     at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345)
[18:23:21] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]:     at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:569)
[18:23:21] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]:     at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351)
[18:23:21] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]:     ... 31 more`

**Comment by IzzelAliz** [comment]
Remove performant, please read FAQ first.
