### ISSUE TITLE
Performant Crash server

### ISSUE THREAD

**Issue by ghost** [IzzelAliz/Arclight#238]
Arclight version arclight-1.16.5-1.0.17-831b37b (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)

This is the latest development version [Y]

* **Java** 11

* **Operating System** Linux Unbuntu 8

* **Plugins** (7): Chatty, LightAPI, ProtocolLib, eco, AuthMe, EcoEnchants, InteractionVisualizer

* **Mods** 
* • minecraft forge-1.16.5-36.1.4-server.jar : minecraft (1.16.5) - 1
• mods_folder byg-1.1.14.jar : byg (1.1.14) - 1
• maven_libs forge-1.16.5-36.1.4-universal.jar : forge (36.1.4) - 1
• mods_folder ferritecore-2.0.4-forge.jar : ferritecore (2.0.4) - 1
• arclight server.jar : arclight (1.16.5-1.0.17-831b37b) - 1

### Description

When the server starts, I instantly catch a fall.
After uninstalling the mod that crashed the server, it encountered another error during loading

`[16:02:05] [Thread-11/INFO] [STDERR/]: [org.bukkit.command.defaults.VersionCommand:getDistance:252]: java.io.IOException: Server returned HTTP response code: 401 for URL: https://hub.spigotmc.org/stash/rest/api/1.0/projects/SPIGOT/repos/craftbukkit/commits?since=831b37b&withCounts=true
[16:02:05] [Thread-11/INFO] [STDERR/]: [org.bukkit.command.defaults.VersionCommand:getDistance:252]:    at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1924)
[16:02:05] [Thread-11/INFO] [STDERR/]: [org.bukkit.command.defaults.VersionCommand:getDistance:252]:    at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1520)
[16:02:05] [Thread-11/INFO] [STDERR/]: [org.bukkit.command.defaults.VersionCommand:getDistance:252]:    at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:250)
[16:02:05] [Thread-11/INFO] [STDERR/]: [org.bukkit.command.defaults.VersionCommand:getDistance:252]:    at java.base/java.net.URL.openStream(URL.java:1140)
[16:02:05] [Thread-11/INFO] [STDERR/]: [org.bukkit.command.defaults.VersionCommand:getDistance:252]:    at com.google.common.io.Resources$UrlByteSource.openStream(Resources.java:72)
[16:02:05] [Thread-11/INFO] [STDERR/]: [org.bukkit.command.defaults.VersionCommand:getDistance:252]:    at com.google.common.io.ByteSource$AsCharSource.openStream(ByteSource.java:456)
[16:02:05] [Thread-11/INFO] [STDERR/]: [org.bukkit.command.defaults.VersionCommand:getDistance:252]:    at com.google.common.io.CharSource.openBufferedStream(CharSource.java:107)
[16:02:05] [Thread-11/INFO] [STDERR/]: [org.bukkit.command.defaults.VersionCommand:getDistance:252]:    at org.bukkit.command.defaults.VersionCommand.getDistance(VersionCommand.java:241)
[16:02:05] [Thread-11/INFO] [STDERR/]: [org.bukkit.command.defaults.VersionCommand:getDistance:252]:    at org.bukkit.command.defaults.VersionCommand.obtainVersion(VersionCommand.java:192)
[16:02:05] [Thread-11/INFO] [STDERR/]: [org.bukkit.command.defaults.VersionCommand:getDistance:252]:    at org.bukkit.command.defaults.VersionCommand.access$0(VersionCommand.java:187)
[16:02:05] [Thread-11/INFO] [STDERR/]: [org.bukkit.command.defaults.VersionCommand:getDistance:252]:    at org.bukkit.command.defaults.VersionCommand$1.run(VersionCommand.java:178)
[16:02:05] [Thread-11/INFO] [STDERR/]: [org.bukkit.command.defaults.VersionCommand:getDistance:252]:    at java.base/java.lang.Thread.run(Thread.java:834)
[16:02:05] [Thread-11/INFO] [STDERR/]: [org.bukkit.command.defaults.VersionCommand:getDistance:252]: java.io.IOException: Server returned HTTP response code: 401 for URL: https://hub.spigotmc.org/stash/rest/api/1.0/projects/SPIGOT/repos/spigot/commits?since=1.0.17&withCounts=true
[16:02:05] [Thread-11/INFO] [STDERR/]: [org.bukkit.command.defaults.VersionCommand:getDistance:252]:    at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1924)
[16:02:05] [Thread-11/INFO] [STDERR/]: [org.bukkit.command.defaults.VersionCommand:getDistance:252]:    at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1520)
[16:02:05] [Thread-11/INFO] [STDERR/]: [org.bukkit.command.defaults.VersionCommand:getDistance:252]:    at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:250)
[16:02:05] [Thread-11/INFO] [STDERR/]: [org.bukkit.command.defaults.VersionCommand:getDistance:252]:    at java.base/java.net.URL.openStream(URL.java:1140)
[16:02:05] [Thread-11/INFO] [STDERR/]: [org.bukkit.command.defaults.VersionCommand:getDistance:252]:    at com.google.common.io.Resources$UrlByteSource.openStream(Resources.java:72)
[16:02:05] [Thread-11/INFO] [STDERR/]: [org.bukkit.command.defaults.VersionCommand:getDistance:252]:    at com.google.common.io.ByteSource$AsCharSource.openStream(ByteSource.java:456)
[16:02:05] [Thread-11/INFO] [STDERR/]: [org.bukkit.command.defaults.VersionCommand:getDistance:252]:    at com.google.common.io.CharSource.openBufferedStream(CharSource.java:107)
[16:02:05] [Thread-11/INFO] [STDERR/]: [org.bukkit.command.defaults.VersionCommand:getDistance:252]:    at org.bukkit.command.defaults.VersionCommand.getDistance(VersionCommand.java:241)
[16:02:05] [Thread-11/INFO] [STDERR/]: [org.bukkit.command.defaults.VersionCommand:getDistance:252]:    at org.bukkit.command.defaults.VersionCommand.obtainVersion(VersionCommand.java:193)
[16:02:05] [Thread-11/INFO] [STDERR/]: [org.bukkit.command.defaults.VersionCommand:getDistance:252]:    at org.bukkit.command.defaults.VersionCommand.access$0(VersionCommand.java:187)
[16:02:05] [Thread-11/INFO] [STDERR/]: [org.bukkit.command.defaults.VersionCommand:getDistance:252]:    at org.bukkit.command.defaults.VersionCommand$1.run(VersionCommand.java:178)
[16:02:05] [Thread-11/INFO] [STDERR/]: [org.bukkit.command.defaults.VersionCommand:getDistance:252]:    at java.base/java.lang.Thread.run(Thread.java:834)
[16:02:05] [Thread-11/INFO] [Console/]: Error obtaining version information`

### Step to reproduce

1. Install Performant
2. Install Ferritecore
3. Install Oh The Biomes You'll Go

**Reproducible in Forge** [Y]

**Reproducible in Spigot** [Nope]

### Logs

[ERROR LOG]

[Logs here]
</pre>
[latest.log](https://github.com/IzzelAliz/Arclight/files/6339100/latest.log)
</details>

-->

**Comment by ahdg6** [comment]
Read FAQ first

**Comment by IzzelAliz** [comment]
Performant compatibility won't be worked on.
