### ISSUE TITLE
Plugin error Ultimate Mob Heads Fork, Ishop 

### ISSUE THREAD

**Issue by ghost** [IzzelAliz/Arclight#258]
**Arclight [1.16.5-1.0.17-831b37b]

This is the latest development version [N]

Java [11]

Operating System [Unbuntu 20]

Plugins: iShop 2.14, Ultimate Mob Heads Fork 4.0b

Mods • AI-Improvements-1.16.2-0.3.0.jar

Description
Space between the two plugins!

1 **Ishops** - when entering /ishop shops gives an error

`[07May2021 11:20:42.045] [Server thread/INFO] [net.minecraft.network.play.ServerPlayNetHandler/]: DeZoWaRe issued server command: /ishop shops
[07May2021 11:20:42.063] [Craft Scheduler Thread - 81/WARN] [iShop/]: Plugin iShop v2.13 generated an exception while executing task 1071793
java.lang.NullPointerException: null
	at java.util.regex.Matcher.appendExpandedReplacement(Matcher.java:1015) ~[?:?]
	at java.util.regex.Matcher.appendReplacement(Matcher.java:998) ~[?:?]
	at java.util.regex.Matcher.replaceAll(Matcher.java:1182) ~[?:?]
	at java.lang.String.replaceAll(String.java:2126) ~[?:?]
	at com.minedhype.ishop.inventories.InvShopList.getShopList(InvShopList.java:84) ~[?:?]
	at com.minedhype.ishop.inventories.InvShopList.lambda$open$3(InvShopList.java:109) ~[?:?]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:81) ~[arclight:arclight-1.16.5-1.0.17-831b37b]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) [arclight:arclight-1.16.5-1.0.17-831b37b]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]`

2.Ultimate Mob Heads Fork 4.0b
Kill the mob. Mob head not droped and log error

`[07May2021 10:39:49.824] [Server thread/ERROR] [Minecraft/]: Could not pass event EntityDeathEvent to MobHeads v4.0
org.bukkit.event.EventException: null
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[serv.jar:arclight-1.16.5-1.0.17-831b37b]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[serv.jar:arclight-1.16.5-1.0.17-831b37b]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[serv.jar:arclight-1.16.5-1.0.17-831b37b]
	at io.izzel.arclight.common.mod.server.event.ArclightEventFactory.callEvent(ArclightEventFactory.java:20) ~[serv.jar:arclight-1.16.5-1.0.17-831b37b]
	at io.izzel.arclight.common.mod.server.event.ArclightEventFactory.callEntityDeathEvent(ArclightEventFactory.java:38) ~[serv.jar:arclight-1.16.5-1.0.17-831b37b]
	at io.izzel.arclight.common.mod.server.event.EntityEventDispatcher.onLivingDeath(EntityEventDispatcher.java:38) ~[serv.jar:arclight-1.16.5-1.0.17-831b37b]
	at net.minecraftforge.eventbus.ASMEventHandler_14_EntityEventDispatcher_onLivingDeath_LivingDropsEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.common.ForgeHooks.onLivingDrops(ForgeHooksMixin.java:378) ~[forge:?]
	at net.minecraft.entity.LivingEntity.func_213345_d(LivingEntityMixin.java:1249) ~[?:?]
	at net.minecraft.entity.LivingEntity.func_70645_a(LivingEntityMixin.java:1202) ~[?:?]
	at net.minecraft.entity.LivingEntity.func_70097_a(LivingEntityMixin.java:3894) ~[?:?]
	at net.minecraft.entity.monster.MonsterEntity.func_70097_a(SourceFile:73) ~[?:?]
	at net.minecraft.entity.monster.ZombieEntity.func_70097_a(ZombieEntityMixin.java:262) ~[?:?]
	at net.minecraft.entity.player.PlayerEntity.func_71059_n(PlayerEntityMixin.java:2458) ~[?:?]
	at net.minecraft.entity.player.ServerPlayerEntity.func_71059_n(ServerPlayerEntityMixin.java:1292) ~[?:?]
	at net.minecraft.network.play.ServerPlayNetHandler.func_147340_a(ServerPlayNetHandlerMixin.java:2676) ~[?:?]
	at net.minecraft.network.play.client.CUseEntityPacket.func_148833_a(SourceFile:74) ~[?:?]
	at net.minecraft.network.play.client.CUseEntityPacket.func_148833_a(SourceFile:13) ~[?:?]
	at net.minecraft.network.PacketThreadUtil.md4d3f6b$lambda$checkThreadAndEnqueue$0$0(PacketThreadUtilMixin.java:536) ~[?:?]
	at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144) ~[?:?]
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServerMixin.java:734) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServerMixin.java:159) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServerMixin.java:717) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServerMixin.java:711) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213160_bf(SourceFile:103) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServerMixin.java:696) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServerMixin.java:1903) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServerMixin.java:232) ~[?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.UnsupportedOperationException
	at java.util.AbstractList.add(AbstractList.java:153) ~[?:?]
	at java.util.AbstractList.add(AbstractList.java:111) ~[?:?]
	at com.cyber.mobheads.listeners.EntityDeathListener.onEntityDeath(EntityDeathListener.java:167) ~[?:?]
	... 35 more`

Step to reproduce
Install
https://www.spigotmc.org/resources/ishop.84555/?__cf_chl_jschl_tk__=db1493fc66dbdb3d209e4e75e6062cbfbc57e727-1620379032-0-AYa4UsfeMXlzdqovR-QmqriIZWTLlAFakEA9ZceYndRunJakES5H7KgxX8QLyT8d328gOpGMkPqWkVpb1815SF5bKDf6yppyfxyZPAPJeAecRL-1HuoeNoabSdpq83yZycvIS4ao-dfLNJtN78sSFUNu0vTDosLNgfwraILayNAq3jl_Gll5utUNVeqsCQaIKJKr6sn6xxpEDafrOpDfsLapY2itO522d2qJ9yDi_0QMdFeOH-yb8bEfoPkEzUISBQq6Cc1HxzeHYWuIkax66v5sPc1GMff464Fps89P_o72Q4iH0XTYNRD0jf_mUKT4E02m0vDt11BW6iG2iPbaC6lB01ZoYpPOhxJgQJaOBjy_XWjHtc-QXpnM_-iayyKjkBgcsk2h-sKCCoSrmEx3esFb3qwV1SG6cNVftWZFn3z5

https://www.spigotmc.org/resources/ultimate-mob-heads-fork.70019/ **SUPPORT 1.16!**

Reproducible in Forge [N]

Reproducible in Spigot [Y]

**Comment by timi137137** [comment]
The memo:  https://paste.ubuntu.com/p/dsqZhNsRpX/

i am testing，don't worry

**Comment by ghost** [comment]
> i am testing，don't worry

Ok, thanks

**Comment by timi137137** [comment]
OK, first bug"when entering /ishop shops gives an error."
is It doesn't exist，maybe you setting error? you can try del old setting,and then try again.

second,Ultimate Mob Heads Fork 4.0b have this bug, It's not our problem.because this plugin try add something,but he can't add.so maybe you should go to Mob Heads repo report this bug

thank you issue
Wish you a happy life.

**Comment by imDaniX** [comment]
> second,Ultimate Mob Heads Fork 4.0b have this bug, It's not our problem.because this plugin try add something,but he can't add.so maybe you should go to Mob Heads repo report this bug

No way. You're using `Lists.transform` there
https://github.com/IzzelAliz/Arclight/blob/5e73c75a53b60379d35fba35d3945ee9a5fcbad4/arclight-common/src/main/java/io/izzel/arclight/common/mod/server/event/EntityEventDispatcher.java#L36-L38
and according to [JavaDocs](https://guava.dev/releases/19.0/api/docs/com/google/common/collect/Lists.html#transform(java.util.List,%20com.google.common.base.Function)), it makes adding methods impossible to use.

**Comment by ghost** [comment]
> Ultimate Mob Heads Fork

It does not work correctly only on this fork.

**Comment by timi137137** [comment]
> > Ultimate Mob Heads Fork
> 
> It does not work correctly only on this fork.

OK,I'm working on the issue with the author, so wait for updates

**Comment by IzzelAliz** [comment]
Please test with latest build

**Comment by ghost** [comment]
> Please test with latest build

I'm use /mobhead give DeZoWaRe Bee

`**[18:42:55] [Server thread/INFO] [minecraft/ServerPlayNetHandler]: DeZoWaRe issued server command: /mobhead give DeZoWaRe[18:42:56] [Server thread/INFO] [minecraft/ServerPlayNetHandler]: DeZoWaRe issued server command: /mobhead give DeZoWaRe Bee

_[18:42:57] [Server thread/INFO] [STDERR/]: [org.bukkit.craftbukkit.v1_16_R3.legacy.CraftLegacy:<clinit>:257]: Initializing Legacy Material Support. Unless you have legacy plugins and/or data this is a bug!_**`

**But at the same time, the head of the mob was issued, when you re-enter the message below, it no longer pops up**

Ishop full fix 100%

**Comment by IzzelAliz** [comment]
The message doesn't matter.

**Comment by ghost** [comment]
> The message doesn't matter.

In this case, they work 100%, I checked all their teams!
