### ISSUE TITLE
Plugins HyEmotes don't work

### ISSUE THREAD

**Issue by ghost** [IzzelAliz/Arclight#259]
**Arclight [arclight-forge-1.16.5-1.0.18-SNAPSHOT]**

This is the latest development version [N]

Java [11]

Operating System [Unbuntu 20]

Plugins: HyEmotes

Mods • Nope

**Description**
Emotion mod refuses to work on server startup, launch on Spigot, Paper, Yatopia without a single error

`[18:54:47] [Server thread/ERROR] [Minecraft/]: Could not load 'plugins\HyEmotes.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.nio.file.InvalidPathException: Path: nul character not allowed: /ar.class
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoaderMixin.java:139) ~[arclight:arclight-1.16.5-1.0.18-SNAPSHOT-cef6d7e] {re:mixin,re:classloading,pl:mixin:APP:mixins.arclight.bukkit.json:JavaPluginLoaderMixin,pl:mixin:A}
        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:394) ~[arclight:arclight-1.16.5-1.0.18-SNAPSHOT-cef6d7e] {re:classloading}
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:301) ~[arclight:arclight-1.16.5-1.0.18-SNAPSHOT-cef6d7e] {re:classloading}
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.loadPlugins(CraftServerMixin.java:382) ~[arclight:arclight-1.16.5-1.0.18-SNAPSHOT-cef6d7e] {re:mixin,re:classloading,pl:mixin:APP:mixins.arclight.bukkit.json:CraftServerMixin,pl:mixin:A,pl:arclight_implementer:switch,pl:arclight_implementer:A}
        at net.minecraft.server.dedicated.DedicatedServer.handler$zpn000$arclight$loadPlugins(DedicatedServerMixin.java:634) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.dedicated.DedicatedServerMixin,pl:mixin:A}
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServerMixin.java:160) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.dedicated.DedicatedServerMixin,pl:mixin:A}
        at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServerMixin.java:1861) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServerMixin.java:232) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_281] {}
Caused by: java.nio.file.InvalidPathException: Path: nul character not allowed: /ar.class
        at com.sun.nio.zipfs.ZipPath.normalize(ZipPath.java:448) ~[zipfs.jar:1.8.0_281] {}
        at com.sun.nio.zipfs.ZipPath.<init>(ZipPath.java:76) ~[zipfs.jar:1.8.0_281] {}
        at com.sun.nio.zipfs.ZipPath.<init>(ZipPath.java:67) ~[zipfs.jar:1.8.0_281] {}
        at com.sun.nio.zipfs.ZipFileSystem.getPath(ZipFileSystem.java:186) ~[zipfs.jar:1.8.0_281] {}
        at com.sun.nio.zipfs.ZipFileSystem.getPath(ZipFileSystem.java:80) ~[zipfs.jar:1.8.0_281] {}
        at net.minecraftforge.fml.loading.moddiscovery.ModDiscoverer$MinecraftLocator.findPathJar(ModDiscoverer.java:208) ~[forge-1.16.5-36.1.4.jar:?] {}
        at net.minecraftforge.fml.loading.moddiscovery.ModDiscoverer$MinecraftLocator.findPath(ModDiscoverer.java:195) ~[forge-1.16.5-36.1.4.jar:?] {}
        at net.minecraftforge.fml.loading.moddiscovery.ModFile.findResource(ModFile.java:180) ~[forge-1.16.5-36.1.4.jar:?] {}
        at net.minecraftforge.fml.loading.LoadingModList$1.findNextURL(LoadingModList.java:150) ~[forge-1.16.5-36.1.4.jar:36.1] {}
        at net.minecraftforge.fml.loading.LoadingModList$1.hasMoreElements(LoadingModList.java:132) ~[forge-1.16.5-36.1.4.jar:36.1] {}
        at cpw.mods.modlauncher.EnumerationHelper$1.hasMoreElements(EnumerationHelper.java:32) ~[modlauncher-8.0.9.jar:?] {}
        at cpw.mods.modlauncher.EnumerationHelper$1.hasMoreElements(EnumerationHelper.java:32) ~[modlauncher-8.0.9.jar:?] {}
        at cpw.mods.modlauncher.EnumerationHelper$1.hasMoreElements(EnumerationHelper.java:32) ~[modlauncher-8.0.9.jar:?] {}
        at cpw.mods.modlauncher.EnumerationHelper.firstElementOrNull(EnumerationHelper.java:47) ~[modlauncher-8.0.9.jar:?] {}
        at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:241) ~[modlauncher-8.0.9.jar:?] {}
        at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:136) ~[modlauncher-8.0.9.jar:?] {re:classloading}
        at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98) ~[modlauncher-8.0.9.jar:?] {re:classloading}
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_281] {}
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_281] {}
        at java.lang.Class.forName0(Native Method) ~[?:1.8.0_281] {}
        at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_281] {}
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoaderMixin.java:64) ~[arclight:arclight-1.16.5-1.0.18-SNAPSHOT-cef6d7e] {re:mixin,re:classloading,pl:mixin:APP:mixins.arclight.bukkit.json:PluginClassLoaderMixin,pl:mixin:A}
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoaderMixin.java:135) ~[arclight:arclight-1.16.5-1.0.18-SNAPSHOT-cef6d7e] {re:mixin,re:classloading,pl:mixin:APP:mixins.arclight.bukkit.json:JavaPluginLoaderMixin,pl:mixin:A}
        ... 8 more`

**Step to reproduce**

Install
https://www.spigotmc.org/resources/hyemotes-great-cosmetic-donor-perk-21-animated-emotes.22407/  #The mod is paid, I will provide you for free if necessary.

Reproducible in Forge [N]

Reproducible in Spigot [Y]

**Comment by timi137137** [comment]
Sorry,bro.i will need sleep.so maybe i must Hongkong 11AM can test this bug

I am sorry,thank you report

**Comment by ghost** [comment]
> Sorry,bro.i will need sleep.so maybe i must Hongkong 11AM can test this bug
> 
> I am sorry,thank you report

Good night

**Comment by timi137137** [comment]
This problem is remapper issue,if we fix problem.i will tell you.

**Comment by IzzelAliz** [comment]
Related to https://github.com/cpw/modlauncher/issues/50, we can't fix.
