### ISSUE TITLE
Gravit Launcher + Arclight error occurs on the plugins 1.15.2 Last build

### ISSUE THREAD

**Issue by ghost** [IzzelAliz/Arclight#260]
Hi i am trying to bind this core (version 1.15.2) to gravitlauncher when loading the server an error occurs and the plugins are not loaded

```
>  08, 2021 8:09:52 PM org.bukkit.plugin.SimplePluginManager enablePlugin
SEVERE: Error occurred (in the plugin loader) while enabling PlaceholderAPI v2.10.9 (Is it up to date?)
java.lang.NullPointerException
        at io.izzel.arclight.common.mod.util.log.ArclightPluginLogger.log(ArclightPluginLogger.java:22)
        at java.util.logging.Logger.doLog(Unknown Source)
        at java.util.logging.Logger.log(Unknown Source)
        at java.util.logging.Logger.info(Unknown Source)
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoaderMixin.java:339)
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480)
        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServerMixin.java:464)
        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServerMixin.java:2162)
        at net.minecraft.server.MinecraftServer.handler$zpd000$arclight$enablePlugins(MinecraftServerMixin.java:2049)
        at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServerMixin.java:367)
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServerMixin.java:212)
        at net.minecraft.server.MinecraftServer.run(MinecraftServerMixin.java:1933)
        at java.lang.Thread.run(Unknown Source)

 08, 2021 8:09:52 PM org.bukkit.plugin.SimplePluginManager enablePlugin
SEVERE: Error occurred (in the plugin loader) while enabling Chatty v2.18.1 (Is it up to date?)
java.lang.NullPointerException
        at io.izzel.arclight.common.mod.util.log.ArclightPluginLogger.log(ArclightPluginLogger.java:22)
        at java.util.logging.Logger.doLog(Unknown Source)
        at java.util.logging.Logger.log(Unknown Source)
        at java.util.logging.Logger.info(Unknown Source)
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoaderMixin.java:339)
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480)
        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServerMixin.java:464)
        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServerMixin.java:2162)
        at net.minecraft.server.MinecraftServer.handler$zpd000$arclight$enablePlugins(MinecraftServerMixin.java:2049)
        at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServerMixin.java:367)
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServerMixin.java:212)
        at net.minecraft.server.MinecraftServer.run(MinecraftServerMixin.java:1933)
        at java.lang.Thread.run(Unknown Source)

 08, 2021 8:09:52 PM org.bukkit.plugin.SimplePluginManager enablePlugin
SEVERE: Error occurred (in the plugin loader) while enabling spark v1.5.2 (Is it up to date?)
java.lang.NullPointerException
        at io.izzel.arclight.common.mod.util.log.ArclightPluginLogger.log(ArclightPluginLogger.java:22)
        at java.util.logging.Logger.doLog(Unknown Source)
        at java.util.logging.Logger.log(Unknown Source)
        at java.util.logging.Logger.info(Unknown Source)
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoaderMixin.java:339)
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480)
        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServerMixin.java:464)
        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServerMixin.java:2162)
        at net.minecraft.server.MinecraftServer.handler$zpd000$arclight$enablePlugins(MinecraftServerMixin.java:2049)
        at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServerMixin.java:367)
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServerMixin.java:212)
        at net.minecraft.server.MinecraftServer.run(MinecraftServerMixin.java:1933)
        at java.lang.Thread.run(Unknown Source)

 08, 2021 8:09:52 PM org.bukkit.plugin.SimplePluginManager enablePlugin
SEVERE: Error occurred (in the plugin loader) while enabling AutoRestart v4.2.1 (Is it up to date?)
java.lang.NullPointerException
        at io.izzel.arclight.common.mod.util.log.ArclightPluginLogger.log(ArclightPluginLogger.java:22)
        at java.util.logging.Logger.doLog(Unknown Source)
        at java.util.logging.Logger.log(Unknown Source)
        at java.util.logging.Logger.info(Unknown Source)
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoaderMixin.java:339)
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480)
        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServerMixin.java:464)
        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServerMixin.java:2162)
        at net.minecraft.server.MinecraftServer.handler$zpd000$arclight$enablePlugins(MinecraftServerMixin.java:2049)
        at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServerMixin.java:367)
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServerMixin.java:212)
        at net.minecraft.server.MinecraftServer.run(MinecraftServerMixin.java:1933)
        at java.lang.Thread.run(Unknown Source)

 08, 2021 8:09:52 PM io.izzel.arclight.common.mod.util.log.ArclightPluginLogger log
INFO: Enabling Essentials v2.19.0-dev+113-0d640d1
 08, 2021 8:09:52 PM io.izzel.arclight.common.mod.util.log.ArclightPluginLogger log
SEVERE: You are running a server that does not properly support Bukkit plugins. Bukkit plugins should not be used with Forge mods! Consider using ForgeEssentials, or SpongeForge + Nucleus.
 08, 2021 8:09:52 PM io.izzel.arclight.common.mod.util.log.ArclightPluginLogger log
INFO: Status determining class: net.minecraftforge.common.MinecraftForge
 08, 2021 8:09:52 PM com.earth2me.essentials.EssentialsUpgrade convertKits
INFO: Attempting to convert old kits in config.yml to new kits.yml
 08, 2021 8:09:52 PM com.earth2me.essentials.EssentialsUpgrade convertKits
INFO: No kits found to migrate.
 08, 2021 8:09:53 PM com.earth2me.essentials.items.FlatItemDb reloadConfig
INFO: Loaded 25599 items from items.json.
 08, 2021 8:09:53 PM com.earth2me.essentials.I18n updateLocale
INFO: Using locale ru_RU
 08, 2021 8:09:53 PM io.izzel.arclight.common.mod.util.log.ArclightPluginLogger log
INFO: ServerListPingEvent: Spigot iterator API
 08, 2021 8:09:54 PM io.izzel.arclight.common.mod.util.log.ArclightPluginLogger log
INFO: Starting Metrics. Opt-out using the global bStats config.
 08, 2021 8:09:54 PM io.izzel.arclight.common.mod.util.log.ArclightPluginLogger log
WARNING: Detected supported permissions plugin LuckPerms without Vault installed.
 08, 2021 8:09:54 PM io.izzel.arclight.common.mod.util.log.ArclightPluginLogger log
WARNING: Features such as chat prefixes/suffixes and group-related functionality will not work until you install Vault.
 08, 2021 8:09:54 PM io.izzel.arclight.common.mod.util.log.ArclightPluginLogger log
INFO: Using superperms-based permissions.
 08, 2021 8:09:54 PM org.bukkit.plugin.SimplePluginManager enablePlugin
SEVERE: Error occurred (in the plugin loader) while enabling EssentialsSpawn v2.19.0-dev+113-0d640d1 (Is it up to date?)
java.lang.NullPointerException
        at io.izzel.arclight.common.mod.util.log.ArclightPluginLogger.log(ArclightPluginLogger.java:22)
        at java.util.logging.Logger.doLog(Unknown Source)
        at java.util.logging.Logger.log(Unknown Source)
        at java.util.logging.Logger.info(Unknown Source)
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoaderMixin.java:339)
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480)
        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServerMixin.java:464)
        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServerMixin.java:2162)
        at net.minecraft.server.MinecraftServer.handler$zpd000$arclight$enablePlugins(MinecraftServerMixin.java:2049)
        at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServerMixin.java:367)
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServerMixin.java:212)
        at net.minecraft.server.MinecraftServer.run(MinecraftServerMixin.java:1933)
        at java.lang.Thread.run(Unknown Source)

 08, 2021 8:09:54 PM org.bukkit.plugin.SimplePluginManager enablePlugin
SEVERE: Error occurred (in the plugin loader) while enabling TAB v2.8.10 (Is it up to date?)
java.lang.NullPointerException
        at io.izzel.arclight.common.mod.util.log.ArclightPluginLogger.log(ArclightPluginLogger.java:22)
        at java.util.logging.Logger.doLog(Unknown Source)
        at java.util.logging.Logger.log(Unknown Source)
        at java.util.logging.Logger.info(Unknown Source)
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoaderMixin.java:339)
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480)
        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServerMixin.java:464)
        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServerMixin.java:2162)
        at net.minecraft.server.MinecraftServer.handler$zpd000$arclight$enablePlugins(MinecraftServerMixin.java:2049)
        at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServerMixin.java:367)
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServerMixin.java:212)
        at net.minecraft.server.MinecraftServer.run(MinecraftServerMixin.java:1933)
        at java.lang.Thread.run(Unknown Source)

 08, 2021 8:09:54 PM org.bukkit.plugin.SimplePluginManager enablePlugin
SEVERE: Error occurred (in the plugin loader) while enabling DiscordSRV v1.22.0 (Is it up to date?)
java.lang.NullPointerException
        at io.izzel.arclight.common.mod.util.log.ArclightPluginLogger.log(ArclightPluginLogger.java:22)
        at java.util.logging.Logger.doLog(Unknown Source)
        at java.util.logging.Logger.log(Unknown Source)
        at java.util.logging.Logger.info(Unknown Source)
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoaderMixin.java:339)
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480)
        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServerMixin.java:464)
        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServerMixin.java:2162)
        at net.minecraft.server.MinecraftServer.handler$zpd000$arclight$enablePlugins(MinecraftServerMixin.java:2049)
        at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServerMixin.java:367)
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServerMixin.java:212)
        at net.minecraft.server.MinecraftServer.run(MinecraftServerMixin.java:1933)
        at java.lang.Thread.run(Unknown Source)
```

**Comment by IzzelAliz** [comment]
Add these launch argument: `-Djava.util.logging.manager=io.izzel.arclight.common.mod.util.log.ArclightLazyLogManager -Dlog4j.jul.LoggerAdapter=io.izzel.arclight.common.mod.util.log.ArclightLoggerAdapter`

**Comment by dima-dencep** [comment]
thanks, worldguard still doesn't work
[11:14:40] [Server thread/ERROR] [Minecraft/]: Could not load 'plugins\worldguard-bukkit-7.0.4.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: Unsupported API version 1.16
        at org.bukkit.craftbukkit.v1_15_R1.util.CraftMagicNumbers.checkSupported(CraftMagicNumbersMixin.java:270) ~[?:arclight-1.15.2-1.0.18-c1ccac9] {re:mixin,re:classloading,pl:mixin:APP:mixins.arclight.bukkit.json:CraftMagicNumbersMixin,pl:mixin:A}
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoaderMixin.java:131) ~[?:arclight-1.15.2-1.0.18-c1ccac9] {re:mixin,re:classloading,pl:mixin:APP:mixins.arclight.bukkit.json:JavaPluginLoaderMixin,pl:mixin:A,re:mixin}
        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:394) ~[?:arclight-1.15.2-1.0.18-c1ccac9] {re:mixin,re:classloading}
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:301) [?:arclight-1.15.2-1.0.18-c1ccac9] {re:mixin,re:classloading}
        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.loadPlugins(CraftServerMixin.java:353) [?:arclight-1.15.2-1.0.18-c1ccac9] {re:mixin,re:classloading,pl:mixin:APP:mixins.arclight.bukkit.json:CraftServerMixin,pl:mixin:A}
        at net.minecraft.server.dedicated.DedicatedServer.handler$zpe000$arclight$loadPlugins(DedicatedServerMixin.java:650) [?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.dedicated.DedicatedServerMixin,pl:mixin:A}
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServerMixin.java:182) [?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.dedicated.DedicatedServerMixin,pl:mixin:A}
        at net.minecraft.server.MinecraftServer.run(MinecraftServerMixin.java:1933) [?:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,pl:mixin:A,pl:runtimedistcleaner:A}
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_281] {}

**Comment by timi137137** [comment]
Unsupported API version 1.16,maybe you should check you plugin version,this plugin only support 1.16（

**Comment by timi137137** [comment]
![image](https://user-images.githubusercontent.com/36812439/117565245-c9d1cf00-b0e2-11eb-904c-20cf69b26e3b.png)
maybe...？

**Comment by ghost** [comment]
> ![image](https://user-images.githubusercontent.com/36812439/117565245-c9d1cf00-b0e2-11eb-904c-20cf69b26e3b.png)
> maybe...？

Yes 100% work

**This version is compatible with:

CraftBukkit/Spigot for 1.14.4 or 1.15.2 (Paper recommended)
THIS VERSION IS NOT COMPATIBLE WITH VERSIONS PRIOR TO 1.14**

**Comment by timi137137** [comment]
xD，your need see GameVersion,don't see Name version（

if work,you can close this issue

**Comment by ghost** [comment]
> Add these launch argument: `-Djava.util.logging.manager=io.izzel.arclight.common.mod.util.log.ArclightLazyLogManager -Dlog4j.jul.LoggerAdapter=io.izzel.arclight.common.mod.util.log.ArclightLoggerAdapter`

Work, thanks!

I suggest adding a note to the Wiki

**Comment by timi137137** [comment]
OK，i will tell author
