### ISSUE TITLE
服务端无限崩端

### ISSUE THREAD

**Issue by HYDeath** [IzzelAliz/Arclight#271]
### 我正在运行

* **Arclight** [arclight-forge-1.16-1.0.18] 

* **你确认这是最新版吗** [是，因为___]

* **你确认所有Mod都安装了依赖** [是]

* **你确认所有插件都已更新至对应版本** [是]

* **Java** [1.8.0_292] 

* **操作系统** [CentOS Linux release 7.7.1908]

  

* **插件列表** 
DeluxeChat,Citizens2,AdvancedNMotd,CatSeedLogin,SNAPSHOT,CitizensCMD,Clearlag,CMI,LoginManager,LuckPerms-Bukkit,placeholderAPI,Residence,SkinsRestorer,TAB Premium,Vanlt
* **Mod 列表** 
[前置]【车车前置】obfuscate-0.6.0-1.16.3.jar              |Obfuscate                     |obfuscate                     |0.6.0               |DONE      |e1:59:1a:56:ec:97:b3:d0:b3:4b:25:06:1f:83:b0:f4:fd:0c:24:e3:6d:ea:94:b1:9f:22:b0:38:13:60:88:ea
		[功能]【拔刀剑附属】Yamazakura-1.16.4-r1
		[功能]【家具】furniture-7.0.0-pre19-1.16.3
		[功能]【虚无3】AoA3-3.5-1.16.5-Beta-4
		[附属]【通用机械发电机】MekanismGenerators-1.16.5-10.0.21.448
		[功能]【车车】vehicle-mod-0.45.2-1.16.3.
		[功能]【更多的雪】SnowRealMagic-1.16.4-2.5.3
		[功能]【JEI物品管理器】jei-1.16.4-7.6.1.65
		arclight-forge-1.16-1.0.18
		[功能]【搬箱子】carryon-1.16.5-1.15.3.11
		[功能]【拔刀剑2】SlashBlade-1.16-0.0.9
		[附属]【JER资源管理器】JustEnoughResources-1.16.4-0.12.0.10
		[功能]【中国风建筑】Chinese-Workshop-Mod-1.16.5
		[前置]【潘工艺前置】Kiwi-1.16.5-3.4.2
		[功能]【通用机械】Mekanism-1.16.5-10.0.21.448
		[功能]【转化桌】ProjectE-1.16.5-PE1.0.1B
		[附属]【JEI拓展】jeiintegration_1.16.4-6.1.1.11
		[功能]【机械动力】create-mc1.16.5_v0.3.1c
		[功能]【潘工艺】pamhc2foodcore-1.16.3-1.0.2
		[附属]【JEIE附魔显示】JEIEnchantmentInfo-1.16.4-1.2.1
		[功能]【更多箱子】ironchest-1.16.4-11.2.10
		[功能]【懒人厨房】CookingForBlockheads_1.16.5-9.3.1
		[功能]【连锁挖矿】OreExcavation-1.8.157
### 错误描述
玩通用机械时拆管道就崩端，到最后服务端启动完超时1分钟就一直重启，再无办法进去

### 重现步骤

 

**可在 Forge 复现** [否]

**可在 Spigot 复现** [否]

### 报错信息

[错误日志]
https://paste.ubuntu.com/p/b42GSGXT8J/

**Comment by IzzelAliz** [comment]
请用最新构建测试

**Comment by robiowu** [comment]
> 请用最新构建测试

现在最新release 还是 5/9 日的1.0.18吧。Arclight [arclight-forge-1.16-1.0.18]

**Comment by timi137137** [comment]
> > 请用最新构建测试
> 
> 现在最新release 还是 5/9 日的1.0.18吧。Arclight [arclight-forge-1.16-1.0.18]

https://github.com/IzzelAliz/Arclight/actions/runs/866588582

**Comment by robiowu** [comment]
> > > 请用最新构建测试
> > 
> > 
> > 现在最新release 还是 5/9 日的1.0.18吧。Arclight [arclight-forge-1.16-1.0.18]
> 
> https://github.com/IzzelAliz/Arclight/actions/runs/866588582

使用最新的build，服务器接受不了大部分指令了。stop和op，貌似找不到指令
 

`> stop

[17:41:01] [Server thread/WARN] [Minecraft/]: Unexpected exception while parsing console command "stop"
org.bukkit.command.CommandException: Unhandled exception executing 'stop' in org.bukkit.craftbukkit.v1_16_R3.command.VanillaCommandWrapper(stop)
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:156) ~[arclight:arclight-1.16.5-1.0.19-SNAPSHOT-5d65f21] {re:classloading}
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServerMixin.java:761) ~[arclight:arclight-1.16.5-1.0.19-SNAPSHOT-5d65f21] {re:mixin,re:classloading,pl:mixin:APP:mixins.arclight.bukkit.json:CraftServerMixin,pl:mixin:A,pl:arclight_implementer:switch,pl:arclight_implementer:A}
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchServerCommand(CraftServerMixin.java:746) ~[arclight:arclight-1.16.5-1.0.19-SNAPSHOT-5d65f21] {re:mixin,re:classloading,pl:mixin:APP:mixins.arclight.bukkit.json:CraftServerMixin,pl:mixin:A,pl:arclight_implementer:switch,pl:arclight_implementer:A}
        at net.minecraft.server.dedicated.DedicatedServer.redirect$bak000$arclight$serverCommandEvent(DedicatedServerMixin.java:652) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.dedicated.DedicatedServerMixin,pl:mixin:A}
        at net.minecraft.server.dedicated.DedicatedServer.func_71333_ah(DedicatedServerMixin.java:312) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.dedicated.DedicatedServerMixin,pl:mixin:A}
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServerMixin.java:292) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.dedicated.DedicatedServerMixin,pl:mixin:A}
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServerMixin.java:787) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServerMixin.java:1899) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServerMixin.java:232) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_292] {}
Caused by: java.lang.NoSuchMethodError: net.minecraft.command.Commands.a(Lnet/minecraft/command/CommandSource;Ljava/lang/String;Ljava/lang/String;Z)I
        at org.bukkit.craftbukkit.v1_16_R3.command.VanillaCommandWrapper.execute(VanillaCommandWrapper.java:45) ~[arclight:arclight-1.16.5-1.0.19-SNAPSHOT-5d65f21] {re:mixin,re:classloading}
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[arclight:arclight-1.16.5-1.0.19-SNAPSHOT-5d65f21] {re:classloading}
        ... 9 more`

**Comment by IzzelAliz** [comment]
请用最新构建测试

**Comment by HYDeath** [comment]
> 请用最新构建测试

日志：https://paste.ubuntu.com/p/kMqb46W3hs/
无错误报告

**Comment by IzzelAliz** [comment]
你没有使用最新构建

https://github.com/IzzelAliz/Arclight/actions

**Comment by HYDeath** [comment]
> 你没有使用最新构建
> 
> [Https://github.com/IzzelAliz/Arclight/actions](https://github.com/IzzelAliz/Arclight/actions)

已解决，这4天测试暂时没有出现崩端现象

**Comment by KenMaHKG** [comment]
请问在lunix 系统上如何安装?
我试了几次都失败
