### ISSUE TITLE
试了一下1.14.4的版本，发现剪羊毛，喂羊的时候服务器会异常退出。

### ISSUE THREAD

**Issue by janl99** [IzzelAliz/Arclight#29]
试了一下1.14.4的版本，发现剪羊毛，喂羊的时候服务器会异常退出。

**Comment by IzzelAliz** [comment]
日志呢？

**Comment by janl99** [comment]
Z:\BaiduNetdiskDownload\MCSManager_8.6.7_Win\MCSManager_8.6.7_Win\server\server_core\new_server_1.14.4>java -jar arclight-forge-1.14-1.0.3.jar
正在使用 zh_cn 语言，zh_cn 作为备选语言
[22:48:11] [main/INFO] [Arclight/]:

       ___           ___     __   /\
      /   | ________/ (_)__ / /  / /
     / /| |/ __/ __/ / / _ / _ \/__/
    / ___ / / / /_/ / / / / // / /
   /_/  |/_/  \__/_/_/\_ /_//_/ /
                     /__/     \/

    运行版本 arclight-1.14.4-1.0.3-f179b02
    构建日期 2020-07-23 04:10:48

[22:48:11] [main/INFO] [c.m.m.Launcher/MODLAUNCHER]: ModLauncher running: args [--gameDir, ., --launchTarget, fmlserver, --fml.forgeVersion, 28.2.0, --fml.mcpVersion, 20190829.143755, --fml.mcVersion, 1.14.4, --fml.forgeGroup, net.minecraftforge]
[22:48:11] [main/INFO] [c.m.m.Launcher/MODLAUNCHER]: ModLauncher 4.1.0+62+5bfa59b starting: java version 1.8.0_111 by Oracle Corporation
[22:48:12] [main/INFO] [n.m.f.l.FixSSL/CORE]: Added Lets Encrypt root certificates as additional trust
[22:48:12] [main/INFO] [mixin/]: SpongePowered MIXIN Subsystem Version=0.8 Source=file:/Z:/BaiduNetdiskDownload/MCSManager_8.6.7_Win/MCSManager_8.6.7_Win/server/server_core/new_server_1.14.4/libraries/org/spongepowered/mixin/0.8/mixin-0.8.jar Service=ModLauncher Env=SERVER
[22:48:13] [main/INFO] [mixin/]: Successfully loaded Mixin Connector [io.izzel.arclight.impl.ArclightConnector_1_14]
[22:48:13] [main/INFO] [Arclight/]: 核心 Mixin 配置已加载
[22:48:13] [main/INFO] [Arclight/]: 服务端优化 Mixin 配置已加载
[22:48:13] [main/INFO] [c.m.m.LaunchServiceHandler/MODLAUNCHER]: Launching target 'fmlserver' with arguments [--gameDir, .]
[22:48:20] [main/WARN] [mixin/]: Method overwrite conflict for bridge$getBukkitEntity in mixins.arclight.impl.core.1_14.json:entity.player.PlayerEntityMixin_1_14, previously written by io.izzel.arclight.common.mixin.core.entity.player.PlayerEntityMixin. Skipping method.
[22:48:23] [main/WARN] [mixin/]: Method overwrite conflict for bridge$getBukkitEntity in mixins.arclight.impl.core.1_14.json:entity.player.ServerPlayerEntityMixin_1_14, previously written by io.izzel.arclight.common.mixin.core.entity.player.ServerPlayerEntityMixin. Skipping method.
[22:48:35] [main/WARN] [minecraft/Commands]: Ambiguity between arguments [teleport, destination] and [teleport, targets] with inputs: [Player, 0123, @e, dd12be42-52a9-4a91-a8a1-11c01849e498]
[22:48:35] [main/WARN] [minecraft/Commands]: Ambiguity between arguments [teleport, location] and [teleport, destination] with inputs: [0.1 -0.5 .9, 0 0 0]
[22:48:35] [main/WARN] [minecraft/Commands]: Ambiguity between arguments [teleport, location] and [teleport, targets] with inputs: [0.1 -0.5 .9, 0 0 0]
[22:48:35] [main/WARN] [minecraft/Commands]: Ambiguity between arguments [teleport, targets] and [teleport, destination] with inputs: [Player, 0123, dd12be42-52a9-4a91-a8a1-11c01849e498]
[22:48:35] [main/WARN] [minecraft/Commands]: Ambiguity between arguments [teleport, targets, location] and [teleport, targets, destination] with inputs: [0.1 -0.5 .9, 0 0 0]
[22:48:36] [Server thread/INFO] [minecraft/DedicatedServer]: Starting minecraft server version 1.14.4
[22:48:37] [modloading-worker-3/INFO] [Arclight/]: Arclight Mod 已加载
[22:48:37] [modloading-worker-1/INFO] [n.m.c.ForgeMod/FORGEMOD]: Forge mod loading, version 28.2.0, for MC 1.14.4 with MCP 20190829.143755
[22:48:37] [modloading-worker-1/INFO] [n.m.c.MinecraftForge/FORGE]: MinecraftForge v28.2.0 Initialized
[22:48:37] [modloading-worker-3/INFO] [Arclight/]: Arclight 事件系统已注册
[22:48:39] [Forge Version Check/INFO] [n.m.f.VersionChecker/]: [forge] Starting version check at https://files.minecraftforge.net/maven/net/minecraftforge/forge/promotions_slim.json
[22:48:39] [Server thread/INFO] [minecraft/DedicatedServer]: Loading properties
[22:48:39] [Server thread/INFO] [minecraft/DedicatedServer]: Default game type: SURVIVAL
[22:48:39] [Server thread/INFO] [minecraft/DedicatedServer]: Generating keypair
[22:48:39] [Server thread/INFO] [minecraft/DedicatedServer]: Starting Minecraft server on *:25565
[22:48:39] [Server thread/INFO] [minecraft/NetworkSystem]: Using default channel type
[22:48:40] [Server thread/WARN] [minecraft/DedicatedServer]: **** SERVER IS RUNNING IN OFFLINE/INSECURE MODE!
[22:48:40] [Server thread/WARN] [minecraft/DedicatedServer]: The server will make no attempt to authenticate usernames. Beware.
[22:48:40] [Server thread/WARN] [minecraft/DedicatedServer]: While this makes the game possible to play without internet access, it also opens up the ability for hackers to connect with any username they choose.
[22:48:40] [Server thread/WARN] [minecraft/DedicatedServer]: To change this, set "online-mode" to "true" in the server.properties file.
[22:48:41] [Server thread/INFO] [Minecraft/]: This server is running Arclight version arclight-1.14.4-1.0.3-f179b02 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)
[22:48:41] [Server thread/INFO] [Minecraft/]: Debug logging is enabled
[22:48:41] [Server thread/INFO] [STDOUT/]: [org.spigotmc.SpigotConfig:playerSample:287]: Server Ping Player Sample Count: 12
[22:48:41] [Server thread/INFO] [Minecraft/]: Using 4 threads for Netty based IO
[22:48:41] [Server thread/INFO] [Arclight/]: 正在向 Bukkit 注册 ...
[22:48:45] [Server thread/INFO] [Arclight/]: 注册了 0 个材料，其中 0 个方块 0 个物品
[22:48:45] [Server thread/INFO] [Arclight/]: 注册了 0 个新的药水效果
[22:48:45] [Server thread/INFO] [Arclight/]: 注册了 37 个新的附魔
[22:48:45] [Server thread/INFO] [Arclight/]: 注册了 0 个新的生物类型
[22:48:45] [Server thread/INFO] [Arclight/]: 注册了 0 个新的村民职业
[22:48:45] [Server thread/INFO] [Arclight/]: 注册了 0 个新的生物群系
[22:48:45] [Server thread/INFO] [minecraft/DedicatedServer]: Preparing level "world"
[22:48:45] [Server thread/INFO] [minecraft/SimpleReloadableResourceManager]: Reloading ResourceManager: Default, forge-1.14.4-28.2.0-universal.jar, arclight-forge-1.14-1.0.3.jar, bukkit
[22:48:46] [Server thread/INFO] [minecraft/RecipeManager]: Loaded 6 recipes
[22:48:46] [Server thread/INFO] [minecraft/AdvancementList]: Loaded 811 advancements
[22:48:46] [Server thread/INFO] [Arclight/]: 注册了 0 个新的世界类型
[22:48:47] [Server thread/INFO] [Minecraft/]: -------- World Settings For [world] --------
[22:48:47] [Server thread/INFO] [Minecraft/]: View Distance: 10
[22:48:47] [Server thread/INFO] [Minecraft/]: Item Merge Radius: 2.5
[22:48:47] [Server thread/INFO] [Minecraft/]: Mob Spawn Range: 6
[22:48:47] [Server thread/INFO] [Minecraft/]: Item Despawn Rate: 6000
[22:48:47] [Server thread/INFO] [Minecraft/]: Experience Merge Radius: 3.0
[22:48:47] [Server thread/INFO] [Minecraft/]: Arrow Despawn Rate: 1200
[22:48:47] [Server thread/INFO] [Minecraft/]: Zombie Aggressive Towards Villager: true
[22:48:47] [Server thread/INFO] [Minecraft/]: Allow Zombie Pigmen to spawn from portal blocks: true
[22:48:47] [Server thread/INFO] [Minecraft/]: Custom Map Seeds:  Village: 10387312 Desert: 14357617 Igloo: 14357618 Jungle: 14357619 Swamp: 14357620 Monument: 10387313Ocean: 14357621 Shipwreck: 165745295 Slime: 987234911
[22:48:47] [Server thread/INFO] [Minecraft/]: Nerfing mobs spawned from spawners: false
[22:48:47] [Server thread/INFO] [Minecraft/]: Cactus Growth Modifier: 100%
[22:48:47] [Server thread/INFO] [Minecraft/]: Cane Growth Modifier: 100%
[22:48:47] [Server thread/INFO] [Minecraft/]: Melon Growth Modifier: 100%
[22:48:47] [Server thread/INFO] [Minecraft/]: Mushroom Growth Modifier: 100%
[22:48:47] [Server thread/INFO] [Minecraft/]: Pumpkin Growth Modifier: 100%
[22:48:47] [Server thread/INFO] [Minecraft/]: Sapling Growth Modifier: 100%
[22:48:47] [Server thread/INFO] [Minecraft/]: Beetroot Growth Modifier: 100%
[22:48:47] [Server thread/INFO] [Minecraft/]: Carrot Growth Modifier: 100%
[22:48:47] [Server thread/INFO] [Minecraft/]: Potato Growth Modifier: 100%
[22:48:47] [Server thread/INFO] [Minecraft/]: Wheat Growth Modifier: 100%
[22:48:47] [Server thread/INFO] [Minecraft/]: NetherWart Growth Modifier: 100%
[22:48:47] [Server thread/INFO] [Minecraft/]: Vine Growth Modifier: 100%
[22:48:47] [Server thread/INFO] [Minecraft/]: Cocoa Growth Modifier: 100%
[22:48:47] [Server thread/INFO] [Minecraft/]: Bamboo Growth Modifier: 100%
[22:48:47] [Server thread/INFO] [Minecraft/]: SweetBerry Growth Modifier: 100%
[22:48:47] [Server thread/INFO] [Minecraft/]: Kelp Growth Modifier: 100%
[22:48:47] [Server thread/INFO] [Minecraft/]: Entity Activation Range: An 32 / Mo 32 / Ra 48 / Mi 16 / Tiv true
[22:48:47] [Server thread/INFO] [Minecraft/]: Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64
[22:48:47] [Server thread/INFO] [Minecraft/]: Hopper Transfer: 8 Hopper Check: 1 Hopper Amount: 1
[22:48:47] [Server thread/INFO] [Minecraft/]: Tile Max Tick Time: 50ms Entity max Tick Time: 50ms
[22:48:47] [Server thread/INFO] [Minecraft/]: Max TNT Explosions: 100
[22:48:47] [Server thread/INFO] [Minecraft/]: -------- World Settings For [world/DIM-1] --------
[22:48:47] [Server thread/INFO] [Minecraft/]: View Distance: 10
[22:48:47] [Server thread/INFO] [Minecraft/]: Item Merge Radius: 2.5
[22:48:47] [Server thread/INFO] [Minecraft/]: Mob Spawn Range: 6
[22:48:47] [Server thread/INFO] [Minecraft/]: Item Despawn Rate: 6000
[22:48:47] [Server thread/INFO] [Minecraft/]: Experience Merge Radius: 3.0
[22:48:47] [Server thread/INFO] [Minecraft/]: Arrow Despawn Rate: 1200
[22:48:47] [Server thread/INFO] [Minecraft/]: Zombie Aggressive Towards Villager: true
[22:48:47] [Server thread/INFO] [Minecraft/]: Allow Zombie Pigmen to spawn from portal blocks: true
[22:48:47] [Server thread/INFO] [Minecraft/]: Custom Map Seeds:  Village: 10387312 Desert: 14357617 Igloo: 14357618 Jungle: 14357619 Swamp: 14357620 Monument: 10387313Ocean: 14357621 Shipwreck: 165745295 Slime: 987234911
[22:48:47] [Server thread/INFO] [Minecraft/]: Nerfing mobs spawned from spawners: false
[22:48:47] [Server thread/INFO] [Minecraft/]: Cactus Growth Modifier: 100%
[22:48:47] [Server thread/INFO] [Minecraft/]: Cane Growth Modifier: 100%
[22:48:47] [Server thread/INFO] [Minecraft/]: Melon Growth Modifier: 100%
[22:48:47] [Server thread/INFO] [Minecraft/]: Mushroom Growth Modifier: 100%
[22:48:47] [Server thread/INFO] [Minecraft/]: Pumpkin Growth Modifier: 100%
[22:48:47] [Server thread/INFO] [Minecraft/]: Sapling Growth Modifier: 100%
[22:48:47] [Server thread/INFO] [Minecraft/]: Beetroot Growth Modifier: 100%
[22:48:47] [Server thread/INFO] [Minecraft/]: Carrot Growth Modifier: 100%
[22:48:47] [Server thread/INFO] [Minecraft/]: Potato Growth Modifier: 100%
[22:48:47] [Server thread/INFO] [Minecraft/]: Wheat Growth Modifier: 100%
[22:48:47] [Server thread/INFO] [Minecraft/]: NetherWart Growth Modifier: 100%
[22:48:47] [Server thread/INFO] [Minecraft/]: Vine Growth Modifier: 100%
[22:48:47] [Server thread/INFO] [Minecraft/]: Cocoa Growth Modifier: 100%
[22:48:47] [Server thread/INFO] [Minecraft/]: Bamboo Growth Modifier: 100%
[22:48:47] [Server thread/INFO] [Minecraft/]: SweetBerry Growth Modifier: 100%
[22:48:47] [Server thread/INFO] [Minecraft/]: Kelp Growth Modifier: 100%
[22:48:47] [Server thread/INFO] [Minecraft/]: Entity Activation Range: An 32 / Mo 32 / Ra 48 / Mi 16 / Tiv true
[22:48:47] [Server thread/INFO] [Minecraft/]: Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64
[22:48:47] [Server thread/INFO] [Minecraft/]: Hopper Transfer: 8 Hopper Check: 1 Hopper Amount: 1
[22:48:47] [Server thread/INFO] [Minecraft/]: Tile Max Tick Time: 50ms Entity max Tick Time: 50ms
[22:48:47] [Server thread/INFO] [Minecraft/]: Max TNT Explosions: 100
[22:48:47] [Server thread/INFO] [Minecraft/]: -------- World Settings For [world/DIM1] --------
[22:48:47] [Server thread/INFO] [Minecraft/]: View Distance: 10
[22:48:47] [Server thread/INFO] [Minecraft/]: Item Merge Radius: 2.5
[22:48:47] [Server thread/INFO] [Minecraft/]: Mob Spawn Range: 6
[22:48:47] [Server thread/INFO] [Minecraft/]: Item Despawn Rate: 6000
[22:48:47] [Server thread/INFO] [Minecraft/]: Experience Merge Radius: 3.0
[22:48:47] [Server thread/INFO] [Minecraft/]: Arrow Despawn Rate: 1200
[22:48:47] [Server thread/INFO] [Minecraft/]: Zombie Aggressive Towards Villager: true
[22:48:47] [Server thread/INFO] [Minecraft/]: Allow Zombie Pigmen to spawn from portal blocks: true
[22:48:47] [Server thread/INFO] [Minecraft/]: Custom Map Seeds:  Village: 10387312 Desert: 14357617 Igloo: 14357618 Jungle: 14357619 Swamp: 14357620 Monument: 10387313Ocean: 14357621 Shipwreck: 165745295 Slime: 987234911
[22:48:47] [Server thread/INFO] [Minecraft/]: Nerfing mobs spawned from spawners: false
[22:48:47] [Server thread/INFO] [Minecraft/]: Cactus Growth Modifier: 100%
[22:48:47] [Server thread/INFO] [Minecraft/]: Cane Growth Modifier: 100%
[22:48:47] [Server thread/INFO] [Minecraft/]: Melon Growth Modifier: 100%
[22:48:47] [Server thread/INFO] [Minecraft/]: Mushroom Growth Modifier: 100%
[22:48:47] [Server thread/INFO] [Minecraft/]: Pumpkin Growth Modifier: 100%
[22:48:47] [Server thread/INFO] [Minecraft/]: Sapling Growth Modifier: 100%
[22:48:47] [Server thread/INFO] [Minecraft/]: Beetroot Growth Modifier: 100%
[22:48:47] [Server thread/INFO] [Minecraft/]: Carrot Growth Modifier: 100%
[22:48:47] [Server thread/INFO] [Minecraft/]: Potato Growth Modifier: 100%
[22:48:47] [Server thread/INFO] [Minecraft/]: Wheat Growth Modifier: 100%
[22:48:47] [Server thread/INFO] [Minecraft/]: NetherWart Growth Modifier: 100%
[22:48:47] [Server thread/INFO] [Minecraft/]: Vine Growth Modifier: 100%
[22:48:47] [Server thread/INFO] [Minecraft/]: Cocoa Growth Modifier: 100%
[22:48:47] [Server thread/INFO] [Minecraft/]: Bamboo Growth Modifier: 100%
[22:48:47] [Server thread/INFO] [Minecraft/]: SweetBerry Growth Modifier: 100%
[22:48:47] [Server thread/INFO] [Minecraft/]: Kelp Growth Modifier: 100%
[22:48:47] [Server thread/INFO] [Minecraft/]: Entity Activation Range: An 32 / Mo 32 / Ra 48 / Mi 16 / Tiv true
[22:48:47] [Server thread/INFO] [Minecraft/]: Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64
[22:48:47] [Server thread/INFO] [Minecraft/]: Hopper Transfer: 8 Hopper Check: 1 Hopper Amount: 1
[22:48:47] [Server thread/INFO] [Minecraft/]: Tile Max Tick Time: 50ms Entity max Tick Time: 50ms
[22:48:47] [Server thread/INFO] [Minecraft/]: Max TNT Explosions: 100
[22:48:47] [Server thread/INFO] [minecraft/MinecraftServer]: Preparing start region for dimension minecraft:overworld
[22:48:48] [Server thread/INFO] [minecraft/LoggingChunkStatusListener]: Preparing spawn area: 0%
[22:48:48] [Server thread/INFO] [minecraft/LoggingChunkStatusListener]: Preparing spawn area: 0%
[22:48:48] [Server thread/INFO] [minecraft/LoggingChunkStatusListener]: Preparing spawn area: 0%
[22:48:49] [Server thread/INFO] [minecraft/LoggingChunkStatusListener]: Preparing spawn area: 29%
[22:48:52] [Server-Worker-2/INFO] [minecraft/LoggingChunkStatusListener]: Preparing spawn area: 83%
[22:48:52] [Server-Worker-2/INFO] [minecraft/LoggingChunkStatusListener]: Preparing spawn area: 83%
[22:48:52] [Server-Worker-2/INFO] [minecraft/LoggingChunkStatusListener]: Preparing spawn area: 83%
[22:48:52] [Server-Worker-9/INFO] [minecraft/LoggingChunkStatusListener]: Preparing spawn area: 83%
[22:48:52] [Server thread/INFO] [minecraft/LoggingChunkStatusListener]: Preparing spawn area: 83%
[22:48:52] [Server-Worker-9/INFO] [minecraft/LoggingChunkStatusListener]: Preparing spawn area: 83%
[22:48:52] [Server thread/INFO] [minecraft/LoggingChunkStatusListener]: Preparing spawn area: 83%
[22:48:53] [Server-Worker-9/INFO] [minecraft/LoggingChunkStatusListener]: Preparing spawn area: 94%
[22:48:53] [Server-Worker-7/INFO] [minecraft/LoggingChunkStatusListener]: Preparing spawn area: 95%
[22:48:53] [Forge Version Check/INFO] [n.m.f.VersionChecker/]: [forge] Found status: UP_TO_DATE Current: 28.2.0 Target: null
[22:48:54] [Server-Worker-2/INFO] [minecraft/LoggingChunkStatusListener]: Preparing spawn area: 99%
[22:48:54] [Server thread/INFO] [minecraft/LoggingChunkStatusListener]: Time elapsed: 6559 ms
[22:48:54] [Server thread/INFO] [Minecraft/]: Server permissions file permissions.yml is empty, ignoring it
[22:48:54] [Server thread/INFO] [minecraft/DedicatedServer]: Done (8.749s)! For help, type "help"
[22:48:54] [Server thread/INFO] [minecraft/ChunkManager]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved
[22:48:54] [Server thread/INFO] [minecraft/ChunkManager]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
[22:49:38] [User Authenticator #1/INFO] [minecraft/ServerLoginNetHandler]: UUID of player alex is bf20048c-a55a-322c-a100-5493e7b87286
[22:49:38] [Server thread/INFO] [minecraft/PlayerList]: alex[/192.168.2.100:52877] logged in with entity id 217 at (-0.21188637478315722, 64.0, 57.83810189043901)
[22:49:38] [Server thread/INFO] [minecraft/DedicatedServer]: alex joined the game
[22:49:38] [Netty Server IO #3/ERROR] [minecraft/ArgumentTypes]: Could not serialize net.minecraftforge.server.command.ModIdArgument@713289e6 (class net.minecraftforge.server.command.ModIdArgument) - will not be sent to client!
[22:49:38] [Netty Server IO #3/ERROR] [minecraft/ArgumentTypes]: Could not serialize net.minecraftforge.server.command.EnumArgument@6ee6fcca (class net.minecraftforge.server.command.EnumArgument) - will not be sent to client!
[22:50:13] [Server thread/ERROR] [minecraft/MinecraftServer]: Encountered an unexpected exception
java.lang.NoSuchMethodError: net.minecraft.util.ActionResultType.func_226247_b_()Z
        at net.minecraft.network.play.ServerPlayNetHandler.func_147340_a(ServerPlayNetHandlerMixin_1_14.java:2517) ~[?:?] {re:mixin,re:classloading,pl:mixin:A}
        at net.minecraft.network.play.client.CUseEntityPacket.func_148833_a(SourceFile:69) ~[?:?] {re:mixin,re:classloading}
        at net.minecraft.network.play.client.CUseEntityPacket.func_148833_a(SourceFile:13) ~[?:?] {re:mixin,re:classloading}
        at net.minecraft.network.PacketThreadUtil.mde6e8b2$lambda$checkThreadAndEnqueue$0$0(PacketThreadUtilMixin.java:536) ~[?:?] {re:mixin,re:classloading,pl:mixin:A}
        at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18) ~[?:?] {re:classloading}
        at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
        at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) ~[?:?] {re:mixin,re:classloading}
        at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
        at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServerMixin.java:699) ~[?:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServerMixin.java:693) ~[?:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213161_c(SourceFile:127) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
        at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServerMixin.java:679) ~[?:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.run(MinecraftServerMixin.java:1926) [?:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,pl:mixin:A,pl:runtimedistcleaner:A}
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_111] {}
[22:50:13] [Server thread/ERROR] [minecraft/MinecraftServer]: This crash report has been saved to: Z:\BaiduNetdiskDownload\MCSManager_8.6.7_Win\MCSManager_8.6.7_Win\server\server_core\new_server_1.14.4\.\crash-reports\crash-2020-07-25_22.50.13-server.txt
[22:50:13] [Server thread/INFO] [minecraft/MinecraftServer]: Stopping server
[22:50:13] [Server thread/INFO] [minecraft/MinecraftServer]: Saving players
[22:50:13] [Server thread/INFO] [minecraft/ServerPlayNetHandler]: alex lost connection: Server closed
[22:50:13] [Server thread/INFO] [minecraft/DedicatedServer]: alex left the game
[22:50:13] [Server thread/INFO] [minecraft/MinecraftServer]: Saving worlds
[22:50:13] [Server thread/INFO] [minecraft/MinecraftServer]: Saving chunks for level 'world'/minecraft:overworld
[22:50:15] [Server thread/INFO] [minecraft/ChunkManager]: ThreadedAnvilChunkStorage (world): All chunks are saved
[22:50:15] [Server thread/INFO] [minecraft/ChunkManager]: ThreadedAnvilChunkStorage (world): All chunks are saved
