### ISSUE TITLE
无法使用OpenJ9作为Java环境

### ISSUE THREAD

**Issue by markusxu** [IzzelAliz/Arclight#294]
### 我正在运行

* **Arclight** [1.16-1.018] 

* **你确认这是最新版吗** [是，因为我从Github的releases里面下载的]

* **你确认所有Mod都安装了依赖** [是]

* **你确认所有插件都已更新至对应版本** [是]

* **Java** [版本] 
openjdk version "1.8.0_292"
OpenJDK Runtime Environment (build 1.8.0_292-b10)
Eclipse OpenJ9 VM (build openj9-0.26.0, JRE 1.8.0 Linux amd64-64-Bit Compressed References 20210421_1000 (JIT enabled, AOT enabled)
OpenJ9   - b4cc246d9
OMR      - 162e6f729
JCL      - 2a5e268814 based on jdk8u292-b10)

* **操作系统** [名称+版本]
ubuntu 18.04 LTS

  

* **插件列表** 
无
* **Mod 列表** 
无

### 错误描述

叙述这个为什么是一个错误，是哪一方面的，以及其他可能需要的信息

### 重现步骤

1. 启动服务器

2. 自动补全文件

3. 报错

4. 重新尝试启动

5. 报错

 

**可在 Forge 复现** [是/否]

**可在 Spigot 复现** [是/否]

### 报错信息
Using locale en_us and fallback locale zh_cn
Your Java is not compatible with Arclight.
java.lang.ExceptionInInitializerError
        at java.lang.J9VMInternals.ensureError(J9VMInternals.java:145)
        at java.lang.J9VMInternals.recordInitializationFailure(J9VMInternals.java:134)
        at sun.misc.Unsafe.ensureClassInitialized(Native Method)
        at io.izzel.arclight.api.Unsafe.ensureClassInitialized(Unsafe.java:245)
        at io.izzel.arclight.common.ArclightMain.run(ArclightMain.java:36)
        at io.izzel.arclight.server.Main_1_16.main(Main_1_16.java:10)
Caused by: java.lang.IllegalStateException: java.lang.NoSuchFieldException: enumConstantDirectory
        at io.izzel.arclight.api.EnumHelper.<clinit>(EnumHelper.java:83)
        ... 4 more
Caused by: java.lang.NoSuchFieldException: enumConstantDirectory
        at java.lang.Class.getDeclaredFieldInternal(Class.java:836)
        at java.lang.Class.getDeclaredField(Class.java:811)
        at io.izzel.arclight.api.EnumHelper.<clinit>(EnumHelper.java:78)
        ... 4 more

[错误日志]

**Comment by IzzelAliz** [comment]
不支持 OpenJ9
