### ISSUE TITLE
!!ProtocolLib, TamableFoxes v1.9.1, HoloChat don't work

### ISSUE THREAD

**Issue by XionioXMaster** [IzzelAliz/Arclight#312]
Arclight version arclight-1.16.5-1.0.18-32d233f

This is the latest development version [Y]

Java 16

Operating System Unbuntu 20
Plugins (3): ProtocolLib, TamableFoxes v1.9.1, HoloChat

Mods nope

Description
When entering the server, ProtocoLib not good startup, HoloChat does not start correctly
TamableFoxes for 1.16 gives an error on startup

Step to reproduce

Install plugins and run server

Reproducible in Forge [N]

Reproducible in Spigot [Y

Logs

HoloChat: 
`[30Jun2021 10:05:48.903] [Server thread/WARN] [HoloChat/]: Disabling plugin ...
[30Jun2021 10:05:48.903] [Server thread/INFO] [HoloChat/]: Disabling HoloChat v4.0.7
[30Jun2021 10:05:48.913] [Server thread/ERROR] [Minecraft/]: Error occurred while enabling HoloChat v4.0.7 (Is it up to date?)
java.lang.NoClassDefFoundError: me/kaizer/HoloChat/Events/PlayerChat
	at me.kaizer.HoloChat.Main.Main.Events(Main.java:64) ~[?:?]
	at me.kaizer.HoloChat.Main.Main.CheckPlugins(Main.java:77) ~[?:?]
	at me.kaizer.HoloChat.Main.Main.onEnable(Main.java:51) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPluginMixin.java:263) ~[arclight:arclight-1.16.5-1.0.19-abf9928]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoaderMixin.java:342) ~[arclight:arclight-1.16.5-1.0.19-abf9928]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[arclight:arclight-1.16.5-1.0.19-abf9928]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServerMixin.java:492) ~[arclight:arclight-1.16.5-1.0.19-abf9928]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServerMixin.java:406) ~[arclight:arclight-1.16.5-1.0.19-abf9928]
	at net.minecraft.server.MinecraftServer.handler$bfi000$arclight$enablePlugins(MinecraftServerMixin.java:1977) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240787_a_(MinecraftServerMixin.java:382) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240800_l__(MinecraftServerMixin.java:308) ~[?:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServerMixin.java:168) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServerMixin.java:1861) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServerMixin.java:232) ~[?:?]
	at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.ClassNotFoundException: me.kaizer.HoloChat.Events.PlayerChat
	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoaderMixin.java:140) ~[arclight:arclight-1.16.5-1.0.19-abf9928]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoaderMixin.java:99) ~[arclight:arclight-1.16.5-1.0.19-abf9928]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
	... 15 more`

ProtocolLib 

`[12:06:18] [User Authenticator #1/INFO] [minecraft/ServerLoginNetHandler]: UUID of player DeZoWaRe is 93deee78-f5fe-4c81-be31-320581ff6d5b
>
>
>
>
[12:06:28] [Server thread/INFO] [forge/AdvancementLoadFix]: Using new advancement loading for net.minecraft.advancements.PlayerAdvancements@6f95a466
[12:06:28] [Server thread/INFO] [minecraft/PlayerList]: DeZoWaRe[/127.0.0.1:29249] logged in with entity id 189 at (112.27895243068272, 75.09572467893031, 118.51249998807907)
[12:06:32] [Server thread/INFO] [simplelogin/]: Player DeZoWaRe has successfully logged in.
[12:06:33] [ProtocolLib-StructureCompiler 0/INFO] [Console/]: Error Cannot compile structure. Disabing compiler. (java.lang.reflect.InaccessibleObjectException: Unable to make protected final java.lang.Class java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int) throws java.lang.ClassFormatError accessible: module java.base does not "opens java.lang" to unnamed module @54f0d4e) occured in com.comphenix.protocol.reflect.compiler.BackgroundCompiler@1433e729.
[12:06:33] [ProtocolLib-StructureCompiler 0/ERROR] [Minecraft/]:   [ProtocolLib] INTERNAL ERROR: Cannot compile structure. Disabing compiler.
  If this problem hasn't already been reported, please open a ticket
  at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
  Stack Trace:
  java.lang.reflect.InaccessibleObjectException: Unable to make protected final java.lang.Class java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int) throws java.lang.ClassFormatError accessible: module java.base does not "opens java.lang" to unnamed module @54f0d4e
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:357)
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
        at java.base/java.lang.reflect.Method.checkCanSetAccessible(Method.java:199)
        at java.base/java.lang.reflect.Method.setAccessible(Method.java:193)
        at com.comphenix.protocol.reflect.compiler.StructureCompiler.generateClass(StructureCompiler.java:299)
        at com.comphenix.protocol.reflect.compiler.StructureCompiler.compile(StructureCompiler.java:213)
        at com.comphenix.protocol.reflect.compiler.BackgroundCompiler$2.call(BackgroundCompiler.java:204)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
        at java.base/java.lang.Thread.run(Thread.java:831)
  Dump:
  Parameters:
    com.comphenix.protocol.reflect.StructureModifier@2fa8c2c9[
      targetType=class net.minecraft.network.play.server.SChangeBlockPacket
      target=<null>
      converter=<null>
      fieldType=class java.lang.Object
      data=[private net.minecraft.util.math.BlockPos net.minecraft.network.play.server.SChangeBlockPacket.field_179828_a, public net.minecraft.block.BlockState net.minecraft.network.play.server.SChangeBlockPacket.field_197686_b]
      defaultFields={private net.minecraft.util.math.BlockPos net.minecraft.network.play.server.SChangeBlockPacket.field_179828_a=0}
      subtypeCache={}
      customConvertHandling=false
      useStructureCompiler=true
    ]
    manager:
      com.comphenix.protocol.injector.PacketFilterManager@78c81465[
        unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@5ab697f0
        packetListeners=[PacketAdapter[plugin=CombatLogX, sending=ListeningWhitelist[priority=NORMAL, packets=[USE_ITEM[class=PacketPlayInUseItem, id=46], BLOCK_CHANGE[class=PacketPlayOutBlockChange, id=11], BLOCK_DIG[class=PacketPlayInBlockDig, id=27]], gamephase=PLAYING, options=[]], receiving=ListeningWhitelist[priority=NORMAL, packets=[USE_ITEM[class=PacketPlayInUseItem, id=46], BLOCK_CHANGE[class=PacketPlayOutBlockChange, id=11], BLOCK_DIG[class=PacketPlayInBlockDig, id=27]], gamephase=PLAYING, options=[]]]]
        packetInjector=com.comphenix.protocol.injector.netty.ProtocolInjector$5@a871d09
        playerInjection=com.comphenix.protocol.injector.netty.ProtocolInjector$4@63d0381a
        inputBufferedPackets=[]
        recievedListeners=com.comphenix.protocol.injector.SortedPacketListenerList@5b036339
        sendingListeners=com.comphenix.protocol.injector.SortedPacketListenerList@35e466be
        hasClosed=false
        classLoader=org.bukkit.plugin.java.PluginClassLoader@510a6f59
        reporter=com.comphenix.protocol.ProtocolLib$1@7395a5e
        server=CraftServer{serverName=CraftBukkit,serverVersion=arclight-1.16.5-1.0.18-32d233f,minecraftVersion=1.16.5}
        library=ProtocolLib v4.6.0
        asyncFilterManager=com.comphenix.protocol.async.AsyncFilterManager@25110f60
        knowsServerPackets=true
        knowsClientPackets=true
        phaseLoginCount=0
        phasePlayingCount=2
        packetCreation=false
        nettyInjector=com.comphenix.protocol.injector.netty.ProtocolInjector@6b56daa6
        pluginVerifier=com.comphenix.protocol.injector.PluginVerifier@6a66fa2a
        hasRecycleDistance=true
        minecraftVersion=(MC: 1.16.5)
        debug=false
      ]
  Sender:
    com.comphenix.protocol.reflect.compiler.BackgroundCompiler@1433e729[
      listeners={com.comphenix.protocol.reflect.compiler.StructureCompiler$StructureKey@394f29d5=[com.comphenix.protocol.injector.StructureCache$1@5f51235b]}
      listenerLock=java.lang.Object@28f51fd
      compiler=com.comphenix.protocol.reflect.compiler.StructureCompiler@5fe55c2c
      enabled=false
      shuttingDown=false
      executor=java.util.concurrent.Executors$FinalizableDelegatedExecutorService@54e4f256
      reporter=com.comphenix.protocol.ProtocolLib$1@7395a5e
      unknownPermGenBean=java.lang.Object@2f9486a
      permGenBean=<null>
      disablePermGenFraction=0.65
    ]
  Version:
    ProtocolLib v4.6.0
  Java Version:
    16.0.1
  Server:
    arclight-1.16.5-1.0.18-32d233f (MC: 1.16.5)
`

TamableFoxes 

 `[30Jun2021 10:05:39.571] [Server thread/ERROR] [org.bukkit.craftbukkit.v1_16_R3.CraftServer/]: null initializing Tamablefoxes v1.9.1-SNAPSHOT (Is it up to date?)
java.lang.ExceptionInInitializerError: null
	at net.seanomik.tamablefoxes.versions.version_1_16_R3.NMSInterface_1_16_R3.registerCustomFoxEntity(NMSInterface_1_16_R3.java:23) ~[?:?]
	at net.seanomik.tamablefoxes.TamableFoxes.onLoad(TamableFoxes.java:62) ~[?:?]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.loadPlugins(CraftServerMixin.java:386) ~[arclight:arclight-1.16.5-1.0.19-abf9928]
	at net.minecraft.server.dedicated.DedicatedServer.handler$bfj000$arclight$loadPlugins(DedicatedServerMixin.java:634) ~[?:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServerMixin.java:160) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServerMixin.java:1861) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServerMixin.java:232) ~[?:?]
	at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.RuntimeException: java.lang.IllegalAccessException: module java.base does not open java.lang.reflect to unnamed module @19316973
	at net.seanomik.tamablefoxes.versions.FieldHelper.<clinit>(FieldHelper.java:25) ~[?:?]
	... 8 more
Caused by: java.lang.IllegalAccessException: module java.base does not open java.lang.reflect to unnamed module @19316973
	at java.lang.invoke.MethodHandles.privateLookupIn(MethodHandles.java:260) ~[?:?]
	at net.seanomik.tamablefoxes.versions.FieldHelper.<clinit>(FieldHelper.java:22) ~[?:?]
	... 8 more`

**Comment by timi137137** [comment]
you need report to HoloChat
