### ISSUE TITLE
InteractionVisualizer don't correct work

### ISSUE THREAD

**Issue by XionioXMaster** [IzzelAliz/Arclight#313]
Arclight version arclight-1.16.5-1.0.18-32d233f

This is the latest development version [Y]

Java 16

Operating System Unbuntu 20
Plugins (1): InteractionVisualizer 

Mods nope

Description
The plugin loads more or less correctly, but gives an error due to which it cannot function correctly in the game. There are no animations when using a workbench, etc.

Step to reproduce

Install plugin
https://www.spigotmc.org/resources/interactionvisualizer-visualize-function-blocks-entities-like-crafting-tables-with-animations.77050/updates
https://www.spigotmc.org/resources/protocollib.1997/
https://www.spigotmc.org/resources/lightapi-fork.48247/
Run server and look logs

Reproducible in Forge [N]

Reproducible in Spigot [Y]

Logs

`[12:23:58] [Server thread/INFO] [Console/]: [LightAPI] Loading CraftBukkit implementation for 1.16.5 server v1_16_R3.
[12:23:58] [Server thread/INFO] [InteractionVisualizer/]: Enabling InteractionVisualizer v1.14.10.12
[12:23:58] [Server thread/INFO] [Console/]: [InteractionVisualizer] InteractionVisualizer has hooked into Essentials!
[12:23:58] [Server thread/INFO] [Console/]: [InteractionVisualizer] Loading languages...
[12:23:59] [Server thread/INFO] [Console/]: [InteractionVisualizer] Opened Sqlite database successfully
[12:23:59] [Server thread/INFO] [Console/]: The material.yml file has been created
[12:23:59] [Server thread/ERROR] [Minecraft/]: Error occurred while enabling InteractionVisualizer v1.14.10.12 (Is it up to date?)
java.lang.ClassCastException: class com.google.common.collect.RegularImmutableMap cannot be cast to class it.unimi.dsi.fastutil.objects.Object2ObjectLinkedOpenHashMap (com.google.common.collect.RegularImmutableMap is in unnamed module of loader 'app'; it.unimi.dsi.fastutil.objects.Object2ObjectLinkedOpenHashMap is in unnamed module of loader cpw.mods.modlauncher.TransformingClassLoader @3913f206)
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.removeRecipe(CraftServerMixin.java:1262) ~[arclight:arclight-1.16.5-1.0.18-32d233f] {re:mixin,re:classloading,pl:mixin:APP:mixins.arclight.bukkit.json:CraftServerMixin,pl:mixin:A,pl:arclight_implementer:switch,pl:arclight_implementer:A,re:mixin}
        at org.bukkit.Bukkit.removeRecipe(Bukkit.java:775) ~[arclight:arclight-1.16.5-1.0.18-32d233f] {re:mixin,re:classloading,re:mixin,re:mixin}
        at com.loohp.interactionvisualizer.debug.Debug.<init>(Debug.java:81) ~[?:?] {re:classloading,re:classloading,re:classloading}
        at com.loohp.interactionvisualizer.managers.TaskManager.setup(TaskManager.java:144) ~[?:?] {re:classloading,re:classloading,re:classloading}
        at com.loohp.interactionvisualizer.InteractionVisualizer.onEnable(InteractionVisualizer.java:177) ~[?:?] {re:classloading,re:classloading,re:classloading}
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPluginMixin.java:263) ~[arclight:arclight-1.16.5-1.0.18-32d233f] {re:mixin,re:classloading,pl:mixin:APP:mixins.arclight.bukkit.json:JavaPluginMixin,pl:mixin:A,re:mixin}
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoaderMixin.java:351) ~[arclight:arclight-1.16.5-1.0.18-32d233f] {re:mixin,re:classloading,pl:mixin:APP:mixins.arclight.bukkit.json:JavaPluginLoaderMixin,pl:mixin:A}
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[arclight:arclight-1.16.5-1.0.18-32d233f] {re:classloading,re:mixin}
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServerMixin.java:493) ~[arclight:arclight-1.16.5-1.0.18-32d233f] {re:mixin,re:classloading,pl:mixin:APP:mixins.arclight.bukkit.json:CraftServerMixin,pl:mixin:A,pl:arclight_implementer:switch,pl:arclight_implementer:A,re:mixin}
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServerMixin.java:407) ~[arclight:arclight-1.16.5-1.0.18-32d233f] {re:mixin,re:classloading,pl:mixin:APP:mixins.arclight.bukkit.json:CraftServerMixin,pl:mixin:A,pl:arclight_implementer:switch,pl:arclight_implementer:A,re:mixin}
        at net.minecraft.server.MinecraftServer.handler$bef000$arclight$enablePlugins(MinecraftServerMixin.java:1977) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:APP:betterendforge.mixins.json:MinecraftServerMixin,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.func_240787_a_(MinecraftServerMixin.java:382) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:APP:betterendforge.mixins.json:MinecraftServerMixin,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.func_240800_l__(MinecraftServerMixin.java:308) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:APP:betterendforge.mixins.json:MinecraftServerMixin,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServerMixin.java:168) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.dedicated.DedicatedServerMixin,pl:mixin:A}
        at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServerMixin.java:1861) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:APP:betterendforge.mixins.json:MinecraftServerMixin,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServerMixin.java:232) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:APP:betterendforge.mixins.json:MinecraftServerMixin,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at java.lang.Thread.run(Thread.java:831) [?:?] {}`

**Comment by timi137137** [comment]
Hey! You must use a template or you may be banned from issuing an issue
