### ISSUE TITLE
Latest Arclight 1.16.5 does not work with GravitLauncher

### ISSUE THREAD

**Issue by dima-dencep** [IzzelAliz/Arclight#319]
When I run Arclight while registering items in bukkit I get the error:

```
[18:13:00] [Server Topic / INFO] [Arclight /]: Registering for Bukkit ...
[18:13:01] [Server thread / INFO] [Arclight /]: 0 new materials registered with 0 blocks and 0 items
[18:13:01] [Server Topic / INFO] [Arclight /]: 1 new potion effects registered
[18:13:01] [Server Topic / INFO] [Arclight /]: 38 enchantments registered
[18:13:01] [Server thread / INFO] [Arclight /]: 0 new creature types registered
[18:13:01] [Server topic / INFO] [Arclight /]: 0 new occupations registered
[18:13:01] [Server topic / INFO] [Arclight /]: 0 new biomes registered
 07, 2021 6:13:01 PM org.spigotmc.SpigotConfig debug
INFO: Debug logging is enabled
[18:13:01] [Server thread/INFO] [STDOUT/]: [org.spigotmc.SpigotConfig:playerSample:287]: Server Ping Player Sample Count: 12
07, 2021 6:13:01 PM org.spigotmc.SpigotConfig nettyThreads
INFO: Using 4 threads for Netty based IO
[18:13:01] [Server thread/ERROR] [minecraft/MinecraftServer]: Encountered an unexpected exception
java.lang.IllegalArgumentException: Unexpected exception java.lang.reflect.InvocationTargetException while attempting to construct a new instance of org.bukkit.plugin.java.JavaPluginLoader
        at org.bukkit.plugin.SimplePluginManager.registerInterface(SimplePluginManager.java:90) ~[arclight:arclight-1.16.5-1.0.20-SNAPSHOT-9dbe8de] {re:classloading}
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.loadPlugins(CraftServerMixin.java:376) ~[arclight:arclight-1.16.5-1.0.20-SNAPSHOT-9dbe8de] {re:mixin,re:classloading,pl:mixin:APP:mixins.arclight.bukkit.json:CraftServerMixin,pl:mixin:A,pl:arclight_implementer:switch,pl:arclight_implementer:A}
        at net.minecraft.server.dedicated.DedicatedServer.handler$zpo000$arclight$loadPlugins(DedicatedServerMixin.java:634) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.dedicated.DedicatedServerMixin,pl:mixin:A}
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServerMixin.java:160) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.dedicated.DedicatedServerMixin,pl:mixin:A}
        at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServerMixin.java:1861) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServerMixin.java:232) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
        at java.lang.Thread.run(Thread.java:834) [?:?] {}
Caused by: java.lang.reflect.InvocationTargetException
        at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {re:classloading}
        at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:?] {re:classloading}
        at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?] {re:classloading}
        at java.lang.reflect.Constructor.newInstance(Constructor.java:490) ~[?:?] {}
        at org.bukkit.plugin.SimplePluginManager.registerInterface(SimplePluginManager.java:84) ~[arclight:arclight-1.16.5-1.0.20-SNAPSHOT-9dbe8de] {re:classloading}
        ... 6 more
Caused by: java.lang.NullPointerException
        at org.bukkit.plugin.java.LibraryLoader.<init>(LibraryLoaderMixin.java:59) ~[arclight:arclight-1.16.5-1.0.20-SNAPSHOT-9dbe8de] {re:mixin,re:classloading,pl:mixin:APP:mixins.arclight.bukkit.json:LibraryLoaderMixin,pl:mixin:A}
        at org.bukkit.plugin.java.JavaPluginLoader.<init>(JavaPluginLoaderMixin.java:71) ~[arclight:arclight-1.16.5-1.0.20-SNAPSHOT-9dbe8de] {re:mixin,re:classloading,pl:mixin:APP:mixins.arclight.bukkit.json:JavaPluginLoaderMixin,pl:mixin:A}
        at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {re:classloading}
        at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:?] {re:classloading}
        at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?] {re:classloading}
        at java.lang.reflect.Constructor.newInstance(Constructor.java:490) ~[?:?] {}
        at org.bukkit.plugin.SimplePluginManager.registerInterface(SimplePluginManager.java:84) ~[arclight:arclight-1.16.5-1.0.20-SNAPSHOT-9dbe8de] {re:classloading}
        ... 6 more
[18:13:01] [Server thread/ERROR] [minecraft/MinecraftServer]:   Cause of unexpected exception was
java.lang.reflect.InvocationTargetException: null
        at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {re:classloading,re:classloading}
        at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:?] {re:classloading,re:classloading}
        at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?] {re:classloading,re:classloading}
        at java.lang.reflect.Constructor.newInstance(Constructor.java:490) ~[?:?] {}
        at org.bukkit.plugin.SimplePluginManager.registerInterface(SimplePluginManager.java:84) ~[arclight:arclight-1.16.5-1.0.20-SNAPSHOT-9dbe8de] {re:classloading}
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.loadPlugins(CraftServerMixin.java:376) ~[arclight:arclight-1.16.5-1.0.20-SNAPSHOT-9dbe8de] {re:mixin,re:classloading,pl:mixin:APP:mixins.arclight.bukkit.json:CraftServerMixin,pl:mixin:A,pl:arclight_implementer:switch,pl:arclight_implementer:A}
        at net.minecraft.server.dedicated.DedicatedServer.handler$zpo000$arclight$loadPlugins(DedicatedServerMixin.java:634) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.dedicated.DedicatedServerMixin,pl:mixin:A}
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServerMixin.java:160) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.dedicated.DedicatedServerMixin,pl:mixin:A}
        at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServerMixin.java:1861) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServerMixin.java:232) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
        at java.lang.Thread.run(Thread.java:834) [?:?] {}
Caused by: java.lang.NullPointerException
        at org.bukkit.plugin.java.LibraryLoader.<init>(LibraryLoaderMixin.java:59) ~[arclight:arclight-1.16.5-1.0.20-SNAPSHOT-9dbe8de] {re:mixin,re:classloading,pl:mixin:APP:mixins.arclight.bukkit.json:LibraryLoaderMixin,pl:mixin:A}
        at org.bukkit.plugin.java.JavaPluginLoader.<init>(JavaPluginLoaderMixin.java:71) ~[arclight:arclight-1.16.5-1.0.20-SNAPSHOT-9dbe8de] {re:mixin,re:classloading,pl:mixin:APP:mixins.arclight.bukkit.json:JavaPluginLoaderMixin,pl:mixin:A}
        ... 11 more
[18:13:01] [Server thread/FATAL] [forge/ForgeMod]: Preparing crash report with UUID c0611327-7079-4623-9ba4-932a909f2975
> 2021.07.07 18:13:01 [INFO] WebSocket client disconnect
2021-07-07 18:13:02,388 Server Shutdown Thread WARN Advanced terminal features are not available in this environment
```

How do I fix it?

**Comment by XionioXMaster** [comment]
Close this topic to him until he learns to create them correctly, let him fix it himself. Ha-ha.
