### ISSUE TITLE
Bug with GravitLauncher

### ISSUE THREAD

**Issue by dayd21git** [IzzelAliz/Arclight#368]
### I am running

* **Arclight** [1.16/1.0.20: Release 1.0.20] 

* **This is the latest development version**: N

* **Java** [8 or 11 or 16 - latest jre versions] 

* **Operating System** [Win7x64]

  

* **Plugins**: N 

* **Mods**: N 

### Description

Hello. I am trying to link your server to GRAVITLAUNCHER, but the server is not working properly. After the launch, there is a failure, which I pointed out above. Is it possible to solve this? I note that in version 18, the server worked correctly with GRAVITLAUNCHER, but since version 20, the bug specified above occurs.

### Step to reproduce

1. download server.jar
2. starting the server: `java -jar server.jar`
3. stoppig server
4. put the ServerWrapper.jar and ServerWrapperConfig.json to the server folder
5. starting the server: `java -javaagent:ServerWrapper.jar -cp ServerWrapper.jar;server.jar pro.gravit.launcher.server.ServerWrapper`

 

**Reproducible in Forge**: N

**Reproducible in Spigot**: N

### Logs

[http://hastebin.com/fewuracuju.yaml](http://hastebin.com/fewuracuju.yaml)

### Launcher(SerwerWrapper) guides
[http://launcher.gravit.pro/serverbuild](http://launcher.gravit.pro/serverbuild)

**Comment by IzzelAliz** [comment]
If Arclight works standalone but fail on your launcher, you are supposed to ask the launcher devs for help.

**Comment by gravit0** [comment]
@IzzelAliz I am developer GravitLauncher. Crash logs:
```
java.lang.IllegalArgumentException: Unexpected exception java.lang.reflect.InvocationTargetException while attempting to construct a new instance of org.bukkit.plugin.java.JavaPluginLoader
        at org.bukkit.plugin.SimplePluginManager.registerInterface(SimplePluginManager.java:90) ~[arclight:arclight-1.16.5-1.0.20-368b0cb] {re:classloading}
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.loadPlugins(CraftServerMixin.java:376) ~[arclight:arclight-1.16.5-1.0.20-368b0cb] {re:mixin,re:classloading,pl:mixin:APP:mixins.arclight.bukkit.json:CraftServerMixin,pl:mixin:A,pl:arclight_implementer:switch,pl:arclight_implementer:A}
        at net.minecraft.server.dedicated.DedicatedServer.handler$zpo000$arclight$loadPlugins(DedicatedServerMixin.java:634) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.dedicated.DedicatedServerMixin,pl:mixin:A}
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServerMixin.java:160) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.dedicated.DedicatedServerMixin,pl:mixin:A}
        at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServerMixin.java:1861) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServerMixin.java:232) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
        at java.lang.Thread.run(Thread.java:831) [?:?] {}
Caused by: java.lang.reflect.InvocationTargetException
        at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {re:classloading}
        at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:78) ~[?:?] {re:classloading}
        at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?] {re:classloading}
        at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?] {}
        at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?] {}
        at org.bukkit.plugin.SimplePluginManager.registerInterface(SimplePluginManager.java:84) ~[arclight:arclight-1.16.5-1.0.20-368b0cb] {re:classloading}
        ... 6 more
Caused by: java.lang.NullPointerException: Cannot invoke "org.eclipse.aether.RepositorySystem.newLocalRepositoryManager(org.eclipse.aether.RepositorySystemSession, org.eclipse.aether.repository.LocalRepository)" because "this.repository" is null
        at org.bukkit.plugin.java.LibraryLoader.<init>(LibraryLoaderMixin.java:59) ~[arclight:arclight-1.16.5-1.0.20-368b0cb] {re:mixin,re:classloading,pl:mixin:APP:mixins.arclight.bukkit.json:LibraryLoaderMixin,pl:mixin:A}
        at org.bukkit.plugin.java.JavaPluginLoader.<init>(JavaPluginLoaderMixin.java:71) ~[arclight:arclight-1.16.5-1.0.20-368b0cb] {re:mixin,re:classloading,pl:mixin:APP:mixins.arclight.bukkit.json:JavaPluginLoaderMixin,pl:mixin:A}
        at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {re:classloading}
        at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:78) ~[?:?] {re:classloading}
        at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?] {re:classloading}
        at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?] {}
        at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?] {}
        at org.bukkit.plugin.SimplePluginManager.registerInterface(SimplePluginManager.java:84) ~[arclight:arclight-1.16.5-1.0.20-368b0cb] {re:classloading}
        ... 6 more
```

**Comment by gravit0** [comment]
Can you help investigate this issue?
