### ISSUE TITLE
ProtocolLib无法在Arclight 1.17.1上使用

### ISSUE THREAD

**Issue by MesuDevastator** [IzzelAliz/Arclight#371]
### 我正在运行

* **Arclight** arclight-1.17.1-1.0.0-SNAPSHOT-64d48c6 

* **你确认这是最新版吗** 是

* **你确认所有Mod都安装了依赖** 是

* **你确认所有插件都已更新至对应版本** 是

* **Java** java 16.0.2 2021-07-20 

* **操作系统** Windows 10

  

* **插件列表** 服务器开启后便关闭，无法执行指令

* **Mod 列表** 服务器开启后便关闭，无法执行指令

### 错误描述

ProtocolLib在该版本的ArcLight上无法运行（报错）
[22:04:58 INFO] [ProtocolLib]: Loading ProtocolLib v4.7.0
[22:04:59 ERROR] [Minecraft]:   [ProtocolLib] INTERNAL ERROR: Cannot load ProtocolLib.
  If this problem hasn't already been reported, please open a ticket
  at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
  Stack Trace:
  java.lang.ExceptionInInitializerError
        at com.comphenix.protocol.injector.netty.ProtocolInjector.<init>(ProtocolInjector.java:69)
        at com.comphenix.protocol.injector.PacketFilterManager.<init>(PacketFilterManager.java:202)
        at com.comphenix.protocol.injector.PacketFilterBuilder.buildInternal(PacketFilterBuilder.java:185)
        at com.comphenix.protocol.injector.PacketFilterBuilder.build(PacketFilterBuilder.java:177)
        at com.comphenix.protocol.ProtocolLib.onLoad(ProtocolLib.java:203)
        at TRANSFORMER/arclight@1.17.1-1.0.0-SNAPSHOT-64d48c6/org.bukkit.craftbukkit.v1_17_R1.CraftServer.loadPlugins(CraftServerMixin.java:405)
        at TRANSFORMER/minecraft@1.17.1/net.minecraft.server.dedicated.DedicatedServer.handler$zbl000$arclight$loadPlugins(DedicatedServerMixin.java:704)
        at TRANSFORMER/minecraft@1.17.1/net.minecraft.server.dedicated.DedicatedServer.m_7038_(DedicatedServerMixin.java:169)
        at TRANSFORMER/minecraft@1.17.1/net.minecraft.server.MinecraftServer.m_130011_(MinecraftServerMixin.java:2010)
        at TRANSFORMER/minecraft@1.17.1/net.minecraft.server.MinecraftServer.m_177918_(MinecraftServerMixin.java:258)
        at java.base/java.lang.Thread.run(Thread.java:831)
  Caused by: java.lang.UnsupportedOperationException: Cannot define class using reflection: Could not locate class file for java.lang.reflect.AccessibleObject
        at com.comphenix.net.bytebuddy.dynamic.loading.ClassInjector$UsingReflection$Dispatcher$Initializable$Unavailable.defineClass(ClassInjector.java:435)
        at com.comphenix.net.bytebuddy.dynamic.loading.ClassInjector$UsingReflection.injectRaw(ClassInjector.java:251)
        at com.comphenix.net.bytebuddy.dynamic.loading.ClassInjector$AbstractBase.inject(ClassInjector.java:110)
        at com.comphenix.net.bytebuddy.dynamic.loading.ClassLoadingStrategy$Default$InjectionDispatcher.load(ClassLoadingStrategy.java:233)
        at com.comphenix.net.bytebuddy.dynamic.loading.ClassLoadingStrategy$Default.load(ClassLoadingStrategy.java:144)
        at com.comphenix.net.bytebuddy.dynamic.TypeResolutionStrategy$Passive.initialize(TypeResolutionStrategy.java:100)
        at com.comphenix.net.bytebuddy.dynamic.DynamicType$Default$Unloaded.load(DynamicType.java:6292)
        at com.comphenix.protocol.injector.server.TemporaryPlayerFactory.setupProxyPlayerConstructor(TemporaryPlayerFactory.java:187)
        at com.comphenix.protocol.injector.server.TemporaryPlayerFactory.<clinit>(TemporaryPlayerFactory.java:51)
        ... 11 more
  Dump:
  Parameters:
    [NULL]
  Sender:
    com.comphenix.protocol.ProtocolLib@5f6f2f7b[
      statistics=<null>
      backgroundCompiler=<null>
      packetTask=-1
      tickCounter=0
      unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@260ebcbe
      configExpectedMod=-1
      updater=com.comphenix.protocol.updater.SpigotUpdater@2eafff4c
      redirectHandler=<null>
      commandProtocol=<null>
      commandPacket=<null>
      commandFilter=<null>
      packetLogging=<null>
      skipDisable=false
      isEnabled=false
      loader=org.bukkit.plugin.java.JavaPluginLoader@4c58186e
      server=CraftServer{serverName=CraftBukkit,serverVersion=arclight-1.17.1-1.0.0-SNAPSHOT-64d48c6,minecraftVersion=1.17.1}
      file=plugins\ProtocolLib.jar
      description=org.bukkit.plugin.PluginDescriptionFile@39d248c6
      dataFolder=plugins\ProtocolLib
      classLoader=org.bukkit.plugin.java.PluginClassLoader@57bc5e9a
      naggable=true
      newConfig=YamlConfiguration[path='', root='YamlConfiguration']
      configFile=plugins\ProtocolLib\config.yml
      logger=io.izzel.arclight.common.mod.util.log.ArclightPluginLogger@64416b23
    ]
  Version:
    ProtocolLib v4.7.0
  Java Version:
    16.0.2
  Server:
    arclight-1.17.1-1.0.0-SNAPSHOT-64d48c6 (MC: 1.17.1)

### 重现步骤

1. 安装 ProtocolLib（能找到的旧版本也会复现）

 

**可在 Forge 复现** 否

**可在 Spigot 复现** 否

### 报错信息

https://paste.ubuntu.com/p/nsB89TMwJm/

**Comment by IzzelAliz** [comment]
Fixed in bd910af6cd6aafc89a7488eaf131647a3d7a4cf6
