### ISSUE TITLE
Arclight fails to launch

### ISSUE THREAD

**Issue by Grinkon** [IzzelAliz/Arclight#398]
Arclight fails to launch with this error:
java.lang.ClassNotFoundException: cpw.mods.bootstraplauncher.BootstrapLauncher
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:636)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:182)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Class.java:375)
        at io.izzel.arclight.boot.application.Main_Forge.main(Main_Forge.java:20)
        at io.izzel.arclight.server.Launcher.main(Launcher.java:18)
Fail to launch Arclight.
I am using Pterodactyl panel to control my servers. How to fix this error?

**Comment by timi137137** [comment]
pls use template
