### ISSUE TITLE
[1.16.5] Unload all chunks on a player

### ISSUE THREAD

**Issue by TheMartinfer22** [IzzelAliz/Arclight#401]
### I have confirmed that ...

- [X] Arclight is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Forge

### Arclight version

arclight-forge-1.16.5-1.0.21

### OS & Java versions

JDK 8, Debian OS

### Plugins and Mods

```raw
• mods_folder CyclopsCore-1.16.5-1.12.1.jar : cyclopscore (1.12.1) - 1
• mods_folder astralsorcery-1.16-1.16.5-1.13.12.jar : astralsorcery (1.16.5-1.13.12) - 1
• mods_folder supermartijn642configlib-1.0.9-mc1.16.jar : supermartijn642configlib (1.0.9) - 1
• mods_folder Hats-1.16.5-10.3.2.jar : hats (10.3.2) - 1
• mods_folder infernal-expansion-1.16.5-2.4.0.jar : infernalexp (2.4.0) - 1
• mods_folder ExtendedCrafting-1.16.5-3.1.10.jar : extendedcrafting (3.1.10) - 1
• mods_folder InsaneLib-1.4.0-mc1.16.5.jar : insanelib (1.4.0) - 1
• mods_folder IronJetpacks-1.16.5-4.2.3.jar : ironjetpacks (4.2.3) - 1
• mods_folder modernlife-1.16.5-1.19.jar : modernlife (1.16.5-1.19) - 1
• mods_folder citadel-1.8.1-1.16.5.jar : citadel (1.8.1) - 1
• mods_folder alexsmobs-1.12.1.jar : alexsmobs (1.12.1) - 1
• mods_folder EvilCraft-1.16.5-1.1.10.jar : evilcraft (1.1.10) - 2
• mods_folder Powah-1.16.5-2.3.16.jar : powah (2.3.16) - 1
• mods_folder potionsmaster-0.2.2-1.16.5-36.1.0.jar : potionsmaster (0.2.2-1.16.5-36.1.0) - 1
• mods_folder Bookshelf-Forge-1.16.5-10.3.29.jar : bookshelf (10.3.29) - 1
• mods_folder reliquary-1.16.5-1.3.5.1100.jar : xreliquary (1.16.5-1.3.5.1100) - 1
• mods_folder sophisticatedbackpacks-1.16.5-3.12.0.407.jar : sophisticatedbackpacks (1.16.5-3.12.0.407) - 1
• mods_folder randompatches-2.4.4-forge.jar : randompatches (2.4.4-forge) - 1
• mods_folder buildinggadgets-1.16.5-3.8.2.jar : buildinggadgets (3.8.2) - 1
• mods_folder DarkUtilities-1.16.5-8.0.10.jar : darkutils (8.0.10) - 1
• mods_folder ProgressiveBosses-3.4.1-mc1.16.5.jar : progressivebosses (3.4.1) - 1
• mods_folder HuddoutMod.jar : huddoutressurrections (task ':jar' property 'archiveVersion') - 1
• mods_folder Morpheus-1.16.5-4.2.70.jar : morpheus (4.2.70) - 1
• mods_folder MekanismGenerators-1.16.5-10.0.24.453.jar : mekanismgenerators (10.0.24) - 1
• mods_folder XNetGases-1.16.5-2.3.8.jar : xnetgases (2.3.8) - 1
• mods_folder mob_grinding_utils-1.16.5-0.4.30.jar : mob_grinding_utils (1.16.5-0.4.30) - 1
• mods_folder refinedstorage-1.9.16.jar : refinedstorage (1.9.16) - 1
• mods_folder industrial-foregoing-1.16.5-3.2.14.6-14.jar : industrialforegoing (3.2.14.6) - 1
• mods_folder torchmaster-2.3.8.jar : torchmaster (2.3.8) - 1
• mods_folder CommonCapabilities-1.16.5-2.8.0.jar : commoncapabilities (2.8.0) - 1
• mods_folder MekanismAdditions-1.16.5-10.0.24.453.jar : mekanismadditions (10.0.24) - 1
• mods_folder valkyrielib-1.16.5-3.0.9.5.jar : valkyrielib (1.16.5-3.0.9.5) - 1
• mods_folder envirocore-1.16.5-3.0.9.3.jar : envirocore (1.16.5-3.0.9.3) - 1
• mods_folder envirotech-1.16.5-3.0.9.4.jar : envirotech (1.16.5-3.0.9.4) - 1
• mods_folder Lollipop-1.16.5-3.2.9.jar : lollipop (3.2.9) - 1
• mods_folder silent-gear-1.16.5-2.6.30.jar : silentgear (2.6.30) - 1
• mods_folder supermartijn642corelib-1.0.14a-mc1.16.5.jar : supermartijn642corelib (1.0.14a) - 1
• mods_folder Botania-1.16.5-420.jar : botania (1.16.5-420) - 1
• mods_folder curios-forge-1.16.5-4.0.5.3.jar : curios (1.16.5-4.0.5.3) - 1
• mods_folder tetra-1.16.5-3.19.0.jar : tetra (3.19.0) - 1
• mods_folder eidolon-0.2.7.jar : eidolon (0.2.7) - 1
• mods_folder Patchouli-1.16.4-53.2.jar : patchouli (1.16.4-53.2) - 1
• mods_folder witchery_rewitched-0.3.0.jar : witchery_rewitched (0.3.0) - 1
• mods_folder IntegratedTunnels-1.16.5-1.8.8.jar : integratedtunnels (1.8.8) - 2
• mods_folder elevatorid-1.16.5-1.7.13.jar : elevatorid (1.16.5-1.7.13) - 1
• mods_folder Runelic-1.16.5-7.0.2.jar : runelic (7.0.2) - 1
• mods_folder ExtraStorage-1.16.5-1.5.1.jar : extrastorage (1.5.1) - 1
• mods_folder TheAbyss2 1.9.7 1.16.5.jar : theabyss (1.9.7) - 1
• mods_folder MekanismTools-1.16.5-10.0.24.453.jar : mekanismtools (10.0.24) - 1
• mods_folder observerlib-1.16.5-1.5.3.jar : observerlib (1.16.5-1.5.3) - 1
• mods_folder cloth-config-4.12.41-forge.jar : cloth-config (4.12.41) - 1
• mods_folder conjuring-forgery-0.2.2.jar : conjuring (0.2.2) - 2
• mods_folder smallships-1.16.5-1.10.1.jar : smallships (1.10.1) - 1
• mods_folder bwncr-1.16.5-3.10.16.jar : bwncr (1.16.5-3.10.16) - 1
• mods_folder FastLeafDecay-v25.jar : fastleafdecay (v25) - 1
• mods_folder CodeChickenLib-1.16.5-4.0.4.435-universal.jar : codechickenlib (4.0.4.435) - 1
• mods_folder CBMultipart-1.16.5-3.0.3.122-universal.jar : cb_multipart (3.0.3.122) - 3
• mods_folder geckolib-forge-1.16.5-3.0.56.jar : geckolib3 (3.0.56) - 1
• mods_folder gocurrency-ALPHA-20210905.jar : gocurrency (ALPHA-20210905) - 1
• mods_folder dungeons_gear-1.16.5-3.0.21-hotfix.jar : dungeons_gear (3.0.21-hotfix) - 1
• mods_folder Cyclic-1.16.5-1.5.11.jar : cyclic (1.16.5-1.5.11) - 1
• mods_folder Cucumber-1.16.5-4.1.12.jar : cucumber (4.1.12) - 1
• mods_folder woot-1.16.5-1.0.8.0.jar : woot (1.16.5-1.0.8.0) - 1
• mods_folder jei-1.16.5-7.7.1.137.jar : jei (7.7.1.137) - 1
• mods_folder AttributeFix-1.16.5-10.1.2.jar : attributefix (10.1.2) - 1
• mods_folder abnormals_core-1.16.5-3.3.0.jar : abnormals_core (3.3.0) - 1
• mods_folder tesseract-1.0.24-mc1.16.jar : tesseract (1.0.24) - 1
• mods_folder Mekanism-1.16.5-10.0.24.453.jar : mekanism (10.0.24) - 1
• mods_folder Waystones_1.16.5-7.6.4.jar : waystones (7.6.4) - 1
• mods_folder mgui-1.16.5-3.3.0.jar : mgui (3.3.0) - 1
• mods_folder Artifacts-1.16.5-2.10.3.jar : artifacts (1.16.5-2.10.3) - 1
• mods_folder compactmachines-4.0.0-beta.2.jar : compactmachines (4.0.0-beta.2) - 1
• mods_folder mcjtylib-1.16-5.1.0.jar : mcjtylib (1.16-5.1.0) - 1
• mods_folder rftoolsbase-1.16-2.1.0.jar : rftoolsbase (1.16-2.1.0) - 1
• mods_folder xnet-1.16-3.0.14.jar : xnet (1.16-3.0.14) - 1
• mods_folder mahoutsukai-1.16.5-v1.33.3.jar : mahoutsukai (1.16.5-v1.33.3) - 1
• mods_folder iceandfire-2.1.9-1.16.5.jar : iceandfire (2.1.9-1.16.5) - 1
• mods_folder walljump-forge-1.16.4-1.3.7.jar : walljump (1.16.4-1.3.7) - 1
• mods_folder JEITweaker-1.16.5-1.1.0.42.jar : jeitweaker (1.1.0.42) - 1
• mods_folder inventorypets-1.16.5-2.0.15.jar : inventorypets (2.0.15) - 1
• mods_folder iChunUtil-1.16.5-10.5.0.jar : ichunutil (10.5.0) - 1
• mods_folder EnderStorage-1.16.5-2.8.0.168-universal.jar : enderstorage (2.8.0.168) - 1
• mods_folder CraftTweaker-1.16.5-7.1.2.468.jar : crafttweaker (7.1.2.468) - 1
• mods_folder BotanyPots-1.16.5-7.0.17.jar : botanypots (7.0.17) - 1
• mods_folder ars_nouveau-1.16.5-1.24.6.jar : ars_nouveau (1.24.6) - 1
• mods_folder rftoolspower-1.16-3.0.10.jar : rftoolspower (1.16-3.0.10) - 1
• maven_libs forge-1.16.5-36.2.9-universal.jar : forge (36.2.9) - 1
• mods_folder BloodMagic-1.16.4-3.1.6-26.jar : bloodmagic (1.16.4-3.1.6-26) - 1
• mods_folder DynamicSurroundings-1.16.5-4.0.5.0.jar : dsurround (4.0.5.0) - 4
• mods_folder ironchest-1.16.5-11.2.13.jar : ironchest (1.16.5-11.2.13) - 1
• mods_folder ZeroCore2-1.16.5-2.1.6.jar : zerocore (1.16.5-2.1.6) - 1
• mods_folder ExtremeReactors2-1.16.5-2.0.31.jar : bigreactors (1.16.5-2.0.31) - 1
• minecraft forge-1.16.5-36.2.9-server.jar : minecraft (1.16.5) - 1
• mods_folder upgrade_aquatic-1.16.5-3.1.1.jar : upgrade_aquatic (3.1.1) - 1
• mods_folder cofh_core-1.16.5-1.3.1.jar : cofh_core (1.3.1) - 1
• mods_folder thermal_foundation-1.16.5-1.3.2.jar : thermal (1.3.2) - 2
• mods_folder thermal_innovation-1.16.5-1.3.0.jar : thermal_innovation (1.3.0) - 1
• mods_folder thermal_expansion-1.16.5-1.3.0.jar : thermal_expansion (1.3.0) - 1
• mods_folder TConstruct-1.16.5-3.2.1.296.jar : tconstruct (3.2.1.296) - 1
• mods_folder voicechat-forge-1.16.5-1.8.0.jar : voicechat (1.16.5-1.8.0) - 1
• mods_folder theoneprobe-1.16-3.1.4.jar : theoneprobe (1.16-3.1.4) - 1
• mods_folder MouseTweaks-2.14-mc1.16.2.jar : mousetweaks (2.14) - 1
• mods_folder titanium-1.16.5-3.2.8.4-10.jar : titanium (3.2.8.4) - 1
• mods_folder Psi 1.16-97.jar : psi (1.16-96) - 1
• mods_folder ImmersiveEngineering-1.16.5-5.0.5-140.jar : immersiveengineering (1.16.5-5.0.5-140) - 1
• mods_folder silent-lib-1.16.3-4.9.6.jar : silentlib (4.9.6) - 1
• mods_folder turtlemancy-1.16.5-1.6.3.jar : turtlemancy (1.6.3) - 1
• mods_folder atmospheric-1.16.5-3.1.0.jar : atmospheric (3.1.0) - 1
• mods_folder jeiintegration_1.16.5-7.0.1.15.jar : jeiintegration (7.0.1.15) - 1
• mods_folder flywheel-1.16-0.2.5.jar : flywheel (1.16-0.2.5) - 1
• mods_folder create-mc1.16.5_v0.3.2g.jar : create (v0.3.2g) - 1
• mods_folder Mantle-1.16.5-1.6.127.jar : mantle (1.6.127) - 1
• mods_folder Xaeros_Minimap_21.22.2_Forge_1.16.5.jar : xaerominimap (21.22.2) - 1
• mods_folder JAOPCA-1.16.5-3.4.2.16.jar : jaopca (3.4.2.16) - 1
• mods_folder IntegratedDynamics-1.16.5-1.10.5.jar : integrateddynamics (1.10.5) - 2
• mods_folder rats-7.2.0-1.16.5.jar : rats (7.2.0) - 1
• mods_folder FluxNetworks-1.16.5-6.1.7.12.jar : fluxnetworks (6.1.7.12) - 1
• mods_folder Vampirism-1.16.5-1.8.4.jar : vampirism (1.8.4) - 2
• mods_folder Infinitylib-2.0.7.jar : infinitylib (1.16.5-2.0.7) - 1
• mods_folder agricraft-3.0.6.jar : agricraft (1.16.5-3.0.6) - 1
• mods_folder engineersdecor-1.16.5-1.1.15.jar : engineersdecor (1.1.15) - 1
• mods_folder SoL-Carrot-1.16.5-1.10.1.jar : solcarrot (1.16.5-1.10.1) - 1
• arclight server.jar : arclight (1.16.5-1.0.21-SNAPSHOT-9fd4ecc) - 1
• mods_folder enhancedcelestials-2.0.9-1.16.5.jar : enhancedcelestials (2.0.9-1.16.5) - 1
• mods_folder SilentGems-1.16.3-3.7.16.jar : silentgems (3.7.16) - 1
• mods_folder refinedstorageaddons-0.7.4.jar : refinedstorageaddons (0.7.4) - 1
• mods_folder expandability-2.0.1-forge.jar : expandability (2.0.1) - 1
• mods_folder CosmeticArmorReworked-1.16.5-v4a.jar : cosmeticarmorreworked (1.16.5-v4a) - 1
• mods_folder Translocators-1.16.5-2.6.0.82-universal.jar : translocators (2.6.0.82) - 1
```

### Description

Randomly unload all chunks from it and then disallow its actions.

### Step to reproduce

It happens at random times, with no possible reproduction at the moment.

### Logs

[00:31:28] [Server thread/FATAL] [minecraft/ThreadTaskExecutor]: Error executing task on Server
java.lang.NullPointerException: null
        at net.minecraft.world.server.TicketManager.func_219367_b(TicketManagerMixin.java:227) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:world.server.TicketManagerMixin,pl:mixin:A}
        at net.minecraft.world.server.ChunkManager.func_219183_a(ChunkManagerMixin.java:884) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:world.server.ChunkManagerMixin,pl:mixin:APP:mixins.arclight.impl.forge.optimization.json:trackingrange.ChunkManagerMixin_TrackingRange,pl:mixin:A,pl:arclight_implementer:async,pl:arclight_implementer:A,pl:runtimedistcleaner:A}
        at net.minecraft.world.server.ServerChunkProvider.func_217221_a(ServerChunkProviderMixin.java:450) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:world.server.ServerChunkProviderMixin,pl:mixin:APP:enhancedcelestials.mixins.json:MixinServerChunkProvider,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.network.play.ServerPlayNetHandler.func_147347_a(ServerPlayNetHandlerMixin.java:2093) ~[?:?] {re:mixin,pl:accesstransformer:B,xf:fml:astralsorcery:reach_set_server_entity_interact,xf:fml:astralsorcery:allow_entity_interaction,re:classloading,pl:accesstransformer:B,xf:fml:astralsorcery:reach_set_server_entity_interact,xf:fml:astralsorcery:allow_entity_interaction,pl:mixin:A}
        at net.minecraft.network.play.client.CPlayerPacket.func_148833_a(SourceFile:122) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
        at net.minecraft.network.play.client.CPlayerPacket$PositionPacket.func_148833_a(SourceFile:56) ~[?:?] {re:classloading}
        at net.minecraft.network.PacketThreadUtil.md15732d$lambda$checkThreadAndEnqueue$0$0(PacketThreadUtilMixin.java:536) ~[?:?] {re:mixin,re:classloading,pl:mixin:APP:mixins.arclight.core.json:network.PacketThreadUtilMixin,pl:mixin:A}
        at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18) ~[?:?] {re:classloading}
        at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144) ~[?:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
        at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) ~[?:?] {re:mixin,re:computing_frames,re:classloading}
        at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServerMixin.java:734) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:APP:jaopca.mixins.json:MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServerMixin.java:159) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:APP:jaopca.mixins.json:MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118) ~[?:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
        at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServerMixin.java:717) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:APP:jaopca.mixins.json:MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServerMixin.java:711) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:APP:jaopca.mixins.json:MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213161_c(SourceFile:127) ~[?:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
        at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServerMixin.java:697) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:APP:jaopca.mixins.json:MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServerMixin.java:1903) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:APP:jaopca.mixins.json:MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServerMixin.java:232) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:APP:jaopca.mixins.json:MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_312] {}

**Comment by IzzelAliz** [comment]
I'm aware of this, so if you cannot reproduce this sadly I cannot help.

**Comment by TheMartinfer22** [comment]
I got some results with this, at first it's something related to connectivity, just a maybe
