### ISSUE TITLE
使用Arclight启动ATM6整合包时发生mod加载错误导致启动失败

### ISSUE THREAD

**Issue by QingShuiMuYang** [IzzelAliz/Arclight#408]
### I have confirmed that ...

- [X] Arclight is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Forge

### Arclight version

arclight-1.16.5-1.0.21-12996b7

### OS & Java versions

java version "16.0.2" 2021-07-20, 系统:Win10专业版21H1

### Plugins and Mods

```raw
Scorge-3.1.3.jar
CodeChickenLib-1.16.5-4.0.4.435-universal.jar
CBMultipart-1.16.5-3.0.3.122-universal.jar
ProjectRed-1.16.5-4.11.0-beta-6-core.jar
ProjectRed-1.16.5-4.11.0-beta-6-transmission.jar
ProjectRed-1.16.5-4.11.0-beta-6-exploration.jar
ProjectRed-1.16.5-4.11.0-beta-6-integration.jar
ProjectRed-1.16.5-4.11.0-beta-6-illumination.jar
没有加载插件
```

### Description

我用Arclight启动All the Mods6整合包时，后台崩溃了。
查看错误报告发现是加载mod发生错误。
于是我把其他MOD全部删掉，并重新启动，复现了错误。
查过后:
CBMultipart是一个装饰性的mod
ProjectRed是红石计划，以红石为主扩展的mod

### Step to reproduce

1.解压
2.运行startserver.bat

### Logs

https://pastebin.mozilla.org/EXOtyUTy#L17

### Server pack link (Optional)

https://1drv.ms/u/s!Ap3fAZLNEB9mlR3qUZS9LoXruviE?e=a7kaaT

**Comment by xlive2233** [comment]
D:\mc18forge>"C:\Program Files\Java\jdk-17.0.1\bin\java" -jar arclight-forge-1.18-1.0.0-SNAPSHOT.jar nogui
java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at io.izzel.arclight.boot.application.Main_Forge.main(Main_Forge.java:23)
        at io.izzel.arclight.server.Launcher.main(Launcher.java:18)
Caused by: java.lang.NullPointerException: Cannot invoke "java.nio.file.Path.toString()" because the return value of "java.nio.file.Path.getFileName()" is null
        at cpw.mods.securejarhandler@0.9.54/cpw.mods.jarhandling.JarMetadata.fromFileName(JarMetadata.java:60)
        at cpw.mods.securejarhandler@0.9.54/cpw.mods.jarhandling.JarMetadata.from(JarMetadata.java:44)
        at cpw.mods.securejarhandler@0.9.54/cpw.mods.jarhandling.SecureJar.lambda$from$1(SecureJar.java:42)
        at cpw.mods.securejarhandler@0.9.54/cpw.mods.jarhandling.impl.Jar.<init>(Jar.java:133)
        at cpw.mods.securejarhandler@0.9.54/cpw.mods.jarhandling.SecureJar.from(SecureJar.java:58)
        at cpw.mods.securejarhandler@0.9.54/cpw.mods.jarhandling.SecureJar.from(SecureJar.java:50)
        at cpw.mods.securejarhandler@0.9.54/cpw.mods.jarhandling.SecureJar.from(SecureJar.java:42)
        at cpw.mods.bootstraplauncher@0.1.17/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:60)
        ... 6 more
Fail to launch Arclight.

D:\mc18forge>pause
请按任意键继续. . .

**Comment by IzzelAliz** [comment]
给 CBMultipart 作者报告.
`java.lang.reflect.InaccessibleObjectException: Unable to make protected final java.lang.Class java.lang.ClassLoader.defineClass(byte[],int,int) throws java.lang.ClassFormatError accessible: module java.base does not "opens java.lang" to unnamed module @3ce524a8`
