### ISSUE TITLE
[1.15] Illegal Access Error using GameRule bukkit API

### ISSUE THREAD

**Issue by bergerkiller** [IzzelAliz/Arclight#43]
### I am running

* **Arclight** arclight-1.15.2-1.0.8-SNAPSHOT-5579f9e (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)

* **This is the latest development version** Y

* **Java** [VERSION] jdk8

* **Operating System** Windows 7

* **Plugins** MyWorlds BKCommonLib

* **Mods** None

### Description
Error occurs in internal code during initialization, as it tries to use the Bukkit GameRule API.

### Step to reproduce

1. Install [BKCommonLib](https://ci.mg-dev.eu/job/BKCommonLib/) + [MyWorlds](https://ci.mg-dev.eu/job/MyWorlds/)
2. Boot up
### Logs
<pre>
java.lang.IllegalAccessError: tried to access method net.minecraft.world.GameRules$RuleValue.func_223553_a(Ljava/lang/String;)V from class org.bukkit.craftbukkit.v1_15_R1.CraftWorld
    at org.bukkit.craftbukkit.v1_15_R1.CraftWorld.setGameRule(CraftWorldMixin.java:2153) ~[?:arclight-1.15.2-1.0.8-SNAPSHOT-5579f9e] {re:mixin,re:classloading,pl:mixin:APP:mixins.arclight.bukkit.json:CraftWorldMixin,pl:mixin:A,re:mixin}
    at com.bergerkiller.bukkit.mw.advancement.AdvancementManagerImpl.applyGameRuleUsingEnum(AdvancementManagerImpl.java:105) ~[MyWorlds-1.16.2-v1-SNAPSHOT.jar:?] {re:classloading}
    at com.bergerkiller.bukkit.mw.advancement.AdvancementManagerImpl.applyGameRule(AdvancementManagerImpl.java:98) ~[MyWorlds-1.16.2-v1-SNAPSHOT.jar:?] {re:classloading}
    at com.bergerkiller.bukkit.mw.WorldConfig.updateAdvancements(WorldConfig.java:618) ~[MyWorlds-1.16.2-v1-SNAPSHOT.jar:?] {re:classloading}
    at com.bergerkiller.bukkit.mw.WorldConfig.updateAll(WorldConfig.java:541) ~[MyWorlds-1.16.2-v1-SNAPSHOT.jar:?] {re:classloading}
    at com.bergerkiller.bukkit.mw.WorldConfig.reset(WorldConfig.java:89) ~[MyWorlds-1.16.2-v1-SNAPSHOT.jar:?] {re:classloading}
    at com.bergerkiller.bukkit.mw.WorldConfigStore.get(WorldConfigStore.java:53) ~[MyWorlds-1.16.2-v1-SNAPSHOT.jar:?] {re:classloading}
    at com.bergerkiller.bukkit.mw.WorldConfigStore.get(WorldConfigStore.java:61) ~[MyWorlds-1.16.2-v1-SNAPSHOT.jar:?] {re:classloading}
    at com.bergerkiller.bukkit.mw.WorldConfigStore.init(WorldConfigStore.java:136) ~[MyWorlds-1.16.2-v1-SNAPSHOT.jar:?] {re:classloading}
    at com.bergerkiller.bukkit.mw.MyWorlds.enable(MyWorlds.java:245) ~[MyWorlds-1.16.2-v1-SNAPSHOT.jar:?] {re:classloading,re:classloading}
    at com.bergerkiller.bukkit.common.PluginBase.onEnable(PluginBase.java:765) [BKCommonLib-1.16.2-v1-SNAPSHOT.jar:?] {re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading}
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPluginMixin.java:263) [?:arclight-1.15.2-1.0.8-SNAPSHOT-5579f9e] {re:mixin,re:mixin,re:classloading,pl:mixin:APP:mixins.arclight.bukkit.json:JavaPluginMixin,pl:mixin:A}
    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoaderMixin.java:351) [?:arclight-1.15.2-1.0.8-SNAPSHOT-5579f9e] {re:mixin,re:classloading,pl:mixin:APP:mixins.arclight.bukkit.json:JavaPluginLoaderMixin,pl:mixin:A}
    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) [?:arclight-1.15.2-1.0.8-SNAPSHOT-5579f9e] {re:mixin,re:classloading,re:mixin}
    at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServerMixin.java:464) [?:arclight-1.15.2-1.0.8-SNAPSHOT-5579f9e] {re:mixin,re:classloading,pl:mixin:APP:mixins.arclight.bukkit.json:CraftServerMixin,pl:mixin:A,re:mixin}
    at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServerMixin.java:2138) [?:arclight-1.15.2-1.0.8-SNAPSHOT-5579f9e] {re:mixin,re:classloading,pl:mixin:APP:mixins.arclight.bukkit.json:CraftServerMixin,pl:mixin:A,re:mixin}
    at net.minecraft.server.MinecraftServer.handler$zom000$arclight$enablePlugins(MinecraftServerMixin.java:2048) [?:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,pl:mixin:A,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
    at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServerMixin.java:367) [?:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,pl:mixin:A,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
    at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServerMixin.java:212) [?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.dedicated.DedicatedServerMixin,pl:mixin:A}
    at net.minecraft.server.MinecraftServer.run(MinecraftServerMixin.java:1932) [?:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,pl:mixin:A,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
    at java.lang.Thread.run(Unknown Source) [?:1.8.0_201] {}
</pre>

**Comment by bergerkiller** [comment]
Involves this line of code: https://github.com/bergerhealer/MyWorlds/blob/master/src/main/java/com/bergerkiller/bukkit/mw/advancement/AdvancementManagerImpl.java#L105

`world.setGameRule(org.bukkit.GameRule.ANNOUNCE_ADVANCEMENTS, true);`
