### ISSUE TITLE
arclight1.18.1无法打开

### ISSUE THREAD

**Issue by Lythrilla** [IzzelAliz/Arclight#431]
### I have confirmed that ...

- [X] Arclight is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Forge

### Arclight version

arclight-forge-1.18.1-1.0.0-SNAPSHOT.jar

### OS & Java versions

操作系统:windows11 ；JAVA版本:JAVA17

### Plugins and Mods

```raw
无
```

### Description

F:\zulu17.30.15-ca-jdk17.0.1-win_x64\bin\java -jar .\arclight-forge-1.18.1-1.0.0-SNAPSHOT.jar
java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at io.izzel.arclight.boot.application.Main_Forge.main(Main_Forge.java:23)
        at io.izzel.arclight.server.Launcher.main(Launcher.java:18)
Caused by: java.lang.NullPointerException: Cannot invoke "java.nio.file.Path.toString()" because the return value of "java.nio.file.Path.getFileName()" is null
        at cpw.mods.securejarhandler@0.9.54/cpw.mods.jarhandling.JarMetadata.fromFileName(JarMetadata.java:60)
        at cpw.mods.securejarhandler@0.9.54/cpw.mods.jarhandling.JarMetadata.from(JarMetadata.java:44)
        at cpw.mods.securejarhandler@0.9.54/cpw.mods.jarhandling.SecureJar.lambda$from$1(SecureJar.java:42)
        at cpw.mods.securejarhandler@0.9.54/cpw.mods.jarhandling.impl.Jar.<init>(Jar.java:133)
        at cpw.mods.securejarhandler@0.9.54/cpw.mods.jarhandling.SecureJar.from(SecureJar.java:58)
        at cpw.mods.securejarhandler@0.9.54/cpw.mods.jarhandling.SecureJar.from(SecureJar.java:50)
        at cpw.mods.securejarhandler@0.9.54/cpw.mods.jarhandling.SecureJar.from(SecureJar.java:42)
        at cpw.mods.bootstraplauncher@0.1.17/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:60)
        ... 6 more
Fail to launch Arclight.

### Step to reproduce

java -jar arclight-.jar
安装时有几个cant find class
后安装好之后无法打开

### Logs

https://paste.ubuntu.com/p/ggJVZMWcGP/

**Comment by timi137137** [comment]
这是你自己使用上的问题，或网络上的问题，另外jar别加点斜杠

**Comment by Lythrilla** [comment]
> 这是你自己用上的问题，或网络上的问题，另外罐子别加点反引号
请问下怎么解决谢谢
