### ISSUE TITLE
MyPet incompatibility

### ISSUE THREAD

**Issue by Dunmeritude** [IzzelAliz/Arclight#436]
### I have confirmed that ...

- [X] Arclight is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Forge

### Arclight version

arclight-forge-1.18.1-1.0.0-SNAPSHOT

### OS & Java versions

please hear me out in Description

### Plugins and Mods

```raw
Plugins (20): ArclightPatcher, LuckPerms, PlaceholderAPI, Vault, ProtocolLib, dynmap, WorldEdit, PCGF_PluginLib, Minepacks, Essentials, EssentialsProtect, EssentialsDiscord, WorldBorder, EssentialsSpawn, WorldGuard, VentureChat, LogBlock, mcMMO, SilkSpawners, MyPet

Mod List: 
minecraft server-1.18.1-20211210.034407-srg.jar : minecraft (1.18.1) - 1
mods_folder QuarkOddities-1.18.jar : quarkoddities (1.18) - 1
minecraft forge-1.18.1-39.0.0-universal.jar : forge (39.0.0) - 1
mods_folder AutoRegLib-1.7-52.jar : autoreglib (1.7-52) - 1
mods_folder Quark-3.0-334.jar : quark (3.0-334) - 1
arclight arclight-1.18.1-1.0.0-SNAPSHOT-2987cd8.jar : arclight (1.18.1-1.0.0-SNAPSHOT-2987cd8) - 1
```

### Description

As it says- the MyPet plugin is not working with Arclight 1.18. The plugin shows as enabled, and I can see the commands suggested when I type /mypet, but nothing happens and the plugin is not actually functioning at all. 

Sorry for the misfiled report earlier, by the way. The template was not working so I did not know how to replicate it. PLEASE do not close this because the Java version is not filled out correctly. My server is hosted through Beastnode and the console can only be accessed with Multicraft's control panel. I cannot check the Java version but I am aware it is at least java 17, and I believe the server runs linux. If you can tell me how to get the java version somehow else, I will, but don't just close this without a word again, **_please._** 

### Step to reproduce

1. Install MyPet

2. Start Server

3. Receive Error

4. Log in to game

5. Confirm that the plugin is not responsive

### Logs

 https://pastebin.com/yezVVDBs

**Comment by heipiao233** [comment]
我也遇到了，应该是它尝试使用nms的注册（而不是forge）

**Comment by heipiao233** [comment]
[13:55:23] [Server thread/ERROR] [Minecraft/]: Error occurred while enabling MyPet v3.12 (Is it up to date?)
java.lang.IllegalStateException: Can not register to a locked registry. Modder should use Forge Register methods.
        at net.minecraftforge.registries.NamespacedDefaultedWrapper.registerMapping(NamespacedDefaultedWrapper.java:58) ~[forge:?] {re:classloading,pl:accesstransformer:B}
        at net.minecraftforge.registries.NamespacedDefaultedWrapper.register(NamespacedDefaultedWrapper.java:74) ~[forge:?] {re:classloading,pl:accesstransformer:B}
        at net.minecraftforge.registries.NamespacedDefaultedWrapper.func_218381_a(NamespacedDefaultedWrapper.java:42) ~[forge:?] {re:classloading,pl:accesstransformer:B}
        at net.minecraft.util.registry.Registry.func_218322_a(Registry.java:456) ~[?:?] {re:classloading,pl:runtimedistcleaner:A,re:mixin,pl:runtimedistcleaner:A,re:mixin,pl:runtimedistcleaner:A}
        at net.minecraft.util.registry.Registry.func_218325_a(Registry.java:452) ~[?:?] {re:classloading,pl:runtimedistcleaner:A,re:mixin,pl:runtimedistcleaner:A,re:mixin,pl:runtimedistcleaner:A}
        at de.Keyle.MyPet.compat.v1_16_R3.entity.EntityRegistry.registerEntityType(EntityRegistry.java:64) ~[?:?] {re:classloading,re:classloading,re:classloading}
        at de.Keyle.MyPet.compat.v1_16_R3.entity.EntityRegistry.registerEntity(EntityRegistry.java:80) ~[?:?] {re:classloading,re:classloading,re:classloading}
        at de.Keyle.MyPet.compat.v1_16_R3.entity.EntityRegistry.registerEntityTypes(EntityRegistry.java:120) ~[?:?] {re:classloading,re:classloading,re:classloading}
        at de.Keyle.MyPet.MyPetPlugin.onEnable(MyPetPlugin.java:192) ~[?:?] {re:classloading,re:classloading,re:classloading}
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPluginMixin.java:263) ~[arclight:arclight-1.16.5-1.0.22-3ca639a6] {re:mixin,re:mixin,re:classloading,pl:mixin:APP:mixins.arclight.bukkit.json:JavaPluginMixin,pl:mixin:A,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin}
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoaderMixin.java:342) ~[arclight:arclight-1.16.5-1.0.22-3ca639a6] {re:mixin,re:classloading,pl:mixin:APP:mixins.arclight.bukkit.json:JavaPluginLoaderMixin,pl:mixin:A,re:mixin}
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[arclight:arclight-1.16.5-1.0.22-3ca639a6] {re:classloading,re:mixin}
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServerMixin.java:492) ~[arclight:arclight-1.16.5-1.0.22-3ca639a6] {re:mixin,re:classloading,pl:mixin:APP:mixins.arclight.bukkit.json:CraftServerMixin,pl:mixin:A,pl:arclight_implementer:switch,pl:arclight_implementer:A,re:mixin,re:mixin,re:mixin}
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServerMixin.java:406) ~[arclight:arclight-1.16.5-1.0.22-3ca639a6] {re:mixin,re:classloading,pl:mixin:APP:mixins.arclight.bukkit.json:CraftServerMixin,pl:mixin:A,pl:arclight_implementer:switch,pl:arclight_implementer:A,re:mixin,re:mixin,re:mixin}
        at net.minecraft.server.MinecraftServer.handler$zpo000$arclight$enablePlugins(MinecraftServerMixin.java:1977) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.func_240787_a_(MinecraftServerMixin.java:382) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.func_240800_l__(MinecraftServerMixin.java:308) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServerMixin.java:168) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.dedicated.DedicatedServerMixin,pl:mixin:A}
        at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServerMixin.java:1861) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServerMixin.java:232) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}

**Comment by heipiao233** [comment]
https://paste.ubuntu.com/p/sG765cKFDr/

**Comment by heipiao233** [comment]
在loliserver复现
