### ISSUE TITLE
[1.15] NoSuchFieldError activationType in SpigotMC code

### ISSUE THREAD

**Issue by bergerkiller** [IzzelAliz/Arclight#44]
### I am running

* **Arclight** arclight-1.15.2-1.0.8-SNAPSHOT-5579f9e (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)

* **This is the latest development version** Y

* **Java** [VERSION] jdk8

* **Operating System** Windows 7

* **Plugins** TrainCarts BKCommonLib

* **Mods** None

### Description
Error occurs in internal code when initializing the entity tracker entry. It tries to query Spigot what tracking range to use, but this has a weird internal error inside:
<pre>
at org.spigotmc.TrackingRange.getEntityTrackingRange(TrackingRange.java:28) ~[?:arclight-1.15.2-1.0.8-SNAPSHOT-5579f9e] {re:classloading,re:mixin}
</pre>

### Step to reproduce

1. Install [BKCommonLib](https://ci.mg-dev.eu/job/BKCommonLib/) + [TrainCarts](https://ci.mg-dev.eu/job/TrainCarts/)
2. Boot up, place down a minecart
### Logs
<pre>
java.lang.NoSuchFieldError: activationType
    at org.spigotmc.TrackingRange.getEntityTrackingRange(TrackingRange.java:28) ~[?:arclight-1.15.2-1.0.8-SNAPSHOT-5579f9e] {re:classloading,re:mixin}
    at com.bergerkiller.mountiplex.reflection.util.fast.GeneratedCodeInvoker$mplgen172a8448.createEntry(GeneratedCodeInvoker$mplgen172a8448.java) ~[?:?] {re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading}
    at com.bergerkiller.mountiplex.reflection.util.fast.GeneratedCodeInvoker$mplgen172a8448.invoke(GeneratedCodeInvoker$mplgen172a8448.java) ~[?:?] {re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading}
    at com.bergerkiller.mountiplex.reflection.util.fast.InitInvoker.invoke(InitInvoker.java:90) ~[?:?] {re:classloading,re:classloading,re:classloading}
    at com.bergerkiller.mountiplex.reflection.util.FastMethod.invoke(FastMethod.java:142) ~[?:?] {re:classloading,re:classloading,re:classloading,re:classloading}
    at com.bergerkiller.bukkit.common.internal.logic.EntityTypingHandler_1_14.createEntityTrackerEntry(EntityTypingHandler_1_14.java:187) ~[?:?] {re:classloading,re:classloading,re:classloading}
    at com.bergerkiller.bukkit.common.entity.CommonEntity.setNetworkController(CommonEntity.java:194) ~[?:?] {re:classloading,re:classloading,re:classloading,re:classloading}
    at com.bergerkiller.bukkit.common.entity.CommonEntity.spawn(CommonEntity.java:698) ~[?:?] {re:classloading,re:classloading,re:classloading,re:classloading}
    at com.bergerkiller.bukkit.tc.controller.MinecartMemberStore.spawn(MinecartMemberStore.java:269) ~[?:?] {re:classloading,re:classloading,re:classloading}
    at com.bergerkiller.bukkit.tc.controller.MinecartMemberStore.spawnBy(MinecartMemberStore.java:251) ~[?:?] {re:classloading,re:classloading,re:classloading}
    at com.bergerkiller.bukkit.tc.TCListener.handleMinecartPlacement(TCListener.java:774) ~[?:?] {re:classloading,re:classloading,re:classloading}
    at com.bergerkiller.bukkit.tc.TCListener.onRightClick(TCListener.java:689) ~[?:?] {re:classloading,re:classloading,re:classloading}
    at com.bergerkiller.bukkit.tc.TCListener.onPlayerInteract(TCListener.java:586) ~[?:?] {re:classloading,re:classloading,re:classloading}
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[?:arclight-1.15.2-1.0.8-SNAPSHOT-5579f9e] {re:mixin,re:mixin,re:classloading}
    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[?:arclight-1.15.2-1.0.8-SNAPSHOT-5579f9e] {re:mixin,re:classloading,re:mixin}
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[?:arclight-1.15.2-1.0.8-SNAPSHOT-5579f9e] {re:mixin,re:classloading,re:mixin}
    at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactoryMixin.java:450) ~[?:arclight-1.15.2-1.0.8-SNAPSHOT-5579f9e] {re:mixin,re:classloading,pl:mixin:APP:mixins.arclight.bukkit.json:CraftEventFactoryMixin,pl:mixin:A,pl:arclight_implementer:switch,pl:arclight_implementer:A}
    at net.minecraft.server.management.PlayerInteractionManager.func_219441_a(PlayerInteractionManagerMixin.java:752) ~[?:?] {re:mixin,re:classloading,pl:mixin:APP:mixins.arclight.core.json:server.management.PlayerInteractionManagerMixin,pl:mixin:A}
    at net.minecraft.network.play.ServerPlayNetHandler.func_184337_a(ServerPlayNetHandlerMixin.java:853) ~[?:?] {re:mixin,re:classloading,pl:mixin:APP:mixins.arclight.core.json:network.play.ServerPlayNetHandlerMixin,pl:mixin:A,re:mixin}
    at net.minecraft.network.play.client.CPlayerTryUseItemOnBlockPacket.func_148833_a(CPlayerTryUseItemOnBlockPacketMixin.java:36) ~[?:?] {re:mixin,re:classloading,pl:mixin:APP:mixins.arclight.core.json:network.play.client.CPlayerTryUseItemOnBlockPacketMixin,pl:mixin:A,re:mixin}
    at net.minecraft.network.play.client.CPlayerTryUseItemOnBlockPacket.func_148833_a(CPlayerTryUseItemOnBlockPacketMixin.java:10) ~[?:?] {re:mixin,re:classloading,pl:mixin:APP:mixins.arclight.core.json:network.play.client.CPlayerTryUseItemOnBlockPacketMixin,pl:mixin:A,re:mixin}
    at net.minecraft.network.PacketThreadUtil.mdcdf10d$lambda$checkThreadAndEnqueue$0$0(PacketThreadUtilMixin.java:536) ~[?:?] {re:mixin,re:classloading,pl:mixin:APP:mixins.arclight.core.json:network.PacketThreadUtilMixin,pl:mixin:A}
    at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18) [?:?] {re:classloading}
    at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144) [?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
    at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) [?:?] {re:mixin,re:classloading,re:mixin}
    at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServerMixin.java:731) [?:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,pl:mixin:A,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
    at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServerMixin.java:141) [?:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,pl:mixin:A,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
    at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118) [?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
    at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServerMixin.java:714) [?:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,pl:mixin:A,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
    at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServerMixin.java:708) [?:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,pl:mixin:A,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
    at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213161_c(SourceFile:127) [?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
    at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServerMixin.java:694) [?:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,pl:mixin:A,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
    at net.minecraft.server.MinecraftServer.run(MinecraftServerMixin.java:1977) [?:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,pl:mixin:A,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
    at java.lang.Thread.run(Unknown Source) [?:1.8.0_201] {}
</pre>

**Comment by bergerkiller** [comment]
Involves this line:
https://github.com/bergerhealer/BKCommonLib/blob/master/src/main/java/com/bergerkiller/bukkit/common/internal/logic/EntityTypingHandler_1_14.java#L195

Commenting this out and everything else works fine.

**Comment by IzzelAliz** [comment]
Arclight actually do not implement all optimizations from spigot, like this inactiveTick and activation range.
I can give a fake field for this, preventing further NoSuchFieldError.

**Comment by bergerkiller** [comment]
That's fine, but then it would be best if either that method I call doesnt exist (I'll put an #if exists check before), or that the method body itself doesn't throw an error. The code I call here is mostly 'optional' so that spigot's ticking range configuration is applied. If this doesn't exist on Arclight, it's fine if that method is a simple no-op.

**Comment by bergerkiller** [comment]
Problem is fixed
