### ISSUE TITLE
PlotSquared Error

### ISSUE THREAD

**Issue by NipoLau** [IzzelAliz/Arclight#445]
### I have confirmed that ...

- [X] Arclight is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Forge

### Arclight version

arclight-1.18.1-1.0.0

### OS & Java versions

openjdk 17.0.1 2021-10-19 LTS OpenJDK Runtime Environment Zulu17.30+15-CA (build 17.0.1+12-LTS) OpenJDK 64-Bit Server VM Zulu17.30+15-CA (build 17.0.1+12-LTS, mixed mode, sharing)

### Plugins and Mods

```raw
WorldEdit, Essentials, PlotSquared
```

### Description

server error when create a plotworld using plugin plotsquared 

### Step to reproduce

1. install plotsquared 
2. plot setup ... to create a plot world 
3. boom

### Logs

[17:36:01 FATAL] [Arclight]: Failed to schedule load callback for chunk [0, 0]
java.util.concurrent.CompletionException: java.lang.NoSuchMethodError: 'void org.bukkit.craftbukkit.v1_18_R1.generator.InternalChunkGenerator.applyBiomeDecoration(net.minecraft.world.level.WorldGenLevel, net.minecraft.world.level.chunk.ChunkAccess, net.minecraft.world.level.StructureFeatureManager, boolean)'
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1159) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
	at net.minecraft.server.level.ChunkTaskPriorityQueueSorter.m_143188_(ChunkTaskPriorityQueueSorter.java:58) ~[server-1.18.1-20211210.034407-srg.jar%2369!:?]
	at net.minecraft.util.thread.ProcessorMailbox.m_18759_(ProcessorMailbox.java:91) [server-1.18.1-20211210.034407-srg.jar%2369!:?]
	at net.minecraft.util.thread.ProcessorMailbox.m_18747_(ProcessorMailbox.java:146) [server-1.18.1-20211210.034407-srg.jar%2369!:?]
	at net.minecraft.util.thread.ProcessorMailbox.run(ProcessorMailbox.java:102) [server-1.18.1-20211210.034407-srg.jar%2369!:?]
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395) [?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) [?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) [?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) [?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) [?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) [?:?]
Caused by: java.lang.NoSuchMethodError: 'void org.bukkit.craftbukkit.v1_18_R1.generator.InternalChunkGenerator.applyBiomeDecoration(net.minecraft.world.level.WorldGenLevel, net.minecraft.world.level.chunk.ChunkAccess, net.minecraft.world.level.StructureFeatureManager, boolean)'
	at org.bukkit.craftbukkit.v1_18_R1.generator.CustomChunkGenerator.m_183372_(CustomChunkGenerator.java:288) ~[arclight-1.18.1-1.0.0-98307237.jar%2367!:arclight-1.18.1-1.0.0-98307237]
	at net.minecraft.world.level.chunk.ChunkStatus.m_187807_(ChunkStatus.java:135) ~[server-1.18.1-20211210.034407-srg.jar%2369!:?]
	at net.minecraft.world.level.chunk.ChunkStatus.m_187788_(ChunkStatus.java:262) ~[server-1.18.1-20211210.034407-srg.jar%2369!:?]
	at net.minecraft.server.level.ChunkMap.lambda$scheduleChunkGeneration$20(ChunkMapMixin.java:552) ~[server-1.18.1-20211210.034407-srg.jar%2369!:?]
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[datafixerupper-4.0.26.jar%2330!:?]
	at net.minecraft.server.level.ChunkMap.lambda$scheduleChunkGeneration$22(ChunkMapMixin.java:550) ~[server-1.18.1-20211210.034407-srg.jar%2369!:?]
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150) ~[?:?]
	... 11 more
[17:36:01 INFO] [STDOUT]: Negative index in crash report handler (18/25)
[17:36:01 ERROR] [STDERR]: net.minecraft.ReportedException: Exception initializing level
[17:36:01 ERROR] [STDERR]: 	at TRANSFORMER/minecraft@1.18.1/net.minecraft.server.MinecraftServer.initWorld(MinecraftServerMixin.java:2260)
[17:36:01 ERROR] [STDERR]: 	at TRANSFORMER/arclight@1.18.1-1.0.0-98307237/org.bukkit.craftbukkit.v1_18_R1.CraftServer.createWorld(CraftServerMixin.java:1149)
[17:36:01 ERROR] [STDERR]: 	at TRANSFORMER/arclight@1.18.1-1.0.0-98307237/org.bukkit.Bukkit.createWorld(Bukkit.java:631)
[17:36:01 ERROR] [STDERR]: 	at com.plotsquared.bukkit.managers.BukkitWorldManager.handleWorldCreation(BukkitWorldManager.java:64)
[17:36:01 ERROR] [STDERR]: 	at com.plotsquared.bukkit.managers.BukkitWorldManager.handleWorldCreation(BukkitWorldManager.java:48)
[17:36:01 ERROR] [STDERR]: 	at com.plotsquared.bukkit.util.BukkitSetupUtils.setupWorld(BukkitSetupUtils.java:231)
[17:36:01 ERROR] [STDERR]: 	at com.plotsquared.core.setup.CommonSetupSteps$7.handleInput(CommonSetupSteps.java:227)
[17:36:01 ERROR] [STDERR]: 	at com.plotsquared.core.setup.SetupProcess.handleInput(SetupProcess.java:54)
[17:36:01 ERROR] [STDERR]: 	at com.plotsquared.core.command.Setup.onCommand(Setup.java:108)
[17:36:01 ERROR] [STDERR]: 	at com.plotsquared.core.command.SubCommand.execute(SubCommand.java:57)
[17:36:01 ERROR] [STDERR]: 	at com.plotsquared.core.command.Command.execute(Command.java:365)
[17:36:01 ERROR] [STDERR]: 	at com.plotsquared.core.command.MainCommand.execute(MainCommand.java:312)
[17:36:01 ERROR] [STDERR]: 	at com.plotsquared.core.command.MainCommand.onCommand(MainCommand.java:187)
[17:36:01 ERROR] [STDERR]: 	at com.plotsquared.bukkit.BukkitCommand.onCommand(BukkitCommand.java:59)
[17:36:01 ERROR] [STDERR]: 	at TRANSFORMER/arclight@1.18.1-1.0.0-98307237/org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[17:36:01 ERROR] [STDERR]: 	at TRANSFORMER/arclight@1.18.1-1.0.0-98307237/org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149)
[17:36:01 ERROR] [STDERR]: 	at TRANSFORMER/arclight@1.18.1-1.0.0-98307237/org.bukkit.craftbukkit.v1_18_R1.CraftServer.dispatchCommand(CraftServerMixin.java:821)
[17:36:01 ERROR] [STDERR]: 	at TRANSFORMER/arclight@1.18.1-1.0.0-98307237/org.bukkit.craftbukkit.v1_18_R1.CraftServer.dispatchServerCommand(CraftServerMixin.java:806)
[17:36:01 ERROR] [STDERR]: 	at TRANSFORMER/minecraft@1.18.1/net.minecraft.server.dedicated.DedicatedServer.redirect$zbl000$arclight$serverCommandEvent(DedicatedServerMixin.java:714)
[17:36:01 ERROR] [STDERR]: 	at TRANSFORMER/minecraft@1.18.1/net.minecraft.server.dedicated.DedicatedServer.m_139665_(DedicatedServerMixin.java:343)
[17:36:01 ERROR] [STDERR]: 	at TRANSFORMER/minecraft@1.18.1/net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServerMixin.java:329)
[17:36:01 ERROR] [STDERR]: 	at TRANSFORMER/minecraft@1.18.1/net.minecraft.server.MinecraftServer.m_5705_(MinecraftServerMixin.java:808)
[17:36:01 ERROR] [STDERR]: 	at TRANSFORMER/minecraft@1.18.1/net.minecraft.server.MinecraftServer.m_130011_(MinecraftServerMixin.java:2063)
[17:36:01 ERROR] [STDERR]: 	at TRANSFORMER/minecraft@1.18.1/net.minecraft.server.MinecraftServer.m_177918_(MinecraftServerMixin.java:258)
[17:36:01 ERROR] [STDERR]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[17:36:01 ERROR] [STDERR]: Caused by: java.lang.NoSuchMethodError: 'void org.bukkit.craftbukkit.v1_18_R1.generator.InternalChunkGenerator.applyBiomeDecoration(net.minecraft.world.level.WorldGenLevel, net.minecraft.world.level.chunk.ChunkAccess, net.minecraft.world.level.StructureFeatureManager, boolean)'
[17:36:01 ERROR] [STDERR]: 	at TRANSFORMER/arclight@1.18.1-1.0.0-98307237/org.bukkit.craftbukkit.v1_18_R1.generator.CustomChunkGenerator.m_183372_(CustomChunkGenerator.java:288)
[17:36:01 ERROR] [STDERR]: 	at TRANSFORMER/minecraft@1.18.1/net.minecraft.world.level.chunk.ChunkStatus.m_187807_(ChunkStatus.java:135)
[17:36:01 ERROR] [STDERR]: 	at TRANSFORMER/minecraft@1.18.1/net.minecraft.world.level.chunk.ChunkStatus.m_187788_(ChunkStatus.java:262)
[17:36:01 ERROR] [STDERR]: 	at TRANSFORMER/minecraft@1.18.1/net.minecraft.server.level.ChunkMap.lambda$scheduleChunkGeneration$20(ChunkMapMixin.java:552)
[17:36:01 ERROR] [STDERR]: 	at MC-BOOTSTRAP/datafixerupper@4.0.26/com.mojang.datafixers.util.Either$Left.map(Either.java:38)
[17:36:01 ERROR] [STDERR]: 	at TRANSFORMER/minecraft@1.18.1/net.minecraft.server.level.ChunkMap.lambda$scheduleChunkGeneration$22(ChunkMapMixin.java:550)
[17:36:01 ERROR] [STDERR]: 	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150)
[17:36:01 ERROR] [STDERR]: 	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
[17:36:01 ERROR] [STDERR]: 	at TRANSFORMER/minecraft@1.18.1/net.minecraft.server.level.ChunkTaskPriorityQueueSorter.m_143188_(ChunkTaskPriorityQueueSorter.java:58)
[17:36:01 ERROR] [STDERR]: 	at TRANSFORMER/minecraft@1.18.1/net.minecraft.util.thread.ProcessorMailbox.m_18759_(ProcessorMailbox.java:91)
[17:36:01 ERROR] [STDERR]: 	at TRANSFORMER/minecraft@1.18.1/net.minecraft.util.thread.ProcessorMailbox.m_18747_(ProcessorMailbox.java:146)
[17:36:01 ERROR] [STDERR]: 	at TRANSFORMER/minecraft@1.18.1/net.minecraft.util.thread.ProcessorMailbox.run(ProcessorMailbox.java:102)
[17:36:01 ERROR] [STDERR]: 	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395)
[17:36:01 ERROR] [STDERR]: 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
[17:36:01 ERROR] [STDERR]: 	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
[17:36:01 ERROR] [STDERR]: 	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
[17:36:01 ERROR] [STDERR]: 	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
[17:36:01 ERROR] [STDERR]: 	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)

**Comment by IzzelAliz** [comment]
请测试是否修复
