### ISSUE TITLE
I Have a Question.

### ISSUE THREAD

**Issue by KMyungs** [IzzelAliz/Arclight#446]
### I have confirmed that ...

- [X] Arclight is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Forge

### Arclight version

arclight-forge-1.18.1-1.0.0

### OS & Java versions

window 10 OpenJDK 64-Bit Server VM Microsoft-28056 (build 17.0.1)

### Plugins and Mods

```raw
Nothing.
```

### Description

I tried on bukkit, I Can't create Plugins folder, 
![image](https://user-images.githubusercontent.com/97261799/148464802-bab9f42f-f59e-4d64-b146-f682a6f368bc.png)
How to get plugins folder?

### Step to reproduce

prepare to develop

### Logs

[07:55:39] [main/INFO]: ModLauncher running: args [--launchTarget, forgeserver, --fml.forgeVersion, 39.0.0, --fml.mcVersion, 1.18.1, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20211210.034407]
[07:55:39] [main/INFO]: ModLauncher 9.0.7+91+master.8569cdf starting: java version 17.0.1 by Oracle Corporation
[07:55:39] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=union:/D:/test/libraries/org/spongepowered/mixin/0.8.5/mixin-0.8.5.jar%2319! Service=ModLauncher Env=SERVER
[07:55:40] [main/INFO]: Found mod file fmlcore-1.18.1-39.0.0.jar of type LIBRARY with locator net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@7be58f16
[07:55:40] [main/INFO]: Found mod file javafmllanguage-1.18.1-39.0.0.jar of type LANGPROVIDER with locator net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@7be58f16
[07:55:40] [main/INFO]: Found mod file mclanguage-1.18.1-39.0.0.jar of type LANGPROVIDER with locator net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@7be58f16
[07:55:40] [main/INFO]: Found mod file server-1.18.1-20211210.034407-srg.jar of type MOD with locator net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@7be58f16
[07:55:40] [main/INFO]: Found mod file forge-1.18.1-39.0.0-universal.jar of type MOD with locator net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@7be58f16
[07:55:40] [main/INFO]: Launching target 'forgeserver' with arguments []
[07:55:45] [modloading-worker-0/INFO]: Forge mod loading, version 39.0.0, for MC 1.18.1 with MCP 20211210.034407
[07:55:45] [modloading-worker-0/INFO]: MinecraftForge v39.0.0 Initialized
[07:55:45] [main/WARN]: Configuration file D:\test\config\forge-common.toml is not correct. Correcting
[07:55:45] [main/WARN]: Incorrect key general was corrected from null to its default, SimpleCommentedConfig:{}. 
[07:55:45] [main/WARN]: Incorrect key general.defaultWorldType was corrected from null to its default, default. 
[07:55:46] [Forge Version Check/INFO]: [forge] Starting version check at https://files.minecraftforge.net/net/minecraftforge/forge/promotions_slim.json
[07:55:47] [Forge Version Check/INFO]: [forge] Found status: BETA_OUTDATED Current: 39.0.0 Target: 39.0.10
[07:55:48] [main/ERROR]: Failed to load properties from file: server.properties
[07:55:48] [main/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[07:55:48] [main/WARN]: Assets URL 'union:/D:/test/libraries/net/minecraft/server/1.18.1-20211210.034407/server-1.18.1-20211210.034407-srg.jar%2338!/assets/.mcassetsroot' uses unexpected schema
[07:55:48] [main/WARN]: Assets URL 'union:/D:/test/libraries/net/minecraft/server/1.18.1-20211210.034407/server-1.18.1-20211210.034407-srg.jar%2338!/data/.mcassetsroot' uses unexpected schema
[07:55:49] [main/WARN]: Ambiguity between arguments [teleport, location] and [teleport, destination] with inputs: [0.1 -0.5 .9, 0 0 0]
[07:55:49] [main/WARN]: Ambiguity between arguments [teleport, location] and [teleport, targets] with inputs: [0.1 -0.5 .9, 0 0 0]
[07:55:49] [main/WARN]: Ambiguity between arguments [teleport, destination] and [teleport, targets] with inputs: [Player, 0123, @e, dd12be42-52a9-4a91-a8a1-11c01849e498]
[07:55:49] [main/WARN]: Ambiguity between arguments [teleport, targets] and [teleport, destination] with inputs: [Player, 0123, dd12be42-52a9-4a91-a8a1-11c01849e498]
[07:55:49] [main/WARN]: Ambiguity between arguments [teleport, targets, location] and [teleport, targets, destination] with inputs: [0.1 -0.5 .9, 0 0 0]
[07:55:49] [main/INFO]: Reloading ResourceManager: Default, forge-1.18.1-39.0.0-universal.jar
[07:55:50] [Worker-Main-16/INFO]: Loaded 7 recipes
[07:55:51] [Worker-Main-16/INFO]: Loaded 1141 advancements
[07:55:54] [Server thread/INFO]: Starting minecraft server version 1.18.1
[07:55:54] [Server thread/INFO]: Loading properties
[07:55:54] [Server thread/INFO]: Default game type: SURVIVAL
[07:55:54] [Server thread/INFO]: Generating keypair
[07:55:54] [Server thread/INFO]: Starting Minecraft server on *:25565
[07:55:54] [Server thread/INFO]: Using default channel type
[07:55:54] [Server thread/WARN]: Configuration file .\world\serverconfig\forge-server.toml is not correct. Correcting
[07:55:54] [Server thread/WARN]: Incorrect key server was corrected from null to its default, SimpleCommentedConfig:{}. 
[07:55:54] [Server thread/WARN]: Incorrect key server.removeErroringBlockEntities was corrected from null to its default, false. 
[07:55:54] [Server thread/WARN]: Incorrect key server.fullBoundingBoxLadders was corrected from null to its default, false. 
[07:55:54] [Server thread/WARN]: Incorrect key server.zombieBaseSummonChance was corrected from null to its default, 0.1. 
[07:55:54] [Server thread/WARN]: Incorrect key server.zombieBabyChance was corrected from null to its default, 0.05. 
[07:55:54] [Server thread/WARN]: Incorrect key server.treatEmptyTagsAsAir was corrected from null to its default, false. 
[07:55:54] [Server thread/WARN]: Incorrect key server.fixAdvancementLoading was corrected from null to its default, true. 
[07:55:54] [Server thread/INFO]: Preparing level "world"
[07:55:59] [Server thread/INFO]: Preparing start region for dimension minecraft:overworld
[07:56:00] [Worker-Main-12/INFO]: Preparing spawn area: 0%
[07:56:00] [Worker-Main-23/INFO]: Preparing spawn area: 0%
[07:56:00] [Worker-Main-23/INFO]: Preparing spawn area: 0%
[07:56:01] [Worker-Main-17/INFO]: Preparing spawn area: 0%
[07:56:01] [Worker-Main-15/INFO]: Preparing spawn area: 0%
[07:56:02] [Worker-Main-17/INFO]: Preparing spawn area: 0%
[07:56:02] [Worker-Main-12/INFO]: Preparing spawn area: 0%
[07:56:03] [Worker-Main-12/INFO]: Preparing spawn area: 1%
[07:56:03] [Worker-Main-18/INFO]: Preparing spawn area: 2%
[07:56:04] [Worker-Main-12/INFO]: Preparing spawn area: 2%
[07:56:04] [Worker-Main-15/INFO]: Preparing spawn area: 3%
[07:56:05] [Worker-Main-19/INFO]: Preparing spawn area: 4%
[07:56:05] [Worker-Main-15/INFO]: Preparing spawn area: 5%
[07:56:06] [Worker-Main-17/INFO]: Preparing spawn area: 8%
[07:56:06] [Worker-Main-24/INFO]: Preparing spawn area: 11%
[07:56:07] [Worker-Main-12/INFO]: Preparing spawn area: 15%
[07:56:07] [Worker-Main-19/INFO]: Preparing spawn area: 18%
[07:56:08] [Worker-Main-19/INFO]: Preparing spawn area: 21%
[07:56:08] [Worker-Main-12/INFO]: Preparing spawn area: 25%
[07:56:09] [Worker-Main-12/INFO]: Preparing spawn area: 28%
[07:56:09] [Worker-Main-18/INFO]: Preparing spawn area: 32%
[07:56:10] [Worker-Main-23/INFO]: Preparing spawn area: 36%
[07:56:10] [Worker-Main-13/INFO]: Preparing spawn area: 41%
[07:56:11] [Worker-Main-25/INFO]: Preparing spawn area: 45%
[07:56:11] [Worker-Main-13/INFO]: Preparing spawn area: 50%
[07:56:12] [Worker-Main-17/INFO]: Preparing spawn area: 55%
[07:56:12] [Worker-Main-19/INFO]: Preparing spawn area: 59%
[07:56:13] [Worker-Main-18/INFO]: Preparing spawn area: 64%
[07:56:13] [Worker-Main-13/INFO]: Preparing spawn area: 69%
[07:56:14] [Worker-Main-17/INFO]: Preparing spawn area: 74%
[07:56:14] [Worker-Main-13/INFO]: Preparing spawn area: 77%
[07:56:15] [Worker-Main-23/INFO]: Preparing spawn area: 84%
[07:56:15] [Worker-Main-17/INFO]: Preparing spawn area: 87%
[07:56:16] [Worker-Main-12/INFO]: Preparing spawn area: 92%
[07:56:16] [Worker-Main-15/INFO]: Preparing spawn area: 96%
[07:56:16] [Server thread/INFO]: Time elapsed: 17162 ms
[07:56:16] [Server thread/INFO]: Done (22.182s)! For help, type "help"
[07:57:52] [Server thread/INFO]: Reloading!
[07:57:52] [Server thread/WARN]: Ambiguity between arguments [teleport, location] and [teleport, destination] with inputs: [0.1 -0.5 .9, 0 0 0]
[07:57:52] [Server thread/WARN]: Ambiguity between arguments [teleport, location] and [teleport, targets] with inputs: [0.1 -0.5 .9, 0 0 0]
[07:57:52] [Server thread/WARN]: Ambiguity between arguments [teleport, destination] and [teleport, targets] with inputs: [Player, 0123, @e, dd12be42-52a9-4a91-a8a1-11c01849e498]
[07:57:52] [Server thread/WARN]: Ambiguity between arguments [teleport, targets] and [teleport, destination] with inputs: [Player, 0123, dd12be42-52a9-4a91-a8a1-11c01849e498]
[07:57:52] [Server thread/WARN]: Ambiguity between arguments [teleport, targets, location] and [teleport, targets, destination] with inputs: [0.1 -0.5 .9, 0 0 0]
[07:57:52] [Server thread/INFO]: Reloading ResourceManager: Default, forge-1.18.1-39.0.0-universal.jar
[07:57:53] [Server thread/INFO]: Loaded 7 recipes
[07:57:53] [Server thread/INFO]: Loaded 1141 advancements
[07:58:03] [Server thread/INFO]: Unknown or incomplete command, see below for error
[07:58:04] [Server thread/INFO]: <--[HERE]
[07:58:05] [Server thread/INFO]: Unknown or incomplete command, see below for error
[07:58:05] [Server thread/INFO]: <--[HERE]
[07:58:06] [Server thread/INFO]: Unknown or incomplete command, see below for error
[07:58:06] [Server thread/INFO]: pl<--[HERE]

**Comment by Taskeren** [comment]
It seems that you are not starting the Arclight server, but the vanilla Forge instead.
Can you post your `run.bat` here?

**Comment by KMyungs** [comment]
I don't know where is arclight server bukkit.
I just download arclight-forge-1.17.1-1.0.2.

**Comment by Taskeren** [comment]
Did you run the server by `run.bat`?
Can you please post your `run.bat` here?

**Comment by KMyungs** [comment]
REM Forge requires a configured set of both JVM and program arguments.
REM Add custom JVM arguments to the user_jvm_args.txt
REM Add custom program arguments {such as nogui} to this file in the next line before the %* or
REM  pass them to this script directly
java @user_jvm_args.txt @libraries/net/minecraftforge/forge/1.17.1-37.1.0/win_args.txt %*
pause


 this?

**Comment by timi137137** [comment]
There are 2 ways to start Arclight:
(Recommended) Launch with command java -jar arclight-forge-<mc>-<version>.jar nogui. The nogui argument will disable the server control panel.
Drop the downloaded jar into mods folder and start a forge server.

use the Recommended launch. if you can't, try learn start a basic bukkit server

**Comment by KMyungs** [comment]
i know start basic bukkit server.

' -jar arclight-forge--.jar nogui.' type at bukkit?

**Comment by timi137137** [comment]
In fact, Arclight startup mode is similar to Bukkit, everything will be downloaded and installed by Arclight, if the folder is not created, you can create your own, do not directly run the original Forge

**Comment by KMyungs** [comment]
java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at io.izzel.arclight.boot.application.Main_Forge.main(Main_Forge.java:23)
        at io.izzel.arclight.server.Launcher.main(Launcher.java:18)
Caused by: java.lang.NullPointerException: Cannot invoke "java.nio.file.Path.toString()" because the return value of "java.nio.file.Path.getFileName()" is null
        at cpw.mods.securejarhandler@0.9.54/cpw.mods.jarhandling.JarMetadata.fromFileName(JarMetadata.java:60)
        at cpw.mods.securejarhandler@0.9.54/cpw.mods.jarhandling.JarMetadata.from(JarMetadata.java:44)
        at cpw.mods.securejarhandler@0.9.54/cpw.mods.jarhandling.SecureJar.lambda$from$1(SecureJar.java:42)
        at cpw.mods.securejarhandler@0.9.54/cpw.mods.jarhandling.impl.Jar.<init>(Jar.java:133)
        at cpw.mods.securejarhandler@0.9.54/cpw.mods.jarhandling.SecureJar.from(SecureJar.java:58)
        at cpw.mods.securejarhandler@0.9.54/cpw.mods.jarhandling.SecureJar.from(SecureJar.java:50)
        at cpw.mods.securejarhandler@0.9.54/cpw.mods.jarhandling.SecureJar.from(SecureJar.java:42)
        at cpw.mods.bootstraplauncher@0.1.17/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:60)
        ... 6 more
Fail to launch Arclight.

**Comment by KMyungs** [comment]
@echo off
java -Xms3G -Xmx8G -jar arclight-forge-1.17.1-1.0.2.jar
pause

I try made bukkit

**Comment by timi137137** [comment]
You can create a folder with the same name in this folder and use Arclight in it。this problem for forge. e.g. first folder name is A,go to A create a new A folder

**Comment by KMyungs** [comment]
sry i dont understand.

**Comment by timi137137** [comment]
emmmmm,Is to put arclight in the folder of the same name folder run

**Comment by timi137137** [comment]
2 folders

**Comment by KMyungs** [comment]
![image](https://user-images.githubusercontent.com/97261799/148642565-9896e83b-c9af-4df8-836a-66354951f7b2.png)

![image](https://user-images.githubusercontent.com/97261799/148642569-4746f49a-4cd0-472b-a1ab-c6f6181e4c0d.png)

like that?

**Comment by timi137137** [comment]
change this 'a' to 'test'

**Comment by KMyungs** [comment]
![image](https://user-images.githubusercontent.com/97261799/148642620-60ae0e60-65b9-431c-a3e7-bb4fab2da7a5.png)
 this?

**Comment by timi137137** [comment]
yeah! try run

**Comment by KMyungs** [comment]
[20:40:39 INFO]: Reloading ResourceManager: Default, forge-1.17.1-37.1.0-universal.jar, arclight-1.17.1-1.0.2-a79a6a5.jar
[20:40:40 INFO]: Loaded 7 recipes
[20:40:41 INFO]: Loaded 1137 advancements
[20:40:43 INFO]: Starting minecraft server version 1.17.1
[20:40:43 INFO]: Loading properties
[20:40:43 INFO]: Default game type: SURVIVAL
[20:40:43 INFO]: Generating keypair
[20:40:43 INFO]: Starting Minecraft server on *:25565
[20:40:43 INFO]: Using default channel type
[20:40:43 ERROR] [STDERR]: java.lang.ExceptionInInitializerError
[20:40:43 INFO] [Arclight]: 正在向 Bukkit 注册 ...
[20:40:43 ERROR] [STDERR]:      at TRANSFORMER/arclight@1.17.1-1.0.2-a79a6a5/org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.<init>(CraftTask.java:61)
[20:40:43 ERROR] [STDERR]:      at TRANSFORMER/arclight@1.17.1-1.0.2-a79a6a5/org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.<init>(CraftTask.java:37)
[20:40:43 ERROR] [STDERR]:      at TRANSFORMER/arclight@1.17.1-1.0.2-a79a6a5/org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.<init>(CraftScheduler.java:68)
[20:40:43 ERROR] [STDERR]:      at TRANSFORMER/arclight@1.17.1-1.0.2-a79a6a5/org.bukkit.craftbukkit.v1_17_R1.CraftServer.<init>(CraftServerMixin.java:257)
[20:40:43 ERROR] [STDERR]:      at TRANSFORMER/arclight@1.17.1-1.0.2-a79a6a5/io.izzel.arclight.common.mod.server.ArclightServer.createOrLoad(ArclightServer.java:33)
[20:40:43 ERROR] [STDERR]:      at TRANSFORMER/minecraft@1.17.1/net.minecraft.server.players.PlayerList.handler$zce000$arclight$loadServer(PlayerListMixin.java:1000)
[20:40:43 ERROR] [STDERR]:      at TRANSFORMER/minecraft@1.17.1/net.minecraft.server.players.PlayerList.<init>(PlayerListMixin.java:125)
[20:40:43 ERROR] [STDERR]:      at TRANSFORMER/minecraft@1.17.1/net.minecraft.server.dedicated.DedicatedPlayerList.<init>(SourceFile:16)
[20:40:43 ERROR] [STDERR]:      at TRANSFORMER/minecraft@1.17.1/net.minecraft.server.dedicated.DedicatedServer.m_7038_(DedicatedServerMixin.java:169)
[20:40:43 ERROR] [STDERR]:      at TRANSFORMER/minecraft@1.17.1/net.minecraft.server.MinecraftServer.m_130011_(MinecraftServerMixin.java:2011)
[20:40:43 ERROR] [STDERR]:      at TRANSFORMER/minecraft@1.17.1/net.minecraft.server.MinecraftServer.m_177918_(MinecraftServerMixin.java:258)
[20:40:43 ERROR] [STDERR]:      at java.base/java.lang.Thread.run(Thread.java:833)
[20:40:43 ERROR] [STDERR]: Caused by: java.lang.UnsupportedOperationException: PermittedSubclasses requires ASM9
[20:40:43 ERROR] [STDERR]:      at org.objectweb.asm@9.1.0/org.objectweb.asm.ClassVisitor.visitPermittedSubclass(ClassVisitor.java:266)
[20:40:43 ERROR] [STDERR]:      at org.objectweb.asm@9.1.0/org.objectweb.asm.ClassReader.accept(ClassReader.java:683)
[20:40:43 ERROR] [STDERR]:      at org.objectweb.asm@9.1.0/org.objectweb.asm.ClassReader.accept(ClassReader.java:401)
[20:40:43 ERROR] [STDERR]:      at MC-BOOTSTRAP/cpw.mods.modlauncher@9.0.7/cpw.mods.modlauncher.TransformerClassWriter.computeHierarchyFromFile(TransformerClassWriter.java:151)
[20:40:43 ERROR] [STDERR]:      at MC-BOOTSTRAP/cpw.mods.modlauncher@9.0.7/cpw.mods.modlauncher.TransformerClassWriter.computeHierarchy(TransformerClassWriter.java:112)
[20:40:43 ERROR] [STDERR]:      at MC-BOOTSTRAP/cpw.mods.modlauncher@9.0.7/cpw.mods.modlauncher.TransformerClassWriter$SuperCollectingVisitor.visit(TransformerClassWriter.java:177)
[20:40:43 ERROR] [STDERR]:      at org.objectweb.asm@9.1.0/org.objectweb.asm.ClassReader.accept(ClassReader.java:546)
[20:40:43 ERROR] [STDERR]:      at org.objectweb.asm@9.1.0/org.objectweb.asm.ClassReader.accept(ClassReader.java:401)
[20:40:43 ERROR] [STDERR]:      at MC-BOOTSTRAP/cpw.mods.modlauncher@9.0.7/cpw.mods.modlauncher.TransformerClassWriter.computeHierarchyFromFile(TransformerClassWriter.java:151)
[20:40:43 ERROR] [STDERR]:      at MC-BOOTSTRAP/cpw.mods.modlauncher@9.0.7/cpw.mods.modlauncher.TransformerClassWriter.computeHierarchy(TransformerClassWriter.java:112)
[20:40:43 ERROR] [STDERR]:      at MC-BOOTSTRAP/cpw.mods.modlauncher@9.0.7/cpw.mods.modlauncher.TransformerClassWriter.getSupers(TransformerClassWriter.java:83)
[20:40:43 ERROR] [STDERR]:      at MC-BOOTSTRAP/cpw.mods.modlauncher@9.0.7/cpw.mods.modlauncher.TransformerClassWriter.getCommonSuperClass(TransformerClassWriter.java:66)
[20:40:43 ERROR] [STDERR]:      at org.objectweb.asm@9.1.0/org.objectweb.asm.SymbolTable.addMergedType(SymbolTable.java:1202)
[20:40:43 ERROR] [STDERR]:      at org.objectweb.asm@9.1.0/org.objectweb.asm.Frame.merge(Frame.java:1299)
[20:40:43 ERROR] [STDERR]:      at org.objectweb.asm@9.1.0/org.objectweb.asm.Frame.merge(Frame.java:1197)
[20:40:43 ERROR] [STDERR]:      at org.objectweb.asm@9.1.0/org.objectweb.asm.MethodWriter.computeAllFrames(MethodWriter.java:1610)
[20:40:43 ERROR] [STDERR]:      at org.objectweb.asm@9.1.0/org.objectweb.asm.MethodWriter.visitMaxs(MethodWriter.java:1546)
[20:40:43 ERROR] [STDERR]:      at org.objectweb.asm.tree@9.1.0/org.objectweb.asm.tree.MethodNode.accept(MethodNode.java:769)
[20:40:43 ERROR] [STDERR]:      at org.objectweb.asm.tree@9.1.0/org.objectweb.asm.tree.MethodNode.accept(MethodNode.java:649)
[20:40:43 ERROR] [STDERR]:      at org.objectweb.asm.tree@9.1.0/org.objectweb.asm.tree.ClassNode.accept(ClassNode.java:452)
[20:40:43 ERROR] [STDERR]:      at MC-BOOTSTRAP/cpw.mods.modlauncher@9.0.7/cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:133)
[20:40:43 ERROR] [STDERR]:      at MC-BOOTSTRAP/cpw.mods.modlauncher@9.0.7/cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:50)
[20:40:43 ERROR] [STDERR]:      at cpw.mods.securejarhandler@0.9.54/cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:110)
[20:40:43 ERROR] [STDERR]:      at cpw.mods.securejarhandler@0.9.54/cpw.mods.cl.ModuleClassLoader.lambda$findClass$16(ModuleClassLoader.java:213)
[20:40:43 ERROR] [STDERR]:      at cpw.mods.securejarhandler@0.9.54/cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:223)
[20:40:43 ERROR] [STDERR]:      at cpw.mods.securejarhandler@0.9.54/cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:213)
[20:40:43 ERROR] [STDERR]:      at cpw.mods.securejarhandler@0.9.54/cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:130)
[20:40:43 ERROR] [STDERR]:      at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
[20:40:43 ERROR] [STDERR]:      at TRANSFORMER/arclight@1.17.1-1.0.2-a79a6a5/org.bukkit.craftbukkit.v1_17_R1.SpigotTimings.<clinit>(SpigotTimings.java:38)
[20:40:43 ERROR] [STDERR]:      ... 12 more
[20:40:44 INFO] [Arclight]: 注册了 0 个材料，其中 0 个方块 0 个物品
[20:40:44 ERROR]: Encountered an unexpected exception
java.lang.NullPointerException: Cannot invoke "org.bukkit.craftbukkit.v1_17_R1.CraftServer.loadPlugins()" because the return value of "org.bukkit.Bukkit.getServer()" is null
        at net.minecraft.server.dedicated.DedicatedServer.handler$zbl000$arclight$loadPlugins(DedicatedServerMixin.java:704) ~[server-1.17.1-20210706.113038-srg.jar%2355!:?]
        at net.minecraft.server.dedicated.DedicatedServer.m_7038_(DedicatedServerMixin.java:169) ~[server-1.17.1-20210706.113038-srg.jar%2355!:?]
        at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServerMixin.java:2011) ~[server-1.17.1-20210706.113038-srg.jar%2355!:?]
        at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServerMixin.java:258) ~[server-1.17.1-20210706.113038-srg.jar%2355!:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
[20:40:44 INFO] [Arclight]: 注册了 1 个新的药水效果
[20:40:44 INFO] [Arclight]: 注册了 38 个新的附魔
[20:40:44 INFO] [Arclight]: 注册了 0 个新的生物类型
[20:40:44 INFO] [Arclight]: 注册了 0 个新的村民职业
[20:40:44 INFO] [Arclight]: 注册了 0 个新的生物群系
[20:40:44 ERROR] [Arclight]: 处理 Forge 注册时出错
java.lang.NullPointerException: Cannot invoke "org.bukkit.Server.getLogger()" because "org.bukkit.Bukkit.server" is null
        at org.bukkit.Bukkit.getLogger(Bukkit.java:716) ~[arclight-1.17.1-1.0.2-a79a6a5.jar%2353!:arclight-1.17.1-1.0.2-a79a6a5]
        at org.spigotmc.SpigotConfig.debug(SpigotConfig.java:376) ~[arclight-1.17.1-1.0.2-a79a6a5.jar%2353!:arclight-1.17.1-1.0.2-a79a6a5]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at org.spigotmc.SpigotConfig.readConfig(SpigotConfig.java:110) ~[arclight-1.17.1-1.0.2-a79a6a5.jar%2353!:arclight-1.17.1-1.0.2-a79a6a5]
        at org.spigotmc.SpigotConfig.init(SpigotConfig.java:76) ~[arclight-1.17.1-1.0.2-a79a6a5.jar%2353!:arclight-1.17.1-1.0.2-a79a6a5]
        at io.izzel.arclight.common.mod.server.ArclightServer.createOrLoad(ArclightServer.java:43) ~[arclight-1.17.1-1.0.2-a79a6a5.jar%2353!:arclight-1.17.1-1.0.2-a79a6a5]
        at net.minecraft.server.players.PlayerList.handler$zce000$arclight$loadServer(PlayerListMixin.java:1000) ~[server-1.17.1-20210706.113038-srg.jar%2355!:?]
        at net.minecraft.server.players.PlayerList.<init>(PlayerListMixin.java:125) ~[server-1.17.1-20210706.113038-srg.jar%2355!:?]
        at net.minecraft.server.dedicated.DedicatedPlayerList.<init>(SourceFile:16) ~[server-1.17.1-20210706.113038-srg.jar%2355!:?]
        at net.minecraft.server.dedicated.DedicatedServer.m_7038_(DedicatedServerMixin.java:169) ~[server-1.17.1-20210706.113038-srg.jar%2355!:?]
        at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServerMixin.java:2011) ~[server-1.17.1-20210706.113038-srg.jar%2355!:?]
        at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServerMixin.java:258) ~[server-1.17.1-20210706.113038-srg.jar%2355!:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
> 2022-01-08 20:40:44,966 Server thread WARN Recursive call to getLogger for org.jline ignored.
2022-01-08 20:40:44,975 Server thread WARN Recursive call to getLogger for org.jline ignored.
2022-01-08 20:40:44,975 Server thread WARN Recursive call to getLogger for org.jline ignored.
