### ISSUE TITLE
Apotheosis Incompatibility

### ISSUE THREAD

**Issue by HerrBeef** [IzzelAliz/Arclight#51]
### I am running

* **Arclight** [VERSION] arclight-forge-1.15-1.0.9 Snapshot (Commit Fix respawn is not available when FirstAid present)

* **This is the latest development version** Y

* **Java** 8 Update 261

* **Operating System** Windows 10 Pro - 2004

* **Plugins** None

* **Mods**
[Apotheosis 1.15.2 3.3.5](https://www.curseforge.com/minecraft/mc-mods/apotheosis)
[Placebo 1.15.2 3.1.0](https://www.curseforge.com/minecraft/mc-mods/placebo)

### Description
Crash on Start

### Step to reproduce
1. Install those mods
2. Run server
3. Error

**Reproducible in Forge** N

### Logs

[ERROR LOG]
<details><pre>
[debug.log](https://github.com/IzzelAliz/Arclight/files/5214508/debug.log)
</pre></details>

**Comment by IzzelAliz** [comment]
Apotheosis has done too much modification to vanilla things, so it may be hard to do compatibilities on my end.

I'll look into Placebo later.

**Comment by HerrBeef** [comment]
> 
> 
> Apotheosis has done too much modification to vanilla things, so it may be hard to do compatibilities on my end.
> 
> I'll look into Placebo later.

Sorry forgot to write that Placebo is required for Apotheosis so i included it in the modlist. But Placebo works fine with Arclight. Just Apotheosis doesn't work.

**Comment by HerrBeef** [comment]
Btw when i'm using another worldgenerator instead of default (for example terraforged) with all modules of apotheosis enabled, the crash looks like this:
<details><pre>
[19:45:02] [Server thread/ERROR] [Arclight/]: Error occured registring Forge
java.lang.NullPointerException: null
        at org.spigotmc.SpigotConfig.registerCommands(SpigotConfig.java:83) ~[?:arclight-1.15.2-1.0.9-SNAPSHOT-07336a5] {re:mixin,re:classloading}
        at io.izzel.arclight.common.mod.server.ArclightServer.createOrLoad(ArclightServer.java:35) [?:arclight-1.15.2-1.0.9-SNAPSHOT-07336a5] {re:mixin,re:classloading}
        at net.minecraft.server.management.PlayerList.handler$zop000$arclight$loadCraftBukkit(PlayerListMixin.java:988) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.management.PlayerListMixin,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.server.management.PlayerList.<init>(PlayerListMixin.java:104) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.management.PlayerListMixin,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.server.dedicated.DedicatedPlayerList.<init>(SourceFile:14) [?:?] {re:classloading}
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServerMixin.java:182) [?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.dedicated.DedicatedServerMixin,pl:mixin:A}
        at net.minecraft.server.MinecraftServer.run(MinecraftServerMixin.java:1932) [?:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,pl:mixin:A,pl:runtimedistcleaner:A}
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_261] {}
[19:45:02] [Server thread/ERROR] [minecraft/MinecraftServer]: Encountered an unexpected exception
java.lang.NullPointerException: null
        at org.bukkit.craftbukkit.v1_15_R1.util.CraftMagicNumbers.checkSupported(CraftMagicNumbersMixin.java:263) ~[?:arclight-1.15.2-1.0.9-SNAPSHOT-07336a5] {re:mixin,re:classloading,pl:mixin:APP:mixins.arclight.bukkit.json:CraftMagicNumbersMixin,pl:mixin:A}
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoaderMixin.java:131) ~[?:arclight-1.15.2-1.0.9-SNAPSHOT-07336a5] {re:mixin,re:classloading,pl:mixin:APP:mixins.arclight.bukkit.json:JavaPluginLoaderMixin,pl:mixin:A}
        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:394) ~[?:arclight-1.15.2-1.0.9-SNAPSHOT-07336a5] {re:mixin,re:classloading}
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:301) ~[?:arclight-1.15.2-1.0.9-SNAPSHOT-07336a5] {re:mixin,re:classloading}
        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.loadPlugins(CraftServerMixin.java:353) ~[?:arclight-1.15.2-1.0.9-SNAPSHOT-07336a5] {re:mixin,re:classloading,pl:mixin:APP:mixins.arclight.bukkit.json:CraftServerMixin,pl:mixin:A}
        at net.minecraft.server.dedicated.DedicatedServer.handler$zon000$arclight$loadPlugins(DedicatedServerMixin.java:650) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.dedicated.DedicatedServerMixin,pl:mixin:A}
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServerMixin.java:182) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.dedicated.DedicatedServerMixin,pl:mixin:A}
        at net.minecraft.server.MinecraftServer.run(MinecraftServerMixin.java:1932) [?:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,pl:mixin:A,pl:runtimedistcleaner:A}
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_261] {}
[19:45:02] [Server thread/ERROR] [minecraft/MinecraftServer]: This crash report has been saved to: H:\Servers\MDM-Light Arclight - SNAPSHOT\.\crash-reports\crash-2020-09-17_19.45.02-server.txt
[19:45:02] [Server thread/INFO] [minecraft/MinecraftServer]: Stopping server
[19:45:02] [Server thread/INFO] [minecraft/MinecraftServer]: Saving players
[19:45:02] [Server thread/INFO] [minecraft/MinecraftServer]: Saving worlds
[19:45:02] [Server thread/ERROR] [minecraft/MinecraftServer]: Exception stopping the server
java.lang.NullPointerException: Cannot Hotload Dim: Overworld is not Loaded!
        at org.apache.commons.lang3.Validate.notNull(Validate.java:225) ~[server-1.15.2-extra.jar:?] {re:mixin}
        at net.minecraftforge.common.DimensionManager.initWorld(DimensionManagerMixin.java:279) ~[?:?] {re:mixin,re:classloading,pl:mixin:APP:mixins.arclight.forge.json:DimensionManagerMixin,pl:mixin:A}
        at net.minecraftforge.common.DimensionManager.getWorld(DimensionManagerMixin.java:208) ~[?:?] {re:mixin,re:classloading,pl:mixin:APP:mixins.arclight.forge.json:DimensionManagerMixin,pl:mixin:A}
        at net.minecraft.server.MinecraftServer.func_71218_a(MinecraftServerMixin.java:1004) ~[?:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.func_213211_a(MinecraftServerMixin.java:536) ~[?:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.func_71260_j(MinecraftServerMixin.java:568) ~[?:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.server.dedicated.DedicatedServer.func_71260_j(DedicatedServerMixin.java:550) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.dedicated.DedicatedServerMixin,pl:mixin:A}
        at net.minecraft.server.MinecraftServer.run(MinecraftServerMixin.java:2012) [?:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,pl:mixin:A,pl:runtimedistcleaner:A}
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_261] {}
</details></pre>

and when i disable **Deadly Module** and **Enchanting Module** in apotheosis.cfg (and if **Quark** is installed **Matrix Enchanting** has to be disabled) than Apotheosis works fine. (It must be **deactivated on the Clientside** too otherwise a connection error occures)
