### ISSUE TITLE
增加模组Survive启动一瞬间崩溃

### ISSUE THREAD

**Issue by Arctc1Fox** [IzzelAliz/Arclight#572]
Survive模组在加入服务器后启动服务器会瞬间崩溃，经过测试在forge端可以正常启动但是换到arc这边就会崩溃。log如下
正在使用 zh_cn 语言，zh_cn 作为备选语言
[21:22:25 INFO] [Arclight]:

       ___           ___     __   /\
      /   | ________/ (_)__ / /  / /
     / /| |/ __/ __/ / / _ / _ \/__/
    / ___ / / / /_/ / / / / // / /
   /_/  |/_/  \__/_/_/\_ /_//_/ /
                     /__/     \/

    运行版本 arclight-1.18.2-1.0.3-c609b197
    构建日期 2022-04-26 10:59:58

[21:22:25 INFO] [c.m.m.Launcher/MODLAUNCHER]: ModLauncher running: args [--launchTarget, forgeserver, --fml.forgeVersion, 40.1.0, --fml.mcVersion, 1.18.2, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20220404.173914, nogui]
[21:22:25 INFO] [c.m.m.Launcher/MODLAUNCHER]: ModLauncher 9.1.3+9.1.3+main.9b69c82a starting: java version 17 by Oracle Corporation
[21:22:25 INFO] [mixin]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=union:/C:/Users/k940/Desktop/1.18.2_Forge_纯模组/libraries/org/spongepowered/mixin/0.8.5/mixin-0.8.5.jar%2316!/ Service=ModLauncher Env=SERVER
[21:22:30 INFO] [mixin]: Compatibility level set to JAVA_17
[21:22:30 INFO] [mixin]: Successfully loaded Mixin Connector [io.izzel.arclight.common.mod.ArclightConnector]
[21:22:30 INFO] [Arclight]: 核心 Mixin 配置已加载
[21:22:30 INFO] [Arclight]: 服务端优化 Mixin 配置已加载
[21:22:30 INFO] [c.m.m.LaunchServiceHandler/MODLAUNCHER]: Launching target 'forgeserver' with arguments [nogui]
[21:22:40 WARN] [mixin]: @Redirect conflict. Skipping mixins.arclight.core.json:world.entity.player.PlayerMixin->@Redirect::arclight$exhaustInfo(Lnet/minecraft/world/entity/player/Player;F)V with priority 500, already redirected by survive.mixins.json:PlayerMixin->@Redirect::morphExhaustion(Lnet/minecraft/world/entity/player/Player;F)V with priority 1000
[21:22:40 WARN] [mixin]: @Redirect conflict. Skipping mixins.arclight.core.json:world.entity.player.PlayerMixin->@Redirect::arclight$exhaustInfo(Lnet/minecraft/world/entity/player/Player;F)V with priority 500, already redirected by survive.mixins.json:PlayerMixin->@Redirect::morphExhaustion(Lnet/minecraft/world/entity/player/Player;F)V with priority 1000
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
        at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:39)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.Launcher.run(Launcher.java:106)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.Launcher.main(Launcher.java:77)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
        at MC-BOOTSTRAP/arclight.boot@1.18.2-1.0.3/io.izzel.arclight.boot.application.ApplicationBootstrap.accept(ApplicationBootstrap.java:41)
        at MC-BOOTSTRAP/arclight.boot@1.18.2-1.0.3/io.izzel.arclight.boot.application.ApplicationBootstrap.accept(ApplicationBootstrap.java:12)
        at cpw.mods.bootstraplauncher@1.0.0/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at io.izzel.arclight.boot.application.Main_Forge.main(Main_Forge.java:23)
        at io.izzel.arclight.server.Launcher.main(Launcher.java:18)
Caused by: java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at MC-BOOTSTRAP/fmlloader@1.18.2-40.1.0/net.minecraftforge.fml.loading.targets.CommonServerLaunchHandler.lambda$launchService$0(CommonServerLaunchHandler.java:32)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
        ... 15 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
        at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392)
        at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:250)
        at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.service.modlauncher.MixinTransformationHandler.processClass(MixinTransformationHandler.java:131)
        at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.launch.MixinLaunchPluginLegacy.processClass(MixinLaunchPluginLegacy.java:131)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.serviceapi.ILaunchPluginService.processClassWithFlags(ILaunchPluginService.java:156)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:88)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:50)
        at cpw.mods.securejarhandler@1.0.3/cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:110)
        at cpw.mods.securejarhandler@1.0.3/cpw.mods.cl.ModuleClassLoader.lambda$findClass$16(ModuleClassLoader.java:216)
        at cpw.mods.securejarhandler@1.0.3/cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:226)
        at cpw.mods.securejarhandler@1.0.3/cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:216)
        at cpw.mods.securejarhandler@1.0.3/cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:132)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
        at TRANSFORMER/forge@40.1.0/net.minecraftforge.registries.GameData.init(GameData.java:123)
        at TRANSFORMER/forge@40.1.0/net.minecraftforge.registries.GameData.<clinit>(GameData.java:108)
        at TRANSFORMER/minecraft@1.18.2/net.minecraft.core.Registry.forge(Registry.java:407)
        at TRANSFORMER/minecraft@1.18.2/net.minecraft.core.Registry.forge(Registry.java:391)
        at TRANSFORMER/minecraft@1.18.2/net.minecraft.core.Registry.<clinit>(Registry.java:170)
        at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.Bootstrap.m_135870_(BootstrapMixin.java:44)
        at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.Main.main(Main.java:109)
        ... 21 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Redirector arclight$exhaustInfo(Lnet/minecraft/world/entity/player/Player;F)V in mixins.arclight.core.json:world.entity.player.PlayerMixin failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap mixins.arclight.refmap.json
        at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:468)
        at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1362)
        at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1051)
        at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:400)
        at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325)
        at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:383)
        at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:365)
        at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
        ... 41 more
Fail to launch Arclight.

**Comment by timi137137** [comment]
请阅读FAQ和 [提问的智慧](https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md) 并使用模板提问
