### ISSUE TITLE
开不起来

### ISSUE THREAD

**Issue by Y-Yuw** [IzzelAliz/Arclight#597]
### 请确认您已完成以下几件事

- [X] 正在使用最新的 Arclight
- [x] 已为所有插件及模组安装依赖
- [x] 已为所有插件及模组更新至最新版
- [ ] 不可在 Spigot 复现
- [ ] 不可在 Forge 复现

### Arclight 版本

arclight-forge-1.16.5-1.0.23.jar

### Java 版本 | 操作系统

java version "18.0.1.1" 2022-04-22

### 相关 Mod/插件 的名称及版本

```raw
开启报错连mod和插件都没加载
```

### 错误描述

[12:17:58] [main/INFO] [c.m.m.Launcher/MODLAUNCHER]: ModLauncher running: args [--gameDir, ., --launchTarget, fmlserver, --fml.forgeVersion, 36.2.26, --fml.mcpVersion, 20210115.111550, --fml.mcVersion, 1.16.5, --fml.forgeGroup, net.minecraftforge]
[12:17:58] [main/INFO] [c.m.m.Launcher/MODLAUNCHER]: ModLauncher 8.1.3+8.1.3+main-8.1.x.c94d18ec starting: java version 18.0.1.1 by Oracle Corporation
[12:17:58] [main/INFO] [forge/FixSSL]: Added Lets Encrypt root certificates as additional trust
[12:17:58] [main/INFO] [mixin/]: SpongePowered MIXIN Subsystem Version=0.8.4 Source=file:/C:/Users/Admin/Desktop/airland/libraries/org/spongepowered/mixin/0.8.4/mixin-0.8.4.jar Service=ModLauncher Env=SERVER
Exception in thread "main" [12:17:58] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1078]: java.lang.NoClassDefFoundError: org/apache/commons/lang3/tuple/Pair
[12:17:58] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1078]:       at net.minecraftforge.fml.loading.FMLLoader.setupLaunchHandler(FMLLoader.java:192)
[12:17:58] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1078]:       at net.minecraftforge.fml.loading.FMLServiceProvider.initialize(FMLServiceProvider.java:94)
[12:17:58] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1078]:       at cpw.mods.modlauncher.TransformationServiceDecorator.onInitialize(TransformationServiceDecorator.java:68)
[12:17:58] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1078]:       at cpw.mods.modlauncher.TransformationServicesHandler.lambda$initialiseTransformationServices$7(TransformationServicesHandler.java:107)
[12:17:58] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1078]:       at java.base/java.util.HashMap$Values.forEach(HashMap.java:1065)
[12:17:58] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1078]:       at cpw.mods.modlauncher.TransformationServicesHandler.initialiseTransformationServices(TransformationServicesHandler.java:107)
[12:17:58] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1078]:       at cpw.mods.modlauncher.TransformationServicesHandler.initializeTransformationServices(TransformationServicesHandler.java:59)
[12:17:58] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1078]:       at cpw.mods.modlauncher.Launcher.run(Launcher.java:76)
[12:17:58] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1078]:       at cpw.mods.modlauncher.Launcher.main(Launcher.java:66)
[12:17:58] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1078]:       at net.minecraftforge.server.ServerMain$Runner.runLauncher(ServerMain.java:63)
[12:17:58] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1078]:       at net.minecraftforge.server.ServerMain$Runner.access$100(ServerMain.java:60)
[12:17:58] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1078]:       at net.minecraftforge.server.ServerMain.main(ServerMain.java:57)
[12:17:58] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1078]:       at io.izzel.arclight.common.ArclightMain.run(ArclightMain.java:50)
[12:17:58] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1078]:       at io.izzel.arclight.server.Main_Forge.main(Main_Forge.java:16)
[12:17:58] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1078]:       at io.izzel.arclight.server.Launcher.main(Launcher.java:16)
[12:17:58] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1087]: Caused by: java.lang.ClassNotFoundException: org.apache.commons.lang3.tuple.Pair
[12:17:58] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1087]:       at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
[12:17:58] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1087]:       at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
[12:17:58] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1087]:       at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
[12:17:58] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1087]:       ... 15 more

### 复现步骤

打开启动bat直接报

### 报错信息

[latest.log](https://github.com/IzzelAliz/Arclight/files/8795386/latest.log)

**Comment by timi137137** [comment]
看FAQ

**Comment by Y-Yuw** [comment]
ok

**Comment by Y-Yuw** [comment]
> 看FAQ

是forge的问题吗
