### ISSUE TITLE
1.18.2不同版本源码都他妈是一样的

### ISSUE THREAD

**Issue by 1luik** [IzzelAliz/Arclight#631]
### 请确认您已完成以下几件事

- [X] 正在使用最新的 Arclight
- [ ] 已为所有插件及模组安装依赖
- [ ] 已为所有插件及模组更新至最新版
- [X] 不可在 Spigot 复现
- [X] 不可在 Forge 复现

### Arclight 版本

1.18.2-不同版本源码都他妈是一样的，鬼知道

### Java 版本 | 操作系统

与这个问题没关系

### 相关 Mod/插件 的名称及版本

```raw
与这个问题无关
```

### 错误描述

不同版本源码都他妈是一样的，鬼知道

### 复现步骤

git clone --branch 1.18/1.0.5 https://github.com/IzzelAliz/Arclight.git
吧1.18/1.0.5的io.izzel.arclight.forgeinstaller.ForgeInstaller反编译

### 报错信息

[09:19:58] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher running: args [--launchTarget, forgeserver, --fml.fo
rgeVersion, 40.1.52, --fml.mcVersion, 1.18.2, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20220404.173914]
[09:19:58] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher 9.1.3+9.1.3+main.9b69c82a starting: java version 17.
0.1 by Microsoft
[09:19:58] [main/INFO] [mixin/]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=union:/D:/-saa/BC2/ew/Arclight-1.18/
测试/libraries/org/spongepowered/mixin/0.8.5/mixin-0.8.5.jar%2316!/ Service=ModLauncher Env=SERVER
[09:19:59] [main/ERROR] [ne.mi.fm.lo.mo.ModDiscoverer/]: Failed to load locator list
java.util.ServiceConfigurationError: net.minecraftforge.forgespi.locating.IModLocator: Provider io.izzel.arclight.boot.m
od.ArclightLocator_Forge could not be instantiated
        at java.util.ServiceLoader.fail(ServiceLoader.java:586) ~[?:?] {}
        at java.util.ServiceLoader$ProviderImpl.newInstance(ServiceLoader.java:813) ~[?:?] {}
        at java.util.ServiceLoader$ProviderImpl.get(ServiceLoader.java:729) ~[?:?] {}
        at cpw.mods.modlauncher.util.ServiceLoaderUtils.lambda$streamWithErrorHandling$0(ServiceLoaderUtils.java:38) ~[m
odlauncher-9.1.3.jar%237!/:?] {}
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?] {}
        at java.util.ServiceLoader$ProviderSpliterator.tryAdvance(ServiceLoader.java:1499) ~[?:?] {}
        at java.util.Spliterator.forEachRemaining(Spliterator.java:332) ~[?:?] {}
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?] {}
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?] {}
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921) ~[?:?] {}
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?] {}
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682) ~[?:?] {}
        at net.minecraftforge.fml.loading.moddiscovery.ModDiscoverer.<init>(ModDiscoverer.java:35) ~[fmlloader-1.18.2-40
.1.52.jar%2318!/:?] {}
        at net.minecraftforge.fml.loading.FMLLoader.beginModScan(FMLLoader.java:165) ~[fmlloader-1.18.2-40.1.52.jar%2318
!/:1.0] {}
        at net.minecraftforge.fml.loading.FMLServiceProvider.beginScanning(FMLServiceProvider.java:86) ~[fmlloader-1.18.
2-40.1.52.jar%2318!/:1.0] {}
        at cpw.mods.modlauncher.TransformationServiceDecorator.runScan(TransformationServiceDecorator.java:112) ~[modlau
ncher-9.1.3.jar%237!/:?] {}
        at cpw.mods.modlauncher.TransformationServicesHandler.lambda$runScanningTransformationServices$8(TransformationS
ervicesHandler.java:100) ~[modlauncher-9.1.3.jar%237!/:?] {}
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) [?:?] {}
        at java.util.HashMap$ValueSpliterator.forEachRemaining(HashMap.java:1779) [?:?] {}
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) [?:?] {}
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) [?:?] {}
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575) [?:?] {}
        at java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260) [?:?] {}
        at java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616) [?:?] {}
        at java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:622) [?:?] {}
        at java.util.stream.ReferencePipeline.toList(ReferencePipeline.java:627) [?:?] {}
        at cpw.mods.modlauncher.TransformationServicesHandler.runScanningTransformationServices(TransformationServicesHa
ndler.java:102) [modlauncher-9.1.3.jar%237!/:?] {}
        at cpw.mods.modlauncher.TransformationServicesHandler.initializeTransformationServices(TransformationServicesHan
dler.java:55) [modlauncher-9.1.3.jar%237!/:?] {}
        at cpw.mods.modlauncher.Launcher.run(Launcher.java:87) [modlauncher-9.1.3.jar%237!/:?] {}
        at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.1.3.jar%237!/:?] {}
        at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.1.3.jar%2
37!/:?] {}
        at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.1.3.jar%2
37!/:?] {}
        at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149) [bootstraplauncher-1.0.0.jar:?]
 {}
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
        at io.izzel.arclight.boot.application.Main_Forge.main(Main_Forge.java:23) [arclight-forge-1.18.2-1.0.5.zip:arcli
ght-1.18.2-1.0.5-00ca124c] {}
        at io.izzel.arclight.server.Launcher.main(Launcher.java:18) [arclight-forge-1.18.2-1.0.5.zip:arclight-1.18.2-1.0
.5-00ca124c] {}
Caused by: java.lang.RuntimeException: java.io.UncheckedIOException: java.io.IOException: Invalid paths argument, contai
ned no existing paths: [.arclight\mod_file\null.jar]
        at io.izzel.arclight.boot.mod.ArclightLocator_Forge.loadJar(ArclightLocator_Forge.java:82) ~[arclight-forge-1.18
.2-1.0.5.zip%231!/:?] {}
        at io.izzel.arclight.boot.mod.ArclightLocator_Forge.<init>(ArclightLocator_Forge.java:32) ~[arclight-forge-1.18.
2-1.0.5.zip%231!/:?] {}
        at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {}
        at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?]
{}
        at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
 ~[?:?] {}
        at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?] {}
        at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?] {}
        at java.util.ServiceLoader$ProviderImpl.newInstance(ServiceLoader.java:789) ~[?:?] {}
        ... 37 more
Caused by: java.io.UncheckedIOException: java.io.IOException: Invalid paths argument, contained no existing paths: [.arc
light\mod_file\null.jar]
        at cpw.mods.jarhandling.impl.Jar.<init>(Jar.java:74) ~[securejarhandler-1.0.3.jar:?] {}
        at cpw.mods.jarhandling.SecureJar.from(SecureJar.java:58) ~[securejarhandler-1.0.3.jar:?] {}
        at cpw.mods.jarhandling.SecureJar.from(SecureJar.java:54) ~[securejarhandler-1.0.3.jar:?] {}
        at cpw.mods.jarhandling.SecureJar.from(SecureJar.java:46) ~[securejarhandler-1.0.3.jar:?] {}
        at io.izzel.arclight.boot.mod.ArclightLocator_Forge.loadJar(ArclightLocator_Forge.java:80) ~[arclight-forge-1.18
.2-1.0.5.zip%231!/:?] {}
        at io.izzel.arclight.boot.mod.ArclightLocator_Forge.<init>(ArclightLocator_Forge.java:32) ~[arclight-forge-1.18.
2-1.0.5.zip%231!/:?] {}
        at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {}
        at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?]
{}
        at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
 ~[?:?] {}
        at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?] {}
        at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?] {}
        at java.util.ServiceLoader$ProviderImpl.newInstance(ServiceLoader.java:789) ~[?:?] {}
        ... 37 more
Caused by: java.io.IOException: Invalid paths argument, contained no existing paths: [.arclight\mod_file\null.jar]
        at cpw.mods.jarhandling.impl.Jar.<init>(Jar.java:74) ~[securejarhandler-1.0.3.jar:?] {}
        at cpw.mods.jarhandling.SecureJar.from(SecureJar.java:58) ~[securejarhandler-1.0.3.jar:?] {}
        at cpw.mods.jarhandling.SecureJar.from(SecureJar.java:54) ~[securejarhandler-1.0.3.jar:?] {}
        at cpw.mods.jarhandling.SecureJar.from(SecureJar.java:46) ~[securejarhandler-1.0.3.jar:?] {}
        at io.izzel.arclight.boot.mod.ArclightLocator_Forge.loadJar(ArclightLocator_Forge.java:80) ~[arclight-forge-1.18
.2-1.0.5.zip%231!/:?] {}
        at io.izzel.arclight.boot.mod.ArclightLocator_Forge.<init>(ArclightLocator_Forge.java:32) ~[arclight-forge-1.18.
2-1.0.5.zip%231!/:?] {}
        at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {}
        at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?]
{}
        at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
 ~[?:?] {}
        at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?] {}
        at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?] {}
        at java.util.ServiceLoader$ProviderImpl.newInstance(ServiceLoader.java:789) ~[?:?] {}
        ... 37 more
java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at io.izzel.arclight.boot.application.Main_Forge.main(Main_Forge.java:23)
        at io.izzel.arclight.server.Launcher.main(Launcher.java:18)
Caused by: java.lang.ExceptionInInitializerError
        at MC-BOOTSTRAP/arclight.forge@1.18.2-1.0.5/io.izzel.arclight.boot.asm.ArclightImplementer.initializeLaunch(Arcl
ightImplementer.java:56)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.LaunchPluginHandler.lambda$announceLaunch$11(Lau
nchPluginHandler.java:100)
        at java.base/java.util.HashMap.forEach(HashMap.java:1421)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.LaunchPluginHandler.announceLaunch(LaunchPluginH
andler.java:100)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler
.java:51)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler
.java:71)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.Launcher.run(Launcher.java:106)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.Launcher.main(Launcher.java:77)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchCo
nsumer.java:26)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchCo
nsumer.java:23)
        at cpw.mods.bootstraplauncher@1.0.0/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149
)
        ... 6 more
Caused by: java.lang.IllegalStateException: Version is not set!
        at MC-BOOTSTRAP/arclight.forge@1.18.2-1.0.5/io.izzel.arclight.api.ArclightVersion.current(ArclightVersion.java:5
8)
        at MC-BOOTSTRAP/arclight.forge@1.18.2-1.0.5/io.izzel.arclight.boot.asm.EntityTypePatcher.<init>(EntityTypePatche
r.java:11)
        at MC-BOOTSTRAP/arclight.forge@1.18.2-1.0.5/io.izzel.arclight.boot.asm.EntityTypePatcher.<clinit>(EntityTypePatc
her.java:9)
        ... 17 more
Fail to launch Arclight.

### 复现用压缩包下载链接(可选)

git clone https://github.com/IzzelAliz/Arclight.git

**Comment by ahdg6** [comment]
说的什么√8，不会好好说话是吧，先不论是否表述清晰，这语气我一个路人看到🔥都能冒上来，你他妈非得用他妈来修饰情感是吧，开源项目我就没见过怨气那么大的

如果你想表述一个与项目无关的编译问题，你应该优先去 discord/github discussion/q群 询问别人，但我估计你他妈甚至没办法放下自己高傲的身段，就只能他妈在 issues 这里污染别人的👀

:smile:

**Comment by heipiao233** [comment]
他妈的他妈的，只知道他妈的是吧
