### ISSUE TITLE
横扫之刃附魔无效

### ISSUE THREAD

**Issue by ECM-xiaokong** [IzzelAliz/Arclight#643]
### 请确认您已完成以下几件事

- [X] 正在使用最新的 Arclight
- [x] 已为所有插件及模组安装依赖
- [x] 已为所有插件及模组更新至最新版
- [X] 不可在 Spigot 复现
- [X] 不可在 Forge 复现

### Arclight 版本

arclight-1.18.2-1.0.6-SNAPSHOT-f9804618

### Java 版本 | 操作系统

java version "17.0.3.1" 2022-04-22 LTS

### 相关 Mod/插件 的名称及版本

```raw
• minecraft server-1.18.2-20220404.173914-srg.jar : minecraft (1.18.2) - 1
• minecraft forge-1.18.2-40.1.31-universal.jar : forge (40.1.31) - 1
• mods_folder journeymap-1.18.2.jar : journeymap (5.8.5) - 1
• arclight arclight-1.18.2-1.0.6-SNAPSHOT-f9804618.jar : arclight (1.18.2-1.0.6-SNAPSHOT-f9804618) - 1
```

### 错误描述

1.18.2原版的横扫之刃附魔无效，无附魔用剑砍也报错，不能使用横扫之刃，对一个怪物/生物砍有横扫之刃特效且后台无报错
对两个及以上怪物/生物砍横扫之刃无效,普通挥刀不会有报错

### 复现步骤

1进入服务器后用普通的剑/附魔横扫之刃的剑砍两个及以上的生物/怪物 

2 横扫之刃，普通攻击对群无效，后台报错

MNT7FW7AGZIKY](https://user-images.githubusercontent.com/62822900/177708159-f05cbf08-8bce-40e5-b611-4fdee66e3bfd.png)
]

### 报错信息

[latest.log](https://github.com/IzzelAliz/Arclight/files/9061044/latest.log)

### 复现用压缩包下载链接(可选)

*

**Comment by 5ur3z** [comment]
我也遇到了同样问题
Error executing task on Server java.lang.NullPointerException: Cannot invoke
"net.minecraft.world.entity.player.Player.canH it ( net.minecraft.world.entity.Entity,
double)" because "this.f 20888
" is null
at net.minecraft.morld.entity.player.Player.m_5706_(PlayerMixin. java:2476) -iserver-1.18.2-20220404.173914-srg . jar8239411:？1
net .minecraft. server .level . ServerPlayer .m_5706_(ServerPlayerMixin. java: 1343) ~[server-1.18.2-20220404.173914-SIg.jarg2394!/:？]
at net. minecraft.server .network . serverGamePacketIistenerImp1 $11ana1er$ae60fb65€3084316a6667089ee74681c.m 141994 (serverplayNetHandlerMixin. java: 1241) -1server-1.18.2-20220404.173914-5rg.
jar823941/:?1
at net . minecraft.network.protocol.game . serverboundInteractPacket $1.m_ 142457_(ServerboundInteractPacket. java:166) ~Iserver-1.18.2-20220404.173914-3rg. jars23941/:2]at net .minecraft .netmork. brotocoi. game . serverboundInteractPacket .m 179617 (serverboundinteractpacket. java: 66)-Iserver-1.18.2-20220404.173914-5rg.jar.23941/:2]at net.minecraft. server .network. ServerGamePacketIistener Impl .m 6946 (ServerPlavNetHandlerMixin. java: 2760) ~rserver-1 .18.2-20220404.173914-Srg.jar%2394:/:31at net . minecraft .network.protocol.game . serverboundInteractPacket .m_5797_(ServerboundInteractPacket . java:53) ~Iserver-1.18.2-20220404.173914-5rg.jar号2394!/:？〕at net.mineazaft .netmork. protoco. game. serverbounarnteractpacket.m 5797-(sezverbounarnteractpacket . java: 13) -isezver-1.18.2-20220404.173914-8tg. jar $239411:21at net. minecraft.network.protocol.Packetuti1s.md1da28c$1ambdasensureRunningonsamerhread$o$0 (Packet rhreaduti1Mixin. java:536） -1server-1.18.2-20220404.173914-srg. jar:2394!/:？]
at net.minecraft.server.TickTask.run (TickTask. java:18) -[server-1.18.2-20220404.173914-srg.jar 2394!/:?] at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:157)~[server-1.18.2-20220404.173914-srg.jar®2394!/:?1
at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23)~[server-1.18.2-20220404.173914-srg.jar82394!/:?1 at net .minecraft. server, MinecraftServer.I_6367_(MinecraftserverMixin. Java: 799) -( server-1.18.2-20220404.173914-srg.Jar823941/1?j
at net.minecraft.server. MinecraftServer.m 6367 (MinecraftServerMixin.iava:164~Iserver-1.18.2-20220404.173914-sra.jar®2394!/:?1
at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:131)~[server-1.18.2-20220404.173914-srg.jar%2394!/:?1
at net .minecraft . server.Minecraftserver.m 129961
_ (MinecraftserverMixin. java:782） ~[server-1.18.2-20220404.173914-55g• jar号23941/:？〕
at net.minecraft. server.ninecraftServer.m_ 7245_ (MinecraftServerNixin. java:776) -[server-1.18.2-20220404.173914-5Ig . jar品2394!1:？]
at net .minecraft .util.thread.BlockableEventLoop.m 18699(BlockableEventLoop . java: 116) ~[server-1.18.2-20220404.173914-Srg.jar%2394:/:3]at net .minecraft .server .MinecraftServer .m_130012_(Minecraftservernixin . java:761) ~[server-1.18.2-20220404.173914-SIg.jarg2394!/:？]
at net .minecraft.server.Minecraftserver.m_130011.
(MinecraftServerMixin. java: 2139）
-lserver-1.18.2-20220404.173914-srg.jar823941/:2]
at net.minecraft.server. Minecraftserver.m_177918_(MinecraftserverMixin. java:261） -Iserver-1.18.2-20220404.173914-5zg. jar82394!/:3]
at java. lang. Thread. run (Thread. java: 833) [?:?]
