### ISSUE TITLE
Server error

### ISSUE THREAD

**Issue by skedyy** [IzzelAliz/Arclight#693]
EDIT:
I have I have solved the problem, removing the mod Moving elevators and the core

I have a server with plugins and mods with arclight and when i try to start the server shows me a error 
MODS : 
Security Craft v1.9.3.1
Additional Guns 0.7.2
Ultimate Car Mod 1.0.1
MrCrayfish Furniture mod 7.0.0 pre29
MrCrayfish Gun mod 1.2.6
Framework 0.2.4
Moving Elevators 1.3.9
supermartijn642configlib 1.1.6
Taterzens 1.9.6

PLUGINS :
SkinsRestorer 
PvPManager 

ERROR : 

`java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
        at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:39)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.Launcher.run(Launcher.java:106)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.Launcher.main(Launcher.java:77)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
        at MC-BOOTSTRAP/arclight.boot/io.izzel.arclight.boot.application.ApplicationBootstrap.accept(ApplicationBootstrap.java:41)
        at MC-BOOTSTRAP/arclight.boot/io.izzel.arclight.boot.application.ApplicationBootstrap.accept(ApplicationBootstrap.java:12)
        at cpw.mods.bootstraplauncher@1.0.0/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at io.izzel.arclight.boot.application.Main_Forge.main(Main_Forge.java:23)
        at io.izzel.arclight.server.Launcher.main(Launcher.java:18)
Caused by: java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at MC-BOOTSTRAP/fmlloader@1.18.2-40.1.59/net.minecraftforge.fml.loading.targets.CommonServerLaunchHandler.lambda$launchService$0(CommonServerLaunchHandler.java:32)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
        ... 15 more
Caused by: java.lang.IllegalAccessError: class io.izzel.arclight.common.mod.util.optimization.OptimizedIndirectMerger cannot access its superinterface net.minecraft.world.phys.shapes.IndexMerger (io.izzel.arclight.common.mod.util.optimization.OptimizedIndirectMerger is in module arclight@1.18.2-1.0.6-7e754e7e of loader 'TRANSFORMER' @34aeacd1; net.minecraft.world.phys.shapes.IndexMerger is in module minecraft@1.18.2 of loader 'TRANSFORMER' @34aeacd1)
        at java.base/java.lang.ClassLoader.defineClass1(Native Method)
        at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1012)
        at cpw.mods.securejarhandler@1.0.3/cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:116)
        at cpw.mods.securejarhandler@1.0.3/cpw.mods.cl.ModuleClassLoader.lambda$findClass$16(ModuleClassLoader.java:216)
        at cpw.mods.securejarhandler@1.0.3/cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:226)
        at cpw.mods.securejarhandler@1.0.3/cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:216)
        at cpw.mods.securejarhandler@1.0.3/cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:132)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
        at TRANSFORMER/minecraft@1.18.2/net.minecraft.world.phys.shapes.Shapes.handler$bge000$arclight$optimizedMerger(Shapes.java:517)
        at TRANSFORMER/minecraft@1.18.2/net.minecraft.world.phys.shapes.Shapes.m_83058_(Shapes.java:323)
        at TRANSFORMER/minecraft@1.18.2/net.minecraft.world.phys.shapes.Shapes.m_83148_(Shapes.java:148)
        at TRANSFORMER/minecraft@1.18.2/net.minecraft.world.phys.shapes.Shapes.m_83113_(Shapes.java:128)
        at TRANSFORMER/minecraft@1.18.2/net.minecraft.world.phys.shapes.Shapes.m_83110_(Shapes.java:120)
        at java.base/java.util.stream.ReduceOps$1ReducingSink.accept(ReduceOps.java:80)
        at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:992)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.reduce(ReferencePipeline.java:657)
        at TRANSFORMER/minecraft@1.18.2/net.minecraft.world.phys.shapes.Shapes.m_83124_(Shapes.java:124)
        at TRANSFORMER/minecraft@1.18.2/net.minecraft.world.level.block.BedBlock.<clinit>(BedBlockMixin.java:60)
        at TRANSFORMER/minecraft@1.18.2/net.minecraft.world.level.block.Blocks.m_50764_(Blocks.java:1056)
        at TRANSFORMER/minecraft@1.18.2/net.minecraft.world.level.block.Blocks.<clinit>(Blocks.java:123)
        at TRANSFORMER/minecraft@1.18.2/net.minecraft.world.level.levelgen.carver.CarverDebugSettings.<clinit>(CarverDebugSettings.java:9)
        at TRANSFORMER/minecraft@1.18.2/net.minecraft.world.level.levelgen.carver.CarverConfiguration.m_190634_(CarverConfiguration.java:16)
        at MC-BOOTSTRAP/datafixerupper@4.1.27/com.mojang.serialization.codecs.RecordCodecBuilder.mapCodec(RecordCodecBuilder.java:76)
        at TRANSFORMER/minecraft@1.18.2/net.minecraft.world.level.levelgen.carver.CarverConfiguration.<clinit>(CarverConfiguration.java:12)
        at TRANSFORMER/minecraft@1.18.2/net.minecraft.world.level.levelgen.carver.WorldCarver.<clinit>(WorldCarver.java:30)
        at TRANSFORMER/minecraft@1.18.2/net.minecraft.data.worldgen.Carvers.<clinit>(Carvers.java:19)
        at TRANSFORMER/minecraft@1.18.2/net.minecraft.data.BuiltinRegistries.m_206400_(BuiltinRegistries.java:45)
        at TRANSFORMER/minecraft@1.18.2/net.minecraft.data.BuiltinRegistries.m_206392_(BuiltinRegistries.java:101)
        at java.base/java.util.LinkedHashMap.forEach(LinkedHashMap.java:721)
        at TRANSFORMER/minecraft@1.18.2/net.minecraft.data.BuiltinRegistries.<clinit>(BuiltinRegistries.java:100)
        at TRANSFORMER/minecraft@1.18.2/net.minecraft.core.Registry.<clinit>(Registry.java:633)
        at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.Bootstrap.m_135870_(BootstrapMixin.java:44)
        at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.Main.main(Main.java:109)
        ... 21 more
Fail to launch Arclight.`

**Comment by HotoRas** [comment]
If it's fixed, please close the issue

**Comment by skedyy** [comment]
> If it's fixed, please close the issue

Sorry
