### ISSUE TITLE
The Command /restart not finish

### ISSUE THREAD

**Issue by TheJhoNY75** [IzzelAliz/Arclight#715]
### I have confirmed that ...

- [X] Arclight is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Forge

### Arclight version

arclight-forge-1.18.2-1.0.6

### OS & Java versions

Windows 10,  openjdk 17.0.1 2021-10-19 LTS

### Plugins and Mods

```raw
no mods, no plugins
```

### Description

using the /restart command does not finish the process. and that does not allow the new process to work properly.

when using the /stop command there is an arclight function that forces the closing:
[06sep.2022 09:29:04.708] [Exit Thread/INFO] [Arclight/]: 8 threads not shutting down correctly, force exiting

but when you use the command /restart that no happen!

and if you use the command from the client it gives a different error and the process is not finished either:

java.util.ConcurrentModificationException

### Step to reproduce

1 install arclight-1.18.2-1.0.6
2 accept eula
3 execute de command /restart

### Logs

C:\Users\jhoni\Desktop\sd>"C:\Program Files\Java\jdk-17.0.4\bin\java.exe" -Xmx8G -Xms1G -jar server.jar nogui
????? es_mx ???
???? es_mx ???zh_cn ??????
[13:25:19 INFO] [Arclight]:

       ___           ___     __   /\
      /   | ________/ (_)__ / /  / /
     / /| |/ __/ __/ / / _ / _ \/__/
    / ___ / / / /_/ / / / / // / /
   /_/  |/_/  \__/_/_/\_ /_//_/ /
                     /__/     \/

    运行版本 arclight-1.18.2-1.0.6-7e754e7e
    构建日期 2022-07-28 14:36:31

[13:25:19 INFO] [c.m.m.Launcher/MODLAUNCHER]: ModLauncher running: args [--launchTarget, forgeserver, --fml.forgeVersion, 40.1.59, --fml.mcVersion, 1.18.2, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20220404.173914, nogui]
[13:25:19 INFO] [c.m.m.Launcher/MODLAUNCHER]: ModLauncher 9.1.3+9.1.3+main.9b69c82a starting: java version 17.0.4 by Oracle Corporation
[13:25:19 INFO] [mixin]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=union:/C:/Users/jhoni/Desktop/sd/libraries/org/spongepowered/mixin/0.8.5/mixin-0.8.5.jar%2316!/ Service=ModLauncher Env=SERVER
[13:25:21 INFO] [mixin]: Successfully loaded Mixin Connector [io.izzel.arclight.common.mod.ArclightConnector]
[13:25:21 INFO] [Arclight]: 核心 Mixin 配置已加载
[13:25:21 INFO] [Arclight]: 服务端优化 Mixin 配置已加载
[13:25:21 INFO] [c.m.m.LaunchServiceHandler/MODLAUNCHER]: Launching target 'forgeserver' with arguments [nogui]
[13:25:31 INFO] [Arclight]: Arclight Mod 已加载
[13:25:32 INFO] [Arclight]: Arclight 事件系统已注册
[13:25:32 INFO]: Forge mod loading, version 40.1.59, for MC 1.18.2 with MCP 20220404.173914
[13:25:32 INFO]: MinecraftForge v40.1.59 Initialized
[13:25:33 INFO]: [forge] Starting version check at https://files.minecraftforge.net/net/minecraftforge/forge/promotions_slim.json
[13:25:34 INFO]: [forge] Found status: OUTDATED Current: 40.1.59 Target: 40.1.76
[13:25:34 INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[13:25:35 WARN]: Assets URL 'union:/C:/Users/jhoni/Desktop/sd/libraries/net/minecraft/server/1.18.2-20220404.173914/server-1.18.2-20220404.173914-srg.jar%2370!/assets/.mcassetsroot' uses unexpected schema
[13:25:35 WARN]: Assets URL 'union:/C:/Users/jhoni/Desktop/sd/libraries/net/minecraft/server/1.18.2-20220404.173914/server-1.18.2-20220404.173914-srg.jar%2370!/data/.mcassetsroot' uses unexpected schema
[13:25:38 WARN]: Ambiguity between arguments [teleport, location] and [teleport, destination] with inputs: [0.1 -0.5 .9, 0 0 0]
[13:25:38 WARN]: Ambiguity between arguments [teleport, location] and [teleport, targets] with inputs: [0.1 -0.5 .9, 0 0 0]
[13:25:38 WARN]: Ambiguity between arguments [teleport, destination] and [teleport, targets] with inputs: [Player, 0123, @e, dd12be42-52a9-4a91-a8a1-11c01849e498]
[13:25:38 WARN]: Ambiguity between arguments [teleport, targets] and [teleport, destination] with inputs: [Player, 0123, dd12be42-52a9-4a91-a8a1-11c01849e498]
[13:25:38 WARN]: Ambiguity between arguments [teleport, targets, location] and [teleport, targets, destination] with inputs: [0.1 -0.5 .9, 0 0 0]
[13:25:41 INFO]: Loaded 7 recipes
[13:25:43 INFO]: Loaded 1141 advancements
[13:25:44 INFO]: Starting minecraft server version 1.18.2
[13:25:44 INFO]: Loading properties
[13:25:44 INFO]: Default game type: SURVIVAL
[13:25:44 INFO]: Generating keypair
[13:25:44 INFO]: Starting Minecraft server on *:25565
[13:25:44 INFO]: Using default channel type
[13:25:45 INFO] [Minecraft]: This server is running Arclight version arclight-1.18.2-1.0.6-7e754e7e (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT)
[13:25:45 INFO] [Arclight]: 正在向 Bukkit 注册 ...
[13:25:45 INFO] [Arclight]: 注册了 0 个材料，其中 0 个方块 0 个物品
[13:25:45 INFO] [Arclight]: 注册了 1 个新的药水效果
[13:25:45 INFO] [Arclight]: 注册了 38 个新的附魔
[13:25:45 INFO] [Arclight]: 注册了 0 个新的生物类型
[13:25:45 INFO] [Arclight]: 注册了 0 个新的村民职业
[13:25:45 INFO] [Arclight]: 注册了 0 个新的生物群系
[13:25:45 INFO] [Minecraft]: Debug logging is enabled
[13:25:45 INFO] [Minecraft]: Using 4 threads for Netty based IO
[13:25:45 INFO] [STDOUT]: Server Ping Player Sample Count: 12
[13:25:45 INFO]: Preparing level "world"
[13:25:45 INFO] [Arclight]: 注册了 0 个新的世界类型
[13:25:45 INFO] [Minecraft]: -------- World Settings For [world] --------
[13:25:45 INFO] [Minecraft]: Simulation Distance: 10
[13:25:45 INFO] [Minecraft]: Allow Zombie Pigmen to spawn from portal blocks: true
[13:25:45 INFO] [Minecraft]: Zombie Aggressive Towards Villager: true
[13:25:45 INFO] [Minecraft]: Mob Spawn Range: 6
[13:25:45 INFO] [Minecraft]: Arrow Despawn Rate: 1200 Trident Respawn Rate:1200
[13:25:45 INFO] [Minecraft]: Experience Merge Radius: 3.0
[13:25:45 INFO] [Minecraft]: Cactus Growth Modifier: 100%
[13:25:45 INFO] [Minecraft]: Cane Growth Modifier: 100%
[13:25:45 INFO] [Minecraft]: Melon Growth Modifier: 100%
[13:25:45 INFO] [Minecraft]: Mushroom Growth Modifier: 100%
[13:25:45 INFO] [Minecraft]: Pumpkin Growth Modifier: 100%
[13:25:45 INFO] [Minecraft]: Sapling Growth Modifier: 100%
[13:25:45 INFO] [Minecraft]: Beetroot Growth Modifier: 100%
[13:25:45 INFO] [Minecraft]: Carrot Growth Modifier: 100%
[13:25:45 INFO] [Minecraft]: Potato Growth Modifier: 100%
[13:25:45 INFO] [Minecraft]: Wheat Growth Modifier: 100%
[13:25:45 INFO] [Minecraft]: NetherWart Growth Modifier: 100%
[13:25:45 INFO] [Minecraft]: Vine Growth Modifier: 100%
[13:25:45 INFO] [Minecraft]: Cocoa Growth Modifier: 100%
[13:25:45 INFO] [Minecraft]: Bamboo Growth Modifier: 100%
[13:25:45 INFO] [Minecraft]: SweetBerry Growth Modifier: 100%
[13:25:45 INFO] [Minecraft]: Kelp Growth Modifier: 100%
[13:25:45 INFO] [Minecraft]: Entity Activation Range: An 32 / Mo 32 / Ra 48 / Mi 16 / Tiv true / Isa false
[13:25:45 INFO] [Minecraft]: Custom Map Seeds:  Village: 10387312 Desert: 14357617 Igloo: 14357618 Jungle: 14357619 Swamp: 14357620 Monument: 10387313 Ocean: 14357621 Shipwreck: 165745295 End City: 10387313 Slime: 987234911 Nether: 30084232 Mansion: 10387319 Fossil: 14357921 Portal: 34222645
[13:25:45 INFO] [Minecraft]: Hopper Transfer: 8 Hopper Check: 1 Hopper Amount: 1
[13:25:45 INFO] [Minecraft]: Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64
[13:25:45 INFO] [Minecraft]: Max TNT Explosions: 100
[13:25:45 INFO] [Minecraft]: Tile Max Tick Time: 50ms Entity max Tick Time: 50ms
[13:25:45 INFO] [Minecraft]: View Distance: 10
[13:25:45 INFO] [Minecraft]: Item Despawn Rate: 6000
[13:25:45 INFO] [Minecraft]: Item Merge Radius: 2.5
[13:25:45 INFO] [Minecraft]: Nerfing mobs spawned from spawners: false
[13:25:45 INFO] [Minecraft]: -------- World Settings For [world/DIM1] --------
[13:25:45 INFO] [Minecraft]: Simulation Distance: 10
[13:25:45 INFO] [Minecraft]: Allow Zombie Pigmen to spawn from portal blocks: true
[13:25:45 INFO] [Minecraft]: Zombie Aggressive Towards Villager: true
[13:25:45 INFO] [Minecraft]: Mob Spawn Range: 6
[13:25:45 INFO] [Minecraft]: Arrow Despawn Rate: 1200 Trident Respawn Rate:1200
[13:25:45 INFO] [Minecraft]: Experience Merge Radius: 3.0
[13:25:45 INFO] [Minecraft]: Cactus Growth Modifier: 100%
[13:25:45 INFO] [Minecraft]: Cane Growth Modifier: 100%
[13:25:45 INFO] [Minecraft]: Melon Growth Modifier: 100%
[13:25:45 INFO] [Minecraft]: Mushroom Growth Modifier: 100%
[13:25:45 INFO] [Minecraft]: Pumpkin Growth Modifier: 100%
[13:25:45 INFO] [Minecraft]: Sapling Growth Modifier: 100%
[13:25:45 INFO] [Minecraft]: Beetroot Growth Modifier: 100%
[13:25:45 INFO] [Minecraft]: Carrot Growth Modifier: 100%
[13:25:45 INFO] [Minecraft]: Potato Growth Modifier: 100%
[13:25:45 INFO] [Minecraft]: Wheat Growth Modifier: 100%
[13:25:45 INFO] [Minecraft]: NetherWart Growth Modifier: 100%
[13:25:45 INFO] [Minecraft]: Vine Growth Modifier: 100%
[13:25:45 INFO] [Minecraft]: Cocoa Growth Modifier: 100%
[13:25:45 INFO] [Minecraft]: Bamboo Growth Modifier: 100%
[13:25:45 INFO] [Minecraft]: SweetBerry Growth Modifier: 100%
[13:25:45 INFO] [Minecraft]: Kelp Growth Modifier: 100%
[13:25:45 INFO] [Minecraft]: Entity Activation Range: An 32 / Mo 32 / Ra 48 / Mi 16 / Tiv true / Isa false
[13:25:45 INFO] [Minecraft]: Custom Map Seeds:  Village: 10387312 Desert: 14357617 Igloo: 14357618 Jungle: 14357619 Swamp: 14357620 Monument: 10387313 Ocean: 14357621 Shipwreck: 165745295 End City: 10387313 Slime: 987234911 Nether: 30084232 Mansion: 10387319 Fossil: 14357921 Portal: 34222645
[13:25:45 INFO] [Minecraft]: Hopper Transfer: 8 Hopper Check: 1 Hopper Amount: 1
[13:25:45 INFO] [Minecraft]: Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64
[13:25:45 INFO] [Minecraft]: Max TNT Explosions: 100
[13:25:45 INFO] [Minecraft]: Tile Max Tick Time: 50ms Entity max Tick Time: 50ms
[13:25:45 INFO] [Minecraft]: View Distance: 10
[13:25:45 INFO] [Minecraft]: Item Despawn Rate: 6000
[13:25:45 INFO] [Minecraft]: Item Merge Radius: 2.5
[13:25:45 INFO] [Minecraft]: Nerfing mobs spawned from spawners: false
[13:25:46 INFO] [Minecraft]: -------- World Settings For [world/DIM-1] --------
[13:25:46 INFO] [Minecraft]: Simulation Distance: 10
[13:25:46 INFO] [Minecraft]: Allow Zombie Pigmen to spawn from portal blocks: true
[13:25:46 INFO] [Minecraft]: Zombie Aggressive Towards Villager: true
[13:25:46 INFO] [Minecraft]: Mob Spawn Range: 6
[13:25:46 INFO] [Minecraft]: Arrow Despawn Rate: 1200 Trident Respawn Rate:1200
[13:25:46 INFO] [Minecraft]: Experience Merge Radius: 3.0
[13:25:46 INFO] [Minecraft]: Cactus Growth Modifier: 100%
[13:25:46 INFO] [Minecraft]: Cane Growth Modifier: 100%
[13:25:46 INFO] [Minecraft]: Melon Growth Modifier: 100%
[13:25:46 INFO] [Minecraft]: Mushroom Growth Modifier: 100%
[13:25:46 INFO] [Minecraft]: Pumpkin Growth Modifier: 100%
[13:25:46 INFO] [Minecraft]: Sapling Growth Modifier: 100%
[13:25:46 INFO] [Minecraft]: Beetroot Growth Modifier: 100%
[13:25:46 INFO] [Minecraft]: Carrot Growth Modifier: 100%
[13:25:46 INFO] [Minecraft]: Potato Growth Modifier: 100%
[13:25:46 INFO] [Minecraft]: Wheat Growth Modifier: 100%
[13:25:46 INFO] [Minecraft]: NetherWart Growth Modifier: 100%
[13:25:46 INFO] [Minecraft]: Vine Growth Modifier: 100%
[13:25:46 INFO] [Minecraft]: Cocoa Growth Modifier: 100%
[13:25:46 INFO] [Minecraft]: Bamboo Growth Modifier: 100%
[13:25:46 INFO] [Minecraft]: SweetBerry Growth Modifier: 100%
[13:25:46 INFO] [Minecraft]: Kelp Growth Modifier: 100%
[13:25:46 INFO] [Minecraft]: Entity Activation Range: An 32 / Mo 32 / Ra 48 / Mi 16 / Tiv true / Isa false
[13:25:46 INFO] [Minecraft]: Custom Map Seeds:  Village: 10387312 Desert: 14357617 Igloo: 14357618 Jungle: 14357619 Swamp: 14357620 Monument: 10387313 Ocean: 14357621 Shipwreck: 165745295 End City: 10387313 Slime: 987234911 Nether: 30084232 Mansion: 10387319 Fossil: 14357921 Portal: 34222645
[13:25:46 INFO] [Minecraft]: Hopper Transfer: 8 Hopper Check: 1 Hopper Amount: 1
[13:25:46 INFO] [Minecraft]: Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64
[13:25:46 INFO] [Minecraft]: Max TNT Explosions: 100
[13:25:46 INFO] [Minecraft]: Tile Max Tick Time: 50ms Entity max Tick Time: 50ms
[13:25:46 INFO] [Minecraft]: View Distance: 10
[13:25:46 INFO] [Minecraft]: Item Despawn Rate: 6000
[13:25:46 INFO] [Minecraft]: Item Merge Radius: 2.5
[13:25:46 INFO] [Minecraft]: Nerfing mobs spawned from spawners: false
[13:25:46 INFO] [Minecraft]: Server permissions file permissions.yml is empty, ignoring it
[13:25:46 INFO]: Preparing start region for dimension minecraft:overworld
[13:25:46 INFO]: Preparing spawn area: 0%
[13:25:46 INFO]: Preparing spawn area: 0%
[13:25:47 INFO]: Preparing spawn area: 0%
[13:25:47 INFO]: Preparing spawn area: 0%
[13:25:48 INFO]: Preparing spawn area: 6%
[13:25:48 INFO]: Preparing spawn area: 28%
[13:25:49 INFO]: Preparing spawn area: 89%
[13:25:49 INFO]: Time elapsed: 3361 ms
[13:25:49 INFO]: Done (3.686s)! For help, type "help"
[13:25:49 INFO]: Successfully initialized permission handler forge:default_handler
[13:25:49 INFO] [Arclight]: Forwarding forge permission[forge:default_handler] to bukkit
> restart
[13:26:42 INFO] [STDOUT]: Attempting to restart with ./restart.sh
[13:26:42 INFO]: Stopping server
[13:26:42 INFO]: Saving players
[13:26:42 INFO]: Saving worlds
[13:26:43 INFO]: Saving chunks for level 'ServerLevel[world]'/minecraft:overworld
[13:26:43 INFO]: Saving chunks for level 'ServerLevel[world/DIM1]'/minecraft:the_end
[13:26:43 INFO]: Saving chunks for level 'ServerLevel[world/DIM-1]'/minecraft:the_nether

====================================================================================================if you excute /restart  from de client and not finish the proscess =====================
==================================================================================

[15:08:05 INFO]: TheJhoNY7 issued server command: /restart
[15:08:05 INFO] [STDOUT]: Attempting to restart with ./restart.sh
[15:08:05 INFO]: TheJhoNY7 lost connection: Server is restarting
[15:08:05 INFO]: TheJhoNY7 left the game.
[15:08:05 ERROR] [STDERR]: java.util.ConcurrentModificationException
[15:08:05 ERROR] [STDERR]:      at java.base/java.util.ArrayList$Itr.checkForComodification(ArrayList.java:1013)
[15:08:05 ERROR] [STDERR]:      at java.base/java.util.ArrayList$Itr.next(ArrayList.java:967)
[15:08:05 ERROR] [STDERR]:      at TRANSFORMER/arclight@1.18.2-1.0.6-7e754e7e/org.spigotmc.RestartCommand.restart(RestartCommand.java:57)
[15:08:05 ERROR] [STDERR]:      at TRANSFORMER/arclight@1.18.2-1.0.6-7e754e7e/org.spigotmc.RestartCommand.restart(RestartCommand.java:40)
[15:08:05 ERROR] [STDERR]:      at TRANSFORMER/arclight@1.18.2-1.0.6-7e754e7e/org.spigotmc.RestartCommand$1.run(RestartCommand.java:31)
[15:08:05 ERROR] [STDERR]:      at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.MinecraftServer.bridge$drainQueuedTasks(MinecraftServerMixin.java:2231)
[15:08:05 ERROR] [STDERR]:      at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.level.ServerChunkCache$MainThreadExecutor.m_7245_(ServerChunkCache_MainThreadExecutorMixin.java:640)
[15:08:05 ERROR] [STDERR]:      at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.level.ServerChunkCache.m_8466_(ServerChunkCacheMixin.java:266)
[15:08:05 ERROR] [STDERR]:      at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.MinecraftServer.m_129961_(MinecraftServerMixin.java:787)
[15:08:05 ERROR] [STDERR]:      at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.MinecraftServer.m_7245_(MinecraftServerMixin.java:776)
[15:08:05 ERROR] [STDERR]:      at TRANSFORMER/minecraft@1.18.2/net.minecraft.util.thread.BlockableEventLoop.m_18701_(BlockableEventLoop.java:140)
[15:08:05 ERROR] [STDERR]:      at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.MinecraftServer.m_130012_(MinecraftServerMixin.java:762)
[15:08:05 ERROR] [STDERR]:      at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.MinecraftServer.m_130011_(MinecraftServerMixin.java:2139)
[15:08:05 ERROR] [STDERR]:      at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.MinecraftServer.m_177918_(MinecraftServerMixin.java:261)
[15:08:05 ERROR] [STDERR]:      at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by IzzelAliz** [comment]
`/restart` is not a good way to restart your server. Use a restart script or `--restart=always` if you are using docker.
