### ISSUE TITLE
1.18.2 Error with PlayerRevive and similar mods or plugins.

### ISSUE THREAD

**Issue by kmo093** [IzzelAliz/Arclight#721]
### I have confirmed that ...

- [X] Arclight is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Forge

### Arclight version

arclight-forge-1.18.2-1.0.6.jar

### OS & Java versions

OS: Windows Server / Java 17

### Plugins and Mods

```raw
Plugins: AuthMe, WorldEdit, PlaceholderAPI, WorldGuard, SimpleClans, OfflineManager, UTitleAuth, RedProtect, WolfyUtilities, CustomCrafting
Mods: 
mods_folder YungsBetterDungeons-1.18.2-Forge-2.1.0.jar : betterdungeons (1.18.2-Forge-2.1.0) - 1
mods_folder UnionLib-1.18.2-7.2.0-Forge.jar : unionlib (7.2.0) - 1
mods_folder cgm-1.2.7-1.18.2.jar : cgm (1.2.7) - 1
mods_folder jei-1.18.2-9.7.1.255.jar : jei (9.7.1.255) - 1
mods_folder incontrol-1.18-6.0.15.jar : incontrol (1.18-6.0.15) - 1
mods_folder Satako-5.0.7-1.18.2.jar : satako (5.0.7-1.18.2) - 1
mods_folder LimitedLives-1.18-1.1.2.jar : limitedlives (1.1.2) - 1
mods_folder day_counter_v1.3_1.18.2_[FORGE].jar : ag_day_counter (1.3) - 1
mods_folder sophisticatedcore-1.18.2-0.5.9.115.jar : sophisticatedcore (1.18.2-0.5.9.115) - 1
mods_folder shutupexperimentalsettings-1.0.5.jar : shutupexperimentalsettings (1.0.5) - 1
mods_folder EnhancedVisuals_FORGE_v1.5.5_mc1.18.2.jar : enhancedvisuals (1.5.5) - 1
mods_folder comforts-forge-1.18.2-5.0.0.4.jar : comforts (1.18.2-5.0.0.4) - 1
mods_folder zombieawareness-1.18.1-1.12.3.jar : zombieawareness (1.18.1-1.12.3) - 1
mods_folder YungsApi-1.18.2-Forge-2.0.8.jar : yungsapi (1.18.2-Forge-2.0.8) - 1
mods_folder additional-guns-0.7.2-1.18.2.jar : additionalguns (0.7.2) - 1
mods_folder Bookshelf-Forge-1.18.2-13.2.50.jar : bookshelf (13.2.50) - 1
mods_folder BadMobs-1.18.2-13.01.jar : badmobs (13.01) - 1
mods_folder farsightedmobs-forge-1.1-1.18.jar : farsightedmobs (1.1) - 1
mods_folder sophisticatedbackpacks-1.18.2-3.18.24.704.jar : sophisticatedbackpacks (1.18.2-3.18.24.704) - 1
mods_folder The-Hordes-1.18.2-1.1.5a.jar : hordes (1.1.5a) - 1
mods_folder MineTraps-1.18.2-(v.2.1.4).jar : minetraps (2.1.4) - 1
mods_folder catalogue-1.6.2-1.18.2.jar : catalogue (1.6.2) - 1
mods_folder K-Turrets-1.1.10-1.18.2.jar : k_turrets (1.1.10-1.18.2) - 1
mods_folder firstaid-1.11.1.jar : firstaid (1.11.1) - 1
mods_folder AdvancementPlaques-1.18.2-1.4.5.1.jar : advancementplaques (1.4.5.1) - 1
mods_folder tenshilib-1.18.2-1.6.10-forge.jar : tenshilib (1.18.2-1.6.10) - 1
mods_folder FarmersDelight-1.18.2-1.1.2.jar : farmersdelight (1.18.2-1.1.2) - 1
mods_folder voicechat-forge-1.18.2-2.3.8.jar : voicechat (1.18.2-2.3.8) - 1
mods_folder soundphysics-forge-1.18.2-1.0.6.jar : sound_physics_remastered (1.18.2-1.0.6) - 1
mods_folder EnchantmentDescriptions-Forge-1.18.2-10.0.8.jar : enchdesc (10.0.8) - 1
mods_folder Menethis_s-Zombie-Apocalypse-Support-1.2.jar : menethis_zombie_apocalypse (1.2) - 1
mods_folder CreativeCore_FORGE_v2.6.15_mc1.18.2.jar : creativecore (0.0NONE) - 1
mods_folder YungsBridges-1.18.2-Forge-2.1.0.jar : yungsbridges (1.18.2-Forge-2.1.0) - 1
mods_folder betterfpsdist-1.18.2-1.5.jar : betterfpsdist (1.18.2-1.5) - 1
mods_folder easy_villagers-1.18.2-1.0.11.jar : easy_villagers (1.18.2-1.0.11) - 1
mods_folder Iceberg-1.18.2-1.0.44.jar : iceberg (1.0.44) - 1
mods_folder curios-forge-1.18.2-5.0.7.1.jar : curios (1.18.2-5.0.7.1) - 1
mods_folder Patchouli-1.18.2-71.1.jar : patchouli (1.18.2-71.1) - 1
mods_folder collective-1.18.2-4.50.jar : collective (4.50) - 1
mods_folder mobsunscreen-1.18.1-3.0.4.jar : mobsunscreen (1.18.1-3.0.4) - 1
mods_folder camera-1.18.2-1.0.2.jar : camera (1.18.2-1.0.2) - 1
mods_folder AutoRegLib-1.7-53.jar : autoreglib (1.7-53) - 1
mods_folder Quark-3.2-358.jar : quark (3.2-358) - 1
mods_folder lostcities-1.18-5.3.9.jar : lostcities (1.18-5.3.9) - 1
mods_folder Regrowth-1.18.2-1.40.0.31.jar : regrowth (1.18.2-1.40.0.31) - 1
mods_folder OfflineSkins-1.18.2-v2.jar : offlineskins (1.18.2-v2) - 1
mods_folder YungsBetterStrongholds-1.18.2-Forge-2.1.1.jar : betterstrongholds (1.18.2-Forge-2.1.1) - 1
mods_folder Atlas-Lib-1.18.2-1.1.5.jar : atlaslib (1.1.5) - 1
mods_folder Tiered-1.18.2-4.1.1-Forge.jar : tiered (1.18.2-4.1.1-Forge) - 1
mods_folder starterkit_1.18.2-3.2.jar : starterkit (3.2) - 1
mods_folder coroutil-1.18.1-1.2.37.jar : coroutil (1.18.1-1.2.37) - 1
mods_folder architectury-4.9.83-forge.jar : architectury (4.9.83) - 1
mods_folder ftb-library-forge-1802.3.6-build.140.jar : ftblibrary (1802.3.6-build.140) - 1
mods_folder ftb-teams-forge-1802.2.6-build.51.jar : ftbteams (1802.2.6-build.51) - 1
mods_folder ftb-chunks-forge-1802.3.6-build.160.jar : ftbchunks (1802.3.6-build.160) - 1
mods_folder lootr-1.18.2-0.2.20.57.jar : lootr (0.2.20.57) - 1
arclight arclight-1.18.2-1.0.6-7e754e7e.jar : arclight (1.18.2-1.0.6-7e754e7e) - 1
mods_folder framework-0.2.4-1.18.2.jar : framework (0.2.4) - 1
mods_folder sulfurpotassiummod-1.18.2-2.3.3+Forge.jar : sulfurpotassiummod (2.3.3) - 1
mods_folder improvedmobs-1.18.2-1.10.15-forge.jar : improvedmobs (1.18.2-1.10.15) - 1
mods_folder valhelsia_core-1.18.2-0.3.1.jar : valhelsia_core (1.18.2-0.3.1) - 1
mods_folder valhelsia_structures-forge-1.18.2-0.1.0.jar : valhelsia_structures (1.18.2-0.1.0) - 1
mods_folder DarkModeEverywhere-1.18.1-1.0.2.jar : darkmodeeverywhere (1.18.1-1.0.2) - 1
mods folder PlayerRevive_FORGE_v2.0.0_mc1.18.2.jar : playerrevive (1.18.2-2.0.0) - 1
```

### Description

With the mods and plugins mentioned above on my server, a problem arises and that is that when a player dies he is left bleeding thanks to a mod but the other player tries to raise him, he raises him by sacrificing part of his food bar and immediately he is raised again to be left in a state of bleeding.
This problem did not occur until I changed from the normal forge to the arclight, I searched for several alternatives with plugins and mods and the result was the same in all of them, when checking on the console I see that an error is generated whenever the player is lifted from the status of bleeding.
Multiple mods and plugins have been tested with mechanics to revive a falling player from death to "bleeding" and the same error persists on console, preventing the player from reviving.

### Step to reproduce

1- Server starts with everything previously named.
2- Two players enter
3- One of them commits suicide in various ways (falling, fighting, etc.)
4- The other player proceeds to approach the bleeding player
5- Press right click to revive the bleeding player
6- The bleeding player is revived and immediately falls back into the bleeding state

### Logs

[06Sep2022 21:31:03.016] [Server thread/WARN] [net.minecraft.network.chat.NbtComponent/]: Failed to parse component: 
java.lang.NullPointerException: Cannot invoke "net.minecraft.network.chat.Component.m_6879_()" because "p_130733_" is null
	at net.minecraft.network.chat.ComponentUtils.m_130731_(ComponentUtils.java:51) ~[server-1.18.2-20220404.173914-srg.jar%23129!/:?] {re:classloading}
	at net.minecraft.network.chat.NbtComponent.m_130967_(NbtComponent.java:300) ~[server-1.18.2-20220404.173914-srg.jar%23129!/:?] {re:classloading}
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:273) ~[?:?] {}
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?] {}
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625) ~[?:?] {}
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762) ~[?:?] {}
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276) ~[?:?] {}
	at java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411) ~[?:?] {}
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?] {}
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?] {}
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921) ~[?:?] {}
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?] {}
	at java.util.stream.ReferencePipeline.reduce(ReferencePipeline.java:662) ~[?:?] {}
	at net.minecraft.network.chat.NbtComponent.m_5638_(NbtComponent.java:306) ~[server-1.18.2-20220404.173914-srg.jar%23129!/:?] {re:classloading}
	at net.minecraft.network.chat.ComponentUtils.m_130731_(ComponentUtils.java:50) ~[server-1.18.2-20220404.173914-srg.jar%23129!/:?] {re:classloading}
	at net.minecraft.network.chat.ComponentUtils.m_130731_(ComponentUtils.java:54) ~[server-1.18.2-20220404.173914-srg.jar%23129!/:?] {re:classloading}
	at net.minecraft.world.level.block.entity.SignBlockEntity.m_155711_(SignBlockEntityMixin.java:111) ~[server-1.18.2-20220404.173914-srg.jar%23129!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:world.level.block.entity.SignBlockEntityMixin,pl:mixin:APP:bookshelf.common.mixins.json:block.entity.AccessorSignBlockEntity,pl:mixin:A}
	at net.minecraft.world.level.block.entity.SignBlockEntity.m_142466_(SignBlockEntityMixin.java:93) ~[server-1.18.2-20220404.173914-srg.jar%23129!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:world.level.block.entity.SignBlockEntityMixin,pl:mixin:APP:bookshelf.common.mixins.json:block.entity.AccessorSignBlockEntity,pl:mixin:A}
	at net.minecraft.server.commands.data.BlockDataAccessor.m_7603_(BlockDataAccessor.java:58) ~[server-1.18.2-20220404.173914-srg.jar%23129!/:?] {re:classloading}
	at net.minecraft.server.commands.data.DataCommands.m_139375_(DataCommands.java:256) ~[server-1.18.2-20220404.173914-srg.jar%23129!/:?] {re:classloading}
	at net.minecraft.server.commands.data.DataCommands.m_142800_(DataCommands.java:231) ~[server-1.18.2-20220404.173914-srg.jar%23129!/:?] {re:classloading}
	at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:263) ~[brigadier-1.0.18.jar%2325!/:?] {re:mixin,re:arclight_implementer}
	at net.minecraft.commands.CommandFunction$CommandEntry.m_164875_(CommandFunction.java:96) ~[server-1.18.2-20220404.173914-srg.jar%23129!/:?] {re:classloading}
	at net.minecraft.commands.CommandFunction$CommandEntry.m_142134_(CommandFunction.java:90) ~[server-1.18.2-20220404.173914-srg.jar%23129!/:?] {re:classloading}
	at net.minecraft.server.ServerFunctionManager$QueuedCommand.m_179985_(ServerFunctionManager.java:137) ~[server-1.18.2-20220404.173914-srg.jar%23129!/:?] {re:classloading}
	at net.minecraft.server.ServerFunctionManager$ExecutionContext.m_179977_(ServerFunctionManager.java:187) ~[server-1.18.2-20220404.173914-srg.jar%23129!/:?] {re:classloading}
	at net.minecraft.server.ServerFunctionManager.m_179960_(ServerFunctionManagerMixin.java:87) ~[server-1.18.2-20220404.173914-srg.jar%23129!/:?] {re:mixin,re:classloading,pl:mixin:APP:mixins.arclight.core.json:server.ServerFunctionManagerMixin,pl:mixin:A}
	at net.minecraft.server.ServerFunctionManager.m_136112_(ServerFunctionManagerMixin.java:71) ~[server-1.18.2-20220404.173914-srg.jar%23129!/:?] {re:mixin,re:classloading,pl:mixin:APP:mixins.arclight.core.json:server.ServerFunctionManagerMixin,pl:mixin:A}
	at net.minecraft.world.level.timers.FunctionCallback.m_82175_(FunctionCallback.java:18) ~[server-1.18.2-20220404.173914-srg.jar%23129!/:?] {re:classloading}
	at java.util.Optional.ifPresent(Optional.java:178) ~[?:?] {re:mixin,re:mixin}
	at net.minecraft.world.level.timers.FunctionCallback.m_5821_(FunctionCallback.java:18) ~[server-1.18.2-20220404.173914-srg.jar%23129!/:?] {re:classloading}
	at net.minecraft.world.level.timers.FunctionCallback.m_5821_(FunctionCallback.java:8) ~[server-1.18.2-20220404.173914-srg.jar%23129!/:?] {re:classloading}
	at net.minecraft.world.level.timers.TimerQueue.m_82256_(TimerQueue.java:82) ~[server-1.18.2-20220404.173914-srg.jar%23129!/:?] {re:classloading}
	at net.minecraft.server.level.ServerLevel.m_8809_(ServerLevelMixin.java:343) ~[server-1.18.2-20220404.173914-srg.jar%23129!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.level.ServerLevelMixin,pl:mixin:APP:zombieawareness.mixins.json:MixinPlaySound,pl:mixin:APP:zombieawareness.mixins.json:MixinLevelEvent,pl:mixin:APP:assets/sound_physics_remastered/sound_physics_remastered.mixins.json:ServerWorldMixin,pl:mixin:APP:mixins.arclight.impl.forge.optimization.json:activationrange.ServerWorldMixin_ActivationRange,pl:mixin:A,pl:arclight_implementer:async,pl:arclight_implementer:A,re:mixin,pl:accesstransformer:B}
	at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevelMixin.java:267) ~[server-1.18.2-20220404.173914-srg.jar%23129!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.level.ServerLevelMixin,pl:mixin:APP:zombieawareness.mixins.json:MixinPlaySound,pl:mixin:APP:zombieawareness.mixins.json:MixinLevelEvent,pl:mixin:APP:assets/sound_physics_remastered/sound_physics_remastered.mixins.json:ServerWorldMixin,pl:mixin:APP:mixins.arclight.impl.forge.optimization.json:activationrange.ServerWorldMixin_ActivationRange,pl:mixin:A,pl:arclight_implementer:async,pl:arclight_implementer:A,re:mixin,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServerMixin.java:902) ~[server-1.18.2-20220404.173914-srg.jar%23129!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServerMixin.java:326) ~[server-1.18.2-20220404.173914-srg.jar%23129!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.dedicated.DedicatedServerMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServerMixin.java:842) ~[server-1.18.2-20220404.173914-srg.jar%23129!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServerMixin.java:2135) ~[server-1.18.2-20220404.173914-srg.jar%23129!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServerMixin.java:261) ~[server-1.18.2-20220404.173914-srg.jar%23129!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:A}
	at java.lang.Thread.run(Thread.java:833) [?:?] {re:arclight_implementer,re:mixin,re:arclight_implementer,re:arclight_implementer,re:arclight_implementer,re:arclight_implementer,re:arclight_implementer,re:arclight_implementer}

**Comment by timi137137** [comment]
first,may be you can see template tips.
![image](https://user-images.githubusercontent.com/36812439/190903386-21cfdfed-36d3-449e-ac7d-aeb5d0693871.png)
and then, you should upload full log to me
