### ISSUE TITLE
应用能源2 导致无法启动.

### ISSUE THREAD

**Issue by Xing-C** [IzzelAliz/Arclight#772]
### 请确认您已完成以下几件事

- [X] 正在使用最新的 Arclight
- [X] 已为所有插件及模组安装依赖
- [X] 已为所有插件及模组更新至最新版
- [X] 不可在 Spigot 复现
- [X] 不可在 Forge 复现

### Arclight 版本

arclight-forge-1.19.2-1.0.0-SNAPSHOT.jar 已更换 forge-1.19.2-43.1.33

### Java 版本 | 操作系统

windows-server2022, zulu17.30.15-ca-jdk17.0.1 x64

### 相关 Mod/插件 的名称及版本

```raw
使用的模组 应用能源2
版本
appliedenergistics2-forge-12.8.2-beta.jar
并且已经尝试新版本
appliedenergistics2-12.7.0.jar
```

### 错误描述

启动服务器，生成世界的时候报错停止

### 复现步骤

安装模组后，删除原有world文件夹，启动服务器  -崩溃

### 报错信息

[00:43:14 INFO] [Minecraft]: Item Merge Radius: 2.5
[00:43:14 INFO] [Minecraft]: Item Despawn Rate: 6000
[00:43:14 INFO] [Minecraft]: Nerfing mobs spawned from spawners: false
[00:43:14 INFO] [Minecraft]: Server permissions file permissions.yml is empty, ignoring it
[00:43:14 ERROR]: Encountered an unexpected exception
java.lang.IllegalStateException: No level stem for dimension ae2:spatial_storage
        at net.minecraft.server.level.ServerLevel.handler$zci000$arclight$init(ServerLevelMixin.java:1840) ~[server-1.19.2-20220805.130853-srg.jar%23165!/:?]
        at net.minecraft.server.level.ServerLevel.<init>(ServerLevelMixin.java:232) ~[server-1.19.2-20220805.130853-srg.jar%23165!/:?]
        at net.minecraft.server.MinecraftServer.handler$zza000$injectSpatialLevel(MinecraftServerMixin.java:2607) ~[server-1.19.2-20220805.130853-srg.jar%23165!/:?]
        at net.minecraft.server.MinecraftServer.m_129815_(MinecraftServerMixin.java:375) ~[server-1.19.2-20220805.130853-srg.jar%23165!/:?]
        at net.minecraft.server.MinecraftServer.m_130006_(MinecraftServerMixin.java:300) ~[server-1.19.2-20220805.130853-srg.jar%23165!/:?]
        at net.minecraft.server.dedicated.DedicatedServer.m_7038_(DedicatedServerMixin.java:165) ~[server-1.19.2-20220805.130853-srg.jar%23165!/:?]
        at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServerMixin.java:2086) ~[server-1.19.2-20220805.130853-srg.jar%23165!/:?]
        at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServerMixin.java:244) ~[server-1.19.2-20220805.130853-srg.jar%23165!/:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
[00:43:15 FATAL]: Preparing crash report with UUID 08f72e16-fb23-4d6e-9993-27dd0150800d
[00:43:15 ERROR]: This crash report has been saved to: D:\MC-server\[0Test]gate\.\crash-reports\crash-2022-10-16_00.43.15-server.txt
[00:43:15 INFO]: Stopping server

详细崩溃日志:
[crash-2022-10-16_00.43.15-server.txt](https://github.com/IzzelAliz/Arclight/files/9792636/crash-2022-10-16_00.43.15-server.txt)

**Comment by Xing-C** [comment]
客户端正常运行，服务端尝试更换forge版本但问题依旧
forge-1.19.2-43.1.25
forge-1.19.2-43.1.33
forge-1.19.2-43.1.43

**Comment by Xing-C** [comment]
我需要帮助......
