### ISSUE TITLE
莫名重启 没有崩溃日志 有一项报错

### ISSUE THREAD

**Issue by ppo325** [IzzelAliz/Arclight#814]
### 请确认您已完成以下几件事

- [X] 正在使用最新的 Arclight
- [X] 已为所有插件及模组安装依赖
- [X] 已为所有插件及模组更新至最新版
- [X] 不可在 Spigot 复现
- [X] 不可在 Forge 复现

### Arclight 版本

arclight-forge-1.18.2-1.0.8-SNAPSHOT.jar

### Java 版本 | 操作系统

Windows Server 2022 Standard      java17

### 相关 Mod/插件 的名称及版本

```raw
Plugins (44): MiniMOTD, CratesPlus, LuckPerms, CrazyAuctionsPlus, OverallGamerule, JoinMessagePlus, UltimateStacker, ConsoleSpamFix, ProtocolLib, Notbuild, AllMusic, Yum, NBTAPI, PoetryGame, Vault, LagAssist, WorldEdit, Essentials, PlaceholderAPI, spark, IllegalStack, TrMenu, ItemCommand, LiteSignIn, TrChat, PuerkasMarriage, BanItem, MiaoBoard, NexEngine, PlayerParticles, CoreProtect, TitleManager, PlayerKits, DecentHolograms, IridiumSkyblock, ItemEdit, Multiverse-Core, PlayerTitle, BungeeTabListPlus, AuthMe, CMILib, Residence, ExcellentEnchants, ResProtection


模组列表：\n? mods_folder [机械动力：物品附加] create-stuff-additions1.18.2_v1.1.6.jar : create_stuff_additions (1.1.6) - 1\n? mods_folder [植物魔法全能工具] AIOTBotania-1.18.2-2.1.1.jar : aiotbotania (1.18.2-2.1.1) - 1\n? mods_folder jei-1.18.2-9.7.2.277.jar : jei (9.7.2.277) - 1\n? mods_folder [应用能源2] appliedenergistics2-11.1.3.jar : ae2 (11.1.3) - 1\n? mods_folder [懒人AE2 1.16+] lazierae2-1.18.2-3.0.2.jar : lazierae2 (3.0.2) - 1\n? mods_folder [拔刀剑] SlashBlade-1.18.2-0.0.8.jar : slashblade (0.0.8) - 1\n? mods_folder [无中生有：传承 - 植物魔法扩展] ExNaturae-1.18.2-2.0.0.jar : exnaturae (1.18.2-2.0.0) - 1\n? mods_folder [静谧四季／季节] SereneSeasons-1.18.2-7.0.0.15.jar : sereneseasons (0.0NONE) - 1\n? mods_folder LibX-1.18.2-3.2.18.jar : libx (1.18.2-3.2.18) - 1\n? mods_folder [机械动力甜食] create-confectionery1.18.2_v1.0.8.jar : create_confectionery (1.0.8) - 1\n? mods_folder lazydfu-1.0-1.18+.jar : lazydfu (0.1.3) - 1\n? mods_folder excompressum-forge-1.18.2-5.0.3.jar : excompressum (5.0.3) - 1\n? mods_folder balm-3.2.0+0.jar : balm (3.2.0+0) - 1\n? mods_folder [通用机械发电机] MekanismGenerators-1.18.2-10.2.4.464.jar : mekanismgenerators (10.2.4) - 1\n? mods_folder [更多磁盘] ExtraDisks-1.18.2-2.1.0.jar : extradisks (1.18.2-2.1.0) - 1\n? minecraft forge-1.18.2-40.1.80-universal.jar : forge (40.1.80) - 1\n? mods_folder ae2ao-6.0.0-1.18.1.jar : ae2ao (6.0.0-1.18.1) - 1\n? mods_folder [精致存储] refinedstorage-1.10.2.jar : refinedstorage (1.10.2) - 1\n? mods_folder [机械动力：奶茶店] createcafe-1.4-1.18.2.jar : createcafe (1.4-1.18.2) - 1\n? mods_folder [沉浸长杆] ImmersivePosts-1.18.2-4.3.0-3.jar : immersiveposts (4.3.0-3) - 1\n? mods_folder [神话植物学] MythicBotany-1.18.2-2.1.9.jar : mythicbotany (1.18.2-2.1.9) - 1\n? minecraft server-1.18.2-20220404.173914-srg.jar : minecraft (1.18.2) - 1\n? mods_folder [CoFH核心] cofh_core-1.18.2-1.6.4.21.jar : cofh_core (1.6.4.21) - 1\n? mods_folder [热力基本] thermal_foundation-1.18.2-1.6.3.28.jar : thermal (1.6.3.28) - 2\n? mods_folder [无中生有：传承 - 热力扩展] ExNihiloThermal-1.18.2-20220608-014416.jar : exnihilothermal (1.18.2-20220608-014416) - 1\n? mods_folder FarmersDelight-1.18.2-1.1.2.jar : farmersdelight (1.18.2-1.1.2) - 1\n? mods_folder [热力革新] thermal_innovation-1.18.2-1.6.3.12.jar : thermal_innovation (1.6.3.12) - 1\n? mods_folder [沉浸工程] ImmersiveEngineering-1.18.2-8.0.2-149.jar : immersiveengineering (1.18.2-8.0.2-149) - 1\n? mods_folder [通用机械附加] MekanismAdditions-1.18.2-10.2.4.464.jar : mekanismadditions (10.2.4) - 1\n? mods_folder AE2-Things-1.0.3-beta.jar : ae2things (1.0.3-beta) - 1\n? mods_folder [植物魔法]Botania-1.18.2-434.jar : botania (1.18.2-434) - 1\n? mods_folder [下界乐事] NethersDelight-1.18.2-2.2.0.jar : nethersdelight (2.2) - 1\n? mods_folder [妖怪之山通用库] mmlib-1.0.3-1.18.2.jar : mmlib (1.0.3-1.18.2) - 1\n? mods_folder FarmersRespite-1.18.2-1.2.0.jar : farmersrespite (1.18.1-1.2.0) - 1\n? mods_folder curios-forge-1.18.2-5.0.7.1.jar : curios (1.18.2-5.0.7.1) - 1\n? mods_folder [通用机械] Mekanism-1.18.2-10.2.4.464.jar : mekanism (10.2.4) - 1\n? mods_folder [无中生有：传承 - 通用机械扩展] ExNihiloMekanism-1.18.2-20220608-005057.jar : exnihilomekanism (1.18.2-20220608-005057) - 1\n? mods_folder [飞轮] flywheel-forge-1.18-0.6.2.jar : flywheel (1.18-0.6.2) - 1\n? mods_folder [机械动力] create-mc1.18.2_v0.4.1.jar : create (0.4.1) - 1\n? mods_folder Patchouli-1.18.2-71.1.jar : patchouli (1.18.2-71.1) - 1\n? mods_folder AE2-Additions-1.18.2-0.1.2.jar : ae2additions (1.18.2-0.1.1) - 1\n? mods_folder [热力农业] thermal_cultivation-1.18.2-1.6.3.11.jar : thermal_cultivation (1.6.3.11) - 1\n? mods_folder OreExcavation-1.10.162.jar : oreexcavation (1.10.162) - 1\n? mods_folder [热力膨胀] thermal_expansion-1.18.2-1.6.3.13.jar : thermal_expansion (1.6.3.13) - 1\n? mods_folder [热力基本] thermal_locomotion-1.18.2-1.6.3.8.jar : thermal_locomotion (1.6.3.8) - 1\n? mods_folder [通用机械工具] MekanismTools-1.18.2-10.2.4.464.jar : mekanismtools (10.2.4) - 1\n? mods_folder [玉米乐事] corn_delight-1.0.4-1.18.2.jar : corn_delight (1.0.4-1.18.2) - 1\n? mods_folder [Macaw的家具] mcw-furniture-3.0.0-mc1.18.2.jar : mcwfurnitures (3.0.0) - 1\n? arclight arclight-1.18.2-1.0.8-SNAPSHOT-715c0c9f.jar : arclight (1.18.2-1.0.8-SNAPSHOT-715c0c9f) - 1\n? mods_folder [精致存储附属] refinedstorageaddons-0.8.2.jar : refinedstorageaddons (0.8.2) - 1\n? mods_folder [无中生有：传承] ExNihiloSequentia-1.18.2-20220620-173540.jar : exnihilosequentia (1.18.2-20220620-173540) - 1\n? mods_folder [无中生有：传承 - 应用能源2扩展] ExNihiloAE-1.18.2-20220607-014628.jar : exnihiloae (1.18.2-20220607-014628) - 1\n? mods_folder [植物机械] BotanicalMachinery-1.18.2-1.0.1.jar : botanicalmachinery (1.18.2-1.0.1) - 1\n? mods_folder createaddition-1.18.2-20220517a.jar : createaddition (1.18.2-20220517a) - 1
```

### 错误描述

导致服务器重启  原因不明  没有崩溃日志

### 复现步骤

进游戏大概十分钟重启一次 没有崩溃日志  后台会出现一个报错  出现这个报错之后开始重启  我放在下面了

### 报错信息

 [21:07:14 ERROR]: Uncaught exception in server thread
java.lang.NullPointerException: Cannot invoke "java.lang.Thread.interrupt()" because "this.pump" is null
        at org.jline.terminal.impl.AbstractWindowsTerminal.close(AbstractWindowsTerminal.java:219) ~[jline-terminal-3.12.1.jar%2315!/:?]
        at net.minecrell.terminalconsole.TerminalConsoleAppender.close(TerminalConsoleAppender.java:282) ~[terminalconsoleappender-1.2.0.jar%2313!/:?]
        at net.minecraft.server.dedicated.DedicatedServer.handler$zem000$arclight$exitNow(DedicatedServerMixin.java:738) ~[server-1.18.2-20220404.173914-srg.jar%23122!/:?]
        at net.minecraft.server.dedicated.DedicatedServer.m_6988_(DedicatedServerMixin.java:323) ~[server-1.18.2-20220404.173914-srg.jar%23122!/:?]
        at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServerMixin.java:2187) ~[server-1.18.2-20220404.173914-srg.jar%23122!/:?]
        at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServerMixin.java:261) ~[server-1.18.2-20220404.173914-srg.jar%23122!/:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]

### 复现用压缩包下载链接(可选)

536666862 群文件 最新客户端

**Comment by IzzelAliz** [comment]
把日志发出来
