### ISSUE TITLE
StackOverflowError at ArclightReflectionHandler_5.redirectTypeGetName

### ISSUE THREAD

**Issue by ShirasawaSama** [IzzelAliz/Arclight#818]
### 请确认您已完成以下几件事

- [X] 正在使用最新的 Arclight
- [X] 已为所有插件及模组安装依赖
- [X] 已为所有插件及模组更新至最新版
- [X] 不可在 Spigot 复现
- [X] 不可在 Forge 复现

### Arclight 版本

arclight-1.19.2-1.0.0-7f496130

### Java 版本 | 操作系统

系统: Windows 11; Java: [LibericaJDK] openjdk version "18.0.2.1" 2022-08-18

### 相关 Mod/插件 的名称及版本

```raw
Plugins (2): Uniporter, NekoMaid

Mod List:
• minecraft server-1.19.2-20220805.130853-srg.jar : minecraft (1.19.2) - 1
• minecraft forge-1.19.2-43.1.3-universal.jar : forge (43.1.3) - 1
• arclight arclight-1.19.2-1.0.0-7f496130.jar : arclight (1.19.2-1.0.0-7f496130) - 1
```

### 错误描述

似乎是在尝试获取玩家列表时产生了报错:

目前还在排查具体的 API

### 复现步骤

1. 安装 NekoMaid
2. 尝试获取玩家列表
3. 报错产生

### 报错信息

```
[22:07:30 ERROR] [STDERR]: java.lang.StackOverflowError
[22:07:30 ERROR] [STDERR]:      at TRANSFORMER/arclight@1.19.2-1.0.0-7f496130/io.izzel.arclight.common.mod.util.remapper.generated.ArclightReflectionHandler_1.redirectTypeGetName(ArclightReflectionHandler.java:178)
[22:07:30 ERROR] [STDERR]:      at TRANSFORMER/arclight@1.19.2-1.0.0-7f496130/io.izzel.arclight.common.mod.util.remapper.generated.ArclightReflectionHandler_1.redirectTypeGetName(ArclightReflectionHandler.java:178)
[22:07:30 ERROR] [STDERR]:      at TRANSFORMER/arclight@1.19.2-1.0.0-7f496130/io.izzel.arclight.common.mod.util.remapper.generated.ArclightReflectionHandler_1.redirectTypeGetName(ArclightReflectionHandler.java:178)
[22:07:30 ERROR] [STDERR]:      at TRANSFORMER/arclight@1.19.2-1.0.0-7f496130/io.izzel.arclight.common.mod.util.remapper.generated.ArclightReflectionHandler_1.redirectTypeGetName(ArclightReflectionHandler.java:178)
[22:07:30 ERROR] [STDERR]:      at TRANSFORMER/arclight@1.19.2-1.0.0-7f496130/io.izzel.arclight.common.mod.util.remapper.generated.ArclightReflectionHandler_1.redirectTypeGetName(ArclightReflectionHandler.java:178)
...【以下均相同】
```

**Comment by ShirasawaSama** [comment]
看起来是

https://github.com/IzzelAliz/Arclight/blob/bdc85d38467f70fbe6f47c70a600c4ef28f03cf8/arclight-common/src/main/java/io/izzel/arclight/common/mod/util/remapper/generated/ArclightReflectionHandler.java#L178

这行应该为

```java
return redirectClassGetName(cl) + "[]";
```
