### ISSUE TITLE
Arclight will not launch on vault hunters 3 modpack 

### ISSUE THREAD

**Issue by Xplodin** [IzzelAliz/Arclight#824]
### I have confirmed that ...

- [X] Arclight is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Forge

### Arclight version

arclight-forge-1.18.2-1.0.8-SNAPSHOT-cb5cec1

### OS & Java versions

Ubuntu 20 and java 17

### Plugins and Mods

```raw
no plugins & Vault Hunters 3 modpack
was released today at: https://www.curseforge.com/minecraft/modpacks/vault-hunters-1-18-2
version 001
```

### Description

server fails to start with presumably custom mod made for the modpack

### Step to reproduce

install vault hunters
install arc
downgrade arclight to the modpacks forge version (40.1.61)

### Logs

https://gist.github.com/Xplodin/560870aaeb24c03772520d0bb377dd93

### Server pack link (Optional)

https://www.curseforge.com/minecraft/modpacks/vault-hunters-1-18-2/files/4119443

**Comment by Xplodin** [comment]
hey got a new issue:
I get internal server error when generating a new vault on the arclight vault hunters 3 modpack latest version 0.3
04:00:33 WARN]: Failed to handle packet for /47.147.55.195:53393
net.minecraft.ReportedException: Colliding entity with block
at net.minecraft.server.level.ServerPlayer.m_9240_(ServerPlayerMixin.java:502) ~[server-1.18.2-20220404.173914-srg.jar%23197!/:?]
at net.minecraft.server.network.ServerGamePacketListenerImpl.m_9933_(ServerPlayNetHandlerMixin.java:207) ~[server-1.18.2-20220404.173914-srg.jar%23197!/:?]
at net.minecraft.network.Connection.m_129483_(ConnectionMixin.java:245) ~[server-1.18.2-20220404.173914-srg.jar%23197!/:?]
at net.minecraft.server.network.ServerConnectionListener.m_9721_(ServerConnectionListener.java:143) ~[server-1.18.2-20220404.173914-srg.jar%23197!/:?]
at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServerMixin.java:916) ~[server-1.18.2-20220404.173914-srg.jar%23197!/:?]
at net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServerMixin.java:326) ~[server-1.18.2-20220404.173914-srg.jar%23197!/:?]
at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServerMixin.java:842) ~[server-1.18.2-20220404.173914-srg.jar%23197!/:?]
at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServerMixin.java:2135) ~[server-1.18.2-20220404.173914-srg.jar%23197!/:?]
at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServerMixin.java:261) ~[server-1.18.2-20220404.173914-srg.jar%23197!/:?]
at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.IllegalStateException: No level stem for dimension the_vault:vault_922c7362-b9bb-4419-8cd7-744c21702ced
at net.minecraft.server.level.ServerLevel.handler$znj000$arclight$init(ServerLevelMixin.java:1830) ~[server-1.18.2-20220404.173914-srg.jar%23197!/:?]
at net.minecraft.server.level.ServerLevel.<init>(ServerLevelMixin.java:228) ~[server-1.18.2-20220404.173914-srg.jar%23197!/:?]
at iskallia.vault.core.world.storage.VirtualWorld.<init>(VirtualWorld.java:43) ~[the_vault-1.18.2-2.0.10.873.jar%23183!/:1.18.2-2.0.10.873]
at iskallia.vault.core.world.storage.VirtualWorld.create(VirtualWorld.java:125) ~[the_vault-1.18.2-2.0.10.873.jar%23183!/:1.18.2-2.0.10.873]
at iskallia.vault.world.data.ServerVaults.add(ServerVaults.java:79) ~[the_vault-1.18.2-2.0.10.873.jar%23183!/:1.18.2-2.0.10.873]
at iskallia.vault.block.VaultPortalBlock.m_7892_(VaultPortalBlock.java:115) ~[the_vault-1.18.2-2.0.10.873.jar%23183!/:1.18.2-2.0.10.873]
at net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.m_60682_(BlockBehaviour_BlockStateBaseMixin.java:685) ~[server-1.18.2-20220404.173914-srg.jar%23197!/:?]
at net.minecraft.world.entity.Entity.m_20101_(EntityMixin.java:902) ~[server-1.18.2-20220404.173914-srg.jar%23197!/:?]
at net.minecraft.world.entity.Entity.m_146872_(EntityMixin.java:696) ~[server-1.18.2-20220404.173914-srg.jar%23197!/:?]
at net.minecraft.world.entity.Entity.m_6478_(EntityMixin.java:668) ~[server-1.18.2-20220404.173914-srg.jar%23197!/:?]
at net.minecraft.world.entity.LivingEntity.m_21074_(LivingEntityMixin.java:2155) ~[server-1.18.2-20220404.173914-srg.jar%23197!/:?]
at net.minecraft.world.entity.LivingEntity.m_7023_(LivingEntityMixin.java:2112) ~[server-1.18.2-20220404.173914-srg.jar%23197!/:?]
at net.minecraft.world.entity.player.Player.m_7023_(PlayerMixin.java:1404) ~[server-1.18.2-20220404.173914-srg.jar%23197!/:?]
at net.minecraft.world.entity.LivingEntity.m_8107_(LivingEntityMixin.java:2544) ~[server-1.18.2-20220404.173914-srg.jar%23197!/:?]
at net.minecraft.world.entity.player.Player.m_8107_(PlayerMixin.java:492) ~[server-1.18.2-20220404.173914-srg.jar%23197!/:?]
at net.minecraft.world.entity.LivingEntity.m_8119_(LivingEntityMixin.java:2253) ~[server-1.18.2-20220404.173914-srg.jar%23197!/:?]
at net.minecraft.world.entity.player.Player.m_8119_(PlayerMixin.java:235) ~[server-1.18.2-20220404.173914-srg.jar%23197!/:?]
at net.minecraft.server.level.ServerPlayer.m_9240_(ServerPlayerMixin.java:439) ~[server-1.18.2-20220404.173914-srg.jar%23197!/:?]
... 9 more
[04:00:33 INFO]: _Shiba_Tatsuya_ lost connection: Internal server error


Heavily appreciate the quick original fix though.
