### ISSUE TITLE
Module *name* reads more than one module named org.yaml.snakeyaml

### ISSUE THREAD

**Issue by lynxaradev** [IzzelAliz/Arclight#854]
### I have confirmed that ...

- [X] Arclight is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Forge

### Arclight version

arclight-forge-1.19.2-1.0.1

### OS & Java versions

Windows 10, Java 17

### Plugins and Mods

```raw
ATM 8 Server Pack
(unable to run the command, because server is not starting)
https://imgur.com/a/TcoW9t3
```

### Description

As soon as I start server, ArcLight returns an error to the random mod with the following crash info:

The name of the module is different every time (takes random mod):
```
[09:02:11 INFO]: Found 19 dependencies adding them to mods collection
java.lang.module.ResolutionException: Module naturalist reads more than one module named org.yaml.snakeyaml
        at java.base/java.lang.module.Resolver.resolveFail(Resolver.java:901)
        at java.base/java.lang.module.Resolver.checkExportSuppliers(Resolver.java:722)
        at java.base/java.lang.module.Resolver.finish(Resolver.java:380)
        at java.base/java.lang.module.Configuration.<init>(Configuration.java:140)
        at java.base/java.lang.module.Configuration.resolveAndBind(Configuration.java:494)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.ModuleLayerHandler.buildLayer(ModuleLayerHandler.java:75)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.TransformationServicesHandler.buildTransformingClassLoader(TransformationServicesHandler.java:60)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.Launcher.run(Launcher.java:104)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.Launcher.main(Launcher.java:77)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
        at MC-BOOTSTRAP/arclight.boot@1.19.2-1.0.1/io.izzel.arclight.boot.application.ApplicationBootstrap.accept(ApplicationBootstrap.java:41)
        at MC-BOOTSTRAP/arclight.boot@1.19.2-1.0.1/io.izzel.arclight.boot.application.ApplicationBootstrap.accept(ApplicationBootstrap.java:12)
        at cpw.mods.bootstraplauncher@1.1.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at io.izzel.arclight.boot.application.Main_Forge.main(Main_Forge.java:23)
        at io.izzel.arclight.server.Launcher.main(Launcher.java:18)
Fail to launch Arclight.
```

### Step to reproduce

1. Install ArcLight
2. Put mods and configs of ATM 8 into the folder
3. Install a Compatible Forge version to the ATM 8 modpack (1.19.2-43.1.55 instead of the 1.19.2-43.2.0)
4. Change 1.19.2-43.2.0 *.args files with 1.19.2-43.1.55 ones
5. Change old forge.jar to the new forge.jar
6. Start the server
7. Get the error on the very beginning of the server start process

### Logs

[latest.log](https://github.com/IzzelAliz/Arclight/files/10285450/latest.log)

### Server pack link (Optional)

https://www.curseforge.com/minecraft/modpacks/all-the-mods-8

**Comment by haarigerhans** [comment]
The way you install arclight in 1.19.2 is different that it is described on the arclight main page. If you create the server you just doubleclick the .jar file and after its installed you put the .jar file in the mod folder.
But anyways, I failed to get ATM 8 to work even if installed correctly. Maybe you have more luck

**Comment by MickgClone** [comment]
(I don't write on github alot, so sorry if anything is lacking)
I thought I would write what I found on here instead of making a new issue. (Unless you want me to do that)
(ATM8 1.0.8)
I was getting this same issue too, so I went ahead and started testing mods. It wasn't some pro way but I think I might've found it. Someone could test it cause I'm not sure if it's actually those 2 mods.
The mods in question are "**deepdarker**" and "**radon**". Radon caused an issue after removing deepdarker.
I should also say that I put "arclight" in the mods folder just to make life a bit more easier and it seems to work in there with the 1 plugin I have in there but once I tried to join the server, it crashed. Probably to do with the auth server stuff. 
There was the error "**Timed out waiting for world statistics**" and then there is "**Attempted to send a Plugin Message to a channel that was too large**". If anyone with an actual working server with it being able to connect to the auth servers, we might get some results.
Idk if it's important to say how I was running it but I was running the server in offline mode (Server can't connect to auth for some reason) and I'm running linux. Server is AMP by cubecoder.
I'll mess with it later. If I do somehow get some results, I'll update this.

E: I decided to launch it up with it being the server jar instead of putting it in the mods folder. Seems to be more stable like that but something still isn't working right. I can't join but I still suspect that to be a auth server issue.

EE: So, I looked a little at the "deepdarker" mod on github and someone did put an issue up 3 days ago. Idk why they didn't report here though. Here's a link to the issue: "**https://github.com/KyaniteMods/DeeperAndDarker/issues/126#issue-1529746370**"

**Comment by Etavioxy** [comment]
i just figured out this problem by changing forge version align to original modpack. See <https://github.com/IzzelAliz/Arclight/wiki/FAQ> in _I want to use a custom Forge version_ section

**Comment by LurgenAU** [comment]
@Etavioxy @MickgClone Are you able to share any further details on how you managed to get ATM8 to book under Arclight? I'm finding that even with a Forge update (following the instructions in the FAQ) I still hit the same `[blah] reads more than one module named org.yaml.snakeyaml` issue.

**Comment by MickgClone** [comment]
Wish I could help but honestly, my setup is strange, it seems. I'm not really playing this modpack anymore so I don't think I'll be diving more into this. Personally, I think this issue is gonna stick till it gets fixed, which it won't now, because it isn't on the list anymore. Maybe Etavioxy may have the solution for you. I did try setting up a new server with arclight but the modpack is stubborn as always. Seems to be a new problem. 
Running it either thru "mods" or "custom forge" just brings up their own errors. If you wanna test what could be causing the problem, I recommend just making a folder on your desktop and then make folder "batches" in that folder. You then grab the server pack from curseforge and then launch the server up once. You'll then take a certain amount of mods out of the mods folder and put them in their own folder "batch". If the server fails to launch because of a dependency, then add it back to the mods folder and..... you'll figure it out from there. I went thru this as well just to figure out what it was but I think it might be different this time.

If you end up not doing this then maybe someone else can report it. My stuff just doesn't work much anymore.
Anyways, not really a solution but maybe it'll be looked into one of these days...
Hope you find a solution!

**Comment by z3nth10n** [comment]
> The way you install arclight in 1.19.2 is different that it is described on the arclight main page. If you create the server you just doubleclick the .jar file and after its installed you put the .jar file in the mod folder. But anyways, I failed to get ATM 8 to work even if installed correctly. Maybe you have more luck

Where did you read that we need to move the arclight jar file into mods. I did it and this is what I get 
[debug.log](https://github.com/IzzelAliz/Arclight/files/13835996/debug.log)

If I try to execute as the README suggests:

![image](https://github.com/IzzelAliz/Arclight/assets/4929135/d11604cf-a639-43ac-a89b-7d245614d1e8)

The following error happens:

```
java.lang.module.ResolutionException: Modules org.fusesource.jansi and advancedbackups export package org.fusesource.jansi.internal to module morejs
        at java.base/java.lang.module.Resolver.resolveFail(Resolver.java:901)
        at java.base/java.lang.module.Resolver.failTwoSuppliers(Resolver.java:815)
        at java.base/java.lang.module.Resolver.checkExportSuppliers(Resolver.java:736)
        at java.base/java.lang.module.Resolver.finish(Resolver.java:380)
        at java.base/java.lang.module.Configuration.<init>(Configuration.java:140)
        at java.base/java.lang.module.Configuration.resolveAndBind(Configuration.java:494)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.ModuleLayerHandler.buildLayer(ModuleLayerHandler.java:75)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.TransformationServicesHandler.buildTransformingClassLoader(TransformationServicesHandler.java:60)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.Launcher.run(Launcher.java:104)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.Launcher.main(Launcher.java:77)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
        at MC-BOOTSTRAP/arclight.boot@1.19.2-1.0.3/io.izzel.arclight.boot.application.ApplicationBootstrap.accept(ApplicationBootstrap.java:41)
        at MC-BOOTSTRAP/arclight.boot@1.19.2-1.0.3/io.izzel.arclight.boot.application.ApplicationBootstrap.accept(ApplicationBootstrap.java:12)
        at cpw.mods.bootstraplauncher@1.1.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at io.izzel.arclight.boot.application.Main_Forge.main(Main_Forge.java:23)
        at io.izzel.arclight.server.Launcher.main(Launcher.java:18)
Fail to launch Arclight.
```

If I don't use any mod, there is no problem.

So, I'll need to do what @MickgClone suggested.

**Comment by MickgClone** [comment]
I just saw your message through email and now that I'm on here, I guess you were asking @haarigerhans for more help.
Just thought I'd write anyways. Read if ya want.

For the "putting it into mods folder" thing, I think I either saw it in the issues or I just attempted to try it and it just worked at that time.

The modpack has probably updated since then and things could've changed. As I'm not really into this modpack anymore and I already have a server running for my friends, I'd suggest running through what I did and then once you get it working, zoom in on those batch of mods to make sure which one doesn't work or which one does.

I felt like before I thought I would be wasting my time with going through the batches method but after going through everything, I tried it and realized I should've just tried that first. Though, it could be a different set of issues now depending on the modpack version.

I honestly just think that this probably won't work out because it seems that stuff is just conflicting somehow and now it not being on the list is also a problem too. Removing mods for it to work isn't really great as everyone needs the same mods as the server and reporting the issue to the conflicting mods page won't help either as they've probably already moved on from this version or they just wouldn't care about Arclight (I mean, they got their mod to worry about).

If you want to test, you can go for it but I'm gonna say you probably aren't gonna have a good time. If there was a way to change Arclight a little to make it work with other mods, I feel like we would've seen some solution but I'm not an expert on that.

One more thing, the "Modules org.fusesource.jansi and advancedbackups export package org.fusesource.jansi.internal to module morejs" error might point you to mods you think you can disable and may think everything would work after but you'll be in a loop of doing that. The errors could still be helpful but I wouldn't rely on them completely.
