### ISSUE TITLE
[1.19.2]独特的附魔导致无法启动服务器

### ISSUE THREAD

**Issue by JellyBubb1e** [IzzelAliz/Arclight#884]
### 请确认您已完成以下几件事

- [X] 正在使用最新的 Arclight
- [X] 已为所有插件及模组安装依赖
- [X] 已为所有插件及模组更新至最新版
- [X] 不可在 Spigot 复现
- [X] 不可在 Forge 复现

### Arclight 版本

arclight-forge-1.19.2-1.0.1.jar

### Java 版本 | 操作系统

系统：Windows 11 21H2|java version "18.0.1.1" 2022-04-22

### 相关 Mod/插件 的名称及版本

```raw
AutoRegLib-1.8.2-55.jar
blueprint-1.19.2-6.1.0.jar
citadel-2.1.1-1.19.jar
cloth-config-8.2.88-forge.jar
CreativeCore_FORGE_v2.9.3_mc1.19.2.jar
geckolib-forge-1.19-3.1.39.jar
LIST.TXT
moonlight-1.19.2-2.1.22-forge.jar
TerraBlender-forge-1.19.2-2.0.1.136.jar
WWOO-FORGE-3.1.9+1.19.x.jar
YungsApi-1.19.2-Forge-3.8.2.jar
YungsBetterOceanMonuments-1.19.2-Forge-2.1.0.jar
YungsExtras-1.19.2-Forge-3.1.0.jar
[Alex 的生物] alexsmobs-1.21.1.jar
[JEI物品管理器] jei-1.19.2-forge-11.5.0.297.jar
[MrCrayfish 的家具] cfm-7.0.0-pre34-1.19.jar
[Xaero的世界地图] XaerosWorldMap_1.28.7_Forge_1.19.1.jar
[Xaero的小地图] Xaeros_Minimap_22.17.0_Forge_1.19.1.jar
[YUNG的地牢优化] YungsBetterDungeons-1.19.2-Forge-3.2.2.jar
[YUNG的沙漠神殿优化] YungsBetterDesertTemples-1.19.2-Forge-2.2.1.jar
[YUNG的沼泽小屋优化] YungsBetterWitchHuts-1.19.2-Forge-2.1.0.jar
[YUNG的矿井优化] YungsBetterMineshafts-1.19.2-Forge-3.2.0.jar
[YUNG的要塞重制] YungsBetterStrongholds-1.19.2-Forge-3.2.0.jar
[丰富的生态] ecologics-forge-1.19.2-2.1.11.jar
[你将去的生物群系] Oh_The_Biomes_You'll_Go-forge-1.19.2-2.0.0.13.jar
[农夫乐事] FarmersDelight-1.19-1.2.0.jar
[夸克] Quark-3.3-377.jar
[帕秋莉手册] Patchouli-1.19.2-77.jar
[放大化下界] Amplified_Nether_v1.2.jar
[旅行者背包] TravelersBackpack-1.19.2-8.2.10.jar
[暮色森林] twilightforest-1.19.2-4.2.1468-universal.jar
[机械动力] create-1.19.2-0.5.0.g.jar
[残暴与掠夺] savage_and_ravage-1.19-5.0.2.jar
[沉浸式风化] immersive_weathering-1.19.2-1.2.5-forge.jar
[独特的附魔] Unique Enchantments-1.19.2-4.0.2.1.jar
[独特的附魔：基础] Unique Enchantments Base-1.19.2-3.0.2.1.jar
[独特的附魔：战斗扩展] Unique Enchantments Battle-1.19.2-3.0.2.jar
[独特的附魔：效用扩展] Unique Enchantments Utils-1.19.2-3.0.2.1.jar
[真实物理] physics-mod-2.9.4-mc-1.19.x-forge.jar
[结构变体] repurposed_structures_forge-6.3.8+1.19.2.jar
[苦力怕改革] creeperoverhaul-2.0.5-forge.jar
[警卫村民] guardvillagers-1.19.2-1.5.2.jar
[豆腐工艺重制版] TofuCraftReload-1.19.2-2.9.0.1.jar
[那不勒斯风味] neapolitan-1.19.2-4.0.2.jar
[风滚草] Tumbleweed-forge-1.19-0.5.1.jar
```

### 错误描述

在Arclight下无法启动，纯Forge倒是没这个问题。
有趣的是当我把独特的附魔及其附属单独抽出放在Arclight下单独跑是可以启动的。
但是我把它们和其他mods合并，就无法启动了。（其他mods是可以正常启动的）

### 复现步骤

1.将更多附魔及其附属与其他模组放在一起
2.启动服务器

### 报错信息

[debug-2.log](https://github.com/IzzelAliz/Arclight/files/10342146/debug-2.log)

### 复现用压缩包下载链接(可选)
https://1drv.ms/u/s!AndELBE7_df9gSQaxjk_CFbc7mGp?e=JJqERd
_No response_

**Comment by IzzelAliz** [comment]
Mod问题，反馈给作者

```
[041月2023 14:56:59.814] [modloading-worker-0/ERROR] [net.minecraftforge.fml.javafmlmod.FMLModContainer/LOADING]: Failed to create mod instance. ModID: uniqueutil, class uniqueeutils.UEUtils
java.lang.reflect.InvocationTargetException: null
	at jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:79) ~[?:?] {}
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?] {}
	at java.lang.reflect.Constructor.newInstance(Constructor.java:483) ~[?:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:68) ~[javafmllanguage-1.19.2-43.2.0.jar%23251!/:?] {}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:121) ~[fmlcore-1.19.2-43.2.0.jar%23250!/:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) [?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) [?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) [?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) [?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) [?:?] {re:computing_frames}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) [?:?] {re:computing_frames}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) [?:?] {}
Caused by: java.util.ConcurrentModificationException
	at java.util.HashMap.computeIfAbsent(HashMap.java:1221) ~[?:?] {re:mixin}
	at net.minecraftforge.registries.ForgeRegistry.bindDelegate(ForgeRegistry.java:555) ~[forge-1.19.2-43.2.0-universal.jar%23254!/:?] {re:classloading}
	at net.minecraftforge.registries.ForgeRegistry.add(ForgeRegistry.java:456) ~[forge-1.19.2-43.2.0-universal.jar%23254!/:?] {re:classloading}
	at net.minecraftforge.registries.ForgeRegistry.add(ForgeRegistry.java:399) ~[forge-1.19.2-43.2.0-universal.jar%23254!/:?] {re:classloading}
	at net.minecraftforge.registries.ForgeRegistry.register(ForgeRegistry.java:129) ~[forge-1.19.2-43.2.0-universal.jar%23254!/:?] {re:classloading}
	at uniquebase.api.BaseUEMod.init(BaseUEMod.java:69) ~[%5B独特的附魔：基础%5D%20Unique%20Enchantments%20Base-1.19.2-3.0.2.1.jar%23226!/:?] {re:classloading}
	at uniqueeutils.UEUtils.<init>(UEUtils.java:92) ~[%5B独特的附魔：效用扩展%5D%20Unique%20Enchantments%20Utils-1.19.2-3.0.2.1.jar%23228!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:67) ~[?:?] {}
	... 11 more
```
