### ISSUE TITLE
[1.19.2/1.19.3]第一次启动核心下载文件时超时

### ISSUE THREAD

**Issue by 5isyphus** [IzzelAliz/Arclight#909]
### I have confirmed that ...

- [X] Arclight is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Forge

### Arclight version

arclight-forge-1.19.3-1.0.2-SNAPSHOT

### OS & Java versions

openjdk version "18.0.2.1" 2022-08-18 OpenJDK Runtime Environment Temurin-18.0.2.1+1 (build 18.0.2.1+1) OpenJDK 64-Bit Server VM Temurin-18.0.2.1+1 (build 18.0.2.1+1, mixed mode, sharing)

### Plugins and Mods

```raw
无
```

### Description

报错提示超时 java.lang.RuntimeException: Timeout https://arclight.mcxk.net/net/minecraftforge/forge/1.19.3-44.0.5/forge-1.19.3-44.0.5-installer.jar

完整的信息如下
Downloading missing libraries ...
java.lang.RuntimeException: Timeout https://arclight.mcxk.net/net/minecraftforge/forge/1.19.3-44.0.5/forge-1.19.3-44.0.5-installer.jar
java.lang.RuntimeException: Timeout https://arclight.mcxk.net/net/minecraftforge/forge/1.19.3-44.0.5/forge-1.19.3-44.0.5-installer.jar
        at io.izzel.arclight.forgeinstaller.FileDownloader.get(FileDownloader.java:50)
        at io.izzel.arclight.forgeinstaller.FileDownloader.get(FileDownloader.java:25)
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
Fail to launch Arclight.

去年年底使用过arclight-forge-1.19.2-1.0.1版本，没出现过这个问题。这次使用该版本和上述版本，都出现了这个问题。

**Comment by Silver1666** [comment]
我也是这样，用的1.19.2的1.0.1的版本

**Comment by IzzelAliz** [comment]
已经好了

**Comment by 5isyphus** [comment]
> 
感谢

**Comment by SulfuricM** [comment]
又寄了
