### ISSUE TITLE
java.lang.RuntimeException: Timeout

### ISSUE THREAD

**Issue by bl4zek** [IzzelAliz/Arclight#914]
### I have confirmed that ...

- [X] Arclight is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Forge

### Arclight version

arclight-forge-1.18.2-1.0.7

### OS & Java versions

java 17.0.6 2023-01-17 LTS

### Plugins and Mods

```raw
Nothing
```

### Description

java.lang.RuntimeException: Timeout https://arclight.mcxk.net/net/minecraftforge/forge/1.18.2-40.1.80/forge-1.18.2-40.1.80-installer.jar
java.lang.RuntimeException: Timeout https://arclight.mcxk.net/net/minecraftforge/forge/1.18.2-40.1.80/forge-1.18.2-40.1.80-installer.jar
        at io.izzel.arclight.forgeinstaller.FileDownloader.get(FileDownloader.java:50)
        at io.izzel.arclight.forgeinstaller.FileDownloader.get(FileDownloader.java:25)
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
Fail to launch Arclight.
![imagen_2023-01-30_092404924](https://user-images.githubusercontent.com/48611299/215503408-429b1bb7-4952-4959-b22a-579a4a102416.png)

**Comment by bl4zek** [comment]
This problem because server is shuting or colapsed, I waiting
