### ISSUE TITLE
不支援MMOCore插件 進伺服器打出指令沒有回應

### ISSUE THREAD

**Issue by y511634a** [IzzelAliz/Arclight#932]
### 请确认您已完成以下几件事

- [X] 正在使用最新的 Arclight
- [X] 已为所有插件及模组安装依赖
- [X] 已为所有插件及模组更新至最新版
- [X] 不可在 Spigot 复现
- [X] 不可在 Forge 复现

### Arclight 版本

arclight-forge-1.19.2-1.0.1

### Java 版本 | 操作系统

java version "17.0.6" 2023-01-17 LTS

### 相关 Mod/插件 的名称及版本

```raw
MMOCore
```

### 错误描述

伺服器將MMOCore插件放入plugins後
進入伺服器後打出/mmocore , /rpg 指令沒有回應
打出其他有關MMOCore的指令都沒有回應
但我在伺服器後台看到己經加載了MMOCore插件

### 复现步骤

1.安裝MMOCore插件放到plugins

2.開伺服器,進伺服器後打指令沒有回應

3.己檢查伺服器後台加載了MMOCore插件

**Comment by IzzelAliz** [comment]
1.19.2已经不再维护，请在1.19.3测试是否修复

**Comment by y511634a** [comment]
> 1.19.2已經不再維護，請在1.19.3測試是否修復

測試過了 1.19.3一樣都是這樣

**Comment by y511634a** [comment]
[16:17:50 ERROR] [Minecraft]: Could not pass event BlockBreakEvent to MMOCore v1.11.1
org.bukkit.event.EventException: null
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[arclight-1.19.3-1.0.2-98f5a183.jar%23161!/:arclight-1.19.3-1.0.2-98f5a183]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[arclight-1.19.3-1.0.2-98f5a183.jar%23161!/:arclight-1.19.3-1.0.2-98f5a183]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[arclight-1.19.3-1.0.2-98f5a183.jar%23161!/:arclight-1.19.3-1.0.2-98f5a183]
        at io.izzel.arclight.common.mod.server.event.BlockBreakEventDispatcher.onBreakBlock(BlockBreakEventDispatcher.java:30) ~[arclight-1.19.3-1.0.2-98f5a183.jar%23161!/:arclight-1.19.3-1.0.2-98f5a183]
        at io.izzel.arclight.common.mod.server.event.__BlockBreakEventDispatcher_onBreakBlock_BreakEvent.invoke(.dynamic) ~[arclight-1.19.3-1.0.2-98f5a183.jar%23161!/:arclight-1.19.3-1.0.2-98f5a183]
        at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73) ~[eventbus-6.0.3.jar%2385!/:?]
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.3.jar%2385!/:?]
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.3.jar%2385!/:?]
        at net.minecraftforge.common.ForgeHooks.onBlockBreakEvent(ForgeHooksMixin.java:536) ~[forge-1.19.3-44.1.8-universal.jar%23168!/:?]
        at net.minecraft.server.level.ServerPlayerGameMode.m_9280_(ServerPlayerGameModeMixin.java:229) ~[server-1.19.3-20221207.122022-srg.jar%23163!/:?]
        at net.minecraft.server.level.ServerPlayerGameMode.m_7712_(ServerPlayerGameModeMixin.java:95) ~[server-1.19.3-20221207.122022-srg.jar%23163!/:?]
        at net.minecraft.server.level.ServerPlayer.m_8119_(ServerPlayerMixin.java:423) ~[server-1.19.3-20221207.122022-srg.jar%23163!/:?]
        at net.minecraft.server.level.ServerLevel.m_8647_(ServerLevelMixin.java:675) ~[server-1.19.3-20221207.122022-srg.jar%23163!/:?]
        at net.minecraft.world.level.Level.m_46653_(LevelMixin.java:479) ~[server-1.19.3-20221207.122022-srg.jar%23163!/:?]
        at net.minecraft.server.level.ServerLevel.m_184063_(ServerLevelMixin.java:327) ~[server-1.19.3-20221207.122022-srg.jar%23163!/:?]
        at net.minecraft.world.level.entity.EntityTickList.m_156910_(EntityTickList.java:54) ~[server-1.19.3-20221207.122022-srg.jar%23163!/:?]
        at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevelMixin.java:307) ~[server-1.19.3-20221207.122022-srg.jar%23163!/:?]
        at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServerMixin.java:876) ~[server-1.19.3-20221207.122022-srg.jar%23163!/:?]
        at net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServerMixin.java:273) ~[server-1.19.3-20221207.122022-srg.jar%23163!/:?]
        at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServerMixin.java:816) ~[server-1.19.3-20221207.122022-srg.jar%23163!/:?]
        at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServerMixin.java:2057) ~[server-1.19.3-20221207.122022-srg.jar%23163!/:?]
        at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServerMixin.java:251) ~[server-1.19.3-20221207.122022-srg.jar%23163!/:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.NullPointerException: Player data is not loaded
        at java.util.Objects.requireNonNull(Objects.java:233) ~[?:?]
        at net.Indyuce.mmocore.manager.data.PlayerDataManager.get(PlayerDataManager.java:35) ~[?:?]
        at net.Indyuce.mmocore.api.player.PlayerData.get(PlayerData.java:1226) ~[?:?]
        at net.Indyuce.mmocore.api.player.PlayerData.get(PlayerData.java:1222) ~[?:?]
        at net.Indyuce.mmocore.experience.source.MineBlockExperienceSource$1.a(MineBlockExperienceSource.java:49) ~[?:?]        ... 23 more

**Comment by y511634a** [comment]
> 1.19.2已經不再維護，請在1.19.3測試是否修復

測試過CatServer和Mohist同樣結果還是不行 於遊戲沒有回應 但伺服器己加載插件
但於Spigot(沒mod)測試就沒問題可以正常運作

**Comment by y511634a** [comment]
> 

血量介面GUI有效 , 但指令同樣無效無回應
還有能不能順便幫我修復1.19.2的版本?
因為我之後的伺服器都是開1.19.2版本

**Comment by y511634a** [comment]
> 1.19.2已经不再维护，请在1.19.3测试是否修复

修復了 現在指令能用了
可不可以順便幫我修復1.19.2的版本?
因為我的伺服器是以1.19.2作構建 感謝你

**Comment by IzzelAliz** [comment]
1.19.2不再维护
