### ISSUE TITLE
RemappingURLClassLoader attempts to re-define `java.*` packages

### ISSUE THREAD

**Issue by LooFifteen** [IzzelAliz/Arclight#949]
### I have confirmed that ...

- [X] Arclight is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Forge

### Arclight version

arclight-1.16.5-1.0.25-SNAPSHOT-c7a91c51

### OS & Java versions

Eclipse Temurin 8, 11 and 17

### Plugins and Mods

```raw
UltraStaffChatPro (https://github.com/ChameleonFramework/Chameleon)
```

### Description

When using reflection to access an internal `java.*` class, [RemappingURLClassLoader attempts to relocate it](https://github.com/IzzelAliz/Arclight/blob/07a3fd1b5dace2bc4cb33fdf471c2af5af585bc1/arclight-common/src/main/java/io/izzel/arclight/common/mod/util/remapper/generated/RemappingURLClassLoader.java). This is not admirable as it causes a Java security stacktrace:
```
Caused by: java.lang.SecurityException: Prohibited package name: java.util
        at java.lang.ClassLoader.preDefineClass(ClassLoader.java:655) ~[?:1.8.0_332] {}
        at java.lang.ClassLoader.defineClass(ClassLoader.java:754) ~[?:1.8.0_332] {}
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[?:1.8.0_332] {}
        at io.izzel.arclight.common.mod.util.remapper.generated.RemappingURLClassLoader.findClass(RemappingURLClassLoader.java:88) ~[server.jar:arclight-1.16.5-1.0.25-SNAPSHOT-c7a91c51] {re:mixin,re:classloading}
        at dev.hypera.ultrastaffchatpro.lib.dragonfly.loading.DragonflyClassLoader.loadClass(DragonflyClassLoader.java) ~[?:?] {re:classloading}
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_332] {}
        at java.lang.Class.getDeclaredConstructors0(Native Method) ~[?:1.8.0_332] {}
        at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671) ~[?:1.8.0_332] {}
        at java.lang.Class.getConstructor0(Class.java:3075) ~[?:1.8.0_332] {}
        at java.lang.Class.getDeclaredConstructor(Class.java:2178) ~[?:1.8.0_332] {}
```
My initial idea of a fix will be to prohibit internal Java packages from being re-defined and return the existing loaded class instead. Although, reality may not be as simple.

### Step to reproduce

1. Use a Bukkit/Spigot plugin to `ClassLoader#loadClass("java.util")`
a. This can be also be done using a library similar to [Dragonfly](https://github.com/HyperaDev/Dragonfly).
2. Profit

### Logs

https://pastes.dev/cbll7ctcML

**Comment by LooFifteen** [comment]
This issue still occurs.
